Starburst: include/accelerator/accelerator.h File Reference
include/accelerator/accelerator.h File Reference
#include <accelerator/acc_types.h>
#include <sys/io.h>
Defines
#define RINGSHELL_CFG_ACK 0
#define RINGSHELL_CFG_FWD 1
#define RINGSHELL_ACC_CFG 4
#define ASSERT_CONCAT_(a, b) a##b
#define ASSERT_CONCAT(a, b) ASSERT_CONCAT_(a, b)
#define ct_assert(e) enum { ASSERT_CONCAT(assert_line_, __LINE__) = 1/(!!(e)) }
#define ring_assert(check,...) if(!(check)) { printf("Ring Stream Setup Error:" __VA_ARGS__); abort(); }
#define ring_assert_accelerator(acc, name)
Functions
ct_assert (sizeof(accelerator_t)==4)
void ring_printall ()
accelerator_t * ring_get_layout ()
int ring_get_layout_size ()
accelerator_t * ring_get_by_type (int core, int subcore)
accelerator_t * ring_get_accelerator (int cpu, int type)
Get the nearest accelerator of the specified type.
accelerator_t * ring_get_fsl (int cpu)
accelerator_t * ring_get_cpu (int cpu)
accelerator_t * ring_get_core (int cpu)
int ring_stream_setup (accelerator_t *dst, accelerator_t *src)
char ring_lookup_type (const char *type_name)
Map the identifier from the XML to the accelerator ID.
Variables
static const uint32_t _ring_layout_size = *(uint32_t *)IO_RINGMAP_LEN
static accelerator_t * _ring_layout = (accelerator_t *)IO_RINGMAP
Define Documentation
#define ASSERT_CONCAT (a, b) ASSERT_CONCAT_(a, b)
Definition at line 24 of file accelerator.h.
#define ASSERT_CONCAT_ (a, b) a##b
Definition at line 23 of file accelerator.h.
#define ct_assert (e) enum { ASSERT_CONCAT(assert_line_, __LINE__) = 1/(!!(e)) }
Definition at line 25 of file accelerator.h.
#define ring_assert (check, ...) if(!(check)) { printf("Ring Stream Setup Error:" __VA_ARGS__); abort(); }
Definition at line 130 of file accelerator.h.
#define ring_assert_accelerator (acc, name)
Value:
{\
            ring_assert(acc != NULL, "passed NULL for " name); \
            ring_assert(acc->type >= 0 && acc->type < ACC_MAX, "invalid accelerator type specified in " name ": %i\n", acc->type); \
            ring_assert(acc->core >= 0 && acc->core < NUM_PROCESSORS, "invalid cpu number specified in " name ": %i\n", acc->core); \
            ring_assert(acc->subcore >= 0 && acc->subcore < 8, "invalid subcore in " name ": %i\n", acc->subcore); \
            }
Definition at line 131 of file accelerator.h.
Referenced by ring_stream_setup().
#define RINGSHELL_ACC_CFG 4
Definition at line 19 of file accelerator.h.
#define RINGSHELL_CFG_ACK 0
Definition at line 17 of file accelerator.h.
Referenced by ring_stream_setup().
#define RINGSHELL_CFG_FWD 1
Definition at line 18 of file accelerator.h.
Referenced by ring_stream_setup().
Function Documentation
ct_assert (sizeof(accelerator_t) = =4)
accelerator_t* ring_get_accelerator (int cpu, int type) [inline]
Get the nearest accelerator of the specified type.
TODO: Perhaps we should have a 'lock' on accelerators until multiplexing is implemented
Parameters:
cpu Core ID to determine the 'nearest' accelerator of the requested type
type The accelerator type to fetch
Returns:
Pointer to the accelerator struct or NULL if none is found/available
Definition at line 83 of file accelerator.h.
References _ring_layout_size, ACC_MAX, and core.
Referenced by ring_get_core().
accelerator_t* ring_get_by_type (int core, int subcore) [inline]
Definition at line 65 of file accelerator.h.
References _ring_layout_size, ACC_CORE, and ACC_CORE_FSL.
accelerator_t* ring_get_core (int cpu) [inline]
Definition at line 120 of file accelerator.h.
References ACC_CORE, ring_get_accelerator(), and ring_get_fsl().
accelerator_t* ring_get_cpu (int cpu) [inline]
Definition at line 111 of file accelerator.h.
References _ring_layout_size, ACC_CORE, and core.
accelerator_t* ring_get_fsl (int cpu) [inline]
Definition at line 102 of file accelerator.h.
References _ring_layout_size, ACC_CORE_FSL, and core.
Referenced by ring_get_core().
accelerator_t* ring_get_layout () [inline]
Definition at line 50 of file accelerator.h.
References _ring_layout.
int ring_get_layout_size () [inline]
Definition at line 54 of file accelerator.h.
References _ring_layout_size.
char ring_lookup_type (const char * type_name) [inline]
Map the identifier from the XML to the accelerator ID.
Definition at line 193 of file accelerator.h.
References _acc_types, ACC_MAX, and ACC_UNKNOWN.
void ring_printall () [inline]
Definition at line 32 of file accelerator.h.
References _acc_names, _ring_layout_size, abort(), ACC_UNKNOWN, core, and accelerator_t::type.
int ring_stream_setup (accelerator_t * dst, accelerator_t * src) [inline]
Definition at line 138 of file accelerator.h.
References _acc_names, abort(), ACC_CORE, ACC_CORE_FSL, accelerator_t::core, MAKE_NOC_ACCE_CONFIG_PTR, MAKE_NOC_ACCE_PTR, MAKE_NOC_CORE_CONFIG_PTR, MAKE_NOC_FSL_CONFIG_PTR, MAKE_NOC_FSL_PTR, ring_assert_accelerator, RINGSHELL_CFG_ACK, RINGSHELL_CFG_FWD, accelerator_t::subcore, and accelerator_t::type.
Variable Documentation
accelerator_t* _ring_layout = (accelerator_t *)IO_RINGMAP [static]
Definition at line 30 of file accelerator.h.
Referenced by ring_get_layout().
const uint32_t _ring_layout_size = *(uint32_t *)IO_RINGMAP_LEN [static]
Definition at line 29 of file accelerator.h.
Referenced by ring_get_accelerator(), ring_get_by_type(), ring_get_cpu(), ring_get_fsl(), ring_get_layout_size(), and ring_printall().