Starburst: bitshark/adc.cc File Reference
bitshark/adc.cc File Reference
#include <stdlib.h>
#include <stdio.h>
#include <sys/api.h>
#include <bitshark/spi.h>
#include <bitshark/bitshark.h>
#include <unistd.h>
Defines
#define verb(...) printf(__VA_ARGS__)
Functions
int adc_reset ()
void adc_init_spi ()
Internal function: set the XPS SPI controller to the correct settings (cpha=0, cpol=0) and drive the Slave Select high to disable communication.
int adc_init ()
Initialize the ADC for use.
Define Documentation
#define verb (...) printf(__VA_ARGS__)
Definition at line 16 of file adc.cc.
Referenced by adc_init().
Function Documentation
int adc_init ()
Initialize the ADC for use.
Details: we reset the on-board XPS SPI controller and program it for use with the ADC. Next, we reset the ADC and then program it for use with the Bitshark LVDS driver. After programming we verify the settings on the ADC to make sure programming worked.
Note: the SPI controller seems quite unreliable: sending commands too fast or right after resets might not work, locking up the driver. Hence all the waiting during the init.
Definition at line 80 of file adc.cc.
References adc_init_spi(), cmd, data, spi_reset(), spi_transfer(), usleep(), and verb.
Referenced by bitshark_init().
void adc_init_spi ()
Internal function: set the XPS SPI controller to the correct settings (cpha=0, cpol=0) and drive the Slave Select high to disable communication.
We also set the master inhibit high to prevent communication at this point.
Definition at line 36 of file adc.cc.
References bsprintf, spireg_spicr_t::cpha, spireg_spicr_t::cpol, spireg_spicr_t::loop, spireg_spicr_t::lsb_first, spireg_spicr_t::master, spireg_spicr_t::mssae, spireg_spicr_t::mti, spireg_spicr_t::spe, spi_get_cr, spi_set_cr, XPS_SPI_SPISSR, and XPS_SPI_SS_REG.
Referenced by adc_init().
int adc_reset ()
Definition at line 21 of file adc.cc.
References adc_reset(), and spi_transfer().
Referenced by adc_reset().