var annotated =
[
    [ "__attribute__", "struct____attribute____.html", "struct____attribute____" ],
    [ "_devinfo_t", "struct__devinfo__t.html", "struct__devinfo__t" ],
    [ "_fd2q_t", "struct__fd2q__t.html", "struct__fd2q__t" ],
    [ "_lck_daemon_lock_t", "struct__lck__daemon__lock__t.html", "struct__lck__daemon__lock__t" ],
    [ "_lck_my_lock_t", "struct__lck__my__lock__t.html", "struct__lck__my__lock__t" ],
    [ "_le_t", "struct__le__t.html", "struct__le__t" ],
    [ "_linfs_t", "struct__linfs__t.html", "struct__linfs__t" ],
    [ "_noc_addr_t", "union__noc__addr__t.html", "union__noc__addr__t" ],
    [ "_prf_mb_t", "struct__prf__mb__t.html", "struct__prf__mb__t" ],
    [ "_prf_mem_t", "struct__prf__mem__t.html", "struct__prf__mem__t" ],
    [ "_proc_table_t", "struct__proc__table__t.html", "struct__proc__table__t" ],
    [ "_timer_event_t", "struct__timer__event__t.html", "struct__timer__event__t" ],
    [ "Accelerator", "classAccelerator.html", "classAccelerator" ],
    [ "accelerator_t", "unionaccelerator__t.html", "unionaccelerator__t" ],
    [ "accList", "structaccList.html", "structaccList" ],
    [ "AccList", "classAccList.html", "classAccList" ],
    [ "auto_ret< T, ok >", "classauto__ret.html", "classauto__ret" ],
    [ "PMC_NS::Backend< T, B >", "classPMC__NS_1_1Backend.html", null ],
    [ "bitshark_ctrl_dev_t", "structbitshark__ctrl__dev__t.html", "structbitshark__ctrl__dev__t" ],
    [ "bitshark_dev_t", "structbitshark__dev__t.html", "structbitshark__dev__t" ],
    [ "CFifo< T, access >", "classCFifo.html", "classCFifo" ],
    [ "CFifo< T, CFifo<>::r >", "classCFifo_3_01T_00_01CFifo_3_4_1_1r_01_4.html", "classCFifo_3_01T_00_01CFifo_3_4_1_1r_01_4" ],
    [ "CFifo< T, CFifo<>::w >", "classCFifo_3_01T_00_01CFifo_3_4_1_1w_01_4.html", "classCFifo_3_01T_00_01CFifo_3_4_1_1w_01_4" ],
    [ "Cfifo_sink< Type >", "classCfifo__sink.html", "classCfifo__sink" ],
    [ "Cfifo_source< Type >", "classCfifo__source.html", "classCfifo__source" ],
    [ "CFifoPtr< T >", "classCFifoPtr.html", "classCFifoPtr" ],
    [ "CFifoPtr_ref< T >", "structCFifoPtr__ref.html", "structCFifoPtr__ref" ],
    [ "channel_t", "structchannel__t.html", "structchannel__t" ],
    [ "clean_type< T >", "structclean__type.html", "structclean__type" ],
    [ "clean_type< const T & >", "structclean__type_3_01const_01T_01_6_01_4.html", "structclean__type_3_01const_01T_01_6_01_4" ],
    [ "clean_type< const T * >", "structclean__type_3_01const_01T_01_5_01_4.html", "structclean__type_3_01const_01T_01_5_01_4" ],
    [ "clean_type< const T >", "structclean__type_3_01const_01T_01_4.html", "structclean__type_3_01const_01T_01_4" ],
    [ "clean_type< const volatile T & >", "structclean__type_3_01const_01volatile_01T_01_6_01_4.html", "structclean__type_3_01const_01volatile_01T_01_6_01_4" ],
    [ "clean_type< const volatile T * >", "structclean__type_3_01const_01volatile_01T_01_5_01_4.html", "structclean__type_3_01const_01volatile_01T_01_5_01_4" ],
    [ "clean_type< const volatile T >", "structclean__type_3_01const_01volatile_01T_01_4.html", "structclean__type_3_01const_01volatile_01T_01_4" ],
    [ "clean_type< T & >", "structclean__type_3_01T_01_6_01_4.html", "structclean__type_3_01T_01_6_01_4" ],
    [ "clean_type< volatile T & >", "structclean__type_3_01volatile_01T_01_6_01_4.html", "structclean__type_3_01volatile_01T_01_6_01_4" ],
    [ "clean_type< volatile T * >", "structclean__type_3_01volatile_01T_01_5_01_4.html", "structclean__type_3_01volatile_01T_01_5_01_4" ],
    [ "clean_type< volatile T >", "structclean__type_3_01volatile_01T_01_4.html", "structclean__type_3_01volatile_01T_01_4" ],
    [ "complex_t", "structcomplex__t.html", "structcomplex__t" ],
    [ "ConArbiter", "structConArbiter.html", "structConArbiter" ],
    [ "coordinate_t", "structcoordinate__t.html", "structcoordinate__t" ],
    [ "cordic_regmap_t", "structcordic__regmap__t.html", "structcordic__regmap__t" ],
    [ "CordicMix", "classCordicMix.html", "classCordicMix" ],
    [ "CordicQuad", "classCordicQuad.html", "classCordicQuad" ],
    [ "Core", "classCore.html", "classCore" ],
    [ "credit2addr_regmap_t", "structcredit2addr__regmap__t.html", "structcredit2addr__regmap__t" ],
    [ "CreditToAddr", "classCreditToAddr.html", "classCreditToAddr" ],
    [ "delete_by_ref", "structdelete__by__ref.html", "structdelete__by__ref" ],
    [ "syncevent_t< N >::dest_t", "structsyncevent__t_1_1dest__t.html", "structsyncevent__t_1_1dest__t" ],
    [ "DIR", "structDIR.html", "structDIR" ],
    [ "dirent", "structdirent.html", "structdirent" ],
    [ "dsd_t", "structdsd__t.html", "structdsd__t" ],
    [ "dsdh_t", "structdsdh__t.html", "structdsdh__t" ],
    [ "dvi_color", "classdvi__color.html", "classdvi__color" ],
    [ "dvi_frame", "uniondvi__frame.html", "uniondvi__frame" ],
    [ "dvi_line", "structdvi__line.html", "structdvi__line" ],
    [ "dvi_pixel_", "uniondvi__pixel__.html", "uniondvi__pixel__" ],
    [ "dvi_screen", "classdvi__screen.html", "classdvi__screen" ],
    [ "mfifo_t< T, FIFO_READERS, FIFO_SIZE_BITS, B >::elem_t", "classmfifo__t_1_1elem__t.html", "classmfifo__t_1_1elem__t" ],
    [ "PMC_NS::Error", "classPMC__NS_1_1Error.html", "classPMC__NS_1_1Error" ],
    [ "Fifo", "structFifo.html", "structFifo" ],
    [ "Fifo_admin", "structFifo__admin.html", "structFifo__admin" ],
    [ "FIFO_ARRAY", "structFIFO__ARRAY.html", "structFIFO__ARRAY" ],
    [ "FifoEP", "structFifoEP.html", "structFifoEP" ],
    [ "PMC_NS::FifoMemPool< Tsa, N, B >", "classPMC__NS_1_1FifoMemPool.html", "classPMC__NS_1_1FifoMemPool" ],
    [ "firfilt_regmap_t", "structfirfilt__regmap__t.html", "structfirfilt__regmap__t" ],
    [ "FirFilter", "classFirFilter.html", "classFirFilter" ],
    [ "fixed_t< I, P, S, rounding >", "classfixed__t.html", "classfixed__t" ],
    [ "fontchar_t", "structfontchar__t.html", "structfontchar__t" ],
    [ "graphix_status_t", "uniongraphix__status__t.html", "uniongraphix__status__t" ],
    [ "PMC_NS::VarPtrArray< L, T, B >::GroupScopeRO", "classPMC__NS_1_1VarPtrArray_1_1GroupScopeRO.html", "classPMC__NS_1_1VarPtrArray_1_1GroupScopeRO" ],
    [ "PMC_NS::VarPtrArray< L, T, B >::GroupScopeX", "classPMC__NS_1_1VarPtrArray_1_1GroupScopeX.html", "classPMC__NS_1_1VarPtrArray_1_1GroupScopeX" ],
    [ "HNTAG", "structHNTAG.html", "structHNTAG" ],
    [ "HTAG", "structHTAG.html", "structHTAG" ],
    [ "Info_App_s", "structInfo__App__s.html", "structInfo__App__s" ],
    [ "Info_CB", "structInfo__CB.html", "structInfo__CB" ],
    [ "Info_CBOverlap", "structInfo__CBOverlap.html", "structInfo__CBOverlap" ],
    [ "Info_CBRing", "structInfo__CBRing.html", "structInfo__CBRing" ],
    [ "Info_CBRingOpt", "structInfo__CBRingOpt.html", "structInfo__CBRingOpt" ],
    [ "Info_CBSliding", "structInfo__CBSliding.html", "structInfo__CBSliding" ],
    [ "Info_FIFO", "structInfo__FIFO.html", "structInfo__FIFO" ],
    [ "Info_FIFO_remote", "structInfo__FIFO__remote.html", "structInfo__FIFO__remote" ],
    [ "Info_Task", "structInfo__Task.html", "structInfo__Task" ],
    [ "Info_Window", "structInfo__Window.html", "structInfo__Window" ],
    [ "iq_t", "unioniq__t.html", "unioniq__t" ],
    [ "iqu_t", "unioniqu__t.html", "unioniqu__t" ],
    [ "is_same< T1, T2 >", "structis__same.html", "structis__same" ],
    [ "is_same< T, T >", "structis__same_3_01T_00_01T_01_4.html", "structis__same_3_01T_00_01T_01_4" ],
    [ "is_type_ptr", "classis__type__ptr.html", "classis__type__ptr" ],
    [ "is_type_ref< T >", "structis__type__ref.html", null ],
    [ "is_type_ref< T & >", "structis__type__ref_3_01T_01_6_01_4.html", null ],
    [ "IsConst< T >", "classIsConst.html", "classIsConst" ],
    [ "IsConst< const T >", "classIsConst_3_01const_01T_01_4.html", "classIsConst_3_01const_01T_01_4" ],
    [ "kernel_boot_param_t", "structkernel__boot__param__t.html", "structkernel__boot__param__t" ],
    [ "kernel_context_t", "structkernel__context__t.html", "structkernel__context__t" ],
    [ "lck_admin_t", "unionlck__admin__t.html", "unionlck__admin__t" ],
    [ "lck_daemon_admin_t", "structlck__daemon__admin__t.html", "structlck__daemon__admin__t" ],
    [ "lck_daemon_locks_t", "structlck__daemon__locks__t.html", "structlck__daemon__locks__t" ],
    [ "lck_my_locks_t", "structlck__my__locks__t.html", "structlck__my__locks__t" ],
    [ "line_t", "structline__t.html", "structline__t" ],
    [ "linfs_queues_t", "structlinfs__queues__t.html", "structlinfs__queues__t" ],
    [ "linfs_res_t", "structlinfs__res__t.html", "structlinfs__res__t" ],
    [ "PMC_NS::LocalAlloc", "classPMC__NS_1_1LocalAlloc.html", "classPMC__NS_1_1LocalAlloc" ],
    [ "PMC_NS::LocalBackend< T >", "classPMC__NS_1_1LocalBackend.html", "classPMC__NS_1_1LocalBackend" ],
    [ "LocalBuffer", "structLocalBuffer.html", "structLocalBuffer" ],
    [ "PMC_NS::Location< T >", "classPMC__NS_1_1Location.html", "classPMC__NS_1_1Location" ],
    [ "lt_t", "structlt__t.html", "structlt__t" ],
    [ "Mail", "structMail.html", "structMail" ],
    [ "malloc_buffer_t", "structmalloc__buffer__t.html", "structmalloc__buffer__t" ],
    [ "map_app_layout_t", "structmap__app__layout__t.html", "structmap__app__layout__t" ],
    [ "map_application_t", "structmap__application__t.html", "structmap__application__t" ],
    [ "map_core_t", "structmap__core__t.html", "structmap__core__t" ],
    [ "map_hardware_t", "structmap__hardware__t.html", "structmap__hardware__t" ],
    [ "map_impl_fifo_t", "structmap__impl__fifo__t.html", "structmap__impl__fifo__t" ],
    [ "map_impl_layout_t", "structmap__impl__layout__t.html", "structmap__impl__layout__t" ],
    [ "map_impl_link_t", "structmap__impl__link__t.html", null ],
    [ "map_impl_mailbox_t", "structmap__impl__mailbox__t.html", "structmap__impl__mailbox__t" ],
    [ "map_impl_memory_t", "structmap__impl__memory__t.html", "structmap__impl__memory__t" ],
    [ "map_impl_process_t", "structmap__impl__process__t.html", "structmap__impl__process__t" ],
    [ "map_implementation_t", "structmap__implementation__t.html", "structmap__implementation__t" ],
    [ "map_port_t", "structmap__port__t.html", "structmap__port__t" ],
    [ "map_task_layout_t", "structmap__task__layout__t.html", "structmap__task__layout__t" ],
    [ "map_task_t", "structmap__task__t.html", "structmap__task__t" ],
    [ "mc_check_t", "structmc__check__t.html", null ],
    [ "mc_prim< T >", "structmc__prim.html", "structmc__prim" ],
    [ "mc_ptr< T >", "structmc__ptr.html", "structmc__ptr" ],
    [ "mc_var< T >", "structmc__var.html", "structmc__var" ],
    [ "PMC_NS::MCBackend< T >", "classPMC__NS_1_1MCBackend.html", "classPMC__NS_1_1MCBackend" ],
    [ "md_t", "structmd__t.html", "structmd__t" ],
    [ "PMC_NS::MemPool", "classPMC__NS_1_1MemPool.html", "classPMC__NS_1_1MemPool" ],
    [ "mfifo_t< T, FIFO_READERS, FIFO_SIZE_BITS, B >", "classmfifo__t.html", "classmfifo__t" ],
    [ "PMC_NS::MultiLocation< T >", "classPMC__NS_1_1MultiLocation.html", "classPMC__NS_1_1MultiLocation" ],
    [ "PMC_NS::VarPtrArray< L, T, B >::GroupScopeRO::NakedData", "structPMC__NS_1_1VarPtrArray_1_1GroupScopeRO_1_1NakedData.html", "structPMC__NS_1_1VarPtrArray_1_1GroupScopeRO_1_1NakedData" ],
    [ "PMC_NS::VarPtrArray< L, T, B >::GroupScopeX::NakedData", "structPMC__NS_1_1VarPtrArray_1_1GroupScopeX_1_1NakedData.html", "structPMC__NS_1_1VarPtrArray_1_1GroupScopeX_1_1NakedData" ],
    [ "PMC_NS::NoAlloc", "classPMC__NS_1_1NoAlloc.html", "classPMC__NS_1_1NoAlloc" ],
    [ "PMC_NS::NoInit< T >", "structPMC__NS_1_1NoInit.html", "structPMC__NS_1_1NoInit" ],
    [ "option", "structoption.html", "structoption" ],
    [ "pipe_admin_t", "structpipe__admin__t.html", "structpipe__admin__t" ],
    [ "pipe_t", "structpipe__t.html", "structpipe__t" ],
    [ "pix_t", "unionpix__t.html", "unionpix__t" ],
    [ "PlacementDelete< T, Tref >", "classPlacementDelete.html", "classPlacementDelete" ],
    [ "PlacementDelete< T, void >", "classPlacementDelete_3_01T_00_01void_01_4.html", "classPlacementDelete_3_01T_00_01void_01_4" ],
    [ "poly_t< N >", "classpoly__t.html", "classpoly__t" ],
    [ "polygon_t", "structpolygon__t.html", "structpolygon__t" ],
    [ "prf_mb_snapshot_t", "structprf__mb__snapshot__t.html", "structprf__mb__snapshot__t" ],
    [ "proc_context_t", "structproc__context__t.html", "structproc__context__t" ],
    [ "proc_local_t", "structproc__local__t.html", "structproc__local__t" ],
    [ "proc_stats_t", "structproc__stats__t.html", "structproc__stats__t" ],
    [ "ProcessState_t", "unionProcessState__t.html", "unionProcessState__t" ],
    [ "pthread_attr_t", "structpthread__attr__t.html", "structpthread__attr__t" ],
    [ "pthread_barrier_t", "structpthread__barrier__t.html", "structpthread__barrier__t" ],
    [ "pthread_barrierattr_t", "structpthread__barrierattr__t.html", "structpthread__barrierattr__t" ],
    [ "pthread_cond_t", "structpthread__cond__t.html", "structpthread__cond__t" ],
    [ "pthread_condattr_t", "structpthread__condattr__t.html", "structpthread__condattr__t" ],
    [ "pthread_key_admin_t", "structpthread__key__admin__t.html", "structpthread__key__admin__t" ],
    [ "pthread_mutex_t", "structpthread__mutex__t.html", "structpthread__mutex__t" ],
    [ "pthread_mutexattr_t", "structpthread__mutexattr__t.html", "structpthread__mutexattr__t" ],
    [ "pthread_sch_t", "structpthread__sch__t.html", "structpthread__sch__t" ],
    [ "r_sel_out_t", "structr__sel__out__t.html", "structr__sel__out__t" ],
    [ "r_sel_out_union_t", "unionr__sel__out__union__t.html", "unionr__sel__out__union__t" ],
    [ "ramfile_entry_t", "structramfile__entry__t.html", "structramfile__entry__t" ],
    [ "rate_frac_t", "unionrate__frac__t.html", "unionrate__frac__t" ],
    [ "PMC_NS::RCBackend< T >", "classPMC__NS_1_1RCBackend.html", "classPMC__NS_1_1RCBackend" ],
    [ "Reader", "classReader.html", "classReader" ],
    [ "RFifo< T >", "classRFifo.html", "classRFifo" ],
    [ "RingBufferOptStruct", "structRingBufferOptStruct.html", "structRingBufferOptStruct" ],
    [ "RingBufferStruct", "structRingBufferStruct.html", "structRingBufferStruct" ],
    [ "RingDma", "classRingDma.html", "classRingDma" ],
    [ "ringratecontrol_dev_t", "structringratecontrol__dev__t.html", "structringratecontrol__dev__t" ],
    [ "ringshell_ctrl_dev_t", "structringshell__ctrl__dev__t.html", "structringshell__ctrl__dev__t" ],
    [ "rusage", "structrusage.html", "structrusage" ],
    [ "PMC_NS::SACallback", "classPMC__NS_1_1SACallback.html", "classPMC__NS_1_1SACallback" ],
    [ "PMC_NS::SAMultiLocation< T >", "classPMC__NS_1_1SAMultiLocation.html", "classPMC__NS_1_1SAMultiLocation" ],
    [ "PMC_NS::SASPMBackend< T, C >", "classPMC__NS_1_1SASPMBackend.html", "classPMC__NS_1_1SASPMBackend" ],
    [ "PMC_NS::SCBackend< T >", "classPMC__NS_1_1SCBackend.html", "classPMC__NS_1_1SCBackend" ],
    [ "sch_t", "structsch__t.html", "structsch__t" ],
    [ "PMC_NS::Scope< V, T >", "classPMC__NS_1_1Scope.html", "classPMC__NS_1_1Scope" ],
    [ "PMC_NS::Scope< V, T >::ScopePtr", "structPMC__NS_1_1Scope_1_1ScopePtr.html", "structPMC__NS_1_1Scope_1_1ScopePtr" ],
    [ "PMC_NS::ScopeRO< V >", "classPMC__NS_1_1ScopeRO.html", "classPMC__NS_1_1ScopeRO" ],
    [ "PMC_NS::ScopeX< V >", "classPMC__NS_1_1ScopeX.html", "classPMC__NS_1_1ScopeX" ],
    [ "PMC_NS::SharedAlloc", "classPMC__NS_1_1SharedAlloc.html", "classPMC__NS_1_1SharedAlloc" ],
    [ "PMC_NS::SharedMemPool", "classPMC__NS_1_1SharedMemPool.html", "classPMC__NS_1_1SharedMemPool" ],
    [ "sigaction", "structsigaction.html", "structsigaction" ],
    [ "sigevent", "structsigevent.html", "structsigevent" ],
    [ "siginfo_t", "structsiginfo__t.html", "structsiginfo__t" ],
    [ "SignedType", "structSignedType.html", "structSignedType" ],
    [ "sigval", "unionsigval.html", "unionsigval" ],
    [ "SmallestInt< bits, E >", "structSmallestInt.html", "structSmallestInt" ],
    [ "SmallestInt< bits, TypeExpr<(bits >=0 &&bits< 8)> >", "structSmallestInt_3_01bits_00_01TypeExpr_3_07bits_01_4_0A0_01_6_6bits_3_018_08_4_01_4.html", "structSmallestInt_3_01bits_00_01TypeExpr_3_07bits_01_4_0A0_01_6_6bits_3_018_08_4_01_4" ],
    [ "SmallestInt< bits, TypeExpr<(bits >=16 &&bits< 32)> >", "structSmallestInt_3_01bits_00_01TypeExpr_3_07bits_01_4_0A16_01_6_6bits_3_0132_08_4_01_4.html", "structSmallestInt_3_01bits_00_01TypeExpr_3_07bits_01_4_0A16_01_6_6bits_3_0132_08_4_01_4" ],
    [ "SmallestInt< bits, TypeExpr<(bits >=32 &&bits< 64)> >", "structSmallestInt_3_01bits_00_01TypeExpr_3_07bits_01_4_0A32_01_6_6bits_3_0164_08_4_01_4.html", "structSmallestInt_3_01bits_00_01TypeExpr_3_07bits_01_4_0A32_01_6_6bits_3_0164_08_4_01_4" ],
    [ "SmallestInt< bits, TypeExpr<(bits >=8 &&bits< 16)> >", "structSmallestInt_3_01bits_00_01TypeExpr_3_07bits_01_4_0A8_01_6_6bits_3_0116_08_4_01_4.html", "structSmallestInt_3_01bits_00_01TypeExpr_3_07bits_01_4_0A8_01_6_6bits_3_0116_08_4_01_4" ],
    [ "SmallestNum< bits, SignedType >", "structSmallestNum_3_01bits_00_01SignedType_01_4.html", "structSmallestNum_3_01bits_00_01SignedType_01_4" ],
    [ "SmallestNum< bits, UnsignedType >", "structSmallestNum_3_01bits_00_01UnsignedType_01_4.html", "structSmallestNum_3_01bits_00_01UnsignedType_01_4" ],
    [ "SmallestUInt< bits, E >", "structSmallestUInt.html", "structSmallestUInt" ],
    [ "SmallestUInt< bits, TypeExpr<(bits >16 &&bits<=32)> >", "structSmallestUInt_3_01bits_00_01TypeExpr_3_07bits_01_416_01_6_6bits_3_0A32_08_4_01_4.html", "structSmallestUInt_3_01bits_00_01TypeExpr_3_07bits_01_416_01_6_6bits_3_0A32_08_4_01_4" ],
    [ "SmallestUInt< bits, TypeExpr<(bits >32 &&bits<=64)> >", "structSmallestUInt_3_01bits_00_01TypeExpr_3_07bits_01_432_01_6_6bits_3_0A64_08_4_01_4.html", "structSmallestUInt_3_01bits_00_01TypeExpr_3_07bits_01_432_01_6_6bits_3_0A64_08_4_01_4" ],
    [ "SmallestUInt< bits, TypeExpr<(bits >8 &&bits<=16)> >", "structSmallestUInt_3_01bits_00_01TypeExpr_3_07bits_01_48_01_6_6bits_3_0A16_08_4_01_4.html", "structSmallestUInt_3_01bits_00_01TypeExpr_3_07bits_01_48_01_6_6bits_3_0A16_08_4_01_4" ],
    [ "SmallestUInt< bits, TypeExpr<(bits >=0 &&bits<=8)> >", "structSmallestUInt_3_01bits_00_01TypeExpr_3_07bits_01_4_0A0_01_6_6bits_3_0A8_08_4_01_4.html", "structSmallestUInt_3_01bits_00_01TypeExpr_3_07bits_01_4_0A0_01_6_6bits_3_0A8_08_4_01_4" ],
    [ "spi_register_t", "structspi__register__t.html", "structspi__register__t" ],
    [ "spi_wrapper_t", "unionspi__wrapper__t.html", "unionspi__wrapper__t" ],
    [ "spireg_spicr_t", "unionspireg__spicr__t.html", "unionspireg__spicr__t" ],
    [ "spireg_spidrr_t", "structspireg__spidrr__t.html", "structspireg__spidrr__t" ],
    [ "spireg_spidtr_t", "structspireg__spidtr__t.html", "structspireg__spidtr__t" ],
    [ "spireg_spisr_t", "structspireg__spisr__t.html", "structspireg__spisr__t" ],
    [ "PMC_NS::SPMBackend< T >", "classPMC__NS_1_1SPMBackend.html", "classPMC__NS_1_1SPMBackend" ],
    [ "stats_t", "structstats__t.html", "structstats__t" ],
    [ "stopwatch_t", "structstopwatch__t.html", "structstopwatch__t" ],
    [ "subpixel_t", "classsubpixel__t.html", "classsubpixel__t" ],
    [ "sync_event_entry_t", "structsync__event__entry__t.html", "structsync__event__entry__t" ],
    [ "syncevent_t< N >", "classsyncevent__t.html", "classsyncevent__t" ],
    [ "TArray< T, L >", "classTArray.html", "classTArray" ],
    [ "TArray< T, 0 >", "classTArray_3_01T_00_010_01_4.html", "classTArray_3_01T_00_010_01_4" ],
    [ "TArray< T, 1 >", "classTArray_3_01T_00_011_01_4.html", "classTArray_3_01T_00_011_01_4" ],
    [ "tdcmd_local_t", "structtdcmd__local__t.html", "structtdcmd__local__t" ],
    [ "tdcmd_remote_t", "structtdcmd__remote__t.html", "structtdcmd__remote__t" ],
    [ "tdcmd_t", "structtdcmd__t.html", "structtdcmd__t" ],
    [ "TDMATimes", "structTDMATimes.html", "structTDMATimes" ],
    [ "tds_t", "structtds__t.html", "structtds__t" ],
    [ "termios", "structtermios.html", "structtermios" ],
    [ "TileArbiter", "structTileArbiter.html", "structTileArbiter" ],
    [ "trace_t", "structtrace__t.html", "structtrace__t" ],
    [ "uartlite_t", "structuartlite__t.html", "structuartlite__t" ],
    [ "UnsignedType", "structUnsignedType.html", "structUnsignedType" ],
    [ "utimbuf", "structutimbuf.html", "structutimbuf" ],
    [ "utsname", "structutsname.html", "structutsname" ],
    [ "PMC_NS::Var< T, B >", "classPMC__NS_1_1Var.html", "classPMC__NS_1_1Var" ],
    [ "PMC_NS::VarPtrArray< L, T, B >", "classPMC__NS_1_1VarPtrArray.html", "classPMC__NS_1_1VarPtrArray" ],
    [ "WFifo< T >", "classWFifo.html", "classWFifo" ],
    [ "WorkQueue< T, W >", "classWorkQueue.html", "classWorkQueue" ],
    [ "Writer", "classWriter.html", "classWriter" ]
];