Starburst: include/sys/api.h File Reference
include/sys/api.h File Reference
Global header file that includes all functions of the OS.
#include <stdio.h>
#include <autoret.h>
#include <sys/time.h>
#include <sys/types.h>
#include <sys/kernel_types.h>
#include <sys/device.h>
#include <sys/io.h>
#include <sys/kernel.h>
#include <sys/syscall.h>
#include <sys/hooks.h>
#include <malloc.h>
#include <daemons.h>
#include <trace.h>
#include <errno.h>
#include <stddef.h>
#include <unistd.h>
#include <stdlib.h>
Defines
#define likely(x) __builtin_expect((x),1)
#define unlikely(x) __builtin_expect((x),0)
#define XSTRINGIFY(s) #s
#define STRINGIFY(s) XSTRINGIFY(s)
#define ASSERT(expr, msg, a...)
#define VA_NUMARGS(...) (sizeof((int[]){0, ##__VA_ARGS__})/sizeof(int)-1)
#define PP_NARG(...) PP_NARG_(__VA_ARGS__,PP_RSEQ_N())
#define PP_NARG_(...) PP_ARG_N(__VA_ARGS__)
#define PP_ARG_N(_1, _2, _3, _4, N,...) N
#define PP_RSEQ_N() 4,3,2,1,0
#define PP_CONCAT(a, b) PP_CONCAT_(a,b)
#define PP_CONCAT_(a, b) a ## b
#define CHECK_NOT_CACHED(p)
#define CHECK_SIZEOF(type, size) extern char sizeof_##type##_not_##size[1-2*(sizeof(type)-size!=0)];
#define CALL_ON_BOOT(fun) int(*call_on_boot_##fun)(void) __attribute__((weak,section(".boot")))=fun;
#define NOERR 0
#define ESUCCESS 0
#define timestamp_start(t) do{int r __attribute__((unused))=gettimeofday((t),NULL);ASSERT(r==0,"Cannot get time stamp: %d",errno);}while(0)
Typedefs
typedef struct timeval timestamp_t
Functions
void abort () _NO_THROW __attribute__((noreturn))
Aborts the calling process.
void * helix_rpc (void *(*fun)(void *), void *arg, int proc) _NO_THROW
int printf_nt (const char *format,...) _NO_THROW __attribute__((format(printf
int pid_t getgpid () _NO_THROW
Returns a globally unique process ID of the current process, that includes information about the core it is mapped to.
pid_t getgpid (pid_t pid, unsigned int proc) _NO_THROW
Returns a globally unique process ID of the specified process, that includes information about the core it is mapped to.
pid_t getlpid (pid_t gpid) _NO_THROW
Returns the local process ID, which is used on the processor the process runs on.
unsigned int getgpidproc (pid_t gpid) _NO_THROW
Returns the processor ID the process runs on.
pid_t getupid () _NO_THROW
int timecmp (const struct timeval *t1, const struct timeval *t2) _NO_THROW
Compares two timevals.
int CreateProcess (pid_t &pid, void *(*main)(void *), void *arg=NULL, timems_t slicelength=PROC_DEFAULT_TIMESLICE, size_t stack=PROC_DEFAULT_STACK, int proc=-1) _NO_THROW __attribute__((warn_unused_result))
int GetProcessFlags (pid_t pid, int *flags, int proc=-1) _NO_THROW
int SetProcessFlags (pid_t pid, int flags, int proc=-1) _NO_THROW
int GetProcessState (pid_t pid, proc_state_t *state, bool *sighandling=NULL, int proc=-1) _NO_THROW
int SetProcessTimeslice (pid_t pid, timems_t slicelength, int proc=-1) _NO_THROW
int StartProcess (pid_t pid, int proc=-1) _NO_THROW __attribute__((warn_unused_result))
int WaitProcess (pid_t pid, void **ret=NULL, int proc=-1) _NO_THROW __attribute__((warn_unused_result))
int DestroyProcess (pid_t pid, void **ret, int proc=-1) _NO_THROW
int SendSignal (pid_t pid, int sig, union sigval *sv, int proc=-1) _NO_THROW
int SyncEventHit (pid_t pid, void *event, int proc=-1) _NO_THROW
int AllocChannels (pid_t pid, int num_chan, int proc=-1) _NO_THROW __attribute__((warn_unused_result))
int AssignChannel (pid_t pid, int chan_id, void *channel, int label=0, int proc=-1) _NO_THROW
int SetChannelLabel (pid_t pid, int chan_id, int label, int proc=-1) _NO_THROW
FifoEP * AllocFifoEndPoint (unsigned int fifo_size, unsigned int element_size, int flags, int proc=-1) _NO_THROW
Mail * AllocMail (unsigned int count, int proc=-1) _NO_THROW
SimpleMail * AllocSimpleMail (int proc=-1) _NO_THROW
void DestroyFifoEndPoint (FifoEP *fifo, int proc=-1) _NO_THROW
void DestroyMail (Mail *mail, int proc=-1) _NO_THROW
int BootKernel (int procid) _NO_THROW
Boots the kernel on another processor.
void DumpConfig () _NO_THROW
unsigned int timestamp_diff_ms (timestamp_t *t) _NO_THROW __attribute__((always_inline))
Variables
void * _kcbegin
void * _spare_memory_cached
Detailed Description
Global header file that includes all functions of the OS.
Definition in file api.h.
Define Documentation
#define ASSERT (expr, msg, a...)
Value:
do{if(unlikely(!(expr))){   \
        printf_nt("ASSERTION FAILED in process %d@%d, " __FILE__ ":" STRINGIFY(__LINE__) ":\"%s\": " msg "\n", \
            getpid(),GetProcID(),STRINGIFY(expr),##a); \
        abort();}               \
    }while(0)
Definition at line 15 of file api.h.
Referenced by DefaultTaskDaemon(), WorkQueue< T, W >::Dispatcher(), DumpStatsNow(), fcntl(), FinishForwardedRequest(), fork(), ForwardRequest(), GetIssueSlot(), getupid(), syncevent_t< N >::hit(), kTraceSync(), mkfifo(), pipe_vfcntl(), ProcessRequest(), pthread_barrier_wait(), ReserveRemoteSlot(), StartMallocDaemon(), StatsCount(), TraceAbsTime(), TraceRelTime(), syncevent_t< N >::wait(), waitpid(), WaitProcess(), and WaitProcessDaemon().
#define CALL_ON_BOOT (fun) int(*call_on_boot_##fun)(void) __attribute__((weak,section(".boot")))=fun;
Definition at line 59 of file api.h.
#define CHECK_NOT_CACHED (p)
Value:
do{                                                                                                         \
        if(unlikely(                                                                                            \
            (p)!=NULL &&                                                                                        \
            (unsigned int)(void*)(p)>=(unsigned int)(void*)&_kcbegin &&                                         \
            (unsigned int)(void*)(p)<(unsigned int)(void*)&_spare_memory_cached                                 \
            )){                                                                                                 \
            printf("WARNING: local data structure %p passed between cores\n",(void*)(p));                       \
            FlushDCacheWord((void*)(p));                                                                        \
            *(volatile int*)(p);                                                                                \
        }                                                                                                       \
    }while(0)
Definition at line 40 of file api.h.
Referenced by dCreateProcess().
#define CHECK_SIZEOF (type, size) extern char sizeof_##type##_not_##size[1-2*(sizeof(type)-size!=0)];
Definition at line 56 of file api.h.
#define ESUCCESS 0
Definition at line 67 of file api.h.
Referenced by _mown(), BootKernel(), check_attr(), CheckRing(), close(), creat(), dBootKernels(), DefaultMulticoreSetup(), DefaultTaskDaemon(), FinishForwardedRequest(), ForwardRequest(), GarbageCollect(), InitFifo(), InitSHeap(), InitTaskDaemon(), kAllocChannels(), kAssignChannel(), kClearSignal(), kCoreDump(), kCreateProcess(), kDestroyProcess(), kGetProcessFlags(), kGetProcessState(), kGetProcessStats(), kGetProcLocal(), kJoinProcess(), kMaskSignal(), kSendSignal(), kSetChannelLabel(), kSetProcessFlags(), kSetProcessTimeslice(), kSetSignalHandler(), kStartProcess(), kSuspend(), kYield(), open(), ProcessRequest(), pthread_attr_destroy(), pthread_attr_getdetachstate(), pthread_attr_getstacksize(), pthread_attr_init(), pthread_attr_setaffinity_np(), pthread_attr_setdetachstate(), pthread_attr_setschedparam(), pthread_attr_setstacksize(), pthread_create(), pthread_mutex_init(), RegisterHook(), SetupProfilerDaemon(), ShutdownDaemon(), StartTimerDaemon(), StopMallocDaemon(), UnregisterHook(), WaitForResult(), and WaitProcessDaemon().
#define likely (x) __builtin_expect((x),1)
Definition at line 7 of file api.h.
Referenced by fillpoly(), fillrect(), kCheckFreeStack(), kScheduleNext(), kTraceSchedule(), kTraceScheduleYield(), lck_pass_p(), lck_unlock(), CFifo< T, CFifo<>::w >::operator new(), dvi_screen::SetPixelSafe(), and usleep().
#define NOERR 0
Definition at line 66 of file api.h.
#define PP_ARG_N (_1, _2, _3, _4, N, ...) N
Definition at line 29 of file api.h.
#define PP_CONCAT (a, b) PP_CONCAT_(a,b)
Definition at line 31 of file api.h.
#define PP_CONCAT_ (a, b) a ## b
Definition at line 32 of file api.h.
#define PP_NARG (...) PP_NARG_(__VA_ARGS__,PP_RSEQ_N())
Definition at line 27 of file api.h.
#define PP_NARG_ (...) PP_ARG_N(__VA_ARGS__)
Definition at line 28 of file api.h.
#define PP_RSEQ_N () 4,3,2,1,0
Definition at line 30 of file api.h.
#define STRINGIFY (s) XSTRINGIFY(s)
Definition at line 11 of file api.h.
Referenced by Disclaimer(), and DumpConfig().
#define timestamp_start (t) do{int r __attribute__((unused))=gettimeofday((t),NULL);ASSERT(r==0,"Cannot get time stamp: %d",errno);}while(0)
Definition at line 127 of file api.h.
Referenced by timestamp_diff_ms().
#define unlikely (x) __builtin_expect((x),0)
Definition at line 8 of file api.h.
Referenced by auto_ret< T, ok >::__attribute__(), _pthread_cond_signal(), _pthread_cond_wait(), PMC_NS::Location< T >::acquire(), PMC_NS::SCBackend< T >::acquire(), PMC_NS::FifoMemPool< Tsa, N, B >::alloc(), bitshark_read(), CFifo< T, CFifo<>::w >::CFifo(), PMC_NS::MemPool::check(), dvi_screen::ClipBottom(), dvi_screen::ClipLeft(), dvi_screen::ClipRight(), dvi_screen::ClipTop(), PMC_NS::SASPMBackend< T, C >::entry_ro(), fillpoly(), fillrect(), PMC_NS::FifoMemPool< Tsa, N, B >::front(), syncevent_t< N >::hit(), kCheckFreeStack(), kCheckStackOverflow(), kGetProcessState(), kScheduleNext(), kScheduleProcess(), kTraceSchedule(), kTraceScheduleYield(), lck_ask(), lck_giveup(), lck_list_add(), lck_pass_p(), lck_register(), lck_request(), lck_tree_add(), llck(), PMC_NS::LocalAlloc::operator new(), PMC_NS::SharedAlloc::operator new(), CFifo< T, CFifo<>::w >::operator new(), CFifo< T, CFifo<>::r >::operator new[](), WorkQueue< T, W >::Pop(), pthread_barrier_wait(), pthread_mutex_lock(), PMC_NS::Location< T >::release(), SignalDispatcher(), and sprintf64().
#define VA_NUMARGS (...) (sizeof((int[]){0, ##__VA_ARGS__})/sizeof(int)-1)
Definition at line 25 of file api.h.
#define XSTRINGIFY (s) #s
Definition at line 10 of file api.h.
Typedef Documentation
typedef struct timeval timestamp_t
Definition at line 126 of file api.h.
Function Documentation
void abort ()
Aborts the calling process.
Forcably ends the process and the timeslice. Will never return. The process return value will be set to -1.
Definition at line 70 of file api.cc.
References getpid().
Referenced by bitshark_auto_tune(), bitshark_auto_tune2(), CFifo< T, CFifo<>::w >::CFifo(), DefaultAbortSignalHandler(), PMC_NS::Error::format(), mc_error_handler(), CFifo< T, CFifo<>::w >::operator new(), operator new(), CFifo< T, CFifo<>::r >::operator new[](), operator new[](), pipe(), pipe_read(), pipe_write(), pthread_barrier_destroy(), pthread_barrier_init(), pthread_getspecific(), ring_printall(), and ring_stream_setup().
int AllocChannels (pid_t pid, int num_chan, int proc = -1)
Definition at line 224 of file api.cc.
References AllocChannels(), and SCWRAP_REMOTE_TD.
Referenced by AllocChannels(), and map_start_task().
FifoEP* AllocFifoEndPoint (unsigned int fifo_size, unsigned int element_size, int flags, int proc = -1)
Definition at line 236 of file api.cc.
References AllocFifoEndPoint(), and SCWRAP_ALL_TD.
Referenced by AllocFifoEndPoint(), and map_start_fifo().
Mail* AllocMail (unsigned int count, int proc = -1)
Definition at line 240 of file api.cc.
References AllocMail(), and SCWRAP_ALL_TD.
Referenced by AllocMail(), and map_start_mail().
SimpleMail* AllocSimpleMail (int proc = -1)
Definition at line 244 of file api.cc.
References AllocSimpleMail(), and SCWRAP_ALL_TDN.
Referenced by AllocSimpleMail(), and map_start_mail().
int AssignChannel (pid_t pid, int chan_id, void * channel, int label = 0, int proc = -1)
Definition at line 228 of file api.cc.
References AssignChannel(), and SCWRAP_REMOTE_TD.
Referenced by AssignChannel(), map_start_fifo(), and map_start_mail().
int BootKernel (int procid)
Boots the kernel on another processor.
When one of the wrapper functions like CreateProcess() is to be used, make sure that the other kernel is booted using BootKernel() or dBootKernels().
Nothing happens when procid is set to the current processor ID. Do not boot a processor twice.
When BootKernel() is called repeatedly for a list of processors, consider using dBootKernels() directly; that reduces the overhead significantly by skipping the already-booted check and booting all cores in parallel.
Parameters:
procid the ID of the processor to boot
Returns:
0 on success, otherwise an errno
Definition at line 272 of file api.cc.
References dBootKernels(), ESUCCESS, and GetProcID().
int CreateProcess (pid_t & pid, void *(*)(void *) main, void * arg = NULL, timems_t slicelength = PROC_DEFAULT_TIMESLICE, size_t stack = PROC_DEFAULT_STACK, int proc = -1)
Definition at line 177 of file api.cc.
References CreateProcess(), main, and SCWRAP_ALL_TD.
Referenced by CreateProcess(), map_start_task(), pthread_create(), WorkQueue< T, W >::StartDispatcher(), WorkQueue< T, W >::StartSlaves(), and StartTimerDaemon().
void DestroyFifoEndPoint (FifoEP * fifo, int proc = -1)
Definition at line 248 of file api.cc.
References DestroyFifoEndPoint(), and SCWRAP_ALL_TDV.
Referenced by DestroyFifoEndPoint(), map_start_fifo(), and map_stop_fifo().
void DestroyMail (Mail * mail, int proc = -1)
Definition at line 252 of file api.cc.
References DestroyMail(), and SCWRAP_ALL_TDV.
Referenced by DestroyMail(), map_start_mail(), and map_stop_mail().
int DestroyProcess (pid_t pid, void ** ret, int proc = -1)
Definition at line 208 of file api.cc.
References DestroyProcess(), and SCWRAP_ALL_TD.
Referenced by DestroyProcess(), map_start_task(), map_stop_task(), pthread_create(), StartTimerDaemon(), and WorkQueue< T, W >::~WorkQueue().
void DumpConfig ()
Definition at line 283 of file api.cc.
References CONTEXT_SWITCH_CYCLE_PANELTY, KERNEL_SYNC_EVENTS, MAX_PROCESSES, MAX_TIMERS, PROC_HEAP, PTHREAD_KEYS_MAX, STRINGIFY, and THREAD_LOCAL_FIELDS.
Referenced by kInitKernel().
int pid_t getgpid ()
Returns a globally unique process ID of the current process, that includes information about the core it is mapped to.
Returns:
the global ID of the current process
Definition at line 24 of file api.cc.
References getgpid(), getpid(), and GetProcID().
Referenced by _pthread_cond_wait(), dLockAsk(), dLockGiveup(), dLockRequest(), getgpid(), lck_migrate(), lck_pass_p(), lck_unlock(), pthread_create(), and pthread_self().
pid_t getgpid (pid_t pid, unsigned int proc)
Returns a globally unique process ID of the specified process, that includes information about the core it is mapped to.
Returns:
the global ID
Definition at line 32 of file api.cc.
References MAX_PROCESSES.
unsigned int getgpidproc (pid_t gpid)
Returns the processor ID the process runs on.
Parameters:
gpid the process ID to find the processor of
Returns:
the processor ID
Definition at line 50 of file api.cc.
References MAX_PROCESSES.
Referenced by dLockAsk(), lck_ask(), lck_migrate(), pthread_detach(), pthread_join(), pthread_kill(), and se_create_pta().
pid_t getlpid (pid_t gpid)
Returns the local process ID, which is used on the processor the process runs on.
Parameters:
gpid the process ID to find the local process ID of
Returns:
the local ID
Definition at line 41 of file api.cc.
References MAX_PROCESSES.
Referenced by dLockAsk(), pthread_detach(), pthread_join(), pthread_kill(), and se_create_pta().
int GetProcessFlags (pid_t pid, int * flags, int proc = -1)
Definition at line 181 of file api.cc.
References GetProcessFlags(), and SCWRAP_REMOTE_TD.
Referenced by GetProcessFlags(), pthread_detach(), and ShutdownDaemon().
int GetProcessState (pid_t pid, proc_state_t * state, bool * sighandling = NULL, int proc = -1)
Definition at line 189 of file api.cc.
References GetProcessState(), and SCWRAP_REMOTE_TD.
Referenced by GetProcessState().
pid_t getupid ()
Definition at line 54 of file api.cc.
References ASSERT, getpid(), lGetProcessState(), MAX_PROCESSES, and pid.
Referenced by calloc(), free(), freeAll(), GetIssueSlot(), mown(), omalloc(), orealloc(), and StopMallocDaemon().
void* helix_rpc (void *(*)(void *) fun, void * arg, int proc)
Definition at line 138 of file api.cc.
References dRemoteCall().
int printf_nt (const char * format, ...)
int SendSignal (pid_t pid, int sig, union sigval * sv, int proc = -1)
Definition at line 216 of file api.cc.
References SCWRAP_REMOTE_TD, and SendSignal().
Referenced by pipe_write(), pthread_kill(), SendSignal(), and ShutdownDaemon().
int SetChannelLabel (pid_t pid, int chan_id, int label, int proc = -1)
Definition at line 232 of file api.cc.
References SCWRAP_REMOTE_TD, and SetChannelLabel().
Referenced by SetChannelLabel().
int SetProcessFlags (pid_t pid, int flags, int proc = -1)
Definition at line 185 of file api.cc.
References SCWRAP_REMOTE_TD, and SetProcessFlags().
Referenced by pthread_create(), pthread_detach(), SetProcessFlags(), and ShutdownDaemon().
int SetProcessTimeslice (pid_t pid, timems_t slicelength, int proc = -1)
Definition at line 212 of file api.cc.
References SCWRAP_REMOTE_TD, and SetProcessTimeslice().
Referenced by SetProcessTimeslice().
int StartProcess (pid_t pid, int proc = -1)
Definition at line 193 of file api.cc.
References SCWRAP_ALL_TD, and StartProcess().
Referenced by map_start_task(), pthread_create(), WorkQueue< T, W >::StartDispatcher(), StartProcess(), WorkQueue< T, W >::StartSlaves(), and StartTimerDaemon().
int SyncEventHit (pid_t pid, void * event, int proc = -1)
Definition at line 220 of file api.cc.
References SCWRAP_ALL_TD, and SyncEventHit().
Referenced by syncevent_t< N >::hit(), and SyncEventHit().
int timecmp (const struct timeval * t1, const struct timeval * t2)
Compares two timevals.
Returns:
1 when t1>t2, 0 when t1==t2, -1 otherwise
Definition at line 448 of file newlibstubs.cc.
Referenced by _pthread_cond_wait(), and usleep().
unsigned int timestamp_diff_ms (timestamp_t * t) [inline]
Definition at line 130 of file api.h.
References timestamp_start.
int WaitProcess (pid_t pid, void ** ret = NULL, int proc = -1)
Definition at line 197 of file api.cc.
References ASSERT, dWaitProcess(), getpid(), GetProcID(), lJoinProcess(), and Yield().
Referenced by pthread_join().
Variable Documentation
void* _kcbegin
void* _spare_memory_cached