Starburst: kernel/api.cc File Reference
kernel/api.cc File Reference
Implementation of some generic non-kernel OS functions.
#include <sys/helix_config.h>
#include <sys/api.h>
#include <stdlib.h>
#include <unistd.h>
#include <stdarg.h>
#include <pwd.h>
#include <pthread.h>
#include <lock.h>
Defines
#define _SCWRAP_ALL_TD(ret, fun, args...)
#define SCWRAP_ALL_TD(fun, args...) _SCWRAP_ALL_TD(return,fun,args)
#define SCWRAP_ALL_TDV(fun, args...) _SCWRAP_ALL_TD(,fun,args)
#define SCWRAP_ALL_TDN(fun)
#define _SCWRAP_REMOTE_TD(ret, fun, args...)
#define SCWRAP_REMOTE_TD(fun, args...) _SCWRAP_REMOTE_TD(return,fun,args)
#define SCWRAP_REMOTE_TDV(fun, args...) _SCWRAP_REMOTE_TD(,fun,args)
Functions
pid_t getgpid ()
Returns a globally unique process ID of the current process, that includes information about the core it is mapped to.
pid_t getgpid (pid_t pid, unsigned int proc)
Returns a globally unique process ID of the specified process, that includes information about the core it is mapped to.
pid_t getlpid (pid_t gpid)
Returns the local process ID, which is used on the processor the process runs on.
unsigned int getgpidproc (pid_t gpid)
Returns the processor ID the process runs on.
pid_t getupid ()
void abort ()
Aborts the calling process.
void _exit (int status)
Exits the calling process, without cleanup.
long sysconf (int name)
struct passwd * getpwnam (const char *name)
void * helix_rpc (void *(*fun)(void *), void *arg, int proc)
int printf_nt (const char *format,...)
int CreateProcess (pid_t &pid, void *(*main)(void *), void *arg, timems_t slicelength, size_t stack, int proc)
int GetProcessFlags (pid_t pid, int *flags, int proc)
int SetProcessFlags (pid_t pid, int flags, int proc)
int GetProcessState (pid_t pid, proc_state_t *state, bool *sighandling, int proc)
int StartProcess (pid_t pid, int proc)
int WaitProcess (pid_t pid, void **ret, int proc)
int DestroyProcess (pid_t pid, void **ret, int proc)
int SetProcessTimeslice (pid_t pid, timems_t timeslice, int proc)
int SendSignal (pid_t pid, int sig, union sigval *sv, int proc)
int SyncEventHit (pid_t pid, void *event, int proc)
int AllocChannels (pid_t pid, int num_chan, int proc)
int AssignChannel (pid_t pid, int chan_id, void *channel, int label, int proc)
int SetChannelLabel (pid_t pid, int chan_id, int label, int proc)
FifoEP * AllocFifoEndPoint (unsigned int fifo_size, unsigned int element_size, int flags, int proc)
Mail * AllocMail (unsigned int count, int proc)
SimpleMail * AllocSimpleMail (int proc)
void DestroyFifoEndPoint (FifoEP *fifo, int proc)
void DestroyMail (Mail *mail, int proc)
int BootKernel (int procid)
Boots the kernel on another processor.
void DumpConfig ()
Variables
const char * tzname [2] = {"local","local"}
long timezone = 0
int daylight = 0
struct passwd _default_passwd = {"","",0,0,"","","",""}
Detailed Description
Implementation of some generic non-kernel OS functions.
Definition in file api.cc.
Define Documentation
#define _SCWRAP_ALL_TD (ret, fun, args...)
Value:
ASSERT(getpid()!=0,"Don't call the syscall wrapper from the taskdaemon");   \
    ret d ## fun(args,proc)
Definition at line 154 of file api.cc.
#define _SCWRAP_REMOTE_TD (ret, fun, args...)
Value:
ASSERT(getpid()!=0,"Don't call the syscall wrapper from the taskdaemon");   \
    if(proc==-1||proc==(int)GetProcID())    \
        ret l ## fun(args);                 \
    else                                    \
        ret d ## fun(args,proc)
Definition at line 165 of file api.cc.
#define SCWRAP_ALL_TD (fun, args...) _SCWRAP_ALL_TD(return,fun,args)
Definition at line 157 of file api.cc.
Referenced by AllocFifoEndPoint(), AllocMail(), CreateProcess(), DestroyProcess(), StartProcess(), and SyncEventHit().
#define SCWRAP_ALL_TDN (fun)
Value:
ASSERT(getpid()!=0,"Don't call the syscall wrapper from the taskdaemon");   \
    return d ## fun(proc)
Definition at line 161 of file api.cc.
Referenced by AllocSimpleMail().
#define SCWRAP_ALL_TDV (fun, args...) _SCWRAP_ALL_TD(,fun,args)
Definition at line 159 of file api.cc.
Referenced by DestroyFifoEndPoint(), and DestroyMail().
#define SCWRAP_REMOTE_TD (fun, args...) _SCWRAP_REMOTE_TD(return,fun,args)
Definition at line 171 of file api.cc.
Referenced by AllocChannels(), AssignChannel(), GetProcessFlags(), GetProcessState(), SendSignal(), SetChannelLabel(), SetProcessFlags(), and SetProcessTimeslice().
#define SCWRAP_REMOTE_TDV (fun, args...) _SCWRAP_REMOTE_TD(,fun,args)
Definition at line 173 of file api.cc.
Function Documentation
void _exit (int status)
Exits the calling process, without cleanup.
Forcably ends the process and the timeslice. Will never return.
For normal termination of a process, just use exit(). This function is for newlib and will be called when all cleanup has been done.
Parameters:
status the exit status of the process
Definition at line 95 of file api.cc.
References EndProcess().
void abort ()
Aborts the calling process.
Forcably ends the process and the timeslice. Will never return. The process return value will be set to -1.
Definition at line 70 of file api.cc.
References getpid().
Referenced by bitshark_auto_tune(), bitshark_auto_tune2(), CFifo< T, CFifo<>::w >::CFifo(), DefaultAbortSignalHandler(), PMC_NS::Error::format(), mc_error_handler(), CFifo< T, CFifo<>::w >::operator new(), operator new(), CFifo< T, CFifo<>::r >::operator new[](), operator new[](), pipe(), pipe_read(), pipe_write(), pthread_barrier_destroy(), pthread_barrier_init(), pthread_getspecific(), ring_printall(), and ring_stream_setup().
int AllocChannels (pid_t pid, int num_chan, int proc)
Definition at line 224 of file api.cc.
References AllocChannels(), and SCWRAP_REMOTE_TD.
Referenced by AllocChannels(), and map_start_task().
FifoEP* AllocFifoEndPoint (unsigned int fifo_size, unsigned int element_size, int flags, int proc)
Definition at line 236 of file api.cc.
References AllocFifoEndPoint(), and SCWRAP_ALL_TD.
Referenced by AllocFifoEndPoint(), and map_start_fifo().
Mail* AllocMail (unsigned int count, int proc)
Definition at line 240 of file api.cc.
References AllocMail(), and SCWRAP_ALL_TD.
Referenced by AllocMail(), and map_start_mail().
SimpleMail* AllocSimpleMail (int proc)
Definition at line 244 of file api.cc.
References AllocSimpleMail(), and SCWRAP_ALL_TDN.
Referenced by AllocSimpleMail(), and map_start_mail().
int AssignChannel (pid_t pid, int chan_id, void * channel, int label, int proc)
Definition at line 228 of file api.cc.
References AssignChannel(), and SCWRAP_REMOTE_TD.
Referenced by AssignChannel(), map_start_fifo(), and map_start_mail().
int BootKernel (int procid)
Boots the kernel on another processor.
When one of the wrapper functions like CreateProcess() is to be used, make sure that the other kernel is booted using BootKernel() or dBootKernels().
Nothing happens when procid is set to the current processor ID. Do not boot a processor twice.
When BootKernel() is called repeatedly for a list of processors, consider using dBootKernels() directly; that reduces the overhead significantly by skipping the already-booted check and booting all cores in parallel.
Parameters:
procid the ID of the processor to boot
Returns:
0 on success, otherwise an errno
Definition at line 272 of file api.cc.
References dBootKernels(), ESUCCESS, and GetProcID().
int CreateProcess (pid_t & pid, void *(*)(void *) main, void * arg, timems_t slicelength, size_t stack, int proc)
Definition at line 177 of file api.cc.
References CreateProcess(), main, and SCWRAP_ALL_TD.
Referenced by CreateProcess(), map_start_task(), pthread_create(), WorkQueue< T, W >::StartDispatcher(), WorkQueue< T, W >::StartSlaves(), and StartTimerDaemon().
void DestroyFifoEndPoint (FifoEP * fifo, int proc)
Definition at line 248 of file api.cc.
References DestroyFifoEndPoint(), and SCWRAP_ALL_TDV.
Referenced by DestroyFifoEndPoint(), map_start_fifo(), and map_stop_fifo().
void DestroyMail (Mail * mail, int proc)
Definition at line 252 of file api.cc.
References DestroyMail(), and SCWRAP_ALL_TDV.
Referenced by DestroyMail(), map_start_mail(), and map_stop_mail().
int DestroyProcess (pid_t pid, void ** ret, int proc)
Definition at line 208 of file api.cc.
References DestroyProcess(), and SCWRAP_ALL_TD.
Referenced by DestroyProcess(), map_start_task(), map_stop_task(), pthread_create(), StartTimerDaemon(), and WorkQueue< T, W >::~WorkQueue().
void DumpConfig ()
Definition at line 283 of file api.cc.
References CONTEXT_SWITCH_CYCLE_PANELTY, KERNEL_SYNC_EVENTS, MAX_PROCESSES, MAX_TIMERS, PROC_HEAP, PTHREAD_KEYS_MAX, STRINGIFY, and THREAD_LOCAL_FIELDS.
Referenced by kInitKernel().
pid_t getgpid ()
Returns a globally unique process ID of the current process, that includes information about the core it is mapped to.
Returns:
the global ID of the current process
Definition at line 24 of file api.cc.
References getgpid(), getpid(), and GetProcID().
Referenced by _pthread_cond_wait(), dLockAsk(), dLockGiveup(), dLockRequest(), getgpid(), lck_migrate(), lck_pass_p(), lck_unlock(), pthread_create(), and pthread_self().
pid_t getgpid (pid_t pid, unsigned int proc)
Returns a globally unique process ID of the specified process, that includes information about the core it is mapped to.
Returns:
the global ID
Definition at line 32 of file api.cc.
References MAX_PROCESSES.
unsigned int getgpidproc (pid_t gpid)
Returns the processor ID the process runs on.
Parameters:
gpid the process ID to find the processor of
Returns:
the processor ID
Definition at line 50 of file api.cc.
References MAX_PROCESSES.
Referenced by dLockAsk(), lck_ask(), lck_migrate(), pthread_detach(), pthread_join(), pthread_kill(), and se_create_pta().
pid_t getlpid (pid_t gpid)
Returns the local process ID, which is used on the processor the process runs on.
Parameters:
gpid the process ID to find the local process ID of
Returns:
the local ID
Definition at line 41 of file api.cc.
References MAX_PROCESSES.
Referenced by dLockAsk(), pthread_detach(), pthread_join(), pthread_kill(), and se_create_pta().
int GetProcessFlags (pid_t pid, int * flags, int proc)
Definition at line 181 of file api.cc.
References GetProcessFlags(), and SCWRAP_REMOTE_TD.
Referenced by GetProcessFlags(), pthread_detach(), and ShutdownDaemon().
int GetProcessState (pid_t pid, proc_state_t * state, bool * sighandling, int proc)
Definition at line 189 of file api.cc.
References GetProcessState(), and SCWRAP_REMOTE_TD.
Referenced by GetProcessState().
struct passwd* getpwnam (const char * name) [read]
Definition at line 134 of file api.cc.
References _default_passwd.
pid_t getupid ()
Definition at line 54 of file api.cc.
References ASSERT, getpid(), lGetProcessState(), MAX_PROCESSES, and pid.
Referenced by calloc(), free(), freeAll(), GetIssueSlot(), mown(), omalloc(), orealloc(), and StopMallocDaemon().
void* helix_rpc (void *(*)(void *) fun, void * arg, int proc)
Definition at line 138 of file api.cc.
References dRemoteCall().
int printf_nt (const char * format, ...)
Definition at line 142 of file api.cc.
int SendSignal (pid_t pid, int sig, union sigval * sv, int proc)
Definition at line 216 of file api.cc.
References SCWRAP_REMOTE_TD, and SendSignal().
Referenced by pipe_write(), pthread_kill(), SendSignal(), and ShutdownDaemon().
int SetChannelLabel (pid_t pid, int chan_id, int label, int proc)
Definition at line 232 of file api.cc.
References SCWRAP_REMOTE_TD, and SetChannelLabel().
Referenced by SetChannelLabel().
int SetProcessFlags (pid_t pid, int flags, int proc)
Definition at line 185 of file api.cc.
References SCWRAP_REMOTE_TD, and SetProcessFlags().
Referenced by pthread_create(), pthread_detach(), SetProcessFlags(), and ShutdownDaemon().
int SetProcessTimeslice (pid_t pid, timems_t timeslice, int proc)
Definition at line 212 of file api.cc.
References SCWRAP_REMOTE_TD, and SetProcessTimeslice().
Referenced by SetProcessTimeslice().
int StartProcess (pid_t pid, int proc)
Definition at line 193 of file api.cc.
References SCWRAP_ALL_TD, and StartProcess().
Referenced by map_start_task(), pthread_create(), WorkQueue< T, W >::StartDispatcher(), StartProcess(), WorkQueue< T, W >::StartSlaves(), and StartTimerDaemon().
int SyncEventHit (pid_t pid, void * event, int proc)
Definition at line 220 of file api.cc.
References SCWRAP_ALL_TD, and SyncEventHit().
Referenced by syncevent_t< N >::hit(), and SyncEventHit().
long sysconf (int name)
Definition at line 100 of file api.cc.
References CACHELINE_ALIGN, GetClockFreq(), GetHook(), HOOK_CORES, and MAX_PROCESSES.
Referenced by DumpStatsDaemon(), find_cpu(), GetIssueSlot(), rc_flush_(), rc_init(), times(), and TraceDumpAll().
int WaitProcess (pid_t pid, void ** ret, int proc)
Definition at line 197 of file api.cc.
References ASSERT, dWaitProcess(), getpid(), GetProcID(), lJoinProcess(), and Yield().
Referenced by pthread_join().
Variable Documentation
struct passwd _default_passwd = {"","",0,0,"","","",""}
Definition at line 130 of file api.cc.
Referenced by getpwnam().
int daylight = 0
Definition at line 13 of file api.cc.
long timezone = 0
Definition at line 12 of file api.cc.
Referenced by gettimeofday().
const char* tzname[2] = {"local","local"}
Definition at line 11 of file api.cc.