Starburst: posix/barrier.cc File Reference
posix/barrier.cc File Reference
POSIX barrier implementation, with software cache coherency.
#include <pthread.h>
#include <sys/syscall.h>
#include <sys/helix_config.h>
#include <sys/api.h>
#include <mc.h>
Defines
#define pthread_stats_elem_register(...)
#define pthread_stats_elem_unregister(...)
#define pthread_stats_global_init(...) 0
#define pthread_stats_global_cleanup(...) 0
#define pthread_stats_thread_init(...) 0
Functions
int pthread_barrier_destroy (pthread_barrier_t *bar)
int pthread_barrier_init (pthread_barrier_t *bar, const pthread_barrierattr_t *attr, unsigned int count)
int pthread_barrier_wait (pthread_barrier_t *bar)
int pthread_barrierattr_destroy (pthread_barrierattr_t *attr)
int pthread_barrierattr_init (pthread_barrierattr_t *attr)
int pthread_barrierattr_getpshared (const pthread_barrierattr_t *attr, int *pshared)
int pthread_barrierattr_setpshared (pthread_barrierattr_t *attr, int pshared)
int pthread_barrier_global_init ()
int pthread_barrier_global_cleanup ()
int pthread_barrier_thread_init ()
int pthread_barrier_thread_cleanup ()
Detailed Description
POSIX barrier implementation, with software cache coherency.
Definition in file barrier.cc.
Define Documentation
#define pthread_stats_elem_register (...)
Definition at line 10 of file barrier.cc.
Referenced by pthread_barrier_init(), pthread_cond_init(), and pthread_mutex_init().
#define pthread_stats_elem_unregister (...)
Definition at line 11 of file barrier.cc.
Referenced by pthread_barrier_destroy(), pthread_cond_destroy(), and pthread_mutex_destroy().
#define pthread_stats_global_cleanup (...) 0
Definition at line 13 of file barrier.cc.
Referenced by pthread_barrier_global_cleanup(), pthread_cond_global_cleanup(), and pthread_mutex_global_cleanup().
#define pthread_stats_global_init (...) 0
Definition at line 12 of file barrier.cc.
Referenced by pthread_barrier_global_init(), pthread_cond_global_init(), and pthread_mutex_global_init().
#define pthread_stats_thread_init (...) 0
Definition at line 14 of file barrier.cc.
Referenced by pthread_barrier_thread_init(), pthread_cond_thread_init(), and pthread_mutex_thread_init().
Function Documentation
int pthread_barrier_destroy (pthread_barrier_t * bar)
Definition at line 161 of file barrier.cc.
References abort(), pthread_barrier_t::attr, pthread_barrier_t::counter, mc_entry_ro, mc_exit_ro, pthread_barrierattr_destroy(), and pthread_stats_elem_unregister.
int pthread_barrier_global_cleanup (void)
Definition at line 324 of file barrier.cc.
References pthread_stats_global_cleanup.
Referenced by pthread_global_cleanup().
int pthread_barrier_global_init (void)
Definition at line 320 of file barrier.cc.
References pthread_stats_global_init.
Referenced by pthread_global_init().
int pthread_barrier_init (pthread_barrier_t * bar, const pthread_barrierattr_t * attr, unsigned int count)
Definition at line 183 of file barrier.cc.
References abort(), pthread_barrier_t::attr, pthread_barrier_t::counter, mc_entry_wou, mc_exit_wou, pthread_barrier_t::participants, pthread_barrierattr_init(), pthread_stats_elem_register, and pthread_barrier_t::queue.
Referenced by dvi_screen::Init(), and ShutdownDaemonInit().
int pthread_barrier_thread_cleanup (void)
Definition at line 332 of file barrier.cc.
Referenced by pthread_thread_cleanup().
int pthread_barrier_thread_init (void)
Definition at line 328 of file barrier.cc.
References pthread_stats_thread_init.
Referenced by pthread_thread_init().
int pthread_barrier_wait (pthread_barrier_t * bar)
Definition at line 212 of file barrier.cc.
References ASSERT, pthread_barrier_t::counter, lck_lock_p(), lck_pass(), lck_unlock(), mc_entry_rw, mc_exit_rw, pthread_barrier_t::participants, PTHREAD_BARRIER_SERIAL_THREAD, pthread_kill(), pthread_self(), pthread_barrier_t::queue, sigblock(), SIGSYNC, TIMESTAMP_GET, TIMESTAMP_SET, and unlikely.
Referenced by ShutdownDaemon().
int pthread_barrierattr_destroy (pthread_barrierattr_t * attr)
Definition at line 293 of file barrier.cc.
Referenced by pthread_barrier_destroy().
int pthread_barrierattr_getpshared (const pthread_barrierattr_t * attr, int * pshared)
Definition at line 306 of file barrier.cc.
References pthread_barrierattr_t::pshared.
int pthread_barrierattr_init (pthread_barrierattr_t * attr)
Definition at line 299 of file barrier.cc.
References pthread_barrierattr_t::pshared, and PTHREAD_PROCESS_PRIVATE.
Referenced by pthread_barrier_init().
int pthread_barrierattr_setpshared (pthread_barrierattr_t * attr, int pshared)
Definition at line 313 of file barrier.cc.
References pthread_barrierattr_t::pshared.