Starburst: include/bitshark/bitshark.h File Reference
include/bitshark/bitshark.h File Reference
#include <sys/api.h>
#include <stdint.h>
#include "uartlite.h"
Data Structures
struct bitshark_ctrl_dev_t
struct bitshark_dev_t
To simplify for users which pointer is expected in function calls, the pointers to the Bitshark UART on the Bitshark card and the Bitshark controller on the FPGA are unified in one structure.
struct spi_register_t
union spi_wrapper_t
union iq_t
struct complex_t
union iqu_t
Defines
#define BITSHARK_DEBUG 0
#define bsprintf(...)
#define BITSHARK_DRIVER_VERSION 0x0008
#define BITSHARK_MAX_ADCLK 24000000
#define MACRO_BITSET(r, mask, b) ((r) = ((b) == 0) ? (r) & ~(mask) : (r) | (mask))
#define BITSHARK_DEBUG_FLAG 1u
#define BITSHARK_DCOFFSET_FLAG 2u
#define BITSHARK_CLEAR_FLAG 4u
#define BITSHARK_LPF_FLAG 8u
#define BITSHARK_COEF_FLAG 16u
#define BITSHARK_BAL_FLAG 32u
#define BITSHARK_RETUNE_FLAG 64u
#define BITSHARK_DECIMATION_RANGE 0xFF00u
#define bitshark_debug_enabled(bs) ((bs)->ctrl->ctrl_reg & BITSHARK_DEBUG_FLAG)
#define bitshark_dc_offset_enabled(bs) ((bs)->ctrl->ctrl_reg & BITSHARK_DCOFFSET_FLAG)
#define bitshark_lpf_enabled(bs) ((bs)->ctrl->ctrl_reg & BITSHARK_LPF_FLAG)
#define bitshark_iqbal_enabled(bs) ((bs)->ctrl->ctrl_reg & BITSHARK_BAL_FLAG)
#define bitshark_retune_enabled(bs) ((bs)->ctrl->ctrl_reg & BITSHARK_RETUNE_FLAG)
#define bitshark_set_debug(bs, b) MACRO_BITSET((bs)->ctrl->ctrl_reg, BITSHARK_DEBUG_FLAG, b)
#define bitshark_set_dc_offset(bs, b) ((bs)->ctrl->ctrl_reg = ((b) == 0) ? (bs)->ctrl->ctrl_reg & ~BITSHARK_DCOFFSET_FLAG : (bs)->ctrl->ctrl_reg | BITSHARK_DCOFFSET_FLAG)
#define bitshark_set_lpf(bs, b) ((bs)->ctrl->ctrl_reg = ((b) == 0) ? (bs)->ctrl->ctrl_reg & ~BITSHARK_LPF_FLAG : (bs)->ctrl->ctrl_reg | BITSHARK_LPF_FLAG)
#define bitshark_set_iqbal(bs, b) ((bs)->ctrl->ctrl_reg = ((b) == 0) ? (bs)->ctrl->ctrl_reg & ~BITSHARK_BAL_FLAG : (bs)->ctrl->ctrl_reg | BITSHARK_BAL_FLAG)
#define bitshark_clear(bs) (bs)->ctrl->ctrl_reg = ((bs)->ctrl->ctrl_reg | BITSHARK_CLEAR_FLAG); (bs)->ctrl->ctrl_reg = ((bs)->ctrl->ctrl_reg & ~BITSHARK_CLEAR_FLAG);
#define bitshark_set_decimate(bs, n) (bs)->ctrl->ctrl_reg = ((bs)->ctrl->ctrl_reg & ~BITSHARK_DECIMATION_RANGE) | ((n & 0xFFu) << 8);
#define bitshark_get_decimate(bs) (unsigned int)(((bs)->ctrl->ctrl_reg & BITSHARK_DECIMATION_RANGE) >> 8)
#define bitshark_begin_coef_load(bs) (bs)->ctrl->ctrl_reg = ((bs)->ctrl->ctrl_reg | BITSHARK_COEF_FLAG); (bs)->ctrl->ctrl_reg = ((bs)->ctrl->ctrl_reg & ~BITSHARK_COEF_FLAG);
#define bitshark_set_retune(bs, b) MACRO_BITSET((bs)->ctrl->ctrl_reg, BITSHARK_RETUNE_FLAG, b)
#define bitshark_has_error(bs) ((bs)->ctrl->error_reg != 0)
#define bitshark_clear_error(bs) ((bs)->ctrl->error_reg = 0)
#define bitshark_get_hw_version(bs) ((unsigned short)((bs)->ctrl->version_reg & 0xFFFF))
#define BS_NO_ERR 0x0
#define BS_ERR_SAMPLE_RATE 0x2000
#define BS_ERR_FREQ 0x2001
#define BS_ERR_BW 0x2002
#define BS_ERR_BAL 0x3000
#define BS_ERR_OTHER 0x3000
Functions
int bitshark_init (bitshark_dev_t *bs)
Initialize the ADC in order to get a valid signal.
static int bitshark_read (bitshark_dev_t *bs, iq_t *iq) __attribute__((always_inline))
Read an IQ sample from the BitShark board.
iq_t bitshark_read_debug (bitshark_dev_t *bs)
Read a debug value straight from the internal counter.
int bitshark_test_debug_value (bitshark_dev_t *bs)
Debug function: Test if a raw read from the Bitshark data FIFO is a valid debug value.
int bitshark_test_debug (bitshark_dev_t *bs, unsigned int num_read, int use_buffer, int verbose)
Debug function: This function will attempt to read a specified number of samples from the debug register on the BitShark control interface.
int bitshark_auto_calibrate (bitshark_dev_t *bs)
Debug function: Utility function to determine the maximum sample rate on a MicroBlaze.
int bitshark_cmd_write (bitshark_dev_t *bs, char *cmd, int verbose)
int bitshark_cmd_write (bitshark_dev_t *bs, char *cmd, char *response, int verbose)
Send a raw command to the Bitshark UART interface.
int bitshark_cmd_get_iqbal (bitshark_dev_t *bs, int freq_kH, iq_t *iqbal, int verbose)
Read IQ balance data from the Bitshark given a specific frequency.
int bitshark_cmd_get_iqbal (bitshark_dev_t *bs, int freq_kH, complex_t *iqbal, int verbose)
int bitshark_cmd_write_freq (bitshark_dev_t *bs, int freq_kH, int verbose)
int bitshark_cmd_write_adclk (bitshark_dev_t *bs, int freq_H, int verbose)
Set the A/D clock frequency in hertz from 5 MHz to 105MHz.
int bitshark_cmd_write_chanbw (bitshark_dev_t *bs, int width_kHz, int verbose)
Set the bandwidth filter of the Bitshark hardware.
int bitshark_cmd_write_rfgain (bitshark_dev_t *bs, float gain_dB, int verbose)
Set the RF gain at the Bitshark (see the FMC-1RX manual for details).
int bitshark_cmd_write_bbgain (bitshark_dev_t *bs, int gain_dB, int verbose)
Set the baseband gain at the Bitshark (see the FMC-1RX manual for details).
int bitshark_cmd_read_adclk (bitshark_dev_t *bs, int *freq_H, int verbose)
Read the actual A/D clock value from the Bitshark in hertz.
int bitshark_cmd_read_chanbw (bitshark_dev_t *bs, int *chanbw, int verbose)
int bitshark_verify_clk (bitshark_dev_t *bs)
Debug function: Calculate the approximate clock frequency of the BitShark LVDS data stream based on the debug counter and the internal timer.
float bitshark_shift_spectrum (bitshark_dev_t *bs, float offset, unsigned adclk, int verbose=0)
Internal utility function: set up the internal CORDIC to shift the spectrum by the requested offset.
int bitshark_auto_tune (bitshark_dev_t *bs, unsigned int rate_Ss, unsigned int freq_kHz, unsigned int bw_kHz, unsigned int *real_rate_Ss, int verbose)
Utility function to quickly tune into a specific frequency with appropriate bandwidth selection.
int bitshark_auto_tune2 (bitshark_dev_t *bs, unsigned int samplerate, unsigned int freq_kHz, unsigned int bw_kHz, unsigned *real_samplerate_p, int verbose)
Utility function to quickly tune into a specific frequency with appropriate bandwidth selection.
float bitshark_decode_fp (unsigned short input, int bits, int fractional)
Decode a fixed point number into a floating point value.
int bitshark_load_iqbal (bitshark_dev_t *bs, iq_t *iq, int verbose)
Load channel balancer with the given values where I is C and Q is D.
int bitshark_use_ring (bitshark_dev_t *bs)
Determine whether the BitShark receiver will send out data using the ring bus.
int bitshark_use_ring (bitshark_dev_t *bs, int mode)
Switch between ring bus streaming data output or PLB polled data mode.
int bitshark_ring_streaming (bitshark_dev_t *bs)
When using the ring output, the data stream can be started and stopped.
unsigned int bitshark_ring_stream (bitshark_dev_t *bs, int enable)
Use this function to start or stop the data stream to the ring bus (assuming the ring bus mode is selected)
Variables
bitshark_dev_t bitshark_dev
Define Documentation
#define BITSHARK_BAL_FLAG 32u
Definition at line 420 of file bitshark.h.
#define bitshark_begin_coef_load (bs) (bs)->ctrl->ctrl_reg = ((bs)->ctrl->ctrl_reg | BITSHARK_COEF_FLAG); (bs)->ctrl->ctrl_reg = ((bs)->ctrl->ctrl_reg & ~BITSHARK_COEF_FLAG);
Definition at line 441 of file bitshark.h.
Referenced by fir_load_coef().
#define bitshark_clear (bs) (bs)->ctrl->ctrl_reg = ((bs)->ctrl->ctrl_reg | BITSHARK_CLEAR_FLAG); (bs)->ctrl->ctrl_reg = ((bs)->ctrl->ctrl_reg & ~BITSHARK_CLEAR_FLAG);
Definition at line 436 of file bitshark.h.
Referenced by bitshark_auto_tune(), bitshark_auto_tune2(), and bitshark_test_debug().
#define bitshark_clear_error (bs) ((bs)->ctrl->error_reg = 0)
Definition at line 448 of file bitshark.h.
#define BITSHARK_CLEAR_FLAG 4u
Definition at line 417 of file bitshark.h.
#define BITSHARK_COEF_FLAG 16u
Definition at line 419 of file bitshark.h.
#define bitshark_dc_offset_enabled (bs) ((bs)->ctrl->ctrl_reg & BITSHARK_DCOFFSET_FLAG)
Definition at line 426 of file bitshark.h.
#define BITSHARK_DCOFFSET_FLAG 2u
Definition at line 416 of file bitshark.h.
#define BITSHARK_DEBUG 0
Definition at line 20 of file bitshark.h.
#define bitshark_debug_enabled (bs) ((bs)->ctrl->ctrl_reg & BITSHARK_DEBUG_FLAG)
Definition at line 425 of file bitshark.h.
#define BITSHARK_DEBUG_FLAG 1u
Definition at line 415 of file bitshark.h.
#define BITSHARK_DECIMATION_RANGE 0xFF00u
Definition at line 422 of file bitshark.h.
#define BITSHARK_DRIVER_VERSION 0x0008
Definition at line 407 of file bitshark.h.
Referenced by bitshark_compatible_version(), and bitshark_init().
#define bitshark_get_decimate (bs) (unsigned int)(((bs)->ctrl->ctrl_reg & BITSHARK_DECIMATION_RANGE) >> 8)
Definition at line 439 of file bitshark.h.
Referenced by bitshark_get_samplerate(), and bitshark_test_debug().
#define bitshark_get_hw_version (bs) ((unsigned short)((bs)->ctrl->version_reg & 0xFFFF))
Definition at line 451 of file bitshark.h.
Referenced by bitshark_compatible_version(), and bitshark_init().
#define bitshark_has_error (bs) ((bs)->ctrl->error_reg != 0)
Definition at line 446 of file bitshark.h.
#define bitshark_iqbal_enabled (bs) ((bs)->ctrl->ctrl_reg & BITSHARK_BAL_FLAG)
Definition at line 428 of file bitshark.h.
#define bitshark_lpf_enabled (bs) ((bs)->ctrl->ctrl_reg & BITSHARK_LPF_FLAG)
Definition at line 427 of file bitshark.h.
#define BITSHARK_LPF_FLAG 8u
Definition at line 418 of file bitshark.h.
#define BITSHARK_MAX_ADCLK 24000000
Definition at line 408 of file bitshark.h.
Referenced by bitshark_auto_tune2().
#define bitshark_retune_enabled (bs) ((bs)->ctrl->ctrl_reg & BITSHARK_RETUNE_FLAG)
Definition at line 429 of file bitshark.h.
#define BITSHARK_RETUNE_FLAG 64u
Definition at line 421 of file bitshark.h.
#define bitshark_set_dc_offset (bs, b) ((bs)->ctrl->ctrl_reg = ((b) == 0) ? (bs)->ctrl->ctrl_reg & ~BITSHARK_DCOFFSET_FLAG : (bs)->ctrl->ctrl_reg | BITSHARK_DCOFFSET_FLAG)
Definition at line 432 of file bitshark.h.
#define bitshark_set_debug (bs, b) MACRO_BITSET((bs)->ctrl->ctrl_reg, BITSHARK_DEBUG_FLAG, b)
Definition at line 431 of file bitshark.h.
Referenced by bitshark_test_debug().
#define bitshark_set_decimate (bs, n) (bs)->ctrl->ctrl_reg = ((bs)->ctrl->ctrl_reg & ~BITSHARK_DECIMATION_RANGE) | ((n & 0xFFu) << 8);
Definition at line 438 of file bitshark.h.
Referenced by bitshark_auto_calibrate(), bitshark_auto_tune(), and bitshark_auto_tune2().
#define bitshark_set_iqbal (bs, b) ((bs)->ctrl->ctrl_reg = ((b) == 0) ? (bs)->ctrl->ctrl_reg & ~BITSHARK_BAL_FLAG : (bs)->ctrl->ctrl_reg | BITSHARK_BAL_FLAG)
Definition at line 434 of file bitshark.h.
Referenced by bitshark_auto_tune(), and bitshark_auto_tune2().
#define bitshark_set_lpf (bs, b) ((bs)->ctrl->ctrl_reg = ((b) == 0) ? (bs)->ctrl->ctrl_reg & ~BITSHARK_LPF_FLAG : (bs)->ctrl->ctrl_reg | BITSHARK_LPF_FLAG)
Definition at line 433 of file bitshark.h.
Referenced by bitshark_auto_tune(), and bitshark_auto_tune2().
#define bitshark_set_retune (bs, b) MACRO_BITSET((bs)->ctrl->ctrl_reg, BITSHARK_RETUNE_FLAG, b)
Definition at line 443 of file bitshark.h.
Referenced by bitshark_auto_tune(), and bitshark_shift_spectrum().
#define BS_ERR_BAL 0x3000
Definition at line 458 of file bitshark.h.
Referenced by bitshark_load_iqbal().
#define BS_ERR_BW 0x2002
Definition at line 457 of file bitshark.h.
Referenced by bitshark_auto_tune(), and bitshark_auto_tune2().
#define BS_ERR_FREQ 0x2001
Definition at line 456 of file bitshark.h.
Referenced by bitshark_auto_tune(), and bitshark_auto_tune2().
#define BS_ERR_OTHER 0x3000
Definition at line 460 of file bitshark.h.
Referenced by bitshark_auto_tune(), and bitshark_auto_tune2().
#define BS_ERR_SAMPLE_RATE 0x2000
Definition at line 455 of file bitshark.h.
Referenced by bitshark_auto_tune(), and bitshark_auto_tune2().
#define BS_NO_ERR 0x0
Definition at line 454 of file bitshark.h.
Referenced by bitshark_auto_tune(), bitshark_auto_tune2(), and bitshark_load_iqbal().
#define bsprintf (...)
Definition at line 24 of file bitshark.h.
Referenced by adc_init_spi().
#define MACRO_BITSET (r, mask, b) ((r) = ((b) == 0) ? (r) & ~(mask) : (r) | (mask))
Definition at line 412 of file bitshark.h.
Function Documentation
int bitshark_auto_calibrate (bitshark_dev_t * bs)
Debug function: Utility function to determine the maximum sample rate on a MicroBlaze.
This function tests to see if consecutive debug values can be read from the device. If this fails, the decimation factor is increased and the test is performed again. Note: this function is used to verify the functioning of the Bitshark and to get an idea of feasible sample rates from the Bitshark device. All feedback is printed to the console in this function, only success and error values are returned.
Parameters:
*bs Handle to the Bitshark device
Returns:
0 when an error occurred during testing or 1 when the test completed and a working decimation factor was found
Debug function: Utility function to determine the maximum sample rate on a MicroBlaze.
This function tests to see if consecutive debug values can be read from the device. If this fails, the decimation factor is increased and the test is performed again. Note: this function is used to verify the functioning of the Bitshark and to get an idea of feasible sample rates from the Bitshark device. All feedback is printed to the console in this function, only success and error values are returned.
Parameters:
*bs Handle to the Bitshark device
Returns:
0 when an error occurred during testing or 1 when the test completed and a working decimation factor was found
Definition at line 313 of file bitshark.cc.
References bitshark_set_decimate, bitshark_test_debug(), and bitshark_verify_clk().
int bitshark_auto_tune (bitshark_dev_t * bs, unsigned int rate_Ss, unsigned int freq_kHz, unsigned int bw_kHz, unsigned int * real_rate_Ss, int verbose)
Utility function to quickly tune into a specific frequency with appropriate bandwidth selection.
The filtering of the signal is done with a mix of analog and digital filters. As the MicroBlaze processor cannot handle capture speeds in excess of 5 MS/s (which means 20 cycles per sample), the sample rate of the A/D converter will be set to ~5 MS/s which will be decimated to approximately the desired sample rate.
The frequency range is 300 MHz to 4000 MHz in kHz steps, the bandwidth selection ranges from 1 kHz to 2.5 MHz. Note: that the bandwidth selection has to be within the bandwidth dictated by the sample rate and the Nyquist frequency. Note: the digital filters are designed for sample rates up to 10 MS/s, as such, the A/D speed is fixed on ~5 MS/s.
Parameters:
bs Handle to the Bitshark device
rate_Ss Sample rate per second, range: 19,532 to 5,000,000 - the value will be updated with the actual sample rate
freq_kHz The frequency in kHz ranging from 300 MHz to 2 GHz
bw_kHz The bandwidth, the actual bandwidth will be at most Fsample/2 to prevent aliasing
real_rate_Ss Pointer to a unsigned int which will contain the actual sample rate (as the sample rate will be approximated)
verbose Enable to help with debugging
Returns:
0 if all ok or an error code otherwise
The filtering of the signal is done with a mix of analog and digital filters. As the MicroBlaze processor cannot handle capture speeds in excess of 5 MS/s (which means 20 cycles per sample), the sample rate of the A/D converter will be set to ~5 MS/s which will be decimated to approximately the desired sample rate.
The frequency range is 300 MHz to 4000 MHz in kHz steps, the bandwidth selection ranges from 1 kHz to 2.5 MHz. Note: that the bandwidth selection has to be within the bandwidth dictated by the sample rate and the Nyquist frequency. Note: the digital filters are designed for sample rates up to 10 MS/s, as such, the A/D speed is fixed on ~5 MS/s.
Parameters:
bs Handle to the Bitshark device
rate_Ss Sample rate per second, range: 19,532 to 5,000,000 - the value will be updated with the actual sample rate
freq_kHz The frequency in kHz ranging from 300 MHz to 2 GHz
bw_kHz The bandwidth, the actual bandwidth will be at most Fsample/2 to prevent aliasing
real_rate_Ss Pointer to a unsigned int which will contain the actual sample rate (as the sample rate will be approximated)
verbose Make the tuning verbose for debugging purposes
Returns:
0 if all ok or an error code otherwise
Definition at line 717 of file bitshark.cc.
References abort(), bitshark_clear, bitshark_cmd_get_iqbal(), bitshark_cmd_write_adclk(), bitshark_cmd_write_chanbw(), bitshark_cmd_write_freq(), bitshark_load_iqbal(), bitshark_set_decimate, bitshark_set_iqbal, bitshark_set_lpf, bitshark_set_retune, bitshark_validate_bandwidth(), BS_ERR_BW, BS_ERR_FREQ, BS_ERR_OTHER, BS_ERR_SAMPLE_RATE, BS_NO_ERR, fir_load_coef(), and fir_lpf_gen_sinc().
int bitshark_auto_tune2 (bitshark_dev_t * bs, unsigned int samplerate, unsigned int freq_kHz, unsigned int bw_kHz, unsigned * real_samplerate_p, int verbose)
Utility function to quickly tune into a specific frequency with appropriate bandwidth selection.
The filtering of the signal is done with a mix of analog and digital filters.
This function handles the automatic spectrum shift to work around the DC gap of the physical receiver. Note that this means the derived A/D clock has to be supported by the FIR filters: you will get an error if this is not the case.
The actual tuning is done by assuming that the band between -Fs/4 and Fs/4 is actually desired. As the DC gap will ruin the data, the tuner is set to roughly (Ftune - Fs/4) and the sample speed is doubled. Using the internal CORDIC, the complex spectrum is shifted by -Fs/4 and filtered down to the band from -Fs/4 to Fs/4 using the FIR filters and decimated to the requested samplerate. As such, this whole chain is invisible to the programmer when this function is used.
WARNING: Because we attempt to approximate the sample frequency and are restricted by the integer decimation, its near impossible to skip the DC gap entirely: it *will* show up in the spectrum at the negative side of the bandwidth. Make sure you are aware of the 30kHz band with -40dB atenuation at the edge.
The settings used for the various parts of the receiver will result in an approximation of the requested parameters; use the feedback variables to make sure the result is what you expect.
Note: that the bandwidth selection has to be within the bandwidth dictated by the sample rate and the Nyquist frequency.
Note: the digital filters are designed for sample rates up to 10 MS/s, as such, the A/D speed is limited to that rate.
Parameters:
bs Handle to the Bitshark device
samplerate Samplerate per second, range: 19,532 to 10,000,000
freq_kHz The frequency in kHz ranging from 300 MHz to 2 GHz
bw_kHz The bandwidth, the actual bandwidth will be at most samplerate/2 to prevent aliasing
real_samplerate_p Pointer to a unsigned int which will contain the actual sample rate in Hz (as the sample rate will be approximated)
verbose Make the tuning verbose for debugging purposes
Returns:
0 if all ok or an error code otherwise
The filtering of the signal is done with a mix of analog and digital filters.
This function handles the automatic spectrum shift to work around the DC gap of the physical receiver. Note that this means the derived A/D clock has to be supported by the FIR filters: you will get an error if this is not the case.
The actual tuning is done by assuming that the band between -Fs/4 and Fs/4 is actually desired. As the DC gap will ruin the data, the tuner is set to roughly (Ftune - Fs/4) and the sample speed is increased. Using the internal CORDIC, the complex spectrum is shifted by -Fs/4 and filtered down to the band from -Fs/4 to Fs/4 using the FIR filters and decimated to the requested samplerate. As such, this whole chain is invisible to the programmer when this function is used.
WARNING: Because we attempt to approximate the sample frequency and are restricted by the integer decimation, its near impossible to skip the DC gap entirely: it *will* show up in the spectrum at the negative side of the bandwidth. Make sure you are aware of the 30kHz band with -40dB atenuation at the edge.
The settings used for the various parts of the receiver will result in an approximation of the requested parameters; use the feedback variables to make sure the result is what you expect.
Note: that the bandwidth selection has to be within the bandwidth dictated by the sample rate and the Nyquist frequency.
Note: the digital filters are designed for sample rates up to 24 MS/s which is a limit in the tuning.
Note: channel balancing is enabled by default.
Parameters:
bs Handle to the Bitshark device
samplerate Samplerate per second, range: 19,532 to 24,000,000
freq_kHz The frequency in kHz ranging from 300 MHz to 2 GHz
bw_kHz The bandwidth for the low pass filter, the actual bandwidth will be at most samplerate/2 to prevent aliasing
real_samplerate_p Pointer to a unsigned int which will contain the actual sample rate in Hz (as the sample rate will be approximated)
verbose Make the tuning verbose for debugging purposes
Returns:
0 if all ok or an error code otherwise
Definition at line 870 of file bitshark.cc.
References abort(), bitshark_clear, bitshark_cmd_get_iqbal(), bitshark_cmd_write_adclk(), bitshark_cmd_write_chanbw(), bitshark_cmd_write_freq(), bitshark_load_iqbal(), BITSHARK_MAX_ADCLK, bitshark_set_decimate, bitshark_set_iqbal, bitshark_set_lpf, bitshark_shift_spectrum(), bitshark_validate_bandwidth(), BS_ERR_BW, BS_ERR_FREQ, BS_ERR_OTHER, BS_ERR_SAMPLE_RATE, BS_NO_ERR, fir_load_coef(), and fir_lpf_gen_sinc().
int bitshark_cmd_get_iqbal (bitshark_dev_t * bs, int freq_kH, iq_t * iqbal, int verbose)
Read IQ balance data from the Bitshark given a specific frequency.
The Bitshark is calibrated to balance the I and Q channel from the ADC and remove unwanted frequency components from the imbalance between channels. This function loads the balance values into the IQ struct in 'iqbal'. Use for example bitshark_decode_fp() with FIX_10_6 format to decode into floating point. Apply to Q as so: Q_new = C*I + D*Q where C = iqbal.I and D = iqbal.Q.
Parameters:
*bs Handle to the Bitshark device
freq_kH Frequency too look up in kHz, valid range: 300000 to 4000000
*iqbal Pointer to the IQ struct to load the balance values into
verbose Enable debug output
Returns:
True when all OK or false when something failed
The Bitshark is calibrated to balance the I and Q channel from the ADC and remove unwanted frequency components from the imbalance between channels. This function loads the balance values into the I-Q struct in 'iqbal'.
Parameters:
*bs Handle to the Bitshark control device
freq_kH Frequency too look up in kHz, valid range: 300000 to 4000000
*iqbal Pointer to the IQ struct to load the balance values into
verbose Enable debug output
Returns:
True when all OK or false when something failed
Definition at line 468 of file bitshark.cc.
References bitshark_cmd_write(), bitshark_parse_hex(), cmd, data, iq_t::I, Q, and iq_t::Q.
Referenced by bitshark_auto_tune(), bitshark_auto_tune2(), and bitshark_cmd_get_iqbal().
int bitshark_cmd_get_iqbal (bitshark_dev_t * bs, int freq_kH, complex_t * iqbal, int verbose)
See also:
bitshark_cmd_get_iqbal(bitshark_dev_t *bs, int freq_kH, iq_t *iqbal, int verbose) Identical aside from the decoding into floating point values for the balancing.
Definition at line 512 of file bitshark.cc.
References bitshark_cmd_get_iqbal(), bitshark_decode_fp(), iq_t::I, complex_t::i, iq_t::Q, and complex_t::r.
int bitshark_cmd_read_adclk (bitshark_dev_t * bs, int * freq_H, int verbose)
Read the actual A/D clock value from the Bitshark in hertz.
Parameters:
bs Pointer to the Bitshark device
freq_H Pointer to a 32-bit integer to fill with the actual value
verbose Perform verbose communication which shows the communication on the console
Returns:
1 if all ok or an error code otherwise
Warning: when using the auto-tuning, this will return the sample rate from the ADCs, the actual sample rate of the data output might not be identical! Use bitshark_get_samplerate to get the actual sample rate.
Parameters:
bs Handle to the Bitshark device
freq_H Pointer to a 32-bit integer to fill with the actual value
verbose Perform verbose communication which shows the communication on the console
Returns:
1 if all ok or an error code otherwise
Definition at line 593 of file bitshark.cc.
References bitshark_cmd_write(), cmd, and data.
Referenced by bitshark_get_samplerate().
int bitshark_cmd_read_chanbw (bitshark_dev_t * bs, int * chanbw, int verbose)
Definition at line 622 of file bitshark.cc.
References bitshark_cmd_write(), cmd, and data.
int bitshark_cmd_write (bitshark_dev_t * bs, char * cmd, int verbose)
See also:
'int bitshark_cmd_write(bitshark_dev_t *bs, char *cmd, char *response, int verbose)'
'int bitshark_cmd_write(uartlite_t *bs, char *cmd, char *response, int verbose)'
Definition at line 340 of file bitshark.cc.
References bitshark_cmd_write().
Referenced by bitshark_cmd_get_iqbal(), bitshark_cmd_read_adclk(), bitshark_cmd_read_chanbw(), bitshark_cmd_write(), bitshark_cmd_write_adclk(), bitshark_cmd_write_bbgain(), bitshark_cmd_write_chanbw(), bitshark_cmd_write_freq(), and bitshark_cmd_write_rfgain().
int bitshark_cmd_write (bitshark_dev_t * bs, char * cmd, char * response, int verbose)
Send a raw command to the Bitshark UART interface.
When an ACK is found, the return code will be 1, upon NCK it will be 0. Note: not intended to be used by the end user.
Parameters:
*bs Handle to the Bitshark device
*cmd Pointer to the string holding the command to send, null terminator is expected.
*response Optional pointer to a buffer to return the transcript of the communication. Make sure this is at least 256 chars long.
verbose Turn on to print the transcript to the console
Returns:
Whether the command was accepted.
Send a raw command to the Bitshark UART interface.
When an ACK is found, the return code will be 1, upon NCK it will be 0.
Parameters:
*bs Handle to the Bitshark device
*cmd Pointer to the string holding the command to send, null terminator is expected.
*response Optional pointer to a buffer to return the transcript of the communication. Make sure this is at least 256 chars long.
verbose Turn on to print the transcript to the console
Returns:
Whether the command was accepted.
Definition at line 352 of file bitshark.cc.
References max, bitshark_dev_t::uart, uart_clear, uart_read(), uart_rx_can_read, uart_write(), and usleep().
int bitshark_cmd_write_adclk (bitshark_dev_t * bs, int freq_H, int verbose)
Set the A/D clock frequency in hertz from 5 MHz to 105MHz.
Since software algorithms will not be able to process much more than a couple of MS/s, setting this above 10 MHz is probably useless (the spectrum analyzer demo uses the FIFO buffer to handle higher rates). WARNING: Make sure you really need this function: use 'bitshark_auto_tune' to control most of the Bitshark at once and capture at lower sample rates than the A/D can provide.
Returns:
True when all OK or false when something failed
Definition at line 552 of file bitshark.cc.
References bitshark_cmd_write().
Referenced by bitshark_auto_tune(), and bitshark_auto_tune2().
int bitshark_cmd_write_bbgain (bitshark_dev_t * bs, int gain_dB, int verbose)
Set the baseband gain at the Bitshark (see the FMC-1RX manual for details).
Range: -18 dB to 6 dB in 6 dB steps. Actual range depends on bandwidth filter, as such it is normally 0 dB or 6 dB without access to the low level controls.
Returns:
True if the setting was accepted or false otherwise
Definition at line 566 of file bitshark.cc.
References bitshark_cmd_write().
int bitshark_cmd_write_chanbw (bitshark_dev_t * bs, int width_kHz, int verbose)
Set the bandwidth filter of the Bitshark hardware.
WARNING: Make sure you really need this function: use 'bitshark_auto_tune' to control most of the Bitshark at once and set the bandwidth below the Bitshark range.
Returns:
True when all OK or false when something failed
Definition at line 573 of file bitshark.cc.
References bitshark_cmd_write().
Referenced by bitshark_auto_tune(), and bitshark_auto_tune2().
int bitshark_cmd_write_freq (bitshark_dev_t * bs, int freq_kH, int verbose)
Definition at line 543 of file bitshark.cc.
References bitshark_cmd_write().
Referenced by bitshark_auto_tune(), and bitshark_auto_tune2().
int bitshark_cmd_write_rfgain (bitshark_dev_t * bs, float gain_dB, int verbose)
Set the RF gain at the Bitshark (see the FMC-1RX manual for details).
Range: 0 to 31.5 dB in 0.5 dB steps. Default value: 15 dB.
Returns:
True if the setting was accepted or false otherwise
Definition at line 559 of file bitshark.cc.
References bitshark_cmd_write().
float bitshark_decode_fp (unsigned short input, int bits, int fractional)
Decode a fixed point number into a floating point value.
The parameters follow the Xilinx notation scheme for fixed point numbers. For example: FIX_10_6. This format is made up of 10 bits, left 4 bits are integer bits (including the sign) and the right 6 bits are fractional.
Parameters:
input The unsigned integer holding the bits to decode
bits Number of bits in the fixed point number, this should ofcourse be less than the number of bits 'input' can hold
fractional Number of bits that are fractional of the total number of bits
Returns:
The floating point value described by the fixed point number
Definition at line 1002 of file bitshark.cc.
References m_get_bit.
Referenced by bitshark_cmd_get_iqbal(), and bitshark_load_iqbal().
int bitshark_init (bitshark_dev_t * bs)
Initialize the ADC in order to get a valid signal.
Note that this does not modify the current (default) settings of the Bitshark itself like the sample rate or frequency.
Parameters:
bs Handle to the Bitshark device
Returns:
0 when encountering errors, 1 when the ADC was set up properly
Definition at line 50 of file bitshark.cc.
References adc_init(), bitshark_compatible_version(), BITSHARK_DRIVER_VERSION, and bitshark_get_hw_version.
int bitshark_load_iqbal (bitshark_dev_t * bs, iq_t * iq, int verbose)
Load channel balancer with the given values where I is C and Q is D.
This is a 'fix' for direct conversion receivers as they tend to have small channel imbalances which result in reflections between positive and negative frequencies. The balancer modifies the Q channel as: Q' = C*I + D*Q. The format for C and D is fixed point FIX_10_6 as thats what is returned by the Bitshark control device. It will get sign extended before use.
Parameters:
bs Handle to the struct with all control registers
iq The struct to obtain the C and D parameters from. Use NULL to load C=0.0 and D=1.0
verbose Set to true to see what is going on in intermediate steps
This is a 'fix' for direct conversion receivers as they tend to have small channel imbalances which result in reflections between positive and negative frequencies. The balancer modifies the Q channel as: Q' = C*I + D*Q. The format for C and D is fixed point FIX_10_6 as thats what is returned by the Bitshark control device. It will get sign extended before using.
Parameters:
bs Handle to the struct with all control registers
iq The struct to obtain the C and D parameters from. Use NULL to load C=0.0 and D=1.0
verbose Set to true to see what is going on in intermediate steps
Definition at line 1036 of file bitshark.cc.
References bitshark_decode_fp(), BS_ERR_BAL, BS_NO_ERR, bitshark_dev_t::ctrl, iq_t::I, bitshark_ctrl_dev_t::iqbal_reg, and iq_t::Q.
Referenced by bitshark_auto_tune(), and bitshark_auto_tune2().
static int bitshark_read (bitshark_dev_t * bs, iq_t * iq) [inline, static]
Read an IQ sample from the BitShark board.
The returned structure contains a signed I and Q sample. Note: when debugging is enabled, the fifo connected to this register will contain a counting sequence from 0x1 to 0x0FFF for both I and Q. Decimation will introduce gaps in the debug sequence from this register.
Parameters:
*bs Handle to the Bitshark control device
*iq Pointer to an iq_t struct to fill with data from the FIFO buffer of the Bitshark device. When debug mode is enabled, this will be the (potentially decimated) debug signal.
Returns:
0 if all is ok
Definition at line 104 of file bitshark.h.
References bitshark_dev_t::ctrl, bitshark_ctrl_dev_t::ctrl_reg, bitshark_ctrl_dev_t::data_reg, iqu_t::IQ, iq_t::raw, unlikely, and iqu_t::val.
Referenced by bitshark_read_test(), bitshark_test_debug(), and bitshark_test_debug_value().
iq_t bitshark_read_debug (bitshark_dev_t * bs)
Read a debug value straight from the internal counter.
The debug register does not have a buffer. This allows read tests to check if the read values are indeed incremental (or the same). If the read loop on the remote end is not fast enough, there will be gaps in the sequence. Note: this is output straight from the counter - decimation will not affect the counter values.
Parameters:
*bs Handle to the Bitshark device
Returns:
IQ value read straight from the debug counter in the Bitshark control device
Read a debug value straight from the internal counter.
Read a debug value straight from the internal counter. The debug register does not have a buffer. This allows read tests to check if the read values are indeed incremental (or the same). If the read loop on the remote end is not fast enough, there will be gaps in the sequence. Note: this is output straight from the counter - decimation will not affect the counter values.
Parameters:
*bs Handle to the Bitshark device
Returns:
IQ value read straight from the debug counter in the Bitshark control device
Definition at line 107 of file bitshark.cc.
References bitshark_dev_t::ctrl, data, bitshark_ctrl_dev_t::debug_reg, iqu_t::IQ, and iqu_t::val.
Referenced by bitshark_test_debug().
unsigned int bitshark_ring_stream (bitshark_dev_t * bs, int enable) [inline]
Use this function to start or stop the data stream to the ring bus (assuming the ring bus mode is selected)
Parameters:
bs Handle to the struct with all control registers
enable Set to 0 to hold data, or something else to start the stream. return 1 if the ring interface is streaming data or 0 if it is on hold
Definition at line 396 of file bitshark.h.
References bitshark_dev_t::ctrl, and bitshark_ctrl_dev_t::ring_status_reg.
int bitshark_ring_streaming (bitshark_dev_t * bs) [inline]
When using the ring output, the data stream can be started and stopped.
Parameters:
bs Handle to the struct with all control registers return 1 if the ring interface is streaming data or 0 if it is on hold
Definition at line 386 of file bitshark.h.
References bitshark_dev_t::ctrl, and bitshark_ctrl_dev_t::ring_status_reg.
float bitshark_shift_spectrum (bitshark_dev_t * bs, float offset, unsigned adclk, int verbose)
Internal utility function: set up the internal CORDIC to shift the spectrum by the requested offset.
This might attenuate the signal by a bit but functions as a work-around to the DC gap.
Parameters:
offset Shift/rotate the spectrum by this much, in Hz
adclk Samplerate from the ADC on the Bitshark (before decimation)
Returns:
Actual offset implemented by the hardware
This might attenuate the signal by a bit but functions as a work-around to the DC gap.
Parameters:
bs Handle to the Bitshark device control registers
offset Shift/rotate the spectrum by this much, in Hz
adclk Samplerate from the ADC on the Bitshark (before decimation)
verbose Debug the inner workings by printing internal steps and values
Returns:
Actual offset implemented by the hardware
Definition at line 680 of file bitshark.cc.
References bitshark_set_retune, bitshark_dev_t::ctrl, and bitshark_ctrl_dev_t::retune_reg.
Referenced by bitshark_auto_tune2().
int bitshark_test_debug (bitshark_dev_t * bs, unsigned int num_read, int use_buffer, int verbose)
Debug function: This function will attempt to read a specified number of samples from the debug register on the BitShark control interface.
If all samples are sequential, true is returned, otherwise false. Enable verbose to see the test results.
Parameters:
*bs Handle to the Bitshark device
num_read Number of word reads to perform on the data bus of the Bitshark debug counter
use_buffer When false, debug values are read straight from the counter instead of the internal buffer. This mode is useful for testing the device but not so much for the consecutive read test. Use the buffered mode by default.
verbose Print debug information during the test
Returns:
1 when the test succeeded or 0 when it failed
Debug function: This function will attempt to read a specified number of samples from the debug register on the BitShark control interface.
If all samples are sequential, true is returned, otherwise false. Enable verbose to see the test results.
Parameters:
*bs Handle to the Bitshark device
num_read Number of word reads to perform on the data bus of the Bitshark debug counter
use_buffer When false, debug values are read straight from the counter instead of the internal buffer. This mode is useful for testing the device but not so much for the consecutive read test. Use the buffered mode by default.
verbose Print debug information during the test
Returns:
1 when the test succeeded or 0 when it failed
Definition at line 181 of file bitshark.cc.
References bitshark_clear, bitshark_get_decimate, bitshark_read(), bitshark_read_debug(), bitshark_set_debug, free(), iq_t::I, malloc(), and Q.
Referenced by bitshark_auto_calibrate().
int bitshark_test_debug_value (bitshark_dev_t * bs)
Debug function: Test if a raw read from the Bitshark data FIFO is a valid debug value.
Only useful during debugging.
Parameters:
*bs Handle to the Bitshark device
Returns:
0 (false) upon an error or 1 (true) when all checks pass
Debug function: Test if a raw read from the Bitshark data FIFO is a valid debug value.
Only useful during debugging.
Parameters:
*bs Handle to the Bitshark device
Returns:
0 (false) upon an error or 1 (true) when all checks pass
Definition at line 119 of file bitshark.cc.
References bitshark_read(), data, iq_t::I, and iq_t::Q.
int bitshark_use_ring (bitshark_dev_t * bs) [inline]
Determine whether the BitShark receiver will send out data using the ring bus.
Parameters:
bs Handle to the struct with all control registers return 0 if the PLB bus is used or 1 if the ring output is selected
Definition at line 359 of file bitshark.h.
References bitshark_dev_t::ctrl, and bitshark_ctrl_dev_t::ring_status_reg.
int bitshark_use_ring (bitshark_dev_t * bs, int mode) [inline]
Switch between ring bus streaming data output or PLB polled data mode.
Parameters:
bs Handle to the struct with all control registers
mode Set to 0 to use the PLB interface or to 1 to use the ring bus interface return 0 if the PLB bus is used or 1 if the ring output is selected
Definition at line 369 of file bitshark.h.
References bitshark_dev_t::ctrl, and bitshark_ctrl_dev_t::ring_status_reg.
int bitshark_verify_clk (bitshark_dev_t * bs)
Debug function: Calculate the approximate clock frequency of the BitShark LVDS data stream based on the debug counter and the internal timer.
Useful for debugging and verifying the A/D speeds.
Parameters:
*bs Pointer to the Bitshark device
Returns:
The estimate for the LVDS frame rate or the ADC clock in kHz or -1 when something failed
Debug function: Calculate the approximate clock frequency of the BitShark LVDS data stream based on the debug counter and the internal timer.
Parameters:
*bs Handle to the Bitshark device
Returns:
The estimate for the LVDS frame rate or the ADC clock in kHz or -1 when something failed
Definition at line 134 of file bitshark.cc.
References bitshark_dev_t::ctrl, bitshark_ctrl_dev_t::debug_reg, and kGetTimer().
Referenced by bitshark_auto_calibrate().
Variable Documentation
bitshark_dev_t bitshark_dev
Definition at line 24 of file bitshark.cc.