Starburst: bitshark/bitshark.cc File Reference
bitshark/bitshark.cc File Reference
#include <bitshark/bitshark.h>
#include <bitshark/uartlite.h>
#include <bitshark/spi.h>
#include <bitshark/adc.h>
#include <bitshark/fir.h>
#include <bitshark/fir_lpf.h>
#include <stdio.h>
#include <stdlib.h>
#include <sys/io.h>
#include <math.h>
#include <unistd.h>
Defines
#define m_get_bit(var, bit) (((var) >> (bit)) & 0x1)
Functions
int bitshark_compatible_version (bitshark_dev_t *bs)
Check the driver version with the hardware version.
int bitshark_init (bitshark_dev_t *bs)
Initialize the ADC in order to get a valid signal.
iq_t bitshark_read_debug (bitshark_dev_t *bs)
* *
int bitshark_test_debug_value (bitshark_dev_t *bs)
Test if a raw read from the Bitshark data FIFO is a valid debug value.
int bitshark_verify_clk (bitshark_dev_t *bs)
Calculate the approximate clock frequency of the BitShark LVDS data stream based on the debug counter and the internal timer.
int bitshark_test_debug (bitshark_dev_t *bs, unsigned int num_read, int use_buffer, int verbose)
This function will attempt to read a specified number of samples from the debug register on the BitShark control interface.
int bitshark_auto_calibrate (bitshark_dev_t *bs)
Utility function to determine the maximum sample rate on a MicroBlaze.
int bitshark_cmd_write (bitshark_dev_t *bs, char *cmd, int verbose)
int bitshark_cmd_write (bitshark_dev_t *bs, char *cmd, char *response, int verbose)
Send a command to the Bitshark UART interface.
char bitshark_parse_ascii (char *c)
Internal function: Convert a single ASCII character to its hex value.
int bitshark_parse_hex (char *data, unsigned short *hex)
Internal function: Parse 4 characters from the given position to decode the hex-encoded value.
int bitshark_cmd_get_iqbal (bitshark_dev_t *bs, int freq_kH, iq_t *iqbal, int verbose)
Read IQ balance data from the Bitshark given a specific frequency.
int bitshark_cmd_get_iqbal (bitshark_dev_t *bs, int freq_kH, complex_t *iqbal, int verbose)
int bitshark_get_samplerate (bitshark_dev_t *bs, int *samplerate)
Get the data sample rate from the Bitshark controller.
int bitshark_cmd_write_freq (bitshark_dev_t *bs, int freq_kH, int verbose)
int bitshark_cmd_write_adclk (bitshark_dev_t *bs, int freq_H, int verbose)
Set the A/D clock frequency in hertz from 5 MHz to 105MHz.
int bitshark_cmd_write_rfgain (bitshark_dev_t *bs, float gain_dB, int verbose)
Set the RF gain at the Bitshark (see the FMC-1RX manual for details).
int bitshark_cmd_write_bbgain (bitshark_dev_t *bs, int gain_dB, int verbose)
Set the baseband gain at the Bitshark (see the FMC-1RX manual for details).
int bitshark_cmd_write_chanbw (bitshark_dev_t *bs, int width_kHz, int verbose)
Set the bandwidth filter of the Bitshark hardware.
int bitshark_cmd_read_adclk (bitshark_dev_t *bs, int *freq_H, int verbose)
Read the actual A/D clock value from the Bitshark in hertz.
int bitshark_cmd_read_chanbw (bitshark_dev_t *bs, int *chanbw, int verbose)
int bitshark_validate_bandwidth (int bw_kHz)
Internal utility function: take an arbitrary bandwidth and obtain the nearest valid bandwidth that the Bitshark hardware can do.
float bitshark_shift_spectrum (bitshark_dev_t *bs, float offset, unsigned adclk, int verbose)
Internal utility function: set up the internal CORDIC to shift the spectrum by the requested offset.
int bitshark_auto_tune (bitshark_dev_t *bs, unsigned int rate_Ss, unsigned int freq_kHz, unsigned int bw_kHz, unsigned int *real_rate_Ss, int verbose)
Utility function to quickly tune into a specific frequency with appropriate bandwidth selection.
int bitshark_auto_tune2 (bitshark_dev_t *bs, unsigned int samplerate, unsigned int freq_kHz, unsigned int bw_kHz, unsigned *real_samplerate_p, int verbose)
Utility function to quickly tune into a specific frequency with appropriate bandwidth selection.
float bitshark_decode_fp (unsigned short input, int bits, int fractional)
Decode a fixed point number into a floating point value.
int bitshark_read_test (bitshark_dev_t *bs, iq_t *iq)
int bitshark_load_iqbal (bitshark_dev_t *bs, iq_t *iq, int verbose)
Load channel balancer with the given values where I is C and Q is D.
Variables
bitshark_dev_t bitshark_dev = {(bitshark_ctrl_dev_t *)IO_BITSHARK_CTRL, (uartlite_t *)IO_BITSHARK_BS_UART}
Define Documentation
#define m_get_bit (var, bit) (((var) >> (bit)) & 0x1)
Definition at line 991 of file bitshark.cc.
Referenced by bitshark_decode_fp().
Function Documentation
int bitshark_auto_calibrate (bitshark_dev_t * bs)
Utility function to determine the maximum sample rate on a MicroBlaze.
Debug function: Utility function to determine the maximum sample rate on a MicroBlaze.
This function tests to see if consecutive debug values can be read from the device. If this fails, the decimation factor is increased and the test is performed again. Note: this function is used to verify the functioning of the Bitshark and to get an idea of feasible sample rates from the Bitshark device. All feedback is printed to the console in this function, only success and error values are returned.
Parameters:
*bs Handle to the Bitshark device
Returns:
0 when an error occurred during testing or 1 when the test completed and a working decimation factor was found
Definition at line 313 of file bitshark.cc.
References bitshark_set_decimate, bitshark_test_debug(), and bitshark_verify_clk().
int bitshark_auto_tune (bitshark_dev_t * bs, unsigned int rate_Ss, unsigned int freq_kHz, unsigned int bw_kHz, unsigned int * real_rate_Ss, int verbose)
Utility function to quickly tune into a specific frequency with appropriate bandwidth selection.
The filtering of the signal is done with a mix of analog and digital filters. As the MicroBlaze processor cannot handle capture speeds in excess of 5 MS/s (which means 20 cycles per sample), the sample rate of the A/D converter will be set to ~5 MS/s which will be decimated to approximately the desired sample rate.
The frequency range is 300 MHz to 4000 MHz in kHz steps, the bandwidth selection ranges from 1 kHz to 2.5 MHz. Note: that the bandwidth selection has to be within the bandwidth dictated by the sample rate and the Nyquist frequency. Note: the digital filters are designed for sample rates up to 10 MS/s, as such, the A/D speed is fixed on ~5 MS/s.
Parameters:
bs Handle to the Bitshark device
rate_Ss Sample rate per second, range: 19,532 to 5,000,000 - the value will be updated with the actual sample rate
freq_kHz The frequency in kHz ranging from 300 MHz to 2 GHz
bw_kHz The bandwidth, the actual bandwidth will be at most Fsample/2 to prevent aliasing
real_rate_Ss Pointer to a unsigned int which will contain the actual sample rate (as the sample rate will be approximated)
verbose Make the tuning verbose for debugging purposes
Returns:
0 if all ok or an error code otherwise
Definition at line 717 of file bitshark.cc.
References abort(), bitshark_clear, bitshark_cmd_get_iqbal(), bitshark_cmd_write_adclk(), bitshark_cmd_write_chanbw(), bitshark_cmd_write_freq(), bitshark_load_iqbal(), bitshark_set_decimate, bitshark_set_iqbal, bitshark_set_lpf, bitshark_set_retune, bitshark_validate_bandwidth(), BS_ERR_BW, BS_ERR_FREQ, BS_ERR_OTHER, BS_ERR_SAMPLE_RATE, BS_NO_ERR, fir_load_coef(), and fir_lpf_gen_sinc().
int bitshark_auto_tune2 (bitshark_dev_t * bs, unsigned int samplerate, unsigned int freq_kHz, unsigned int bw_kHz, unsigned * real_samplerate_p, int verbose)
Utility function to quickly tune into a specific frequency with appropriate bandwidth selection.
The filtering of the signal is done with a mix of analog and digital filters.
This function handles the automatic spectrum shift to work around the DC gap of the physical receiver. Note that this means the derived A/D clock has to be supported by the FIR filters: you will get an error if this is not the case.
The actual tuning is done by assuming that the band between -Fs/4 and Fs/4 is actually desired. As the DC gap will ruin the data, the tuner is set to roughly (Ftune - Fs/4) and the sample speed is increased. Using the internal CORDIC, the complex spectrum is shifted by -Fs/4 and filtered down to the band from -Fs/4 to Fs/4 using the FIR filters and decimated to the requested samplerate. As such, this whole chain is invisible to the programmer when this function is used.
WARNING: Because we attempt to approximate the sample frequency and are restricted by the integer decimation, its near impossible to skip the DC gap entirely: it *will* show up in the spectrum at the negative side of the bandwidth. Make sure you are aware of the 30kHz band with -40dB atenuation at the edge.
The settings used for the various parts of the receiver will result in an approximation of the requested parameters; use the feedback variables to make sure the result is what you expect.
Note: that the bandwidth selection has to be within the bandwidth dictated by the sample rate and the Nyquist frequency.
Note: the digital filters are designed for sample rates up to 24 MS/s which is a limit in the tuning.
Note: channel balancing is enabled by default.
Parameters:
bs Handle to the Bitshark device
samplerate Samplerate per second, range: 19,532 to 24,000,000
freq_kHz The frequency in kHz ranging from 300 MHz to 2 GHz
bw_kHz The bandwidth for the low pass filter, the actual bandwidth will be at most samplerate/2 to prevent aliasing
real_samplerate_p Pointer to a unsigned int which will contain the actual sample rate in Hz (as the sample rate will be approximated)
verbose Make the tuning verbose for debugging purposes
Returns:
0 if all ok or an error code otherwise
Definition at line 870 of file bitshark.cc.
References abort(), bitshark_clear, bitshark_cmd_get_iqbal(), bitshark_cmd_write_adclk(), bitshark_cmd_write_chanbw(), bitshark_cmd_write_freq(), bitshark_load_iqbal(), BITSHARK_MAX_ADCLK, bitshark_set_decimate, bitshark_set_iqbal, bitshark_set_lpf, bitshark_shift_spectrum(), bitshark_validate_bandwidth(), BS_ERR_BW, BS_ERR_FREQ, BS_ERR_OTHER, BS_ERR_SAMPLE_RATE, BS_NO_ERR, fir_load_coef(), and fir_lpf_gen_sinc().
int bitshark_cmd_get_iqbal (bitshark_dev_t * bs, int freq_kH, iq_t * iqbal, int verbose)
Read IQ balance data from the Bitshark given a specific frequency.
The Bitshark is calibrated to balance the I and Q channel from the ADC and remove unwanted frequency components from the imbalance between channels. This function loads the balance values into the I-Q struct in 'iqbal'.
Parameters:
*bs Handle to the Bitshark control device
freq_kH Frequency too look up in kHz, valid range: 300000 to 4000000
*iqbal Pointer to the IQ struct to load the balance values into
verbose Enable debug output
Returns:
True when all OK or false when something failed
Definition at line 468 of file bitshark.cc.
References bitshark_cmd_write(), bitshark_parse_hex(), cmd, data, iq_t::I, Q, and iq_t::Q.
Referenced by bitshark_auto_tune(), bitshark_auto_tune2(), and bitshark_cmd_get_iqbal().
int bitshark_cmd_get_iqbal (bitshark_dev_t * bs, int freq_kH, complex_t * iqbal, int verbose)
See also:
bitshark_cmd_get_iqbal(bitshark_dev_t *bs, int freq_kH, iq_t *iqbal, int verbose) Identical aside from the decoding into floating point values for the balancing.
Definition at line 512 of file bitshark.cc.
References bitshark_cmd_get_iqbal(), bitshark_decode_fp(), iq_t::I, complex_t::i, iq_t::Q, and complex_t::r.
int bitshark_cmd_read_adclk (bitshark_dev_t * bs, int * freq_H, int verbose)
Read the actual A/D clock value from the Bitshark in hertz.
Warning: when using the auto-tuning, this will return the sample rate from the ADCs, the actual sample rate of the data output might not be identical! Use bitshark_get_samplerate to get the actual sample rate.
Parameters:
bs Handle to the Bitshark device
freq_H Pointer to a 32-bit integer to fill with the actual value
verbose Perform verbose communication which shows the communication on the console
Returns:
1 if all ok or an error code otherwise
Definition at line 593 of file bitshark.cc.
References bitshark_cmd_write(), cmd, and data.
Referenced by bitshark_get_samplerate().
int bitshark_cmd_read_chanbw (bitshark_dev_t * bs, int * chanbw, int verbose)
Definition at line 622 of file bitshark.cc.
References bitshark_cmd_write(), cmd, and data.
int bitshark_cmd_write (bitshark_dev_t * bs, char * cmd, int verbose)
See also:
'int bitshark_cmd_write(uartlite_t *bs, char *cmd, char *response, int verbose)'
Definition at line 340 of file bitshark.cc.
References bitshark_cmd_write().
Referenced by bitshark_cmd_get_iqbal(), bitshark_cmd_read_adclk(), bitshark_cmd_read_chanbw(), bitshark_cmd_write(), bitshark_cmd_write_adclk(), bitshark_cmd_write_bbgain(), bitshark_cmd_write_chanbw(), bitshark_cmd_write_freq(), and bitshark_cmd_write_rfgain().
int bitshark_cmd_write (bitshark_dev_t * bs, char * cmd, char * response, int verbose)
Send a command to the Bitshark UART interface.
Send a raw command to the Bitshark UART interface.
When an ACK is found, the return code will be 1, upon NCK it will be 0.
Parameters:
*bs Handle to the Bitshark device
*cmd Pointer to the string holding the command to send, null terminator is expected.
*response Optional pointer to a buffer to return the transcript of the communication. Make sure this is at least 256 chars long.
verbose Turn on to print the transcript to the console
Returns:
Whether the command was accepted.
Definition at line 352 of file bitshark.cc.
References max, bitshark_dev_t::uart, uart_clear, uart_read(), uart_rx_can_read, uart_write(), and usleep().
int bitshark_cmd_write_adclk (bitshark_dev_t * bs, int freq_H, int verbose)
Set the A/D clock frequency in hertz from 5 MHz to 105MHz.
Since software algorithms will not be able to process much more than a couple of MS/s, setting this above 10 MHz is probably useless (the spectrum analyzer demo uses the FIFO buffer to handle higher rates). WARNING: Make sure you really need this function: use 'bitshark_auto_tune' to control most of the Bitshark at once and capture at lower sample rates than the A/D can provide.
Returns:
True when all OK or false when something failed
Definition at line 552 of file bitshark.cc.
References bitshark_cmd_write().
Referenced by bitshark_auto_tune(), and bitshark_auto_tune2().
int bitshark_cmd_write_bbgain (bitshark_dev_t * bs, int gain_dB, int verbose)
Set the baseband gain at the Bitshark (see the FMC-1RX manual for details).
Range: -18 dB to 6 dB in 6 dB steps. Actual range depends on bandwidth filter, as such it is normally 0 dB or 6 dB without access to the low level controls.
Returns:
True if the setting was accepted or false otherwise
Definition at line 566 of file bitshark.cc.
References bitshark_cmd_write().
int bitshark_cmd_write_chanbw (bitshark_dev_t * bs, int width_kHz, int verbose)
Set the bandwidth filter of the Bitshark hardware.
WARNING: Make sure you really need this function: use 'bitshark_auto_tune' to control most of the Bitshark at once and set the bandwidth below the Bitshark range.
Returns:
True when all OK or false when something failed
Definition at line 573 of file bitshark.cc.
References bitshark_cmd_write().
Referenced by bitshark_auto_tune(), and bitshark_auto_tune2().
int bitshark_cmd_write_freq (bitshark_dev_t * bs, int freq_kH, int verbose)
Definition at line 543 of file bitshark.cc.
References bitshark_cmd_write().
Referenced by bitshark_auto_tune(), and bitshark_auto_tune2().
int bitshark_cmd_write_rfgain (bitshark_dev_t * bs, float gain_dB, int verbose)
Set the RF gain at the Bitshark (see the FMC-1RX manual for details).
Range: 0 to 31.5 dB in 0.5 dB steps. Default value: 15 dB.
Returns:
True if the setting was accepted or false otherwise
Definition at line 559 of file bitshark.cc.
References bitshark_cmd_write().
int bitshark_compatible_version (bitshark_dev_t * bs)
Check the driver version with the hardware version.
If this does not match, the driver will most likely not work properly on the hardware.
Parameters:
bs Handle to the Bitshark control device
Returns:
True (1) when everything was ok or false (0) when either the Bitshark was not found or the driver does not match
Definition at line 32 of file bitshark.cc.
References BITSHARK_DRIVER_VERSION, bitshark_get_hw_version, bitshark_dev_t::ctrl, and bitshark_ctrl_dev_t::version_reg.
Referenced by bitshark_init().
float bitshark_decode_fp (unsigned short input, int bits, int fractional)
Decode a fixed point number into a floating point value.
The parameters follow the Xilinx notation scheme for fixed point numbers. For example: FIX_10_6. This format is made up of 10 bits, left 4 bits are integer bits (including the sign) and the right 6 bits are fractional.
Parameters:
input The unsigned integer holding the bits to decode
bits Number of bits in the fixed point number, this should ofcourse be less than the number of bits 'input' can hold
fractional Number of bits that are fractional of the total number of bits
Returns:
The floating point value described by the fixed point number
Definition at line 1002 of file bitshark.cc.
References m_get_bit.
Referenced by bitshark_cmd_get_iqbal(), and bitshark_load_iqbal().
int bitshark_get_samplerate (bitshark_dev_t * bs, int * samplerate)
Get the data sample rate from the Bitshark controller.
Note that at low sample speed, this is *NOT* the same speed as the ADC clock speed (as obtained from bitshark_cmd_read_adclk).
Parameters:
bs Handle to the Bitshark device
samplerate Pointer to a 32-bit integer to write the actual sample rate in
Returns:
True (1) when all ok or an error code otherwise
Definition at line 530 of file bitshark.cc.
References bitshark_cmd_read_adclk(), and bitshark_get_decimate.
int bitshark_init (bitshark_dev_t * bs)
Initialize the ADC in order to get a valid signal.
Note that this does not modify the current (default) settings of the Bitshark itself like the sample rate or frequency.
Parameters:
bs Handle to the Bitshark device
Returns:
0 when encountering errors, 1 when the ADC was set up properly
Definition at line 50 of file bitshark.cc.
References adc_init(), bitshark_compatible_version(), BITSHARK_DRIVER_VERSION, and bitshark_get_hw_version.
int bitshark_load_iqbal (bitshark_dev_t * bs, iq_t * iq, int verbose)
Load channel balancer with the given values where I is C and Q is D.
This is a 'fix' for direct conversion receivers as they tend to have small channel imbalances which result in reflections between positive and negative frequencies. The balancer modifies the Q channel as: Q' = C*I + D*Q. The format for C and D is fixed point FIX_10_6 as thats what is returned by the Bitshark control device. It will get sign extended before using.
Parameters:
bs Handle to the struct with all control registers
iq The struct to obtain the C and D parameters from. Use NULL to load C=0.0 and D=1.0
verbose Set to true to see what is going on in intermediate steps
Definition at line 1036 of file bitshark.cc.
References bitshark_decode_fp(), BS_ERR_BAL, BS_NO_ERR, bitshark_dev_t::ctrl, iq_t::I, bitshark_ctrl_dev_t::iqbal_reg, and iq_t::Q.
Referenced by bitshark_auto_tune(), and bitshark_auto_tune2().
char bitshark_parse_ascii (char * c)
Internal function: Convert a single ASCII character to its hex value.
Valid input values are 0-9,a-f and A-F.
Parameters:
*c Pointer to the character to decode
Returns:
The decoded value for the given character or -1 if not a hex character.
Definition at line 405 of file bitshark.cc.
Referenced by bitshark_parse_hex().
int bitshark_parse_hex (char * data, unsigned short * hex)
Internal function: Parse 4 characters from the given position to decode the hex-encoded value.
E.g.: AB01
Parameters:
*data Pointer to buffer of at least 4 character to decode (if not it will segfault)
*hex Pointer to a buffer to put the decoded result in
Returns:
1 when everything worked out or 0 if invalid characters were encountered
Definition at line 423 of file bitshark.cc.
References bitshark_parse_ascii().
Referenced by bitshark_cmd_get_iqbal().
iq_t bitshark_read_debug (bitshark_dev_t * bs)
* *
Read a debug value straight from the internal counter.
Read a debug value straight from the internal counter. The debug register does not have a buffer. This allows read tests to check if the read values are indeed incremental (or the same). If the read loop on the remote end is not fast enough, there will be gaps in the sequence. Note: this is output straight from the counter - decimation will not affect the counter values.
Parameters:
*bs Handle to the Bitshark device
Returns:
IQ value read straight from the debug counter in the Bitshark control device
Definition at line 107 of file bitshark.cc.
References bitshark_dev_t::ctrl, data, bitshark_ctrl_dev_t::debug_reg, iqu_t::IQ, and iqu_t::val.
Referenced by bitshark_test_debug().
int bitshark_read_test (bitshark_dev_t * bs, iq_t * iq)
Definition at line 1019 of file bitshark.cc.
References bitshark_read().
float bitshark_shift_spectrum (bitshark_dev_t * bs, float offset, unsigned adclk, int verbose)
Internal utility function: set up the internal CORDIC to shift the spectrum by the requested offset.
This might attenuate the signal by a bit but functions as a work-around to the DC gap.
Parameters:
bs Handle to the Bitshark device control registers
offset Shift/rotate the spectrum by this much, in Hz
adclk Samplerate from the ADC on the Bitshark (before decimation)
verbose Debug the inner workings by printing internal steps and values
Returns:
Actual offset implemented by the hardware
Definition at line 680 of file bitshark.cc.
References bitshark_set_retune, bitshark_dev_t::ctrl, and bitshark_ctrl_dev_t::retune_reg.
Referenced by bitshark_auto_tune2().
int bitshark_test_debug (bitshark_dev_t * bs, unsigned int num_read, int use_buffer, int verbose)
This function will attempt to read a specified number of samples from the debug register on the BitShark control interface.
Debug function: This function will attempt to read a specified number of samples from the debug register on the BitShark control interface.
If all samples are sequential, true is returned, otherwise false. Enable verbose to see the test results.
Parameters:
*bs Handle to the Bitshark device
num_read Number of word reads to perform on the data bus of the Bitshark debug counter
use_buffer When false, debug values are read straight from the counter instead of the internal buffer. This mode is useful for testing the device but not so much for the consecutive read test. Use the buffered mode by default.
verbose Print debug information during the test
Returns:
1 when the test succeeded or 0 when it failed
Definition at line 181 of file bitshark.cc.
References bitshark_clear, bitshark_get_decimate, bitshark_read(), bitshark_read_debug(), bitshark_set_debug, free(), iq_t::I, malloc(), and Q.
Referenced by bitshark_auto_calibrate().
int bitshark_test_debug_value (bitshark_dev_t * bs)
Test if a raw read from the Bitshark data FIFO is a valid debug value.
Debug function: Test if a raw read from the Bitshark data FIFO is a valid debug value.
Only useful during debugging.
Parameters:
*bs Handle to the Bitshark device
Returns:
0 (false) upon an error or 1 (true) when all checks pass
Definition at line 119 of file bitshark.cc.
References bitshark_read(), data, iq_t::I, and iq_t::Q.
int bitshark_validate_bandwidth (int bw_kHz)
Internal utility function: take an arbitrary bandwidth and obtain the nearest valid bandwidth that the Bitshark hardware can do.
Note that this does not take the samplerate from the ADC in account; it only looks at the bandwidth.
Parameters:
bw_kHz the low-pass filter bandwidth in kHz
Returns:
the new bandwidth based on the requested bandwidth but rounded to the nearest valid value
Definition at line 658 of file bitshark.cc.
Referenced by bitshark_auto_tune(), and bitshark_auto_tune2().
int bitshark_verify_clk (bitshark_dev_t * bs)
Calculate the approximate clock frequency of the BitShark LVDS data stream based on the debug counter and the internal timer.
Debug function: Calculate the approximate clock frequency of the BitShark LVDS data stream based on the debug counter and the internal timer.
Parameters:
*bs Handle to the Bitshark device
Returns:
The estimate for the LVDS frame rate or the ADC clock in kHz or -1 when something failed
Definition at line 134 of file bitshark.cc.
References bitshark_dev_t::ctrl, bitshark_ctrl_dev_t::debug_reg, and kGetTimer().
Referenced by bitshark_auto_calibrate().
Variable Documentation
bitshark_dev_t bitshark_dev = {(bitshark_ctrl_dev_t *)IO_BITSHARK_CTRL, (uartlite_t *)IO_BITSHARK_BS_UART}
Definition at line 24 of file bitshark.cc.