Starburst: io/buttons.cc File Reference
io/buttons.cc File Reference
Low-level functions to handle input from the push buttons.
#include <sys/io.h>
#include <sys/helix_config.h>
#include "iodebug.h"
Functions
bool button_state (int button)
Returns the current state of the specified button.
unsigned int buttons_state ()
Returns the current state of all buttons.
unsigned int buttons_event ()
Returns all press/release events that are not processed yet.
bool button_event (int button)
Checks whether there is a new event for the specified button.
void button_clear_event (int button)
Clears the event flag of the specified button.
bool button_pressed (int button)
Checks whether the button has been pressed.
bool button_released (int button)
Checks whether the button has been pressed.
Detailed Description
Low-level functions to handle input from the push buttons.
Definition in file buttons.cc.
Function Documentation
void button_clear_event (int button)
Clears the event flag of the specified button.
Definition at line 53 of file buttons.cc.
References IO_BUTTONS_EDGE, and io_write.
Referenced by button_pressed(), and button_released().
bool button_event (int button)
Checks whether there is a new event for the specified button.
When a button is pressed, this event is detected and stored. Such event can only be cleared when calling button_clear_event(). In the mean time, new events will be ignored.
Returns:
true when there is one
Definition at line 46 of file buttons.cc.
References buttons_event().
Referenced by button_pressed(), and button_released().
bool button_pressed (int button)
Checks whether the button has been pressed.
It checks whether there is an event. When there is one, the current state of the button is checked. In case the button is currently pressed, it is assumed the event is a press event, which is then cleared and true is returned. When there was no event or the button isn't hold down currently, nothing is changed and false is returned.
Note that when a button is pressed and released before the call to button_pressed() is made, it is assumed that the last event was a release event, so false will be returned. In that case, the press event is lost. When it is required that all events are processed, make sure that button_pressed() and button_released() are called in a timely fashion. It might be a good practice to let software poll the registers using buttons_event() and call button_pressed() or button_released() when buttons_event() returns a non-zero value. Polling the buttons by repeatedly calling button_pressed() and buton_released() for all buttons to be monitored, is inefficient.
There is a race condition in the case that the button is pressed or released during the execution of this function. In that case, it is possible that old or new events are ignored. However, it is assumed that the buttons are just human input, which is not that fast to cause problems.
Returns:
true in the case of a new event and the button is currently pressed
Definition at line 82 of file buttons.cc.
References button_clear_event(), button_event(), and button_state().
bool button_released (int button)
Checks whether the button has been pressed.
Similar to button_pressed().
Returns:
true in the case of a new event and the button is currently released
Definition at line 95 of file buttons.cc.
References button_clear_event(), button_event(), and button_state().
bool button_state (int button)
Returns the current state of the specified button.
Returns:
true when the button is currently pressed
Definition at line 17 of file buttons.cc.
References buttons_state().
Referenced by button_pressed(), and button_released().
unsigned int buttons_event ()
Returns all press/release events that are not processed yet.
Returns:
For every button a 1 in the result represents an unprocessed edge of the button.
Definition at line 33 of file buttons.cc.
References IO_BUTTONS_EDGE, and io_read.
Referenced by button_event().
unsigned int buttons_state ()
Returns the current state of all buttons.
Returns:
a 1 at the bit index when the corresponding button is pressed
Definition at line 25 of file buttons.cc.
References IO_BUTTONS_STATE, and io_read.
Referenced by button_state().