Starburst: include/helios/cheap.h File Reference
include/helios/cheap.h File Reference
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <inttypes.h>
#include "InfoFIFO.h"
#include "memmap.h"
Defines
#define WRITE_BACK_CACHE 0
#define SETWAY 0
#define INV_ENTIRE_CACHE 1
#define NUMBER_OF_LOCKS 480
#define NUMBER_OF_PROC 34
#define EXIT_ENTER_CS 0
#define EXIT_EXIT_CS 1
#define EXIT_LOCK 2
#define EXIT_LOCK_ERROR 3
#define TASK_START 0
#define TASK_STOP 1
#define CACHE_CTRL_NOOP 0x0
#define CACHE_CTRL_FLUSH_RANGE 0x1
#define CACHE_CTRL_INV_RANGE 0x2
#define CACHE_CTRL_FUNCTION ((volatile uint32_t*)0x01810000)
#define CACHE_CTRL_FROM ((volatile uint32_t*) 0x01810004)
#define CACHE_CTRL_UNTIL ((volatile uint32_t*) 0x01810008)
#define min(a, b) (((a) < (b)) ? (a) : (b))
#define max(a, b) (((a) > (b)) ? (a) : (b))
#define EXIT_ERROR 0
#define EXIT_OK 1
#define EXIT_PARAM_ER 2
#define EXIT_MALLOC 3
#define EXIT_FIFO_FULL 4
#define EXIT_FIFO_EMPTY 5
#define READ 0
#define WRITE 1
#define UNBLOCK 0
#define BLOCK 1
#define UPTD_MASK 0x00000001
#define WRAP_SET_MASK 0x80000000
#define WRAP_RST_MASK 0x00000000
#define WR_RD_MASK 0x7FFFFFFF
Typedefs
typedef enum ACTIVETYPE enumForActiveType
Enumerations
enum ACTIVETYPE { CON_ACTIVE = 1, CON_NOT_ACTIVE = 0 }
Functions
void initFifoInfo (void *)
int createFifo (uint32_t tokensize, uint32_t fifosize, int id)
struct Info_FIFO * openFifo (int id)
int readFifo (volatile struct Info_FIFO *ptrFifo, int *data)
int writeFifo (volatile struct Info_FIFO *ptrFifo, void *data)
void initSemaphores (int numberoflocks)
void wlock (int lockid, int id)
void wunlock (int lockid, int id)
void acquire (int lockid, int id, int *ptr, int size)
void release (int lockid, int id, int *ptr, int size)
void lock (int lockid, int id, int num)
void unlock (int lockid, int id, int num)
void invalidateDCache (uint32_t *ptr, uint32_t size)
Define Documentation
#define BLOCK 1
Definition at line 71 of file cheap.h.
#define CACHE_CTRL_FLUSH_RANGE 0x1
Definition at line 50 of file cheap.h.
#define CACHE_CTRL_FROM ((volatile uint32_t*) 0x01810004)
Definition at line 54 of file cheap.h.
#define CACHE_CTRL_FUNCTION ((volatile uint32_t*)0x01810000)
Definition at line 53 of file cheap.h.
#define CACHE_CTRL_INV_RANGE 0x2
Definition at line 51 of file cheap.h.
#define CACHE_CTRL_NOOP 0x0
Definition at line 49 of file cheap.h.
#define CACHE_CTRL_UNTIL ((volatile uint32_t*) 0x01810008)
Definition at line 55 of file cheap.h.
#define EXIT_ENTER_CS 0
Definition at line 41 of file cheap.h.
#define EXIT_ERROR 0
Definition at line 60 of file cheap.h.
Referenced by claimData(), and claimSpace().
#define EXIT_EXIT_CS 1
Definition at line 42 of file cheap.h.
#define EXIT_FIFO_EMPTY 5
Definition at line 65 of file cheap.h.
Referenced by readFifo().
#define EXIT_FIFO_FULL 4
Definition at line 64 of file cheap.h.
Referenced by createFifo(), and writeFifo().
#define EXIT_LOCK 2
Definition at line 43 of file cheap.h.
#define EXIT_LOCK_ERROR 3
Definition at line 44 of file cheap.h.
#define EXIT_MALLOC 3
Definition at line 63 of file cheap.h.
#define EXIT_OK 1
Definition at line 61 of file cheap.h.
Referenced by createFifo(), readFifo(), and writeFifo().
#define EXIT_PARAM_ER 2
Definition at line 62 of file cheap.h.
Referenced by createFifo().
#define INV_ENTIRE_CACHE 1
Definition at line 24 of file cheap.h.
#define max (a, b) (((a) > (b)) ? (a) : (b))
Definition at line 58 of file cheap.h.
Referenced by bitshark_cmd_write(), and maximum().
#define min (a, b) (((a) < (b)) ? (a) : (b))
Definition at line 57 of file cheap.h.
#define NUMBER_OF_LOCKS 480
Definition at line 36 of file cheap.h.
#define NUMBER_OF_PROC 34
Definition at line 39 of file cheap.h.
Referenced by acquire(), initSemaphores(), lock(), lockCB(), release(), unlock(), and unlockCB().
#define READ 0
Definition at line 67 of file cheap.h.
#define SETWAY 0
Definition at line 21 of file cheap.h.
#define TASK_START 0
Definition at line 46 of file cheap.h.
#define TASK_STOP 1
Definition at line 47 of file cheap.h.
#define UNBLOCK 0
Definition at line 70 of file cheap.h.
#define UPTD_MASK 0x00000001
Definition at line 73 of file cheap.h.
Referenced by releaseData(), and releaseSpace().
#define WR_RD_MASK 0x7FFFFFFF
Definition at line 76 of file cheap.h.
Referenced by claimData(), claimSpace(), releaseData(), and releaseSpace().
#define WRAP_RST_MASK 0x00000000
Definition at line 75 of file cheap.h.
Referenced by initFifo(), initFifoInfo(), releaseData(), and releaseSpace().
#define WRAP_SET_MASK 0x80000000
Definition at line 74 of file cheap.h.
Referenced by claimData(), claimSpace(), releaseData(), and releaseSpace().
#define WRITE 1
Definition at line 68 of file cheap.h.
#define WRITE_BACK_CACHE 0
Definition at line 18 of file cheap.h.
Typedef Documentation
typedef enum ACTIVETYPE enumForActiveType
Enumeration Type Documentation
enum ACTIVETYPE
Enumerator:
CON_ACTIVE
CON_NOT_ACTIVE
Definition at line 78 of file cheap.h.
Function Documentation
void acquire (int lockid, int id, int * ptr, int size)
Definition at line 345 of file cheap.cc.
References invalidateDCache(), lock(), and NUMBER_OF_PROC.
int createFifo (uint32_t tokensize, uint32_t fifosize, int id)
Definition at line 34 of file cheap.cc.
References data, EXIT_FIFO_FULL, EXIT_OK, EXIT_PARAM_ER, FIFO_BASE_ADDRESS, Info_FIFO::fifo_size, Info_FIFO::id, initFifo(), MAKE_INFOFIFO_ADDR, NOT_DEFINED, NUM_FIFOS, and Info_FIFO::token_size.
void initFifoInfo (void *)
Definition at line 60 of file cheap.cc.
References Info_FIFO::active, Info_FIFO::con_ID, CON_NOT_ACTIVE, Info_FIFO::data, Info_FIFO::direction, Info_FIFO::fifo_size, Info_FIFO::id, MAKE_INFOFIFO_ADDR, NOT_DEFINED, NUM_FIFOS, Info_FIFO::readc, Info_FIFO::remote, Info_FIFO::tdma, Info_FIFO::token_size, WRAP_RST_MASK, and Info_FIFO::writec.
void initSemaphores (int numberoflocks)
Definition at line 372 of file cheap.cc.
References LOCK_CHOOSING_ADDRESS, LOCK_NUMBER_ADDRESS, and NUMBER_OF_PROC.
void invalidateDCache (uint32_t * ptr, uint32_t size)
Definition at line 17 of file cheap.cc.
Referenced by acquire(), getReadAddressCB(), and readCB().
void lock (int lockid, int id, int num)
Definition at line 279 of file cheap.cc.
References Info_FIFO::id, LOCK_CHOOSING_ADDRESS, LOCK_NUMBER_ADDRESS, maximum(), NUMBER_OF_PROC, and Yield().
Referenced by acquire(), lck_ask(), lck_destroy(), lck_giveup(), lck_pass_p(), lck_request(), lck_unlock(), and lockCB().
struct Info_FIFO* openFifo (int id) [read]
Definition at line 86 of file cheap.cc.
References Info_FIFO::id, MAKE_INFOFIFO_ADDR, and NUM_FIFOS.
int readFifo (volatile struct Info_FIFO * ptrFifo, int * data)
Definition at line 221 of file cheap.cc.
References claimData(), EXIT_FIFO_EMPTY, EXIT_OK, invalidateDCacheMVA(), releaseSpace(), Info_FIFO::token_size, and Yield().
void release (int lockid, int id, int * ptr, int size)
Definition at line 362 of file cheap.cc.
References cleanDCache(), NUMBER_OF_PROC, and unlock().
void unlock (int lockid, int id, int num)
Definition at line 327 of file cheap.cc.
References Info_FIFO::id, LOCK_NUMBER_ADDRESS, and NUMBER_OF_PROC.
Referenced by lck_list_add(), release(), and unlockCB().
void wlock (int lockid, int id)
int writeFifo (volatile struct Info_FIFO * ptrFifo, void * data)
Definition at line 186 of file cheap.cc.
References claimSpace(), cleanDCache(), EXIT_FIFO_FULL, EXIT_OK, releaseData(), Info_FIFO::token_size, and Yield().
void wunlock (int lockid, int id)