Starburst: com/cheap.cc File Reference
com/cheap.cc File Reference
#include <helios/cheap.h>
#include <sys/syscall.h>
#include <helios/InfoFIFO.h>
Defines
#define NUM_FIFOS 32
#define NOT_DEFINED -1
#define MAKE_INFOFIFO_ADDR(i) ((volatile struct Info_FIFO*) ((unsigned int)_ddrbase + (sizeof(volatile struct Info_FIFO) * i)))
Functions
volatile void cleanDCache (uint32_t *ptr, uint32_t size)
void invalidateDCache (uint32_t *ptr, uint32_t size)
volatile void invalidateDCacheMVA (uint32_t *ptr, uint32_t size)
void initFifo (volatile struct Info_FIFO *ptrFifo, void *data, uint32_t tokensize, uint32_t fifosize, int id)
int createFifo (uint32_t tokensize, uint32_t fifosize, int id)
void initFifoInfo (void *shmaddrIn)
struct Info_FIFO * openFifo (int id)
void * claimSpace (volatile struct Info_FIFO *ptrFifo)
void releaseData (volatile struct Info_FIFO *ptrFifo)
void * claimData (volatile struct Info_FIFO *ptrFifo)
void releaseSpace (volatile struct Info_FIFO *ptrFifo)
int writeFifo (volatile struct Info_FIFO *ptrFifo, void *data)
int readFifo (volatile struct Info_FIFO *ptrFifo, int *data)
int maximum (int *ptr, int num)
void lock (int lockid, int id, int num)
void unlock (int lockid, int id, int num)
void acquire (int lockid, int id, int *ptr, int size)
void release (int lockid, int id, int *ptr, int size)
void initSemaphores (int numberoflocks)
Variables
unsigned int _ddrbase
Define Documentation
#define MAKE_INFOFIFO_ADDR (i) ((volatile struct Info_FIFO*) ((unsigned int)_ddrbase + (sizeof(volatile struct Info_FIFO) * i)))
Definition at line 12 of file cheap.cc.
Referenced by createFifo(), initFifoInfo(), and openFifo().
#define NOT_DEFINED -1
Definition at line 10 of file cheap.cc.
Referenced by createFifo(), and initFifoInfo().
#define NUM_FIFOS 32
Definition at line 9 of file cheap.cc.
Referenced by createFifo(), initFifoInfo(), and openFifo().
Function Documentation
void acquire (int lockid, int id, int * ptr, int size)
Definition at line 345 of file cheap.cc.
References invalidateDCache(), lock(), and NUMBER_OF_PROC.
void* claimData (volatile struct Info_FIFO * ptrFifo)
Definition at line 144 of file cheap.cc.
References Info_FIFO::data, EXIT_ERROR, Info_FIFO::readc, Info_FIFO::token_size, WR_RD_MASK, WRAP_SET_MASK, and Info_FIFO::writec.
Referenced by readFifo().
void* claimSpace (volatile struct Info_FIFO * ptrFifo)
Definition at line 98 of file cheap.cc.
References Info_FIFO::data, EXIT_ERROR, Info_FIFO::readc, Info_FIFO::token_size, WR_RD_MASK, WRAP_SET_MASK, and Info_FIFO::writec.
Referenced by writeFifo().
volatile void cleanDCache (uint32_t * ptr, uint32_t size)
Definition at line 14 of file cheap.cc.
Referenced by release(), writeCB(), and writeFifo().
int createFifo (uint32_t tokensize, uint32_t fifosize, int id)
Definition at line 34 of file cheap.cc.
References data, EXIT_FIFO_FULL, EXIT_OK, EXIT_PARAM_ER, FIFO_BASE_ADDRESS, Info_FIFO::fifo_size, Info_FIFO::id, initFifo(), MAKE_INFOFIFO_ADDR, NOT_DEFINED, NUM_FIFOS, and Info_FIFO::token_size.
void initFifo (volatile struct Info_FIFO * ptrFifo, void * data, uint32_t tokensize, uint32_t fifosize, int id)
Definition at line 23 of file cheap.cc.
References Info_FIFO::data, data, Info_FIFO::fifo_size, Info_FIFO::id, Info_FIFO::readc, Info_FIFO::remote, Info_FIFO::token_size, WRAP_RST_MASK, and Info_FIFO::writec.
Referenced by createFifo().
void initFifoInfo (void * shmaddrIn)
Definition at line 60 of file cheap.cc.
References Info_FIFO::active, Info_FIFO::con_ID, CON_NOT_ACTIVE, Info_FIFO::data, Info_FIFO::direction, Info_FIFO::fifo_size, Info_FIFO::id, MAKE_INFOFIFO_ADDR, NOT_DEFINED, NUM_FIFOS, Info_FIFO::readc, Info_FIFO::remote, Info_FIFO::tdma, Info_FIFO::token_size, WRAP_RST_MASK, and Info_FIFO::writec.
void initSemaphores (int numberoflocks)
Definition at line 372 of file cheap.cc.
References LOCK_CHOOSING_ADDRESS, LOCK_NUMBER_ADDRESS, and NUMBER_OF_PROC.
void invalidateDCache (uint32_t * ptr, uint32_t size)
Definition at line 17 of file cheap.cc.
Referenced by acquire(), getReadAddressCB(), and readCB().
volatile void invalidateDCacheMVA (uint32_t * ptr, uint32_t size)
Definition at line 20 of file cheap.cc.
Referenced by readFifo().
void lock (int lockid, int id, int num)
Definition at line 279 of file cheap.cc.
References Info_FIFO::id, LOCK_CHOOSING_ADDRESS, LOCK_NUMBER_ADDRESS, maximum(), NUMBER_OF_PROC, and Yield().
Referenced by acquire(), lck_ask(), lck_destroy(), lck_giveup(), lck_pass_p(), lck_request(), lck_unlock(), and lockCB().
int maximum (int * ptr, int num)
Definition at line 254 of file cheap.cc.
References max.
Referenced by lock().
struct Info_FIFO* openFifo (int id) [read]
Definition at line 86 of file cheap.cc.
References Info_FIFO::id, MAKE_INFOFIFO_ADDR, and NUM_FIFOS.
int readFifo (volatile struct Info_FIFO * ptrFifo, int * data)
Definition at line 221 of file cheap.cc.
References claimData(), EXIT_FIFO_EMPTY, EXIT_OK, invalidateDCacheMVA(), releaseSpace(), Info_FIFO::token_size, and Yield().
void release (int lockid, int id, int * ptr, int size)
Definition at line 362 of file cheap.cc.
References cleanDCache(), NUMBER_OF_PROC, and unlock().
void releaseData (volatile struct Info_FIFO * ptrFifo)
Definition at line 118 of file cheap.cc.
References Info_FIFO::fifo_size, UPTD_MASK, WR_RD_MASK, WRAP_RST_MASK, WRAP_SET_MASK, and Info_FIFO::writec.
Referenced by writeFifo().
void releaseSpace (volatile struct Info_FIFO * ptrFifo)
Definition at line 161 of file cheap.cc.
References Info_FIFO::fifo_size, Info_FIFO::readc, UPTD_MASK, WR_RD_MASK, WRAP_RST_MASK, and WRAP_SET_MASK.
Referenced by readFifo().
void unlock (int lockid, int id, int num)
Definition at line 327 of file cheap.cc.
References Info_FIFO::id, LOCK_NUMBER_ADDRESS, and NUMBER_OF_PROC.
Referenced by lck_list_add(), release(), and unlockCB().
int writeFifo (volatile struct Info_FIFO * ptrFifo, void * data)
Definition at line 186 of file cheap.cc.
References claimSpace(), cleanDCache(), EXIT_FIFO_FULL, EXIT_OK, releaseData(), Info_FIFO::token_size, and Yield().
Variable Documentation
unsigned int _ddrbase
Referenced by dvi_init().