Starburst: syncevent_t< N > Class Template Reference
syncevent_t< N > Class Template Reference
#include <syncevent.h>
Data Structures
struct dest_t
Public Types
typedef void(* hit_func)()
typedef void(* wait_func)(int)
Public Member Functions
syncevent_t ()
void finish ()
void hit () const
void wait (int count=1) const
operator syncevent_t< N > & () const
Static Public Member Functions
template<syncevent_t< N > & se>
static void hit_static ()
template<syncevent_t< N > & se>
static void wait_static (int count)
Data Fields
dest_t dest[N] ATTR_DATA_ALIGNED
bool initialized
Static Public Attributes
static const int n = N
Detailed Description
template<int N = 0>
class syncevent_t< N >
Definition at line 15 of file syncevent.h.
Member Typedef Documentation
template<int N = 0> typedef void(* syncevent_t< N >::hit_func)()
Definition at line 27 of file syncevent.h.
template<int N = 0> typedef void(* syncevent_t< N >::wait_func)(int)
Definition at line 39 of file syncevent.h.
Constructor & Destructor Documentation
template<int N = 0> syncevent_t< N >::syncevent_t () [inline]
Definition at line 19 of file syncevent.h.
Member Function Documentation
template<int N = 0> void syncevent_t< N >::finish () [inline]
Definition at line 21 of file syncevent.h.
References syncevent_t< N >::initialized, and mc_flush.
Referenced by se_create_a(), and se_create_pta().
template<int N = 0> void syncevent_t< N >::hit () const [inline]
Definition at line 28 of file syncevent.h.
References __attribute__, ASSERT, syncevent_t< N >::initialized, mc_flush, pid, SyncEventHit(), unlikely, and Yield().
template<int N = 0> template<syncevent_t< N > & se> static void syncevent_t< N >::hit_static () [inline, static]
Definition at line 51 of file syncevent.h.
template<int N = 0> syncevent_t< N >::operator syncevent_t< N > & () const [inline]
Definition at line 45 of file syncevent.h.
template<int N = 0> void syncevent_t< N >::wait (int count = 1) const [inline]
Definition at line 40 of file syncevent.h.
References __attribute__, ASSERT, and SyncEventWait().
template<int N = 0> template<syncevent_t< N > & se> static void syncevent_t< N >::wait_static (int count) [inline, static]
Definition at line 52 of file syncevent.h.
Field Documentation
template<int N = 0> dest_t dest [N] syncevent_t< N >::ATTR_DATA_ALIGNED
Definition at line 48 of file syncevent.h.
template<int N = 0> bool syncevent_t< N >::initialized
Definition at line 49 of file syncevent.h.
Referenced by syncevent_t< N >::finish(), and syncevent_t< N >::hit().
template<int N = 0> const int syncevent_t< N >::n = N [static]
Definition at line 17 of file syncevent.h.
The documentation for this class was generated from the following file:
include/syncevent.h