Starburst: PMC_NS::Var< T, B > Class Template Reference
PMC_NS::Var< T, B > Class Template Reference
#include <pmc.h>
Public Types
typedef Backend< T, B > base
typedef base backend
typedef T type
typedef Var< const T, B > CVar
Public Member Functions
Var () throw ()
Var (const Var &v)
ScopeX< Var > entry_x () __attribute__((always_inline)) throw ()
ScopeRO< Var > entry_ro () __attribute__((always_inline)) throw ()
ScopeRO< CVar > entry_ro () const __attribute__((always_inline)) throw ()
const T poll () __attribute__((always_inline)) throw ()
const T poll () const __attribute__((always_inline)) throw ()
operator const T () __attribute__((always_inline)) throw ()
operator const T () const __attribute__((always_inline)) throw ()
Var & operator= (const T &rhs) __attribute__((always_inline)) throw ()
Var & operator= (const Var &rhs) __attribute__((always_inline)) throw ()
Var * operator& () __attribute__((always_inline))
CVar * operator& () const __attribute__((always_inline))
operator CVar & () const __attribute__((always_inline))
CVar & makeConst () __attribute__((always_inline))
CVar & makeConst () const __attribute__((always_inline))
Static Public Member Functions
static void fence () __attribute__((always_inline)) throw ()
static void * operator new (size_t s) __attribute__((always_inline)) throw ()
static void * operator new[] (size_t s) __attribute__((always_inline)) throw ()
static void operator delete (void *x) __attribute__((always_inline)) throw ()
static void operator delete[] (void *x) __attribute__((always_inline)) throw ()
template<typename P >
static void * operator new (size_t s, P &pool) throw ()
template<typename P >
static void operator delete (void *p, P &pool) throw ()
Protected Member Functions
template<typename R >
operator R & () const
const T & access () const __attribute__((always_inline)) throw ()
T & access () __attribute__((always_inline)) throw ()
Static Protected Member Functions
template<typename S , typename A >
static S __attribute__ ((always_inline)) entry_x(A &a) throw ()
template<typename S , typename A >
static S __attribute__ ((always_inline)) entry_ro(A &a) throw ()
Friends
class Scope< Var, T >
class Scope< Var, const T >
class ScopeX< Var >
class ScopeRO< Var >
class VarPtrArray
Detailed Description
template<typename T, typename B = sc>
class PMC_NS::Var< T, B >
Definition at line 474 of file pmc.h.
Member Typedef Documentation
template<typename T, typename B = sc> typedef base PMC_NS::Var< T, B >::backend
Definition at line 477 of file pmc.h.
template<typename T, typename B = sc> typedef Backend<T,B> PMC_NS::Var< T, B >::base
Reimplemented in mfifo_t< T, FIFO_READERS, FIFO_SIZE_BITS, B >::elem_t.
Definition at line 476 of file pmc.h.
template<typename T, typename B = sc> typedef Var<const T,B> PMC_NS::Var< T, B >::CVar
Definition at line 479 of file pmc.h.
template<typename T, typename B = sc> typedef T PMC_NS::Var< T, B >::type
Definition at line 478 of file pmc.h.
Constructor & Destructor Documentation
template<typename T, typename B = sc> PMC_NS::Var< T, B >::Var () throw () [inline]
Definition at line 482 of file pmc.h.
template<typename T, typename B = sc> PMC_NS::Var< T, B >::Var (const Var< T, B > & v) [inline]
Definition at line 483 of file pmc.h.
Member Function Documentation
template<typename T, typename B = sc> template<typename S , typename A > static S PMC_NS::Var< T, B >::__attribute__ ((always_inline)) throw () [inline, static, protected]
Definition at line 525 of file pmc.h.
template<typename T, typename B = sc> template<typename S , typename A > static S PMC_NS::Var< T, B >::__attribute__ ((always_inline)) throw () [inline, static, protected]
Definition at line 528 of file pmc.h.
template<typename T, typename B = sc> const T& PMC_NS::Var< T, B >::access () const throw () [inline, protected]
Definition at line 531 of file pmc.h.
template<typename T, typename B = sc> T& PMC_NS::Var< T, B >::access () throw () [inline, protected]
Definition at line 534 of file pmc.h.
template<typename T, typename B = sc> ScopeRO<Var> PMC_NS::Var< T, B >::entry_ro () throw () [inline]
Reimplemented in mfifo_t< T, FIFO_READERS, FIFO_SIZE_BITS, B >::elem_t.
Definition at line 489 of file pmc.h.
template<typename T, typename B = sc> ScopeRO<CVar> PMC_NS::Var< T, B >::entry_ro () const throw () [inline]
Definition at line 491 of file pmc.h.
template<typename T, typename B = sc> ScopeX<Var> PMC_NS::Var< T, B >::entry_x () throw () [inline]
Reimplemented in mfifo_t< T, FIFO_READERS, FIFO_SIZE_BITS, B >::elem_t.
Definition at line 486 of file pmc.h.
Referenced by mfifo_t< T, FIFO_READERS, FIFO_SIZE_BITS, B >::acquire_elem(), PMC_NS::FifoMemPool< Tsa, N, B >::alloc(), mfifo_t< T, FIFO_READERS, FIFO_SIZE_BITS, B >::bump(), mfifo_t< T, FIFO_READERS, FIFO_SIZE_BITS, B >::elem_t::exit_x(), and PMC_NS::FifoMemPool< Tsa, N, B >::free().
template<typename T, typename B = sc> static void PMC_NS::Var< T, B >::fence () throw () [inline, static]
Definition at line 494 of file pmc.h.
Referenced by mfifo_t< T, FIFO_READERS, FIFO_SIZE_BITS, B >::bump(), mfifo_t< T, FIFO_READERS, FIFO_SIZE_BITS, B >::elem_t::exit_x(), PMC_NS::FifoMemPool< Tsa, N, B >::free(), and mfifo_t< T, FIFO_READERS, FIFO_SIZE_BITS, B >::front_elem().
template<typename T, typename B = sc> CVar& PMC_NS::Var< T, B >::makeConst () [inline]
Definition at line 510 of file pmc.h.
Referenced by PMC_NS::VarPtrArray< L, T, B >::operator[]().
template<typename T, typename B = sc> CVar& PMC_NS::Var< T, B >::makeConst () const [inline]
Definition at line 511 of file pmc.h.
template<typename T, typename B = sc> PMC_NS::Var< T, B >::operator const T () throw () [inline]
Reimplemented in mfifo_t< T, FIFO_READERS, FIFO_SIZE_BITS, B >::elem_t.
Definition at line 501 of file pmc.h.
template<typename T, typename B = sc> PMC_NS::Var< T, B >::operator const T () const throw () [inline]
Definition at line 502 of file pmc.h.
template<typename T, typename B = sc> PMC_NS::Var< T, B >::operator CVar & () const [inline]
Definition at line 509 of file pmc.h.
template<typename T, typename B = sc> static void PMC_NS::Var< T, B >::operator delete (void * x) throw () [inline, static]
Definition at line 516 of file pmc.h.
template<typename T, typename B = sc> template<typename P > static void PMC_NS::Var< T, B >::operator delete (void * p, P & pool) throw () [inline, static]
Definition at line 519 of file pmc.h.
template<typename T, typename B = sc> static void PMC_NS::Var< T, B >::operator delete[] (void * x) throw () [inline, static]
Definition at line 517 of file pmc.h.
template<typename T, typename B = sc> static void* PMC_NS::Var< T, B >::operator new (size_t s) throw () [inline, static]
Definition at line 514 of file pmc.h.
template<typename T, typename B = sc> template<typename P > static void* PMC_NS::Var< T, B >::operator new (size_t s, P & pool) throw () [inline, static]
Definition at line 518 of file pmc.h.
template<typename T, typename B = sc> static void* PMC_NS::Var< T, B >::operator new[] (size_t s) throw () [inline, static]
Definition at line 515 of file pmc.h.
template<typename T, typename B = sc> template<typename R > PMC_NS::Var< T, B >::operator R & () const [protected]
template<typename T, typename B = sc> Var* PMC_NS::Var< T, B >::operator& () [inline]
Reimplemented in mfifo_t< T, FIFO_READERS, FIFO_SIZE_BITS, B >::elem_t.
Definition at line 507 of file pmc.h.
template<typename T, typename B = sc> CVar* PMC_NS::Var< T, B >::operator& () const [inline]
Definition at line 508 of file pmc.h.
template<typename T, typename B = sc> Var& PMC_NS::Var< T, B >::operator= (const T & rhs) throw () [inline]
Definition at line 504 of file pmc.h.
template<typename T, typename B = sc> Var& PMC_NS::Var< T, B >::operator= (const Var< T, B > & rhs) throw () [inline]
Definition at line 505 of file pmc.h.
template<typename T, typename B = sc> const T PMC_NS::Var< T, B >::poll () throw () [inline]
Reimplemented in mfifo_t< T, FIFO_READERS, FIFO_SIZE_BITS, B >::elem_t.
Definition at line 499 of file pmc.h.
Referenced by PMC_NS::FifoMemPool< Tsa, N, B >::front(), and mfifo_t< T, FIFO_READERS, FIFO_SIZE_BITS, B >::front_elem().
template<typename T, typename B = sc> const T PMC_NS::Var< T, B >::poll () const throw () [inline]
Definition at line 500 of file pmc.h.
Friends And Related Function Documentation
template<typename T, typename B = sc> friend class Scope< Var, const T > [friend]
Definition at line 539 of file pmc.h.
template<typename T, typename B = sc> friend class Scope< Var, T > [friend]
Definition at line 538 of file pmc.h.
template<typename T, typename B = sc> friend class ScopeRO< Var > [friend]
Definition at line 541 of file pmc.h.
template<typename T, typename B = sc> friend class ScopeX< Var > [friend]
Definition at line 540 of file pmc.h.
template<typename T, typename B = sc> friend class VarPtrArray [friend]
Definition at line 542 of file pmc.h.
The documentation for this class was generated from the following file:
include/pmc.h