Starburst: PMC_NS::SCBackend< T > Class Template Reference
PMC_NS::SCBackend< T > Class Template Reference
#include <pmc.h>
Public Types
typedef MultiLocation< T > base
Public Member Functions
SCBackend ()
T & acquire () __attribute__((always_inline)) throw ()
void release (bool cleanup=false) __attribute__((always_inline)) throw ()
T & entry_x () __attribute__((always_inline)) throw ()
void exit_x (T &data, bool did_read=true, bool did_write=true, bool cleanup=false) __attribute__((always_inline)) throw ()
const T & entry_ro () __attribute__((always_inline)) throw ()
void exit_ro (const T &data, bool did_read=true, bool cleanup=false) __attribute__((always_inline)) throw ()
bool atomic () const __attribute__((always_inline
Detailed Description
template<typename T>
class PMC_NS::SCBackend< T >
Definition at line 228 of file pmc.h.
Member Typedef Documentation
template<typename T > typedef MultiLocation<T> PMC_NS::SCBackend< T >::base
Reimplemented from PMC_NS::MultiLocation< T >.
Definition at line 230 of file pmc.h.
Constructor & Destructor Documentation
template<typename T > PMC_NS::SCBackend< T >::SCBackend () [inline]
Definition at line 231 of file pmc.h.
Member Function Documentation
template<typename T > T& PMC_NS::SCBackend< T >::acquire () throw () [inline]
Reimplemented from PMC_NS::Location< T >.
Definition at line 233 of file pmc.h.
References PMC_NS::Location< T >::access(), unlikely, and Yield().
Referenced by PMC_NS::SCBackend< T >::entry_ro(), and PMC_NS::SCBackend< T >::entry_x().
template<typename T > bool PMC_NS::SCBackend< T >::atomic () const
Reimplemented from PMC_NS::MultiLocation< T >.
Referenced by PMC_NS::SCBackend< T >::entry_ro(), and PMC_NS::SCBackend< T >::exit_ro().
template<typename T > const T& PMC_NS::SCBackend< T >::entry_ro () throw () [inline]
Reimplemented from PMC_NS::MultiLocation< T >.
Definition at line 246 of file pmc.h.
References PMC_NS::Location< T >::access(), PMC_NS::SCBackend< T >::acquire(), and PMC_NS::SCBackend< T >::atomic().
template<typename T > T& PMC_NS::SCBackend< T >::entry_x () throw () [inline]
Reimplemented from PMC_NS::MultiLocation< T >.
Definition at line 240 of file pmc.h.
References PMC_NS::SCBackend< T >::acquire().
template<typename T > void PMC_NS::SCBackend< T >::exit_ro (const T & data, bool did_read = true, bool cleanup = false) throw () [inline]
Reimplemented from PMC_NS::MultiLocation< T >.
Definition at line 251 of file pmc.h.
References PMC_NS::SCBackend< T >::atomic(), and PMC_NS::SCBackend< T >::release().
template<typename T > void PMC_NS::SCBackend< T >::exit_x (T & data, bool did_read = true, bool did_write = true, bool cleanup = false) throw () [inline]
Reimplemented from PMC_NS::MultiLocation< T >.
Definition at line 243 of file pmc.h.
References PMC_NS::SCBackend< T >::release().
template<typename T > void PMC_NS::SCBackend< T >::release (bool cleanup = false) throw () [inline]
Definition at line 237 of file pmc.h.
Referenced by PMC_NS::SCBackend< T >::exit_ro(), and PMC_NS::SCBackend< T >::exit_x().
The documentation for this class was generated from the following file:
include/pmc.h