Starburst: fixed_t< I, P, S, rounding > Class Template Reference
fixed_t< I, P, S, rounding > Class Template Reference
A fixed point type, with configurable primitive type, bits after comma, and rounding policy.
#include <fixed.h>
Public Types
typedef SmallestNum< I+P, S >::type T
typedef SmallestNum< I, S >::type TI
typedef SmallestNum< P,
UnsignedType >::type TP
Public Member Functions
fixed_t (T t=0) __attribute__((always_inline))
fixed_t (float f) __attribute__((always_inline))
fixed_t (double d) __attribute__((always_inline))
fixed_t (const fixed_t &f) __attribute__((always_inline))
template<uint8_t I_, uint8_t P_, typename S_ , fixed_rounding_t R_>
__attribute__ ((always_inline)) fixed_t(const fixed_t< I_
template<class A >
R_ __attribute__ ((always_inline)) fixed_t(const A &a)
TI operator+ () const
fixed_t operator- () const
fixed_t & operator= (const fixed_t &rhs)
fixed_t & operator+= (const fixed_t &rhs)
fixed_t & operator-= (const fixed_t &rhs)
fixed_t & operator*= (const fixed_t &rhs)
fixed_t & operator/= (const fixed_t &rhs)
fixed_t operator++ (int i)
fixed_t & operator++ ()
fixed_t operator-- (int i)
fixed_t & operator-- ()
operator float () const
operator double () const
operator TI () const
template<typename A >
operator A () const
T raw () const
TI integer () const
TP fraction () const
bool overflow () const
bool underflow () const
bool out_of_range () const
Static Public Member Functions
template<class A >
static __attribute__ ((pure)) A max(const A a
Data Fields
P_
S_
R_ f: n(P>P_?(f.n<<(max(P-P_
Friends
class fixed_t
Detailed Description
template<uint8_t I, uint8_t P, typename S = SignedType, fixed_rounding_t rounding = round_nearest_int>
class fixed_t< I, P, S, rounding >
A fixed point type, with configurable primitive type, bits after comma, and rounding policy.
The implementation is heavily optimized such that it is compiled to only a few, fast instructions. The template class has the following parameters: I is the number of bits before the comma; P is the number of bits that is used after the comma (so when having T=int, one bit is used as the sign bit, P bits are used for after the comma, and 32-1-P bits are used for the integer part); S is either SignedType or UnsignedType; rounding is the rounding policy when the type is casted to an integer value. Use round_truncate to emulate int behavior, round_half_up for efficient unsigned rounding, and round_nearest_int for the slowest, but most accurate signed rounding.
During coding, don't think about all these overloaded operators, just use the type as you would do with an int or float.
Definition at line 27 of file fixed.h.
Member Typedef Documentation
template<uint8_t I, uint8_t P, typename S = SignedType, fixed_rounding_t rounding = round_nearest_int> typedef SmallestNum<I+P,S>::type fixed_t< I, P, S, rounding >::T
Definition at line 29 of file fixed.h.
template<uint8_t I, uint8_t P, typename S = SignedType, fixed_rounding_t rounding = round_nearest_int> typedef SmallestNum<I,S>::type fixed_t< I, P, S, rounding >::TI
Definition at line 30 of file fixed.h.
template<uint8_t I, uint8_t P, typename S = SignedType, fixed_rounding_t rounding = round_nearest_int> typedef SmallestNum<P,UnsignedType>::type fixed_t< I, P, S, rounding >::TP
Definition at line 31 of file fixed.h.
Constructor & Destructor Documentation
template<uint8_t I, uint8_t P, typename S = SignedType, fixed_rounding_t rounding = round_nearest_int> fixed_t< I, P, S, rounding >::fixed_t (T t = 0) [inline]
Definition at line 33 of file fixed.h.
template<uint8_t I, uint8_t P, typename S = SignedType, fixed_rounding_t rounding = round_nearest_int> fixed_t< I, P, S, rounding >::fixed_t (float f) [inline]
Definition at line 34 of file fixed.h.
template<uint8_t I, uint8_t P, typename S = SignedType, fixed_rounding_t rounding = round_nearest_int> fixed_t< I, P, S, rounding >::fixed_t (double d) [inline]
Definition at line 35 of file fixed.h.
template<uint8_t I, uint8_t P, typename S = SignedType, fixed_rounding_t rounding = round_nearest_int> fixed_t< I, P, S, rounding >::fixed_t (const fixed_t< I, P, S, rounding > & f) [inline]
Definition at line 36 of file fixed.h.
Member Function Documentation
template<uint8_t I, uint8_t P, typename S = SignedType, fixed_rounding_t rounding = round_nearest_int> template<uint8_t I_, uint8_t P_, typename S_ , fixed_rounding_t R_> fixed_t< I, P, S, rounding >::__attribute__ ((always_inline)) const
template<uint8_t I, uint8_t P, typename S = SignedType, fixed_rounding_t rounding = round_nearest_int> template<class A > R_ fixed_t< I, P, S, rounding >::__attribute__ ((always_inline)) const [inline]
Definition at line 39 of file fixed.h.
template<uint8_t I, uint8_t P, typename S = SignedType, fixed_rounding_t rounding = round_nearest_int> template<class A > static fixed_t< I, P, S, rounding >::__attribute__ ((pure)) const [static]
template<uint8_t I, uint8_t P, typename S = SignedType, fixed_rounding_t rounding = round_nearest_int> TP fixed_t< I, P, S, rounding >::fraction () const [inline]
Definition at line 107 of file fixed.h.
template<uint8_t I, uint8_t P, typename S = SignedType, fixed_rounding_t rounding = round_nearest_int> TI fixed_t< I, P, S, rounding >::integer () const [inline]
Definition at line 106 of file fixed.h.
template<uint8_t I, uint8_t P, typename S = SignedType, fixed_rounding_t rounding = round_nearest_int> template<typename A > fixed_t< I, P, S, rounding >::operator A () const [inline]
Definition at line 103 of file fixed.h.
template<uint8_t I, uint8_t P, typename S = SignedType, fixed_rounding_t rounding = round_nearest_int> fixed_t< I, P, S, rounding >::operator double () const [inline]
Definition at line 91 of file fixed.h.
template<uint8_t I, uint8_t P, typename S = SignedType, fixed_rounding_t rounding = round_nearest_int> fixed_t< I, P, S, rounding >::operator float () const [inline]
Definition at line 90 of file fixed.h.
template<uint8_t I, uint8_t P, typename S = SignedType, fixed_rounding_t rounding = round_nearest_int> fixed_t< I, P, S, rounding >::operator TI () const [inline]
Definition at line 92 of file fixed.h.
References round_half_up, round_nearest_int, and round_truncate.
template<uint8_t I, uint8_t P, typename S = SignedType, fixed_rounding_t rounding = round_nearest_int> fixed_t& fixed_t< I, P, S, rounding >::operator*= (const fixed_t< I, P, S, rounding > & rhs) [inline]
Definition at line 57 of file fixed.h.
template<uint8_t I, uint8_t P, typename S = SignedType, fixed_rounding_t rounding = round_nearest_int> TI fixed_t< I, P, S, rounding >::operator+ () const [inline]
Definition at line 51 of file fixed.h.
template<uint8_t I, uint8_t P, typename S = SignedType, fixed_rounding_t rounding = round_nearest_int> fixed_t fixed_t< I, P, S, rounding >::operator++ (int i) [inline]
Definition at line 60 of file fixed.h.
template<uint8_t I, uint8_t P, typename S = SignedType, fixed_rounding_t rounding = round_nearest_int> fixed_t& fixed_t< I, P, S, rounding >::operator++ () [inline]
Definition at line 61 of file fixed.h.
template<uint8_t I, uint8_t P, typename S = SignedType, fixed_rounding_t rounding = round_nearest_int> fixed_t& fixed_t< I, P, S, rounding >::operator+= (const fixed_t< I, P, S, rounding > & rhs) [inline]
Definition at line 55 of file fixed.h.
template<uint8_t I, uint8_t P, typename S = SignedType, fixed_rounding_t rounding = round_nearest_int> fixed_t fixed_t< I, P, S, rounding >::operator- () const [inline]
Definition at line 52 of file fixed.h.
template<uint8_t I, uint8_t P, typename S = SignedType, fixed_rounding_t rounding = round_nearest_int> fixed_t fixed_t< I, P, S, rounding >::operator-- (int i) [inline]
Definition at line 62 of file fixed.h.
template<uint8_t I, uint8_t P, typename S = SignedType, fixed_rounding_t rounding = round_nearest_int> fixed_t& fixed_t< I, P, S, rounding >::operator-- () [inline]
Definition at line 63 of file fixed.h.
template<uint8_t I, uint8_t P, typename S = SignedType, fixed_rounding_t rounding = round_nearest_int> fixed_t& fixed_t< I, P, S, rounding >::operator-= (const fixed_t< I, P, S, rounding > & rhs) [inline]
Definition at line 56 of file fixed.h.
template<uint8_t I, uint8_t P, typename S = SignedType, fixed_rounding_t rounding = round_nearest_int> fixed_t& fixed_t< I, P, S, rounding >::operator/= (const fixed_t< I, P, S, rounding > & rhs) [inline]
Definition at line 58 of file fixed.h.
template<uint8_t I, uint8_t P, typename S = SignedType, fixed_rounding_t rounding = round_nearest_int> fixed_t& fixed_t< I, P, S, rounding >::operator= (const fixed_t< I, P, S, rounding > & rhs) [inline]
Definition at line 54 of file fixed.h.
template<uint8_t I, uint8_t P, typename S = SignedType, fixed_rounding_t rounding = round_nearest_int> bool fixed_t< I, P, S, rounding >::out_of_range () const [inline]
Definition at line 110 of file fixed.h.
References fixed_t< I, P, S, rounding >::overflow(), and fixed_t< I, P, S, rounding >::underflow().
template<uint8_t I, uint8_t P, typename S = SignedType, fixed_rounding_t rounding = round_nearest_int> bool fixed_t< I, P, S, rounding >::overflow () const [inline]
Definition at line 108 of file fixed.h.
Referenced by fixed_t< I, P, S, rounding >::out_of_range().
template<uint8_t I, uint8_t P, typename S = SignedType, fixed_rounding_t rounding = round_nearest_int> T fixed_t< I, P, S, rounding >::raw () const [inline]
Definition at line 105 of file fixed.h.
template<uint8_t I, uint8_t P, typename S = SignedType, fixed_rounding_t rounding = round_nearest_int> bool fixed_t< I, P, S, rounding >::underflow () const [inline]
Definition at line 109 of file fixed.h.
Referenced by fixed_t< I, P, S, rounding >::out_of_range().
Friends And Related Function Documentation
template<uint8_t I, uint8_t P, typename S = SignedType, fixed_rounding_t rounding = round_nearest_int> friend class fixed_t [friend]
Definition at line 112 of file fixed.h.
Field Documentation
template<uint8_t I, uint8_t P, typename S = SignedType, fixed_rounding_t rounding = round_nearest_int> R_ fixed_t< I, P, S, rounding >::f
Definition at line 37 of file fixed.h.
template<uint8_t I, uint8_t P, typename S = SignedType, fixed_rounding_t rounding = round_nearest_int> fixed_t< I, P, S, rounding >::P_
Definition at line 37 of file fixed.h.
template<uint8_t I, uint8_t P, typename S = SignedType, fixed_rounding_t rounding = round_nearest_int> fixed_t< I, P, S, rounding >::S_
Definition at line 37 of file fixed.h.
The documentation for this class was generated from the following file:
include/fixed.h