Starburst: PMC_NS::ScopeRO< V > Class Template Reference
PMC_NS::ScopeRO< V > Class Template Reference
#include <pmc.h>
Public Types
typedef const V::type T
typedef Scope< V, T > base
Public Member Functions
ScopeRO ()
ScopeRO (V &v, T &data)
ScopeRO (ScopeRO &s)
ScopeRO (const typename base::ScopePtr ptr)
~ScopeRO () __attribute__((always_inline))
void exit_ro (bool cleanup=false) __attribute__((always_inline))
operator T & () __attribute__((always_inline)) throw ()
T & read () __attribute__((always_inline)) throw ()
T * operator-> () __attribute__((always_inline)) throw ()
T & operator* () __attribute__((always_inline)) throw ()
void reentry_ro () __attribute__((always_inline)) throw ()
void refresh () __attribute__((always_inline)) throw ()
Protected Member Functions
bool did_read () const __attribute__((always_inline)) throw ()
Detailed Description
template<typename V>
class PMC_NS::ScopeRO< V >
Definition at line 650 of file pmc.h.
Member Typedef Documentation
template<typename V > typedef Scope<V,T> PMC_NS::ScopeRO< V >::base
Definition at line 653 of file pmc.h.
template<typename V > typedef const V::type PMC_NS::ScopeRO< V >::T
Definition at line 652 of file pmc.h.
Constructor & Destructor Documentation
template<typename V > PMC_NS::ScopeRO< V >::ScopeRO () [inline]
Definition at line 655 of file pmc.h.
Referenced by PMC_NS::ScopeRO< V >::reentry_ro().
template<typename V > PMC_NS::ScopeRO< V >::ScopeRO (V & v, T & data) [inline]
Definition at line 656 of file pmc.h.
template<typename V > PMC_NS::ScopeRO< V >::ScopeRO (ScopeRO< V > & s) [inline]
Definition at line 657 of file pmc.h.
template<typename V > PMC_NS::ScopeRO< V >::ScopeRO (const typename base::ScopePtr ptr) [inline]
Definition at line 658 of file pmc.h.
template<typename V > PMC_NS::ScopeRO< V >::~ScopeRO () [inline]
Definition at line 660 of file pmc.h.
References PMC_NS::ScopeRO< V >::exit_ro(), and PMC_NS::Scope< V, const V::type >::in_scope().
Referenced by PMC_NS::ScopeRO< V >::reentry_ro().
Member Function Documentation
template<typename V > bool PMC_NS::ScopeRO< V >::did_read () const throw () [inline, protected]
Definition at line 685 of file pmc.h.
Referenced by PMC_NS::ScopeRO< V >::exit_ro().
template<typename V > void PMC_NS::ScopeRO< V >::exit_ro (bool cleanup = false) [inline]
Definition at line 664 of file pmc.h.
References PMC_NS::Scope< V, const V::type >::data(), PMC_NS::ScopeRO< V >::did_read(), and PMC_NS::Scope< V, const V::type >::release().
Referenced by PMC_NS::ScopeRO< V >::~ScopeRO().
template<typename V > PMC_NS::ScopeRO< V >::operator T & () throw () [inline]
Definition at line 667 of file pmc.h.
References PMC_NS::Scope< V, T >::operator T &().
template<typename V > T& PMC_NS::ScopeRO< V >::operator* () throw () [inline]
Definition at line 675 of file pmc.h.
template<typename V > T* PMC_NS::ScopeRO< V >::operator-> () throw () [inline]
Definition at line 674 of file pmc.h.
template<typename V > T& PMC_NS::ScopeRO< V >::read () throw () [inline]
Definition at line 671 of file pmc.h.
template<typename V > void PMC_NS::ScopeRO< V >::reentry_ro () throw () [inline]
Definition at line 676 of file pmc.h.
References PMC_NS::ScopeRO< V >::ScopeRO(), PMC_NS::Scope< V, const V::type >::var(), and PMC_NS::ScopeRO< V >::~ScopeRO().
Referenced by PMC_NS::ScopeRO< V >::refresh().
template<typename V > void PMC_NS::ScopeRO< V >::refresh () throw () [inline]
Definition at line 681 of file pmc.h.
References PMC_NS::ScopeRO< V >::reentry_ro().
The documentation for this class was generated from the following file:
include/pmc.h