Starburst: PMC_NS::MultiLocation< T > Class Template Reference
PMC_NS::MultiLocation< T > Class Template Reference
#include <pmc.h>
Public Types
typedef Location< T > base
Public Member Functions
MultiLocation ()
T & entry_x () __attribute__((always_inline)) throw ()
void exit_x (T &data, bool did_read=true, bool did_write=true, bool cleanup=false) __attribute__((always_inline)) throw ()
const T & entry_ro () __attribute__((always_inline)) throw ()
void exit_ro (const T &data, bool did_read=true, bool cleanup=false) __attribute__((always_inline)) throw ()
void flush (T &data, bool did_read=true, bool did_write=true) __attribute__((always_inline)) throw ()
bool atomic () const __attribute__((always_inline
Detailed Description
template<typename T>
class PMC_NS::MultiLocation< T >
Definition at line 100 of file pmc.h.
Member Typedef Documentation
template<typename T > typedef Location<T> PMC_NS::MultiLocation< T >::base
Reimplemented in PMC_NS::SPMBackend< T >, PMC_NS::RCBackend< T >, PMC_NS::MCBackend< T >, PMC_NS::SCBackend< T >, and PMC_NS::LocalBackend< T >.
Definition at line 102 of file pmc.h.
Constructor & Destructor Documentation
template<typename T > PMC_NS::MultiLocation< T >::MultiLocation () [inline]
Definition at line 103 of file pmc.h.
Member Function Documentation
template<typename T > bool PMC_NS::MultiLocation< T >::atomic () const
Reimplemented in PMC_NS::SPMBackend< T >, PMC_NS::RCBackend< T >, PMC_NS::MCBackend< T >, PMC_NS::SCBackend< T >, and PMC_NS::LocalBackend< T >.
template<typename T > const T& PMC_NS::MultiLocation< T >::entry_ro () throw () [inline]
Reimplemented in PMC_NS::SPMBackend< T >, PMC_NS::RCBackend< T >, PMC_NS::MCBackend< T >, PMC_NS::SCBackend< T >, and PMC_NS::LocalBackend< T >.
Definition at line 111 of file pmc.h.
References PMC_NS::Location< T >::access().
template<typename T > T& PMC_NS::MultiLocation< T >::entry_x () throw () [inline]
Reimplemented in PMC_NS::SPMBackend< T >, PMC_NS::RCBackend< T >, PMC_NS::MCBackend< T >, PMC_NS::SCBackend< T >, and PMC_NS::LocalBackend< T >.
Definition at line 105 of file pmc.h.
References PMC_NS::Location< T >::acquire().
template<typename T > void PMC_NS::MultiLocation< T >::exit_ro (const T & data, bool did_read = true, bool cleanup = false) throw () [inline]
Reimplemented in PMC_NS::SCBackend< T >, and PMC_NS::LocalBackend< T >.
Definition at line 114 of file pmc.h.
template<typename T > void PMC_NS::MultiLocation< T >::exit_x (T & data, bool did_read = true, bool did_write = true, bool cleanup = false) throw () [inline]
Reimplemented in PMC_NS::SPMBackend< T >, PMC_NS::SCBackend< T >, and PMC_NS::LocalBackend< T >.
Definition at line 108 of file pmc.h.
References PMC_NS::Location< T >::release().
template<typename T > void PMC_NS::MultiLocation< T >::flush (T & data, bool did_read = true, bool did_write = true) throw () [inline]
Reimplemented in PMC_NS::SPMBackend< T >.
Definition at line 116 of file pmc.h.
The documentation for this class was generated from the following file:
include/pmc.h