Starburst: TArray< T, L > Class Template Reference
TArray< T, L > Class Template Reference
#include <ttypes.h>
Public Member Functions
TArray () __attribute__((always_inline))
TArray (const T &val) __attribute__((always_inline))
TArray (const TArray &a) __attribute__((always_inline))
template<typename B >
__attribute__ ((always_inline)) TArray(const TArray<B
m_tail ()
template<typename B , unsigned int A>
__attribute__ ((always_inline)) TArray(const T &val
const TArray< B, A > m_tail (rest)
template<typename B , unsigned int A>
__attribute__ ((always_inline)) TArray(const TArray<B
A m_tail (a.tail())
~TArray () __attribute__((always_inline))
TArray< T, 1 > first () const __attribute__((always_inline))
TArray< T, L-1 > head () const __attribute__((always_inline))
TArray< T, L-1 > tail () const __attribute__((always_inline))
void map (void(*f)(T &))
template<typename R >
TArray< R, L > map (R(*f)(T &))
template<void(*)(T &) f>
void __attribute__ ((always_inline)) map()
template<typename R , R(*)(T &) f>
TArray< R, L > __attribute__ ((always_inline)) map()
TArray & operator= (const T &rhs) __attribute__((always_inline))
TArray & operator= (const TArray &rhs) __attribute__((always_inline))
TArray & operator= (const TArray< T, 0 > &rhs) __attribute__((always_inline))
template<unsigned int A>
TArray & __attribute__ ((always_inline)) operator
operator array_type & () __attribute__((always_inline))
T & operator[] (int i) __attribute__((always_inline))
const T & operator[] (int i) const __attribute__((always_inline))
Data Fields
& a: m_first()
const TArray< B, A > & rest: m_first(val)
A & a: m_first(a[0])
Detailed Description
template<typename T, unsigned int L>
class TArray< T, L >
Definition at line 75 of file ttypes.h.
Constructor & Destructor Documentation
template<typename T, unsigned int L> TArray< T, L >::TArray () [inline]
Definition at line 77 of file ttypes.h.
template<typename T, unsigned int L> TArray< T, L >::TArray (const T & val) [inline]
Definition at line 78 of file ttypes.h.
template<typename T, unsigned int L> TArray< T, L >::TArray (const TArray< T, L > & a) [inline]
Definition at line 79 of file ttypes.h.
template<typename T, unsigned int L> TArray< T, L >::~TArray () [inline]
Definition at line 85 of file ttypes.h.
Member Function Documentation
template<typename T, unsigned int L> template<typename B > TArray< T, L >::__attribute__ ((always_inline)) const
template<typename T, unsigned int L> template<typename B , unsigned int A> TArray< T, L >::__attribute__ ((always_inline)) const
template<typename T, unsigned int L> template<typename B , unsigned int A> TArray< T, L >::__attribute__ ((always_inline)) const
template<typename T, unsigned int L> template<void(*)(T &) f> void TArray< T, L >::__attribute__ ((always_inline)) [inline]
Definition at line 94 of file ttypes.h.
template<typename T, unsigned int L> template<typename R , R(*)(T &) f> TArray<R,L> TArray< T, L >::__attribute__ ((always_inline)) [inline]
Definition at line 96 of file ttypes.h.
template<typename T, unsigned int L> template<unsigned int A> TArray& TArray< T, L >::__attribute__ ((always_inline))
template<typename T, unsigned int L> TArray<T,1> TArray< T, L >::first () const [inline]
Definition at line 87 of file ttypes.h.
template<typename T, unsigned int L> TArray<T,L-1> TArray< T, L >::head () const [inline]
Definition at line 88 of file ttypes.h.
template<typename T, unsigned int L> TArray< T, L >::m_tail () [inline]
Definition at line 81 of file ttypes.h.
Referenced by TArray< B, A >::__attribute__(), TArray< B, A >::head(), TArray< B, A >::map(), TArray< B, A >::operator=(), and TArray< B, A >::tail().
template<typename T, unsigned int L> const TArray<B,A> TArray< T, L >::m_tail (rest) [inline]
Definition at line 82 of file ttypes.h.
template<typename T, unsigned int L> A TArray< T, L >::m_tail (a. tail()) [inline]
Definition at line 83 of file ttypes.h.
template<typename T, unsigned int L> void TArray< T, L >::map (void(*)(T &) f) [inline]
Definition at line 91 of file ttypes.h.
template<typename T, unsigned int L> template<typename R > TArray<R,L> TArray< T, L >::map (R(*)(T &) f) [inline]
Definition at line 92 of file ttypes.h.
template<typename T, unsigned int L> TArray< T, L >::operator array_type & () [inline]
Definition at line 105 of file ttypes.h.
template<typename T, unsigned int L> TArray& TArray< T, L >::operator= (const T & rhs) [inline]
Definition at line 99 of file ttypes.h.
template<typename T, unsigned int L> TArray& TArray< T, L >::operator= (const TArray< T, L > & rhs) [inline]
Definition at line 100 of file ttypes.h.
template<typename T, unsigned int L> TArray& TArray< T, L >::operator= (const TArray< T, 0 > & rhs) [inline]
Definition at line 101 of file ttypes.h.
template<typename T, unsigned int L> T& TArray< T, L >::operator[] (int i) [inline]
Definition at line 107 of file ttypes.h.
template<typename T, unsigned int L> const T& TArray< T, L >::operator[] (int i) const [inline]
Definition at line 108 of file ttypes.h.
template<typename T, unsigned int L> TArray<T,L-1> TArray< T, L >::tail () const [inline]
Definition at line 89 of file ttypes.h.
Field Documentation
template<typename T, unsigned int L> & TArray< T, L >::a
Definition at line 81 of file ttypes.h.
template<typename T, unsigned int L> A& TArray< T, L >::a
Definition at line 83 of file ttypes.h.
template<typename T, unsigned int L> const TArray<B,A>& TArray< T, L >::rest
Definition at line 82 of file ttypes.h.
The documentation for this class was generated from the following file:
include/ttypes.h