Starburst: CFifo< T, CFifo<>::w > Class Template Reference
CFifo< T, CFifo<>::w > Class Template Reference
#include <cfifo.h>
Public Member Functions
void * operator new (size_t size, CFifo< T, CFifo<>::w > *p)
Placement new.
void * operator new (size_t size)
Allocate a new local CFifo write end-point.
void * operator new (size_t size, int core)
Allocate a new CFifo write end-point in the fifo mem.
void * operator new (size_t size, int core, uint8_t storage)
Allocate a new CFifo write end-point.
void * operator new (size_t size, int core, uint8_t storage, const std::nothrow_t &nt)
Allocate a new CFifo write end-point, returning NULL on failure.
CFifo (CFifo< T, CFifo< T >::r > *other)
void push (const T &e)
T * reserve () const
Reserves an element in the FIFO memory.
void commit ()
Commit a reserved buffer.
void bump ()
Sends a non-data element through the (empty) fifo.
const T & operator+= (const T &e) __attribute__((always_inline))
Pushes specified data.
Detailed Description
template<class T>
class CFifo< T, CFifo<>::w >
Definition at line 290 of file cfifo.h.
Constructor & Destructor Documentation
template<class T > CFifo< T, CFifo<>::w >::CFifo (CFifo< T, CFifo< T >::r > * other) [inline]
Definition at line 369 of file cfifo.h.
References __attribute__, abort(), addr_core(), dRemoteCall(), FIFO_DEBUG, CFifo< T, access >::init3(), CFifo< T, access >::m_mask, CFifo< T, access >::m_other, PMC_NS::T, and unlikely.
Member Function Documentation
template<class T > void CFifo< T, CFifo<>::w >::bump () [inline]
Sends a non-data element through the (empty) fifo.
Can be used for something like an end-of-stream signal.
Definition at line 425 of file cfifo.h.
References CFIFO_BUMP, CFIFO_WAIT_UNTIL, CFifo< T, access >::empty(), FIFO_DEBUG_VALIDATE, CFifo< T, access >::m_mask, CFifo< T, access >::m_other, and CFifo< T, access >::m_wp.
template<class T > void CFifo< T, CFifo<>::w >::commit () [inline]
Commit a reserved buffer.
Note that this effectively only moves the write pointer to the next element in the FIFO queue.
It also means that if the current FIFO entry was not reserved and written, the committed data is undefined.
Definition at line 416 of file cfifo.h.
References CFifo< T, access >::m_mask, CFifo< T, access >::m_other, and CFifo< T, access >::m_wp.
template<class T > void* CFifo< T, CFifo<>::w >::operator new (size_t size, CFifo< T, CFifo<>::w > * p) [inline]
Placement new.
Definition at line 293 of file cfifo.h.
References GetProcID().
template<class T > void* CFifo< T, CFifo<>::w >::operator new (size_t size) [inline]
Allocate a new local CFifo write end-point.
Identical to new(size,-1);
See also:
operator new(size_t,int)
Definition at line 302 of file cfifo.h.
References operator new().
template<class T > void* CFifo< T, CFifo<>::w >::operator new (size_t size, int core) [inline]
Allocate a new CFifo write end-point in the fifo mem.
Identical to new(size,core,STORAGE_FIFO);
See also:
operator new(size_t,int,uint8_t)
Definition at line 310 of file cfifo.h.
References operator new().
template<class T > void* CFifo< T, CFifo<>::w >::operator new (size_t size, int core, uint8_t storage) [inline]
Allocate a new CFifo write end-point.
Identical to new(size,core,storage,nothrow), but abort()s on failure.
See also:
operator new(size_t,int,uint8_t,const std::nothrow_t&)
Definition at line 318 of file cfifo.h.
References abort(), operator new(), and unlikely.
template<class T > void* CFifo< T, CFifo<>::w >::operator new (size_t size, int core, uint8_t storage, const std::nothrow_t & nt) [inline]
Allocate a new CFifo write end-point, returning NULL on failure.
Can be called from any core.
Parameters:
size size of the object to be created (automatically by new operator)
core core to create fifo for
storage either STORAGE_FIFO, STORAGE_HEAP or STORAGE_SHARED
nt value doesn't matter, only for correct function override
Definition at line 332 of file cfifo.h.
References abort(), dRemoteCall(), FIFO_DEBUG, fmalloc(), GetProcID(), likely, MAKE_NOC_FIFOMEM_PTR, malloc(), smalloc(), PMC_NS::T, and unlikely.
template<class T > const T& CFifo< T, CFifo<>::w >::operator+= (const T & e) [inline]
Pushes specified data.
Definition at line 432 of file cfifo.h.
References FIFO_DEBUG_VALIDATE.
template<class T > void CFifo< T, CFifo<>::w >::push (const T & e) [inline]
Definition at line 393 of file cfifo.h.
References FIFO_DEBUG_VALIDATE.
template<class T > T* CFifo< T, CFifo<>::w >::reserve () const [inline]
Reserves an element in the FIFO memory.
This will return a *write-only* pointer to the FIFO memory. Effectively, you can write data straight to the end point of the FIFO.
Mind that only char/short/int write operations can be used, so when T is a struct with bitfields and you would update a field, then the data will be read first!
Returns:
NULL if something went wrong or a pointer otherwise.
Definition at line 405 of file cfifo.h.
References CFIFO_WAIT_UNTIL, FIFO_DEBUG_VALIDATE, CFifo< T, access >::full(), CFifo< T, access >::m_mask, CFifo< T, access >::m_other, and CFifo< T, access >::m_wp.
The documentation for this class was generated from the following file:
include/cfifo.h