Starburst: WorkQueue< T, W > Class Template Reference
WorkQueue< T, W > Class Template Reference
#include <workqueue.h>
Public Member Functions
WorkQueue (uint16_t maxsize=WQ_MAX_SIZE, bool(*generator)(T &, bool, void *)=NULL, void *arg=NULL)
~WorkQueue ()
void Push (const T &w)
bool Pop (T &w)
bool IsEmpty ()
bool IsFull ()
int StartSlaves (int num, void *(*func)(void *), void *arg=NULL, timems_t slicelength=PROC_DEFAULT_TIMESLICE, unsigned int stack=PROC_DEFAULT_STACK)
Protected Member Functions
int StartDispatcher ()
void RunDispatcher ()
bool RetrieveWork (int queue, bool *enabled)
void DispatchWork (const T &w, bool *enabled)
bool StillWorking (bool *enabled)
void BumpAll (bool *enabled)
Static Protected Member Functions
static void Dispatcher (WorkQueue *wq)
Detailed Description
template<typename T, int W = NUM_PROCESSORS>
class WorkQueue< T, W >
Definition at line 19 of file workqueue.h.
Constructor & Destructor Documentation
template<typename T , int W = NUM_PROCESSORS> WorkQueue< T, W >::WorkQueue (uint16_t maxsize = WQ_MAX_SIZE, bool(*)(T &, bool, void *) generator = NULL, void * arg = NULL) [inline]
Definition at line 21 of file workqueue.h.
References fmalloc(), GetProcID(), mc_flush, WorkQueue< T, W >::StartDispatcher(), WQ_DEBUG, and WQ_NEW_SIZE.
template<typename T , int W = NUM_PROCESSORS> WorkQueue< T, W >::~WorkQueue () [inline]
Definition at line 55 of file workqueue.h.
References __attribute__, DestroyProcess(), ffree(), WQ_DEBUG, and WorkQueue< T, W >::write_work.
Member Function Documentation
template<typename T , int W = NUM_PROCESSORS> void WorkQueue< T, W >::BumpAll (bool * enabled) [inline, protected]
Definition at line 232 of file workqueue.h.
References WQ_DEBUG.
Referenced by WorkQueue< T, W >::RunDispatcher().
template<typename T , int W = NUM_PROCESSORS> static void WorkQueue< T, W >::Dispatcher (WorkQueue< T, W > * wq) [inline, static, protected]
Definition at line 124 of file workqueue.h.
References ASSERT, getpid(), and WorkQueue< T, W >::RunDispatcher().
Referenced by WorkQueue< T, W >::StartDispatcher().
template<typename T , int W = NUM_PROCESSORS> void WorkQueue< T, W >::DispatchWork (const T & w, bool * enabled) [inline, protected]
Definition at line 183 of file workqueue.h.
References CFifo< T, CFifo<>::r >::bumped(), CFifo< T, access >::empty(), GetProcID(), WorkQueue< T, W >::read_new_work, WQ_DEBUG, WorkQueue< T, W >::write_work, and Yield().
Referenced by WorkQueue< T, W >::RetrieveWork(), and WorkQueue< T, W >::RunDispatcher().
template<typename T , int W = NUM_PROCESSORS> bool WorkQueue< T, W >::IsEmpty () [inline]
Definition at line 95 of file workqueue.h.
References GetProcID().
template<typename T , int W = NUM_PROCESSORS> bool WorkQueue< T, W >::IsFull () [inline]
Definition at line 96 of file workqueue.h.
References GetProcID().
template<typename T , int W = NUM_PROCESSORS> bool WorkQueue< T, W >::Pop (T & w) [inline]
Definition at line 73 of file workqueue.h.
References GetProcID(), and unlikely.
template<typename T , int W = NUM_PROCESSORS> void WorkQueue< T, W >::Push (const T & w) [inline]
Definition at line 64 of file workqueue.h.
References GetProcID(), and WQ_DEBUG.
template<typename T , int W = NUM_PROCESSORS> bool WorkQueue< T, W >::RetrieveWork (int queue, bool * enabled) [inline, protected]
Definition at line 166 of file workqueue.h.
References CFifo< T, CFifo<>::r >::bumped(), WorkQueue< T, W >::DispatchWork(), CFifo< T, access >::empty(), WorkQueue< T, W >::read_new_work, PMC_NS::T, and WQ_DEBUG.
Referenced by WorkQueue< T, W >::RunDispatcher().
template<typename T , int W = NUM_PROCESSORS> void WorkQueue< T, W >::RunDispatcher () [inline, protected]
Definition at line 129 of file workqueue.h.
References WorkQueue< T, W >::BumpAll(), WorkQueue< T, W >::DispatchWork(), WorkQueue< T, W >::RetrieveWork(), WorkQueue< T, W >::StillWorking(), PMC_NS::T, WQ_DEBUG, and Yield().
Referenced by WorkQueue< T, W >::Dispatcher().
template<typename T , int W = NUM_PROCESSORS> int WorkQueue< T, W >::StartDispatcher () [inline, protected]
Definition at line 116 of file workqueue.h.
References CreateProcess(), DAEMON_DEFAULT_STACK, DAEMON_DEFAULT_TIMESLICE, WorkQueue< T, W >::Dispatcher(), pid, and StartProcess().
Referenced by WorkQueue< T, W >::WorkQueue().
template<typename T , int W = NUM_PROCESSORS> int WorkQueue< T, W >::StartSlaves (int num, void *(*)(void *) func, void * arg = NULL, timems_t slicelength = PROC_DEFAULT_TIMESLICE, unsigned int stack = PROC_DEFAULT_STACK) [inline]
Definition at line 97 of file workqueue.h.
References CreateProcess(), GetProcID(), pid, StartProcess(), and WQ_DEBUG.
template<typename T , int W = NUM_PROCESSORS> bool WorkQueue< T, W >::StillWorking (bool * enabled) [inline, protected]
Definition at line 223 of file workqueue.h.
References CFifo< T, access >::count(), CFifo< T, access >::empty(), WQ_DEBUG, and WorkQueue< T, W >::write_work.
Referenced by WorkQueue< T, W >::RunDispatcher().
Field Documentation
template<typename T , int W = NUM_PROCESSORS> CFifoPtr<T> new_work WorkQueue< T, W >::ATTR_DATA_ALIGNED
Definition at line 247 of file workqueue.h.
template<typename T , int W = NUM_PROCESSORS> bool WorkQueue< T, W >::open
Definition at line 255 of file workqueue.h.
template<typename T , int W = NUM_PROCESSORS> CFifo<T,CFifo<>::r>* WorkQueue< T, W >::read_new_work
Definition at line 249 of file workqueue.h.
Referenced by WorkQueue< T, W >::DispatchWork(), and WorkQueue< T, W >::RetrieveWork().
template<typename T , int W = NUM_PROCESSORS> CFifo<T,CFifo<>::r>* WorkQueue< T, W >::read_work
Definition at line 252 of file workqueue.h.
template<typename T , int W = NUM_PROCESSORS> CFifoPtr<T> WorkQueue< T, W >::work
Definition at line 250 of file workqueue.h.
template<typename T , int W = NUM_PROCESSORS> T WorkQueue< T, W >::work_cache
Definition at line 253 of file workqueue.h.
template<typename T , int W = NUM_PROCESSORS> bool WorkQueue< T, W >::work_cached
Definition at line 254 of file workqueue.h.
template<typename T , int W = NUM_PROCESSORS> CFifo<T,CFifo<>::w>* WorkQueue< T, W >::write_new_work
Definition at line 248 of file workqueue.h.
template<typename T , int W = NUM_PROCESSORS> CFifo<T,CFifo<>::w>* WorkQueue< T, W >::write_work
Definition at line 251 of file workqueue.h.
Referenced by WorkQueue< T, W >::DispatchWork(), WorkQueue< T, W >::StillWorking(), and WorkQueue< T, W >::~WorkQueue().
The documentation for this class was generated from the following file:
include/workqueue.h