Starburst: dvi_screen Class Reference
dvi_screen Class Reference
Low-level access to DVI.
Public Member Functions
dvi_screen (bool doublebuf=true, uint8_t xsubdiv=1, uint8_t ysubdiv=1)
~dvi_screen ()
int Init ()
void Flush ()
int DoubleBuf (bool doublebuf)
int ShowBuffer (int buf)
dvi_frame * GetBuffer (int id=-1)
int FlipSlave (syncevent_t<>::hit_func hit=NULL, syncevent_t<>::wait_func wait=NULL)
int Flip (syncevent_t<>::wait_func collect_all=NULL, syncevent_t<>::hit_func signal_slaves=NULL)
void FlipNow ()
dvi_pixel * GetPixel (int x, int y) const
void SetPixel (int x, int y, uint32_t raw)
void SetPixelSafe (int x, int y, uint32_t raw, int xsubdiv=-1, int ysubdiv=-1)
bool OnScreen (int x, int y, int xsubdiv=-1, int ysubdiv=-1)
int ClipLeft (int x, int xsubdiv=-1) const __attribute__((always_inline))
int ClipRight (int x, int xsubdiv=-1) const __attribute__((always_inline))
int ClipTop (int y, int ysubdiv=-1) const __attribute__((always_inline))
int ClipBottom (int y, int ysubdiv=-1) const __attribute__((always_inline))
range_t RangeX (int x, int xsubdiv) const
range_t RangeY (int y, int ysubdiv) const
Static Protected Member Functions
static bool IsValidSubdiv (int x, int y)
static int Log2 (int n)
Detailed Description
Low-level access to DVI.
Definition at line 42 of file render.cc.
Constructor & Destructor Documentation
dvi_screen::dvi_screen (bool doublebuf = true, uint8_t xsubdiv = 1, uint8_t ysubdiv = 1) [inline]
Definition at line 44 of file render.cc.
dvi_screen::~dvi_screen () [inline]
Definition at line 47 of file render.cc.
References sfree().
Member Function Documentation
int dvi_screen::ClipBottom (int y, int ysubdiv = -1) const [inline]
Definition at line 218 of file render.cc.
References DVI_HEIGHT, and unlikely.
int dvi_screen::ClipLeft (int x, int xsubdiv = -1) const [inline]
Definition at line 191 of file render.cc.
References unlikely.
int dvi_screen::ClipRight (int x, int xsubdiv = -1) const [inline]
Definition at line 200 of file render.cc.
References DVI_WIDTH, and unlikely.
int dvi_screen::ClipTop (int y, int ysubdiv = -1) const [inline]
Definition at line 209 of file render.cc.
References unlikely.
int dvi_screen::DoubleBuf (bool doublebuf) [inline]
Definition at line 87 of file render.cc.
References dvi_set_address().
Referenced by Init().
int dvi_screen::Flip (syncevent_t<>::wait_func collect_all = NULL, syncevent_t<>::hit_func signal_slaves = NULL) [inline]
Definition at line 132 of file render.cc.
References dvi_set_address(), dvi_vsync(), and mc_flush.
void dvi_screen::FlipNow () [inline]
Definition at line 157 of file render.cc.
References dvi_set_address(), and mc_flush.
int dvi_screen::FlipSlave (syncevent_t<>::hit_func hit = NULL, syncevent_t<>::wait_func wait = NULL) [inline]
Definition at line 116 of file render.cc.
References dvi_vsync(), and mc_flush.
void dvi_screen::Flush () [inline]
Definition at line 82 of file render.cc.
References mc_flush.
dvi_frame* dvi_screen::GetBuffer (int id = -1) [inline]
Definition at line 105 of file render.cc.
dvi_pixel* dvi_screen::GetPixel (int x, int y) const [inline]
Definition at line 168 of file render.cc.
Referenced by SetPixel().
int dvi_screen::Init () [inline]
Definition at line 56 of file render.cc.
References DoubleBuf(), DVI_HEIGHT, DVI_WIDTH, IsValidSubdiv(), mc_flush, pthread_barrier_init(), and render_alloc_buf().
static bool dvi_screen::IsValidSubdiv (int x, int y) [inline, static, protected]
Definition at line 256 of file render.cc.
References DCACHE_LINESIZE, DVI_HEIGHT, and DVI_WIDTH.
Referenced by Init().
static int dvi_screen::Log2 (int n) [inline, static, protected]
Definition at line 271 of file render.cc.
bool dvi_screen::OnScreen (int x, int y, int xsubdiv = -1, int ysubdiv = -1) [inline]
Definition at line 181 of file render.cc.
References DVI_HEIGHT, and DVI_WIDTH.
Referenced by SetPixelSafe().
range_t dvi_screen::RangeX (int x, int xsubdiv) const [inline]
Definition at line 227 of file render.cc.
References AFTER_SCREEN, AFTER_WINDOW, BEFORE_SCREEN, BEFORE_WINDOW, DVI_WIDTH, and IN_WINDOW.
range_t dvi_screen::RangeY (int y, int ysubdiv) const [inline]
Definition at line 241 of file render.cc.
References AFTER_SCREEN, AFTER_WINDOW, BEFORE_SCREEN, BEFORE_WINDOW, DVI_HEIGHT, and IN_WINDOW.
void dvi_screen::SetPixel (int x, int y, uint32_t raw) [inline]
Definition at line 172 of file render.cc.
References GetPixel().
Referenced by SetPixelSafe().
void dvi_screen::SetPixelSafe (int x, int y, uint32_t raw, int xsubdiv = -1, int ysubdiv = -1) [inline]
Definition at line 176 of file render.cc.
References likely, OnScreen(), and SetPixel().
int dvi_screen::ShowBuffer (int buf) [inline]
Definition at line 95 of file render.cc.
References dvi_set_address().
The documentation for this class was generated from the following file:
io/render.cc