Starburst: PMC_NS::SPMBackend< T > Class Template Reference
PMC_NS::SPMBackend< T > Class Template Reference
#include <pmc.h>
Public Types
typedef MultiLocation< T > base
Public Member Functions
SPMBackend ()
T & entry_x () __attribute__((always_inline)) throw ()
void exit_x (T &data, bool did_read=true, bool did_write=true, bool cleanup=false) __attribute__((always_inline)) throw ()
const T & entry_ro () __attribute__((always_inline)) throw ()
void exit_ro (const T &data, bool did_read=true, bool cleanup=false) const __attribute__((always_inline)) throw ()
void flush (T &data, bool did_read=true, bool did_write=true) __attribute__((always_inline)) throw ()
bool atomic () const __attribute__((always_inline
Detailed Description
template<typename T>
class PMC_NS::SPMBackend< T >
Definition at line 379 of file pmc.h.
Member Typedef Documentation
template<typename T > typedef MultiLocation<T> PMC_NS::SPMBackend< T >::base
Reimplemented from PMC_NS::MultiLocation< T >.
Definition at line 381 of file pmc.h.
Constructor & Destructor Documentation
template<typename T > PMC_NS::SPMBackend< T >::SPMBackend () [inline]
Definition at line 382 of file pmc.h.
Member Function Documentation
template<typename T > bool PMC_NS::SPMBackend< T >::atomic () const
Reimplemented from PMC_NS::MultiLocation< T >.
Referenced by PMC_NS::SPMBackend< T >::entry_ro().
template<typename T > const T& PMC_NS::SPMBackend< T >::entry_ro () throw () [inline]
Reimplemented from PMC_NS::MultiLocation< T >.
Definition at line 394 of file pmc.h.
References PMC_NS::Location< T >::access(), PMC_NS::Location< T >::acquire(), PMC_NS::SPMBackend< T >::atomic(), PMC_NS::SPMBackend< T >::flush(), PMC_NS::Location< T >::release(), and PMC_NS::T.
template<typename T > T& PMC_NS::SPMBackend< T >::entry_x () throw () [inline]
Reimplemented from PMC_NS::MultiLocation< T >.
Definition at line 385 of file pmc.h.
References PMC_NS::Location< T >::acquire().
template<typename T > void PMC_NS::SPMBackend< T >::exit_ro (const T & data, bool did_read = true, bool cleanup = false) const throw () [inline]
Definition at line 406 of file pmc.h.
References ffree(), and PMC_NS::Location< T >::release().
template<typename T > void PMC_NS::SPMBackend< T >::exit_x (T & data, bool did_read = true, bool did_write = true, bool cleanup = false) throw () [inline]
Reimplemented from PMC_NS::MultiLocation< T >.
Definition at line 389 of file pmc.h.
References ffree(), PMC_NS::SPMBackend< T >::flush(), and PMC_NS::Location< T >::release().
template<typename T > void PMC_NS::SPMBackend< T >::flush (T & data, bool did_read = true, bool did_write = true) throw () [inline]
Reimplemented from PMC_NS::MultiLocation< T >.
Definition at line 411 of file pmc.h.
References PMC_NS::Location< T >::access(), and mc_flush.
Referenced by PMC_NS::SPMBackend< T >::entry_ro(), and PMC_NS::SPMBackend< T >::exit_x().
The documentation for this class was generated from the following file:
include/pmc.h