Starburst: PMC_NS::Scope< V, T > Class Template Reference
PMC_NS::Scope< V, T > Class Template Reference
#include <pmc.h>
Data Structures
struct ScopePtr
Public Member Functions
operator const ScopePtr () __attribute__((always_inline)) throw ()
operator T & () __attribute__((always_inline)) throw ()
Static Public Member Functions
static void out_of_scope () __attribute__((error("Out of scope") throw ()
Data Fields
static void noreturn
static void noinline
Protected Member Functions
Scope ()
Scope (V &v, T &data)
Scope (Scope &s)
Scope (const ScopePtr ptr)
Scope & operator= (const Scope &rhs) __attribute__((error("Assigning a scope is not allowed")))
bool in_scope () const __attribute__((always_inline))
V * release () __attribute__((always_inline))
V & var () __attribute__((always_inline))
T & data () __attribute__((always_inline))
Detailed Description
template<typename V, typename T>
class PMC_NS::Scope< V, T >
Definition at line 552 of file pmc.h.
Constructor & Destructor Documentation
template<typename V, typename T> PMC_NS::Scope< V, T >::Scope () [inline, protected]
Definition at line 574 of file pmc.h.
template<typename V, typename T> PMC_NS::Scope< V, T >::Scope (V & v, T & data) [inline, protected]
Definition at line 575 of file pmc.h.
template<typename V, typename T> PMC_NS::Scope< V, T >::Scope (Scope< V, T > & s) [inline, protected]
Definition at line 576 of file pmc.h.
template<typename V, typename T> PMC_NS::Scope< V, T >::Scope (const ScopePtr ptr) [inline, protected]
Definition at line 577 of file pmc.h.
Member Function Documentation
template<typename V, typename T> T& PMC_NS::Scope< V, T >::data () [inline, protected]
Definition at line 592 of file pmc.h.
Referenced by PMC_NS::Scope< V, const V::type >::operator const ScopePtr(), and PMC_NS::Scope< V >::operator T &().
template<typename V, typename T> bool PMC_NS::Scope< V, T >::in_scope () const [inline, protected]
Definition at line 580 of file pmc.h.
Referenced by PMC_NS::Scope< V, const V::type >::var().
template<typename V, typename T> PMC_NS::Scope< V, T >::operator const ScopePtr () throw () [inline]
Definition at line 566 of file pmc.h.
template<typename V, typename T> PMC_NS::Scope< V, T >::operator T & () throw () [inline]
Reimplemented in PMC_NS::ScopeX< V >.
Definition at line 570 of file pmc.h.
Referenced by PMC_NS::ScopeX< V >::operator T &(), and PMC_NS::ScopeRO< V >::operator T &().
template<typename V, typename T> Scope& PMC_NS::Scope< V, T >::operator= (const Scope< V, T > & rhs) [protected]
template<typename V, typename T> static void PMC_NS::Scope< V, T >::out_of_scope () throw () [static]
Referenced by PMC_NS::Scope< V, const V::type >::var().
template<typename V, typename T> V* PMC_NS::Scope< V, T >::release () [inline, protected]
Definition at line 583 of file pmc.h.
Referenced by PMC_NS::Scope< V, const V::type >::operator const ScopePtr().
template<typename V, typename T> V& PMC_NS::Scope< V, T >::var () [inline, protected]
Definition at line 588 of file pmc.h.
Referenced by PMC_NS::Scope< V, const V::type >::release().
Field Documentation
template<typename V, typename T> void PMC_NS::Scope< V, T >::noinline
Definition at line 555 of file pmc.h.
template<typename V, typename T> void PMC_NS::Scope< V, T >::noreturn
Definition at line 555 of file pmc.h.
The documentation for this class was generated from the following file:
include/pmc.h