Starburst: auto_ret< T, ok > Class Template Reference
auto_ret< T, ok > Class Template Reference
Class to automatically verify return values, even when caller does not.
#include <autoret.h>
Public Member Functions
auto_ret (T ret)
__attribute__ ((always_inline))~auto_ret()
operator T ()
Protected Member Functions
void abort () __attribute__((noreturn))
Detailed Description
template<typename T, T ok>
class auto_ret< T, ok >
Class to automatically verify return values, even when caller does not.
An instance of this class can be used as the return value of a function. When the function returns a value that should be handled by the calling function, such as a non-zero return value of pthread_create(), and this value is not read, the destructor will abort() the program.
Effectively, this removes the need to clutter your code with all kinds of error checking for functions that are never throwing errors, but still have a safety net when they do.
Definition at line 78 of file autoret.h.
Constructor & Destructor Documentation
template<typename T, T ok> auto_ret< T, ok >::auto_ret (T ret) [inline]
Definition at line 80 of file autoret.h.
Member Function Documentation
template<typename T, T ok> auto_ret< T, ok >::__attribute__ ((always_inline)) [inline]
Definition at line 82 of file autoret.h.
References auto_ret< T, ok >::abort(), and unlikely.
template<typename T, T ok> void auto_ret< T, ok >::abort () [inline, protected]
Definition at line 90 of file autoret.h.
References getpid(), GetProcID(), and printf_typefmt.
Referenced by auto_ret< T, ok >::__attribute__().
template<typename T, T ok> auto_ret< T, ok >::operator T () [inline]
Definition at line 87 of file autoret.h.
The documentation for this class was generated from the following file:
include/autoret.h