Starburst: PMC_NS::SharedAlloc Class Reference
PMC_NS::SharedAlloc Class Reference
#include <pmc.h>
Static Public Member Functions
static void * operator new (size_t s) throw ()
static void * operator new[] (size_t s) __attribute__((always_inline)) throw ()
static void operator delete (void *x) __attribute__((always_inline)) throw ()
static void operator delete[] (void *x) __attribute__((always_inline)) throw ()
template<typename P >
static void * operator new (size_t s, P &pool) throw ()
template<typename P >
static void operator delete (void *p, P &pool) throw ()
Detailed Description
Definition at line 153 of file pmc.h.
Member Function Documentation
static void PMC_NS::SharedAlloc::operator delete (void * x) throw () [inline, static]
Definition at line 162 of file pmc.h.
References sfree().
Referenced by operator delete[]().
template<typename P > static void PMC_NS::SharedAlloc::operator delete (void * p, P & pool) throw () [inline, static]
Definition at line 165 of file pmc.h.
static void PMC_NS::SharedAlloc::operator delete[] (void * x) throw () [inline, static]
Definition at line 163 of file pmc.h.
References operator delete().
static void* PMC_NS::SharedAlloc::operator new (size_t s) throw () [inline, static]
Definition at line 155 of file pmc.h.
References scalloc(), and unlikely.
Referenced by operator new[]().
template<typename P > static void* PMC_NS::SharedAlloc::operator new (size_t s, P & pool) throw () [inline, static]
Definition at line 164 of file pmc.h.
static void* PMC_NS::SharedAlloc::operator new[] (size_t s) throw () [inline, static]
Definition at line 161 of file pmc.h.
References operator new().
The documentation for this class was generated from the following file:
include/pmc.h