Starburst: CFifo< T, CFifo<>::r > Class Template Reference
CFifo< T, CFifo<>::r > Class Template Reference
#include <cfifo.h>
Public Member Functions
void * operator new[] (size_t size)
Allocate a new local CFifo read end-point.
void * operator new[] (size_t size, int core)
Allocate a new CFifo read end-point in fifo mem.
void * operator new[] (size_t size, int core, uint8_t storage)
Allocate a new CFifo read end-point.
void * operator new[] (size_t size, int core, uint8_t storage, const std::nothrow_t &nt)
Allocate a new CFifo read end-point.
const T & front () const
Returns a read-only reference to the next element in the fifo.
void pop ()
Removes next element from the fifo.
bool bumped () const
Checks whether the write end-point bumped the fifo.
const T & operator-- ()
Prefix operator: First pop()s, then front()s the fifo.
const T operator-- (int unused)
Postfix operator: First front()s the fifo and makes a local copy, then pop()s the element read and return that element (not the reference!).
operator T () const
Returns the front() of the fifo.
Friends
class CFifo< T, CFifo<>::w >
Detailed Description
template<class T>
class CFifo< T, CFifo<>::r >
Definition at line 446 of file cfifo.h.
Member Function Documentation
template<class T > bool CFifo< T, CFifo<>::r >::bumped () const [inline]
Checks whether the write end-point bumped the fifo.
Definition at line 558 of file cfifo.h.
References CFIFO_BUMP, CFifo< T, access >::empty(), FIFO_DEBUG_VALIDATE, and CFifo< T, access >::m_wp.
Referenced by WorkQueue< T, W >::DispatchWork(), and WorkQueue< T, W >::RetrieveWork().
template<class T > const T& CFifo< T, CFifo<>::r >::front () const [inline]
Returns a read-only reference to the next element in the fifo.
Definition at line 544 of file cfifo.h.
References CFIFO_WAIT_UNTIL, CFifo< T, access >::empty(), FIFO_DEBUG_VALIDATE, CFifo< T, access >::m_mask, and CFifo< T, access >::m_rp.
template<class T > void* CFifo< T, CFifo<>::r >::operator new[] (size_t size) [inline]
Allocate a new local CFifo read end-point.
Identical to new[](size,-1);
See also:
operator new[](size_t,int)
Definition at line 452 of file cfifo.h.
References operator new[]().
template<class T > void* CFifo< T, CFifo<>::r >::operator new[] (size_t size, int core) [inline]
Allocate a new CFifo read end-point in fifo mem.
Identical to new[](size,core,STORAGE_FIFO);
See also:
operator new[](size_t,int,uint8_t)
Definition at line 460 of file cfifo.h.
References operator new[]().
template<class T > void* CFifo< T, CFifo<>::r >::operator new[] (size_t size, int core, uint8_t storage) [inline]
Allocate a new CFifo read end-point.
Identical to new[](size,core,storage,nothrow), but abort()s on failure.
See also:
operator new[](size_t,int,uint8_t)
Definition at line 468 of file cfifo.h.
References abort(), operator new[](), and unlikely.
template<class T > void* CFifo< T, CFifo<>::r >::operator new[] (size_t size, int core, uint8_t storage, const std::nothrow_t & nt) [inline]
Allocate a new CFifo read end-point.
Only one object is created, but the array indicates the size of the buffer (which is rounded up to a power of two).
Can be called from any core.
Parameters:
size nr_elements*sizeof(class)
core core to create fifo on
storage storage location
nt ignored, only for correct function override
Returns:
NULL on failure
See also:
operator new[](size_t,int,uint8_t)
Definition at line 485 of file cfifo.h.
References dRemoteCall(), and FIFO_DEBUG.
template<class T > CFifo< T, CFifo<>::r >::operator T () const [inline]
Returns the front() of the fifo.
Definition at line 579 of file cfifo.h.
template<class T > const T& CFifo< T, CFifo<>::r >::operator-- () [inline]
Prefix operator: First pop()s, then front()s the fifo.
Definition at line 564 of file cfifo.h.
References FIFO_DEBUG_VALIDATE.
template<class T > const T CFifo< T, CFifo<>::r >::operator-- (int unused) [inline]
Postfix operator: First front()s the fifo and makes a local copy, then pop()s the element read and return that element (not the reference!).
Definition at line 571 of file cfifo.h.
References FIFO_DEBUG_VALIDATE, and PMC_NS::T.
template<class T > void CFifo< T, CFifo<>::r >::pop () [inline]
Removes next element from the fifo.
Definition at line 551 of file cfifo.h.
References CFIFO_WAIT_UNTIL, CFifo< T, access >::empty(), FIFO_DEBUG_VALIDATE, CFifo< T, access >::m_mask, CFifo< T, access >::m_other, and CFifo< T, access >::m_rp.
Friends And Related Function Documentation
template<class T > friend class CFifo< T, CFifo<>::w > [friend]
Definition at line 590 of file cfifo.h.
The documentation for this class was generated from the following file:
include/cfifo.h