Starburst: PMC_NS::LocalBackend< T > Class Template Reference
PMC_NS::LocalBackend< T > Class Template Reference
#include <pmc.h>
Public Types
typedef MultiLocation< T > base
Public Member Functions
LocalBackend ()
T & acquire () __attribute__((always_inline)) throw ()
void release (bool cleanup=false) __attribute__((always_inline)) throw ()
T & entry_x () __attribute__((always_inline)) throw ()
void exit_x (T &data, bool did_read=true, bool did_write=true, bool cleanup=false) __attribute__((always_inline)) throw ()
const T & entry_ro () __attribute__((always_inline)) throw ()
void exit_ro (const T &data, bool did_read=true, bool cleanup=false) __attribute__((always_inline)) throw ()
bool atomic () const __attribute__((always_inline
Detailed Description
template<typename T>
class PMC_NS::LocalBackend< T >
Definition at line 200 of file pmc.h.
Member Typedef Documentation
template<typename T > typedef MultiLocation<T> PMC_NS::LocalBackend< T >::base
Reimplemented from PMC_NS::MultiLocation< T >.
Definition at line 202 of file pmc.h.
Constructor & Destructor Documentation
template<typename T > PMC_NS::LocalBackend< T >::LocalBackend () [inline]
Definition at line 203 of file pmc.h.
Member Function Documentation
template<typename T > T& PMC_NS::LocalBackend< T >::acquire () throw () [inline]
Reimplemented from PMC_NS::Location< T >.
Definition at line 205 of file pmc.h.
References PMC_NS::Location< T >::access().
Referenced by PMC_NS::LocalBackend< T >::entry_x().
template<typename T > bool PMC_NS::LocalBackend< T >::atomic () const
Reimplemented from PMC_NS::MultiLocation< T >.
template<typename T > const T& PMC_NS::LocalBackend< T >::entry_ro () throw () [inline]
Reimplemented from PMC_NS::MultiLocation< T >.
Definition at line 216 of file pmc.h.
References PMC_NS::Location< T >::access().
template<typename T > T& PMC_NS::LocalBackend< T >::entry_x () throw () [inline]
Reimplemented from PMC_NS::MultiLocation< T >.
Definition at line 210 of file pmc.h.
References PMC_NS::LocalBackend< T >::acquire().
template<typename T > void PMC_NS::LocalBackend< T >::exit_ro (const T & data, bool did_read = true, bool cleanup = false) throw () [inline]
Reimplemented from PMC_NS::MultiLocation< T >.
Definition at line 219 of file pmc.h.
template<typename T > void PMC_NS::LocalBackend< T >::exit_x (T & data, bool did_read = true, bool did_write = true, bool cleanup = false) throw () [inline]
Reimplemented from PMC_NS::MultiLocation< T >.
Definition at line 213 of file pmc.h.
References PMC_NS::LocalBackend< T >::release().
template<typename T > void PMC_NS::LocalBackend< T >::release (bool cleanup = false) throw () [inline]
Definition at line 208 of file pmc.h.
Referenced by PMC_NS::LocalBackend< T >::exit_x().
The documentation for this class was generated from the following file:
include/pmc.h