Starburst: PMC_NS::MCBackend< T > Class Template Reference
PMC_NS::MCBackend< T > Class Template Reference
#include <pmc.h>
Public Types
typedef MultiLocation< T > base
Public Member Functions
MCBackend ()
T & acquire () __attribute__((always_inline)) throw ()
void release (bool cleanup=false) __attribute__((always_inline)) throw ()
T & entry_x () __attribute__((always_inline)) throw ()
void exit_x (T &data, bool did_read=true, bool did_write=true, bool cleanup=false) const __attribute__((always_inline)) throw ()
const T & entry_ro () __attribute__((always_inline)) throw ()
void exit_ro (const T &data, bool did_read=true, bool cleanup=false) const __attribute__((always_inline)) throw ()
void flush (T &data, bool did_read=true, bool did_write=true) const __attribute__((always_inline)) throw ()
bool atomic () const __attribute__((always_inline
Static Public Member Functions
static void fence () __attribute__((always_inline)) throw ()
Detailed Description
template<typename T>
class PMC_NS::MCBackend< T >
Definition at line 264 of file pmc.h.
Member Typedef Documentation
template<typename T > typedef MultiLocation<T> PMC_NS::MCBackend< T >::base
Reimplemented from PMC_NS::MultiLocation< T >.
Definition at line 266 of file pmc.h.
Constructor & Destructor Documentation
template<typename T > PMC_NS::MCBackend< T >::MCBackend () [inline]
Definition at line 267 of file pmc.h.
Member Function Documentation
template<typename T > T& PMC_NS::MCBackend< T >::acquire () throw () [inline]
Reimplemented from PMC_NS::Location< T >.
Definition at line 270 of file pmc.h.
References PMC_NS::Location< T >::access(), and mc_acquire.
template<typename T > bool PMC_NS::MCBackend< T >::atomic () const
Reimplemented from PMC_NS::MultiLocation< T >.
Referenced by PMC_NS::MCBackend< T >::entry_ro(), and PMC_NS::MCBackend< T >::exit_ro().
template<typename T > const T& PMC_NS::MCBackend< T >::entry_ro () throw () [inline]
Reimplemented from PMC_NS::MultiLocation< T >.
Definition at line 294 of file pmc.h.
References PMC_NS::Location< T >::access(), PMC_NS::MCBackend< T >::atomic(), mc_entry_ro, and mc_entry_x.
template<typename T > T& PMC_NS::MCBackend< T >::entry_x () throw () [inline]
Reimplemented from PMC_NS::MultiLocation< T >.
Definition at line 284 of file pmc.h.
References PMC_NS::Location< T >::access(), and mc_entry_x.
template<typename T > void PMC_NS::MCBackend< T >::exit_ro (const T & data, bool did_read = true, bool cleanup = false) const throw () [inline]
Definition at line 301 of file pmc.h.
References PMC_NS::MCBackend< T >::atomic(), mc_exit_ro, mc_exit_x, and mc_release_eager.
template<typename T > void PMC_NS::MCBackend< T >::exit_x (T & data, bool did_read = true, bool did_write = true, bool cleanup = false) const throw () [inline]
Definition at line 288 of file pmc.h.
References mc_exit_x, and mc_release_eager.
template<typename T > static void PMC_NS::MCBackend< T >::fence () throw () [inline, static]
Reimplemented from PMC_NS::Location< T >.
Definition at line 280 of file pmc.h.
References mc_fence.
template<typename T > void PMC_NS::MCBackend< T >::flush (T & data, bool did_read = true, bool did_write = true) const throw () [inline]
Definition at line 310 of file pmc.h.
References mc_flush.
template<typename T > void PMC_NS::MCBackend< T >::release (bool cleanup = false) throw () [inline]
Definition at line 274 of file pmc.h.
References PMC_NS::Location< T >::access(), mc_release, and mc_release_eager.
The documentation for this class was generated from the following file:
include/pmc.h