Starburst: PMC_NS::SAMultiLocation< T > Class Template Reference
PMC_NS::SAMultiLocation< T > Class Template Reference
#include <pmc_sa.h>
Public Types
typedef Location< T > base
Public Member Functions
SAMultiLocation ()
T & entry_x () __attribute__((always_inline)) throw ()
void exit_x (T &data, bool did_read=true, bool did_write=true, bool cleanup=false) __attribute__((always_inline)) throw ()
const T & entry_ro () __attribute__((always_inline)) throw ()
void exit_ro (const T &data, bool did_read=true, bool cleanup=false) __attribute__((always_inline)) throw ()
void flush (T &data, bool did_read=true, bool did_write=true) __attribute__((always_inline)) throw ()
bool atomic () const __attribute__((always_inline
Detailed Description
template<typename T>
class PMC_NS::SAMultiLocation< T >
Definition at line 14 of file pmc_sa.h.
Member Typedef Documentation
template<typename T > typedef Location<T> PMC_NS::SAMultiLocation< T >::base
Reimplemented in PMC_NS::SASPMBackend< T, C >.
Definition at line 16 of file pmc_sa.h.
Constructor & Destructor Documentation
template<typename T > PMC_NS::SAMultiLocation< T >::SAMultiLocation () [inline]
Definition at line 17 of file pmc_sa.h.
Member Function Documentation
template<typename T > bool PMC_NS::SAMultiLocation< T >::atomic () const
Reimplemented in PMC_NS::SASPMBackend< T, C >.
template<typename T > const T& PMC_NS::SAMultiLocation< T >::entry_ro () throw () [inline]
Reimplemented in PMC_NS::SASPMBackend< T, C >.
Definition at line 25 of file pmc_sa.h.
References PMC_NS::Location< T >::access().
template<typename T > T& PMC_NS::SAMultiLocation< T >::entry_x () throw () [inline]
Reimplemented in PMC_NS::SASPMBackend< T, C >.
Definition at line 19 of file pmc_sa.h.
References PMC_NS::Location< T >::access().
template<typename T > void PMC_NS::SAMultiLocation< T >::exit_ro (const T & data, bool did_read = true, bool cleanup = false) throw () [inline]
Definition at line 28 of file pmc_sa.h.
template<typename T > void PMC_NS::SAMultiLocation< T >::exit_x (T & data, bool did_read = true, bool did_write = true, bool cleanup = false) throw () [inline]
Reimplemented in PMC_NS::SASPMBackend< T, C >.
Definition at line 22 of file pmc_sa.h.
References PMC_NS::SAMultiLocation< T >::flush().
template<typename T > void PMC_NS::SAMultiLocation< T >::flush (T & data, bool did_read = true, bool did_write = true) throw () [inline]
Reimplemented in PMC_NS::SASPMBackend< T, C >.
Definition at line 30 of file pmc_sa.h.
Referenced by PMC_NS::SAMultiLocation< T >::exit_x().
The documentation for this class was generated from the following file:
include/pmc_sa.h