Starburst: PMC_NS::RCBackend< T > Class Template Reference
PMC_NS::RCBackend< T > Class Template Reference
#include <pmc.h>
Public Types
typedef MultiLocation< T > base
Public Member Functions
RCBackend ()
T & acquire () __attribute__((always_inline)) throw ()
void release (bool cleanup=false) __attribute__((always_inline)) throw ()
T & entry_x () __attribute__((always_inline)) throw ()
void exit_x (T &data, bool did_read=true, bool did_write=true, bool cleanup=false) const __attribute__((always_inline)) throw ()
const T & entry_ro () __attribute__((always_inline)) throw ()
void exit_ro (const T &data, bool did_read=true, bool cleanup=false) const __attribute__((always_inline)) throw ()
void flush (T &data, bool did_read=true, bool did_write=true) const __attribute__((always_inline)) throw ()
bool atomic () const __attribute__((always_inline
Static Public Member Functions
static void fence () __attribute__((always_inline)) throw ()
Detailed Description
template<typename T>
class PMC_NS::RCBackend< T >
Definition at line 322 of file pmc.h.
Member Typedef Documentation
template<typename T > typedef MultiLocation<T> PMC_NS::RCBackend< T >::base
Reimplemented from PMC_NS::MultiLocation< T >.
Definition at line 324 of file pmc.h.
Constructor & Destructor Documentation
template<typename T > PMC_NS::RCBackend< T >::RCBackend () [inline]
Definition at line 326 of file pmc.h.
Member Function Documentation
template<typename T > T& PMC_NS::RCBackend< T >::acquire () throw () [inline]
Reimplemented from PMC_NS::Location< T >.
Definition at line 329 of file pmc.h.
References PMC_NS::Location< T >::access(), and rc_entry_x.
Referenced by PMC_NS::RCBackend< T >::entry_x().
template<typename T > bool PMC_NS::RCBackend< T >::atomic () const
Reimplemented from PMC_NS::MultiLocation< T >.
Referenced by PMC_NS::RCBackend< T >::entry_ro(), and PMC_NS::RCBackend< T >::exit_ro().
template<typename T > const T& PMC_NS::RCBackend< T >::entry_ro () throw () [inline]
Reimplemented from PMC_NS::MultiLocation< T >.
Definition at line 350 of file pmc.h.
References PMC_NS::Location< T >::access(), PMC_NS::RCBackend< T >::atomic(), rc_entry_ro, and rc_entry_x.
template<typename T > T& PMC_NS::RCBackend< T >::entry_x () throw () [inline]
Reimplemented from PMC_NS::MultiLocation< T >.
Definition at line 342 of file pmc.h.
References PMC_NS::RCBackend< T >::acquire().
template<typename T > void PMC_NS::RCBackend< T >::exit_ro (const T & data, bool did_read = true, bool cleanup = false) const throw () [inline]
Definition at line 357 of file pmc.h.
References PMC_NS::RCBackend< T >::atomic(), lck_destroy(), rc_exit_ro, and rc_exit_x.
template<typename T > void PMC_NS::RCBackend< T >::exit_x (T & data, bool did_read = true, bool did_write = true, bool cleanup = false) const throw () [inline]
Definition at line 345 of file pmc.h.
References lck_destroy(), and rc_exit_x.
template<typename T > static void PMC_NS::RCBackend< T >::fence () throw () [inline, static]
Reimplemented from PMC_NS::Location< T >.
Definition at line 338 of file pmc.h.
References rc_fence.
template<typename T > void PMC_NS::RCBackend< T >::flush (T & data, bool did_read = true, bool did_write = true) const throw () [inline]
Definition at line 367 of file pmc.h.
References rc_flush.
template<typename T > void PMC_NS::RCBackend< T >::release (bool cleanup = false) throw () [inline]
Definition at line 333 of file pmc.h.
References PMC_NS::Location< T >::access(), lck_destroy(), and rc_exit_x.
The documentation for this class was generated from the following file:
include/pmc.h