Starburst: PMC_NS::Location< T > Class Template Reference
PMC_NS::Location< T > Class Template Reference
#include <pmc.h>
Public Member Functions
Location () throw ()
T & acquire () throw ()
void release (bool cleanup=false) const throw ()
const T read () const __attribute__((always_inline)) throw ()
void write (const T &val) __attribute__((always_inline)) throw ()
bool isWordType () const __attribute__((always_inline
bool pure return IS_TYPE_SIMPLE (m_var)
Static Public Member Functions
static void fence () __attribute__((always_inline)) throw ()
Protected Member Functions
T & access () __attribute__((always_inline)) throw ()
const T & access () const __attribute__((always_inline)) throw ()
Detailed Description
template<typename T>
class PMC_NS::Location< T >
Definition at line 63 of file pmc.h.
Constructor & Destructor Documentation
template<typename T > PMC_NS::Location< T >::Location () throw () [inline]
Definition at line 65 of file pmc.h.
Member Function Documentation
template<typename T > T& PMC_NS::Location< T >::access () throw () [inline, protected]
Definition at line 89 of file pmc.h.
Referenced by PMC_NS::Location< T >::acquire(), PMC_NS::LocalBackend< T >::acquire(), PMC_NS::SCBackend< T >::acquire(), PMC_NS::MCBackend< T >::acquire(), PMC_NS::RCBackend< T >::acquire(), PMC_NS::SAMultiLocation< T >::entry_ro(), PMC_NS::MultiLocation< T >::entry_ro(), PMC_NS::LocalBackend< T >::entry_ro(), PMC_NS::SCBackend< T >::entry_ro(), PMC_NS::MCBackend< T >::entry_ro(), PMC_NS::RCBackend< T >::entry_ro(), PMC_NS::SPMBackend< T >::entry_ro(), PMC_NS::SAMultiLocation< T >::entry_x(), PMC_NS::MCBackend< T >::entry_x(), PMC_NS::SASPMBackend< T, C >::flush(), PMC_NS::SPMBackend< T >::flush(), PMC_NS::Location< T >::read(), PMC_NS::MCBackend< T >::release(), PMC_NS::RCBackend< T >::release(), and PMC_NS::Location< T >::write().
template<typename T > const T& PMC_NS::Location< T >::access () const throw () [inline, protected]
Definition at line 91 of file pmc.h.
template<typename T > T& PMC_NS::Location< T >::acquire () throw () [inline]
Reimplemented in PMC_NS::RCBackend< T >, PMC_NS::MCBackend< T >, PMC_NS::SCBackend< T >, and PMC_NS::LocalBackend< T >.
Definition at line 67 of file pmc.h.
References PMC_NS::Location< T >::access(), lck_lock(), and unlikely.
Referenced by PMC_NS::SPMBackend< T >::entry_ro(), PMC_NS::MultiLocation< T >::entry_x(), and PMC_NS::SPMBackend< T >::entry_x().
template<typename T > static void PMC_NS::Location< T >::fence () throw () [inline, static]
Reimplemented in PMC_NS::RCBackend< T >, and PMC_NS::MCBackend< T >.
Definition at line 82 of file pmc.h.
template<typename T > bool pure return PMC_NS::Location< T >::IS_TYPE_SIMPLE (m_var)
template<typename T > bool PMC_NS::Location< T >::isWordType () const
template<typename T > const T PMC_NS::Location< T >::read () const throw () [inline]
Definition at line 77 of file pmc.h.
References PMC_NS::Location< T >::access().
template<typename T > void PMC_NS::Location< T >::release (bool cleanup = false) const throw () [inline]
Definition at line 72 of file pmc.h.
References lck_destroy(), lck_unlock(), and unlikely.
Referenced by PMC_NS::SPMBackend< T >::entry_ro(), PMC_NS::SPMBackend< T >::exit_ro(), PMC_NS::MultiLocation< T >::exit_x(), and PMC_NS::SPMBackend< T >::exit_x().
template<typename T > void PMC_NS::Location< T >::write (const T & val) throw () [inline]
Definition at line 79 of file pmc.h.
References PMC_NS::Location< T >::access().
The documentation for this class was generated from the following file:
include/pmc.h