Starburst: Accelerator Class Reference
Accelerator Class Reference
#include <accelerator_class.h>
Public Member Functions
Accelerator ()
virtual void saveState ()
virtual void writeState ()
virtual void setupStream ()
bool ready ()
virtual void run ()
virtual int getType ()=0
uint32_t getRingAddr ()
uint32_t getRingConfAddr ()
int setNext (Accelerator *newAcc, AccList *parent)
Accelerator * getNext (void)
void setParent (AccList *parent)
void configWrite (int dest, int *data, int n)
void configRead (int src, int *data, int n)
Protected Member Functions
AccList * getParent (void)
void setAckReturn (uint32_t ackReturnAddr)
Protected Attributes
uint32_t ringAddr
uint32_t ringConfAddr
uint32_t dataForwardAddr
uint32_t ackReturnAddr
Detailed Description
Definition at line 23 of file accelerator_class.h.
Constructor & Destructor Documentation
Accelerator::Accelerator ()
Member Function Documentation
void Accelerator::configRead (int src, int * data, int n)
void Accelerator::configWrite (int dest, int * data, int n)
Accelerator* Accelerator::getNext (void)
AccList* Accelerator::getParent (void) [protected]
uint32_t Accelerator::getRingAddr ()
uint32_t Accelerator::getRingConfAddr ()
Referenced by Cfifo_sink< Type >::writeState().
virtual int Accelerator::getType () [pure virtual]
Implemented in Cfifo_sink< Type >, RingDma, Cfifo_source< Type >, CreditToAddr, FirFilter, CordicMix, CordicQuad, and Core.
bool Accelerator::ready ()
virtual void Accelerator::run () [virtual]
Reimplemented in Cfifo_sink< Type >, and Cfifo_source< Type >.
virtual void Accelerator::saveState () [virtual]
Reimplemented in FirFilter, CordicMix, and CordicQuad.
void Accelerator::setAckReturn (uint32_t ackReturnAddr) [protected]
int Accelerator::setNext (Accelerator * newAcc, AccList * parent)
void Accelerator::setParent (AccList * parent)
virtual void Accelerator::setupStream () [virtual]
Reimplemented in Cfifo_sink< Type >, and Cfifo_source< Type >.
Referenced by Cfifo_source< Type >::setupStream(), and Cfifo_sink< Type >::setupStream().
virtual void Accelerator::writeState () [virtual]
Reimplemented in RingDma, Cfifo_sink< Type >, Cfifo_source< Type >, FirFilter, CordicMix, CordicQuad, and Core.
Field Documentation
uint32_t Accelerator::ackReturnAddr [protected]
Definition at line 68 of file accelerator_class.h.
uint32_t Accelerator::dataForwardAddr [protected]
Definition at line 67 of file accelerator_class.h.
uint32_t Accelerator::ringAddr [protected]
Definition at line 61 of file accelerator_class.h.
uint32_t Accelerator::ringConfAddr [protected]
Definition at line 62 of file accelerator_class.h.
The documentation for this class was generated from the following file:
include/accelerator/accelerator_class.h