Starburst: PMC_NS::FifoMemPool< Tsa, N, B > Class Template Reference
PMC_NS::FifoMemPool< Tsa, N, B > Class Template Reference
#include <pmc_sa.h>
Public Types
typedef MemPool base
typedef SmallestUInt< N *2 >::type pointer_t
Public Member Functions
FifoMemPool ()
void * alloc (size_t s) throw ()
void free (void *s) throw ()
Tsa & reserve () throw ()
void push (const Tsa &v) throw ()
void pop () throw ()
const Tsa & front () throw ()
Detailed Description
template<typename Tsa, int N, typename B>
class PMC_NS::FifoMemPool< Tsa, N, B >
Definition at line 61 of file pmc_sa.h.
Member Typedef Documentation
template<typename Tsa , int N, typename B > typedef MemPool PMC_NS::FifoMemPool< Tsa, N, B >::base
Definition at line 63 of file pmc_sa.h.
template<typename Tsa , int N, typename B > typedef SmallestUInt<N*2>::type PMC_NS::FifoMemPool< Tsa, N, B >::pointer_t
Definition at line 64 of file pmc_sa.h.
Constructor & Destructor Documentation
template<typename Tsa , int N, typename B > PMC_NS::FifoMemPool< Tsa, N, B >::FifoMemPool () [inline]
Definition at line 66 of file pmc_sa.h.
Member Function Documentation
template<typename Tsa , int N, typename B > void* PMC_NS::FifoMemPool< Tsa, N, B >::alloc (size_t s) throw () [inline]
Reimplemented from PMC_NS::MemPool.
Definition at line 68 of file pmc_sa.h.
References PMC_NS::Var< T, B >::entry_x(), ScopeX_type, unlikely, and Yield().
template<typename Tsa , int N, typename B > void PMC_NS::FifoMemPool< Tsa, N, B >::free (void * s) throw () [inline]
Reimplemented from PMC_NS::MemPool.
Definition at line 77 of file pmc_sa.h.
References PMC_NS::Var< T, B >::entry_x(), PMC_NS::Var< T, B >::fence(), and ScopeX_type.
template<typename Tsa , int N, typename B > const Tsa& PMC_NS::FifoMemPool< Tsa, N, B >::front () throw () [inline]
Definition at line 93 of file pmc_sa.h.
References PMC_NS::Var< T, B >::poll(), unlikely, and Yield().
Referenced by PMC_NS::FifoMemPool< Tsa, N, B >::pop().
template<typename Tsa , int N, typename B > void PMC_NS::FifoMemPool< Tsa, N, B >::pop () throw () [inline]
Definition at line 90 of file pmc_sa.h.
References PMC_NS::FifoMemPool< Tsa, N, B >::front(), and pdelete.
template<typename Tsa , int N, typename B > void PMC_NS::FifoMemPool< Tsa, N, B >::push (const Tsa & v) throw () [inline]
Definition at line 87 of file pmc_sa.h.
References PMC_NS::FifoMemPool< Tsa, N, B >::reserve().
template<typename Tsa , int N, typename B > Tsa& PMC_NS::FifoMemPool< Tsa, N, B >::reserve () throw () [inline]
Definition at line 84 of file pmc_sa.h.
Referenced by PMC_NS::FifoMemPool< Tsa, N, B >::push().
The documentation for this class was generated from the following file:
include/pmc_sa.h