Starburst: dvi_color Class Reference
dvi_color Class Reference
#include <io.h>
Public Member Functions
dvi_color (uint8_t red, uint8_t green, uint8_t blue)
dvi_color (uint8_t const (&rgb)[3])
dvi_color (uint32_t raw=0)
dvi_color (dvi_color const &c)
dvi_color (dvi_pixel const &p)
operator dvi_pixel & ()
operator dvi_pixel const & () const
operator uint32_t () const
subpixel_t & r ()
subpixel_t const & r () const
subpixel_t & g ()
subpixel_t const & g () const
subpixel_t & b ()
subpixel_t const & b () const
dvi_color & operator= (dvi_color const &p)
dvi_color & operator= (uint32_t p)
dvi_color & operator+= (dvi_color const &p)
dvi_color & operator-= (dvi_color const &p)
dvi_color & operator|= (dvi_color const &p)
dvi_color & operator&= (dvi_color const &p)
Detailed Description
Definition at line 194 of file io.h.
Constructor & Destructor Documentation
dvi_color::dvi_color (uint8_t red, uint8_t green, uint8_t blue) [inline]
Definition at line 196 of file io.h.
References blue, green, and red.
dvi_color::dvi_color (uint8_t const (&) rgb[3]) [inline]
Definition at line 201 of file io.h.
References dvi_color().
Referenced by dvi_color().
dvi_color::dvi_color (uint32_t raw = 0) [inline]
Definition at line 202 of file io.h.
dvi_color::dvi_color (dvi_color const & c) [inline]
Definition at line 203 of file io.h.
References dvi_pixel_::raw.
dvi_color::dvi_color (dvi_pixel const & p) [inline]
Definition at line 204 of file io.h.
References dvi_pixel_::raw.
Member Function Documentation
subpixel_t& dvi_color::b () [inline]
Definition at line 217 of file io.h.
Referenced by fillpoly(), fillrect(), operator+=(), and operator-=().
subpixel_t const& dvi_color::b () const [inline]
Definition at line 218 of file io.h.
subpixel_t& dvi_color::g () [inline]
Definition at line 215 of file io.h.
Referenced by fillpoly(), fillrect(), operator+=(), and operator-=().
subpixel_t const& dvi_color::g () const [inline]
Definition at line 216 of file io.h.
dvi_color::operator dvi_pixel & () [inline]
Definition at line 206 of file io.h.
dvi_color::operator dvi_pixel const & () const [inline]
Definition at line 207 of file io.h.
dvi_color::operator uint32_t () const [inline]
Definition at line 208 of file io.h.
dvi_color& dvi_color::operator&= (dvi_color const & p) [inline]
Definition at line 228 of file io.h.
References dvi_pixel_::raw.
dvi_color& dvi_color::operator+= (dvi_color const & p) [inline]
Definition at line 225 of file io.h.
References b, b(), g, g(), r, and r().
dvi_color& dvi_color::operator-= (dvi_color const & p) [inline]
Definition at line 226 of file io.h.
References b, b(), g, g(), r, and r().
dvi_color& dvi_color::operator= (dvi_color const & p) [inline]
Definition at line 223 of file io.h.
dvi_color& dvi_color::operator= (uint32_t p) [inline]
Definition at line 224 of file io.h.
dvi_color& dvi_color::operator|= (dvi_color const & p) [inline]
Definition at line 227 of file io.h.
References dvi_pixel_::raw.
subpixel_t& dvi_color::r () [inline]
Definition at line 213 of file io.h.
Referenced by fillpoly(), fillrect(), operator+=(), and operator-=().
subpixel_t const& dvi_color::r () const [inline]
Definition at line 214 of file io.h.
The documentation for this class was generated from the following file:
include/sys/io.h