Starburst: mfifo_t< T, FIFO_READERS, FIFO_SIZE_BITS, B > Class Template Reference
mfifo_t< T, FIFO_READERS, FIFO_SIZE_BITS, B > Class Template Reference
#include <mfifo.h>
Data Structures
class elem_t
Public Types
typedef SmallestUInt
< FIFO_SIZE_BITS+1 >::type pointer_t
Public Member Functions
mfifo_t ()
elem_t::ScopeX reserve () __attribute__((always_inline))
void push (const T &e)
elem_t::ScopeRO front (int me=0) __attribute__((always_inline))
void pop (int me=0)
void pop (T &o, int me=0)
Static Public Member Functions
static T data_t ()
Static Public Attributes
static const int FIFO_SIZE = 1<<FIFO_SIZE_BITS
Protected Member Functions
elem_t & acquire_elem ()
elem_t & front_elem (int me)
void bump (int me)
elem_t & w_elem (int i)
elem_t & r_elem (int i)
elem_t & operator[] (int i)
Detailed Description
template<typename T, int FIFO_READERS = 4, int FIFO_SIZE_BITS = 3, typename B = ::PMC_NS::ring>
class mfifo_t< T, FIFO_READERS, FIFO_SIZE_BITS, B >
Definition at line 10 of file mfifo.h.
Member Typedef Documentation
template<typename T , int FIFO_READERS = 4, int FIFO_SIZE_BITS = 3, typename B = ::PMC_NS::ring> typedef SmallestUInt<FIFO_SIZE_BITS+1>::type mfifo_t< T, FIFO_READERS, FIFO_SIZE_BITS, B >::pointer_t
Definition at line 21 of file mfifo.h.
Constructor & Destructor Documentation
template<typename T , int FIFO_READERS = 4, int FIFO_SIZE_BITS = 3, typename B = ::PMC_NS::ring> mfifo_t< T, FIFO_READERS, FIFO_SIZE_BITS, B >::mfifo_t () [inline]
Definition at line 18 of file mfifo.h.
Member Function Documentation
template<typename T , int FIFO_READERS = 4, int FIFO_SIZE_BITS = 3, typename B = ::PMC_NS::ring> elem_t& mfifo_t< T, FIFO_READERS, FIFO_SIZE_BITS, B >::acquire_elem () [inline, protected]
Definition at line 91 of file mfifo.h.
References b, PMC_NS::Var< T, B >::entry_x(), mfifo_t< T, FIFO_READERS, FIFO_SIZE_BITS, B >::FIFO_SIZE, GetProcID(), MFIFO_DEBUG, r, ScopeX_type, mfifo_t< T, FIFO_READERS, FIFO_SIZE_BITS, B >::w_elem(), and Yield().
Referenced by mfifo_t< T, FIFO_READERS, FIFO_SIZE_BITS, B >::reserve().
template<typename T , int FIFO_READERS = 4, int FIFO_SIZE_BITS = 3, typename B = ::PMC_NS::ring> void mfifo_t< T, FIFO_READERS, FIFO_SIZE_BITS, B >::bump (int me) [inline, protected]
Definition at line 129 of file mfifo.h.
References PMC_NS::Var< T, B >::entry_x(), PMC_NS::Var< T, B >::fence(), GetProcID(), MFIFO_DEBUG, and ScopeX_type.
Referenced by mfifo_t< T, FIFO_READERS, FIFO_SIZE_BITS, B >::pop().
template<typename T , int FIFO_READERS = 4, int FIFO_SIZE_BITS = 3, typename B = ::PMC_NS::ring> static T mfifo_t< T, FIFO_READERS, FIFO_SIZE_BITS, B >::data_t () [static]
template<typename T , int FIFO_READERS = 4, int FIFO_SIZE_BITS = 3, typename B = ::PMC_NS::ring> elem_t::ScopeRO mfifo_t< T, FIFO_READERS, FIFO_SIZE_BITS, B >::front (int me = 0) [inline]
Definition at line 74 of file mfifo.h.
References mfifo_t< T, FIFO_READERS, FIFO_SIZE_BITS, B >::elem_t::entry_ro(), mfifo_t< T, FIFO_READERS, FIFO_SIZE_BITS, B >::front_elem(), GetProcID(), and MFIFO_DEBUG.
Referenced by mfifo_t< T, FIFO_READERS, FIFO_SIZE_BITS, B >::pop().
template<typename T , int FIFO_READERS = 4, int FIFO_SIZE_BITS = 3, typename B = ::PMC_NS::ring> elem_t& mfifo_t< T, FIFO_READERS, FIFO_SIZE_BITS, B >::front_elem (int me) [inline, protected]
Definition at line 112 of file mfifo.h.
References b, PMC_NS::Var< T, B >::fence(), GetProcID(), MFIFO_DEBUG, PMC_NS::Var< T, B >::poll(), r, mfifo_t< T, FIFO_READERS, FIFO_SIZE_BITS, B >::r_elem(), and Yield().
Referenced by mfifo_t< T, FIFO_READERS, FIFO_SIZE_BITS, B >::front().
template<typename T , int FIFO_READERS = 4, int FIFO_SIZE_BITS = 3, typename B = ::PMC_NS::ring> elem_t& mfifo_t< T, FIFO_READERS, FIFO_SIZE_BITS, B >::operator[] (int i) [inline, protected]
Definition at line 140 of file mfifo.h.
References mfifo_t< T, FIFO_READERS, FIFO_SIZE_BITS, B >::r_elem().
template<typename T , int FIFO_READERS = 4, int FIFO_SIZE_BITS = 3, typename B = ::PMC_NS::ring> void mfifo_t< T, FIFO_READERS, FIFO_SIZE_BITS, B >::pop (int me = 0) [inline]
Definition at line 79 of file mfifo.h.
References mfifo_t< T, FIFO_READERS, FIFO_SIZE_BITS, B >::bump(), GetProcID(), and MFIFO_DEBUG.
template<typename T , int FIFO_READERS = 4, int FIFO_SIZE_BITS = 3, typename B = ::PMC_NS::ring> void mfifo_t< T, FIFO_READERS, FIFO_SIZE_BITS, B >::pop (T & o, int me = 0) [inline]
Definition at line 84 of file mfifo.h.
References mfifo_t< T, FIFO_READERS, FIFO_SIZE_BITS, B >::bump(), mfifo_t< T, FIFO_READERS, FIFO_SIZE_BITS, B >::front(), GetProcID(), MFIFO_DEBUG, and PMC_NS::T.
template<typename T , int FIFO_READERS = 4, int FIFO_SIZE_BITS = 3, typename B = ::PMC_NS::ring> void mfifo_t< T, FIFO_READERS, FIFO_SIZE_BITS, B >::push (const T & e) [inline]
Definition at line 69 of file mfifo.h.
References GetProcID(), MFIFO_DEBUG, and mfifo_t< T, FIFO_READERS, FIFO_SIZE_BITS, B >::reserve().
template<typename T , int FIFO_READERS = 4, int FIFO_SIZE_BITS = 3, typename B = ::PMC_NS::ring> elem_t& mfifo_t< T, FIFO_READERS, FIFO_SIZE_BITS, B >::r_elem (int i) [inline, protected]
Definition at line 139 of file mfifo.h.
References mfifo_t< T, FIFO_READERS, FIFO_SIZE_BITS, B >::FIFO_SIZE.
Referenced by mfifo_t< T, FIFO_READERS, FIFO_SIZE_BITS, B >::front_elem(), and mfifo_t< T, FIFO_READERS, FIFO_SIZE_BITS, B >::operator[]().
template<typename T , int FIFO_READERS = 4, int FIFO_SIZE_BITS = 3, typename B = ::PMC_NS::ring> elem_t::ScopeX mfifo_t< T, FIFO_READERS, FIFO_SIZE_BITS, B >::reserve () [inline]
Definition at line 65 of file mfifo.h.
References mfifo_t< T, FIFO_READERS, FIFO_SIZE_BITS, B >::acquire_elem(), and mfifo_t< T, FIFO_READERS, FIFO_SIZE_BITS, B >::elem_t::entry_x().
Referenced by mfifo_t< T, FIFO_READERS, FIFO_SIZE_BITS, B >::push().
template<typename T , int FIFO_READERS = 4, int FIFO_SIZE_BITS = 3, typename B = ::PMC_NS::ring> elem_t& mfifo_t< T, FIFO_READERS, FIFO_SIZE_BITS, B >::w_elem (int i) [inline, protected]
Definition at line 138 of file mfifo.h.
References mfifo_t< T, FIFO_READERS, FIFO_SIZE_BITS, B >::FIFO_SIZE.
Referenced by mfifo_t< T, FIFO_READERS, FIFO_SIZE_BITS, B >::acquire_elem().
Field Documentation
template<typename T , int FIFO_READERS = 4, int FIFO_SIZE_BITS = 3, typename B = ::PMC_NS::ring> const int mfifo_t< T, FIFO_READERS, FIFO_SIZE_BITS, B >::FIFO_SIZE = 1<<FIFO_SIZE_BITS [static]
Definition at line 20 of file mfifo.h.
Referenced by mfifo_t< T, FIFO_READERS, FIFO_SIZE_BITS, B >::acquire_elem(), mfifo_t< T, FIFO_READERS, FIFO_SIZE_BITS, B >::r_elem(), and mfifo_t< T, FIFO_READERS, FIFO_SIZE_BITS, B >::w_elem().
The documentation for this class was generated from the following file:
include/mfifo.h