Starburst: PMC_NS::ScopeX< V > Class Template Reference
PMC_NS::ScopeX< V > Class Template Reference
#include <pmc.h>
Public Types
typedef V::type T
typedef Scope< V, T > base
Public Member Functions
ScopeX ()
ScopeX (V &v, T &data)
ScopeX (ScopeX &s)
ScopeX (const typename base::ScopePtr ptr)
~ScopeX () __attribute__((always_inline))
void exit_x (bool cleanup=false) __attribute__((always_inline))
void flush () __attribute__((always_inline))
ScopeX & operator= (const T &rhs)
T & read () __attribute__((always_inline)) throw ()
operator T & () __attribute__((always_inline)) throw ()
T * operator-> () __attribute__((always_inline)) throw ()
T & operator* () __attribute__((always_inline)) throw ()
Protected Member Functions
bool did_read () const __attribute__((always_inline)) throw ()
bool did_write () const __attribute__((always_inline)) throw ()
Detailed Description
template<typename V>
class PMC_NS::ScopeX< V >
Definition at line 602 of file pmc.h.
Member Typedef Documentation
template<typename V > typedef Scope<V,T> PMC_NS::ScopeX< V >::base
Definition at line 605 of file pmc.h.
template<typename V > typedef V::type PMC_NS::ScopeX< V >::T
Definition at line 604 of file pmc.h.
Constructor & Destructor Documentation
template<typename V > PMC_NS::ScopeX< V >::ScopeX () [inline]
Definition at line 607 of file pmc.h.
template<typename V > PMC_NS::ScopeX< V >::ScopeX (V & v, T & data) [inline]
Definition at line 608 of file pmc.h.
template<typename V > PMC_NS::ScopeX< V >::ScopeX (ScopeX< V > & s) [inline]
Definition at line 609 of file pmc.h.
template<typename V > PMC_NS::ScopeX< V >::ScopeX (const typename base::ScopePtr ptr) [inline]
Definition at line 610 of file pmc.h.
template<typename V > PMC_NS::ScopeX< V >::~ScopeX () [inline]
Definition at line 612 of file pmc.h.
References PMC_NS::ScopeX< V >::exit_x(), and PMC_NS::Scope< V >::in_scope().
Member Function Documentation
template<typename V > bool PMC_NS::ScopeX< V >::did_read () const throw () [inline, protected]
Definition at line 638 of file pmc.h.
Referenced by PMC_NS::ScopeX< V >::exit_x(), and PMC_NS::ScopeX< V >::flush().
template<typename V > bool PMC_NS::ScopeX< V >::did_write () const throw () [inline, protected]
Definition at line 641 of file pmc.h.
Referenced by PMC_NS::ScopeX< V >::exit_x(), and PMC_NS::ScopeX< V >::flush().
template<typename V > void PMC_NS::ScopeX< V >::exit_x (bool cleanup = false) [inline]
Definition at line 616 of file pmc.h.
References PMC_NS::Scope< V >::data(), PMC_NS::ScopeX< V >::did_read(), PMC_NS::ScopeX< V >::did_write(), and PMC_NS::Scope< V >::release().
Referenced by PMC_NS::ScopeX< V >::~ScopeX().
template<typename V > void PMC_NS::ScopeX< V >::flush () [inline]
Definition at line 619 of file pmc.h.
References PMC_NS::Scope< V >::data(), PMC_NS::ScopeX< V >::did_read(), PMC_NS::ScopeX< V >::did_write(), and PMC_NS::Scope< V >::var().
template<typename V > PMC_NS::ScopeX< V >::operator T & () throw () [inline]
Reimplemented from PMC_NS::Scope< V >.
Definition at line 631 of file pmc.h.
References PMC_NS::Scope< V, T >::operator T &().
template<typename V > T& PMC_NS::ScopeX< V >::operator* () throw () [inline]
Definition at line 636 of file pmc.h.
template<typename V > T* PMC_NS::ScopeX< V >::operator-> () throw () [inline]
Definition at line 635 of file pmc.h.
template<typename V > ScopeX& PMC_NS::ScopeX< V >::operator= (const T & rhs) [inline]
Definition at line 623 of file pmc.h.
References PMC_NS::Scope< V >::data().
template<typename V > T& PMC_NS::ScopeX< V >::read () throw () [inline]
Definition at line 628 of file pmc.h.
The documentation for this class was generated from the following file:
include/pmc.h