Starburst: Cfifo_sink< Type > Class Template Reference
Cfifo_sink< Type > Class Template Reference
#include <cfifo_sink.h>
Public Member Functions
Cfifo_sink (CFifo< Type, CFifo<>::w > *fifo)
void writeState ()
void setupStream ()
int getType ()
void run ()
Data Fields
void * dest_addr
Detailed Description
template<typename Type>
class Cfifo_sink< Type >
Definition at line 19 of file cfifo_sink.h.
Constructor & Destructor Documentation
template<class Type > Cfifo_sink< Type >::Cfifo_sink (CFifo< Type, CFifo<>::w > * fifo)
Definition at line 36 of file cfifo_sink.h.
Member Function Documentation
template<class Type > int Cfifo_sink< Type >::getType () [virtual]
Implements Accelerator.
Definition at line 85 of file cfifo_sink.h.
References ACC_CORE.
template<class Type > void Cfifo_sink< Type >::run () [virtual]
Reimplemented from Accelerator.
Definition at line 69 of file cfifo_sink.h.
template<class Type > void Cfifo_sink< Type >::setupStream () [virtual]
Reimplemented from Accelerator.
Definition at line 76 of file cfifo_sink.h.
References Accelerator::setupStream().
template<class Type > void Cfifo_sink< Type >::writeState () [virtual]
Reimplemented from Accelerator.
Definition at line 41 of file cfifo_sink.h.
References ringshell_ctrl_dev_t::ack_return, ringshell_ctrl_dev_t::data_forward, Accelerator::getRingConfAddr(), and Reader::read().
Field Documentation
template<typename Type > void* Cfifo_sink< Type >::dest_addr
Definition at line 27 of file cfifo_sink.h.
The documentation for this class was generated from the following file:
include/accelerator/cfifo_sink.h