Starburst: mfifo_t< T, FIFO_READERS, FIFO_SIZE_BITS, B >::elem_t Class Reference
mfifo_t< T, FIFO_READERS, FIFO_SIZE_BITS, B >::elem_t Class Reference
#include <mfifo.h>
Public Types
typedef ::PMC_NS::Var< T, B > base
typedef ::PMC_NS::ScopeX< elem_t > ScopeX
typedef ::PMC_NS::ScopeRO< elem_t > ScopeRO
Public Member Functions
elem_t ()
elem_t * operator& ()
ScopeX entry_x () __attribute__((always_inline)) throw ()
ScopeRO entry_ro () __attribute__((always_inline)) throw ()
const T poll () __attribute__((always_inline)) throw ()
operator const T () __attribute__((always_inline)) throw ()
Protected Member Functions
void exit_x (T &data, bool did_read=true, bool did_write=true, bool cleanup=true) __attribute__((always_inline)) throw ()
void exit_ro (const T &data, bool did_read=true, bool cleanup=true) __attribute__((always_inline)) throw ()
Friends
class mfifo_t< T, FIFO_READERS, FIFO_SIZE_BITS, B >
class ::PMC_NS::ScopeX< elem_t >
class ::PMC_NS::ScopeRO< elem_t >
Detailed Description
template<typename T, int FIFO_READERS = 4, int FIFO_SIZE_BITS = 3, typename B = ::PMC_NS::ring>
class mfifo_t< T, FIFO_READERS, FIFO_SIZE_BITS, B >::elem_t
Definition at line 24 of file mfifo.h.
Member Typedef Documentation
template<typename T , int FIFO_READERS = 4, int FIFO_SIZE_BITS = 3, typename B = ::PMC_NS::ring> typedef ::PMC_NS::Var<T,B> mfifo_t< T, FIFO_READERS, FIFO_SIZE_BITS, B >::elem_t::base
Reimplemented from PMC_NS::Var< T, B >.
Definition at line 26 of file mfifo.h.
template<typename T , int FIFO_READERS = 4, int FIFO_SIZE_BITS = 3, typename B = ::PMC_NS::ring> typedef ::PMC_NS::ScopeRO<elem_t> mfifo_t< T, FIFO_READERS, FIFO_SIZE_BITS, B >::elem_t::ScopeRO
Definition at line 28 of file mfifo.h.
template<typename T , int FIFO_READERS = 4, int FIFO_SIZE_BITS = 3, typename B = ::PMC_NS::ring> typedef ::PMC_NS::ScopeX<elem_t> mfifo_t< T, FIFO_READERS, FIFO_SIZE_BITS, B >::elem_t::ScopeX
Definition at line 27 of file mfifo.h.
Constructor & Destructor Documentation
template<typename T , int FIFO_READERS = 4, int FIFO_SIZE_BITS = 3, typename B = ::PMC_NS::ring> mfifo_t< T, FIFO_READERS, FIFO_SIZE_BITS, B >::elem_t::elem_t () [inline]
Definition at line 29 of file mfifo.h.
Member Function Documentation
template<typename T , int FIFO_READERS = 4, int FIFO_SIZE_BITS = 3, typename B = ::PMC_NS::ring> ScopeRO mfifo_t< T, FIFO_READERS, FIFO_SIZE_BITS, B >::elem_t::entry_ro () throw () [inline]
Reimplemented from PMC_NS::Var< T, B >.
Definition at line 37 of file mfifo.h.
Referenced by mfifo_t< T, FIFO_READERS, FIFO_SIZE_BITS, B >::front(), and mfifo_t< T, FIFO_READERS, FIFO_SIZE_BITS, B >::elem_t::poll().
template<typename T , int FIFO_READERS = 4, int FIFO_SIZE_BITS = 3, typename B = ::PMC_NS::ring> ScopeX mfifo_t< T, FIFO_READERS, FIFO_SIZE_BITS, B >::elem_t::entry_x () throw () [inline]
Reimplemented from PMC_NS::Var< T, B >.
Definition at line 33 of file mfifo.h.
References GetProcID(), and MFIFO_DEBUG.
Referenced by mfifo_t< T, FIFO_READERS, FIFO_SIZE_BITS, B >::reserve().
template<typename T , int FIFO_READERS = 4, int FIFO_SIZE_BITS = 3, typename B = ::PMC_NS::ring> void mfifo_t< T, FIFO_READERS, FIFO_SIZE_BITS, B >::elem_t::exit_ro (const T & data, bool did_read = true, bool cleanup = true) throw () [inline, protected]
Definition at line 51 of file mfifo.h.
References mfifo_t< T, FIFO_READERS, FIFO_SIZE_BITS, B >::elem_t::exit_x().
template<typename T , int FIFO_READERS = 4, int FIFO_SIZE_BITS = 3, typename B = ::PMC_NS::ring> void mfifo_t< T, FIFO_READERS, FIFO_SIZE_BITS, B >::elem_t::exit_x (T & data, bool did_read = true, bool did_write = true, bool cleanup = true) throw () [inline, protected]
Definition at line 43 of file mfifo.h.
References PMC_NS::Var< T, B >::entry_x(), PMC_NS::Var< T, B >::fence(), GetProcID(), MFIFO_DEBUG, and ScopeX_type.
Referenced by mfifo_t< T, FIFO_READERS, FIFO_SIZE_BITS, B >::elem_t::exit_ro().
template<typename T , int FIFO_READERS = 4, int FIFO_SIZE_BITS = 3, typename B = ::PMC_NS::ring> mfifo_t< T, FIFO_READERS, FIFO_SIZE_BITS, B >::elem_t::operator const T () throw () [inline]
Reimplemented from PMC_NS::Var< T, B >.
Definition at line 41 of file mfifo.h.
References mfifo_t< T, FIFO_READERS, FIFO_SIZE_BITS, B >::elem_t::poll().
template<typename T , int FIFO_READERS = 4, int FIFO_SIZE_BITS = 3, typename B = ::PMC_NS::ring> elem_t* mfifo_t< T, FIFO_READERS, FIFO_SIZE_BITS, B >::elem_t::operator& () [inline]
Reimplemented from PMC_NS::Var< T, B >.
Definition at line 31 of file mfifo.h.
template<typename T , int FIFO_READERS = 4, int FIFO_SIZE_BITS = 3, typename B = ::PMC_NS::ring> const T mfifo_t< T, FIFO_READERS, FIFO_SIZE_BITS, B >::elem_t::poll () throw () [inline]
Reimplemented from PMC_NS::Var< T, B >.
Definition at line 40 of file mfifo.h.
References mfifo_t< T, FIFO_READERS, FIFO_SIZE_BITS, B >::elem_t::entry_ro().
Referenced by mfifo_t< T, FIFO_READERS, FIFO_SIZE_BITS, B >::elem_t::operator const T().
Friends And Related Function Documentation
template<typename T , int FIFO_READERS = 4, int FIFO_SIZE_BITS = 3, typename B = ::PMC_NS::ring> friend class ::PMC_NS::ScopeRO< elem_t > [friend]
Definition at line 62 of file mfifo.h.
template<typename T , int FIFO_READERS = 4, int FIFO_SIZE_BITS = 3, typename B = ::PMC_NS::ring> friend class ::PMC_NS::ScopeX< elem_t > [friend]
Definition at line 61 of file mfifo.h.
template<typename T , int FIFO_READERS = 4, int FIFO_SIZE_BITS = 3, typename B = ::PMC_NS::ring> friend class mfifo_t< T, FIFO_READERS, FIFO_SIZE_BITS, B > [friend]
Definition at line 60 of file mfifo.h.
The documentation for this class was generated from the following file:
include/mfifo.h