Starburst: PMC_NS::SASPMBackend< T, C > Class Template Reference
PMC_NS::SASPMBackend< T, C > Class Template Reference
#include <pmc_sa.h>
Public Types
typedef SAMultiLocation< T > base
typedef C callback
typedef sa_spm< C > backend_type
Public Member Functions
SASPMBackend ()
~SASPMBackend ()
T & entry_x () __attribute__((always_inline)) throw ()
void exit_x (T &data, bool did_read=true, bool did_write=true, bool cleanup=false) __attribute__((always_inline)) throw ()
const T & entry_ro () __attribute__((always_inline)) throw ()
void exit_ro (const T &data, bool did_read=true, bool cleanup=false) const __attribute__((always_inline)) throw ()
void flush (T &data, bool did_read=true, bool did_write=true) __attribute__((always_inline)) throw ()
bool atomic () const __attribute__((always_inline
Detailed Description
template<typename T, typename C = SACallback>
class PMC_NS::SASPMBackend< T, C >
Definition at line 111 of file pmc_sa.h.
Member Typedef Documentation
template<typename T , typename C = SACallback> typedef sa_spm<C> PMC_NS::SASPMBackend< T, C >::backend_type
Definition at line 115 of file pmc_sa.h.
template<typename T , typename C = SACallback> typedef SAMultiLocation<T> PMC_NS::SASPMBackend< T, C >::base
Reimplemented from PMC_NS::SAMultiLocation< T >.
Definition at line 113 of file pmc_sa.h.
template<typename T , typename C = SACallback> typedef C PMC_NS::SASPMBackend< T, C >::callback
Definition at line 114 of file pmc_sa.h.
Constructor & Destructor Documentation
template<typename T , typename C = SACallback> PMC_NS::SASPMBackend< T, C >::SASPMBackend () [inline]
Definition at line 116 of file pmc_sa.h.
References PMC_ASSERT.
template<typename T , typename C = SACallback> PMC_NS::SASPMBackend< T, C >::~SASPMBackend () [inline]
Definition at line 117 of file pmc_sa.h.
Member Function Documentation
template<typename T , typename C = SACallback> bool PMC_NS::SASPMBackend< T, C >::atomic () const
Reimplemented from PMC_NS::SAMultiLocation< T >.
template<typename T , typename C = SACallback> const T& PMC_NS::SASPMBackend< T, C >::entry_ro () throw () [inline]
Reimplemented from PMC_NS::SAMultiLocation< T >.
Definition at line 130 of file pmc_sa.h.
References PMC_BACKEND_TO_VAR_PTR, and unlikely.
template<typename T , typename C = SACallback> T& PMC_NS::SASPMBackend< T, C >::entry_x () throw () [inline]
Reimplemented from PMC_NS::SAMultiLocation< T >.
Definition at line 120 of file pmc_sa.h.
References PMC_ASSERT, and PMC_BACKEND_TO_VAR_PTR.
template<typename T , typename C = SACallback> void PMC_NS::SASPMBackend< T, C >::exit_ro (const T & data, bool did_read = true, bool cleanup = false) const throw () [inline]
Definition at line 137 of file pmc_sa.h.
References ffree().
template<typename T , typename C = SACallback> void PMC_NS::SASPMBackend< T, C >::exit_x (T & data, bool did_read = true, bool did_write = true, bool cleanup = false) throw () [inline]
Reimplemented from PMC_NS::SAMultiLocation< T >.
Definition at line 124 of file pmc_sa.h.
References ffree(), PMC_NS::SASPMBackend< T, C >::flush(), and PMC_BACKEND_TO_VAR_PTR.
template<typename T , typename C = SACallback> void PMC_NS::SASPMBackend< T, C >::flush (T & data, bool did_read = true, bool did_write = true) throw () [inline]
Reimplemented from PMC_NS::SAMultiLocation< T >.
Definition at line 140 of file pmc_sa.h.
References PMC_NS::Location< T >::access().
Referenced by PMC_NS::SASPMBackend< T, C >::exit_x().
The documentation for this class was generated from the following file:
include/pmc_sa.h