Starburst: posix/cond.cc File Reference
posix/cond.cc File Reference
POSIX condition implementation, with software cache coherency.
#include <sys/api.h>
#include <mc.h>
#include <pthread.h>
#include <unistd.h>
Defines
#define CHAN_LABEL_COND_MASK (CHAN_LABEL_COND-1)
#define CHAN_COND_LABEL(cond) (-((CHAN_LABEL_COND_MASK&((unsigned int)(cond)))|CHAN_LABEL_COND))
#define COND_STATE_FREE 0
#define COND_STATE_WAITING 1
#define COND_STATE_SIGNALLED 2
#define pthread_stats_elem_register(...)
#define pthread_stats_elem_unregister(...)
#define pthread_stats_global_init(...) 0
#define pthread_stats_global_cleanup(...) 0
#define pthread_stats_thread_init(...) 0
Functions
int pthread_cond_init (pthread_cond_t *cond, const pthread_condattr_t *attr)
int pthread_cond_destroy (pthread_cond_t *cond)
int _pthread_cond_signal (pthread_cond_t *cond, bool all)
int pthread_cond_signal (pthread_cond_t *cond)
int pthread_cond_broadcast (pthread_cond_t *cond)
int _pthread_cond_wait (pthread_cond_t *cond, pthread_mutex_t *mutex, const struct timespec *abstime)
int pthread_cond_wait (pthread_cond_t *cond, pthread_mutex_t *mutex)
int pthread_cond_timedwait (pthread_cond_t *cond, pthread_mutex_t *mutex, const struct timespec *abstime)
int pthread_condattr_init (pthread_condattr_t *attr)
int pthread_condattr_destroy (pthread_condattr_t *attr)
int pthread_condattr_getpshared (const pthread_condattr_t *attr, int *pshared)
int pthread_condattr_setpshared (pthread_condattr_t *attr, int pshared)
int pthread_cond_global_init ()
int pthread_cond_global_cleanup ()
int pthread_cond_thread_init ()
int pthread_cond_thread_cleanup ()
Detailed Description
POSIX condition implementation, with software cache coherency.
Definition in file cond.cc.
Define Documentation
#define CHAN_COND_LABEL (cond) (-((CHAN_LABEL_COND_MASK&((unsigned int)(cond)))|CHAN_LABEL_COND))
Definition at line 11 of file cond.cc.
#define CHAN_LABEL_COND_MASK (CHAN_LABEL_COND-1)
Definition at line 10 of file cond.cc.
#define COND_STATE_FREE 0
Definition at line 13 of file cond.cc.
Referenced by _pthread_cond_wait(), and pthread_cond_init().
#define COND_STATE_SIGNALLED 2
Definition at line 15 of file cond.cc.
Referenced by _pthread_cond_signal(), and _pthread_cond_wait().
#define COND_STATE_WAITING 1
Definition at line 14 of file cond.cc.
Referenced by _pthread_cond_signal(), _pthread_cond_wait(), and pthread_cond_destroy().
#define pthread_stats_elem_register (...)
Definition at line 20 of file cond.cc.
#define pthread_stats_elem_unregister (...)
Definition at line 21 of file cond.cc.
#define pthread_stats_global_cleanup (...) 0
Definition at line 23 of file cond.cc.
#define pthread_stats_global_init (...) 0
Definition at line 22 of file cond.cc.
#define pthread_stats_thread_init (...) 0
Definition at line 24 of file cond.cc.
Function Documentation
int _pthread_cond_signal (pthread_cond_t * cond, bool all)
Definition at line 73 of file cond.cc.
References COND_NR_IDS, COND_STATE_SIGNALLED, COND_STATE_WAITING, pthread_cond_t::last_signalled, mc_entry_ro, mc_entry_wou, mc_exit_ro, mc_exit_wou, pthread_kill(), SIGCONT, and unlikely.
Referenced by pthread_cond_broadcast(), and pthread_cond_signal().
int _pthread_cond_wait (pthread_cond_t * cond, pthread_mutex_t * mutex, const struct timespec * abstime)
Definition at line 127 of file cond.cc.
References COND_STATE_FREE, COND_STATE_SIGNALLED, COND_STATE_WAITING, getgpid(), gettimeofday(), mc_entry_ro, mc_entry_rwu, mc_entry_wou, mc_exit_ro, mc_exit_rwu, mc_exit_wou, pthread_mutex_lock(), pthread_mutex_unlock(), PTHREAD_SPIN, sigaddset(), SIGCONT, sigemptyset(), Suspend(), timecmp(), TIMESTAMP_GET, TIMESTAMP_SET, unlikely, and Yield().
Referenced by pthread_cond_timedwait(), and pthread_cond_wait().
int pthread_cond_broadcast (pthread_cond_t * cond)
Definition at line 123 of file cond.cc.
References _pthread_cond_signal().
int pthread_cond_destroy (pthread_cond_t * cond)
Definition at line 53 of file cond.cc.
References COND_NR_IDS, COND_STATE_WAITING, mc_entry_ro, mc_exit_ro, and pthread_stats_elem_unregister.
Referenced by pipe_close().
int pthread_cond_global_cleanup (void)
Definition at line 296 of file cond.cc.
References pthread_stats_global_cleanup.
Referenced by pthread_global_cleanup().
int pthread_cond_global_init (void)
Definition at line 292 of file cond.cc.
References pthread_stats_global_init.
Referenced by pthread_global_init().
int pthread_cond_init (pthread_cond_t * cond, const pthread_condattr_t * attr)
Definition at line 27 of file cond.cc.
References pthread_cond_t::attr, COND_NR_IDS, COND_STATE_FREE, pthread_cond_t::last_signalled, mc_entry_wou, mc_exit_wou, pthread_condattr_init(), and pthread_stats_elem_register.
Referenced by pipe().
int pthread_cond_signal (pthread_cond_t * cond)
Definition at line 119 of file cond.cc.
References _pthread_cond_signal().
Referenced by pipe_read(), and pipe_write().
int pthread_cond_thread_cleanup (void)
Definition at line 304 of file cond.cc.
Referenced by pthread_thread_cleanup().
int pthread_cond_thread_init (void)
Definition at line 300 of file cond.cc.
References pthread_stats_thread_init.
Referenced by pthread_thread_init().
int pthread_cond_timedwait (pthread_cond_t * cond, pthread_mutex_t * mutex, const struct timespec * abstime)
Definition at line 248 of file cond.cc.
References _pthread_cond_wait().
int pthread_cond_wait (pthread_cond_t * cond, pthread_mutex_t * mutex)
Definition at line 244 of file cond.cc.
References _pthread_cond_wait().
Referenced by pipe_read(), and pipe_write().
int pthread_condattr_destroy (pthread_condattr_t * attr)
Definition at line 261 of file cond.cc.
int pthread_condattr_getpshared (const pthread_condattr_t * attr, int * pshared)
Definition at line 267 of file cond.cc.
References pthread_condattr_t::pshared.
int pthread_condattr_init (pthread_condattr_t * attr)
Definition at line 254 of file cond.cc.
References pthread_condattr_t::pshared, and PTHREAD_PROCESS_PRIVATE.
Referenced by pthread_cond_init().
int pthread_condattr_setpshared (pthread_condattr_t * attr, int pshared)
Definition at line 274 of file cond.cc.
References pthread_condattr_t::pshared.