Starburst: include/daemons.h File Reference
include/daemons.h File Reference
Daemons
All daemon definitions.
#include <sys/helix_config.h>
#include <sys/kernel.h>
#include <fifo.h>
#include <mail.h>
Data Structures
struct tdcmd_t
struct tdcmd_remote_t
struct tdcmd_local_t
struct malloc_buffer_t
Defines
#define TD_MAX_U_PROCESSES (2*MAX_PROCESSES)
#define TASK_DAEMON_FIFO_SIZE (sizeof(tdcmd_remote_t))
#define TASK_DAEMON_TIMESLICE DAEMON_DEFAULT_TIMESLICE
#define TASK_DAEMON_STACK (DAEMON_DEFAULT_STACK*2)
#define TDCMD_NONE 0
#define TDCMD_BOOT_KERNEL 1
#define TDCMD_PROCESS_CREATE 2
#define TDCMD_PROCESS_START 3
#define TDCMD_PROCESS_DESTROY 4
#define TDCMD_PROCESS_WAIT 5
#define TDCMD_PROCESS_SET_FLAGS 6
#define TDCMD_PROCESS_GET_FLAGS 7
#define TDCMD_PROCESS_GET_STATE 8
#define TDCMD_PROCESS_SET_TIMESLICE 9
#define TDCMD_PROCESS_SIGNAL 10
#define TDCMD_CHANNEL_ALLOC 11
#define TDCMD_CHANNEL_ASSIGN 12
#define TDCMD_CHANNEL_LABEL 13
#define TDCMD_FIFO_ALLOC 14
#define TDCMD_FIFO_DESTROY 15
#define TDCMD_SIMPLEMAIL_ALLOC 16
#define TDCMD_MAIL_ALLOC 17
#define TDCMD_MAIL_DESTROY 18
#define TDCMD_SHEAP_ALLOC 19
#define TDCMD_SHEAP_CALLOC 20
#define TDCMD_SHEAP_REALLOC 21
#define TDCMD_SHEAP_FREE 22
#define TDCMD_REMOTE_CALL 23
#define TDCMD_ATOMIC_CAS 24
#define TDCMD_ATOMIC_XCHG 25
#define TDCMD_ATOMIC_ADD 26
#define TDCMD_SHUTDOWN 27
#define TDCMD_LOCK_REGISTER 28
#define TDCMD_LOCK_REQUEST 29
#define TDCMD_LOCK_ASK 30
#define TDCMD_LOCK_GIVEUP 31
#define TDCMD_SYNCEVENT_HIT 32
#define TDCMD_COUNT 33
#define dDestroySimpleMail(mail, proc) dDestroyMail((Mail*)mail,proc)
#define SMALLOC_PROC 0
Enumerations
enum proc_busy_t { PROC_IDLE, PROC_SYNC, PROC_ASYNC }
enum malloc_req_t {
MD_NONE, MD_ACK, MD_MALLOC, MD_CALLOC,
MD_REALLOC, MD_MOWN, MD_FREE, MD_FREEALL,
MD_EXIT
}
Functions
void InitHardware (void *arg)
Call to initialize hardware, such as network routes to essential peripherals.
void * InitTaskDaemon (void *kernel_param)
Initializes the task daemon.
int DefaultMulticoreSetup (int cores=0)
Initializes a default multi-core setup.
int GarbageCollect ()
Cleans up all unused resources.
void * DefaultTaskDaemon (void *arg)
The default implementation of the task daemon.
void * TaskDaemon (void *arg)
The task daemon on the master processor.
int dCreateProcess (pid_t &pid, void *(*main)(void *), void *arg, timems_t slicelength, unsigned int stack, int proc=-1) __attribute__((warn_unused_result))
Wrapper for a remote call to lCreateProcess().
int dStartProcess (pid_t pid, int proc=-1) __attribute__((warn_unused_result))
Wrapper for a remote call to lStartProcess().
int dDestroyProcess (pid_t pid, void **ret, int proc=-1)
Wrapper for a remote call to lDestroyProcess().
int dWaitProcess (pid_t pid, void **ret, int proc=-1) __attribute__((warn_unused_result))
Wrapper for a remote call to lJoinProcess().
int dSetProcessFlags (pid_t pid, int flags, int proc=-1)
Wrapper for a remote call to lSetProcessFlags().
int dGetProcessFlags (pid_t pid, int *flags, int proc=-1)
Wrapper for a remote call to lGetProcessFlags().
int dGetProcessState (pid_t pid, proc_state_t *state, bool *sighandling=NULL, int proc=-1)
Wrapper for a remote call to lGetProcessState().
int dSetProcessTimeslice (pid_t pid, timems_t slicelength, int proc=-1)
Wrapper for a remote call to lSetProcessTimeslice().
int dSendSignal (pid_t pid, int sig, union sigval *sv, int proc=-1)
Wrapper for a remote call to lSendSignal().
int dSyncEventHit (pid_t pid, void *event, int proc=-1)
int dAllocChannels (pid_t pid, int num_chan, int proc=-1) __attribute__((warn_unused_result))
Wrapper for a remote call to lAllocChannels().
int dAssignChannel (pid_t pid, int chan_id, void *channel, int label, int proc=-1)
Wrapper for a remote call to lAssignChannel().
int dSetChannelLabel (pid_t pid, int chan_id, int label, int proc=-1)
Wrapper for a remote call to lSetChannelLabel().
FifoEP * dAllocFifoEndPoint (unsigned int fifo_size, unsigned int element_size, int flags, int proc=-1)
Wrapper for a remote call to lAllocFifoEndPoint().
void dDestroyFifoEndPoint (FifoEP *fifo, int proc=-1)
Wrapper for a remote call to lDestroyFifoEndPoint().
SimpleMail * dAllocSimpleMail (int proc=-1)
Wrapper for a remote call to lAllocSimpleMail().
Mail * dAllocMail (unsigned int count, int proc=-1)
Wrapper for a remote call to lAllocMail().
void dDestroyMail (Mail *mail, int proc=-1)
Wrapper for a remote call to lDestroyMail().
int dBootKernels (int num, int *procs)
Boots the kernel on other processors.
void * dSMalloc (size_t size) __attribute__((warn_unused_result))
Internal function to forward the smalloc() request to the appropriate core.
void * dSCalloc (size_t nmemb, size_t size) __attribute__((warn_unused_result))
Internal function to forward the scalloc() request to the appropriate core.
void * dSRealloc (void *ptr, size_t size) __attribute__((warn_unused_result))
Internal function to forward the srealloc() request to the appropriate core.
void dSFree (void *ptr)
Internal function to forward the sfree() request to the appropriate core.
void * dRemoteCall (void *(*fun)(void *), void *arg, int proc=-1) _NO_THROW
Generic function to call all arbitrary functions an another core.
int dAtomicCAS (void *mem, int oldval, int newval)
An atomic compare-and-swap implementation.
int dAtomicXCHG (void *mem, int val)
An atomic exchange implementation.
int dAtomicAdd (void *mem, int val)
An atomic add implementation.
int dLockRegister (lck_my_locks_t *list)
Backend for lck_register().
int dLockRequest (void *l)
Backend for lck_request().
int dLockAsk (void *l, int gpid)
Backend for lck_ask().
int dLockGiveup (void *l)
Backend for lck_giveup().
void * MallocDaemon (void *arg)
Daemon to handle all processor heap operations.
int StartMallocDaemon () __attribute__((warn_unused_result))
Starts the MallocDaemon().
void IssueMallocRequest (malloc_buffer_t *b, malloc_req_t type)
Sends a request to the MallocDaemon().
int timer_repeat (void(*handler)(int, siginfo_t *, void *), void *arg, long interval_sec, long interval_nsec=0)
int StartTimerDaemon ()
Starts the timer daemon.
int StartDumpStatsDaemon (int interval, void *(*main)(void *), void(*tdstats)(void))
Stats the DumpStatsDaemon().
void do_gracefull_exit_funs ()
Function to cleanup process stuff, called by abort() and exit() (via atexit()).
void set_no_gracefull_exit ()
Prevents the calling process to be killed by the ShutdownDaemon on reboot.
int StartShutdownDaemon ()
Starts the ShutdownDaemon to gracefully shutdown the kernel.
Detailed Description
All daemon definitions.
Definition in file daemons.h.
Define Documentation
#define dDestroySimpleMail (mail, proc) dDestroyMail((Mail*)mail,proc)
Definition at line 211 of file daemons.h.
#define SMALLOC_PROC 0
Definition at line 254 of file daemons.h.
Referenced by dSCalloc(), dSFree(), dSMalloc(), dSRealloc(), scalloc(), sfree(), smalloc(), and srealloc().
#define TASK_DAEMON_FIFO_SIZE (sizeof(tdcmd_remote_t))
Definition at line 122 of file daemons.h.
Referenced by kInitKernel().
#define TASK_DAEMON_STACK (DAEMON_DEFAULT_STACK*2)
Definition at line 124 of file daemons.h.
Referenced by kStartTaskDaemon().
#define TASK_DAEMON_TIMESLICE DAEMON_DEFAULT_TIMESLICE
Definition at line 123 of file daemons.h.
Referenced by kStartTaskDaemon().
#define TD_MAX_U_PROCESSES (2*MAX_PROCESSES)
Definition at line 96 of file daemons.h.
Referenced by DefaultTaskDaemon(), and InitTaskDaemon().
#define TDCMD_ATOMIC_ADD 26
Definition at line 159 of file daemons.h.
Referenced by dAtomicAdd(), ForwardRequest(), and ProcessRequest().
#define TDCMD_ATOMIC_CAS 24
Definition at line 157 of file daemons.h.
Referenced by dAtomicCAS(), ForwardRequest(), and ProcessRequest().
#define TDCMD_ATOMIC_XCHG 25
Definition at line 158 of file daemons.h.
Referenced by dAtomicXCHG(), ForwardRequest(), and ProcessRequest().
#define TDCMD_BOOT_KERNEL 1
Definition at line 127 of file daemons.h.
#define TDCMD_CHANNEL_ALLOC 11
Definition at line 139 of file daemons.h.
Referenced by dAllocChannels(), ForwardRequest(), and ProcessRequest().
#define TDCMD_CHANNEL_ASSIGN 12
Definition at line 140 of file daemons.h.
Referenced by dAssignChannel(), ForwardRequest(), and ProcessRequest().
#define TDCMD_CHANNEL_LABEL 13
Definition at line 141 of file daemons.h.
Referenced by dSetChannelLabel(), ForwardRequest(), and ProcessRequest().
#define TDCMD_COUNT 33
Definition at line 172 of file daemons.h.
Referenced by StatsCount(), and StatsDump().
#define TDCMD_FIFO_ALLOC 14
Definition at line 143 of file daemons.h.
Referenced by dAllocFifoEndPoint(), ForwardRequest(), and ProcessRequest().
#define TDCMD_FIFO_DESTROY 15
Definition at line 144 of file daemons.h.
Referenced by dDestroyFifoEndPoint(), ForwardRequest(), and ProcessRequest().
#define TDCMD_LOCK_ASK 30
Definition at line 166 of file daemons.h.
Referenced by dLockAsk(), ForwardRequest(), and ProcessRequest().
#define TDCMD_LOCK_GIVEUP 31
Definition at line 167 of file daemons.h.
Referenced by dLockGiveup(), ForwardRequest(), and ProcessRequest().
#define TDCMD_LOCK_REGISTER 28
Definition at line 164 of file daemons.h.
Referenced by dLockRegister(), ForwardRequest(), and ProcessRequest().
#define TDCMD_LOCK_REQUEST 29
Definition at line 165 of file daemons.h.
Referenced by dLockRequest(), ForwardRequest(), and ProcessRequest().
#define TDCMD_MAIL_ALLOC 17
Definition at line 147 of file daemons.h.
Referenced by dAllocMail(), ForwardRequest(), and ProcessRequest().
#define TDCMD_MAIL_DESTROY 18
Definition at line 148 of file daemons.h.
Referenced by dDestroyMail(), ForwardRequest(), and ProcessRequest().
#define TDCMD_NONE 0
Definition at line 126 of file daemons.h.
Referenced by DefaultTaskDaemon(), GetIssueSlot(), and InitTaskDaemon().
#define TDCMD_PROCESS_CREATE 2
Definition at line 129 of file daemons.h.
Referenced by dCreateProcess(), ForwardRequest(), and ProcessRequest().
#define TDCMD_PROCESS_DESTROY 4
Definition at line 131 of file daemons.h.
Referenced by dDestroyProcess(), ForwardRequest(), and ProcessRequest().
#define TDCMD_PROCESS_GET_FLAGS 7
Definition at line 134 of file daemons.h.
Referenced by dGetProcessFlags(), ForwardRequest(), and ProcessRequest().
#define TDCMD_PROCESS_GET_STATE 8
Definition at line 135 of file daemons.h.
Referenced by dGetProcessState(), ForwardRequest(), and ProcessRequest().
#define TDCMD_PROCESS_SET_FLAGS 6
Definition at line 133 of file daemons.h.
Referenced by dSetProcessFlags(), ForwardRequest(), and ProcessRequest().
#define TDCMD_PROCESS_SET_TIMESLICE 9
Definition at line 136 of file daemons.h.
Referenced by dSetProcessTimeslice(), ForwardRequest(), and ProcessRequest().
#define TDCMD_PROCESS_SIGNAL 10
Definition at line 137 of file daemons.h.
Referenced by dSendSignal(), ForwardRequest(), and ProcessRequest().
#define TDCMD_PROCESS_START 3
Definition at line 130 of file daemons.h.
Referenced by dStartProcess(), ForwardRequest(), and ProcessRequest().
#define TDCMD_PROCESS_WAIT 5
Definition at line 132 of file daemons.h.
Referenced by dWaitProcess(), ForwardRequest(), and ProcessRequest().
#define TDCMD_REMOTE_CALL 23
Definition at line 155 of file daemons.h.
Referenced by dRemoteCall(), ForwardRequest(), and ProcessRequest().
#define TDCMD_SHEAP_ALLOC 19
Definition at line 150 of file daemons.h.
Referenced by dSMalloc(), ForwardRequest(), and ProcessRequest().
#define TDCMD_SHEAP_CALLOC 20
Definition at line 151 of file daemons.h.
Referenced by dSCalloc(), ForwardRequest(), and ProcessRequest().
#define TDCMD_SHEAP_FREE 22
Definition at line 153 of file daemons.h.
Referenced by dSFree(), ForwardRequest(), and ProcessRequest().
#define TDCMD_SHEAP_REALLOC 21
Definition at line 152 of file daemons.h.
Referenced by dSRealloc(), ForwardRequest(), and ProcessRequest().
#define TDCMD_SHUTDOWN 27
Definition at line 161 of file daemons.h.
Referenced by ProcessRequest().
#define TDCMD_SIMPLEMAIL_ALLOC 16
Definition at line 146 of file daemons.h.
Referenced by dAllocSimpleMail(), ForwardRequest(), and ProcessRequest().
#define TDCMD_SYNCEVENT_HIT 32
Definition at line 170 of file daemons.h.
Referenced by dSyncEventHit(), ForwardRequest(), and ProcessRequest().
Enumeration Type Documentation
enum malloc_req_t
Enumerator:
MD_NONE
MD_ACK
MD_MALLOC
MD_CALLOC
MD_REALLOC
MD_MOWN
MD_FREE
MD_FREEALL
MD_EXIT
Definition at line 232 of file daemons.h.
enum proc_busy_t
Enumerator:
PROC_IDLE
PROC_SYNC
PROC_ASYNC
Definition at line 113 of file daemons.h.
Function Documentation
int dAllocChannels (pid_t pid, int num_chan, int proc)
Wrapper for a remote call to lAllocChannels().
Definition at line 1527 of file DefaultTaskDaemon.cc.
References cmd, CMD_EXECUTE, ISSUE_SLOT, pid, RESULT_SHORT, and TDCMD_CHANNEL_ALLOC.
FifoEP* dAllocFifoEndPoint (unsigned int fifo_size, unsigned int element_size, int flags, int proc)
Wrapper for a remote call to lAllocFifoEndPoint().
Definition at line 1557 of file DefaultTaskDaemon.cc.
References addr_direct(), cmd, CMD_EXECUTE, ISSUE_SLOT, RESULT_FULL, and TDCMD_FIFO_ALLOC.
Mail* dAllocMail (unsigned int count, int proc)
Wrapper for a remote call to lAllocMail().
Definition at line 1582 of file DefaultTaskDaemon.cc.
References addr_direct(), cmd, CMD_EXECUTE, ISSUE_SLOT, RESULT_FULL, and TDCMD_MAIL_ALLOC.
SimpleMail* dAllocSimpleMail (int proc)
Wrapper for a remote call to lAllocSimpleMail().
Definition at line 1575 of file DefaultTaskDaemon.cc.
References addr_direct(), CMD_EXECUTE, ISSUE_SLOT, RESULT_FULL, and TDCMD_SIMPLEMAIL_ALLOC.
int dAssignChannel (pid_t pid, int chan_id, void * channel, int label, int proc)
Wrapper for a remote call to lAssignChannel().
Definition at line 1536 of file DefaultTaskDaemon.cc.
References cmd, CMD_EXECUTE, ISSUE_SLOT, pid, RESULT_SHORT, and TDCMD_CHANNEL_ASSIGN.
int dAtomicAdd (void * mem, int val)
An atomic add implementation.
This involves pushing the arguments to a central server, which is very expensive compared to hardware exchange support.
Parameters:
mem address to add val to
val the value to add to *mem
Returns:
the old contents of mem
Definition at line 1711 of file DefaultTaskDaemon.cc.
References ATOMIC_SERVER, cmd, CMD_EXECUTE, ISSUE_SLOT, RESULT_FULL, and TDCMD_ATOMIC_ADD.
int dAtomicCAS (void * mem, int oldval, int newval)
An atomic compare-and-swap implementation.
This involves pushing the arguments to a central server, which is very expensive compared to hardware cas support.
Parameters:
mem address to cas
oldval the old value that is expected at mem
newval the new value to put in mem when *mem==oldval
Returns:
the old contents of mem
Definition at line 1678 of file DefaultTaskDaemon.cc.
References ATOMIC_SERVER, cmd, CMD_EXECUTE, ISSUE_SLOT, RESULT_FULL, and TDCMD_ATOMIC_CAS.
int dAtomicXCHG (void * mem, int val)
An atomic exchange implementation.
This involves pushing the arguments to a central server, which is very expensive compared to hardware exchange support.
Parameters:
mem address to exchange
val the new value to put in mem
Returns:
the old contents of mem
Definition at line 1695 of file DefaultTaskDaemon.cc.
References ATOMIC_SERVER, cmd, CMD_EXECUTE, ISSUE_SLOT, RESULT_FULL, and TDCMD_ATOMIC_XCHG.
int dBootKernels (int num, int * procs)
Boots the kernel on other processors.
It does the following: other processors will get the boot signal (assuming the slaveloader is running) and we will wait for the boot notification. When you want to use the wrapper functions like CreateProcess(), all other cores must be booted using this function, in order to setup the channels correctly. Do not call this function twice.
Parameters:
num the number of processors to boot, that is the length of the procs parameter
procs an array of core IDs of processors to boot
Returns:
0 on success, EXFULL when the fifo memory is full, otherwise an errno. In case of an error, it is undecidable which processors have been booted and which have not.
Definition at line 1126 of file DefaultTaskDaemon.cc.
References dBootKernel(), DEBUGH, DEBUGL, ESUCCESS, ffree(), fmalloc(), HOOK_CORES, MailPeek(), MailRead(), OS_SOC, RegisterHook(), SetOSState, and Yield().
Referenced by BootKernel(), and DefaultMulticoreSetup().
int dCreateProcess (pid_t & pid, void *(*)(void *) main, void * arg, timems_t slicelength, unsigned int stack, int proc)
Wrapper for a remote call to lCreateProcess().
Definition at line 1396 of file DefaultTaskDaemon.cc.
References CHECK_NOT_CACHED, cmd, CMD_EXECUTE, ISSUE_SLOT, main, RESULT_PACKED, and TDCMD_PROCESS_CREATE.
void dDestroyFifoEndPoint (FifoEP * fifo, int proc)
Wrapper for a remote call to lDestroyFifoEndPoint().
Definition at line 1567 of file DefaultTaskDaemon.cc.
References addr_global(), cmd, CMD_EXECUTE_VOID, ISSUE_SLOT_ASYNC, RESULT_IGNORE, and TDCMD_FIFO_DESTROY.
void dDestroyMail (Mail * mail, int proc)
Wrapper for a remote call to lDestroyMail().
Definition at line 1590 of file DefaultTaskDaemon.cc.
References addr_global(), cmd, CMD_EXECUTE_VOID, ISSUE_SLOT_ASYNC, RESULT_IGNORE, and TDCMD_MAIL_DESTROY.
int dDestroyProcess (pid_t pid, void ** ret, int proc)
Wrapper for a remote call to lDestroyProcess().
Definition at line 1417 of file DefaultTaskDaemon.cc.
References cmd, CMD_EXECUTE, ISSUE_SLOT, pid, RESULT_BOTH, and TDCMD_PROCESS_DESTROY.
int DefaultMulticoreSetup (int cores)
Initializes a default multi-core setup.
This includes: processors 0 to cores-1, 0 is the master, having a shared heap.
Parameters:
cores the number of cores in the system, set to 0 to boot all known processors in the system
Returns:
0 on success, EREMOTE when called from another processor than 0, otherwise an errno
Definition at line 481 of file DefaultTaskDaemon.cc.
References CheckRing(), dBootKernels(), DEBUGH, ESUCCESS, GetProcID(), GetSoCCores(), and InitSHeap().
Referenced by TaskDaemon().
int dGetProcessFlags (pid_t pid, int * flags, int proc)
Wrapper for a remote call to lGetProcessFlags().
Definition at line 1468 of file DefaultTaskDaemon.cc.
References cmd, CMD_EXECUTE, ISSUE_SLOT, pid, RESULT_PACKED, and TDCMD_PROCESS_GET_FLAGS.
int dGetProcessState (pid_t pid, proc_state_t * state, bool * sighandling, int proc)
Wrapper for a remote call to lGetProcessState().
Definition at line 1486 of file DefaultTaskDaemon.cc.
References cmd, CMD_EXECUTE, HandleGPS(), ISSUE_SLOT, pid, RESULT_PACKED, ProcessState_t::state_, and TDCMD_PROCESS_GET_STATE.
int dLockAsk (void * l, int gpid)
Backend for lck_ask().
Not to be called directly.
Definition at line 1753 of file DefaultTaskDaemon.cc.
References cmd, CMD_EXECUTE, getgpid(), getgpidproc(), getlpid(), ISSUE_SLOT, RESULT_SHORT, and TDCMD_LOCK_ASK.
Referenced by lck_pass_p().
int dLockGiveup (void * l)
Backend for lck_giveup().
Not to be called directly.
Definition at line 1768 of file DefaultTaskDaemon.cc.
References cmd, CMD_EXECUTE, getgpid(), ISSUE_SLOT_ASYNC, LOCK_DAEMON_CORE, RESULT_IGNORE, and TDCMD_LOCK_GIVEUP.
Referenced by lck_destroy().
int dLockRegister (lck_my_locks_t * list)
Backend for lck_register().
Not to be called directly.
Definition at line 1725 of file DefaultTaskDaemon.cc.
References cmd, CMD_EXECUTE, getpid(), ISSUE_SLOT, RESULT_SHORT, and TDCMD_LOCK_REGISTER.
Referenced by lck_cleanup(), and lck_pass_p().
int dLockRequest (void * l)
Backend for lck_request().
Not to be called directly.
Definition at line 1739 of file DefaultTaskDaemon.cc.
References cmd, CMD_EXECUTE, getgpid(), ISSUE_SLOT, LOCK_DAEMON_CORE, RESULT_SHORT, and TDCMD_LOCK_REQUEST.
Referenced by lck_pass_p().
void do_gracefull_exit_funs ()
Function to cleanup process stuff, called by abort() and exit() (via atexit()).
Definition at line 34 of file ShutdownDaemon.cc.
References linfs_close_all().
Referenced by ProcessEntry().
void* dRemoteCall (void *(*)(void *) fun, void * arg, int proc)
Generic function to call all arbitrary functions an another core.
The function will be executed by the remote task daemon, so make sure your function does not badly influence the stack/timeslice of the task daemon.
Parameters:
fun the function to call
arg the argument to pass to fun
proc the processor to run the function at
Returns:
the result of fun(arg)
Definition at line 1655 of file DefaultTaskDaemon.cc.
References cmd, CMD_EXECUTE, ISSUE_SLOT, RESULT_FULL, and TDCMD_REMOTE_CALL.
Referenced by CFifo< T, CFifo<>::w >::CFifo(), DumpStatsDaemon(), DumpStatsNow(), ForceShutdown(), GarbageCollect(), helix_rpc(), linfs_register(), CFifo< T, r >::operator delete(), CFifo< T, CFifo<>::w >::operator new(), CFifo< T, CFifo<>::r >::operator new[](), and TraceDumpAll().
void* dSCalloc (size_t nmemb, size_t size)
Internal function to forward the scalloc() request to the appropriate core.
Not to be called directly.
Definition at line 1625 of file DefaultTaskDaemon.cc.
References cmd, CMD_EXECUTE, ISSUE_SLOT, RESULT_FULL, SMALLOC_PROC, and TDCMD_SHEAP_CALLOC.
Referenced by scalloc().
int dSendSignal (pid_t pid, int sig, union sigval * sv, int proc)
Wrapper for a remote call to lSendSignal().
In contrast to lSendSignal, the result is not waited for and is always 0.
Hence, the command is sent asynchronously and this call does not block (when a free issue slot can be obtained)
Returns:
0 when the command is delivered (does not indicate the result of the lSendSignal() call), an errno otherwise.
Definition at line 1509 of file DefaultTaskDaemon.cc.
References cmd, CMD_EXECUTE, ISSUE_SLOT_ASYNC, pid, RESULT_IGNORE, and TDCMD_PROCESS_SIGNAL.
int dSetChannelLabel (pid_t pid, int chan_id, int label, int proc)
Wrapper for a remote call to lSetChannelLabel().
Definition at line 1547 of file DefaultTaskDaemon.cc.
References cmd, CMD_EXECUTE, ISSUE_SLOT, pid, RESULT_SHORT, and TDCMD_CHANNEL_LABEL.
int dSetProcessFlags (pid_t pid, int flags, int proc)
Wrapper for a remote call to lSetProcessFlags().
Definition at line 1459 of file DefaultTaskDaemon.cc.
References cmd, CMD_EXECUTE, ISSUE_SLOT, pid, RESULT_SHORT, and TDCMD_PROCESS_SET_FLAGS.
int dSetProcessTimeslice (pid_t pid, timems_t slicelength, int proc)
Wrapper for a remote call to lSetProcessTimeslice().
Definition at line 1495 of file DefaultTaskDaemon.cc.
References cmd, CMD_EXECUTE, ISSUE_SLOT, pid, RESULT_SHORT, and TDCMD_PROCESS_SET_TIMESLICE.
void dSFree (void * ptr)
Internal function to forward the sfree() request to the appropriate core.
Not to be called directly.
Definition at line 1613 of file DefaultTaskDaemon.cc.
References cmd, CMD_EXECUTE_VOID, ISSUE_SLOT_ASYNC, RESULT_IGNORE, SMALLOC_PROC, and TDCMD_SHEAP_FREE.
Referenced by sfree().
void* dSMalloc (size_t size)
Internal function to forward the smalloc() request to the appropriate core.
Not to be called directly.
Definition at line 1601 of file DefaultTaskDaemon.cc.
References cmd, CMD_EXECUTE, ISSUE_SLOT, RESULT_FULL, SMALLOC_PROC, and TDCMD_SHEAP_ALLOC.
Referenced by smalloc().
void* dSRealloc (void * ptr, size_t size)
Internal function to forward the srealloc() request to the appropriate core.
Not to be called directly.
Definition at line 1638 of file DefaultTaskDaemon.cc.
References cmd, CMD_EXECUTE, ISSUE_SLOT, RESULT_FULL, SMALLOC_PROC, and TDCMD_SHEAP_REALLOC.
Referenced by srealloc().
int dStartProcess (pid_t pid, int proc)
Wrapper for a remote call to lStartProcess().
Definition at line 1409 of file DefaultTaskDaemon.cc.
References cmd, CMD_EXECUTE, ISSUE_SLOT, pid, RESULT_SHORT, and TDCMD_PROCESS_START.
int dSyncEventHit (pid_t pid, void * event, int proc = -1)
Definition at line 1518 of file DefaultTaskDaemon.cc.
References cmd, CMD_EXECUTE, ISSUE_SLOT_ASYNC, pid, RESULT_IGNORE, and TDCMD_SYNCEVENT_HIT.
int dWaitProcess (pid_t pid, void ** ret, int proc)
Wrapper for a remote call to lJoinProcess().
At the other core, a new process is created that does lJoinProcess().
When the target process terminates, the return value is sent back to the calling process of this function.
See also:
WaitProcessDaemon()
Definition at line 1445 of file DefaultTaskDaemon.cc.
References addr_global(), cmd, CMD_EXECUTE, HandleWPD(), InitMail, ISSUE_SLOT, lAllocMail, pid, RESULT_SHORT, and TDCMD_PROCESS_WAIT.
Referenced by WaitProcess().
int GarbageCollect ()
Cleans up all unused resources.
Actually, only all zombie processes will be removed.
Returns:
EAGAIN when there was nothing to clean, otherwise ESUCCESS
Definition at line 541 of file DefaultTaskDaemon.cc.
References dRemoteCall(), ESUCCESS, GarbageCollect(), getpid(), GetProcessStats(), GetProcID(), lGetZombie(), proc_stats_t::min_stack, and proc_stats_t::slice_used.
Referenced by DefaultTaskDaemon(), and GarbageCollect().
void InitHardware (void * arg)
Call to initialize hardware, such as network routes to essential peripherals.
This is a stub. Should be reimplemented by the application. Will be called before kernel initialization.
Parameters:
arg a copy of kernel_boot_param_t::arg, as received by main(int,char**)
Definition at line 10 of file InitHardware.cc.
Referenced by kBoot().
void IssueMallocRequest (malloc_buffer_t * b, malloc_req_t type)
Sends a request to the MallocDaemon().
For internal use only. Use normal malloc() and friends.
Parameters:
b the malloc buffer to communicate with
type the request type
Returns:
after the request has been served
Definition at line 219 of file MallocDaemon.cc.
References lSendSignal(), MALLOC_PID, MALLOC_SIGNAL, MD_ACK, MD_NONE, malloc_buffer_t::request, and Yield().
Referenced by calloc(), free(), freeAll(), mown(), omalloc(), orealloc(), and StopMallocDaemon().
void* MallocDaemon (void * arg)
Daemon to handle all processor heap operations.
Every process can have one outstanding malloc/calloc/realloc/mown/free request. The daemon will handle all requests in order of process id. When all requests are processed, the daemon Yield()s. This means that all heap requests are serviced in one complete scheduling period, assuming that the daemon finishes before the end of its timeslice. The heap will not be locked; locking is implicit by using this daemon.
The FIFO heap and shared heap are not managed by this daemon. The daemon should be started by calling StartMallocDaemon().
Parameters:
arg a pointer to a malloc_buffer_t[MAX_PROCESSES*2], cannot be null
Returns:
(void*)errno
Definition at line 107 of file MallocDaemon.cc.
References md_t::b, b, HOOK_MALLOC, md_t::m, MailWrite(), MALLOC_SIGNAL, MallocDaemonHandler(), pause(), sigaction::sa_flags, sigaction::sa_handler, sigaction::sa_mask, SA_NODEFER, set_no_gracefull_exit(), sigaction(), sigemptyset(), thread_local, and UnregisterHook().
Referenced by StartMallocDaemon().
void set_no_gracefull_exit ()
Prevents the calling process to be killed by the ShutdownDaemon on reboot.
SIGTERM will be masked.
Only critical daemons that do not require system-wide cleanup functions should call this.
Definition at line 46 of file ShutdownDaemon.cc.
References DEBUG, MaskSignal(), SIG_BLOCK, sigaddset(), sigemptyset(), and SIGTERM.
Referenced by MallocDaemon(), ShutdownDaemon(), TimerDaemon(), and TraceDump().
int timer_repeat (void(*)(int, siginfo_t *, void *) handler, void * arg, long interval_sec, long interval_nsec = 0)
Definition at line 195 of file TimerDaemon.cc.
References CLOCK_MONOTONIC, sigaction::sa_flags, sigaction::sa_mask, sigaction::sa_sigaction, SA_SIGINFO, sigaction(), SIGALRM, sigemptyset(), sigevent::sigev_notify, SIGEV_SIGNAL, sigevent::sigev_signo, sigevent::sigev_value, sigval::sival_ptr, timer_create(), and timer_settime().
Referenced by DumpStatsDaemon(), and ShutdownDaemon().