Starburst: daemons/DefaultTaskDaemon.cc File Reference
daemons/DefaultTaskDaemon.cc File Reference
Daemons
Daemon for communication and synchronization in the SoC.
#include <sys/syscall.h>
#include <daemons.h>
#include <stdio.h>
#include <errno.h>
#include <sys/helix_config.h>
#include <sys/types.h>
#include <unistd.h>
Data Structures
union ProcessState_t
struct tds_t
Defines
#define TASKDAEMON_DEBUG_HIPRI
#define DEBUGH(str, a...) printf("TaskDaemon %d: " str "\n",GetProcID(),##a)
#define DEBUGL(s...)
#define TASKDAEMON_STATS
#define SetOSState(state) *(os_state_t*)&os_state=state
#define PACK_RES(mb, res_errno, res) MailWrite(mb,((res_errno)==0?(unsigned int)(res):-(res_errno)))
#define UNPACK_RES(mb, res) (((res)=(typeof(res))MailRead(mb)),(((unsigned int)(res))&0x40000000?-(int)((unsigned int)(res)|MAIL_GOTMAIL_FLAG):0))
#define FIND_MAILBOX(a, pid) ((Mail*)&((int*)a)[pid*2])
#define tdr ((tdcmd_remote_t*)FIFO_MEM)
#define tdrr(p) ((tdcmd_remote_t*)MAKE_NOC_FIFOMEM_PTR(0,p))
#define tdrc(p) (&(tdrr(p)->cmd[GetProcID()]))
#define TDS ((tds_t*)thread_local[0])
#define sheap_last_addr(valid_mask)
#define sheap_set_end(valid_mask) sheap_end=(void*)(sheap_last_addr(valid_mask)+1)
#define TDCMD_HEAD
#define ISSUE_SLOT(errret)
#define ISSUE_SLOT_ASYNC(errret)
#define RESULT_PACKED(packret)
#define RESULT_SHORT()
#define RESULT_FULL(field)
#define RESULT_BOTH(field, arg)
#define RESULT_IGNORE()
#define CMD_EXECUTE(c, rettype, pp, a...)
#define CMD_EXECUTE_VOID(c)
#define NUM_PROCESSORS_ONLINE sysconf(_SC_NPROCESSORS_ONLN)
#define ATOMIC_SERVER(p) (GetOSState()>=OS_SOC?((((int)(p))>>2)%NUM_PROCESSORS_ONLINE):-1)
Enumerations
enum tds_type_t { TDS_LOCAL, TDS_FORWARD, TDS_REMOTE }
enum res_type_t {
RES_PACKED, RES_SHORT, RES_FULL, RES_BOTH,
RES_IGNORE
}
Functions
void * _boot_kernel_slave (kernel_boot_param_t param)
static int StatsInit ()
Initialization for message statistics.
static void StatsCount (int cmd, tds_type_t type) __attribute__((always_inline))
Count a single event of a specific command.
static void StatsDump () __attribute__((unused))
Print statistics for this task daemon.
int main (int argc, char **argv)
Entry point of your application.
void __init ()
void __fini ()
void * mainProc (void *arg)
Process entry point of main().
void * InitTaskDaemon (void *kernel_param)
Initializes the task daemon.
static int InitSHeap ()
int CheckRing ()
Checks if the communicating ring is working by writing to the local fifo-memory via the ring.
int DefaultMulticoreSetup (int cores)
Initializes a default multi-core setup.
int GarbageCollect ()
Cleans up all unused resources.
static void * WaitProcessDaemon (void *arg)
Simple process that joins another process that is running on this core.
static int ProcessRequest (tdcmd_t *cmd, int cmd_type)
Processes a request at this core.
static int ForwardRequest (tdcmd_t *cmd)
Forward a command to another core.
static int FinishForwardedRequest (volatile tdcmd_t *cmd)
Checks whether the command has been executed by the core it has been sent to.
void * DefaultTaskDaemon (void *arg)
The default implementation of the task daemon.
void dBootKernel (int proc, SimpleMail *ret, int cores, void *arg)
Boot other processor.
int dBootKernels (int num, int *procs)
Boots the kernel on other processors.
static volatile tdcmd_t * ReserveRemoteSlot (tdcmd_local_t *tdl, int proc)
Tries to reserve a slot in a remote command list, depending on other (parallel) commands in transit.
static int GetIssueSlot (pid_t &me, tdcmd_local_t *&tdl, volatile tdcmd_t *&cmd, int proc, bool &async)
Finds the slot to put a new command in, either to local processes or remote.
static int WaitForResult ()
Yield (and suspend when possible) to wait for a remote command to be finished.
int dCreateProcess (pid_t &pid, void *(*main)(void *), void *arg, timems_t slicelength, unsigned int stack, int proc)
Wrapper for a remote call to lCreateProcess().
int dStartProcess (pid_t pid, int proc)
Wrapper for a remote call to lStartProcess().
int dDestroyProcess (pid_t pid, void **ret, int proc)
Wrapper for a remote call to lDestroyProcess().
static int HandleWPD (int cmdres, Mail *w, void **ret)
int dWaitProcess (pid_t pid, void **ret, int proc)
Wrapper for a remote call to lJoinProcess().
int dSetProcessFlags (pid_t pid, int flags, int proc)
Wrapper for a remote call to lSetProcessFlags().
int dGetProcessFlags (pid_t pid, int *flags, int proc)
Wrapper for a remote call to lGetProcessFlags().
static int HandleGPS (int cmdres, proc_state_t *state, bool *sighandling, ProcessState_t *pack)
int dGetProcessState (pid_t pid, proc_state_t *state, bool *sighandling, int proc)
Wrapper for a remote call to lGetProcessState().
int dSetProcessTimeslice (pid_t pid, timems_t slicelength, int proc)
Wrapper for a remote call to lSetProcessTimeslice().
int dSendSignal (pid_t pid, int sig, union sigval *sv, int proc)
Wrapper for a remote call to lSendSignal().
int dSyncEventHit (pid_t pid, void *event, int proc)
int dAllocChannels (pid_t pid, int num_chan, int proc)
Wrapper for a remote call to lAllocChannels().
int dAssignChannel (pid_t pid, int chan_id, void *channel, int label, int proc)
Wrapper for a remote call to lAssignChannel().
int dSetChannelLabel (pid_t pid, int chan_id, int label, int proc)
Wrapper for a remote call to lSetChannelLabel().
FifoEP * dAllocFifoEndPoint (unsigned int fifo_size, unsigned int element_size, int flags, int proc)
Wrapper for a remote call to lAllocFifoEndPoint().
void dDestroyFifoEndPoint (FifoEP *fifo, int proc)
Wrapper for a remote call to lDestroyFifoEndPoint().
SimpleMail * dAllocSimpleMail (int proc)
Wrapper for a remote call to lAllocSimpleMail().
Mail * dAllocMail (unsigned int count, int proc)
Wrapper for a remote call to lAllocMail().
void dDestroyMail (Mail *mail, int proc)
Wrapper for a remote call to lDestroyMail().
void * dSMalloc (size_t size)
Internal function to forward the smalloc() request to the appropriate core.
void dSFree (void *ptr)
Internal function to forward the sfree() request to the appropriate core.
void * dSCalloc (size_t nmemb, size_t size)
Internal function to forward the scalloc() request to the appropriate core.
void * dSRealloc (void *ptr, size_t size)
Internal function to forward the srealloc() request to the appropriate core.
void * dRemoteCall (void *(*fun)(void *), void *arg, int proc)
Generic function to call all arbitrary functions an another core.
int dAtomicCAS (void *mem, int oldval, int newval)
An atomic compare-and-swap implementation.
int dAtomicXCHG (void *mem, int val)
An atomic exchange implementation.
int dAtomicAdd (void *mem, int val)
An atomic add implementation.
int dLockRegister (lck_my_locks_t *list)
Backend for lck_register().
int dLockRequest (void *l)
Backend for lck_request().
int dLockAsk (void *l, int gpid)
Backend for lck_ask().
int dLockGiveup (void *l)
Backend for lck_giveup().
Variables
int(* __boot_funs [])(void)
void *const _heap_end
void *const _ddrbase
static const char * tdcmd_name [TDCMD_COUNT]
Names corresponding to command IDs.
int _argc = 1
char _args_buf [MAIN_MAX_ARGC *8] = "skat"
char * _argv [MAIN_MAX_ARGC+1] = {_args_buf}
All arguments to main().
Detailed Description
Daemon for communication and synchronization in the SoC.
The task daemon is the essential daemon of the OS; this is the first process running and is responsible for process management and synchronization for the running kernel and with other kernels in the system.
There is one very special command for the task daemon: the shutdown command. There is no call available to invoke this from a normal process--it should only be used for debugging. The call is (possibly) destructive for the whole system. No feedback is given when the core has been reset. It can take up to multiple replenishment intervals. All kernels wait for at least one second between terminating all processes and rebooting. Make sure that all cores that have been booted receive the shutdown command within that second to prevent race conditions.
Quick and dirty method to shutdown core p:
 ((tdcmd_remote_t*)MAKE_NOC_FIFOMEM_PTR(0,p))->cmd[p].cmd=TDCMD_SHUTDOWN;  // (combined with next line)
 ((tdcmd_remote_t*)MAKE_NOC_FIFOMEM_PTR(0,p))->cmd[p].proc=p;              // (0x60000000 & (p<<20)) + (p*6+1)*4 = 0x1bff0000
 ((tdcmd_remote_t*)MAKE_NOC_FIFOMEM_PTR(0,p))->have_cmd=1;                 // (0x60000000 & (p<<20)) = 1
Definition in file DefaultTaskDaemon.cc.
Define Documentation
#define ATOMIC_SERVER (p) (GetOSState()>=OS_SOC?((((int)(p))>>2)%NUM_PROCESSORS_ONLINE):-1)
Definition at line 1667 of file DefaultTaskDaemon.cc.
Referenced by dAtomicAdd(), dAtomicCAS(), and dAtomicXCHG().
#define CMD_EXECUTE (c, rettype, pp, a...)
Definition at line 1236 of file DefaultTaskDaemon.cc.
Referenced by dAllocChannels(), dAllocFifoEndPoint(), dAllocMail(), dAllocSimpleMail(), dAssignChannel(), dAtomicAdd(), dAtomicCAS(), dAtomicXCHG(), dCreateProcess(), dDestroyProcess(), dGetProcessFlags(), dGetProcessState(), dLockAsk(), dLockGiveup(), dLockRegister(), dLockRequest(), dRemoteCall(), dSCalloc(), dSendSignal(), dSetChannelLabel(), dSetProcessFlags(), dSetProcessTimeslice(), dSMalloc(), dSRealloc(), dStartProcess(), dSyncEventHit(), and dWaitProcess().
#define CMD_EXECUTE_VOID (c)
Value:
barrier();                                  \
    cmd->cmd=c;                                 \
    barrier();                                  \
    if(async){                                  \
        ASSERT(res_type==RES_IGNORE,"Cannot wait for async result"); \
        tdrr(proc)->have_cmd=1;                 \
    }else{                                      \
        tdl->have_cmd=1;                        \
        tdr->have_cmd_local=1;                  \
    }                                           \
    barrier();                                  \
    switch(res_type){                           \
    case RES_IGNORE:                            \
        break;                                  \
    default:                                    \
        ASSERT(false,"Invalid result type");    \
    }
Definition at line 1273 of file DefaultTaskDaemon.cc.
Referenced by dDestroyFifoEndPoint(), dDestroyMail(), and dSFree().
#define DEBUGH (str, a...) printf("TaskDaemon %d: " str "\n",GetProcID(),##a)
Definition at line 42 of file DefaultTaskDaemon.cc.
Referenced by CheckRing(), dBootKernel(), dBootKernels(), DefaultMulticoreSetup(), DefaultTaskDaemon(), InitSHeap(), InitTaskDaemon(), mainProc(), ProcessRequest(), and StatsInit().
#define DEBUGL (s...)
Definition at line 50 of file DefaultTaskDaemon.cc.
Referenced by dBootKernels(), DefaultTaskDaemon(), FinishForwardedRequest(), ForwardRequest(), InitTaskDaemon(), ProcessRequest(), and WaitProcessDaemon().
#define FIND_MAILBOX (a, pid) ((Mail*)&((int*)a)[pid*2])
Definition at line 91 of file DefaultTaskDaemon.cc.
#define ISSUE_SLOT (errret)
Value:
TDCMD_HEAD;                                 \
    bool async=false;                           \
    if((res=GetIssueSlot(me,tdl,cmd,proc,async)))return errret
Definition at line 1194 of file DefaultTaskDaemon.cc.
Referenced by dAllocChannels(), dAllocFifoEndPoint(), dAllocMail(), dAllocSimpleMail(), dAssignChannel(), dAtomicAdd(), dAtomicCAS(), dAtomicXCHG(), dCreateProcess(), dDestroyProcess(), dGetProcessFlags(), dGetProcessState(), dLockAsk(), dLockRegister(), dLockRequest(), dRemoteCall(), dSCalloc(), dSetChannelLabel(), dSetProcessFlags(), dSetProcessTimeslice(), dSMalloc(), dSRealloc(), dStartProcess(), and dWaitProcess().
#define ISSUE_SLOT_ASYNC (errret)
Value:
TDCMD_HEAD;                                 \
    bool async=true;                            \
    if((res=GetIssueSlot(me,tdl,cmd,proc,async)))return errret
Definition at line 1199 of file DefaultTaskDaemon.cc.
Referenced by dDestroyFifoEndPoint(), dDestroyMail(), dLockGiveup(), dSendSignal(), dSFree(), and dSyncEventHit().
#define NUM_PROCESSORS_ONLINE sysconf(_SC_NPROCESSORS_ONLN)
Definition at line 1663 of file DefaultTaskDaemon.cc.
#define PACK_RES (mb, res_errno, res) MailWrite(mb,((res_errno)==0?(unsigned int)(res):-(res_errno)))
Definition at line 86 of file DefaultTaskDaemon.cc.
Referenced by ProcessRequest().
#define RESULT_BOTH (field, arg)
Value:
typeof(arg) packret_=arg;                   \
    const res_type_t res_type=RES_BOTH;         \
    InitMail(&mp);                              \
    cmd->res=&mp;                               \
    mf=FIND_MAILBOX(tdl->m,me);                 \
    InitMail(mf);                               \
    cmd->field=(void*)addr_global((void*)mf)
Definition at line 1224 of file DefaultTaskDaemon.cc.
Referenced by dDestroyProcess().
#define RESULT_FULL (field)
Value:
void** packret_ __attribute__((unused))=NULL;   \
    const res_type_t res_type=RES_FULL;         \
    InitMail(&mp);                              \
    cmd->res=&mp;                               \
    mf=FIND_MAILBOX(tdl->m,me);                 \
    InitMail(mf);                               \
    cmd->field=(void*)addr_global((void*)mf)
Definition at line 1216 of file DefaultTaskDaemon.cc.
Referenced by dAllocFifoEndPoint(), dAllocMail(), dAllocSimpleMail(), dAtomicAdd(), dAtomicCAS(), dAtomicXCHG(), dRemoteCall(), dSCalloc(), dSMalloc(), and dSRealloc().
#define RESULT_IGNORE ()
Value:
void** packret_ __attribute__((unused))=NULL;   \
    const res_type_t res_type=RES_IGNORE
Definition at line 1232 of file DefaultTaskDaemon.cc.
Referenced by dDestroyFifoEndPoint(), dDestroyMail(), dLockGiveup(), dSendSignal(), dSFree(), and dSyncEventHit().
#define RESULT_PACKED (packret)
Value:
typeof(packret) packret_=packret;           \
    const res_type_t res_type=RES_PACKED;       \
    InitMail(&mp);                              \
    cmd->res=&mp
Definition at line 1206 of file DefaultTaskDaemon.cc.
Referenced by dCreateProcess(), dGetProcessFlags(), and dGetProcessState().
#define RESULT_SHORT ()
Value:
void** packret_ __attribute__((unused))=NULL;   \
    const res_type_t res_type=RES_SHORT;        \
    InitMail(&mp);                              \
    cmd->res=&mp
Definition at line 1211 of file DefaultTaskDaemon.cc.
Referenced by dAllocChannels(), dAssignChannel(), dLockAsk(), dLockRegister(), dLockRequest(), dSetChannelLabel(), dSetProcessFlags(), dSetProcessTimeslice(), dStartProcess(), and dWaitProcess().
#define SetOSState (state) *(os_state_t*)&os_state=state
Definition at line 84 of file DefaultTaskDaemon.cc.
Referenced by dBootKernels(), InitTaskDaemon(), and ProcessRequest().
#define sheap_last_addr (valid_mask)
Value:
((typeof(marker) volatile *)                                                            \
            ((((uintptr_t)&_ddrbase&~((uintptr_t)(valid_mask)-1)) |                             \
            (((uintptr_t)&_heap_end-(uintptr_t)sizeof(marker))&((uintptr_t)(valid_mask)-1))) &  \
            (uintptr_t)~(sizeof(marker)-1)))
Referenced by InitSHeap().
#define sheap_set_end (valid_mask) sheap_end=(void*)(sheap_last_addr(valid_mask)+1)
Referenced by InitSHeap().
#define TASKDAEMON_DEBUG_HIPRI
Definition at line 36 of file DefaultTaskDaemon.cc.
#define TASKDAEMON_STATS
Definition at line 54 of file DefaultTaskDaemon.cc.
#define TDCMD_HEAD
Value:
tdcmd_local_t* tdl=NULL;    \
    volatile tdcmd_t* cmd=NULL; \
    pid_t me=-1;                \
    int res=0;                  \
    SimpleMail mp __attribute__((unused));  \
    Mail* mf __attribute__((unused))
Definition at line 1186 of file DefaultTaskDaemon.cc.
#define tdr ((tdcmd_remote_t*)FIFO_MEM)
Definition at line 94 of file DefaultTaskDaemon.cc.
Referenced by DefaultTaskDaemon(), FinishForwardedRequest(), ForwardRequest(), InitTaskDaemon(), and ReserveRemoteSlot().
#define tdrc (p) (&(tdrr(p)->cmd[GetProcID()]))
Definition at line 98 of file DefaultTaskDaemon.cc.
Referenced by ForwardRequest(), and ReserveRemoteSlot().
#define tdrr (p) ((tdcmd_remote_t*)MAKE_NOC_FIFOMEM_PTR(0,p))
Definition at line 96 of file DefaultTaskDaemon.cc.
Referenced by ForwardRequest().
#define TDS ((tds_t*)thread_local[0])
Definition at line 131 of file DefaultTaskDaemon.cc.
Referenced by StatsCount(), and StatsDump().
#define UNPACK_RES (mb, res) (((res)=(typeof(res))MailRead(mb)),(((unsigned int)(res))&0x40000000?-(int)((unsigned int)(res)|MAIL_GOTMAIL_FLAG):0))
Definition at line 88 of file DefaultTaskDaemon.cc.
Enumeration Type Documentation
enum res_type_t
Enumerator:
RES_PACKED
RES_SHORT
RES_FULL
RES_BOTH
RES_IGNORE
Definition at line 1204 of file DefaultTaskDaemon.cc.
enum tds_type_t
Enumerator:
TDS_LOCAL
TDS_FORWARD
TDS_REMOTE
Definition at line 133 of file DefaultTaskDaemon.cc.
Function Documentation
void __fini ()
Referenced by mainProc().
void __init ()
Referenced by mainProc().
void* _boot_kernel_slave (kernel_boot_param_t param)
Referenced by dBootKernel().
int CheckRing ()
Checks if the communicating ring is working by writing to the local fifo-memory via the ring.
Returns:
0 on succes, otherwise an errno
Definition at line 458 of file DefaultTaskDaemon.cc.
References DEBUGH, ESUCCESS, GetProcID(), MAKE_LOCAL_FIFOMEM_PTR, and MAKE_NOC_FIFOMEM_PTR.
Referenced by DefaultMulticoreSetup().
int dAllocChannels (pid_t pid, int num_chan, int proc)
Wrapper for a remote call to lAllocChannels().
Definition at line 1527 of file DefaultTaskDaemon.cc.
References cmd, CMD_EXECUTE, ISSUE_SLOT, pid, RESULT_SHORT, and TDCMD_CHANNEL_ALLOC.
FifoEP* dAllocFifoEndPoint (unsigned int fifo_size, unsigned int element_size, int flags, int proc)
Wrapper for a remote call to lAllocFifoEndPoint().
Definition at line 1557 of file DefaultTaskDaemon.cc.
References addr_direct(), cmd, CMD_EXECUTE, ISSUE_SLOT, RESULT_FULL, and TDCMD_FIFO_ALLOC.
Mail* dAllocMail (unsigned int count, int proc)
Wrapper for a remote call to lAllocMail().
Definition at line 1582 of file DefaultTaskDaemon.cc.
References addr_direct(), cmd, CMD_EXECUTE, ISSUE_SLOT, RESULT_FULL, and TDCMD_MAIL_ALLOC.
SimpleMail* dAllocSimpleMail (int proc)
Wrapper for a remote call to lAllocSimpleMail().
Definition at line 1575 of file DefaultTaskDaemon.cc.
References addr_direct(), CMD_EXECUTE, ISSUE_SLOT, RESULT_FULL, and TDCMD_SIMPLEMAIL_ALLOC.
int dAssignChannel (pid_t pid, int chan_id, void * channel, int label, int proc)
Wrapper for a remote call to lAssignChannel().
Definition at line 1536 of file DefaultTaskDaemon.cc.
References cmd, CMD_EXECUTE, ISSUE_SLOT, pid, RESULT_SHORT, and TDCMD_CHANNEL_ASSIGN.
int dAtomicAdd (void * mem, int val)
An atomic add implementation.
This involves pushing the arguments to a central server, which is very expensive compared to hardware exchange support.
Parameters:
mem address to add val to
val the value to add to *mem
Returns:
the old contents of mem
Definition at line 1711 of file DefaultTaskDaemon.cc.
References ATOMIC_SERVER, cmd, CMD_EXECUTE, ISSUE_SLOT, RESULT_FULL, and TDCMD_ATOMIC_ADD.
int dAtomicCAS (void * mem, int oldval, int newval)
An atomic compare-and-swap implementation.
This involves pushing the arguments to a central server, which is very expensive compared to hardware cas support.
Parameters:
mem address to cas
oldval the old value that is expected at mem
newval the new value to put in mem when *mem==oldval
Returns:
the old contents of mem
Definition at line 1678 of file DefaultTaskDaemon.cc.
References ATOMIC_SERVER, cmd, CMD_EXECUTE, ISSUE_SLOT, RESULT_FULL, and TDCMD_ATOMIC_CAS.
int dAtomicXCHG (void * mem, int val)
An atomic exchange implementation.
This involves pushing the arguments to a central server, which is very expensive compared to hardware exchange support.
Parameters:
mem address to exchange
val the new value to put in mem
Returns:
the old contents of mem
Definition at line 1695 of file DefaultTaskDaemon.cc.
References ATOMIC_SERVER, cmd, CMD_EXECUTE, ISSUE_SLOT, RESULT_FULL, and TDCMD_ATOMIC_XCHG.
void dBootKernel (int proc, SimpleMail * ret, int cores, void * arg)
Boot other processor.
The call is not forwarded to the task daemon but executed directly instead.
Parameters:
proc core id to boot
ret the mailbox to receive a notification after booting
cores the number of running cores in the SoC, communicated to the kernel that is booted
arg argument to pass to the kernel
Definition at line 1090 of file DefaultTaskDaemon.cc.
References _boot_kernel_slave(), addr_global(), addr_local(), kernel_boot_param_t::arg, kernel_boot_param_t::cores, DEBUGH, InitMail, MailWrite(), MAKE_NOC_FIFOMEM_PTR, and kernel_boot_param_t::notify_booted.
Referenced by dBootKernels().
int dBootKernels (int num, int * procs)
Boots the kernel on other processors.
It does the following: other processors will get the boot signal (assuming the slaveloader is running) and we will wait for the boot notification. When you want to use the wrapper functions like CreateProcess(), all other cores must be booted using this function, in order to setup the channels correctly. Do not call this function twice.
Parameters:
num the number of processors to boot, that is the length of the procs parameter
procs an array of core IDs of processors to boot
Returns:
0 on success, EXFULL when the fifo memory is full, otherwise an errno. In case of an error, it is undecidable which processors have been booted and which have not.
Definition at line 1126 of file DefaultTaskDaemon.cc.
References dBootKernel(), DEBUGH, DEBUGL, ESUCCESS, ffree(), fmalloc(), HOOK_CORES, MailPeek(), MailRead(), OS_SOC, RegisterHook(), SetOSState, and Yield().
Referenced by BootKernel(), and DefaultMulticoreSetup().
int dCreateProcess (pid_t & pid, void *(*)(void *) main, void * arg, timems_t slicelength, unsigned int stack, int proc)
Wrapper for a remote call to lCreateProcess().
Definition at line 1396 of file DefaultTaskDaemon.cc.
References CHECK_NOT_CACHED, cmd, CMD_EXECUTE, ISSUE_SLOT, main, RESULT_PACKED, and TDCMD_PROCESS_CREATE.
void dDestroyFifoEndPoint (FifoEP * fifo, int proc)
Wrapper for a remote call to lDestroyFifoEndPoint().
Definition at line 1567 of file DefaultTaskDaemon.cc.
References addr_global(), cmd, CMD_EXECUTE_VOID, ISSUE_SLOT_ASYNC, RESULT_IGNORE, and TDCMD_FIFO_DESTROY.
void dDestroyMail (Mail * mail, int proc)
Wrapper for a remote call to lDestroyMail().
Definition at line 1590 of file DefaultTaskDaemon.cc.
References addr_global(), cmd, CMD_EXECUTE_VOID, ISSUE_SLOT_ASYNC, RESULT_IGNORE, and TDCMD_MAIL_DESTROY.
int dDestroyProcess (pid_t pid, void ** ret, int proc)
Wrapper for a remote call to lDestroyProcess().
Definition at line 1417 of file DefaultTaskDaemon.cc.
References cmd, CMD_EXECUTE, ISSUE_SLOT, pid, RESULT_BOTH, and TDCMD_PROCESS_DESTROY.
int DefaultMulticoreSetup (int cores)
Initializes a default multi-core setup.
This includes: processors 0 to cores-1, 0 is the master, having a shared heap.
Parameters:
cores the number of cores in the system, set to 0 to boot all known processors in the system
Returns:
0 on success, EREMOTE when called from another processor than 0, otherwise an errno
Definition at line 481 of file DefaultTaskDaemon.cc.
References CheckRing(), dBootKernels(), DEBUGH, ESUCCESS, GetProcID(), GetSoCCores(), and InitSHeap().
Referenced by TaskDaemon().
int dGetProcessFlags (pid_t pid, int * flags, int proc)
Wrapper for a remote call to lGetProcessFlags().
Definition at line 1468 of file DefaultTaskDaemon.cc.
References cmd, CMD_EXECUTE, ISSUE_SLOT, pid, RESULT_PACKED, and TDCMD_PROCESS_GET_FLAGS.
int dGetProcessState (pid_t pid, proc_state_t * state, bool * sighandling, int proc)
Wrapper for a remote call to lGetProcessState().
Definition at line 1486 of file DefaultTaskDaemon.cc.
References cmd, CMD_EXECUTE, HandleGPS(), ISSUE_SLOT, pid, RESULT_PACKED, ProcessState_t::state_, and TDCMD_PROCESS_GET_STATE.
int dLockAsk (void * l, int gpid)
Backend for lck_ask().
Not to be called directly.
Definition at line 1753 of file DefaultTaskDaemon.cc.
References cmd, CMD_EXECUTE, getgpid(), getgpidproc(), getlpid(), ISSUE_SLOT, RESULT_SHORT, and TDCMD_LOCK_ASK.
Referenced by lck_pass_p().
int dLockGiveup (void * l)
Backend for lck_giveup().
Not to be called directly.
Definition at line 1768 of file DefaultTaskDaemon.cc.
References cmd, CMD_EXECUTE, getgpid(), ISSUE_SLOT_ASYNC, LOCK_DAEMON_CORE, RESULT_IGNORE, and TDCMD_LOCK_GIVEUP.
Referenced by lck_destroy().
int dLockRegister (lck_my_locks_t * list)
Backend for lck_register().
Not to be called directly.
Definition at line 1725 of file DefaultTaskDaemon.cc.
References cmd, CMD_EXECUTE, getpid(), ISSUE_SLOT, RESULT_SHORT, and TDCMD_LOCK_REGISTER.
Referenced by lck_cleanup(), and lck_pass_p().
int dLockRequest (void * l)
Backend for lck_request().
Not to be called directly.
Definition at line 1739 of file DefaultTaskDaemon.cc.
References cmd, CMD_EXECUTE, getgpid(), ISSUE_SLOT, LOCK_DAEMON_CORE, RESULT_SHORT, and TDCMD_LOCK_REQUEST.
Referenced by lck_pass_p().
void* dRemoteCall (void *(*)(void *) fun, void * arg, int proc)
Generic function to call all arbitrary functions an another core.
The function will be executed by the remote task daemon, so make sure your function does not badly influence the stack/timeslice of the task daemon.
Parameters:
fun the function to call
arg the argument to pass to fun
proc the processor to run the function at
Returns:
the result of fun(arg)
Definition at line 1655 of file DefaultTaskDaemon.cc.
References cmd, CMD_EXECUTE, ISSUE_SLOT, RESULT_FULL, and TDCMD_REMOTE_CALL.
Referenced by CFifo< T, CFifo<>::w >::CFifo(), DumpStatsDaemon(), DumpStatsNow(), ForceShutdown(), GarbageCollect(), helix_rpc(), linfs_register(), CFifo< T, r >::operator delete(), CFifo< T, CFifo<>::w >::operator new(), CFifo< T, CFifo<>::r >::operator new[](), and TraceDumpAll().
void* dSCalloc (size_t nmemb, size_t size)
Internal function to forward the scalloc() request to the appropriate core.
Not to be called directly.
Definition at line 1625 of file DefaultTaskDaemon.cc.
References cmd, CMD_EXECUTE, ISSUE_SLOT, RESULT_FULL, SMALLOC_PROC, and TDCMD_SHEAP_CALLOC.
Referenced by scalloc().
int dSendSignal (pid_t pid, int sig, union sigval * sv, int proc)
Wrapper for a remote call to lSendSignal().
In contrast to lSendSignal, the result is not waited for and is always 0.
Hence, the command is sent asynchronously and this call does not block (when a free issue slot can be obtained)
Returns:
0 when the command is delivered (does not indicate the result of the lSendSignal() call), an errno otherwise.
Definition at line 1509 of file DefaultTaskDaemon.cc.
References cmd, CMD_EXECUTE, ISSUE_SLOT_ASYNC, pid, RESULT_IGNORE, and TDCMD_PROCESS_SIGNAL.
int dSetChannelLabel (pid_t pid, int chan_id, int label, int proc)
Wrapper for a remote call to lSetChannelLabel().
Definition at line 1547 of file DefaultTaskDaemon.cc.
References cmd, CMD_EXECUTE, ISSUE_SLOT, pid, RESULT_SHORT, and TDCMD_CHANNEL_LABEL.
int dSetProcessFlags (pid_t pid, int flags, int proc)
Wrapper for a remote call to lSetProcessFlags().
Definition at line 1459 of file DefaultTaskDaemon.cc.
References cmd, CMD_EXECUTE, ISSUE_SLOT, pid, RESULT_SHORT, and TDCMD_PROCESS_SET_FLAGS.
int dSetProcessTimeslice (pid_t pid, timems_t slicelength, int proc)
Wrapper for a remote call to lSetProcessTimeslice().
Definition at line 1495 of file DefaultTaskDaemon.cc.
References cmd, CMD_EXECUTE, ISSUE_SLOT, pid, RESULT_SHORT, and TDCMD_PROCESS_SET_TIMESLICE.
void dSFree (void * ptr)
Internal function to forward the sfree() request to the appropriate core.
Not to be called directly.
Definition at line 1613 of file DefaultTaskDaemon.cc.
References cmd, CMD_EXECUTE_VOID, ISSUE_SLOT_ASYNC, RESULT_IGNORE, SMALLOC_PROC, and TDCMD_SHEAP_FREE.
Referenced by sfree().
void* dSMalloc (size_t size)
Internal function to forward the smalloc() request to the appropriate core.
Not to be called directly.
Definition at line 1601 of file DefaultTaskDaemon.cc.
References cmd, CMD_EXECUTE, ISSUE_SLOT, RESULT_FULL, SMALLOC_PROC, and TDCMD_SHEAP_ALLOC.
Referenced by smalloc().
void* dSRealloc (void * ptr, size_t size)
Internal function to forward the srealloc() request to the appropriate core.
Not to be called directly.
Definition at line 1638 of file DefaultTaskDaemon.cc.
References cmd, CMD_EXECUTE, ISSUE_SLOT, RESULT_FULL, SMALLOC_PROC, and TDCMD_SHEAP_REALLOC.
Referenced by srealloc().
int dStartProcess (pid_t pid, int proc)
Wrapper for a remote call to lStartProcess().
Definition at line 1409 of file DefaultTaskDaemon.cc.
References cmd, CMD_EXECUTE, ISSUE_SLOT, pid, RESULT_SHORT, and TDCMD_PROCESS_START.
int dSyncEventHit (pid_t pid, void * event, int proc)
Definition at line 1518 of file DefaultTaskDaemon.cc.
References cmd, CMD_EXECUTE, ISSUE_SLOT_ASYNC, pid, RESULT_IGNORE, and TDCMD_SYNCEVENT_HIT.
int dWaitProcess (pid_t pid, void ** ret, int proc)
Wrapper for a remote call to lJoinProcess().
At the other core, a new process is created that does lJoinProcess().
When the target process terminates, the return value is sent back to the calling process of this function.
See also:
WaitProcessDaemon()
Definition at line 1445 of file DefaultTaskDaemon.cc.
References addr_global(), cmd, CMD_EXECUTE, HandleWPD(), InitMail, ISSUE_SLOT, lAllocMail, pid, RESULT_SHORT, and TDCMD_PROCESS_WAIT.
Referenced by WaitProcess().
static int FinishForwardedRequest (volatile tdcmd_t * cmd) [static]
Checks whether the command has been executed by the core it has been sent to.
Parameters:
cmd the same command as supplied to ForwardRequest()
Returns:
0 when the other core (cmd->proc) has executed the command, EAGAIN otherwise.
Definition at line 873 of file DefaultTaskDaemon.cc.
References ASSERT, tdcmd_t::cmd, DEBUGL, ESUCCESS, MailPeek(), MailRead(), MailWrite(), tdcmd_t::proc, tdcmd_t::res, and tdr.
Referenced by DefaultTaskDaemon().
static int ForwardRequest (tdcmd_t * cmd) [static]
Forward a command to another core.
Only writes the command, does not wait for response.
Parameters:
cmd the command to forward to core cmd->proc
Returns:
0 on success, otherwise an errno
See also:
FinishForwardedRequest()
Definition at line 801 of file DefaultTaskDaemon.cc.
References addr_global(), ASSERT, tdcmd_t::cmd, DEBUGL, ESUCCESS, GetProcID(), InitMail, tdcmd_t::proc, TDCMD_ATOMIC_ADD, TDCMD_ATOMIC_CAS, TDCMD_ATOMIC_XCHG, TDCMD_CHANNEL_ALLOC, TDCMD_CHANNEL_ASSIGN, TDCMD_CHANNEL_LABEL, TDCMD_FIFO_ALLOC, TDCMD_FIFO_DESTROY, TDCMD_LOCK_ASK, TDCMD_LOCK_GIVEUP, TDCMD_LOCK_REGISTER, TDCMD_LOCK_REQUEST, TDCMD_MAIL_ALLOC, TDCMD_MAIL_DESTROY, TDCMD_PROCESS_CREATE, TDCMD_PROCESS_DESTROY, TDCMD_PROCESS_GET_FLAGS, TDCMD_PROCESS_GET_STATE, TDCMD_PROCESS_SET_FLAGS, TDCMD_PROCESS_SET_TIMESLICE, TDCMD_PROCESS_SIGNAL, TDCMD_PROCESS_START, TDCMD_PROCESS_WAIT, TDCMD_REMOTE_CALL, TDCMD_SHEAP_ALLOC, TDCMD_SHEAP_CALLOC, TDCMD_SHEAP_FREE, TDCMD_SHEAP_REALLOC, TDCMD_SIMPLEMAIL_ALLOC, TDCMD_SYNCEVENT_HIT, tdr, tdrc, and tdrr.
Referenced by DefaultTaskDaemon().
int GarbageCollect ()
Cleans up all unused resources.
Actually, only all zombie processes will be removed.
Returns:
EAGAIN when there was nothing to clean, otherwise ESUCCESS
Definition at line 541 of file DefaultTaskDaemon.cc.
References dRemoteCall(), ESUCCESS, GarbageCollect(), getpid(), GetProcessStats(), GetProcID(), lGetZombie(), proc_stats_t::min_stack, and proc_stats_t::slice_used.
Referenced by DefaultTaskDaemon(), and GarbageCollect().
static int GetIssueSlot (pid_t & me, tdcmd_local_t *& tdl, volatile tdcmd_t *& cmd, int proc, bool & async) [static]
Finds the slot to put a new command in, either to local processes or remote.
Parameters:
me the upid of the calling process (output)
tdl the pointer to the local command list (output)
cmd a pointer to a slot in a command list, either for the local task daemon or a remote one (output)
proc the process to send a command to
async when true, the command can be sent asynchronously and bypassing the local task daemon (mostly input, but can be overruled)
Returns:
0 on success, an errno otherwise
Definition at line 1334 of file DefaultTaskDaemon.cc.
References ASSERT, tdcmd_t::cmd, tdcmd_local_t::cmd, GetHook(), GetOSState, getupid(), HOOK_TASKDAEMON, InitMail, MailRead(), OS_SOC, tdcmd_t::proc, tdcmd_t::res, ReserveRemoteSlot(), sigaddset(), SIGCONT, sigemptyset(), Suspend(), sysconf(), and TDCMD_NONE.
static int HandleGPS (int cmdres, proc_state_t * state, bool * sighandling, ProcessState_t * pack) [static]
Definition at line 1475 of file DefaultTaskDaemon.cc.
References ProcessState_t::sigh, and ProcessState_t::state.
Referenced by dGetProcessState().
static int HandleWPD (int cmdres, Mail * w, void ** ret) [static]
Definition at line 1424 of file DefaultTaskDaemon.cc.
References lDestroyMail, and MailRead().
Referenced by dWaitProcess().
static int InitSHeap () [static]
Definition at line 405 of file DefaultTaskDaemon.cc.
References _heap_end, _sheap, DEBUGH, ESUCCESS, FlushDCache(), FlushDCacheWord(), malloc_init(), sheap_last_addr, and sheap_set_end.
Referenced by DefaultMulticoreSetup().
static int ProcessRequest (tdcmd_t * cmd, int cmd_type) [static]
Processes a request at this core.
Parameters:
cmd the command to execute, cannot be NULL.
cmd_type the message type (which is usually also stored in cmd->cmd)
Definition at line 601 of file DefaultTaskDaemon.cc.
References addr_direct(), addr_global(), ASSERT, tdcmd_t::chan_id, tdcmd_t::chan_label, tdcmd_t::chan_value, DAEMON_DEFAULT_STACK, DAEMON_DEFAULT_TIMESLICE, DEBUGH, DEBUGL, ProcessState_t::dummy, ESUCCESS, tdcmd_t::fifo_element_size, tdcmd_t::fifo_flags, tdcmd_t::fifo_ret, tdcmd_t::fifo_size, tdcmd_t::fun, tdcmd_t::fun_arg, tdcmd_t::fun_ret, GetProcID(), lAllocChannels(), lAllocFifoEndPoint, lAllocMail, lAllocSimpleMail, lAssignChannel(), lck_ask(), lck_giveup(), tdcmd_t::lck_list, tdcmd_t::lck_lock, lck_register(), lck_request(), tdcmd_t::lck_requester, lCreateProcess(), lDestroyFifoEndPoint, lDestroyMail, lDestroyProcess(), lGetProcessFlags(), lGetProcessState(), lSendSignal(), lSetChannelLabel(), lSetProcessFlags(), lSetProcessTimeslice(), lStartProcess(), lSyncEventHit(), tdcmd_t::mail_count, tdcmd_t::mail_ret, MailWrite(), tdcmd_t::malloc_nmemb, tdcmd_t::malloc_ptr, tdcmd_t::malloc_reptr, tdcmd_t::malloc_size, tdcmd_t::num, tdcmd_t::op1, tdcmd_t::op2, OS_SHUTDOWN, PACK_RES, tdcmd_t::pid, pid, tdcmd_t::proc, tdcmd_t::proc_create_arg, tdcmd_t::proc_create_main, tdcmd_t::proc_create_stacksize, tdcmd_t::proc_create_timeslice, tdcmd_t::ptr, tdcmd_t::res, tdcmd_t::ret_ptr, scalloc(), SetOSState, sfree(), tdcmd_t::sig_num, tdcmd_t::sig_sv, ProcessState_t::sigh, smalloc(), srealloc(), StartShutdownDaemon(), ProcessState_t::state, ProcessState_t::state_, TDCMD_ATOMIC_ADD, TDCMD_ATOMIC_CAS, TDCMD_ATOMIC_XCHG, TDCMD_CHANNEL_ALLOC, TDCMD_CHANNEL_ASSIGN, TDCMD_CHANNEL_LABEL, TDCMD_FIFO_ALLOC, TDCMD_FIFO_DESTROY, TDCMD_LOCK_ASK, TDCMD_LOCK_GIVEUP, TDCMD_LOCK_REGISTER, TDCMD_LOCK_REQUEST, TDCMD_MAIL_ALLOC, TDCMD_MAIL_DESTROY, TDCMD_PROCESS_CREATE, TDCMD_PROCESS_DESTROY, TDCMD_PROCESS_GET_FLAGS, TDCMD_PROCESS_GET_STATE, TDCMD_PROCESS_SET_FLAGS, TDCMD_PROCESS_SET_TIMESLICE, TDCMD_PROCESS_SIGNAL, TDCMD_PROCESS_START, TDCMD_PROCESS_WAIT, TDCMD_REMOTE_CALL, TDCMD_SHEAP_ALLOC, TDCMD_SHEAP_CALLOC, TDCMD_SHEAP_FREE, TDCMD_SHEAP_REALLOC, TDCMD_SHUTDOWN, TDCMD_SIMPLEMAIL_ALLOC, TDCMD_SYNCEVENT_HIT, tdcmd_t::timeslice, and WaitProcessDaemon().
Referenced by DefaultTaskDaemon().
static volatile tdcmd_t* ReserveRemoteSlot (tdcmd_local_t * tdl, int proc) [static]
Tries to reserve a slot in a remote command list, depending on other (parallel) commands in transit.
Parameters:
tdl pointer to the local command list
proc the processor to send a command to
Returns:
a pointer to a remote slot, which is allocated, or NULL on failure.
Definition at line 1298 of file DefaultTaskDaemon.cc.
References addr_global(), ASSERT, tdcmd_local_t::busy_proc, cmd, GetProcID(), InitMail, PROC_ASYNC, PROC_IDLE, PROC_SYNC, tdcmd_t::res, tdr, and tdrc.
Referenced by GetIssueSlot().
static void StatsCount (int cmd, tds_type_t type) [inline, static]
Count a single event of a specific command.
Parameters:
cmd a command to count
type the type how this command was received: sent from and to the local core, forwarded to another core, received from anther core
Definition at line 159 of file DefaultTaskDaemon.cc.
References ASSERT, cmd, TDCMD_COUNT, TDS, TDS_FORWARD, TDS_LOCAL, and TDS_REMOTE.
Referenced by DefaultTaskDaemon().
static void StatsDump () [static]
Print statistics for this task daemon.
Definition at line 206 of file DefaultTaskDaemon.cc.
References GetProcID(), TDCMD_COUNT, and TDS.
Referenced by InitTaskDaemon().
static int StatsInit () [static]
Initialization for message statistics.
Always call before using StatsCount().
Definition at line 145 of file DefaultTaskDaemon.cc.
References DEBUGH, lcalloc, and thread_local.
Referenced by InitTaskDaemon().
static int WaitForResult () [static]
Yield (and suspend when possible) to wait for a remote command to be finished.
Returns:
0 on success, an errno otherwise
Definition at line 1372 of file DefaultTaskDaemon.cc.
References ESUCCESS, sigaddset(), SIGCONT, sigemptyset(), Suspend(), and Yield().
static void* WaitProcessDaemon (void * arg) [static]
Simple process that joins another process that is running on this core.
This is the backend process of dWaitProcess. It will call JoinProcess() repeatedly until the call is successful. When a join cannot be executed, the process Yield()s. Channel 0 must be a pointer to Mail. This mailbox will get the status value (errno) on index 1. When the join was successfull, the return value of the process that is joined is put on index 0.
Parameters:
arg the pid to join (must be of type pid_t)
Returns:
The status value of the join.
Definition at line 575 of file DefaultTaskDaemon.cc.
References ASSERT, DEBUGL, ESUCCESS, getpid(), lJoinProcess(), MailWrite(), OpenChannel(), pid, and Yield().
Referenced by ProcessRequest().
Variable Documentation
int(* __boot_funs[])(void)
Referenced by InitTaskDaemon().
int _argc = 1
Definition at line 225 of file DefaultTaskDaemon.cc.
char _args_buf[MAIN_MAX_ARGC *8] = "skat"
Definition at line 226 of file DefaultTaskDaemon.cc.
char* _argv[MAIN_MAX_ARGC+1] = {_args_buf}
All arguments to main().
The contents are usually modified by the XMD-script, which patches the memory region the variable is stored.
Definition at line 231 of file DefaultTaskDaemon.cc.
void* const _ddrbase
void* const _heap_end
Referenced by InitSHeap(), and mainProc().
const char* tdcmd_name[TDCMD_COUNT] [static]
Names corresponding to command IDs.
Definition at line 169 of file DefaultTaskDaemon.cc.