Starburst: include/sys/device.h File Reference
include/sys/device.h File Reference
Declaration of functions that gives information about the hardware platform.
#include <sys/types.h>
#include <sys/kernel_types.h>
#include <sys/helix_config.h>
Defines
#define MB_FLAG_DCACHE_WRITEBACK (1<<0)
#define MB_FLAG_HAVE_HWMUL (1<<1)
#define MB_FLAG_HAVE_BARREL (1<<2)
#define MB_FLAG_HAVE_MSR (1<<3)
#define MB_FLAG_HAVE_PCMP (1<<4)
#define MB_FLAG_HAVE_FPU (1<<5)
#define MB_FLAG_SHARED_HEAP_CACHED (1<<6)
#define ClearDMemAccess(...)
#define DumpDMemAccess(...)
#define ATOMIC_CAS(name, op)
#define ATOMIC_CONDSET_OP(name, op)
#define ATOMIC_OP(name, op, swx_reg)
#define ATOMIC_OP_RETOLD(name, op) ATOMIC_OP(name,op,"r11")
#define ATOMIC_OP_RETNEW(name, op) ATOMIC_OP(name,op,"%0")
#define lainc(a) lainco(a,0)
#define ladec(a) ladeco(a,0)
#define laset(a, flags) laor(a,flags)
#define launset(a, flags) laandn(a,flags)
#define lulcklsb(a) launset(a,1)
Typedefs
typedef volatile int llck_t
Functions
unsigned int GetClockFreq (void) _NO_THROW __attribute__((const))
Returns the clock frequency of the current core in Hz.
size_t GetLocalMemSize (void) _NO_THROW __attribute__((const))
Returns the size of the local memory in bytes.
size_t GetFifoMemSize (void) _NO_THROW __attribute__((const))
Returns the size of the FIFO memory in bytes.
unsigned int GetSoCCores (void) _NO_THROW __attribute__((const))
Returns the number of cores in the SoC.
unsigned int GetMBFlags (void) _NO_THROW __attribute__((const))
Returns configuration settings of this core.
size_t GetICacheSize (void) _NO_THROW __attribute__((const))
Returns the size of the instruction cache of this processor.
size_t GetDCacheSize (void) _NO_THROW __attribute__((const))
Returns the size of the data cache of this processor.
void InitICache (void) _NO_THROW
Initializes, invalidates and enables instruction cache (when available).
void EnableICache (void) _NO_THROW
Enables instruction cache (when available).
void DisableICache (void) _NO_THROW
Disables instruction cache (when available).
void InitDCache (void) _NO_THROW
Initializes, invalidates and enables data cache (when available).
void EnableDCache (void) _NO_THROW
Enables data cache (when available).
unsigned int DisableDCache (void) _NO_THROW
Disables data cache (when available).
void InvalidateDCache (void) _NO_THROW
Invalidates (means: just drop data from cache) the complete data cache.
static void InvalidateDCacheRange (void *base, size_t size) _NO_THROW __attribute__((always_inline))
Invalidates (means: just drop data from cache) a range of the data cache.
static void InvalidateDCacheWord (void *base) _NO_THROW __attribute__((always_inline))
Invalidates (means: just drop data from cache) the cacheline containing the specified word.
void FlushDCache (void) _NO_THROW
Flushes (means: write back and invalidate) the complete data cache.
static void FlushDCacheRange (void *base, size_t size) _NO_THROW __attribute__((always_inline))
Flushes (means: write back and invalidate) a range of the data cache.
static void FlushDCacheWord (void *base) _NO_THROW __attribute__((always_inline))
Flushes (means: write back and invalidate) the cacheline containing the specified word.
static unsigned int GetProcID (void) _NO_THROW __attribute__((always_inline
static int lxchg (int *a, int newval) _NO_THROW __attribute__((always_inline))
static int llcklsb (int *a) _NO_THROW __attribute__((always_inline))
static void lastart (int *a) _NO_THROW __attribute__((always_inline))
static bool laend (int *a, int val) _NO_THROW __attribute__((always_inline))
static int clz (unsigned int i) _NO_THROW __attribute__((always_inline
Variables
static unsigned int const
static int pure
Detailed Description
Declaration of functions that gives information about the hardware platform.
The values are read from the local memory that contains the .devinfo section.
Definition in file device.h.
Define Documentation
#define ATOMIC_CAS (name, op)
Value:
static inline int l##name(int* a,int oldval,int newval) _NO_THROW __attribute__ ((always_inline)); \
static inline int l##name(int* a,int oldval,int newval) _NO_THROW {                             \
    int res;                                                                                    \
    asm volatile (                                                                              \
    "1: "                                                                                       \
        "lwx    %0, %1, r0;"        /* load from a */                                           \
        "rsubk  r11, %0, %2;"       /* subtract *a and oldval */                                \
        op "i   r11, 2f;"           /* branch when *a=?=oldval */                               \
        "swx    %3, %1, r0;"        /* save newval */                                           \
        "addic  r11, r0, 0;"        /* check reservation bit */                                 \
        "bnei   r11, 1b;"           /* branch when interrupted */                               \
    "2: "                                                                                       \
        :"=&r"(res):"r"(a),"r"(oldval),"r"(newval):"r11","memory"                               \
    );                                                                                          \
    return res;                                                                                 \
}
Definition at line 227 of file device.h.
#define ATOMIC_CONDSET_OP (name, op)
Value:
static inline int l##name(int* testa,int test,int* seta,int seteq,int setneq) _NO_THROW __attribute__ ((always_inline));    \
static inline int l##name(int* testa,int test,int* seta,int seteq,int setneq) _NO_THROW {                       \
    int res;                                                                                                    \
    asm volatile (                                                                                              \
    "1: "                                                                                                       \
        "lwx    %0, %1, r0;"        /* load from testa */                                                       \
        op "    r11, %0, %2;"       /* test *testa and test */                                                  \
        "bnei   r11, 2f;"           /* branch when *testa!=test */                                              \
        "brid   3f;"                                                                                            \
        "swx    %4, %3, r0;"        /* set=seteq */                                                             \
    "2: "                                                                                                       \
        "swx    %5, %3, r0;"        /* set=setneq */                                                            \
    "3: "                                                                                                       \
        "addic  r11, r0, 0;"        /* check reservation bit */                                                 \
        "bnei   r11, 1b;"           /* branch when interrupted */                                               \
        :"=&r"(res):"r"(testa),"r"(test),"r"(seta),"r"(seteq),"r"(setneq):"r11","memory"                        \
    );                                                                                                          \
    return res;                                                                                                 \
}
Definition at line 251 of file device.h.
#define ATOMIC_OP (name, op, swx_reg)
Value:
static inline int la##name(int* a,int operand) _NO_THROW __attribute__ ((always_inline));   \
static inline int la##name(int* a,int operand) _NO_THROW {                          \
    int res;                                                                        \
    asm volatile (                                                                  \
    "1: "                                                                           \
        "lwx    %0, %1, r0;"        /* load from a */                               \
        op                          /* execute operation */                         \
        "swx " swx_reg ", %1, r0;"  /* save newval */                               \
        "addic  r11, r0, 0;"        /* check reservation bit */                     \
        "bnei   r11, 1b;"           /* branch when interrupted */                   \
        :"=&r"(res):"r"(a),"r"(operand):"r11","memory"                              \
    );                                                                              \
    return res;                                                                     \
}
Definition at line 277 of file device.h.
#define ATOMIC_OP_RETNEW (name, op) ATOMIC_OP(name,op,"%0")
Definition at line 293 of file device.h.
#define ATOMIC_OP_RETOLD (name, op) ATOMIC_OP(name,op,"r11")
Definition at line 292 of file device.h.
#define ClearDMemAccess (...)
Definition at line 207 of file device.h.
Referenced by mainProc().
#define DumpDMemAccess (...)
Definition at line 208 of file device.h.
Referenced by mainProc().
#define ladec (a) ladeco(a,0)
Definition at line 310 of file device.h.
Referenced by kTraceSync().
#define lainc (a) lainco(a,0)
Definition at line 307 of file device.h.
#define laset (a, flags) laor(a,flags)
Definition at line 312 of file device.h.
Referenced by kSendSignal().
#define launset (a, flags) laandn(a,flags)
Definition at line 314 of file device.h.
Referenced by kSuspend().
#define lulcklsb (a) launset(a,1)
Definition at line 335 of file device.h.
#define MB_FLAG_DCACHE_WRITEBACK (1<<0)
Definition at line 44 of file device.h.
Referenced by kInitKernel().
#define MB_FLAG_HAVE_BARREL (1<<2)
Definition at line 46 of file device.h.
#define MB_FLAG_HAVE_FPU (1<<5)
Definition at line 49 of file device.h.
#define MB_FLAG_HAVE_HWMUL (1<<1)
Definition at line 45 of file device.h.
#define MB_FLAG_HAVE_MSR (1<<3)
Definition at line 47 of file device.h.
#define MB_FLAG_HAVE_PCMP (1<<4)
Definition at line 48 of file device.h.
#define MB_FLAG_SHARED_HEAP_CACHED (1<<6)
Definition at line 50 of file device.h.
Referenced by kInitKernel().
Typedef Documentation
typedef volatile int llck_t
Definition at line 383 of file device.h.
Function Documentation
static int clz (unsigned int i) [inline, static]
Definition at line 359 of file device.h.
unsigned int DisableDCache (void)
Disables data cache (when available).
Returns:
A number that indicates how slow the memory was (mainly for debugging)
When turning off the cache, all valid lines will be written to the memory. So, turning off and on the cache at any point in the program is safe. The cache will be completely invalidated when DisableDCache() returns.
Referenced by kPanic(), and kShutdown().
void DisableICache (void)
Disables instruction cache (when available).
The cache will never be turned off by the kernel. Moreover, this setting is a per-process setting.
Referenced by kPanic(), and kShutdown().
void EnableDCache (void)
Enables data cache (when available).
void EnableICache (void)
Enables instruction cache (when available).
void FlushDCache (void)
Flushes (means: write back and invalidate) the complete data cache.
Does nothing when there is no data cache.
Referenced by DumpStats(), FlushDCacheRange(), InitSHeap(), kPanic(), and TraceDump().
static void FlushDCacheRange (void * base, size_t size) [inline, static]
Flushes (means: write back and invalidate) a range of the data cache.
Does nothing when there is no data cache.
Parameters:
base address to invalidate
size the number of bytes to invalidate (which is rounded to full cache lines)
Definition at line 161 of file device.h.
References ATTR_WDC_FLUSH_REG, DCACHE_LINESIZE, DUFF, FlushDCache(), and GetDCacheSize().
Referenced by gettimeofday(), linfs_open(), linfs_write(), and mc_flush_().
static void FlushDCacheWord (void * base) [inline, static]
Flushes (means: write back and invalidate) the cacheline containing the specified word.
Does nothing when there is no data cache.
The functionality is identical to FlushDCacheRange(base,1), but this one is implemented more efficiently.
Parameters:
base address to invalidate
Definition at line 184 of file device.h.
References ATTR_WDC_FLUSH_REG.
Referenced by InitSHeap(), linfs_read(), and mc_flushw_().
unsigned int GetClockFreq (void) const
Returns the clock frequency of the current core in Hz.
Referenced by kCoreDump(), kGetProcessStats(), kSetProcessTimeslice(), kTraceInit(), prf_mb_dump(), sw_elapsed_cycles(), and sysconf().
size_t GetDCacheSize (void) const
Returns the size of the data cache of this processor.
Referenced by FlushDCacheRange(), and kInitKernel().
size_t GetFifoMemSize (void) const
Returns the size of the FIFO memory in bytes.
Referenced by kInitKernel(), and linfs_unregister().
size_t GetICacheSize (void) const
Returns the size of the instruction cache of this processor.
Referenced by kInitKernel().
size_t GetLocalMemSize (void) const
Returns the size of the local memory in bytes.
Referenced by kInitKernel().
unsigned int GetMBFlags (void) const
Returns configuration settings of this core.
Returns:
A combination of the MB_FLAG_* flags.
Referenced by kInitKernel().
static unsigned int GetProcID (void) [inline, static]
Definition at line 196 of file device.h.
Referenced by auto_ret< T, ok >::abort(), mfifo_t< T, FIFO_READERS, FIFO_SIZE_BITS, B >::acquire_elem(), addr_direct(), addr_global(), BootKernel(), mfifo_t< T, FIFO_READERS, FIFO_SIZE_BITS, B >::bump(), CheckRing(), CFifo< T, r >::Create(), DefaultMulticoreSetup(), DefaultTaskDaemon(), WorkQueue< T, W >::DispatchWork(), CFifo< T, r >::dump(), DumpStatsDaemon(), mfifo_t< T, FIFO_READERS, FIFO_SIZE_BITS, B >::elem_t::entry_x(), mfifo_t< T, FIFO_READERS, FIFO_SIZE_BITS, B >::elem_t::exit_x(), find_cpu(), findApp(), ForceShutdown(), PMC_NS::Error::format(), ForwardRequest(), mfifo_t< T, FIFO_READERS, FIFO_SIZE_BITS, B >::front(), mfifo_t< T, FIFO_READERS, FIFO_SIZE_BITS, B >::front_elem(), GarbageCollect(), getgpid(), CFifo< T, r >::init(), InitTaskDaemon(), WorkQueue< T, W >::IsEmpty(), WorkQueue< T, W >::IsFull(), kCoreDump(), kEndProcess(), kInitKernel(), kPanic(), kTraceInit(), lck_ask(), lck_giveup(), lck_request(), linfs_register_seq(), malloc_dump(), mc_error_handler(), CFifo< T, CFifo<>::w >::operator new(), WorkQueue< T, W >::Pop(), mfifo_t< T, FIFO_READERS, FIFO_SIZE_BITS, B >::pop(), pprintf(), PrintProfilerOutput(), ProcessRequest(), pthread_local_init(), WorkQueue< T, W >::Push(), mfifo_t< T, FIFO_READERS, FIFO_SIZE_BITS, B >::push(), rc_flush_(), rc_init(), ReserveRemoteSlot(), scalloc(), sfree(), ShutdownDaemon(), smalloc(), srealloc(), WorkQueue< T, W >::StartSlaves(), StatsDump(), TaskDaemon(), TraceDump(), CFifo< T, r >::validate(), WaitProcess(), and WorkQueue< T, W >::WorkQueue().
unsigned int GetSoCCores (void) const
Returns the number of cores in the SoC.
Referenced by DefaultMulticoreSetup(), ForceShutdown(), kInitKernel(), and ShutdownDaemonInit().
void InitDCache (void)
Initializes, invalidates and enables data cache (when available).
Referenced by kInitKernel(), and main().
void InitICache (void)
Initializes, invalidates and enables instruction cache (when available).
This function is called during initialization of the kernel. Override it to change the caching behavior.
Referenced by kInitKernel(), and main().
void InvalidateDCache (void)
Invalidates (means: just drop data from cache) the complete data cache.
Does nothing when there is no data cache.
Referenced by kInitKernel().
static void InvalidateDCacheRange (void * base, size_t size) [inline, static]
Invalidates (means: just drop data from cache) a range of the data cache.
Does nothing when there is no data cache.
Parameters:
base address to invalidate
size the number of bytes to invalidate (which is rounded to full cache lines)
Definition at line 127 of file device.h.
References DCACHE_LINESIZE.
Referenced by linfs_read(), main(), and mc_update_().
static void InvalidateDCacheWord (void * base) [inline, static]
Invalidates (means: just drop data from cache) the cacheline containing the specified word.
Does nothing when there is no data cache.
The functionality is identical to InvalidateDCacheRange(base,1), but this one is implemented more efficiently.
Parameters:
base address to invalidate
Definition at line 141 of file device.h.
static bool laend (int * a, int val) [inline, static]
Definition at line 348 of file device.h.
References a.
Referenced by kYield().
static void lastart (int * a) [inline, static]
Definition at line 339 of file device.h.
References a.
Referenced by kYield().
static int llcklsb (int * a) [inline, static]
Definition at line 318 of file device.h.
References a.
static int lxchg (int * a, int newval) [inline, static]
Definition at line 213 of file device.h.
References a.
Referenced by kTraceClose().
Variable Documentation
unsigned int const
Definition at line 195 of file device.h.
Referenced by prf_mem_dump().
int pure
Definition at line 358 of file device.h.