Starburst: io/dir.cc File Reference
io/dir.cc File Reference
#include <dirent.h>
#include <ramfile.h>
#include <malloc.h>
#include <unistd.h>
#include <string.h>
#include <errno.h>
#include <sys/api.h>
Defines
#define DEBUG(...)
Functions
DIR * opendir (const char *dirname)
struct dirent * readdir (DIR *dirp)
off_t telldir (DIR *dirp)
void seekdir (DIR *dirp, off_t loc)
void rewinddir (DIR *dirp)
int closedir (DIR *dirp)
char * getwd (char *buf)
char * getcwd (char *buf, size_t size)
Variables
ramfile_entry_t ramfile_table [MAX_RAMFILES]
Define Documentation
#define DEBUG (...)
Definition at line 12 of file dir.cc.
Referenced by closedir(), opendir(), and readdir().
Function Documentation
int closedir (DIR * dirp)
Definition at line 79 of file dir.cc.
References DIR::base, DEBUG, and lfree.
char* getcwd (char * buf, size_t size)
Definition at line 97 of file dir.cc.
char* getwd (char * buf)
Definition at line 88 of file dir.cc.
DIR* opendir (const char * dirname)
Definition at line 17 of file dir.cc.
References DIR::base, DIR::base_len, DEBUG, lmalloc, and rewinddir().
struct dirent* readdir (DIR * dirp) [read]
Definition at line 33 of file dir.cc.
References DIR::base, DIR::base_len, DIR::cur, dirent::d_ino, dirent::d_name, DEBUG, DIR::index, and DIR::offset.
Referenced by seekdir().
void rewinddir (DIR * dirp)
Definition at line 71 of file dir.cc.
References DIR::index, and DIR::offset.
Referenced by opendir(), and seekdir().
void seekdir (DIR * dirp, off_t loc)
Definition at line 60 of file dir.cc.
References DIR::offset, readdir(), and rewinddir().
off_t telldir (DIR * dirp)
Definition at line 52 of file dir.cc.
References DIR::offset.
Variable Documentation
ramfile_entry_t ramfile_table[MAX_RAMFILES]