Starburst: include/dirent.h File Reference
include/dirent.h File Reference
#include <sys/syslimits.h>
#include <sys/types.h>
Data Structures
struct dirent
struct DIR
Functions
DIR * opendir (const char *dirname)
struct dirent * readdir (DIR *dirp)
off_t telldir (DIR *dirp)
void seekdir (DIR *dirp, off_t loc)
void rewinddir (DIR *dirp)
int closedir (DIR *dirp)
Function Documentation
int closedir (DIR * dirp)
Definition at line 79 of file dir.cc.
References DIR::base, DEBUG, and lfree.
DIR* opendir (const char * dirname)
Definition at line 17 of file dir.cc.
References DIR::base, DIR::base_len, DEBUG, lmalloc, and rewinddir().
struct dirent* readdir (DIR * dirp) [read]
Definition at line 33 of file dir.cc.
References DIR::base, DIR::base_len, DIR::cur, dirent::d_ino, dirent::d_name, DEBUG, DIR::index, and DIR::offset.
Referenced by seekdir().
void rewinddir (DIR * dirp)
Definition at line 71 of file dir.cc.
References DIR::index, and DIR::offset.
Referenced by opendir(), and seekdir().
void seekdir (DIR * dirp, off_t loc)
Definition at line 60 of file dir.cc.
References DIR::offset, readdir(), and rewinddir().
off_t telldir (DIR * dirp)
Definition at line 52 of file dir.cc.
References DIR::offset.