Starburst: daemons/DumpStatsDaemon.cc File Reference
daemons/DumpStatsDaemon.cc File Reference
Daemons
A daemon to print process statistics every time interval.
#include <helix.h>
Data Structures
struct dsd_t
Arguments passed between StartDumpStatsDaemon() and DumpStatsDaemon()
struct dsdh_t
Arguments passed between DumpStatsDaemon() and DumpStatsDaemonNow()
Functions
static int DumpStats (proc_stats_t(*stats)[MAX_PROCESSES])
Dumps process information to memory.
void DumpStatsNow (int sig, siginfo_t *si, void *dummy)
Collects stats from all cores and prints it on the console.
void * DumpStatsDaemon (void *arg)
Main process of the stats daemon.
int StartDumpStatsDaemon (int interval, void *(*main)(void *), void(*tdstats)(void))
Stats the DumpStatsDaemon().
Detailed Description
A daemon to print process statistics every time interval.
Definition in file DumpStatsDaemon.cc.
Function Documentation
static int DumpStats (proc_stats_t(*) stats[MAX_PROCESSES]) [static]
Dumps process information to memory.
Flushes the D-cache afterwards.
Parameters:
stats the data structure to dump the information to
Returns:
0 on succes, an errno otherwise.
Definition at line 16 of file DumpStatsDaemon.cc.
References FlushDCache(), GetProcessStats(), MAX_PROCESSES, mc_entry_wou, and mc_exit_wou.
Referenced by DumpStatsNow().
void* DumpStatsDaemon (void * arg)
Main process of the stats daemon.
Initializes the environment, sets up an timer that invokes DumpStatsNow() periodically.
Parameters:
arg a pointer to a dsd_t structure
See also:
StartDumpStatsDaemon()
Definition at line 94 of file DumpStatsDaemon.cc.
References a, core, dRemoteCall(), DumpStatsNow(), GetProcID(), dsd_t::interval, MailWrite(), dsd_t::main, dsdh_t::main, MAX_PROCESSES, pause(), sfree(), smalloc(), dsd_t::started, sysconf(), dsd_t::tdstats, and timer_repeat().
Referenced by StartDumpStatsDaemon().
void DumpStatsNow (int sig, siginfo_t * si, void * dummy)
Collects stats from all cores and prints it on the console.
This is a signal handler, triggered by a timer.
Parameters:
sig the signal that triggered the execution of this handler
si si->si_value.sival_ptr contains a dsdh_t structure containing information what to dump
dummy ignored
Definition at line 50 of file DumpStatsDaemon.cc.
References ASSERT, proc_stats_t::context, proc_stats_t::context_switches, core, dsdh_t::cores, dRemoteCall(), DumpStats(), proc_stats_t::flags, gettimeofday(), proc_stats_t::insighandler, dsdh_t::main, proc_stats_t::main, MAX_PROCESSES, mc_entry_ro, mc_exit_ro, proc_stats_t::min_stack, NOPROC, proc_stats_t::pid, siginfo_t::si_value, sigval::sival_ptr, proc_stats_t::slice_length, proc_stats_t::slice_used, proc_stats_t::state, dsdh_t::stats, dsdh_t::stop, proc_stats_t::yields, and ZOMBIE.
Referenced by DumpStatsDaemon().