Starburst: io/dvi.cc File Reference
io/dvi.cc File Reference
Low-level functions to control the DVI port.
#include <sys/io.h>
#include <sys/helix_config.h>
#include "iodebug.h"
Functions
void dvi_init (void *address)
Initializes DVI controller.
void dvi_set_address (void *address)
Set a new base address of the video memory for the next frame.
dvi_frame * dvi_get_address ()
Returns the address of the video memory of the currently displayed frame.
void dvi_turn_on ()
Turns on the video output.
void dvi_turn_off ()
Turns off the video output.
bool dvi_vsync ()
Checks whether a vsync occured.
void dvi_set_pixel (unsigned int x, unsigned int y, dvi_pixel color)
Sets a specific pixel in the current frame.
void dvi_set_pixel (unsigned int x, unsigned int y, unsigned int red, unsigned int green, unsigned int blue)
Sets a specific pixel in the current frame.
dvi_pixel dvi_get_pixel (unsigned int x, unsigned int y)
Gets the pixel information of a specific pixel in the current frame.
void dvi_get_pixel (unsigned int x, unsigned int y, unsigned int &red, unsigned int &green, unsigned int &blue)
Gets the color of a specific pixel in the current frame.
Variables
unsigned int _ddrbase
Detailed Description
Low-level functions to control the DVI port.
The supported video format is 640x480 pixels, 60 Hz, 24 bit colors. Frame lines are 1024 pixels wide, but only the first 640 pixels are shown on the screen. Pixel information is stored as follows: (msb) --------rrrrrr--gggggg--bbbbbb-- (lsb).
Definition in file dvi.cc.
Function Documentation
dvi_frame* dvi_get_address ()
Returns the address of the video memory of the currently displayed frame.
Definition at line 38 of file dvi.cc.
References IO_DVI_AR, and io_read.
Referenced by dvi_get_pixel(), and dvi_set_pixel().
dvi_pixel dvi_get_pixel (unsigned int x, unsigned int y)
Gets the pixel information of a specific pixel in the current frame.
Definition at line 94 of file dvi.cc.
References dvi_get_address(), io_read, and dvi_pixel_::raw.
Referenced by dvi_get_pixel().
void dvi_get_pixel (unsigned int x, unsigned int y, unsigned int & red, unsigned int & green, unsigned int & blue)
Gets the color of a specific pixel in the current frame.
Note that using this function has a huge overhead. Consider reading from the video memory directly for better performance.
Parameters:
x the column on the screen
y the row on the screen, where the upper left corner is the origin
red the red component of the pixel, range from 0 to 255
green the green component of the pixel, range from 0 to 255
blue the blue component of the pixel, range from 0 to 255
Definition at line 110 of file dvi.cc.
References dvi_pixel_::blue, dvi_get_pixel(), dvi_pixel_::green, dvi_pixel_::red, dvi_pixel_::rgb, and dvi_pixel_::rgb_exact.
void dvi_init (void * address)
Initializes DVI controller.
Definition at line 18 of file dvi.cc.
References _ddrbase, and dvi_set_address().
Referenced by mainProc().
void dvi_set_address (void * address)
Set a new base address of the video memory for the next frame.
Parameters:
address the new address, will be aligned to 2MB boundary
Definition at line 31 of file dvi.cc.
References IO_DVI_AR, and io_write.
Referenced by dvi_screen::DoubleBuf(), dvi_init(), dvi_screen::Flip(), dvi_screen::FlipNow(), and dvi_screen::ShowBuffer().
void dvi_set_pixel (unsigned int x, unsigned int y, dvi_pixel color)
Sets a specific pixel in the current frame.
Definition at line 68 of file dvi.cc.
References dvi_get_address(), io_write, and dvi_pixel_::raw.
Referenced by dvi_set_pixel().
void dvi_set_pixel (unsigned int x, unsigned int y, unsigned int red, unsigned int green, unsigned int blue)
Sets a specific pixel in the current frame.
Note that using this function has a huge overhead. Consider writing to the video memory directly for better performance.
Parameters:
x the column on the screen
y the row on the screen, where the upper left corner is the origin
red the red component of the pixel, range from 0 to 255
green the green component of the pixel, range from 0 to 255
blue the blue component of the pixel, range from 0 to 255
Definition at line 82 of file dvi.cc.
References blue, dvi_pixel_::blue, dvi_set_pixel(), green, dvi_pixel_::green, red, dvi_pixel_::red, and dvi_pixel_::rgb.
void dvi_turn_off ()
Turns off the video output.
Definition at line 52 of file dvi.cc.
References IO_DVI_CR, and io_write.
void dvi_turn_on ()
Turns on the video output.
Definition at line 45 of file dvi.cc.
References IO_DVI_CR, and io_write.
bool dvi_vsync ()
Checks whether a vsync occured.
dvi_vsync() keeps returning true until dvi_set_address() is called.
Returns:
true when a vsync has occured since the last call to dvi_set_address()
Definition at line 61 of file dvi.cc.
References IO_DVI_IESR, and io_read.
Referenced by dvi_screen::Flip(), and dvi_screen::FlipSlave().
Variable Documentation
unsigned int _ddrbase