Starburst: ipc/fifo.cc File Reference
ipc/fifo.cc File Reference
Implementation of several FIFO functions.
#include <fifo.h>
#include <sys/io.h>
Functions
int InitFifo (FifoEP *ep_write, FifoEP *ep_read, unsigned int size, int flags)
Initializes the FIFO pointers.
Detailed Description
Implementation of several FIFO functions.
Definition in file fifo.cc.
Function Documentation
int InitFifo (FifoEP * ep_write, FifoEP * ep_read, unsigned int size, int flags)
Initializes the FIFO pointers.
Always call this function after both end points have been allocated for all kinds of FIFOs.
Parameters:
ep_write write end point (is identical to ep_read in case of FIFO_ENDPOINT_BOTH), cannot be NULL
ep_read read end point (is identical to ep_write in case of FIFO_ENDPOINT_BOTH), cannot be NULL
size the size of the FIFO in number of elements
flags a combination of FIFO_* flags
Definition at line 9 of file fifo.cc.
References addr_direct(), addr_global(), addr_local(), ESUCCESS, Fifo::fifo, FifoEP::fifo, FIFO_LOCAL, Fifo::local, FifoEP::ptr, Fifo::remote, Fifo_admin::rp, Fifo::size, and Fifo_admin::wp.
Referenced by map_start_fifo().