Starburst: include/bitshark/fir_lpf.h File Reference
include/bitshark/fir_lpf.h File Reference
Functions
int fir_lpf_gen_gauss (int N, float *win)
Generate a Gaussian filter window for use with the filter generation.
int fir_lpf_gen_sinc (int N, float cutoff, float *coef)
Generate N coefficients for a low-pass FIR filter.
Function Documentation
int fir_lpf_gen_gauss (int N, float * win)
Generate a Gaussian filter window for use with the filter generation.
Based on: http://en.wikipedia.org/wiki/Gaussian_filter
Parameters:
N Number of samples to generate the Gaussian for
win Pointer to an array to fill with window values
Returns:
0 if all ok
Definition at line 20 of file fir_lpf.cc.
Referenced by fir_lpf_gen_sinc().
int fir_lpf_gen_sinc (int N, float cutoff, float * coef)
Generate N coefficients for a low-pass FIR filter.
Parameters:
N Number of coefficients to produce, must be an even number
cutoff Frequency on the w scale (range: 0 to 1)
coef Pointer to the array to hold the coefficients (float[N])
Returns:
0 if all ok
Definition at line 46 of file fir_lpf.cc.
References fir_lpf_gen_gauss().
Referenced by bitshark_auto_tune(), and bitshark_auto_tune2().