Starburst: util/getopt.cc File Reference
util/getopt.cc File Reference
#include <stdio.h>
#include "getopt.h"
#include <string.h>
Defines
#define _NO_PROTO
#define const
#define GETOPT_INTERFACE_VERSION 2
#define _(msgid) (msgid)
#define getenv(...) NULL
#define SWAP_FLAGS(ch1, ch2)
#define NONOPTION_P (argv[optind][0] != '-' || argv[optind][1] == '\0')
Enumerations
enum { REQUIRE_ORDER, PERMUTE, RETURN_IN_ORDER }
Functions
static char * my_index (const char *str, int chr)
static void exchange (char **argv)
static const char * _getopt_initialize (int argc, char *const *argv, const char *optstring)
int _getopt_internal (int argc, char *const *argv, const char *optstring, const struct option *longopts, int *longind, int long_only)
int getopt (int argc, char *const *argv, const char *optstring)
int getopt_long (int argc, char *const *argv, const char *options, const struct option *long_options, int *opt_index)
int getopt_long_only (int argc, char *const *argv, const char *options, const struct option *long_options, int *opt_index)
Variables
char * optarg
int optind = 1
int __getopt_initialized
static char * nextchar
int opterr = 1
int optopt = '?'
static enum { ... } ordering
static char * posixly_correct
static int first_nonopt
static int last_nonopt
Define Documentation
#define _ (msgid) (msgid)
Definition at line 85 of file getopt.cc.
Referenced by _getopt_internal().
#define _NO_PROTO
Definition at line 27 of file getopt.cc.
#define const
Definition at line 38 of file getopt.cc.
#define getenv (...) NULL
Definition at line 214 of file getopt.cc.
Referenced by _getopt_initialize().
#define GETOPT_INTERFACE_VERSION 2
Definition at line 52 of file getopt.cc.
#define NONOPTION_P (argv[optind][0] != '-' || argv[optind][1] == '\0')
Referenced by _getopt_internal().
#define SWAP_FLAGS (ch1, ch2)
Definition at line 281 of file getopt.cc.
Referenced by exchange().
Enumeration Type Documentation
anonymous enum
Enumerator:
REQUIRE_ORDER
PERMUTE
RETURN_IN_ORDER
Definition at line 186 of file getopt.cc.
Function Documentation
static const char* _getopt_initialize (int argc, char *const * argv, const char * optstring) [static]
Definition at line 380 of file getopt.cc.
References first_nonopt, getenv, last_nonopt, malloc(), nextchar, optind, ordering, PERMUTE, posixly_correct, REQUIRE_ORDER, and RETURN_IN_ORDER.
Referenced by _getopt_internal().
int _getopt_internal (int argc, char *const * argv, const char * optstring, const struct option * longopts, int * longind, int long_only)
Definition at line 498 of file getopt.cc.
References _, __getopt_initialized, _getopt_initialize(), exchange(), first_nonopt, option::flag, free(), option::has_arg, last_nonopt, my_index(), option::name, nextchar, NONOPTION_P, optarg, opterr, optind, optopt, ordering, PERMUTE, posixly_correct, REQUIRE_ORDER, and option::val.
Referenced by getopt(), getopt_long(), and getopt_long_only().
static void exchange (char ** argv) [static]
Definition at line 297 of file getopt.cc.
References first_nonopt, last_nonopt, malloc(), optind, and SWAP_FLAGS.
Referenced by _getopt_internal().
int getopt (int argc, char *const * argv, const char * optstring)
Definition at line 1151 of file getopt.cc.
References _getopt_internal().
int getopt_long (int argc, char *const * argv, const char * options, const struct option * long_options, int * opt_index)
Definition at line 1159 of file getopt.cc.
References _getopt_internal().
int getopt_long_only (int argc, char *const * argv, const char * options, const struct option * long_options, int * opt_index)
Definition at line 1169 of file getopt.cc.
References _getopt_internal().
static char* my_index (const char * str, int chr) [static]
Definition at line 217 of file getopt.cc.
Referenced by _getopt_internal().
Variable Documentation
int __getopt_initialized
Definition at line 135 of file getopt.cc.
Referenced by _getopt_internal().
int first_nonopt [static]
Definition at line 248 of file getopt.cc.
Referenced by _getopt_initialize(), _getopt_internal(), and exchange().
int last_nonopt [static]
Definition at line 249 of file getopt.cc.
Referenced by _getopt_initialize(), _getopt_internal(), and exchange().
char* nextchar [static]
Definition at line 144 of file getopt.cc.
Referenced by _getopt_initialize(), and _getopt_internal().
char* optarg
Definition at line 114 of file getopt.cc.
Referenced by _getopt_internal().
int opterr = 1
Definition at line 149 of file getopt.cc.
Referenced by _getopt_internal().
int optind = 1
Definition at line 129 of file getopt.cc.
Referenced by _getopt_initialize(), _getopt_internal(), and exchange().
int optopt = '?'
Definition at line 155 of file getopt.cc.
Referenced by _getopt_internal().
enum { ... } ordering [static]
Referenced by _getopt_initialize(), and _getopt_internal().
char* posixly_correct [static]
Definition at line 192 of file getopt.cc.
Referenced by _getopt_initialize(), and _getopt_internal().