Starburst: Daemons
Daemons
Files
file DefaultTaskDaemon.cc
Daemon for communication and synchronization in the SoC.
file DumpStatsDaemon.cc
A daemon to print process statistics every time interval.
file MallocDaemon.cc
A daemon to handle all malloc (and friends) requests in predictable order, thread-safe.
file ProfilerDaemon.cc
MicroBlaze profiling daemon.
file ShutdownDaemon.cc
Implementation of a gracefull shutdown daemon.
file TaskDaemon.cc
Default implementation of the user specific task daemon.
file TimerDaemon.cc
Daemon to handle all timer calls.
file daemons.h
All daemon definitions.
Functions
void * mainProc (void *arg)
Process entry point of main().
void * InitTaskDaemon (void *kernel_param)
Initializes the task daemon.
void * DefaultTaskDaemon (void *arg)
The default implementation of the task daemon.
int StartDumpStatsDaemon (int interval, void *(*main)(void *), void(*tdstats)(void))
Stats the DumpStatsDaemon().
int StartMallocDaemon ()
Starts the MallocDaemon().
int SetupProfilerDaemon (pid_t &pid, prf_mb_snapshot_t **snapshots)
Starts the profiler daemon.
void PrintProfilerOutput (prf_mb_snapshot_t *snapshots, bool full)
Prints profiling information as gathered by the ProfilingDaemon()
int StartShutdownDaemon ()
Starts the ShutdownDaemon to gracefully shutdown the kernel.
void * TaskDaemon (void *arg)
The task daemon on the master processor.
int StartTimerDaemon ()
Starts the timer daemon.
Function Documentation
void* DefaultTaskDaemon (void * arg)
The default implementation of the task daemon.
In a loop, it cleans up zombie processes, polls for commands of local processes and polls for commands of remote processes.
It will Yield() when there is nothing more to do.
Parameters:
arg unused
Returns:
never, but when it does, it can be assumed to be very critical and a reason for the kernel to panic
Definition at line 923 of file DefaultTaskDaemon.cc.
References ASSERT, tdcmd_local_t::busy_proc, tdcmd_t::cmd, cmd, tdcmd_local_t::cmd, DEBUGH, DEBUGL, ESUCCESS, FinishForwardedRequest(), ForwardRequest(), GarbageCollect(), GetHook(), GetProcID(), tdcmd_local_t::have_cmd, HOOK_TASKDAEMON, kill(), MailPeek(), MAX_PROCESSES, pid, tdcmd_t::proc, PROC_ASYNC, PROC_IDLE, PROC_SYNC, ProcessRequest(), tdcmd_t::res, SIGCONT, StatsCount(), TD_MAX_U_PROCESSES, TDCMD_NONE, tdr, TDS_FORWARD, TDS_LOCAL, TDS_REMOTE, and Yield().
Referenced by InitTaskDaemon().
void* InitTaskDaemon (void * kernel_param)
Initializes the task daemon.
It performs the following tasks: it initializes the command FIFO in the FIFO memory; the FIFO will be assigned to channel 0; depending on kernel_param, another core is notified of our successful boot; and finally it will call main() when running on core 0 and start the DefaultTaskDaemon() afterwards (when main() returns zero).
Parameters:
kernel_param the parameter that was given to the kernel itself when calling main(int,char**)
Returns:
The result of DefaultTaskDaemon().
Definition at line 300 of file DefaultTaskDaemon.cc.
References __boot_funs, kernel_boot_param_t::arg, kernel_boot_param_t::cores, DEBUGH, DEBUGL, DefaultTaskDaemon(), ENABLE_STATS_DAEMON, ESUCCESS, fmalloc(), GetProcID(), HOOK_CORES, HOOK_TASKDAEMON, InitMail, lCreateProcess(), lmalloc, lStartProcess(), tdcmd_local_t::m, MailWrite(), MAIN_DEFAULT_STACK, mainProc(), kernel_boot_param_t::notify_booted, OS_SOC, PROC_DEFAULT_TIMESLICE, RegisterHook(), SetOSState, StartDumpStatsDaemon(), StartMallocDaemon(), StatsDump(), StatsInit(), TaskDaemon(), TD_MAX_U_PROCESSES, TDCMD_NONE, and tdr.
Referenced by kStartTaskDaemon().
void* mainProc (void * arg)
Process entry point of main().
main() will get argv from the static _argv variable.
Only started on processor 0 by the task daemon.
Parameters:
arg not used
Returns:
the result of main()
Definition at line 247 of file DefaultTaskDaemon.cc.
References __fini(), __init(), _heap_end, ClearDMemAccess, DEBUGH, DumpDMemAccess, dvi_init(), main, TraceDumpAll(), and TraceLog().
Referenced by InitTaskDaemon().
void PrintProfilerOutput (prf_mb_snapshot_t * snapshots, bool full)
Prints profiling information as gathered by the ProfilingDaemon()
Parameters:
snapshots the pointer to the memory as malloc()ed by SetProfilingDaemon()
full set to true to print all profiling information instead of just a summary
Definition at line 103 of file ProfilerDaemon.cc.
References GetProcID(), prf_mb_dump(), prf_mb_dump_list(), PROFILER_SNAPSHOTS, and prf_mb_snapshot_t::tv.
int SetupProfilerDaemon (pid_t & pid, prf_mb_snapshot_t ** snapshots)
Starts the profiler daemon.
Parameters:
pid when the daemon is started, the process id of the daemon is written to pid
snapshots a pointer to where the address of the snapshots will be written to (must be free()ed afterwards by caller)
Returns:
an errno
Definition at line 67 of file ProfilerDaemon.cc.
References ESUCCESS, lAllocChannels(), lAssignChannel(), lCreateProcess(), lDestroyProcess(), lfree, lmalloc, lStartProcess(), PROFILER_SNAPSHOTS, and ProfilerDaemon().
int StartDumpStatsDaemon (int interval, void *(*)(void *) main, void(*)(void) tdstats)
Stats the DumpStatsDaemon().
Parameters:
interval interval process statistics will be printed in seconds
main start address of a process, statistics will be printed as long as this process runs (usually main())
tdstats function to execute when this daemon terminates (usually used to dump statistics of the task daemon)
Returns:
0 when the daemon has been started successfully, an errno otherwise.
Definition at line 138 of file DumpStatsDaemon.cc.
References a, DAEMON_DEFAULT_STACK, DAEMON_DEFAULT_TIMESLICE, DumpStatsDaemon(), InitMail, dsd_t::interval, lCreateProcess(), lStartProcess(), MailRead(), dsd_t::main, main, dsd_t::started, and dsd_t::tdstats.
Referenced by InitTaskDaemon().
int StartMallocDaemon ()
Starts the MallocDaemon().
By using the MallocDaemon, all requests to the processor heap are redirected to that daemon and are handled sequentially. Therefore, no locks are used and it is safe to malloc() from multiple processes simultaneously.
It is safe to start the daemon at any point in time, as long there are no malloc()s currently in process. It is unsafe to kill the daemon while running. Use StopMallocDaemon() for that.
Returns:
0 on success, otherwise an errno
Definition at line 152 of file MallocDaemon.cc.
References ASSERT, md_t::b, DAEMON_DEFAULT_STACK, DAEMON_DEFAULT_TIMESLICE, HOOK_MALLOC, InitMail, lcalloc, lCreateProcess(), lDestroyProcess(), lSetProcessFlags(), lStartProcess(), md_t::m, MailRead(), MALLOC_PID, MallocDaemon(), MAX_U_PROCESSES, pid, PROC_FLAG_JOINABLE, and RegisterHook().
Referenced by InitTaskDaemon().
int StartShutdownDaemon ()
Starts the ShutdownDaemon to gracefully shutdown the kernel.
Returns:
0 when the daemon has been started and shutdown is pending, an errno when called from another process than the task daemon, never when the daemon could not be started and the system is shutdown immediately.
Definition at line 132 of file ShutdownDaemon.cc.
References DAEMON_DEFAULT_STACK, DAEMON_DEFAULT_TIMESLICE, DEBUG, lCreateProcess(), lStartProcess(), pid, Shutdown(), and ShutdownDaemon().
Referenced by ProcessRequest().
int StartTimerDaemon ()
Starts the timer daemon.
Will be called automatically when a timer function requires the daemon.
Returns:
0 on succes, otherwise an errno.
Definition at line 323 of file TimerDaemon.cc.
References CreateProcess(), DAEMON_DEFAULT_STACK, DAEMON_DEFAULT_TIMESLICE, DestroyProcess(), ESUCCESS, InitMail, MailRead(), pid, StartProcess(), and TimerDaemon().
Referenced by timer_create().
void* TaskDaemon (void * arg)
The task daemon on the master processor.
By default, it will call DefaultMulticoreSetup() and returns. Override when neccessary.
Definition at line 16 of file TaskDaemon.cc.
References DEFAULT_P, DefaultMulticoreSetup(), and GetProcID().
Referenced by InitTaskDaemon().