var hierarchy =
[
    [ "__attribute__", "struct____attribute____.html", null ],
    [ "_devinfo_t", "struct__devinfo__t.html", null ],
    [ "_fd2q_t", "struct__fd2q__t.html", null ],
    [ "_lck_daemon_lock_t", "struct__lck__daemon__lock__t.html", null ],
    [ "_lck_my_lock_t", "struct__lck__my__lock__t.html", null ],
    [ "_le_t", "struct__le__t.html", null ],
    [ "_linfs_t", "struct__linfs__t.html", null ],
    [ "_noc_addr_t", "union__noc__addr__t.html", null ],
    [ "_prf_mb_t", "struct__prf__mb__t.html", null ],
    [ "_prf_mem_t", "struct__prf__mem__t.html", null ],
    [ "_proc_table_t", "struct__proc__table__t.html", null ],
    [ "_timer_event_t", "struct__timer__event__t.html", null ],
    [ "Accelerator", "classAccelerator.html", [
      [ "Cfifo_sink< Type >", "classCfifo__sink.html", null ],
      [ "Cfifo_source< Type >", "classCfifo__source.html", null ],
      [ "CordicMix", "classCordicMix.html", null ],
      [ "CordicQuad", "classCordicQuad.html", null ],
      [ "FirFilter", "classFirFilter.html", null ],
      [ "Reader", "classReader.html", [
        [ "CreditToAddr", "classCreditToAddr.html", null ]
      ] ],
      [ "Writer", "classWriter.html", [
        [ "Core", "classCore.html", null ],
        [ "RingDma", "classRingDma.html", null ]
      ] ]
    ] ],
    [ "accelerator_t", "unionaccelerator__t.html", null ],
    [ "accList", "structaccList.html", null ],
    [ "AccList", "classAccList.html", null ],
    [ "auto_ret< T, ok >", "classauto__ret.html", null ],
    [ "PMC_NS::Backend< T, B >", "classPMC__NS_1_1Backend.html", [
      [ "PMC_NS::Var< T, B >", "classPMC__NS_1_1Var.html", [
        [ "mfifo_t< T, FIFO_READERS, FIFO_SIZE_BITS, B >::elem_t", "classmfifo__t_1_1elem__t.html", null ]
      ] ]
    ] ],
    [ "bitshark_ctrl_dev_t", "structbitshark__ctrl__dev__t.html", null ],
    [ "bitshark_dev_t", "structbitshark__dev__t.html", null ],
    [ "CFifo< T, access >", "classCFifo.html", null ],
    [ "CFifo< T >", "classCFifo.html", [
      [ "CFifo< T, CFifo<>::r >", "classCFifo_3_01T_00_01CFifo_3_4_1_1r_01_4.html", null ],
      [ "CFifo< T, CFifo<>::w >", "classCFifo_3_01T_00_01CFifo_3_4_1_1w_01_4.html", null ]
    ] ],
    [ "CFifoPtr< T >", "classCFifoPtr.html", null ],
    [ "CFifoPtr_ref< T >", "structCFifoPtr__ref.html", null ],
    [ "channel_t", "structchannel__t.html", null ],
    [ "clean_type< T >", "structclean__type.html", null ],
    [ "clean_type< const T & >", "structclean__type_3_01const_01T_01_6_01_4.html", null ],
    [ "clean_type< const T * >", "structclean__type_3_01const_01T_01_5_01_4.html", null ],
    [ "clean_type< const T >", "structclean__type_3_01const_01T_01_4.html", null ],
    [ "clean_type< const volatile T & >", "structclean__type_3_01const_01volatile_01T_01_6_01_4.html", null ],
    [ "clean_type< const volatile T * >", "structclean__type_3_01const_01volatile_01T_01_5_01_4.html", null ],
    [ "clean_type< const volatile T >", "structclean__type_3_01const_01volatile_01T_01_4.html", null ],
    [ "clean_type< T & >", "structclean__type_3_01T_01_6_01_4.html", null ],
    [ "clean_type< volatile T & >", "structclean__type_3_01volatile_01T_01_6_01_4.html", null ],
    [ "clean_type< volatile T * >", "structclean__type_3_01volatile_01T_01_5_01_4.html", null ],
    [ "clean_type< volatile T >", "structclean__type_3_01volatile_01T_01_4.html", null ],
    [ "complex_t", "structcomplex__t.html", null ],
    [ "ConArbiter", "structConArbiter.html", null ],
    [ "coordinate_t", "structcoordinate__t.html", null ],
    [ "cordic_regmap_t", "structcordic__regmap__t.html", null ],
    [ "credit2addr_regmap_t", "structcredit2addr__regmap__t.html", null ],
    [ "delete_by_ref", "structdelete__by__ref.html", null ],
    [ "syncevent_t< N >::dest_t", "structsyncevent__t_1_1dest__t.html", null ],
    [ "DIR", "structDIR.html", null ],
    [ "dirent", "structdirent.html", null ],
    [ "dsd_t", "structdsd__t.html", null ],
    [ "dsdh_t", "structdsdh__t.html", null ],
    [ "dvi_color", "classdvi__color.html", null ],
    [ "dvi_frame", "uniondvi__frame.html", null ],
    [ "dvi_line", "structdvi__line.html", null ],
    [ "dvi_pixel_", "uniondvi__pixel__.html", null ],
    [ "dvi_screen", "classdvi__screen.html", null ],
    [ "PMC_NS::Error", "classPMC__NS_1_1Error.html", null ],
    [ "Fifo", "structFifo.html", null ],
    [ "Fifo_admin", "structFifo__admin.html", null ],
    [ "FIFO_ARRAY", "structFIFO__ARRAY.html", null ],
    [ "FifoEP", "structFifoEP.html", null ],
    [ "firfilt_regmap_t", "structfirfilt__regmap__t.html", null ],
    [ "fixed_t< I, P, S, rounding >", "classfixed__t.html", null ],
    [ "fontchar_t", "structfontchar__t.html", null ],
    [ "graphix_status_t", "uniongraphix__status__t.html", null ],
    [ "PMC_NS::VarPtrArray< L, T, B >::GroupScopeRO", "classPMC__NS_1_1VarPtrArray_1_1GroupScopeRO.html", null ],
    [ "PMC_NS::VarPtrArray< L, T, B >::GroupScopeX", "classPMC__NS_1_1VarPtrArray_1_1GroupScopeX.html", null ],
    [ "HNTAG", "structHNTAG.html", null ],
    [ "HTAG", "structHTAG.html", null ],
    [ "Info_App_s", "structInfo__App__s.html", null ],
    [ "Info_CB", "structInfo__CB.html", null ],
    [ "Info_CBOverlap", "structInfo__CBOverlap.html", null ],
    [ "Info_CBRing", "structInfo__CBRing.html", null ],
    [ "Info_CBRingOpt", "structInfo__CBRingOpt.html", null ],
    [ "Info_CBSliding", "structInfo__CBSliding.html", null ],
    [ "Info_FIFO", "structInfo__FIFO.html", null ],
    [ "Info_FIFO_remote", "structInfo__FIFO__remote.html", null ],
    [ "Info_Task", "structInfo__Task.html", null ],
    [ "Info_Window", "structInfo__Window.html", null ],
    [ "iq_t", "unioniq__t.html", null ],
    [ "iqu_t", "unioniqu__t.html", null ],
    [ "is_same< T1, T2 >", "structis__same.html", null ],
    [ "is_same< T, T >", "structis__same_3_01T_00_01T_01_4.html", null ],
    [ "is_type_ptr", "classis__type__ptr.html", null ],
    [ "is_type_ref< T >", "structis__type__ref.html", null ],
    [ "is_type_ref< T & >", "structis__type__ref_3_01T_01_6_01_4.html", null ],
    [ "IsConst< T >", "classIsConst.html", null ],
    [ "IsConst< const T >", "classIsConst_3_01const_01T_01_4.html", null ],
    [ "kernel_boot_param_t", "structkernel__boot__param__t.html", null ],
    [ "kernel_context_t", "structkernel__context__t.html", null ],
    [ "lck_admin_t", "unionlck__admin__t.html", null ],
    [ "lck_daemon_admin_t", "structlck__daemon__admin__t.html", null ],
    [ "lck_daemon_locks_t", "structlck__daemon__locks__t.html", null ],
    [ "lck_my_locks_t", "structlck__my__locks__t.html", null ],
    [ "line_t", "structline__t.html", null ],
    [ "linfs_queues_t", "structlinfs__queues__t.html", null ],
    [ "linfs_res_t", "structlinfs__res__t.html", null ],
    [ "PMC_NS::LocalAlloc", "classPMC__NS_1_1LocalAlloc.html", [
      [ "PMC_NS::LocalBackend< T >", "classPMC__NS_1_1LocalBackend.html", null ]
    ] ],
    [ "LocalBuffer", "structLocalBuffer.html", null ],
    [ "PMC_NS::Location< T >", "classPMC__NS_1_1Location.html", [
      [ "PMC_NS::MultiLocation< T >", "classPMC__NS_1_1MultiLocation.html", [
        [ "PMC_NS::LocalBackend< T >", "classPMC__NS_1_1LocalBackend.html", null ],
        [ "PMC_NS::MCBackend< T >", "classPMC__NS_1_1MCBackend.html", null ],
        [ "PMC_NS::RCBackend< T >", "classPMC__NS_1_1RCBackend.html", null ],
        [ "PMC_NS::SCBackend< T >", "classPMC__NS_1_1SCBackend.html", null ],
        [ "PMC_NS::SPMBackend< T >", "classPMC__NS_1_1SPMBackend.html", null ]
      ] ],
      [ "PMC_NS::SAMultiLocation< T >", "classPMC__NS_1_1SAMultiLocation.html", [
        [ "PMC_NS::SASPMBackend< T, C >", "classPMC__NS_1_1SASPMBackend.html", null ]
      ] ]
    ] ],
    [ "lt_t", "structlt__t.html", null ],
    [ "Mail", "structMail.html", null ],
    [ "malloc_buffer_t", "structmalloc__buffer__t.html", null ],
    [ "map_app_layout_t", "structmap__app__layout__t.html", null ],
    [ "map_application_t", "structmap__application__t.html", null ],
    [ "map_core_t", "structmap__core__t.html", null ],
    [ "map_hardware_t", "structmap__hardware__t.html", null ],
    [ "map_impl_fifo_t", "structmap__impl__fifo__t.html", null ],
    [ "map_impl_layout_t", "structmap__impl__layout__t.html", null ],
    [ "map_impl_link_t", "structmap__impl__link__t.html", null ],
    [ "map_impl_mailbox_t", "structmap__impl__mailbox__t.html", null ],
    [ "map_impl_memory_t", "structmap__impl__memory__t.html", null ],
    [ "map_impl_process_t", "structmap__impl__process__t.html", null ],
    [ "map_implementation_t", "structmap__implementation__t.html", null ],
    [ "map_port_t", "structmap__port__t.html", null ],
    [ "map_task_layout_t", "structmap__task__layout__t.html", null ],
    [ "map_task_t", "structmap__task__t.html", null ],
    [ "mc_check_t", "structmc__check__t.html", null ],
    [ "mc_var< T >", "structmc__var.html", [
      [ "mc_prim< T >", "structmc__prim.html", null ]
    ] ],
    [ "mc_var< T * >", "structmc__var.html", [
      [ "mc_prim< T * >", "structmc__prim.html", [
        [ "mc_ptr< T >", "structmc__ptr.html", null ]
      ] ]
    ] ],
    [ "md_t", "structmd__t.html", null ],
    [ "PMC_NS::MemPool", "classPMC__NS_1_1MemPool.html", [
      [ "PMC_NS::FifoMemPool< Tsa, N, B >", "classPMC__NS_1_1FifoMemPool.html", null ],
      [ "PMC_NS::SharedMemPool", "classPMC__NS_1_1SharedMemPool.html", null ]
    ] ],
    [ "mfifo_t< T, FIFO_READERS, FIFO_SIZE_BITS, B >", "classmfifo__t.html", null ],
    [ "PMC_NS::VarPtrArray< L, T, B >::GroupScopeRO::NakedData", "structPMC__NS_1_1VarPtrArray_1_1GroupScopeRO_1_1NakedData.html", null ],
    [ "PMC_NS::VarPtrArray< L, T, B >::GroupScopeX::NakedData", "structPMC__NS_1_1VarPtrArray_1_1GroupScopeX_1_1NakedData.html", null ],
    [ "PMC_NS::NoAlloc", "classPMC__NS_1_1NoAlloc.html", [
      [ "PMC_NS::RCBackend< T >", "classPMC__NS_1_1RCBackend.html", null ]
    ] ],
    [ "PMC_NS::NoInit< T >", "structPMC__NS_1_1NoInit.html", null ],
    [ "option", "structoption.html", null ],
    [ "pipe_admin_t", "structpipe__admin__t.html", null ],
    [ "pipe_t", "structpipe__t.html", null ],
    [ "pix_t", "unionpix__t.html", null ],
    [ "PlacementDelete< T, Tref >", "classPlacementDelete.html", null ],
    [ "PlacementDelete< T, void >", "classPlacementDelete_3_01T_00_01void_01_4.html", null ],
    [ "poly_t< N >", "classpoly__t.html", null ],
    [ "polygon_t", "structpolygon__t.html", null ],
    [ "prf_mb_snapshot_t", "structprf__mb__snapshot__t.html", null ],
    [ "proc_context_t", "structproc__context__t.html", null ],
    [ "proc_local_t", "structproc__local__t.html", null ],
    [ "proc_stats_t", "structproc__stats__t.html", null ],
    [ "ProcessState_t", "unionProcessState__t.html", null ],
    [ "pthread_attr_t", "structpthread__attr__t.html", null ],
    [ "pthread_barrier_t", "structpthread__barrier__t.html", null ],
    [ "pthread_barrierattr_t", "structpthread__barrierattr__t.html", null ],
    [ "pthread_cond_t", "structpthread__cond__t.html", null ],
    [ "pthread_condattr_t", "structpthread__condattr__t.html", null ],
    [ "pthread_key_admin_t", "structpthread__key__admin__t.html", null ],
    [ "pthread_mutex_t", "structpthread__mutex__t.html", null ],
    [ "pthread_mutexattr_t", "structpthread__mutexattr__t.html", null ],
    [ "pthread_sch_t", "structpthread__sch__t.html", null ],
    [ "r_sel_out_t", "structr__sel__out__t.html", null ],
    [ "r_sel_out_union_t", "unionr__sel__out__union__t.html", null ],
    [ "ramfile_entry_t", "structramfile__entry__t.html", null ],
    [ "rate_frac_t", "unionrate__frac__t.html", null ],
    [ "RFifo< T >", "classRFifo.html", null ],
    [ "RingBufferOptStruct", "structRingBufferOptStruct.html", null ],
    [ "RingBufferStruct", "structRingBufferStruct.html", null ],
    [ "ringratecontrol_dev_t", "structringratecontrol__dev__t.html", null ],
    [ "ringshell_ctrl_dev_t", "structringshell__ctrl__dev__t.html", null ],
    [ "rusage", "structrusage.html", null ],
    [ "PMC_NS::SACallback", "classPMC__NS_1_1SACallback.html", null ],
    [ "sch_t", "structsch__t.html", null ],
    [ "PMC_NS::Scope< V, T >", "classPMC__NS_1_1Scope.html", null ],
    [ "PMC_NS::Scope< V >", "classPMC__NS_1_1Scope.html", [
      [ "PMC_NS::ScopeX< V >", "classPMC__NS_1_1ScopeX.html", null ]
    ] ],
    [ "PMC_NS::Scope< V, const V::type >", "classPMC__NS_1_1Scope.html", [
      [ "PMC_NS::ScopeRO< V >", "classPMC__NS_1_1ScopeRO.html", null ]
    ] ],
    [ "PMC_NS::Scope< V, T >::ScopePtr", "structPMC__NS_1_1Scope_1_1ScopePtr.html", null ],
    [ "PMC_NS::SharedAlloc", "classPMC__NS_1_1SharedAlloc.html", [
      [ "PMC_NS::MCBackend< T >", "classPMC__NS_1_1MCBackend.html", null ],
      [ "PMC_NS::SASPMBackend< T, C >", "classPMC__NS_1_1SASPMBackend.html", null ],
      [ "PMC_NS::SCBackend< T >", "classPMC__NS_1_1SCBackend.html", null ],
      [ "PMC_NS::SPMBackend< T >", "classPMC__NS_1_1SPMBackend.html", null ]
    ] ],
    [ "sigaction", "structsigaction.html", null ],
    [ "sigevent", "structsigevent.html", null ],
    [ "siginfo_t", "structsiginfo__t.html", null ],
    [ "SignedType", "structSignedType.html", null ],
    [ "sigval", "unionsigval.html", null ],
    [ "SmallestInt< bits, E >", "structSmallestInt.html", null ],
    [ "SmallestInt< bits, TypeExpr<(bits >=0 &&bits< 8)> >", "structSmallestInt_3_01bits_00_01TypeExpr_3_07bits_01_4_0A0_01_6_6bits_3_018_08_4_01_4.html", null ],
    [ "SmallestInt< bits, TypeExpr<(bits >=16 &&bits< 32)> >", "structSmallestInt_3_01bits_00_01TypeExpr_3_07bits_01_4_0A16_01_6_6bits_3_0132_08_4_01_4.html", null ],
    [ "SmallestInt< bits, TypeExpr<(bits >=32 &&bits< 64)> >", "structSmallestInt_3_01bits_00_01TypeExpr_3_07bits_01_4_0A32_01_6_6bits_3_0164_08_4_01_4.html", null ],
    [ "SmallestInt< bits, TypeExpr<(bits >=8 &&bits< 16)> >", "structSmallestInt_3_01bits_00_01TypeExpr_3_07bits_01_4_0A8_01_6_6bits_3_0116_08_4_01_4.html", null ],
    [ "SmallestNum< bits, SignedType >", "structSmallestNum_3_01bits_00_01SignedType_01_4.html", null ],
    [ "SmallestNum< bits, UnsignedType >", "structSmallestNum_3_01bits_00_01UnsignedType_01_4.html", null ],
    [ "SmallestUInt< bits, E >", "structSmallestUInt.html", null ],
    [ "SmallestUInt< bits, TypeExpr<(bits >16 &&bits<=32)> >", "structSmallestUInt_3_01bits_00_01TypeExpr_3_07bits_01_416_01_6_6bits_3_0A32_08_4_01_4.html", null ],
    [ "SmallestUInt< bits, TypeExpr<(bits >32 &&bits<=64)> >", "structSmallestUInt_3_01bits_00_01TypeExpr_3_07bits_01_432_01_6_6bits_3_0A64_08_4_01_4.html", null ],
    [ "SmallestUInt< bits, TypeExpr<(bits >8 &&bits<=16)> >", "structSmallestUInt_3_01bits_00_01TypeExpr_3_07bits_01_48_01_6_6bits_3_0A16_08_4_01_4.html", null ],
    [ "SmallestUInt< bits, TypeExpr<(bits >=0 &&bits<=8)> >", "structSmallestUInt_3_01bits_00_01TypeExpr_3_07bits_01_4_0A0_01_6_6bits_3_0A8_08_4_01_4.html", null ],
    [ "spi_register_t", "structspi__register__t.html", null ],
    [ "spi_wrapper_t", "unionspi__wrapper__t.html", null ],
    [ "spireg_spicr_t", "unionspireg__spicr__t.html", null ],
    [ "spireg_spidrr_t", "structspireg__spidrr__t.html", null ],
    [ "spireg_spidtr_t", "structspireg__spidtr__t.html", null ],
    [ "spireg_spisr_t", "structspireg__spisr__t.html", null ],
    [ "stats_t", "structstats__t.html", null ],
    [ "stopwatch_t", "structstopwatch__t.html", null ],
    [ "subpixel_t", "classsubpixel__t.html", null ],
    [ "sync_event_entry_t", "structsync__event__entry__t.html", null ],
    [ "syncevent_t< N >", "classsyncevent__t.html", null ],
    [ "TArray< T, L >", "classTArray.html", null ],
    [ "TArray< T, 0 >", "classTArray_3_01T_00_010_01_4.html", null ],
    [ "TArray< T, 1 >", "classTArray_3_01T_00_011_01_4.html", null ],
    [ "tdcmd_local_t", "structtdcmd__local__t.html", null ],
    [ "tdcmd_remote_t", "structtdcmd__remote__t.html", null ],
    [ "tdcmd_t", "structtdcmd__t.html", null ],
    [ "TDMATimes", "structTDMATimes.html", null ],
    [ "tds_t", "structtds__t.html", null ],
    [ "termios", "structtermios.html", null ],
    [ "TileArbiter", "structTileArbiter.html", null ],
    [ "trace_t", "structtrace__t.html", null ],
    [ "uartlite_t", "structuartlite__t.html", null ],
    [ "UnsignedType", "structUnsignedType.html", null ],
    [ "utimbuf", "structutimbuf.html", null ],
    [ "utsname", "structutsname.html", null ],
    [ "PMC_NS::VarPtrArray< L, T, B >", "classPMC__NS_1_1VarPtrArray.html", null ],
    [ "WFifo< T >", "classWFifo.html", null ],
    [ "WorkQueue< T, W >", "classWorkQueue.html", null ]
];