Starburst: kernel/hooks.cc File Reference
kernel/hooks.cc File Reference
Support for hooks into specific system calls.
#include <sys/api.h>
Functions
int RegisterHook (int hook, void *ptr, bool once)
Associates the given pointer to the specified hook.
void * GetHook (int hook)
Returns the pointer associated with the specified hook.
int UnregisterHook (int hook)
Unregister a specific hook.
Detailed Description
Support for hooks into specific system calls.
Definition in file hooks.cc.
Function Documentation
void* GetHook (int hook)
Returns the pointer associated with the specified hook.
Parameters:
hook the hook to get the pointer of
Returns:
The pointer. When NULL, the hook was not set.
Definition at line 33 of file hooks.cc.
References GetHookTable(), and HOOKS.
Referenced by calloc(), DefaultTaskDaemon(), free(), freeAll(), GetIssueSlot(), mown(), omalloc(), orealloc(), StopMallocDaemon(), sysconf(), timer_create(), TraceDump(), TraceLog_(), TracePhaseChange(), and TraceRedir().
int RegisterHook (int hook, void * ptr, bool once)
Associates the given pointer to the specified hook.
Parameters:
hook the hook to register the pointer to
ptr the pointer to register, cannot be NULL
once when true, the call will fail with EAGAIN when the hook was already set
Returns:
0 on success, otherwise an errno
Definition at line 14 of file hooks.cc.
References ESUCCESS, GetHookTable(), and HOOKS.
Referenced by dBootKernels(), InitTaskDaemon(), kTraceInit(), pthread_local_init(), StartMallocDaemon(), and TimerDaemon().
int UnregisterHook (int hook)
Unregister a specific hook.
Parameters:
hook the hook to unregister
Returns:
0 on success, otherwise an errno
Definition at line 45 of file hooks.cc.
References ESUCCESS, GetHookTable(), and HOOKS.
Referenced by MallocDaemon(), and StopMallocDaemon().