Starburst: include/sys/hooks.h File Reference
include/sys/hooks.h File Reference
Hooks in kernel, to get specific call-backs or information.
Defines
#define HOOKS 6
Number hooks.
#define HOOK_SCHEDULER 0
The hook is an address to the pthread_sch_t structure with per-process scheduling information.
#define HOOK_MALLOC 1
The hook is an address to a malloc_buffer_t structure with the communication infrastructure between processes and the MallocDaemon().
#define HOOK_TIMER 2
The hook is an address to the start of the list of timers in a timer_event_t structure for the TimerDaemon().
#define HOOK_TASKDAEMON 3
The hook is an address to the process-to-task-daemon command slots.
#define HOOK_CORES 4
The hook is the number of running cores in the SoC.
#define HOOK_TRACE 5
A pointer to a trace_t for tracing execution times.
Typedefs
typedef void * hook_t
The hook-table type.
Functions
int RegisterHook (int hook, void *ptr, bool once=false)
Associates the given pointer to the specified hook.
void * GetHook (int hook)
Returns the pointer associated with the specified hook.
int UnregisterHook (int hook)
Unregister a specific hook.
Detailed Description
Hooks in kernel, to get specific call-backs or information.
The usage of the hooks are hook-specific.
Definition in file hooks.h.
Define Documentation
#define HOOK_CORES 4
The hook is the number of running cores in the SoC.
Set at boot time, to be retrieved using sysconf().
Definition at line 36 of file hooks.h.
Referenced by dBootKernels(), InitTaskDaemon(), and sysconf().
#define HOOK_MALLOC 1
The hook is an address to a malloc_buffer_t structure with the communication infrastructure between processes and the MallocDaemon().
When NULL, no daemon is running (and malloc()s are unsafe).
Definition at line 21 of file hooks.h.
Referenced by calloc(), free(), freeAll(), MallocDaemon(), mown(), omalloc(), orealloc(), StartMallocDaemon(), and StopMallocDaemon().
#define HOOK_SCHEDULER 0
The hook is an address to the pthread_sch_t structure with per-process scheduling information.
Used by the kernel.
Definition at line 16 of file hooks.h.
Referenced by kInitKernel(), and pthread_local_init().
#define HOOK_TASKDAEMON 3
The hook is an address to the process-to-task-daemon command slots.
Set and used by the DefaultTaskDaemon().
Definition at line 31 of file hooks.h.
Referenced by DefaultTaskDaemon(), GetIssueSlot(), and InitTaskDaemon().
#define HOOK_TIMER 2
The hook is an address to the start of the list of timers in a timer_event_t structure for the TimerDaemon().
Set and used by the TimerDaemon().
Definition at line 26 of file hooks.h.
Referenced by timer_create(), and TimerDaemon().
#define HOOK_TRACE 5
A pointer to a trace_t for tracing execution times.
Set and used by kTraceInit() and friends.
Definition at line 41 of file hooks.h.
Referenced by kTraceInit(), TraceDump(), TraceLog_(), TracePhaseChange(), and TraceRedir().
#define HOOKS 6
Number hooks.
Definition at line 11 of file hooks.h.
Referenced by GetHook(), kInitKernel(), RegisterHook(), and UnregisterHook().
Typedef Documentation
typedef void* hook_t
The hook-table type.
Definition at line 44 of file hooks.h.
Function Documentation
void* GetHook (int hook)
Returns the pointer associated with the specified hook.
Parameters:
hook the hook to get the pointer of
Returns:
The pointer. When NULL, the hook was not set.
Definition at line 33 of file hooks.cc.
References GetHookTable(), and HOOKS.
Referenced by calloc(), DefaultTaskDaemon(), free(), freeAll(), GetIssueSlot(), mown(), omalloc(), orealloc(), StopMallocDaemon(), sysconf(), timer_create(), TraceDump(), TraceLog_(), TracePhaseChange(), and TraceRedir().
int RegisterHook (int hook, void * ptr, bool once)
Associates the given pointer to the specified hook.
Parameters:
hook the hook to register the pointer to
ptr the pointer to register, cannot be NULL
once when true, the call will fail with EAGAIN when the hook was already set
Returns:
0 on success, otherwise an errno
Definition at line 14 of file hooks.cc.
References ESUCCESS, GetHookTable(), and HOOKS.
Referenced by dBootKernels(), InitTaskDaemon(), kTraceInit(), pthread_local_init(), StartMallocDaemon(), and TimerDaemon().
int UnregisterHook (int hook)
Unregister a specific hook.
Parameters:
hook the hook to unregister
Returns:
0 on success, otherwise an errno
Definition at line 45 of file hooks.cc.
References ESUCCESS, GetHookTable(), and HOOKS.
Referenced by MallocDaemon(), and StopMallocDaemon().