Starburst: include/sys/io.h File Reference
include/sys/io.h File Reference
Declaration of all I/O function, types and address macros.
#include <sys/helix_config.h>
#include <sys/api.h>
#include <stdint.h>
Data Structures
union dvi_pixel_
class subpixel_t
class dvi_color
struct dvi_line
union dvi_frame
union _noc_addr_t
Defines
#define IO_TIMER 0x00210000
#define IO_TIMER_MASK 0xFFFFFF00
#define IO_TIMER_TCSR0 (IO_TIMER|0x00)
#define IO_TIMER_TLR0 (IO_TIMER|0x04)
#define IO_TIMER_TCR0 (IO_TIMER|0x08)
#define kInitIrq()
#define kClearIrq()
#define IO_UART 0xE0000000
#define IO_UART_MASK 0xFFFFFFF0
#define IO_UART_RX_REG (IO_UART|0x0)
#define IO_UART_TX_REG (IO_UART|0x4)
#define IO_UART_STAT_REG (IO_UART|0x8)
#define IO_UART_CTRL_REG (IO_UART|0xC)
#define _putn(i) _putp((void*)(i))
#define IO_LEDS 0xE0010000
#define IO_LEDS_MASK 0xFFFFFFF0
#define IO_LEDS_VALUE (IO_LEDS|0x0)
#define IO_LEDS_ON (IO_LEDS|0x4)
#define IO_LEDS_OFF (IO_LEDS|0x8)
#define IO_POSLEDS 0xE0020000
#define IO_POSLEDS_MASK 0xFFFFFFF0
#define IO_POSLEDS_VALUE (IO_POSLEDS|0x0)
#define IO_POSLEDS_ON (IO_POSLEDS|0x4)
#define IO_POSLEDS_OFF (IO_POSLEDS|0x8)
#define IO_POSLEDS_N 2
#define IO_POSLEDS_S 3
#define IO_POSLEDS_E 1
#define IO_POSLEDS_W 4
#define IO_POSLEDS_C 0
#define IO_CLOCK 0xE0040000
#define IO_CLOCK_MASK 0xFFFFFFF0
#define IO_CLOCK_REG (IO_CLOCK|0x0)
#define IO_BUTTONS 0xE0030000
#define IO_BUTTONS_MASK 0xFFFFFFF0
#define IO_BUTTONS_STATE (IO_BUTTONS|0x0)
#define IO_BUTTONS_EDGE (IO_BUTTONS|0x0)
#define IO_DVI 0xE0090000
#define IO_DVI_MASK 0xfffffff0
#define IO_DVI_AR (IO_DVI|0x0)
#define IO_DVI_CR (IO_DVI|0x4)
#define IO_DVI_IESR (IO_DVI|0x8)
#define IO_DVI_WIDTH 640
#define IO_DVI_HEIGHT 480
#define PIX_CONST(r, g, b) ((const dvi_pixel){{b,g,r}})
#define MAKE_LOCAL_FIFOMEM_PTR(a) ((void*)((((unsigned int)(a))&(FIFO_MEM_SIZE-1))|FIFO_MEM))
#define MAKE_NOC_FIFOMEM_PTR(a, proc) ((void*)((((unsigned int)(a))&(FIFO_MEM_SIZE-1))|(NOC_ADDR_MAJOR<<(32-NOC_ADDR_MAJOR_WIDTH))|(((proc)&(NOC_ADDR_MAX_PROCS-1))<<(NOC_ADDR_LOCAL_WIDTH+NOC_ADDR_ACC_WIDTH+NOC_ADDR_ACC_CONF_WIDTH))))
#define MAKE_NOC_FSL_PTR(core) ((void*)((unsigned int) MAKE_NOC_FIFOMEM_PTR(0,core)|(1<<(NOC_ADDR_LOCAL_WIDTH+NOC_ADDR_ACC_CONF_WIDTH))))
#define MAKE_NOC_ACCE_PTR(core, acce) ((void*)((unsigned int) MAKE_NOC_FIFOMEM_PTR(0,core)|((((unsigned int)acce+2)&(NOC_ADDR_MAX_ACCS-1))<<(NOC_ADDR_LOCAL_WIDTH+NOC_ADDR_ACC_CONF_WIDTH))))
#define MAKE_NOC_CORE_CONFIG_PTR(a, core) ((void*)((unsigned int) MAKE_NOC_FIFOMEM_PTR(a,core)|(1<<NOC_ADDR_LOCAL_WIDTH)))
#define MAKE_NOC_FSL_CONFIG_PTR(a, core) ((void*)((unsigned int) MAKE_NOC_FIFOMEM_PTR(a,core)|(1<<NOC_ADDR_LOCAL_WIDTH)|(1<<(NOC_ADDR_LOCAL_WIDTH+NOC_ADDR_ACC_CONF_WIDTH))))
#define MAKE_NOC_ACCE_CONFIG_PTR(a, core, acce) ((void*)((unsigned int) MAKE_NOC_FIFOMEM_PTR(a,core)|(1<<NOC_ADDR_LOCAL_WIDTH)|((((unsigned int)acce+2)&(NOC_ADDR_MAX_ACCS-1))<<(NOC_ADDR_LOCAL_WIDTH+NOC_ADDR_ACC_CONF_WIDTH))))
#define io_read(addr, type) (type)(*((volatile type*)(addr)))
#define io_write(addr, type, value) do{ *((volatile type*)(addr))=(type)value; barrier(); }while(0)
#define IO_BITSHARK_BS_UART 0x10000000
#define IO_BITSHARK_GPS_UART 0x10000010
#define IO_BITSHARK_CTRL 0x10001000
#define IO_RINGRATECONTROL 0x10002000
#define IO_RINGMAP_LEN 0xE00B0000
#define IO_RINGMAP 0xE00B0004
Typedefs
typedef union dvi_pixel_ dvi_pixel
typedef union _noc_addr_t noc_addr_t
Functions
void kSetTimer (unsigned int time, unsigned int repeat=0) _NO_THROW __attribute__((section(".text.schedule")))
Sets the local timer to the designated number of clock cycles.
unsigned int kGetTimer () _NO_THROW
Returns the current value of the timer.
void kStopTimer () _NO_THROW
Stops the local timer.
int inbyte () _NO_THROW
Reads one byte from the serial port.
int kbhit () _NO_THROW
Checks whether data is to be read from the serial port.
void outbyte (char ch) _NO_THROW
Writes one byte to the serial port.
void _puts (const char *s) _NO_THROW
Writes given string to the terminal.
void _putp (void *p) _NO_THROW
void led_on (int led) _NO_THROW
Turns on the led with the given number.
void led_off (int led) _NO_THROW
Turns off the led with the given number.
void leds_on (int ledmask) _NO_THROW
Turns on leds corresponding to the masked bits.
void leds_off (int ledmask) _NO_THROW
Turns off leds corresponding to the masked bits.
void leds_value (int leds) _NO_THROW
Controls all leds simultaneously.
void posled_on (int led) _NO_THROW
void posled_off (int led) _NO_THROW
void posleds_on (int ledmask) _NO_THROW
void posleds_off (int ledmask) _NO_THROW
void posleds_value (int leds) _NO_THROW
unsigned int get_clock () _NO_THROW
Returns the number of seconds and microseconds since the last reset.
bool button_state (int button) _NO_THROW
Returns the current state of the specified button.
unsigned int buttons_state () _NO_THROW
Returns the current state of all buttons.
unsigned int buttons_event () _NO_THROW
Returns all press/release events that are not processed yet.
bool button_event (int button) _NO_THROW
Checks whether there is a new event for the specified button.
void button_clear_event (int button) _NO_THROW
Clears the event flag of the specified button.
bool button_pressed (int button) _NO_THROW
Checks whether the button has been pressed.
bool button_released (int button) _NO_THROW
Checks whether the button has been pressed.
void dvi_init (void *address=NULL) _NO_THROW
Initializes DVI controller.
void dvi_set_address (void *address) _NO_THROW
Set a new base address of the video memory for the next frame.
dvi_frame * dvi_get_address () _NO_THROW
Returns the address of the video memory of the currently displayed frame.
void dvi_turn_on () _NO_THROW
Turns on the video output.
void dvi_turn_off () _NO_THROW
Turns off the video output.
bool dvi_vsync () _NO_THROW
Checks whether a vsync occured.
void dvi_set_pixel (unsigned int x, unsigned int y, dvi_pixel color) _NO_THROW
Sets a specific pixel in the current frame.
void dvi_set_pixel (unsigned int x, unsigned int y, unsigned int red, unsigned int green, unsigned int blue) _NO_THROW
Sets a specific pixel in the current frame.
dvi_pixel dvi_get_pixel (unsigned int x, unsigned int y) _NO_THROW
Gets the pixel information of a specific pixel in the current frame.
void dvi_get_pixel (unsigned int x, unsigned int y, unsigned int &red, unsigned int &green, unsigned int &blue) _NO_THROW
Gets the color of a specific pixel in the current frame.
template<class T >
T * addr_global (T *a)
template<class T >
T * addr_local (T *a)
template<class T >
T * addr_direct (T *a)
template<class T >
int addr_core (T *a)
Detailed Description
Declaration of all I/O function, types and address macros.
Definition in file io.h.
Define Documentation
#define _putn (i) _putp((void*)(i))
Definition at line 65 of file io.h.
Referenced by _malloc().
#define IO_BITSHARK_BS_UART 0x10000000
Definition at line 320 of file io.h.
#define IO_BITSHARK_CTRL 0x10001000
Definition at line 322 of file io.h.
#define IO_BITSHARK_GPS_UART 0x10000010
Definition at line 321 of file io.h.
#define IO_BUTTONS 0xE0030000
Definition at line 112 of file io.h.
#define IO_BUTTONS_EDGE (IO_BUTTONS|0x0)
Definition at line 115 of file io.h.
Referenced by button_clear_event(), and buttons_event().
#define IO_BUTTONS_MASK 0xFFFFFFF0
Definition at line 113 of file io.h.
#define IO_BUTTONS_STATE (IO_BUTTONS|0x0)
Definition at line 114 of file io.h.
Referenced by buttons_state().
#define IO_CLOCK 0xE0040000
Definition at line 104 of file io.h.
#define IO_CLOCK_MASK 0xFFFFFFF0
Definition at line 105 of file io.h.
#define IO_CLOCK_REG (IO_CLOCK|0x0)
Definition at line 106 of file io.h.
Referenced by get_clock().
#define IO_DVI 0xE0090000
Definition at line 127 of file io.h.
#define IO_DVI_AR (IO_DVI|0x0)
Definition at line 129 of file io.h.
Referenced by dvi_get_address(), and dvi_set_address().
#define IO_DVI_CR (IO_DVI|0x4)
Definition at line 130 of file io.h.
Referenced by dvi_turn_off(), and dvi_turn_on().
#define IO_DVI_HEIGHT 480
Definition at line 134 of file io.h.
#define IO_DVI_IESR (IO_DVI|0x8)
Definition at line 131 of file io.h.
Referenced by dvi_vsync().
#define IO_DVI_MASK 0xfffffff0
Definition at line 128 of file io.h.
#define IO_DVI_WIDTH 640
Definition at line 133 of file io.h.
#define IO_LEDS 0xE0010000
Definition at line 71 of file io.h.
#define IO_LEDS_MASK 0xFFFFFFF0
Definition at line 72 of file io.h.
#define IO_LEDS_OFF (IO_LEDS|0x8)
Definition at line 75 of file io.h.
Referenced by leds_off().
#define IO_LEDS_ON (IO_LEDS|0x4)
Definition at line 74 of file io.h.
Referenced by leds_on().
#define IO_LEDS_VALUE (IO_LEDS|0x0)
Definition at line 73 of file io.h.
Referenced by leds_value().
#define IO_POSLEDS 0xE0020000
Definition at line 85 of file io.h.
#define IO_POSLEDS_C 0
Definition at line 94 of file io.h.
#define IO_POSLEDS_E 1
Definition at line 92 of file io.h.
#define IO_POSLEDS_MASK 0xFFFFFFF0
Definition at line 86 of file io.h.
#define IO_POSLEDS_N 2
Definition at line 90 of file io.h.
#define IO_POSLEDS_OFF (IO_POSLEDS|0x8)
Definition at line 89 of file io.h.
Referenced by posleds_off().
#define IO_POSLEDS_ON (IO_POSLEDS|0x4)
Definition at line 88 of file io.h.
Referenced by posleds_on().
#define IO_POSLEDS_S 3
Definition at line 91 of file io.h.
#define IO_POSLEDS_VALUE (IO_POSLEDS|0x0)
Definition at line 87 of file io.h.
Referenced by posleds_value().
#define IO_POSLEDS_W 4
Definition at line 93 of file io.h.
#define io_read (addr, type) (type)(*((volatile type*)(addr)))
Definition at line 292 of file io.h.
Referenced by buttons_event(), buttons_state(), dvi_get_address(), dvi_get_pixel(), dvi_vsync(), get_clock(), inbyte(), kbhit(), kGetTimer(), and outbyte().
#define IO_RINGMAP 0xE00B0004
Definition at line 327 of file io.h.
#define IO_RINGMAP_LEN 0xE00B0000
Definition at line 326 of file io.h.
#define IO_RINGRATECONTROL 0x10002000
Definition at line 324 of file io.h.
#define IO_TIMER 0x00210000
Definition at line 13 of file io.h.
#define IO_TIMER_MASK 0xFFFFFF00
Definition at line 14 of file io.h.
#define IO_TIMER_TCR0 (IO_TIMER|0x08)
Definition at line 17 of file io.h.
Referenced by kGetTimer().
#define IO_TIMER_TCSR0 (IO_TIMER|0x00)
Definition at line 15 of file io.h.
Referenced by kSetTimer(), and kStopTimer().
#define IO_TIMER_TLR0 (IO_TIMER|0x04)
Definition at line 16 of file io.h.
Referenced by kSetTimer().
#define IO_UART 0xE0000000
Definition at line 49 of file io.h.
#define IO_UART_CTRL_REG (IO_UART|0xC)
Definition at line 54 of file io.h.
#define IO_UART_MASK 0xFFFFFFF0
Definition at line 50 of file io.h.
#define IO_UART_RX_REG (IO_UART|0x0)
Definition at line 51 of file io.h.
Referenced by inbyte().
#define IO_UART_STAT_REG (IO_UART|0x8)
Definition at line 53 of file io.h.
Referenced by inbyte(), kbhit(), and outbyte().
#define IO_UART_TX_REG (IO_UART|0x4)
Definition at line 52 of file io.h.
Referenced by outbyte().
#define io_write (addr, type, value) do{ *((volatile type*)(addr))=(type)value; barrier(); }while(0)
Definition at line 293 of file io.h.
Referenced by button_clear_event(), dvi_set_address(), dvi_set_pixel(), dvi_turn_off(), dvi_turn_on(), kSetTimer(), kStopTimer(), leds_off(), leds_on(), leds_value(), outbyte(), posleds_off(), posleds_on(), posleds_value(), prf_mb_snapshot(), and prf_mem_snapshot().
#define kClearIrq ()
Definition at line 44 of file io.h.
Referenced by kScheduleProcess().
#define kInitIrq ()
Definition at line 43 of file io.h.
Referenced by kStartScheduling().
#define MAKE_LOCAL_FIFOMEM_PTR (a) ((void*)((((unsigned int)(a))&(FIFO_MEM_SIZE-1))|FIFO_MEM))
Definition at line 278 of file io.h.
Referenced by addr_local(), and CheckRing().
#define MAKE_NOC_ACCE_CONFIG_PTR (a, core, acce) ((void*)((unsigned int) MAKE_NOC_FIFOMEM_PTR(a,core)|(1<<NOC_ADDR_LOCAL_WIDTH)|((((unsigned int)acce+2)&(NOC_ADDR_MAX_ACCS-1))<<(NOC_ADDR_LOCAL_WIDTH+NOC_ADDR_ACC_CONF_WIDTH))))
Definition at line 287 of file io.h.
Referenced by ring_stream_setup().
#define MAKE_NOC_ACCE_PTR (core, acce) ((void*)((unsigned int) MAKE_NOC_FIFOMEM_PTR(0,core)|((((unsigned int)acce+2)&(NOC_ADDR_MAX_ACCS-1))<<(NOC_ADDR_LOCAL_WIDTH+NOC_ADDR_ACC_CONF_WIDTH))))
Definition at line 284 of file io.h.
Referenced by ring_stream_setup().
#define MAKE_NOC_CORE_CONFIG_PTR (a, core) ((void*)((unsigned int) MAKE_NOC_FIFOMEM_PTR(a,core)|(1<<NOC_ADDR_LOCAL_WIDTH)))
Definition at line 285 of file io.h.
Referenced by ring_stream_setup().
#define MAKE_NOC_FIFOMEM_PTR (a, proc) ((void*)((((unsigned int)(a))&(FIFO_MEM_SIZE-1))|(NOC_ADDR_MAJOR<<(32-NOC_ADDR_MAJOR_WIDTH))|(((proc)&(NOC_ADDR_MAX_PROCS-1))<<(NOC_ADDR_LOCAL_WIDTH+NOC_ADDR_ACC_WIDTH+NOC_ADDR_ACC_CONF_WIDTH))))
Definition at line 281 of file io.h.
Referenced by addr_global(), CheckRing(), dBootKernel(), ForceShutdown(), CFifo< T, CFifo<>::w >::operator new(), rc_flush_(), and rc_init().
#define MAKE_NOC_FSL_CONFIG_PTR (a, core) ((void*)((unsigned int) MAKE_NOC_FIFOMEM_PTR(a,core)|(1<<NOC_ADDR_LOCAL_WIDTH)|(1<<(NOC_ADDR_LOCAL_WIDTH+NOC_ADDR_ACC_CONF_WIDTH))))
Definition at line 286 of file io.h.
Referenced by ring_stream_setup().
#define MAKE_NOC_FSL_PTR (core) ((void*)((unsigned int) MAKE_NOC_FIFOMEM_PTR(0,core)|(1<<(NOC_ADDR_LOCAL_WIDTH+NOC_ADDR_ACC_CONF_WIDTH))))
Definition at line 283 of file io.h.
Referenced by ring_stream_setup().
#define PIX_CONST (r, g, b) ((const dvi_pixel){{b,g,r}})
Definition at line 177 of file io.h.
Typedef Documentation
typedef union dvi_pixel_ dvi_pixel
typedef union _noc_addr_t noc_addr_t
Function Documentation
void _putp (void * p)
Definition at line 82 of file uart.cc.
References outbyte().
Referenced by _malloc().
void _puts (const char * s)
Writes given string to the terminal.
In contrast to newlib's puts() function, this function does not use file descriptors, buffering, etc., making it perfectly suitable for low level and high performance access to the terminal. It blocks until the last byte is written to the UART fifo.
Definition at line 73 of file uart.cc.
References outbyte().
Referenced by _malloc(), kPanic(), main(), srec(), srec_exec(), and srec_load().
template<class T > int addr_core (T * a)
Definition at line 313 of file io.h.
References _noc_addr_t::a, _noc_addr_t::major, _noc_addr_t::noc, NOC_ADDR_MAJOR, and _noc_addr_t::proc.
Referenced by CFifo< T, CFifo<>::w >::CFifo(), CFifo< T, r >::dump(), CFifo< T, r >::operator delete(), and CFifo< T, r >::validate().
template<class T > T* addr_direct (T * a)
Definition at line 307 of file io.h.
References _noc_addr_t::a, GetProcID(), _noc_addr_t::local, _noc_addr_t::major, _noc_addr_t::noc, NOC_ADDR_MAJOR, _noc_addr_t::proc, and PMC_NS::T.
Referenced by dAllocFifoEndPoint(), dAllocMail(), dAllocSimpleMail(), CFifo< T, r >::init3(), InitFifo(), and ProcessRequest().
template<class T > T* addr_global (T * a)
Definition at line 295 of file io.h.
References _noc_addr_t::a, GetProcID(), _noc_addr_t::major, MAKE_NOC_FIFOMEM_PTR, _noc_addr_t::noc, and PMC_NS::T.
Referenced by CFifo< T, r >::Create(), dBootKernel(), dDestroyFifoEndPoint(), dDestroyMail(), dWaitProcess(), ForwardRequest(), InitFifo(), linfs_register_seq(), map_start_mail(), ProcessRequest(), and ReserveRemoteSlot().
template<class T > T* addr_local (T * a)
Definition at line 301 of file io.h.
References a, _noc_addr_t::a, _noc_addr_t::major, MAKE_LOCAL_FIFOMEM_PTR, _noc_addr_t::noc, NOC_ADDR_MAJOR, and PMC_NS::T.
Referenced by CFifo< T, r >::Create(), dBootKernel(), InitFifo(), map_start_fifo(), and CFifo< T, r >::operator delete().
void button_clear_event (int button)
Clears the event flag of the specified button.
Definition at line 53 of file buttons.cc.
References IO_BUTTONS_EDGE, and io_write.
Referenced by button_pressed(), and button_released().
bool button_event (int button)
Checks whether there is a new event for the specified button.
When a button is pressed, this event is detected and stored. Such event can only be cleared when calling button_clear_event(). In the mean time, new events will be ignored.
Returns:
true when there is one
Definition at line 46 of file buttons.cc.
References buttons_event().
Referenced by button_pressed(), and button_released().
bool button_pressed (int button)
Checks whether the button has been pressed.
It checks whether there is an event. When there is one, the current state of the button is checked. In case the button is currently pressed, it is assumed the event is a press event, which is then cleared and true is returned. When there was no event or the button isn't hold down currently, nothing is changed and false is returned.
Note that when a button is pressed and released before the call to button_pressed() is made, it is assumed that the last event was a release event, so false will be returned. In that case, the press event is lost. When it is required that all events are processed, make sure that button_pressed() and button_released() are called in a timely fashion. It might be a good practice to let software poll the registers using buttons_event() and call button_pressed() or button_released() when buttons_event() returns a non-zero value. Polling the buttons by repeatedly calling button_pressed() and buton_released() for all buttons to be monitored, is inefficient.
There is a race condition in the case that the button is pressed or released during the execution of this function. In that case, it is possible that old or new events are ignored. However, it is assumed that the buttons are just human input, which is not that fast to cause problems.
Returns:
true in the case of a new event and the button is currently pressed
Definition at line 82 of file buttons.cc.
References button_clear_event(), button_event(), and button_state().
bool button_released (int button)
Checks whether the button has been pressed.
Similar to button_pressed().
Returns:
true in the case of a new event and the button is currently released
Definition at line 95 of file buttons.cc.
References button_clear_event(), button_event(), and button_state().
bool button_state (int button)
Returns the current state of the specified button.
Returns:
true when the button is currently pressed
Definition at line 17 of file buttons.cc.
References buttons_state().
Referenced by button_pressed(), and button_released().
unsigned int buttons_event ()
Returns all press/release events that are not processed yet.
Returns:
For every button a 1 in the result represents an unprocessed edge of the button.
Definition at line 33 of file buttons.cc.
References IO_BUTTONS_EDGE, and io_read.
Referenced by button_event().
unsigned int buttons_state ()
Returns the current state of all buttons.
Returns:
a 1 at the bit index when the corresponding button is pressed
Definition at line 25 of file buttons.cc.
References IO_BUTTONS_STATE, and io_read.
Referenced by button_state().
dvi_frame* dvi_get_address ()
Returns the address of the video memory of the currently displayed frame.
Definition at line 38 of file dvi.cc.
References IO_DVI_AR, and io_read.
Referenced by dvi_get_pixel(), and dvi_set_pixel().
dvi_pixel dvi_get_pixel (unsigned int x, unsigned int y)
Gets the pixel information of a specific pixel in the current frame.
Definition at line 94 of file dvi.cc.
References dvi_get_address(), io_read, and dvi_pixel_::raw.
Referenced by dvi_get_pixel().
void dvi_get_pixel (unsigned int x, unsigned int y, unsigned int & red, unsigned int & green, unsigned int & blue)
Gets the color of a specific pixel in the current frame.
Note that using this function has a huge overhead. Consider reading from the video memory directly for better performance.
Parameters:
x the column on the screen
y the row on the screen, where the upper left corner is the origin
red the red component of the pixel, range from 0 to 255
green the green component of the pixel, range from 0 to 255
blue the blue component of the pixel, range from 0 to 255
Definition at line 110 of file dvi.cc.
References dvi_pixel_::blue, dvi_get_pixel(), dvi_pixel_::green, dvi_pixel_::red, dvi_pixel_::rgb, and dvi_pixel_::rgb_exact.
void dvi_init (void * address = NULL)
Initializes DVI controller.
Definition at line 18 of file dvi.cc.
References _ddrbase, and dvi_set_address().
Referenced by mainProc().
void dvi_set_address (void * address)
Set a new base address of the video memory for the next frame.
Parameters:
address the new address, will be aligned to 2MB boundary
Definition at line 31 of file dvi.cc.
References IO_DVI_AR, and io_write.
Referenced by dvi_screen::DoubleBuf(), dvi_init(), dvi_screen::Flip(), dvi_screen::FlipNow(), and dvi_screen::ShowBuffer().
void dvi_set_pixel (unsigned int x, unsigned int y, dvi_pixel color)
Sets a specific pixel in the current frame.
Definition at line 68 of file dvi.cc.
References dvi_get_address(), io_write, and dvi_pixel_::raw.
Referenced by dvi_set_pixel().
void dvi_set_pixel (unsigned int x, unsigned int y, unsigned int red, unsigned int green, unsigned int blue)
Sets a specific pixel in the current frame.
Note that using this function has a huge overhead. Consider writing to the video memory directly for better performance.
Parameters:
x the column on the screen
y the row on the screen, where the upper left corner is the origin
red the red component of the pixel, range from 0 to 255
green the green component of the pixel, range from 0 to 255
blue the blue component of the pixel, range from 0 to 255
Definition at line 82 of file dvi.cc.
References blue, dvi_pixel_::blue, dvi_set_pixel(), green, dvi_pixel_::green, red, dvi_pixel_::red, and dvi_pixel_::rgb.
void dvi_turn_off ()
Turns off the video output.
Definition at line 52 of file dvi.cc.
References IO_DVI_CR, and io_write.
void dvi_turn_on ()
Turns on the video output.
Definition at line 45 of file dvi.cc.
References IO_DVI_CR, and io_write.
bool dvi_vsync ()
Checks whether a vsync occured.
dvi_vsync() keeps returning true until dvi_set_address() is called.
Returns:
true when a vsync has occured since the last call to dvi_set_address()
Definition at line 61 of file dvi.cc.
References IO_DVI_IESR, and io_read.
Referenced by dvi_screen::Flip(), and dvi_screen::FlipSlave().
unsigned int get_clock ()
Returns the number of seconds and microseconds since the last reset.
The system contains a clock peripheral that has a 32-bit counter to count microseconds since the last reset. To prevent problems by reading the seconds and microseconds from different registers, both the seconds and microseconds are packed into the same 32-bit register. Therefore, the maximum number of seconds is limited by 2**(32-ceil(log2(1000000)))=4096.
Returns:
(nr_sec<<20 | nr_ms%%1000000)
Definition at line 24 of file clock.cc.
References IO_CLOCK_REG, and io_read.
Referenced by gettimeofday().
int inbyte ()
Reads one byte from the serial port.
This is a blocking call. It will poll the status register until a byte is available. Note that when two processes simultaneously try to read, race conditions occur. The behavior is undefined when the UART fifo underruns in that case.
Definition at line 25 of file uart.cc.
References io_read, IO_UART_RX_REG, and IO_UART_STAT_REG.
Referenced by read(), and srec_char().
int kbhit ()
Checks whether data is to be read from the serial port.
This is a non-blocking call. It will return a non-zero value when at least one byte is available and ready to be read using inbyte().
Returns:
non-zero value when data is available
Definition at line 42 of file uart.cc.
References io_read, and IO_UART_STAT_REG.
unsigned int kGetTimer ()
Returns the current value of the timer.
Definition at line 68 of file timer.cc.
References io_read, and IO_TIMER_TCR0.
Referenced by bitshark_verify_clk(), GetRemainingTimeslice(), and kYield().
void kSetTimer (unsigned int time, unsigned int repeat)
Sets the local timer to the designated number of clock cycles.
The timer will be started automatically. When the value 0 is reached, an interrupt is generated.
Parameters:
time number of cycles to set the counter to
repeat set to non-zero to reload and restart the timer with this interval when zero is reached
Definition at line 22 of file timer.cc.
References IO_TIMER_TCSR0, IO_TIMER_TLR0, and io_write.
Referenced by kScheduleProcess(), kStartScheduling(), and kYield().
void kStopTimer ()
Stops the local timer.
The interrupt flag will be cleared.
Definition at line 76 of file timer.cc.
References IO_TIMER_TCSR0, and io_write.
Referenced by kInitKernel(), and kPanic().
void led_off (int led)
Turns off the led with the given number.
Parameters:
led The led to turn off. Which IDs are valid depend on the platform.
See also:
led_on()
Definition at line 27 of file leds.cc.
References leds_off().
void led_on (int led)
Turns on the led with the given number.
Parameters:
led The led to turn on. Which IDs are valid depend on the platform.
See also:
led_off()
Definition at line 18 of file leds.cc.
References leds_on().
void leds_off (int ledmask)
Turns off leds corresponding to the masked bits.
Parameters:
ledmask The leds to turn off. Led 0 is positioned at the LSB of ledmask.
See also:
leds_on()
Definition at line 45 of file leds.cc.
References IO_LEDS_OFF, and io_write.
Referenced by led_off().
void leds_on (int ledmask)
Turns on leds corresponding to the masked bits.
Parameters:
ledmask The leds to turn on. Led 0 is positioned at the LSB of ledmask.
See also:
leds_off()
Definition at line 36 of file leds.cc.
References IO_LEDS_ON, and io_write.
Referenced by led_on(), and main().
void leds_value (int leds)
Controls all leds simultaneously.
Parameters:
leds bitwise indication whether the corresponding leds should be turned on (1) or off (0)
Definition at line 53 of file leds.cc.
References IO_LEDS_VALUE, and io_write.
void outbyte (char ch)
Writes one byte to the serial port.
This is a blocking call. It will poll the status register until space is available to write one byte. In case that two processes are writing simultaneously, race conditions occur, resulting in buffer overflows. The behavior is undefined when the UART fifo overflows. It is likely that the whole fifo is invalidated and previously written but not yet transmitted bytes are lost.
Definition at line 56 of file uart.cc.
References io_read, IO_UART_STAT_REG, IO_UART_TX_REG, and io_write.
Referenced by _putp(), _puts(), srec_putc(), and write().
void posled_off (int led)
Definition at line 60 of file leds.cc.
References posleds_off().
void posled_on (int led)
Definition at line 57 of file leds.cc.
References posleds_on().
void posleds_off (int ledmask)
Definition at line 66 of file leds.cc.
References IO_POSLEDS_OFF, and io_write.
Referenced by posled_off().
void posleds_on (int ledmask)
Definition at line 63 of file leds.cc.
References IO_POSLEDS_ON, and io_write.
Referenced by posled_on().
void posleds_value (int leds)
Definition at line 69 of file leds.cc.
References IO_POSLEDS_VALUE, and io_write.