Starburst: kernel/kernel.cc File Reference
kernel/kernel.cc File Reference
Implementation of all kernel functions.
#include <errno.h>
#include <sys/helix_config.h>
#include <sys/kernel.h>
#include <sys/io.h>
#include <stdio.h>
#include <malloc.h>
#include <daemons.h>
#include <sys/time.h>
#include <signal.h>
#include <pthread.h>
#include <stdlib.h>
#include <trace.h>
#include <mc.h>
#include <reent.h>
Data Structures
struct sch_t
Flags to influence scheduling.
Defines
#define DBLED_ALIVE 0
#define DBLED_INIT 1
#define DBLED_SCHEDULE 2
#define DBLED_PANIC 3
#define DBLED_NEWPROC 4
#define DEBUG_ON(led) led_on(led)
#define DEBUG_OFF(led) led_off(led)
#define DEBUG_ALLOFF() leds_value(0)
#define DEBUG(str, a...) printk("KERNEL %d: " str "\n",GetProcID(),##a)
#define DEBUG0(a...) do{if(GetProcID()==0)DEBUG(a);}while(0)
#define TDEBUG_SIZE 13
#define TDEBUG(a...)
#define ASSIGN_CONST_PTR(type, var, val) *(type**)&(var)=(val)
#define kSetOSState(state) *(os_state_t*)&os_state=state
#define kIsInSigHandler(pt) (pt->sig_havetriggered!=0)
#define td_proc (&kernel_context->proc_table[0])
#define IS_VALID_DDR_PTR(p) ((uintptr_t)(p)>=(uintptr_t)(&_ddrbase)&&(uintptr_t)(p)<(uintptr_t)(&_ddrend))
#define STACK_PROTECTION_VALUE 0xdeadbeef
#define DID_WORK_NO 0
#define DID_WORK_MAYBE 1
#define DID_WORK_YES 2
#define TRACE ((trace_t*)kGetHookTable()[HOOK_TRACE])
#define __sf_fake_stdio __sf_fake_stdin
#define KERNEL_PRINT_PROGRESS if(GetProcID()==0)outbyte(kernel_name[init_progress++])
#define KERNEL_PRINT_PROGRESS_END if(GetProcID()==0)do{printk("%s\n",&kernel_name[init_progress]); if(GetProcID()==0)Disclaimer();}while(0)
#define TRACE ((trace_t*)kernel_context->hooks[HOOK_TRACE])
#define ASSERT(expr, msg) do{if(unlikely(!(expr)))kPanic(msg);}while(0)
Functions
void kInitSignalContext (proc_context_t *sig_context, proc_context_t *proc_context, char *triggered, int *havetriggered)
void kResetSignalContext (proc_context_t *sig_context)
static void kInitKernel (kernel_boot_param_t *param)
Basic initialization of the kernel.
static void kStartTaskDaemon (kernel_boot_param_t *param)
Starts the task daemon.
static void kStartScheduling ()
Initializes the scheduler and start scheduling.
kernel_context_t
kernel_contexts[NUM_PROCESSORS] __attribute__ ((section(".bss.kcontext"), aligned(CACHELINE_ALIGN)))
All kernel contexts, located in shared memory.
static const char *kernel_name __attribute__ ((unused))
The name of the kernel to print during boot.
struct _reent kernel_impure_data __attribute__ ((section(".bss.proc")))
All impure data (as defined by newlib), reserved for kernel.
void kBoot (kernel_boot_param_t *arg) __attribute__((noreturn))
Entry point of C-code of the kernel.
void Disclaimer ()
void kPanic (const char *msg)
Prints coredump and halts kernel, in case of emergency.
int kShutdown ()
Shuts down kernel and return to bootloader.
pid_t kGetPid ()
Returns the process id of the current process.
int kCreateProcess (pid_t &pid, void *(*main)(void *), void *arg, timems_t slicelength, unsigned int stack)
Creates a new process.
void * ProcessEntry (void *(*main)(void *), void *arg)
Entry point of a process.
int kSetProcessFlags (pid_t pid, int flags)
Sets specific process flags.
int kGetProcessFlags (pid_t pid, int *flags)
Gets the process flags.
int kGetProcessState (pid_t pid, proc_state_t *state, bool *sighandling)
Returns the state of a process.
int kSetProcessTimeslice (pid_t pid, timems_t slicelength)
Changes the length of the timeslice of an existing process.
timeslice_t GetRemainingTimeslice ()
Returns the remaining clock ticks before the end of the current timeslice.
int kStartProcess (pid_t pid)
Starts a process that has been created using kCreateProcess().
int kYield (bool havework)
Forcably ends the timeslice of the current process.
int kSuspend (const sigset_t *mask, const sigset_t *wait_sticky)
Suspends current process until one of the non-masked signals occur.
void kEndProcess (void *ret)
Ends the current process.
int kJoinProcess (pid_t pid, void **ret)
Joins a JOINABLE process.
int kDestroyProcess (pid_t pid, void **ret)
Destroys and clean up a process.
int kGetZombie (pid_t *pid, void **ret)
Looks for a ZOMBIE process and destroys it.
int kGetProcessStats (pid_t pid, proc_stats_t *stats)
Collects statistics of the specified process.
int kCoreDump ()
Prints complete state of the current process and the kernel.
int kGetProcLocal (proc_local_t **p)
int kGetChannelCount (pid_t pid)
Returns the number of allocated channels.
int kAllocChannels (pid_t pid, int num_chan)
Allocates memory for channels.
int kAssignChannel (pid_t pid, int chan_id, void *channel, int label)
Assigns a pointer to a channel.
int kSetChannelLabel (pid_t pid, int chan_id, int label)
Sets a new label to an existing channel.
int kFindChannel (int label)
Looks for a channel with the specified label.
void * kOpenChannel (int channel)
Returns the pointer corresponding to the given channel of the current process.
hook_t * kGetHookTable ()
Returns the pointer to the hook table.
int kSetSignalHandler (int signum, const struct sigaction *act)
int kClearSignal (int signum, struct sigaction *sa)
int kSendSignal (pid_t pid, int sig, union sigval *sv)
Send signal to other process.
int kMaskSignal (int how, const sigset_t *set, sigset_t *oldset)
static sync_event_entry_t * kFindEventEntry (proc_table_t *proc, void *event)
int kSyncEventHit (pid_t pid, void *event)
Marks specified event as hit.
int kSyncEventWait (void *event, int count)
Blocks until a given event has occured.
static void kCheckFreeStack () __attribute__((unused))
static void kCheckStackOverflow () __attribute__((unused))
static void kScheduleProcess (proc_table_t *next, bool continue_slice)
void kScheduleNext ()
Determines the next process to schedule.
Variables
void * _text_schedule
void * _text_schedule_end
void * _text_schedule_base
unsigned int _ddrbase
unsigned int _ddrend
sch_t sch
struct _reent *_CONST
__ATTRIBUTE_IMPURE_PTR__ _kernel_impure_ptr = &kernel_impure_data
Pointer to global_impure_data.
Detailed Description
Implementation of all kernel functions.
Note that all function starting with k should only be called from within the kernel context: priviledged mode, in a syscall. Do not do a syscall from within a syscall.
Definition in file kernel.cc.
Define Documentation
#define __sf_fake_stdio __sf_fake_stdin
Definition at line 132 of file kernel.cc.
#define ASSERT (expr, msg) do{if(unlikely(!(expr)))kPanic(msg);}while(0)
Definition at line 1584 of file kernel.cc.
Referenced by kFindEventEntry(), kInitKernel(), kScheduleNext(), kScheduleProcess(), kSuspend(), and kYield().
#define ASSIGN_CONST_PTR (type, var, val) *(type**)&(var)=(val)
Definition at line 53 of file kernel.cc.
Referenced by kInitKernel(), and kScheduleProcess().
#define DBLED_ALIVE 0
Definition at line 22 of file kernel.cc.
Referenced by kBoot().
#define DBLED_INIT 1
Definition at line 23 of file kernel.cc.
Referenced by kBoot().
#define DBLED_NEWPROC 4
Definition at line 26 of file kernel.cc.
Referenced by kCreateProcess(), and kStartProcess().
#define DBLED_PANIC 3
Definition at line 25 of file kernel.cc.
Referenced by kPanic().
#define DBLED_SCHEDULE 2
Definition at line 24 of file kernel.cc.
Referenced by kScheduleNext().
#define DEBUG (str, a...) printk("KERNEL %d: " str "\n",GetProcID(),##a)
Definition at line 32 of file kernel.cc.
Referenced by kInitKernel(), and ProcessEntry().
#define DEBUG0 (a...) do{if(GetProcID()==0)DEBUG(a);}while(0)
Definition at line 33 of file kernel.cc.
Referenced by kInitKernel(), kStartScheduling(), and kStartTaskDaemon().
#define DEBUG_ALLOFF () leds_value(0)
Definition at line 31 of file kernel.cc.
Referenced by kBoot().
#define DEBUG_OFF (led) led_off(led)
Definition at line 30 of file kernel.cc.
Referenced by kBoot(), kScheduleNext(), and kStartProcess().
#define DEBUG_ON (led) led_on(led)
Definition at line 29 of file kernel.cc.
Referenced by kBoot(), kCreateProcess(), kPanic(), and kScheduleNext().
#define DID_WORK_MAYBE 1
Definition at line 121 of file kernel.cc.
Referenced by kScheduleProcess(), and kYield().
#define DID_WORK_NO 0
Definition at line 120 of file kernel.cc.
Referenced by kScheduleNext(), and kYield().
#define DID_WORK_YES 2
Definition at line 122 of file kernel.cc.
Referenced by kAssignChannel(), kScheduleNext(), kSendSignal(), kStartProcess(), kStartScheduling(), and kYield().
#define IS_VALID_DDR_PTR (p) ((uintptr_t)(p)>=(uintptr_t)(&_ddrbase)&&(uintptr_t)(p)<(uintptr_t)(&_ddrend))
Definition at line 87 of file kernel.cc.
Referenced by kCoreDump().
#define KERNEL_PRINT_PROGRESS if(GetProcID()==0)outbyte(kernel_name[init_progress++])
Definition at line 246 of file kernel.cc.
Referenced by kInitKernel().
#define KERNEL_PRINT_PROGRESS_END if(GetProcID()==0)do{printk("%s\n",&kernel_name[init_progress]); if(GetProcID()==0)Disclaimer();}while(0)
Definition at line 247 of file kernel.cc.
Referenced by kInitKernel().
#define kIsInSigHandler (pt) (pt->sig_havetriggered!=0)
Definition at line 57 of file kernel.cc.
Referenced by kGetProcessState(), kGetProcessStats(), and kSuspend().
#define kSetOSState (state) *(os_state_t*)&os_state=state
Definition at line 54 of file kernel.cc.
Referenced by kBoot(), kInitKernel(), kPanic(), and kStartScheduling().
#define STACK_PROTECTION_VALUE 0xdeadbeef
Definition at line 93 of file kernel.cc.
Referenced by kCheckStackOverflow(), kCreateProcess(), and kEndProcess().
#define td_proc (&kernel_context->proc_table[0])
Definition at line 62 of file kernel.cc.
Referenced by kDestroyProcess(), kInitKernel(), kScheduleNext(), kStartProcess(), and kStartScheduling().
#define TDEBUG (a...)
Value:
do{                                                                                             \
        struct timeval now;                                                                         \
        const unsigned int  ts=(1<<TDEBUG_SIZE)*GetProcID(),                                        \
                            ts_mask=((1<<TDEBUG_SIZE)*NUM_PROCESSORS-1)&~((1<<TDEBUG_SIZE)-1);      \
        while(gettimeofday(&now,NULL)==0&&(now.tv_usec&ts_mask)!=ts);                               \
        DEBUG(a);                                                                                   \
    }while(0)
Definition at line 35 of file kernel.cc.
Referenced by kInitKernel(), and kShutdown().
#define TDEBUG_SIZE 13
Definition at line 34 of file kernel.cc.
#define TRACE ((trace_t*)kGetHookTable()[HOOK_TRACE])
Definition at line 1555 of file kernel.cc.
Referenced by kDestroyProcess(), kScheduleNext(), kScheduleProcess(), kSetProcessTimeslice(), and kYield().
#define TRACE ((trace_t*)kernel_context->hooks[HOOK_TRACE])
Definition at line 1555 of file kernel.cc.
Function Documentation
kernel_context_t kernel_contexts [NUM_PROCESSORS] __attribute__ ((section(".bss.kcontext"), aligned(CACHELINE_ALIGN)))
All kernel contexts, located in shared memory.
static const char* kernel_name __attribute__ ((unused)) [static]
The name of the kernel to print during boot.
struct _reent kernel_impure_data __attribute__ ((section(".bss.proc"))) [read]
All impure data (as defined by newlib), reserved for kernel.
void Disclaimer ()
Definition at line 183 of file kernel.cc.
References MAX_PROCESSES, printk, and STRINGIFY.
timeslice_t GetRemainingTimeslice ()
Returns the remaining clock ticks before the end of the current timeslice.
When interrupted by the timer, race conditions can occur, which result in a reported timeslice that is too high.
Call from user space, does not need a syscall.
Returns:
the number of remaining clock cycles.
Definition at line 763 of file kernel.cc.
References current_proc, kGetTimer(), sch_t::remaining_slots, SCHEDULE_SLOTS, and _proc_table_t::time_yielded.
Referenced by TraceRelTime().
int kAllocChannels (pid_t pid, int num_chan)
Allocates memory for channels.
When called multiple times, the allocated memory will be resized.
Parameters:
pid process to allocate channel memory for
num_chan number of channels to allocate, will be initialized to NULL
Returns:
0 on success, otherwise an errno
Definition at line 1198 of file kernel.cc.
References channel_t::channel, _proc_table_t::channels, ESUCCESS, kernel_context, channel_t::label, MAX_PROCESSES, _proc_table_t::num_channels, orealloc(), pid, and kernel_context_t::proc_table.
Referenced by kAssignChannel().
int kAssignChannel (pid_t pid, int chan_id, void * channel, int label)
Assigns a pointer to a channel.
Parameters:
pid process to assign a channel to
chan_id channel to assign the pointer to, must be less than num_chan of a previous kAllocChannels() call, when set to -1, a new channel is allocated at the end of the list
channel to store in the channel list
label an alternative label of the channel (set to 0 for no label, all negative labels are reserved by the kernel)
Returns:
0 on success, otherwise an errno
Definition at line 1226 of file kernel.cc.
References channel_t::channel, _proc_table_t::channels, DID_WORK_YES, ESUCCESS, sch_t::just_did_work, kAllocChannels(), kernel_context, channel_t::label, MAX_PROCESSES, _proc_table_t::num_channels, pid, and kernel_context_t::proc_table.
void kBoot (kernel_boot_param_t * arg)
Entry point of C-code of the kernel.
After initialization of crt0.S and crtbegin.S, this function is called. It will handle all initialization routines of the kernel and will eventually start the task daemon.
The master core will usually be invoked without additional arguments, a slave core will receive a kernel_boot_param_t* that contains a reference to a mailbox to notify a successful boot.
Parameters:
arg NULL or kernel_boot_param_t*
Definition at line 159 of file kernel.cc.
References kernel_boot_param_t::arg, DBLED_ALIVE, DBLED_INIT, DEBUG_ALLOFF, DEBUG_OFF, DEBUG_ON, InitHardware(), kInitKernel(), kSetOSState, kStartScheduling(), kStartTaskDaemon(), kernel_boot_param_t::notify_booted, and OS_BOOT.
static void kCheckFreeStack () [static]
Definition at line 1588 of file kernel.cc.
References _proc_table_t::context_switches, current_context, current_proc, likely, _proc_table_t::min_stack, proc_context_t::regs, _proc_table_t::stack, and unlikely.
Referenced by kScheduleNext().
static void kCheckStackOverflow () [static]
Definition at line 1603 of file kernel.cc.
References _impure_ptr, _kernel_impure_ptr, current_context, current_proc, kGetPid(), kPanic(), proc_context_t::regs, _proc_table_t::stack, STACK_PROTECTION_VALUE, and unlikely.
Referenced by kScheduleNext().
int kClearSignal (int signum, struct sigaction * sa)
Definition at line 1325 of file kernel.cc.
References _sig_def_func, current_proc, ESUCCESS, kMaskSignal(), NSIG, sigaction::sa_flags, sigaction::sa_handler, sigaction::sa_mask, SA_RESETHAND, _proc_table_t::sig_action, SIG_BLOCK, _proc_table_t::sig_enabled, _proc_table_t::sig_triggered, and sigaddset().
int kCoreDump ()
Prints complete state of the current process and the kernel.
Returns:
0 on success, otherwise an errno
Definition at line 1123 of file kernel.cc.
References current_context, current_proc, ESUCCESS, _proc_table_t::flags, proc_context_t::fsr, GetClockFreq(), GetOSState, GetProcID(), IS_VALID_DDR_PTR, kernel_context, _proc_table_t::main, MAX_PROCESSES, _proc_table_t::min_stack, proc_context_t::msr, _proc_table_t::pid, printk, kernel_context_t::proc_table, proc_context_t::regs, _proc_table_t::stack, _proc_table_t::state, _proc_table_t::time, and _proc_table_t::time_yielded.
Referenced by kPanic().
int kCreateProcess (pid_t & pid, void *(*)(void *) main, void * arg, timems_t slicelength, unsigned int stack)
Creates a new process.
By default, a process is created detached.
Only the task daemon is allowed to start new processes.
Parameters:
pid the new process id will be written to the pointer supplied
main the main function of this process
arg an optional argument to main, can be NULL
slicelength the length of the allocated time slice in ms
stack the size of the stack in words
Returns:
0 on success, otherwise an errno
Definition at line 545 of file kernel.cc.
References DBLED_NEWPROC, DEBUG_ON, ESUCCESS, InitSignalList(), kDestroyProcess(), kernel_context, kGetPid(), kInitContext(), kInitSignalContext(), kSetProcessTimeslice(), main, MAX_PROCESSES, mc_apply, MEASURE_STACK_USAGE, NEW, NOPROC, omalloc(), pid, PROC_FLAG_DETACHED, kernel_context_t::proc_table, pthread_sch_t::processes, sch_t::pthread_sch, sigemptyset(), sigfillset(), and STACK_PROTECTION_VALUE.
Referenced by kStartTaskDaemon().
int kDestroyProcess (pid_t pid, void ** ret)
Destroys and clean up a process.
Only the task daemon is allowed to destroy processes. All allocated memory will be freeed. Process statistics is not deleted, so after destroying a process, kGetProcessStats() can be called. A process cannot destroy itself.
Parameters:
pid process to destroy
ret a pointer to store the return value of the process, can be NULL, holds unknown data when a non-ZOMBIE process is destroyed
Returns:
0 on success, otherwise an errno
Definition at line 1017 of file kernel.cc.
References ESUCCESS, ffreeAll(), freeAll(), kernel_context, kGetPid(), kTraceProcChange(), MAX_PROCESSES, mc_apply, _proc_table_t::next_entry, NOPROC, pid, _proc_table_t::prev_entry, kernel_context_t::proc_table, pthread_sch_t::processes, sch_t::pthread_sch, _proc_table_t::ret, _proc_table_t::state, td_proc, TRACE, and ZOMBIE.
Referenced by kCreateProcess(), and kGetZombie().
void kEndProcess (void * ret)
Ends the current process.
Will be called automatically when the main function of a process returns. The timeslice will always be ended by a call to kYield().
Parameters:
ret the value returned by the main of the process, which can be retrieved using kJoinProcess() and kDestroyProcess()
Returns:
never
Definition at line 944 of file kernel.cc.
References _impure_ptr, _kernel_impure_ptr, current_context, current_proc, _proc_table_t::flags, GetProcID(), JOINABLE, kGetPid(), kPanic(), kYield(), _proc_table_t::main, _proc_table_t::min_stack, printk, PROC_FLAG_JOINABLE, _proc_table_t::ret, _proc_table_t::stack, STACK_PROTECTION_VALUE, _proc_table_t::state, and ZOMBIE.
int kFindChannel (int label)
Looks for a channel with the specified label.
Parameters:
label the label to look for
Returns:
the channel id of the channel with the specified label, or -1 when not found
Definition at line 1271 of file kernel.cc.
References _proc_table_t::channels, current_proc, channel_t::label, and _proc_table_t::num_channels.
static sync_event_entry_t* kFindEventEntry (proc_table_t * proc, void * event) [static]
Definition at line 1449 of file kernel.cc.
References ASSERT, sync_event_entry_t::event, sync_event_entry_t::hit, KERNEL_SYNC_EVENTS, _proc_table_t::sync_event, and sync_event_entry_t::wait.
Referenced by kSyncEventHit(), and kSyncEventWait().
int kGetChannelCount (pid_t pid)
Returns the number of allocated channels.
This does not indicate whether channels are assigned or in use.
Parameters:
pid the process to get the information of
Returns:
The channel count or -1 when an invalid pid is supplied
Definition at line 1179 of file kernel.cc.
References _proc_table_t::channels, kernel_context, MAX_PROCESSES, NOPROC, _proc_table_t::num_channels, pid, kernel_context_t::proc_table, and _proc_table_t::state.
hook_t* kGetHookTable ()
Returns the pointer to the hook table.
The memory region of the hook table is owned by the TaskDaemon (pid 0).
Returns:
cannot be NULL during normal operation (it can be null during kernel initialization, just before the table is initialized)
Definition at line 1301 of file kernel.cc.
References kernel_context.
Referenced by kInitKernel().
pid_t kGetPid ()
Returns the process id of the current process.
Definition at line 530 of file kernel.cc.
References current_proc, and _proc_table_t::pid.
Referenced by kCheckStackOverflow(), kCreateProcess(), kDestroyProcess(), kEndProcess(), kGetProcessState(), kGetZombie(), kShutdown(), kStartProcess(), kSyncEventHit(), kYield(), and ProcessEntry().
int kGetProcessFlags (pid_t pid, int * flags)
Gets the process flags.
Parameters:
pid the process to retrieve the flags of
flags will receive the flags of the process, cannot be NULL
Returns:
0 on success, otherwise an errno
Definition at line 687 of file kernel.cc.
References ESUCCESS, _proc_table_t::flags, kernel_context, MAX_PROCESSES, NOPROC, pid, kernel_context_t::proc_table, and _proc_table_t::state.
int kGetProcessState (pid_t pid, proc_state_t * state, bool * sighandling)
Returns the state of a process.
Parameters:
pid the process to retrieve the state of, -1 means myself
state will receive the state of the process
sighandling will set to true when the process is currently handling signals
Returns:
0 on success, otherwise an errno
Definition at line 706 of file kernel.cc.
References current_proc, ESUCCESS, kernel_context, kGetPid(), kIsInSigHandler, MAX_PROCESSES, NOPROC, pid, kernel_context_t::proc_table, _proc_table_t::state, and unlikely.
int kGetProcessStats (pid_t pid, proc_stats_t * stats)
Collects statistics of the specified process.
Parameters:
pid the process to collect statistics of (can be an non-existing process)
stats pointer to struct to write statistics to
Returns:
0 on success, otherwise an errno
Definition at line 1087 of file kernel.cc.
References _proc_table_t::context, proc_stats_t::context, _proc_table_t::context_switches, proc_stats_t::context_switches, ESUCCESS, _proc_table_t::flags, proc_stats_t::flags, GetClockFreq(), proc_stats_t::insighandler, kernel_context, kIsInSigHandler, _proc_table_t::main, proc_stats_t::main, MAX_PROCESSES, _proc_table_t::min_stack, proc_stats_t::min_stack, proc_stats_t::pid, pid, kernel_context_t::proc_table, SCHEDULE_SLOTS, _proc_table_t::slack, proc_stats_t::slice_length, proc_stats_t::slice_slack, proc_stats_t::slice_used, _proc_table_t::state, proc_stats_t::state, _proc_table_t::time, _proc_table_t::time_alloc, _proc_table_t::yields, and proc_stats_t::yields.
int kGetProcLocal (proc_local_t ** p)
Definition at line 1160 of file kernel.cc.
References current_proc, ESUCCESS, and _proc_table_t::proc_local.
int kGetZombie (pid_t * pid, void ** ret)
Looks for a ZOMBIE process and destroys it.
Walks over all processes and cleans up the first ZOMBIE process it can find. Only the task daemon is allowed to call the function.
Parameters:
pid the process that has been cleaned up, can be NULL
ret pointer to store the return value of the process in, can be NULL
Returns:
0 on success, EAGAIN when no ZOMBIEs has been found, otherwise an appropriate errno
Definition at line 1066 of file kernel.cc.
References kDestroyProcess(), kernel_context, kGetPid(), MAX_PROCESSES, kernel_context_t::proc_table, _proc_table_t::state, and ZOMBIE.
static void kInitKernel (kernel_boot_param_t * param) [static]
Basic initialization of the kernel.
It will initialize the heaps, kernel context, and process table.
Parameters:
param the same argument as the one main(int,char**) got
Definition at line 260 of file kernel.cc.
References __attribute__, _fifomem, _impure_ptr, _kernel_impure_ptr, ASSERT, ASSIGN_CONST_PTR, CACHELINE_ALIGN, _proc_table_t::context, current_context, current_proc, DEBUG, DEBUG0, proc_context_t::donttouch, DumpConfig(), GetDCacheSize(), GetFifoMemSize(), GetICacheSize(), GetLocalMemSize(), GetMBFlags(), GetProcID(), GetSoCCores(), gettimeofday(), kernel_context_t::heap, HOOK_SCHEDULER, HOOKS, InitDCache(), InitICache(), InvalidateDCache(), kernel_context, KERNEL_PRINT_PROGRESS, KERNEL_PRINT_PROGRESS_END, kernel_stack, KERNEL_STACK_SIZE, kGetHookTable(), kPanic(), kSetOSState, kStopTimer(), kTraceInit(), lcalloc, malloc_dump(), malloc_init(), MAX_PROCESSES, MB_FLAG_DCACHE_WRITEBACK, MB_FLAG_SHARED_HEAP_CACHED, _proc_table_t::next_entry, NOPROC, kernel_boot_param_t::notify_booted, OS_INIT, OS_SINGLE, _proc_table_t::pid, _proc_table_t::prev_entry, printk, PROC_HEAP, kernel_context_t::proc_table, pthread_global_init(), pthread_local_init(), sch_t::pthread_sch, RING_CONSISTENCY_SIZE, kernel_context_t::stack, _proc_table_t::state, TASK_DAEMON_FIFO_SIZE, td_proc, and TDEBUG.
Referenced by kBoot().
void kInitSignalContext (proc_context_t * sig_context, proc_context_t * proc_context, char * triggered, int * havetriggered)
Referenced by kCreateProcess().
int kJoinProcess (pid_t pid, void ** ret)
Joins a JOINABLE process.
Gets the return value of the process to join. Never blocks, so wrap in a loop when it is intended to wait until the process finishes. A JOINABLE process will become a ZOMBIE when the join is successful. The function is not thread-safe.
Parameters:
pid process to join
ret pointer to store the return value of the process to join, can be NULL
Returns:
0 on success, EAGAIN when pid was not JOINABLE, otherwise an appropiate errno
Definition at line 982 of file kernel.cc.
References ESUCCESS, _proc_table_t::flags, JOINABLE, kernel_context, MAX_PROCESSES, NOPROC, pid, PROC_FLAG_JOINABLE, kernel_context_t::proc_table, _proc_table_t::ret, _proc_table_t::state, and ZOMBIE.
int kMaskSignal (int how, const sigset_t * set, sigset_t * oldset)
Definition at line 1416 of file kernel.cc.
References current_proc, ESUCCESS, SIG_BLOCK, SIG_BLOCKABLE, _proc_table_t::sig_mask, SIG_SETMASK, SIG_UNBLOCK, sigandset(), and sigorset().
Referenced by kClearSignal(), and kSuspend().
void* kOpenChannel (int channel)
Returns the pointer corresponding to the given channel of the current process.
Blocks and kYield()s until the given channel is not NULL. Note that the specified channel is not checked for validity.
Parameters:
channel channel to open
Returns:
pointer corresponding to the channel, cannot be NULL
Definition at line 1289 of file kernel.cc.
References channel_t::channel, _proc_table_t::channels, current_proc, kYield(), and _proc_table_t::num_channels.
void kPanic (const char * msg)
Prints coredump and halts kernel, in case of emergency.
Parameters:
msg message to be printed, which indicates the reason of the core dump. Can be NULL.
Definition at line 468 of file kernel.cc.
References _fifomem, _puts(), DBLED_PANIC, DEBUG_ON, DisableDCache(), DisableICache(), FlushDCache(), GetProcID(), gettimeofday(), kernel_context_t::heap, kCoreDump(), kDisableInterrupt(), kernel_context, kReset(), kSetOSState, kStopTimer(), malloc_dump(), OS_BOOT, and printk.
Referenced by kCheckStackOverflow(), kEndProcess(), kInitKernel(), and kStartTaskDaemon().
void kResetSignalContext (proc_context_t * sig_context)
Referenced by kScheduleProcess().
void kScheduleNext ()
Determines the next process to schedule.
This function is called by entry.S after an interrupt.
Definition at line 1679 of file kernel.cc.
References ASSERT, current_proc, DBLED_SCHEDULE, DEBUG_OFF, DEBUG_ON, DID_WORK_NO, DID_WORK_YES, sch_t::have_work, sch_t::just_did_work, kCheckFreeStack(), kCheckStackOverflow(), kScheduleProcess(), kTraceClose(), kTraceScheduleYield(), likely, _proc_table_t::next_entry, _proc_table_t::prev_entry, sch_t::remaining_slots, RUNNING, SCHEDULE_SLOTS, _proc_table_t::sig_havetriggered, _proc_table_t::sig_ret, sch_t::skip_taskdaemon, _proc_table_t::slack, _proc_table_t::state, SUSPENDED, td_proc, _proc_table_t::time_yielded, TRACE, and unlikely.
static void kScheduleProcess (proc_table_t * next, bool continue_slice) [static]
Definition at line 1622 of file kernel.cc.
References _impure_ptr, ASSERT, ASSIGN_CONST_PTR, _proc_table_t::context, current_context, current_proc, DID_WORK_MAYBE, _proc_table_t::impure_data, sch_t::just_did_work, kClearIrq, kResetSignalContext(), kSetTimer(), kTraceClose(), kTraceSchedule(), _proc_table_t::pid, _proc_table_t::proc_local, proc_local, sch_t::remaining_slots, SCHEDULE_SLOTS, _proc_table_t::sig_context, _proc_table_t::sig_havetriggered, _proc_table_t::sig_ret, _proc_table_t::sig_trig_handling, SIG_TRIG_HANDLING_ABRT, SIG_TRIG_HANDLING_CONT, SIG_TRIG_HANDLING_HAND, _proc_table_t::stack, thread_local, _proc_table_t::time, _proc_table_t::time_alloc, _proc_table_t::time_yielded, timeslice, TRACE, unlikely, and proc_local_t::user.
Referenced by kScheduleNext().
int kSendSignal (pid_t pid, int sig, union sigval * sv)
Send signal to other process.
A signal will only be triggered (and thus handled) once.
When the signal was already triggered, the previous sv will be overwritten.
Parameters:
pid the process to send to
sig the signal number to send
sv value to pass to the handler by siginfo_t
Returns:
ESRCH when the process does not exist (anymore), ENOENT when the signal was disabled, EAGAIN when masked, 0 on accept, otherwise another errno
Definition at line 1365 of file kernel.cc.
References DID_WORK_YES, ESUCCESS, sch_t::just_did_work, kernel_context, laset, MAX_PROCESSES, NSIG, pid, kernel_context_t::proc_table, RUNNING, _proc_table_t::sig_action, _proc_table_t::sig_enabled, _proc_table_t::sig_mask, _proc_table_t::sig_sticky, SIG_STICKY, _proc_table_t::sig_trig_handling, SIG_TRIG_HANDLING_CONT, SIG_TRIG_HANDLING_SEND, _proc_table_t::sig_triggered, SIGCONT, sigismember(), _proc_table_t::state, SUSPENDED, and sigaction::sv.
int kSetChannelLabel (pid_t pid, int chan_id, int label)
Sets a new label to an existing channel.
Parameters:
pid process that has the channel to change the label of
chan_id the channel to change the label of
label the new label, where 0 means 'no label'
Returns:
0 on success, otherwise an errno
Definition at line 1256 of file kernel.cc.
References _proc_table_t::channels, ESUCCESS, kernel_context, channel_t::label, MAX_PROCESSES, _proc_table_t::num_channels, pid, and kernel_context_t::proc_table.
int kSetProcessFlags (pid_t pid, int flags)
Sets specific process flags.
It is not safe to set the flags and join/destroy the process concurrent.
So, do process management of a single process in a safe manner.
Returns:
0 on success, otherwise an errno
Definition at line 662 of file kernel.cc.
References ESUCCESS, _proc_table_t::flags, JOINABLE, kernel_context, MAX_PROCESSES, NOPROC, pid, PROC_FLAG_DETACHED, kernel_context_t::proc_table, _proc_table_t::state, and ZOMBIE.
int kSetProcessTimeslice (pid_t pid, timems_t slicelength)
Changes the length of the timeslice of an existing process.
When pid is the current process, the new time is effective after the next context switch
Parameters:
pid the process to change the timeslice of, which must exist
slicelength the length of the allocated time slice in ms
Returns:
0 on success, otherwise an errno
Definition at line 732 of file kernel.cc.
References ESUCCESS, GetClockFreq(), kernel_context, kTraceProcChange(), _proc_table_t::main, MAX_PROCESSES, NOPROC, pid, kernel_context_t::proc_table, _proc_table_t::state, _proc_table_t::time, and TRACE.
Referenced by kCreateProcess().
int kSetSignalHandler (int signum, const struct sigaction * act)
Definition at line 1305 of file kernel.cc.
References current_proc, ESUCCESS, NSIG, sigaction::sa_handler, _proc_table_t::sig_action, _proc_table_t::sig_enabled, SIG_HANDLEABLE, _proc_table_t::sig_triggered, sigaddset(), SIGCONT, and sigdelset().
int kShutdown ()
Shuts down kernel and return to bootloader.
Not gracefull, no process termination, just reboot immediately.
Returns:
EPERM when another process than the task daemon tries to shutdown, otherwise never
Definition at line 509 of file kernel.cc.
References DisableDCache(), DisableICache(), kDisableInterrupt(), kGetPid(), kReset(), and TDEBUG.
int kStartProcess (pid_t pid)
Starts a process that has been created using kCreateProcess().
Only the task daemon is allowed to start processes.
Parameters:
pid the process to start
Returns:
0 on success, otherwise an errno
Definition at line 779 of file kernel.cc.
References current_proc, DBLED_NEWPROC, DEBUG_OFF, DID_WORK_YES, ESUCCESS, sch_t::just_did_work, kernel_context, kGetPid(), MAX_PROCESSES, NEW, _proc_table_t::next_entry, pid, _proc_table_t::prev_entry, kernel_context_t::proc_table, RUNNING, _proc_table_t::state, and td_proc.
Referenced by kStartTaskDaemon().
static void kStartScheduling () [static]
Initializes the scheduler and start scheduling.
Never returns.
Definition at line 1561 of file kernel.cc.
References DEBUG0, DID_WORK_YES, sch_t::have_work, sch_t::just_did_work, kEnableInterrupt(), kInitIrq, kSetOSState, kSetTimer(), OS_MULTI, sch_t::remaining_slots, SCHEDULE_SLOTS, sch_t::skip_taskdaemon, td_proc, and sch_t::was_idle.
Referenced by kBoot().
static void kStartTaskDaemon (kernel_boot_param_t * param) [static]
Starts the task daemon.
This is essentially a wrapper around kCreateProcess() and kStartProcess(). It will call InitTaskDaemon(), which should be implemented by the application.
Parameters:
param as received by main(int,char**)
Definition at line 446 of file kernel.cc.
References DEBUG0, InitTaskDaemon(), kCreateProcess(), kPanic(), kStartProcess(), malloc(), pid, TASK_DAEMON_STACK, and TASK_DAEMON_TIMESLICE.
Referenced by kBoot().
int kSuspend (const sigset_t * mask, const sigset_t * wait_sticky)
Suspends current process until one of the non-masked signals occur.
Cannot be called from within a signal handler
Parameters:
mask ignore all signals specified in this set (NULL=no mask)
wait_sticky keep suspended until one of the wait_sticky sticky signals were triggered (NULL or none set=don't care; continue on any signal)
Definition at line 892 of file kernel.cc.
References ASSERT, current_proc, ESUCCESS, kIsInSigHandler, kMaskSignal(), kYield(), launset, RUNNING, SIG_BLOCK, SIG_SETMASK, _proc_table_t::sig_sticky, SIG_STICKY, _proc_table_t::state, and SUSPENDED.
int kSyncEventHit (pid_t pid, void * event)
Marks specified event as hit.
Increments hit counter corresponding to specified event.
Should only be called from the task daemon.
Parameters:
pid the process to sent the hit to
event the event that has been hit
Returns:
ENOMEM when out of event records, 0 on success, otherwise an errno
Definition at line 1483 of file kernel.cc.
References sync_event_entry_t::event, sync_event_entry_t::hit, kernel_context, kFindEventEntry(), kGetPid(), MAX_PROCESSES, pid, kernel_context_t::proc_table, RUNNING, _proc_table_t::state, and SUSPENDED.
int kSyncEventWait (void * event, int count)
Blocks until a given event has occured.
Parameters:
event the event to wait for
count the number of hits to wait for
Returns:
ENOMEM when out of empty event records, 0 on success, otherwise an errno
Definition at line 1524 of file kernel.cc.
References current_proc, sync_event_entry_t::event, sync_event_entry_t::hit, kFindEventEntry(), kYield(), and sync_event_entry_t::wait.
int kYield (bool havework)
Forcably ends the timeslice of the current process.
Todo:
fix, several race conditions exist!
Parameters:
havework set to false when no work has been done and none is expected soon; this prevents rapid rescheduling
Returns:
0 on success, otherwise an errno
Definition at line 814 of file kernel.cc.
References ASSERT, CONTEXT_SWITCH_CYCLE_PANELTY, current_proc, DID_WORK_MAYBE, DID_WORK_NO, DID_WORK_YES, ESUCCESS, sch_t::have_work, pthread_sch_t::idle, sch_t::just_did_work, kGetPid(), kGetTimer(), kSetTimer(), kTraceYield(), laend(), lastart(), mc_entry_wou, mc_exit_wou, sch_t::pthread_sch, sch_t::remaining_slots, SCHEDULE_SLOTS, _proc_table_t::slack, _proc_table_t::time_yielded, TRACE, sch_t::was_idle, and _proc_table_t::yields.
Referenced by kEndProcess(), kOpenChannel(), kSuspend(), and kSyncEventWait().
void* ProcessEntry (void *(*)(void *) main, void * arg)
Entry point of a process.
Initializes some stuff and calls the entry point as specified using kCreateProcess().
Definition at line 640 of file kernel.cc.
References DEBUG, do_gracefull_exit_funs(), kGetPid(), main, pthread_thread_cleanup(), pthread_thread_init(), TRACE_PHASE_RUNNING, TraceExitProc(), and TracePhaseChange().
Variable Documentation
unsigned int _ddrbase
unsigned int _ddrend
struct _reent* _CONST __ATTRIBUTE_IMPURE_PTR__ _kernel_impure_ptr = &kernel_impure_data
Pointer to global_impure_data.
Definition at line 137 of file kernel.cc.
Referenced by kCheckStackOverflow(), kEndProcess(), and kInitKernel().
void* _text_schedule
void* _text_schedule_base
void* _text_schedule_end
sch_t sch