Starburst: include/sys/kernel.h File Reference
include/sys/kernel.h File Reference
Declaration of all kernel functions.
#include <sys/helix_config.h>
#include <sys/types.h>
#include <sys/device.h>
#include <stdint.h>
#include <reent.h>
#include <sys/hooks.h>
#include <pthread.h>
#include <sys/signal.h>
#include <sys/kernel_types.h>
#include <lock.h>
#include <mail.h>
Data Structures
struct proc_context_t
The context of a process.
struct channel_t
struct sync_event_entry_t
struct proc_local_t
struct _proc_table_t
The process table.
struct kernel_context_t
All information of the kernel.
struct proc_stats_t
struct kernel_boot_param_t
The optional parameter to main(int,char**) when the kernel boots.
Defines
#define GetOSState() os_state
#define SIG_TRIG_HANDLING_SEND 0
#define SIG_TRIG_HANDLING_CONT 1
#define SIG_TRIG_HANDLING_HAND 2
#define SIG_TRIG_HANDLING_ABRT 3
#define _fifomem ((HEAP*)((char*)FIFO_MEM+TASK_DAEMON_FIFO_SIZE+RING_CONSISTENCY_SIZE))
Pointer to the local FIFO memory HEAP structure.
#define _pheap ((HEAP*)kernel_context->heap)
Pointer to the HEAP structure of this processor.
#define printk printf
#define CHAN_LABEL_PROC NUM_PROCESSORS
#define CHAN_LABEL_COND 0x10000000
Typedefs
typedef unsigned int cpureg_t
Type of a register of the cpu.
typedef struct _proc_table_t proc_table_t
The process table.
Enumerations
enum os_state_t {
OS_BOOT = 0, OS_INIT = 1, OS_SINGLE = 2, OS_MULTI = 3,
OS_SOC = 4, OS_SHUTDOWN = 5
}
enum proc_state_t {
NOPROC, NEW, RUNNING, SUSPENDED,
JOINABLE, ZOMBIE
}
The states of a process.
Functions
pid_t kGetPid () _NO_THROW
Returns the process id of the current process.
int kCreateProcess (pid_t &pid, void *(*main)(void *), void *argt=NULL, timems_t slicelength=PROC_DEFAULT_TIMESLICE, unsigned int stack=PROC_DEFAULT_STACK) _NO_THROW
Creates a new process.
void * ProcessEntry (void *(*main)(void *), void *arg) _NO_THROW
Entry point of a process.
int kGetProcessFlags (pid_t pid, int *flags) _NO_THROW
Gets the process flags.
int kSetProcessFlags (pid_t pid, int flags) _NO_THROW
Sets specific process flags.
int kGetProcessState (pid_t pid, proc_state_t *state, bool *sighandling=NULL) _NO_THROW
Returns the state of a process.
int kSetProcessTimeslice (pid_t pid, timems_t slicelength) _NO_THROW
Changes the length of the timeslice of an existing process.
timeslice_t GetRemainingTimeslice () _NO_THROW
Returns the remaining clock ticks before the end of the current timeslice.
int kGetProcessStats (pid_t pid, proc_stats_t *stats) _NO_THROW
Collects statistics of the specified process.
int kStartProcess (pid_t) _NO_THROW
Starts a process that has been created using kCreateProcess().
int kYield (bool havework=true) _NO_THROW
Forcably ends the timeslice of the current process.
int kSuspend (const sigset_t *mask=NULL, const sigset_t *wait_sticky=NULL) _NO_THROW
Suspends current process until one of the non-masked signals occur.
void kEndProcess (void *ret) _NO_THROW __attribute__((noreturn))
Ends the current process.
int kJoinProcess (pid_t pid, void **ret) _NO_THROW
Joins a JOINABLE process.
int kDestroyProcess (pid_t pid, void **ret) _NO_THROW
Destroys and clean up a process.
int kGetZombie (pid_t *pid, void **ret) _NO_THROW
Looks for a ZOMBIE process and destroys it.
int kCoreDump () _NO_THROW
Prints complete state of the current process and the kernel.
int kGetProcLocal (proc_local_t **p) _NO_THROW
int kGetChannelCount (pid_t pid) _NO_THROW
Returns the number of allocated channels.
int kAllocChannels (pid_t pid, int num_chan) _NO_THROW
Allocates memory for channels.
int kAssignChannel (pid_t pid, int chan_id, void *channel, int label=0) _NO_THROW
Assigns a pointer to a channel.
int kSetChannelLabel (pid_t pid, int chan_id, int label) _NO_THROW
Sets a new label to an existing channel.
int kFindChannel (int label) _NO_THROW
Looks for a channel with the specified label.
void * kOpenChannel (int channel) _NO_THROW
Returns the pointer corresponding to the given channel of the current process.
hook_t * kGetHookTable () _NO_THROW
Returns the pointer to the hook table.
int kSetSignalHandler (int signum, const struct sigaction *act) _NO_THROW
int kClearSignal (int signum, struct sigaction *sa) _NO_THROW
int kSendSignal (pid_t pid, int sig, union sigval *si) _NO_THROW
Send signal to other process.
int kMaskSignal (int how, const sigset_t *set, sigset_t *oldset) _NO_THROW
int kSyncEventHit (pid_t pid, void *event) _NO_THROW
Marks specified event as hit.
int kSyncEventWait (void *event, int count) _NO_THROW
Blocks until a given event has occured.
void kPanic (const char *msg) _NO_THROW __attribute__((noreturn))
Prints coredump and halts kernel, in case of emergency.
int kShutdown () _NO_THROW
Shuts down kernel and return to bootloader.
void kScheduleNext () _NO_THROW __attribute__((section(".text.schedule")))
Determines the next process to schedule.
void kInitContext (proc_context_t *new_context, void *(*main)(void *), void *arg, void *sp) _NO_THROW
Initializes a context of a newly created process.
void kEnableInterrupt () _NO_THROW
Enables interrupts in the processor.
void kDisableInterrupt () _NO_THROW
void kReset () _NO_THROW __attribute__((noreturn))
Variables
os_state_t const os_state
proc_table_t *const current_proc
currently running process
proc_context_t *const current_context
location to store context of currently running process
proc_local_t *const proc_local
void **const thread_local
array of thread-local data with size THREAD_LOCAL_FIELDS, initially all set to 0
kernel_context_t * kernel_context
pointer to our kernel_context, equals kernel_contexts[GetProcID()]
unsigned int * kernel_stack
equals &kernel_context->stack[KERNEL_STACK_SIZE]
struct _reent
*__ATTRIBUTE_IMPURE_PTR__ _impure_ptr
thread-local reentrancy struct of newlib, must point to process's proc_table_t::impure_data
struct _reent *_CONST
__ATTRIBUTE_IMPURE_PTR__ _global_impure_ptr
process-global reentrancy struct of newlib, must point to process's proc_table_t::impure_data
Detailed Description
Declaration of all kernel functions.
Definition in file kernel.h.
Define Documentation
#define _fifomem ((HEAP*)((char*)FIFO_MEM+TASK_DAEMON_FIFO_SIZE+RING_CONSISTENCY_SIZE))
Pointer to the local FIFO memory HEAP structure.
Definition at line 202 of file kernel.h.
Referenced by fcalloc(), ffree(), ffreeAll(), fmalloc(), fmown(), frealloc(), kInitKernel(), and kPanic().
#define _pheap ((HEAP*)kernel_context->heap)
Pointer to the HEAP structure of this processor.
Definition at line 204 of file kernel.h.
Referenced by calloc(), free(), freeAll(), MallocDaemonHandler(), mown(), omalloc(), and orealloc().
#define CHAN_LABEL_COND 0x10000000
Definition at line 269 of file kernel.h.
#define CHAN_LABEL_PROC NUM_PROCESSORS
Definition at line 268 of file kernel.h.
#define GetOSState () os_state
Definition at line 28 of file kernel.h.
Referenced by GetIssueSlot(), kCoreDump(), TraceDump(), and TraceDumpAll().
#define printk printf
Definition at line 262 of file kernel.h.
Referenced by Disclaimer(), kCoreDump(), kEndProcess(), kInitKernel(), kPanic(), and malloc_dump().
#define SIG_TRIG_HANDLING_ABRT 3
Definition at line 154 of file kernel.h.
Referenced by __wrap_exit(), and kScheduleProcess().
#define SIG_TRIG_HANDLING_CONT 1
Definition at line 152 of file kernel.h.
Referenced by kScheduleProcess(), and kSendSignal().
#define SIG_TRIG_HANDLING_HAND 2
Definition at line 153 of file kernel.h.
Referenced by kScheduleProcess().
#define SIG_TRIG_HANDLING_SEND 0
Definition at line 151 of file kernel.h.
Referenced by kSendSignal().
Typedef Documentation
typedef unsigned int cpureg_t
Type of a register of the cpu.
Definition at line 57 of file kernel.h.
typedef struct _proc_table_t proc_table_t
The process table.
Enumeration Type Documentation
enum os_state_t
Enumerator:
OS_BOOT
OS_INIT
OS_SINGLE
OS_MULTI
OS_SOC
OS_SHUTDOWN
Definition at line 18 of file kernel.h.
enum proc_state_t
The states of a process.
Enumerator:
NOPROC
invalid process
NEW
process has been created, but not started
RUNNING
process has been started and can be scheduled
SUSPENDED
process waits for signal
JOINABLE
process has ended, but waits until kJoinProcess() is called
ZOMBIE
process has ended, but not cleaned up
Definition at line 46 of file kernel.h.
Function Documentation
timeslice_t GetRemainingTimeslice ()
Returns the remaining clock ticks before the end of the current timeslice.
When interrupted by the timer, race conditions can occur, which result in a reported timeslice that is too high.
Call from user space, does not need a syscall.
Returns:
the number of remaining clock cycles.
Definition at line 763 of file kernel.cc.
References current_proc, kGetTimer(), sch_t::remaining_slots, SCHEDULE_SLOTS, and _proc_table_t::time_yielded.
Referenced by TraceRelTime().
int kAllocChannels (pid_t pid, int num_chan)
Allocates memory for channels.
When called multiple times, the allocated memory will be resized.
Parameters:
pid process to allocate channel memory for
num_chan number of channels to allocate, will be initialized to NULL
Returns:
0 on success, otherwise an errno
Definition at line 1198 of file kernel.cc.
References channel_t::channel, _proc_table_t::channels, ESUCCESS, kernel_context, channel_t::label, MAX_PROCESSES, _proc_table_t::num_channels, orealloc(), pid, and kernel_context_t::proc_table.
Referenced by kAssignChannel().
int kAssignChannel (pid_t pid, int chan_id, void * channel, int label)
Assigns a pointer to a channel.
Parameters:
pid process to assign a channel to
chan_id channel to assign the pointer to, must be less than num_chan of a previous kAllocChannels() call, when set to -1, a new channel is allocated at the end of the list
channel to store in the channel list
label an alternative label of the channel (set to 0 for no label, all negative labels are reserved by the kernel)
Returns:
0 on success, otherwise an errno
Definition at line 1226 of file kernel.cc.
References channel_t::channel, _proc_table_t::channels, DID_WORK_YES, ESUCCESS, sch_t::just_did_work, kAllocChannels(), kernel_context, channel_t::label, MAX_PROCESSES, _proc_table_t::num_channels, pid, and kernel_context_t::proc_table.
int kClearSignal (int signum, struct sigaction * sa)
Definition at line 1325 of file kernel.cc.
References _sig_def_func, current_proc, ESUCCESS, kMaskSignal(), NSIG, sigaction::sa_flags, sigaction::sa_handler, sigaction::sa_mask, SA_RESETHAND, _proc_table_t::sig_action, SIG_BLOCK, _proc_table_t::sig_enabled, _proc_table_t::sig_triggered, and sigaddset().
int kCoreDump ()
Prints complete state of the current process and the kernel.
Returns:
0 on success, otherwise an errno
Definition at line 1123 of file kernel.cc.
References current_context, current_proc, ESUCCESS, _proc_table_t::flags, proc_context_t::fsr, GetClockFreq(), GetOSState, GetProcID(), IS_VALID_DDR_PTR, kernel_context, _proc_table_t::main, MAX_PROCESSES, _proc_table_t::min_stack, proc_context_t::msr, _proc_table_t::pid, printk, kernel_context_t::proc_table, proc_context_t::regs, _proc_table_t::stack, _proc_table_t::state, _proc_table_t::time, and _proc_table_t::time_yielded.
Referenced by kPanic().
int kCreateProcess (pid_t & pid, void *(*)(void *) main, void * arg, timems_t slicelength, unsigned int stack)
Creates a new process.
By default, a process is created detached.
Only the task daemon is allowed to start new processes.
Parameters:
pid the new process id will be written to the pointer supplied
main the main function of this process
arg an optional argument to main, can be NULL
slicelength the length of the allocated time slice in ms
stack the size of the stack in words
Returns:
0 on success, otherwise an errno
Definition at line 545 of file kernel.cc.
References DBLED_NEWPROC, DEBUG_ON, ESUCCESS, InitSignalList(), kDestroyProcess(), kernel_context, kGetPid(), kInitContext(), kInitSignalContext(), kSetProcessTimeslice(), main, MAX_PROCESSES, mc_apply, MEASURE_STACK_USAGE, NEW, NOPROC, omalloc(), pid, PROC_FLAG_DETACHED, kernel_context_t::proc_table, pthread_sch_t::processes, sch_t::pthread_sch, sigemptyset(), sigfillset(), and STACK_PROTECTION_VALUE.
Referenced by kStartTaskDaemon().
int kDestroyProcess (pid_t pid, void ** ret)
Destroys and clean up a process.
Only the task daemon is allowed to destroy processes. All allocated memory will be freeed. Process statistics is not deleted, so after destroying a process, kGetProcessStats() can be called. A process cannot destroy itself.
Parameters:
pid process to destroy
ret a pointer to store the return value of the process, can be NULL, holds unknown data when a non-ZOMBIE process is destroyed
Returns:
0 on success, otherwise an errno
Definition at line 1017 of file kernel.cc.
References ESUCCESS, ffreeAll(), freeAll(), kernel_context, kGetPid(), kTraceProcChange(), MAX_PROCESSES, mc_apply, _proc_table_t::next_entry, NOPROC, pid, _proc_table_t::prev_entry, kernel_context_t::proc_table, pthread_sch_t::processes, sch_t::pthread_sch, _proc_table_t::ret, _proc_table_t::state, td_proc, TRACE, and ZOMBIE.
Referenced by kCreateProcess(), and kGetZombie().
void kDisableInterrupt ()
Referenced by kPanic(), and kShutdown().
void kEnableInterrupt ()
Enables interrupts in the processor.
The function is implemented by entry.S.
Referenced by kStartScheduling().
void kEndProcess (void * ret)
Ends the current process.
Will be called automatically when the main function of a process returns. The timeslice will always be ended by a call to kYield().
Parameters:
ret the value returned by the main of the process, which can be retrieved using kJoinProcess() and kDestroyProcess()
Returns:
never
Definition at line 944 of file kernel.cc.
References _impure_ptr, _kernel_impure_ptr, current_context, current_proc, _proc_table_t::flags, GetProcID(), JOINABLE, kGetPid(), kPanic(), kYield(), _proc_table_t::main, _proc_table_t::min_stack, printk, PROC_FLAG_JOINABLE, _proc_table_t::ret, _proc_table_t::stack, STACK_PROTECTION_VALUE, _proc_table_t::state, and ZOMBIE.
int kFindChannel (int label)
Looks for a channel with the specified label.
Parameters:
label the label to look for
Returns:
the channel id of the channel with the specified label, or -1 when not found
Definition at line 1271 of file kernel.cc.
References _proc_table_t::channels, current_proc, channel_t::label, and _proc_table_t::num_channels.
int kGetChannelCount (pid_t pid)
Returns the number of allocated channels.
This does not indicate whether channels are assigned or in use.
Parameters:
pid the process to get the information of
Returns:
The channel count or -1 when an invalid pid is supplied
Definition at line 1179 of file kernel.cc.
References _proc_table_t::channels, kernel_context, MAX_PROCESSES, NOPROC, _proc_table_t::num_channels, pid, kernel_context_t::proc_table, and _proc_table_t::state.
hook_t* kGetHookTable ()
Returns the pointer to the hook table.
The memory region of the hook table is owned by the TaskDaemon (pid 0).
Returns:
cannot be NULL during normal operation (it can be null during kernel initialization, just before the table is initialized)
Definition at line 1301 of file kernel.cc.
References kernel_context.
Referenced by kInitKernel().
pid_t kGetPid ()
Returns the process id of the current process.
Definition at line 530 of file kernel.cc.
References current_proc, and _proc_table_t::pid.
Referenced by kCheckStackOverflow(), kCreateProcess(), kDestroyProcess(), kEndProcess(), kGetProcessState(), kGetZombie(), kShutdown(), kStartProcess(), kSyncEventHit(), kYield(), and ProcessEntry().
int kGetProcessFlags (pid_t pid, int * flags)
Gets the process flags.
Parameters:
pid the process to retrieve the flags of
flags will receive the flags of the process, cannot be NULL
Returns:
0 on success, otherwise an errno
Definition at line 687 of file kernel.cc.
References ESUCCESS, _proc_table_t::flags, kernel_context, MAX_PROCESSES, NOPROC, pid, kernel_context_t::proc_table, and _proc_table_t::state.
int kGetProcessState (pid_t pid, proc_state_t * state, bool * sighandling)
Returns the state of a process.
Parameters:
pid the process to retrieve the state of, -1 means myself
state will receive the state of the process
sighandling will set to true when the process is currently handling signals
Returns:
0 on success, otherwise an errno
Definition at line 706 of file kernel.cc.
References current_proc, ESUCCESS, kernel_context, kGetPid(), kIsInSigHandler, MAX_PROCESSES, NOPROC, pid, kernel_context_t::proc_table, _proc_table_t::state, and unlikely.
int kGetProcessStats (pid_t pid, proc_stats_t * stats)
Collects statistics of the specified process.
Parameters:
pid the process to collect statistics of (can be an non-existing process)
stats pointer to struct to write statistics to
Returns:
0 on success, otherwise an errno
Definition at line 1087 of file kernel.cc.
References _proc_table_t::context, proc_stats_t::context, _proc_table_t::context_switches, proc_stats_t::context_switches, ESUCCESS, _proc_table_t::flags, proc_stats_t::flags, GetClockFreq(), proc_stats_t::insighandler, kernel_context, kIsInSigHandler, _proc_table_t::main, proc_stats_t::main, MAX_PROCESSES, _proc_table_t::min_stack, proc_stats_t::min_stack, proc_stats_t::pid, pid, kernel_context_t::proc_table, SCHEDULE_SLOTS, _proc_table_t::slack, proc_stats_t::slice_length, proc_stats_t::slice_slack, proc_stats_t::slice_used, _proc_table_t::state, proc_stats_t::state, _proc_table_t::time, _proc_table_t::time_alloc, _proc_table_t::yields, and proc_stats_t::yields.
int kGetProcLocal (proc_local_t ** p)
Definition at line 1160 of file kernel.cc.
References current_proc, ESUCCESS, and _proc_table_t::proc_local.
int kGetZombie (pid_t * pid, void ** ret)
Looks for a ZOMBIE process and destroys it.
Walks over all processes and cleans up the first ZOMBIE process it can find. Only the task daemon is allowed to call the function.
Parameters:
pid the process that has been cleaned up, can be NULL
ret pointer to store the return value of the process in, can be NULL
Returns:
0 on success, EAGAIN when no ZOMBIEs has been found, otherwise an appropriate errno
Definition at line 1066 of file kernel.cc.
References kDestroyProcess(), kernel_context, kGetPid(), MAX_PROCESSES, kernel_context_t::proc_table, _proc_table_t::state, and ZOMBIE.
void kInitContext (proc_context_t * new_context, void *(*)(void *) main, void * arg, void * sp)
Initializes a context of a newly created process.
The function is implemented by entry.S.
Parameters:
new_context a pointer to the context-to-be-initialized
main a pointer to the process's function
arg optional argument to the main, can be NULL
sp pointer to the top of the stack of this process
Referenced by kCreateProcess().
int kJoinProcess (pid_t pid, void ** ret)
Joins a JOINABLE process.
Gets the return value of the process to join. Never blocks, so wrap in a loop when it is intended to wait until the process finishes. A JOINABLE process will become a ZOMBIE when the join is successful. The function is not thread-safe.
Parameters:
pid process to join
ret pointer to store the return value of the process to join, can be NULL
Returns:
0 on success, EAGAIN when pid was not JOINABLE, otherwise an appropiate errno
Definition at line 982 of file kernel.cc.
References ESUCCESS, _proc_table_t::flags, JOINABLE, kernel_context, MAX_PROCESSES, NOPROC, pid, PROC_FLAG_JOINABLE, kernel_context_t::proc_table, _proc_table_t::ret, _proc_table_t::state, and ZOMBIE.
int kMaskSignal (int how, const sigset_t * set, sigset_t * oldset)
Definition at line 1416 of file kernel.cc.
References current_proc, ESUCCESS, SIG_BLOCK, SIG_BLOCKABLE, _proc_table_t::sig_mask, SIG_SETMASK, SIG_UNBLOCK, sigandset(), and sigorset().
Referenced by kClearSignal(), and kSuspend().
void* kOpenChannel (int channel)
Returns the pointer corresponding to the given channel of the current process.
Blocks and kYield()s until the given channel is not NULL. Note that the specified channel is not checked for validity.
Parameters:
channel channel to open
Returns:
pointer corresponding to the channel, cannot be NULL
Definition at line 1289 of file kernel.cc.
References channel_t::channel, _proc_table_t::channels, current_proc, kYield(), and _proc_table_t::num_channels.
void kPanic (const char * msg)
Prints coredump and halts kernel, in case of emergency.
Parameters:
msg message to be printed, which indicates the reason of the core dump. Can be NULL.
Definition at line 468 of file kernel.cc.
References _fifomem, _puts(), DBLED_PANIC, DEBUG_ON, DisableDCache(), DisableICache(), FlushDCache(), GetProcID(), gettimeofday(), kernel_context_t::heap, kCoreDump(), kDisableInterrupt(), kernel_context, kReset(), kSetOSState, kStopTimer(), malloc_dump(), OS_BOOT, and printk.
Referenced by kCheckStackOverflow(), kEndProcess(), kInitKernel(), and kStartTaskDaemon().
void kReset ()
Referenced by kPanic(), and kShutdown().
void kScheduleNext ()
Determines the next process to schedule.
This function is called by entry.S after an interrupt.
Definition at line 1679 of file kernel.cc.
References ASSERT, current_proc, DBLED_SCHEDULE, DEBUG_OFF, DEBUG_ON, DID_WORK_NO, DID_WORK_YES, sch_t::have_work, sch_t::just_did_work, kCheckFreeStack(), kCheckStackOverflow(), kScheduleProcess(), kTraceClose(), kTraceScheduleYield(), likely, _proc_table_t::next_entry, _proc_table_t::prev_entry, sch_t::remaining_slots, RUNNING, SCHEDULE_SLOTS, _proc_table_t::sig_havetriggered, _proc_table_t::sig_ret, sch_t::skip_taskdaemon, _proc_table_t::slack, _proc_table_t::state, SUSPENDED, td_proc, _proc_table_t::time_yielded, TRACE, and unlikely.
int kSendSignal (pid_t pid, int sig, union sigval * sv)
Send signal to other process.
A signal will only be triggered (and thus handled) once.
When the signal was already triggered, the previous sv will be overwritten.
Parameters:
pid the process to send to
sig the signal number to send
sv value to pass to the handler by siginfo_t
Returns:
ESRCH when the process does not exist (anymore), ENOENT when the signal was disabled, EAGAIN when masked, 0 on accept, otherwise another errno
Definition at line 1365 of file kernel.cc.
References DID_WORK_YES, ESUCCESS, sch_t::just_did_work, kernel_context, laset, MAX_PROCESSES, NSIG, pid, kernel_context_t::proc_table, RUNNING, _proc_table_t::sig_action, _proc_table_t::sig_enabled, _proc_table_t::sig_mask, _proc_table_t::sig_sticky, SIG_STICKY, _proc_table_t::sig_trig_handling, SIG_TRIG_HANDLING_CONT, SIG_TRIG_HANDLING_SEND, _proc_table_t::sig_triggered, SIGCONT, sigismember(), _proc_table_t::state, SUSPENDED, and sigaction::sv.
int kSetChannelLabel (pid_t pid, int chan_id, int label)
Sets a new label to an existing channel.
Parameters:
pid process that has the channel to change the label of
chan_id the channel to change the label of
label the new label, where 0 means 'no label'
Returns:
0 on success, otherwise an errno
Definition at line 1256 of file kernel.cc.
References _proc_table_t::channels, ESUCCESS, kernel_context, channel_t::label, MAX_PROCESSES, _proc_table_t::num_channels, pid, and kernel_context_t::proc_table.
int kSetProcessFlags (pid_t pid, int flags)
Sets specific process flags.
It is not safe to set the flags and join/destroy the process concurrent.
So, do process management of a single process in a safe manner.
Returns:
0 on success, otherwise an errno
Definition at line 662 of file kernel.cc.
References ESUCCESS, _proc_table_t::flags, JOINABLE, kernel_context, MAX_PROCESSES, NOPROC, pid, PROC_FLAG_DETACHED, kernel_context_t::proc_table, _proc_table_t::state, and ZOMBIE.
int kSetProcessTimeslice (pid_t pid, timems_t slicelength)
Changes the length of the timeslice of an existing process.
When pid is the current process, the new time is effective after the next context switch
Parameters:
pid the process to change the timeslice of, which must exist
slicelength the length of the allocated time slice in ms
Returns:
0 on success, otherwise an errno
Definition at line 732 of file kernel.cc.
References ESUCCESS, GetClockFreq(), kernel_context, kTraceProcChange(), _proc_table_t::main, MAX_PROCESSES, NOPROC, pid, kernel_context_t::proc_table, _proc_table_t::state, _proc_table_t::time, and TRACE.
Referenced by kCreateProcess().
int kSetSignalHandler (int signum, const struct sigaction * act)
Definition at line 1305 of file kernel.cc.
References current_proc, ESUCCESS, NSIG, sigaction::sa_handler, _proc_table_t::sig_action, _proc_table_t::sig_enabled, SIG_HANDLEABLE, _proc_table_t::sig_triggered, sigaddset(), SIGCONT, and sigdelset().
int kShutdown ()
Shuts down kernel and return to bootloader.
Not gracefull, no process termination, just reboot immediately.
Returns:
EPERM when another process than the task daemon tries to shutdown, otherwise never
Definition at line 509 of file kernel.cc.
References DisableDCache(), DisableICache(), kDisableInterrupt(), kGetPid(), kReset(), and TDEBUG.
int kStartProcess (pid_t pid)
Starts a process that has been created using kCreateProcess().
Only the task daemon is allowed to start processes.
Parameters:
pid the process to start
Returns:
0 on success, otherwise an errno
Definition at line 779 of file kernel.cc.
References current_proc, DBLED_NEWPROC, DEBUG_OFF, DID_WORK_YES, ESUCCESS, sch_t::just_did_work, kernel_context, kGetPid(), MAX_PROCESSES, NEW, _proc_table_t::next_entry, pid, _proc_table_t::prev_entry, kernel_context_t::proc_table, RUNNING, _proc_table_t::state, and td_proc.
Referenced by kStartTaskDaemon().
int kSuspend (const sigset_t * mask, const sigset_t * wait_sticky)
Suspends current process until one of the non-masked signals occur.
Cannot be called from within a signal handler
Parameters:
mask ignore all signals specified in this set (NULL=no mask)
wait_sticky keep suspended until one of the wait_sticky sticky signals were triggered (NULL or none set=don't care; continue on any signal)
Definition at line 892 of file kernel.cc.
References ASSERT, current_proc, ESUCCESS, kIsInSigHandler, kMaskSignal(), kYield(), launset, RUNNING, SIG_BLOCK, SIG_SETMASK, _proc_table_t::sig_sticky, SIG_STICKY, _proc_table_t::state, and SUSPENDED.
int kSyncEventHit (pid_t pid, void * event)
Marks specified event as hit.
Increments hit counter corresponding to specified event.
Should only be called from the task daemon.
Parameters:
pid the process to sent the hit to
event the event that has been hit
Returns:
ENOMEM when out of event records, 0 on success, otherwise an errno
Definition at line 1483 of file kernel.cc.
References sync_event_entry_t::event, sync_event_entry_t::hit, kernel_context, kFindEventEntry(), kGetPid(), MAX_PROCESSES, pid, kernel_context_t::proc_table, RUNNING, _proc_table_t::state, and SUSPENDED.
int kSyncEventWait (void * event, int count)
Blocks until a given event has occured.
Parameters:
event the event to wait for
count the number of hits to wait for
Returns:
ENOMEM when out of empty event records, 0 on success, otherwise an errno
Definition at line 1524 of file kernel.cc.
References current_proc, sync_event_entry_t::event, sync_event_entry_t::hit, kFindEventEntry(), kYield(), and sync_event_entry_t::wait.
int kYield (bool havework)
Forcably ends the timeslice of the current process.
Todo:
fix, several race conditions exist!
Parameters:
havework set to false when no work has been done and none is expected soon; this prevents rapid rescheduling
Returns:
0 on success, otherwise an errno
Definition at line 814 of file kernel.cc.
References ASSERT, CONTEXT_SWITCH_CYCLE_PANELTY, current_proc, DID_WORK_MAYBE, DID_WORK_NO, DID_WORK_YES, ESUCCESS, sch_t::have_work, pthread_sch_t::idle, sch_t::just_did_work, kGetPid(), kGetTimer(), kSetTimer(), kTraceYield(), laend(), lastart(), mc_entry_wou, mc_exit_wou, sch_t::pthread_sch, sch_t::remaining_slots, SCHEDULE_SLOTS, _proc_table_t::slack, _proc_table_t::time_yielded, TRACE, sch_t::was_idle, and _proc_table_t::yields.
Referenced by kEndProcess(), kOpenChannel(), kSuspend(), and kSyncEventWait().
void* ProcessEntry (void *(*)(void *) main, void * arg)
Entry point of a process.
Initializes some stuff and calls the entry point as specified using kCreateProcess().
Definition at line 640 of file kernel.cc.
References DEBUG, do_gracefull_exit_funs(), kGetPid(), main, pthread_thread_cleanup(), pthread_thread_init(), TRACE_PHASE_RUNNING, TraceExitProc(), and TracePhaseChange().
Variable Documentation
struct _reent* _CONST __ATTRIBUTE_IMPURE_PTR__ _global_impure_ptr
process-global reentrancy struct of newlib, must point to process's proc_table_t::impure_data
Is defined in entry.S
struct _reent* __ATTRIBUTE_IMPURE_PTR__ _impure_ptr
thread-local reentrancy struct of newlib, must point to process's proc_table_t::impure_data
Is defined in entry.S
Referenced by kCheckStackOverflow(), kEndProcess(), kInitKernel(), and kScheduleProcess().
proc_context_t* const current_context
location to store context of currently running process
Is defined in entry.S
Referenced by kCheckFreeStack(), kCheckStackOverflow(), kCoreDump(), kEndProcess(), kInitKernel(), and kScheduleProcess().
proc_table_t* const current_proc
currently running process
Is defined in entry.S
Referenced by __wrap_exit(), GetRemainingTimeslice(), kCheckFreeStack(), kCheckStackOverflow(), kClearSignal(), kCoreDump(), kEndProcess(), kFindChannel(), kGetPid(), kGetProcessState(), kGetProcLocal(), kInitKernel(), kMaskSignal(), kOpenChannel(), kScheduleNext(), kScheduleProcess(), kSetSignalHandler(), kStartProcess(), kSuspend(), kSyncEventWait(), and kYield().
kernel_context_t* kernel_context
pointer to our kernel_context, equals kernel_contexts[GetProcID()]
Is defined in entry.S
Referenced by kAllocChannels(), kAssignChannel(), kCoreDump(), kCreateProcess(), kDestroyProcess(), kGetChannelCount(), kGetHookTable(), kGetProcessFlags(), kGetProcessState(), kGetProcessStats(), kGetZombie(), kInitKernel(), kJoinProcess(), kPanic(), kSendSignal(), kSetChannelLabel(), kSetProcessFlags(), kSetProcessTimeslice(), kStartProcess(), and kSyncEventHit().
unsigned int* kernel_stack
equals &kernel_context->stack[KERNEL_STACK_SIZE]
Is defined in entry.S
Referenced by kInitKernel().
os_state_t const os_state
proc_local_t* const proc_local
Referenced by kScheduleProcess(), mc_error(), and mc_set_error().
void** const thread_local
array of thread-local data with size THREAD_LOCAL_FIELDS, initially all set to 0
Referenced by kScheduleProcess(), MallocDaemon(), MallocDaemonHandler(), and StatsInit().