Starburst: kernel/signal.cc File Reference
kernel/signal.cc File Reference
Signal handler functions.
#include <sys/api.h>
#include <stdio.h>
Defines
#define DEBUG(str, a...) printf("Process %d@%d: " str "\n",getpid(),GetProcID(),##a)
Functions
void DefaultSignalHandler (int sig)
void SilentSignalHandler (int sig)
void DefaultAbortSignalHandler (int sig)
void InitSignalList (struct sigaction *sa)
void SignalDispatcher (sigset_t sigs)
Variables
const sighandler_t _sig_def_func [NSIG]
Detailed Description
Signal handler functions.
Definition in file signal.cc.
Define Documentation
#define DEBUG (str, a...) printf("Process %d@%d: " str "\n",getpid(),GetProcID(),##a)
Definition at line 9 of file signal.cc.
Referenced by DefaultAbortSignalHandler(), and DefaultSignalHandler().
Function Documentation
void DefaultAbortSignalHandler (int sig)
Definition at line 25 of file signal.cc.
References abort(), and DEBUG.
void DefaultSignalHandler (int sig)
Definition at line 18 of file signal.cc.
References DEBUG.
void InitSignalList (struct sigaction * sa)
Definition at line 30 of file signal.cc.
References _sig_def_func, and NSIG.
Referenced by kCreateProcess().
void SignalDispatcher (sigset_t sigs)
Definition at line 35 of file signal.cc.
References __attribute__, ClearSignal(), MaskSignal(), NSIG, sigaction::sa_flags, sigaction::sa_mask, SA_NODEFER, sigaction::sa_sigaction, siginfo_t::si_code, siginfo_t::si_signo, siginfo_t::si_value, SIG_SETMASK, sigdelset(), sigismember(), sigaction::sv, TRACE_PHASE_SIGNAL, TracePhaseChange(), and unlikely.
void SilentSignalHandler (int sig)
Definition at line 22 of file signal.cc.
Variable Documentation
const sighandler_t _sig_def_func[NSIG]
Definition at line 67 of file signal.cc.
Referenced by InitSignalList(), and kClearSignal().