Starburst: posix/key.cc File Reference
posix/key.cc File Reference
POSIX key implementation.
#include <sys/api.h>
#include <mc.h>
#include <pthread.h>
Data Structures
struct pthread_key_admin_t
Defines
#define LOCAL_INIT(p) {int res;if((res=GetProcLocal(&(p))))return res;}
#define KEY_LOCK {int res;if(GetOSState()>=OS_MULTI&&(res=pthread_mutex_lock(&pthread_key_mutex)))return res;}
#define KEY_UNLOCK {int res;if(GetOSState()>=OS_MULTI&&(res=pthread_mutex_unlock(&pthread_key_mutex)))return res;}
Functions
int pthread_key_create (pthread_key_t *key, void(*destructor)(void *))
int pthread_key_delete (pthread_key_t key)
void * pthread_getspecific (pthread_key_t key)
int pthread_setspecific (pthread_key_t key, const void *value)
int pthread_key_global_init ()
int pthread_key_global_cleanup ()
int pthread_key_thread_init ()
int pthread_key_thread_cleanup ()
Variables
pthread_key_admin_t pthread_key_admin
pthread_mutex_t pthread_key_mutex
Detailed Description
POSIX key implementation.
Definition in file key.cc.
Define Documentation
#define KEY_LOCK {int res;if(GetOSState()>=OS_MULTI&&(res=pthread_mutex_lock(&pthread_key_mutex)))return res;}
Definition at line 11 of file key.cc.
Referenced by pthread_key_create(), and pthread_key_delete().
#define KEY_UNLOCK {int res;if(GetOSState()>=OS_MULTI&&(res=pthread_mutex_unlock(&pthread_key_mutex)))return res;}
Definition at line 13 of file key.cc.
Referenced by pthread_key_create(), and pthread_key_delete().
#define LOCAL_INIT (p) {int res;if((res=GetProcLocal(&(p))))return res;}
Definition at line 9 of file key.cc.
Referenced by pthread_key_create(), pthread_key_delete(), pthread_key_thread_cleanup(), pthread_key_thread_init(), and pthread_setspecific().
Function Documentation
void* pthread_getspecific (pthread_key_t key)
Definition at line 72 of file key.cc.
References abort(), GetProcLocal(), mc_entry_ro, mc_exit_ro, proc_local_t::pthread_key, pthread_key_admin_t::pthread_key_nr, proc_local_t::pthread_key_nr, and PTHREAD_KEYS_MAX.
Referenced by pthread_key_thread_cleanup(), pthread_stats_elem_register(), and pthread_stats_elem_unregister().
int pthread_key_create (pthread_key_t * key, void(*)(void *) destructor)
Definition at line 25 of file key.cc.
References KEY_LOCK, KEY_UNLOCK, LOCAL_INIT, pthread_key_admin_t::pthread_key_destructor, pthread_key_admin_t::pthread_key_nr, and PTHREAD_KEYS_MAX.
Referenced by pthread_stats_global_init().
int pthread_key_delete (pthread_key_t key)
Definition at line 53 of file key.cc.
References KEY_LOCK, KEY_UNLOCK, LOCAL_INIT, and PTHREAD_KEYS_MAX.
Referenced by pthread_stats_global_cleanup().
int pthread_key_global_cleanup (void)
Definition at line 134 of file key.cc.
References pthread_mutex_destroy().
Referenced by pthread_global_cleanup().
int pthread_key_global_init (void)
Definition at line 116 of file key.cc.
References mc_entry_wou, mc_exit_wou, pthread_key_admin_t::pthread_key_nr, PTHREAD_KEYS_MAX, pthread_mutex_init(), PTHREAD_MUTEXATTR_INITIALIZER, and pthread_mutexattr_protect().
Referenced by pthread_global_init().
int pthread_key_thread_cleanup (void)
Definition at line 147 of file key.cc.
References LOCAL_INIT, mc_entry_ro, mc_exit_ro, PTHREAD_DESTRUCTOR_ITERATIONS, pthread_getspecific(), pthread_key_admin_t::pthread_key_destructor, and pthread_setspecific().
Referenced by pthread_thread_cleanup().
int pthread_key_thread_init (void)
Definition at line 139 of file key.cc.
References LOCAL_INIT, proc_local_t::pthread_key_nr, and PTHREAD_KEYS_MAX.
Referenced by pthread_thread_init().
int pthread_setspecific (pthread_key_t key, const void * value)
Definition at line 97 of file key.cc.
References LOCAL_INIT, mc_entry_ro, mc_exit_ro, proc_local_t::pthread_key, pthread_key_admin_t::pthread_key_nr, proc_local_t::pthread_key_nr, and PTHREAD_KEYS_MAX.
Referenced by pthread_key_thread_cleanup(), and pthread_stats_thread_init().
Variable Documentation
pthread_key_admin_t pthread_key_admin
Definition at line 22 of file key.cc.
pthread_mutex_t pthread_key_mutex
Definition at line 23 of file key.cc.