Starburst: io/leds.cc File Reference
io/leds.cc File Reference
Low-level functions to control the LEDs.
#include <sys/io.h>
#include <sys/helix_config.h>
#include "iodebug.h"
Functions
void led_on (int led)
Turns on the led with the given number.
void led_off (int led)
Turns off the led with the given number.
void leds_on (int ledmask)
Turns on leds corresponding to the masked bits.
void leds_off (int ledmask)
Turns off leds corresponding to the masked bits.
void leds_value (int leds)
Controls all leds simultaneously.
void posled_on (int led)
void posled_off (int led)
void posleds_on (int ledmask)
void posleds_off (int ledmask)
void posleds_value (int leds)
Detailed Description
Low-level functions to control the LEDs.
Definition in file leds.cc.
Function Documentation
void led_off (int led)
Turns off the led with the given number.
Parameters:
led The led to turn off. Which IDs are valid depend on the platform.
See also:
led_on()
Definition at line 27 of file leds.cc.
References leds_off().
void led_on (int led)
Turns on the led with the given number.
Parameters:
led The led to turn on. Which IDs are valid depend on the platform.
See also:
led_off()
Definition at line 18 of file leds.cc.
References leds_on().
void leds_off (int ledmask)
Turns off leds corresponding to the masked bits.
Parameters:
ledmask The leds to turn off. Led 0 is positioned at the LSB of ledmask.
See also:
leds_on()
Definition at line 45 of file leds.cc.
References IO_LEDS_OFF, and io_write.
Referenced by led_off().
void leds_on (int ledmask)
Turns on leds corresponding to the masked bits.
Parameters:
ledmask The leds to turn on. Led 0 is positioned at the LSB of ledmask.
See also:
leds_off()
Definition at line 36 of file leds.cc.
References IO_LEDS_ON, and io_write.
Referenced by led_on(), and main().
void leds_value (int leds)
Controls all leds simultaneously.
Parameters:
leds bitwise indication whether the corresponding leds should be turned on (1) or off (0)
Definition at line 53 of file leds.cc.
References IO_LEDS_VALUE, and io_write.
void posled_off (int led)
Definition at line 60 of file leds.cc.
References posleds_off().
void posled_on (int led)
Definition at line 57 of file leds.cc.
References posleds_on().
void posleds_off (int ledmask)
Definition at line 66 of file leds.cc.
References IO_POSLEDS_OFF, and io_write.
Referenced by posled_off().
void posleds_on (int ledmask)
Definition at line 63 of file leds.cc.
References IO_POSLEDS_ON, and io_write.
Referenced by posled_on().
void posleds_value (int leds)
Definition at line 69 of file leds.cc.
References IO_POSLEDS_VALUE, and io_write.