Starburst: include/linfs.h File Reference
include/linfs.h File Reference
#include <sys/types.h>
#include <sys/stat.h>
#include <fcntl.h>
#include <pthread.h>
Data Structures
struct linfs_res_t
struct _linfs_t
struct linfs_queues_t
Defines
#define MAX_LINFS_FDS 256
#define MAX_LINFS_FD (MAX_LINFS_FDS+RESERVED_FDS-1)
Typedefs
typedef struct _linfs_t linfs_t
Enumerations
enum linfs_cmd_t {
LINFS_NOP, LINFS_CREAT, LINFS_OPEN, LINFS_CLOSE,
LINFS_READ, LINFS_WRITE, LINFS_SEEK
}
Functions
ssize_t linfs_read (int fd, void *buf, size_t cnt)
Reads a block of data.
ssize_t linfs_write (int fd, const void *buf, size_t cnt)
Writes buffer to the file descriptor.
int linfs_open (const char *pathname, int flags, mode_t mode)
Opens a file.
int linfs_close (int fd)
int linfs_close_all ()
Closes all open file descriptors of the current process.
int linfs_creat (const char *pathname, mode_t mode)
off_t linfs_lseek (int fd, off_t pos, int whence)
Define Documentation
#define MAX_LINFS_FD (MAX_LINFS_FDS+RESERVED_FDS-1)
Definition at line 17 of file linfs.h.
Referenced by close(), and fcntl().
#define MAX_LINFS_FDS 256
Definition at line 16 of file linfs.h.
Typedef Documentation
typedef struct _linfs_t linfs_t
Enumeration Type Documentation
enum linfs_cmd_t
Enumerator:
LINFS_NOP
LINFS_CREAT
LINFS_OPEN
LINFS_CLOSE
LINFS_READ
LINFS_WRITE
LINFS_SEEK
Definition at line 19 of file linfs.h.
Function Documentation
int linfs_close (int fd)
Definition at line 312 of file linfs.cc.
References linfs_res_t::count, DEBUG, LINFS_CLOSE, linfs_unregister(), linfs_res_t::ptr, Q, _fd2q_t::res, and Yield().
Referenced by close(), and linfs_close_all().
int linfs_close_all ()
Closes all open file descriptors of the current process.
Returns:
0 on success, otherwise the errno of the first failing linfs_close()
Definition at line 332 of file linfs.cc.
References FD2Q_MAP, linfs_close(), and _fd2q_t::res.
Referenced by do_gracefull_exit_funs().
int linfs_creat (const char * pathname, mode_t mode)
Definition at line 198 of file linfs.cc.
References linfs_open().
Referenced by creat().
off_t linfs_lseek (int fd, off_t pos, int whence)
Definition at line 296 of file linfs.cc.
References linfs_res_t::count, DEBUG, LINFS_SEEK, linfs_res_t::ptr, Q, _fd2q_t::res, and Yield().
Referenced by lseek().
int linfs_open (const char * pathname, int flags, mode_t mode)
Opens a file.
When flags&O_ASYNC, writes will be executed asynchronously on Helix.
All operations will be done synchronously in Linux, so an operation after a write can block until the write is finished.
Definition at line 207 of file linfs.cc.
References _fd2q_t::async, _linfs_t::cmd, linfs_res_t::count, DEBUG, _fd2q_t::fd, FD_TO_QUEUE, _linfs_t::filename, _linfs_t::flags, FlushDCacheRange(), linfs_queues_t::have_cmd, linfs_flags(), LINFS_OPEN, linfs_register(), linfs_unregister(), _linfs_t::mode, linfs_res_t::ptr, QUEUE, _fd2q_t::res, and Yield().
Referenced by linfs_creat(), and open().
ssize_t linfs_read (int fd, void * buf, size_t cnt)
Reads a block of data.
The cache lines that belong to buf will be invalidated, make sure that buf does not share a cache line with other objects (i.e. by using malloc() for buf).
Definition at line 247 of file linfs.cc.
References linfs_res_t::count, DCACHE_LINESIZE, DEBUG, FlushDCacheWord(), InvalidateDCacheRange(), LINFS_READ, linfs_res_t::ptr, Q, _fd2q_t::res, and Yield().
ssize_t linfs_write (int fd, const void * buf, size_t cnt)
Writes buffer to the file descriptor.
In contrast to POSIX write(), partial writes will automatically retried until nothing is written anymore or an error occurs.
As a consequence, when linfs_write() returns with a value less than cnt, errno always indicates the error.
When fd has been open()ed with flags&O_ASYNC, the write will return immediately with cnt.
In that case, errors during the write will be silently ignored.
Definition at line 276 of file linfs.cc.
References linfs_res_t::count, DEBUG, FlushDCacheRange(), LINFS_WRITE, linfs_res_t::ptr, Q, _fd2q_t::res, and Yield().