Starburst: io/linfs.cc File Reference
io/linfs.cc File Reference
#include <sys/device.h>
#include <sys/io.h>
#include <sys/helix_config.h>
#include <unistd.h>
#include <stdio.h>
#include <fcntl.h>
#include <linfs.h>
#include <malloc.h>
#include <time.h>
Data Structures
struct _fd2q_t
Defines
#define DEBUG(...)
#define LINUX_COREID() GetSoCCores()
#define QUEUE ((linfs_queues_t*)MAKE_NOC_FIFOMEM_PTR(0,LINUX_COREID()))
#define FD_TO_QUEUE(fd) ((linfs_t*)(&queue->queue[(fd)-RESERVED_FDS]))
#define QUEUE_TO_FD(q) ((int)(((long)(q)-(long)&queue->queue[0])/sizeof(linfs_t))+RESERVED_FDS)
#define FD2Q_MAP ((fd2q_t*)(proc_local->linfs))
#define SET_FD2Q_MAP(val) proc_local->linfs=(void*)(val)
#define FIND_MAP(fild) fd2q_t* f __attribute__((unused))=FD2Q_MAP;while(f&&f->fd!=(fild))f=f->next;
#define Q(fd)
#define LINUX_O_RDONLY 0
#define LINUX_O_WRONLY 01
#define LINUX_O_RDWR 02
#define LINUX_O_APPEND 02000
#define LINUX_O_CREAT 0100
#define LINUX_O_EXCL 0200
#define LINUX_O_NOCTTY 0400
#define LINUX_O_NONBLOCK 04000
#define LINUX_O_SYNC 010000
#define LINUX_O_TRUNC 01000
#define L_FLAG(flags, flag) ((flags)&flag?LINUX_##flag:0)
Typedefs
typedef struct _fd2q_t fd2q_t
Functions
static void linfs_unregister (fd2q_t *f)
static int linfs_register_seq (linfs_res_t *res)
static fd2q_t * linfs_register ()
static int linfs_flags (int flags)
int linfs_creat (const char *pathname, mode_t mode)
int linfs_open (const char *pathname, int flags, mode_t mode)
Opens a file.
ssize_t linfs_read (int fd, void *buf, size_t cnt)
Reads a block of data.
ssize_t linfs_write (int fd, const void *buf, size_t cnt)
Writes buffer to the file descriptor.
off_t linfs_lseek (int fd, off_t pos, int whence)
int linfs_close (int fd)
int linfs_close_all ()
Closes all open file descriptors of the current process.
Define Documentation
#define DEBUG (...)
Definition at line 16 of file linfs.cc.
Referenced by linfs_close(), linfs_lseek(), linfs_open(), linfs_read(), linfs_register(), linfs_register_seq(), linfs_unregister(), and linfs_write().
#define FD2Q_MAP ((fd2q_t*)(proc_local->linfs))
Definition at line 30 of file linfs.cc.
Referenced by linfs_close_all(), linfs_register(), linfs_register_seq(), and linfs_unregister().
#define FD_TO_QUEUE (fd) ((linfs_t*)(&queue->queue[(fd)-RESERVED_FDS]))
Definition at line 21 of file linfs.cc.
Referenced by linfs_open().
#define FIND_MAP (fild) fd2q_t* f __attribute__((unused))=FD2Q_MAP;while(f&&f->fd!=(fild))f=f->next;
Definition at line 32 of file linfs.cc.
#define L_FLAG (flags, flag) ((flags)&flag?LINUX_##flag:0)
Definition at line 182 of file linfs.cc.
Referenced by linfs_flags().
#define LINUX_COREID () GetSoCCores()
Definition at line 19 of file linfs.cc.
#define LINUX_O_APPEND 02000
Definition at line 166 of file linfs.cc.
#define LINUX_O_CREAT 0100
Definition at line 169 of file linfs.cc.
#define LINUX_O_EXCL 0200
Definition at line 172 of file linfs.cc.
#define LINUX_O_NOCTTY 0400
Definition at line 175 of file linfs.cc.
#define LINUX_O_NONBLOCK 04000
Definition at line 177 of file linfs.cc.
#define LINUX_O_RDONLY 0
Definition at line 163 of file linfs.cc.
#define LINUX_O_RDWR 02
Definition at line 165 of file linfs.cc.
#define LINUX_O_SYNC 010000
Definition at line 179 of file linfs.cc.
#define LINUX_O_TRUNC 01000
Definition at line 180 of file linfs.cc.
#define LINUX_O_WRONLY 01
Definition at line 164 of file linfs.cc.
#define Q (fd)
Value:
linfs_queues_t* queue __attribute__((unused))=QUEUE;        \
    linfs_t* q __attribute__((unused))=FD_TO_QUEUE(fd);         \
    FIND_MAP(fd)                                                \
    if(!f){errno=EBADF;return -1;}                              \
    linfs_res_t* res __attribute__((unused))=f->res;            \
    if(f->async&&res->count==0){                                \
        DEBUG("blocking on previous write...\n");               \
        while(res->count==0)                                    \
            Yield(false);                                       \
        DEBUG("previous write done\n");                         \
    }
Definition at line 34 of file linfs.cc.
Referenced by bitshark_cmd_get_iqbal(), bitshark_test_debug(), linfs_close(), linfs_lseek(), linfs_read(), and linfs_write().
#define QUEUE ((linfs_queues_t*)MAKE_NOC_FIFOMEM_PTR(0,LINUX_COREID()))
Definition at line 20 of file linfs.cc.
Referenced by linfs_open(), linfs_register(), and linfs_register_seq().
#define QUEUE_TO_FD (q) ((int)(((long)(q)-(long)&queue->queue[0])/sizeof(linfs_t))+RESERVED_FDS)
Definition at line 22 of file linfs.cc.
Referenced by linfs_register().
#define SET_FD2Q_MAP (val) proc_local->linfs=(void*)(val)
Definition at line 31 of file linfs.cc.
Referenced by linfs_register(), linfs_register_seq(), and linfs_unregister().
Typedef Documentation
typedef struct _fd2q_t fd2q_t
Function Documentation
int linfs_close (int fd)
Definition at line 312 of file linfs.cc.
References linfs_res_t::count, DEBUG, LINFS_CLOSE, linfs_unregister(), linfs_res_t::ptr, Q, _fd2q_t::res, and Yield().
Referenced by close(), and linfs_close_all().
int linfs_close_all ()
Closes all open file descriptors of the current process.
Returns:
0 on success, otherwise the errno of the first failing linfs_close()
Definition at line 332 of file linfs.cc.
References FD2Q_MAP, linfs_close(), and _fd2q_t::res.
Referenced by do_gracefull_exit_funs().
int linfs_creat (const char * pathname, mode_t mode)
Definition at line 198 of file linfs.cc.
References linfs_open().
Referenced by creat().
static int linfs_flags (int flags) [static]
Definition at line 184 of file linfs.cc.
References L_FLAG.
Referenced by linfs_open().
off_t linfs_lseek (int fd, off_t pos, int whence)
Definition at line 296 of file linfs.cc.
References linfs_res_t::count, DEBUG, LINFS_SEEK, linfs_res_t::ptr, Q, _fd2q_t::res, and Yield().
Referenced by lseek().
int linfs_open (const char * pathname, int flags, mode_t mode)
Opens a file.
When flags&O_ASYNC, writes will be executed asynchronously on Helix.
All operations will be done synchronously in Linux, so an operation after a write can block until the write is finished.
Definition at line 207 of file linfs.cc.
References _fd2q_t::async, _linfs_t::cmd, linfs_res_t::count, DEBUG, _fd2q_t::fd, FD_TO_QUEUE, _linfs_t::filename, _linfs_t::flags, FlushDCacheRange(), linfs_queues_t::have_cmd, linfs_flags(), LINFS_OPEN, linfs_register(), linfs_unregister(), _linfs_t::mode, linfs_res_t::ptr, QUEUE, _fd2q_t::res, and Yield().
Referenced by linfs_creat(), and open().
ssize_t linfs_read (int fd, void * buf, size_t cnt)
Reads a block of data.
The cache lines that belong to buf will be invalidated, make sure that buf does not share a cache line with other objects (i.e. by using malloc() for buf).
Definition at line 247 of file linfs.cc.
References linfs_res_t::count, DCACHE_LINESIZE, DEBUG, FlushDCacheWord(), InvalidateDCacheRange(), LINFS_READ, linfs_res_t::ptr, Q, _fd2q_t::res, and Yield().
static fd2q_t* linfs_register () [static]
Definition at line 106 of file linfs.cc.
References DEBUG, dRemoteCall(), _fd2q_t::fd, FD2Q_MAP, fmalloc(), free(), getpid(), linfs_register_seq(), linfs_unregister(), malloc(), _fd2q_t::next, linfs_res_t::ptr, QUEUE, QUEUE_TO_FD, _fd2q_t::res, SET_FD2Q_MAP, smalloc(), time, and Yield().
Referenced by linfs_open().
static int linfs_register_seq (linfs_res_t * res) [static]
Definition at line 68 of file linfs.cc.
References addr_global(), linfs_res_t::count, DEBUG, FD2Q_MAP, GetProcID(), linfs_queues_t::have_cmd, QUEUE, linfs_queues_t::queue_req, and SET_FD2Q_MAP.
Referenced by linfs_register().
static void linfs_unregister (fd2q_t * f) [static]
Definition at line 47 of file linfs.cc.
References DEBUG, _fd2q_t::fd, FD2Q_MAP, ffree(), free(), GetFifoMemSize(), _fd2q_t::next, _fd2q_t::res, SET_FD2Q_MAP, and sfree().
Referenced by linfs_close(), linfs_open(), and linfs_register().
ssize_t linfs_write (int fd, const void * buf, size_t cnt)
Writes buffer to the file descriptor.
In contrast to POSIX write(), partial writes will automatically retried until nothing is written anymore or an error occurs.
As a consequence, when linfs_write() returns with a value less than cnt, errno always indicates the error.
When fd has been open()ed with flags&O_ASYNC, the write will return immediately with cnt.
In that case, errors during the write will be silently ignored.
Definition at line 276 of file linfs.cc.
References linfs_res_t::count, DEBUG, FlushDCacheRange(), LINFS_WRITE, linfs_res_t::ptr, Q, _fd2q_t::res, and Yield().