Starburst: include/llock.h File Reference
include/llock.h File Reference
#include <sys/device.h>
#include <sys/syscall.h>
#include <sys/api.h>
Functions
static void llck_init (llck_t *l) _NO_THROW __attribute__((always_inline))
static void llck (llck_t *l) _NO_THROW __attribute__((always_inline))
static void lulck (llck_t *l) _NO_THROW __attribute__((always_inline))
Function Documentation
static void llck (llck_t * l) [inline, static]
Definition at line 12 of file llock.h.
References unlikely, and Yield().
Referenced by fcalloc(), ffree(), ffreeAll(), fmalloc(), fmown(), and frealloc().
static void llck_init (llck_t * l) [inline, static]
Definition at line 10 of file llock.h.
Referenced by malloc_init().
static void lulck (llck_t * l) [inline, static]
Definition at line 14 of file llock.h.
Referenced by fcalloc(), ffree(), ffreeAll(), fmalloc(), fmown(), and frealloc().