Starburst: ipc/lock.cc File Reference
ipc/lock.cc File Reference
#include <lock.h>
#include <sys/api.h>
#include <mc.h>
#include <rc.h>
Data Structures
struct _le_t
struct lt_t
Defines
#define MAX_FREE_LOCKS 12800
#define DEBUG(...)
#define DEBUGS(...)
#define WARNING(...)
#define DEBUGC(l, c)
#define LASSERT(a...)
#define CHECK_NON_SIGHANDLER
#define BULK_RECORDS (MAX_FREE_LOCKS>>2)
#define LOCK_LIST(list) while(unlikely(lcas((int*)&(list)->locked,0,1)!=0))Yield()
#define UNLOCK_LIST(list) do{barrier();(list)->locked=0;}while(0)
#define lck_tree_validate(...)
#define lck_tree_dump(...)
#define LCK_ADMIN (&proc_local->lck.d)
#define mc_rc_flush(o, s, dest) do{if(likely((uintptr_t)(o)>RING_CONSISTENCY_EDGE))mc_flush_(o,s);else rc_flush_(o,s,dest);}while(0)
#define mc_protect(lock, obj, objsize) do{(lock)->mc_obj=(obj);(lock)->mc_objsize=(objsize);}while(0)
#define mc_unprotect(lock, dest) do{if((lock)->mc_obj)mc_rc_flush((lock)->mc_obj,(lock)->mc_objsize,dest);}while(0)
#define mc_reprotect(lock, obj, objsize, dest) do{if((lock)->mc_obj!=obj){mc_unprotect(lock,dest);mc_protect(lock,obj,objsize);}}while(0)
#define LCK_ADMIN (&proc_local->lck.m)
#define MEM_SYNC()
Typedefs
typedef struct _le_t le_t
Functions
static le_t * lck_tree_find (le_t *root, void *value)
static le_t * lck_tree_skew (le_t *t)
static le_t * lck_tree_split (le_t *t)
static void lck_tree_declevel (le_t *t)
static le_t * lck_tree_delete (le_t *root, le_t *elem)
static void lck_tree_remove (lt_t *tree, le_t *elem)
static le_t * lck_tree_insert (le_t *t, le_t *x)
static le_t * lck_tree_add (lt_t *tree, void *value, size_t elem_size)
static lck_my_lock_t * lck_list_find (lck_my_locks_t *list, void *value)
static void lck_list_free (lck_my_locks_t *list, lck_my_lock_t *elem)
static void lck_list_use (lck_my_locks_t *list, lck_my_lock_t *elem)
static void lck_list_remove (lck_my_locks_t *list, lck_my_lock_t *elem)
static lck_my_lock_t * lck_list_add (lck_my_locks_t *list, void *value)
static lck_daemon_lock_t * lck_list_find (lck_daemon_locks_t *list, void *value)
static void lck_list_remove (lck_daemon_locks_t *list, lck_daemon_lock_t *elem)
static lck_daemon_lock_t * lck_list_add (lck_daemon_locks_t *list, void *value)
void lck_daemon_lock_stats (lck_daemon_lock_t *lock)
void lck_daemon_locks_stats ()
int lck_request (void *l, int requester)
Request lock ownage by lock daemon.
int lck_giveup (void *l, int pid)
int lck_register (lck_my_locks_t *list, pid_t pid)
Register the lock list of a process.
int lck_ask (void *l, int requester, int owner)
Non-lock daemon lock request forwarding.
static int lck_pass_p (void *ul, void *l, void *protectee=NULL, size_t sprotectee=0, bool only_try_local=false)
static void lck_cleanup ()
static int lck_migrate (lck_my_lock_t *lock)
int lck_lock (void *l)
Get lock (from local or remote) corresponding to address.
int lck_lock_p (void *l, void *protectee, size_t sprotectee)
int lck_pass (void *ul, void *l)
int lck_unlock (void *l)
Unlock an address Does not communicate with lock daemon, unless old lock is destroyed.
int lck_destroy (void *l)
Unlock and give back to server When result < 0: LR_LOCAL: lock was local LR_STOLEN: already stolen before destruction (no communication with lock daemon) LR_STEALING: theft in progress, yielding until stolen (after giveup) LR_MIGRATED: migrated (after giveup) possible combinations: LR_STOLEN || (LR_LOCAL|(LR_STEALING?||LR_MIGRATED))
Define Documentation
#define BULK_RECORDS (MAX_FREE_LOCKS>>2)
Definition at line 52 of file lock.cc.
Referenced by lck_tree_add().
#define CHECK_NON_SIGHANDLER
Definition at line 44 of file lock.cc.
Referenced by lck_destroy(), lck_pass_p(), and lck_unlock().
#define DEBUG (...)
Definition at line 39 of file lock.cc.
Referenced by lck_ask(), lck_cleanup(), lck_destroy(), lck_migrate(), lck_pass_p(), lck_register(), lck_tree_add(), and lck_unlock().
#define DEBUGC (l, c)
Definition at line 42 of file lock.cc.
Referenced by lck_ask(), lck_destroy(), lck_giveup(), lck_migrate(), lck_request(), and lck_unlock().
#define DEBUGS (...)
Definition at line 40 of file lock.cc.
Referenced by lck_giveup(), and lck_request().
#define LASSERT (a...)
Definition at line 43 of file lock.cc.
Referenced by lck_ask(), lck_cleanup(), lck_destroy(), lck_giveup(), lck_list_add(), lck_list_free(), lck_list_remove(), lck_list_use(), lck_migrate(), lck_pass_p(), lck_register(), lck_request(), lck_tree_add(), lck_tree_declevel(), lck_tree_delete(), lck_tree_insert(), and lck_unlock().
#define LCK_ADMIN (&proc_local->lck.d)
Definition at line 615 of file lock.cc.
Referenced by lck_ask(), lck_cleanup(), lck_destroy(), lck_giveup(), lck_pass_p(), lck_register(), lck_request(), and lck_unlock().
#define LCK_ADMIN (&proc_local->lck.m)
Definition at line 615 of file lock.cc.
#define lck_tree_dump (...)
Definition at line 125 of file lock.cc.
#define lck_tree_validate (...)
Definition at line 124 of file lock.cc.
Referenced by lck_list_remove(), and lck_tree_add().
#define LOCK_LIST (list) while(unlikely(lcas((int*)&(list)->locked,0,1)!=0))Yield()
Definition at line 75 of file lock.cc.
Referenced by lck_ask(), lck_list_add(), and lck_list_remove().
#define MAX_FREE_LOCKS 12800
Definition at line 10 of file lock.cc.
Referenced by lck_unlock().
#define mc_protect (lock, obj, objsize) do{(lock)->mc_obj=(obj);(lock)->mc_objsize=(objsize);}while(0)
Definition at line 510 of file lock.cc.
Referenced by lck_pass_p().
#define mc_rc_flush (o, s, dest) do{if(likely((uintptr_t)(o)>RING_CONSISTENCY_EDGE))mc_flush_(o,s);else rc_flush_(o,s,dest);}while(0)
Definition at line 502 of file lock.cc.
#define mc_reprotect (lock, obj, objsize, dest) do{if((lock)->mc_obj!=obj){mc_unprotect(lock,dest);mc_protect(lock,obj,objsize);}}while(0)
Definition at line 512 of file lock.cc.
Referenced by lck_pass_p().
#define mc_unprotect (lock, dest) do{if((lock)->mc_obj)mc_rc_flush((lock)->mc_obj,(lock)->mc_objsize,dest);}while(0)
Definition at line 511 of file lock.cc.
Referenced by lck_ask(), lck_destroy(), and lck_migrate().
#define MEM_SYNC ()
Value:
do{InvalidateDCacheWord((void*)lck_unlock); \
    volatile unsigned int* p __attribute__((__may_alias__))=(volatile unsigned int*)lck_unlock;*p;barrier();}while(0)
Definition at line 813 of file lock.cc.
Referenced by lck_unlock().
#define UNLOCK_LIST (list) do{barrier();(list)->locked=0;}while(0)
Definition at line 77 of file lock.cc.
Referenced by lck_ask(), lck_list_add(), and lck_list_remove().
#define WARNING (...)
Definition at line 41 of file lock.cc.
Referenced by lck_cleanup().
Typedef Documentation
typedef struct _le_t le_t
Function Documentation
int lck_ask (void * l, int requester, int owner)
Non-lock daemon lock request forwarding.
Definition at line 539 of file lock.cc.
References a, DEBUG, DEBUGC, getgpidproc(), getpid(), GetProcID(), LASSERT, LCK_ADMIN, LCK_DESTROYED, LCK_FREE, lck_list_find(), LCK_LOCKED, LCK_MIGRATED, LCK_MINE, LCK_REQUEST, LCK_STOLEN, lck_daemon_admin_t::lists, lock(), LOCK_LIST, MAX_PROCESSES, mc_unprotect, _lck_my_lock_t::own, _lck_my_lock_t::pid, _lck_my_lock_t::state, _lck_my_lock_t::state_, unlikely, and UNLOCK_LIST.
Referenced by ProcessRequest().
static void lck_cleanup () [static]
Definition at line 617 of file lock.cc.
References DEBUG, dLockRegister(), LASSERT, LCK_ADMIN, lck_destroy(), lck_pass_p(), _lck_my_lock_t::lock, _lck_my_lock_t::mc_obj, lck_my_locks_t::root, and WARNING.
Referenced by lck_pass_p().
void lck_daemon_lock_stats (lck_daemon_lock_t * lock)
Definition at line 403 of file lock.cc.
References _lck_daemon_lock_t::count_migrated, _lck_daemon_lock_t::lock, _lck_daemon_lock_t::owner, and _lck_daemon_lock_t::state.
void lck_daemon_locks_stats (void)
Definition at line 408 of file lock.cc.
int lck_destroy (void * l)
Unlock and give back to server When result < 0: LR_LOCAL: lock was local LR_STOLEN: already stolen before destruction (no communication with lock daemon) LR_STEALING: theft in progress, yielding until stolen (after giveup) LR_MIGRATED: migrated (after giveup) possible combinations: LR_STOLEN || (LR_LOCAL|(LR_STEALING?||LR_MIGRATED))
Definition at line 906 of file lock.cc.
References CHECK_NON_SIGHANDLER, DEBUG, DEBUGC, dLockGiveup(), getpid(), LASSERT, LCK_ADMIN, LCK_DESTROYED, LCK_FREE, lck_list_find(), lck_list_remove(), lck_list_use(), LCK_LOCKED, lck_migrate(), LCK_MIGRATED, LCK_MINE, LCK_REQUEST, LCK_STOLEN, lock(), LR_LOCAL, LR_MIGRATED, LR_STOLEN, mc_unprotect, _lck_my_lock_t::own, and _lck_my_lock_t::state.
Referenced by PMC_NS::RCBackend< T >::exit_ro(), PMC_NS::RCBackend< T >::exit_x(), lck_cleanup(), lck_unlock(), mc_release_eager_(), pthread_mutex_destroy(), pthread_mutex_protect(), PMC_NS::Location< T >::release(), and PMC_NS::RCBackend< T >::release().
int lck_giveup (void * l, int pid)
Definition at line 468 of file lock.cc.
References a, DEBUGC, DEBUGS, getpid(), GetProcID(), LASSERT, LCK_ADMIN, lck_list_find(), lck_list_remove(), LCK_NEW, LCK_OWNED, lock(), LOCK_DAEMON_CORE, lck_daemon_admin_t::locks, _lck_daemon_lock_t::owner, _lck_daemon_lock_t::state, and unlikely.
Referenced by ProcessRequest().
static lck_my_lock_t* lck_list_add (lck_my_locks_t * list, void * value) [static]
Definition at line 348 of file lock.cc.
References LASSERT, LCK_LOCKED, LCK_MINE, lck_tree_add(), LOCK_LIST, _lck_my_lock_t::own, _lck_my_lock_t::state, unlock(), and UNLOCK_LIST.
Referenced by lck_pass_p(), and lck_request().
static lck_daemon_lock_t* lck_list_add (lck_daemon_locks_t * list, void * value) [static]
Definition at line 380 of file lock.cc.
References LASSERT, LCK_NEW, lck_tree_add(), _lck_daemon_lock_t::owner, _lck_daemon_lock_t::state, unlikely, and unlock().
static lck_my_lock_t* lck_list_find (lck_my_locks_t * list, void * value) [inline, static]
Definition at line 284 of file lock.cc.
References lck_tree_find(), and lck_my_locks_t::root.
Referenced by lck_ask(), lck_destroy(), lck_giveup(), lck_pass_p(), lck_request(), and lck_unlock().
static lck_daemon_lock_t* lck_list_find (lck_daemon_locks_t * list, void * value) [inline, static]
Definition at line 369 of file lock.cc.
References lck_tree_find(), and lck_daemon_locks_t::root.
static void lck_list_free (lck_my_locks_t * list, lck_my_lock_t * elem) [static]
Definition at line 289 of file lock.cc.
References lck_my_locks_t::free, lck_my_locks_t::free_first, lck_my_locks_t::free_last, LASSERT, _lck_my_lock_t::lock, _lck_my_lock_t::next_free, and _lck_my_lock_t::prev_free.
Referenced by lck_unlock().
static void lck_list_remove (lck_my_locks_t * list, lck_my_lock_t * elem) [static]
Definition at line 339 of file lock.cc.
References LASSERT, lck_tree_remove(), lck_tree_validate, LOCK_LIST, and UNLOCK_LIST.
Referenced by lck_destroy(), lck_giveup(), and lck_unlock().
static void lck_list_remove (lck_daemon_locks_t * list, lck_daemon_lock_t * elem) [static]
Definition at line 373 of file lock.cc.
References LASSERT, lck_tree_remove(), and lck_tree_validate.
static void lck_list_use (lck_my_locks_t * list, lck_my_lock_t * elem) [static]
Definition at line 312 of file lock.cc.
References lck_my_locks_t::free, lck_my_locks_t::free_first, lck_my_locks_t::free_last, LASSERT, _lck_my_lock_t::lock, _lck_my_lock_t::next_free, and _lck_my_lock_t::prev_free.
Referenced by lck_destroy(), and lck_pass_p().
int lck_lock (void * l)
Get lock (from local or remote) corresponding to address.
Parameters:
l the address to lock, cannot be NULL
Returns:
<=0 on success, EDEADLCK when already locked, otherwise an errno. When locking fails, the lock is probably in an unknown and unrecovereable state. When result < 0: LR_LOCAL: lock is lock, relocked LR_STOLEN: lock is stolen, request remote LR_UNKNOWN: lock is not here, ask lock server LR_NEW: new lock (after asking lock server) LR_FREE: we stole lock LR_LOCKED: lock was remote and locked possible combinations: LR_LOCAL || ((LR_STOLEN||LR_UNKNOWN) | (LR_NEW||LR_FREE||LR_LOCKED))
Definition at line 674 of file lock.cc.
References lck_pass_p().
Referenced by PMC_NS::Location< T >::acquire(), mc_nullify_(), pthread_mutex_lock(), and pthread_mutex_protect().
int lck_lock_p (void * l, void * protectee, size_t sprotectee)
Definition at line 678 of file lock.cc.
References lck_pass_p().
Referenced by mc_acquire_(), pthread_barrier_wait(), pthread_mutex_lock(), and rc_entry_x_().
static int lck_migrate (lck_my_lock_t * lock) [static]
Definition at line 645 of file lock.cc.
References DEBUG, DEBUGC, getgpid(), getgpidproc(), LASSERT, _lck_my_lock_t::lock, mc_unprotect, _lck_my_lock_t::pid, pthread_kill(), and SIGLCK.
Referenced by lck_destroy(), and lck_unlock().
int lck_pass (void * ul, void * l)
Definition at line 682 of file lock.cc.
References lck_pass_p().
Referenced by pthread_barrier_wait().
static int lck_pass_p (void * ul, void * l, void * protectee = NULL, size_t sprotectee = 0, bool only_try_local = false) [static]
Definition at line 686 of file lock.cc.
References CHECK_NON_SIGHANDLER, DEBUG, dLockAsk(), dLockRegister(), dLockRequest(), getgpid(), getpid(), LASSERT, LCK_ADMIN, lck_cleanup(), LCK_DESTROYED, LCK_FREE, lck_list_add(), lck_list_find(), lck_list_use(), LCK_LOCKED, LCK_MIGRATED, LCK_MINE, LCK_STOLEN, lck_unlock(), likely, lock(), LR_FREE, LR_LOCAL, LR_LOCKED, LR_NEW, LR_STOLEN, LR_UNKNOWN, mc_protect, mc_reprotect, _lck_my_lock_t::own, lck_my_locks_t::root, sigaddset(), sigemptyset(), SIGLCK, lck_my_locks_t::spare, _lck_my_lock_t::state, _lck_my_lock_t::state_, Suspend(), and unlikely.
Referenced by lck_cleanup(), lck_lock(), lck_lock_p(), and lck_pass().
int lck_register (lck_my_locks_t * list, pid_t pid)
Register the lock list of a process.
Should be done before using locks by every process.
Definition at line 520 of file lock.cc.
References a, DEBUG, getpid(), LASSERT, lcalloc, LCK_ADMIN, lck_daemon_admin_t::lists, MAX_PROCESSES, and unlikely.
int lck_request (void * l, int requester)
Request lock ownage by lock daemon.
Definition at line 419 of file lock.cc.
References a, _lck_daemon_lock_t::count_migrated, DEBUGC, DEBUGS, getpid(), GetProcID(), LASSERT, LCK_ADMIN, lck_list_add(), lck_list_find(), LCK_NEW, LCK_OWNED, lock(), LOCK_DAEMON_CORE, lck_daemon_admin_t::locks, MAX_PROCESSES, _lck_daemon_lock_t::owner, _lck_daemon_lock_t::state, and unlikely.
Referenced by ProcessRequest().
static le_t* lck_tree_add (lt_t * tree, void * value, size_t elem_size) [static]
Definition at line 246 of file lock.cc.
References BULK_RECORDS, DEBUG, LASSERT, lck_tree_insert(), lck_tree_validate, lmalloc, _le_t::next, lt_t::root, lt_t::spare, unlikely, and _le_t::value.
Referenced by lck_list_add().
static void lck_tree_declevel (le_t * t) [static]
Definition at line 159 of file lock.cc.
References LASSERT, _le_t::left, _le_t::level, and _le_t::right.
Referenced by lck_tree_delete().
static le_t* lck_tree_delete (le_t * root, le_t * elem) [static]
Definition at line 172 of file lock.cc.
References LASSERT, lck_tree_declevel(), lck_tree_skew(), lck_tree_split(), _le_t::left, _le_t::level, _le_t::right, and _le_t::value.
Referenced by lck_tree_remove().
static le_t* lck_tree_find (le_t * root, void * value) [inline, static]
Definition at line 129 of file lock.cc.
References _le_t::left, _le_t::right, and _le_t::value.
Referenced by lck_list_find().
static le_t* lck_tree_insert (le_t * t, le_t * x) [static]
Definition at line 227 of file lock.cc.
References LASSERT, lck_tree_skew(), lck_tree_split(), _le_t::left, _le_t::level, _le_t::right, and _le_t::value.
Referenced by lck_tree_add().
static void lck_tree_remove (lt_t * tree, le_t * elem) [static]
Definition at line 220 of file lock.cc.
References lck_tree_delete(), _le_t::next, lt_t::root, and lt_t::spare.
Referenced by lck_list_remove().
static le_t* lck_tree_skew (le_t * t) [static]
Definition at line 136 of file lock.cc.
References _le_t::left, _le_t::level, and _le_t::right.
Referenced by lck_tree_delete(), and lck_tree_insert().
static le_t* lck_tree_split (le_t * t) [static]
Definition at line 148 of file lock.cc.
References _le_t::left, _le_t::level, r, and _le_t::right.
Referenced by lck_tree_delete(), and lck_tree_insert().
int lck_unlock (void * l)
Unlock an address Does not communicate with lock daemon, unless old lock is destroyed.
When result < 0: LR_LOCAL: we owned the lock LR_LOCKED: lock was locked LR_FULL: too many free locks, destroyed oldest one LR_MIGRATED: lock was migrated immediately and or'ed with lck_destroy() possible combinations: LR_LOCAL|LR_LOCKED| ((LR_FULL|lck_destroy) || LR_MIGRATED)?
Definition at line 831 of file lock.cc.
References CHECK_NON_SIGHANDLER, DEBUG, DEBUGC, lck_my_locks_t::free, lck_my_locks_t::free_last, getgpid(), getpid(), LASSERT, LCK_ADMIN, lck_destroy(), LCK_DESTROYED, LCK_FREE, lck_list_find(), lck_list_free(), lck_list_remove(), LCK_LOCKED, lck_migrate(), LCK_MIGRATED, LCK_MINE, LCK_REQUEST, LCK_STOLEN, likely, _lck_my_lock_t::lock, lock(), LR_FULL, LR_LOCAL, LR_LOCKED, LR_MIGRATED, MAX_FREE_LOCKS, MAX_PROCESSES, MEM_SYNC, _lck_my_lock_t::own_, lck_my_locks_t::root, _lck_my_lock_t::state, and _lck_my_lock_t::state_.
Referenced by lck_pass_p(), mc_constantize_(), mc_release_(), pthread_barrier_wait(), pthread_mutex_unlock(), rc_exit_x_(), and PMC_NS::Location< T >::release().