Starburst: include/lock.h File Reference
include/lock.h File Reference
#include <sys/helix_config.h>
#include <sys/types.h>
#include <sys/kernel_types.h>
Data Structures
struct _lck_my_lock_t
struct lck_my_locks_t
struct _lck_daemon_lock_t
struct lck_daemon_locks_t
struct lck_daemon_admin_t
union lck_admin_t
Defines
#define LOCK_DAEMON_CORE(l) ((unsigned int)((((unsigned int)(l))>>5)%sysconf(_SC_NPROCESSORS_ONLN)))
#define LCK_USE_PROTECTEE
#define LR_LOCAL 0x001
#define LR_STOLEN 0x002
#define LR_UNKNOWN 0x004
#define LR_NEW 0x008
#define LR_FREE 0x010
#define LR_LOCKED 0x020
#define LR_FULL 0x040
#define LR_MIGRATED 0x080
#define LR_STEALING 0x100
Typedefs
typedef struct _lck_my_lock_t lck_my_lock_t
typedef struct _lck_daemon_lock_t lck_daemon_lock_t
Enumerations
enum lck_lock_state_t {
LCK_LOCKED = 0, LCK_FREE, LCK_MIGRATED, LCK_STOLEN,
LCK_DESTROYED
}
enum lck_own_state_t { LCK_MINE = 0, LCK_REQUEST }
enum lck_daemon_state_t { LCK_NEW, LCK_OWNED }
Functions
void lck_daemon_locks_stats (void) _NO_THROW
int lck_request (void *l, int requester) _NO_THROW
Request lock ownage by lock daemon.
int lck_giveup (void *l, int pid) _NO_THROW
int lck_register (lck_my_locks_t *list, int pid) _NO_THROW
int lck_ask (void *l, int requester, int owner) _NO_THROW
Non-lock daemon lock request forwarding.
int lck_lock (void *l) _NO_THROW
Get lock (from local or remote) corresponding to address.
int lck_unlock (void *l) _NO_THROW
Unlock an address Does not communicate with lock daemon, unless old lock is destroyed.
int lck_destroy (void *l) _NO_THROW
Unlock and give back to server When result < 0: LR_LOCAL: lock was local LR_STOLEN: already stolen before destruction (no communication with lock daemon) LR_STEALING: theft in progress, yielding until stolen (after giveup) LR_MIGRATED: migrated (after giveup) possible combinations: LR_STOLEN || (LR_LOCAL|(LR_STEALING?||LR_MIGRATED))
int lck_pass (void *from, void *to) _NO_THROW
int lck_lock_p (void *l, void *protectee, size_t sprotectee) _NO_THROW
Define Documentation
#define LCK_USE_PROTECTEE
Definition at line 25 of file lock.h.
#define LOCK_DAEMON_CORE (l) ((unsigned int)((((unsigned int)(l))>>5)%sysconf(_SC_NPROCESSORS_ONLN)))
Definition at line 17 of file lock.h.
Referenced by dLockGiveup(), dLockRequest(), lck_giveup(), and lck_request().
#define LR_FREE 0x010
Definition at line 128 of file lock.h.
Referenced by lck_pass_p(), and pthread_mutex_lock().
#define LR_FULL 0x040
Definition at line 130 of file lock.h.
Referenced by lck_unlock().
#define LR_LOCAL 0x001
Definition at line 124 of file lock.h.
Referenced by lck_destroy(), lck_pass_p(), lck_unlock(), and pthread_mutex_lock().
#define LR_LOCKED 0x020
Definition at line 129 of file lock.h.
Referenced by lck_pass_p(), and lck_unlock().
#define LR_MIGRATED 0x080
Definition at line 131 of file lock.h.
Referenced by lck_destroy(), and lck_unlock().
#define LR_NEW 0x008
Definition at line 127 of file lock.h.
Referenced by lck_pass_p(), and pthread_mutex_lock().
#define LR_STEALING 0x100
Definition at line 132 of file lock.h.
#define LR_STOLEN 0x002
Definition at line 125 of file lock.h.
Referenced by lck_destroy(), and lck_pass_p().
#define LR_UNKNOWN 0x004
Definition at line 126 of file lock.h.
Referenced by lck_pass_p().
Typedef Documentation
typedef struct _lck_daemon_lock_t lck_daemon_lock_t
typedef struct _lck_my_lock_t lck_my_lock_t
Enumeration Type Documentation
enum lck_daemon_state_t
Enumerator:
LCK_NEW
LCK_OWNED
Definition at line 34 of file lock.h.
enum lck_lock_state_t
Enumerator:
LCK_LOCKED
LCK_FREE
LCK_MIGRATED
LCK_STOLEN
LCK_DESTROYED
Definition at line 32 of file lock.h.
enum lck_own_state_t
Enumerator:
LCK_MINE
LCK_REQUEST
Definition at line 33 of file lock.h.
Function Documentation
int lck_ask (void * l, int requester, int owner)
Non-lock daemon lock request forwarding.
Definition at line 539 of file lock.cc.
References a, DEBUG, DEBUGC, getgpidproc(), getpid(), GetProcID(), LASSERT, LCK_ADMIN, LCK_DESTROYED, LCK_FREE, lck_list_find(), LCK_LOCKED, LCK_MIGRATED, LCK_MINE, LCK_REQUEST, LCK_STOLEN, lck_daemon_admin_t::lists, lock(), LOCK_LIST, MAX_PROCESSES, mc_unprotect, _lck_my_lock_t::own, _lck_my_lock_t::pid, _lck_my_lock_t::state, _lck_my_lock_t::state_, unlikely, and UNLOCK_LIST.
Referenced by ProcessRequest().
void lck_daemon_locks_stats (void)
Definition at line 408 of file lock.cc.
int lck_destroy (void * l)
Unlock and give back to server When result < 0: LR_LOCAL: lock was local LR_STOLEN: already stolen before destruction (no communication with lock daemon) LR_STEALING: theft in progress, yielding until stolen (after giveup) LR_MIGRATED: migrated (after giveup) possible combinations: LR_STOLEN || (LR_LOCAL|(LR_STEALING?||LR_MIGRATED))
Definition at line 906 of file lock.cc.
References CHECK_NON_SIGHANDLER, DEBUG, DEBUGC, dLockGiveup(), getpid(), LASSERT, LCK_ADMIN, LCK_DESTROYED, LCK_FREE, lck_list_find(), lck_list_remove(), lck_list_use(), LCK_LOCKED, lck_migrate(), LCK_MIGRATED, LCK_MINE, LCK_REQUEST, LCK_STOLEN, lock(), LR_LOCAL, LR_MIGRATED, LR_STOLEN, mc_unprotect, _lck_my_lock_t::own, and _lck_my_lock_t::state.
Referenced by PMC_NS::RCBackend< T >::exit_ro(), PMC_NS::RCBackend< T >::exit_x(), lck_cleanup(), lck_unlock(), mc_release_eager_(), pthread_mutex_destroy(), pthread_mutex_protect(), PMC_NS::Location< T >::release(), and PMC_NS::RCBackend< T >::release().
int lck_giveup (void * l, int pid)
Definition at line 468 of file lock.cc.
References a, DEBUGC, DEBUGS, getpid(), GetProcID(), LASSERT, LCK_ADMIN, lck_list_find(), lck_list_remove(), LCK_NEW, LCK_OWNED, lock(), LOCK_DAEMON_CORE, lck_daemon_admin_t::locks, _lck_daemon_lock_t::owner, _lck_daemon_lock_t::state, and unlikely.
Referenced by ProcessRequest().
int lck_lock (void * l)
Get lock (from local or remote) corresponding to address.
Parameters:
l the address to lock, cannot be NULL
Returns:
<=0 on success, EDEADLCK when already locked, otherwise an errno. When locking fails, the lock is probably in an unknown and unrecovereable state. When result < 0: LR_LOCAL: lock is lock, relocked LR_STOLEN: lock is stolen, request remote LR_UNKNOWN: lock is not here, ask lock server LR_NEW: new lock (after asking lock server) LR_FREE: we stole lock LR_LOCKED: lock was remote and locked possible combinations: LR_LOCAL || ((LR_STOLEN||LR_UNKNOWN) | (LR_NEW||LR_FREE||LR_LOCKED))
Definition at line 674 of file lock.cc.
References lck_pass_p().
Referenced by PMC_NS::Location< T >::acquire(), mc_nullify_(), pthread_mutex_lock(), and pthread_mutex_protect().
int lck_lock_p (void * l, void * protectee, size_t sprotectee)
Definition at line 678 of file lock.cc.
References lck_pass_p().
Referenced by mc_acquire_(), pthread_barrier_wait(), pthread_mutex_lock(), and rc_entry_x_().
int lck_pass (void * from, void * to)
Definition at line 682 of file lock.cc.
References lck_pass_p().
Referenced by pthread_barrier_wait().
int lck_register (lck_my_locks_t * list, int pid)
Referenced by ProcessRequest().
int lck_request (void * l, int requester)
Request lock ownage by lock daemon.
Definition at line 419 of file lock.cc.
References a, _lck_daemon_lock_t::count_migrated, DEBUGC, DEBUGS, getpid(), GetProcID(), LASSERT, LCK_ADMIN, lck_list_add(), lck_list_find(), LCK_NEW, LCK_OWNED, lock(), LOCK_DAEMON_CORE, lck_daemon_admin_t::locks, MAX_PROCESSES, _lck_daemon_lock_t::owner, _lck_daemon_lock_t::state, and unlikely.
Referenced by ProcessRequest().
int lck_unlock (void * l)
Unlock an address Does not communicate with lock daemon, unless old lock is destroyed.
When result < 0: LR_LOCAL: we owned the lock LR_LOCKED: lock was locked LR_FULL: too many free locks, destroyed oldest one LR_MIGRATED: lock was migrated immediately and or'ed with lck_destroy() possible combinations: LR_LOCAL|LR_LOCKED| ((LR_FULL|lck_destroy) || LR_MIGRATED)?
Definition at line 831 of file lock.cc.
References CHECK_NON_SIGHANDLER, DEBUG, DEBUGC, lck_my_locks_t::free, lck_my_locks_t::free_last, getgpid(), getpid(), LASSERT, LCK_ADMIN, lck_destroy(), LCK_DESTROYED, LCK_FREE, lck_list_find(), lck_list_free(), lck_list_remove(), LCK_LOCKED, lck_migrate(), LCK_MIGRATED, LCK_MINE, LCK_REQUEST, LCK_STOLEN, likely, _lck_my_lock_t::lock, lock(), LR_FULL, LR_LOCAL, LR_LOCKED, LR_MIGRATED, MAX_FREE_LOCKS, MAX_PROCESSES, MEM_SYNC, _lck_my_lock_t::own_, lck_my_locks_t::root, _lck_my_lock_t::state, and _lck_my_lock_t::state_.
Referenced by lck_pass_p(), mc_constantize_(), mc_release_(), pthread_barrier_wait(), pthread_mutex_unlock(), rc_exit_x_(), and PMC_NS::Location< T >::release().