Starburst: include/mail.h File Reference
include/mail.h File Reference
Mailboxes: a simple system to pass integer values around.
Data Structures
struct Mail
A normal mailbox: multiple 32-bit values.
Defines
#define lAllocSimpleMail() (SimpleMail*)fmalloc(sizeof(SimpleMail))
Allocates memory for a simple mailbox.
#define lAllocMail(count) (Mail*)fmalloc((count+1)*sizeof(unsigned int))
Allocates memory for a mailbox.
#define InitMail(mail) _InitMail((volatile void*)(mail))
Initializes a mailbox.
#define lDestroyMail(mail) ffree((void*)addr_direct(mail))
Cleans up a mailbox.
#define MAIL_GOTMAIL_FLAG (0x80000000)
Flag to indicate a valid value in a simple mailbox.
Typedefs
typedef volatile unsigned int SimpleMail
A simple mailbox: one single 31-bit value.
Functions
void MailWrite (SimpleMail *box, unsigned int msg)
Write a value to a simple mailbox.
void MailWrite (Mail *box, unsigned int index, unsigned int msg)
Write a value to a mailbox.
bool MailPeek (SimpleMail *box)
Checks whether there is mail in the box.
bool MailPeek (Mail *box, unsigned int number)
Checks whether the specified message has been received.
unsigned int MailRead (SimpleMail *box)
Reads mail from the mailbox and blocks if there is nothing to read yet.
unsigned int MailRead (Mail *box, unsigned int index)
Reads mail from the mailbox and blocks if there is no message at the specified index yet.
static void _InitMail (volatile void *mail) __attribute__((always_inline))
Detailed Description
Mailboxes: a simple system to pass integer values around.
The concept of a mailbox is easy: it is a pointer to a memory. The writing side is only allowed to write once, the reading site can read it as many times as wanted.
A simple mailbox is just one 31-bit value (the last bit is set when the value has been written). A normal mailbox can contain multiple values. A counter indicates how many fields in the box are written. Normal mailboxes must be written in increasing index -- a write to index n means that all values at an index lower than n are valid.
These mailboxes can be used to signal between processors, such as the result of a command that has been executed. Using FIFOs for this is possible, but a FIFO has much more overhead.
Definition in file mail.h.
Define Documentation
#define InitMail (mail) _InitMail((volatile void*)(mail))
Initializes a mailbox.
Definition at line 58 of file mail.h.
Referenced by dBootKernel(), dWaitProcess(), ForwardRequest(), GetIssueSlot(), InitTaskDaemon(), map_start_mail(), ReserveRemoteSlot(), StartDumpStatsDaemon(), StartMallocDaemon(), and StartTimerDaemon().
#define lAllocMail (count) (Mail*)fmalloc((count+1)*sizeof(unsigned int))
Allocates memory for a mailbox.
The mailbox will be allocated in the FIFO memory. The pointer to it is local to the calling processor.
Parameters:
count the number of elements to be allocated
Definition at line 54 of file mail.h.
Referenced by dWaitProcess(), and ProcessRequest().
#define lAllocSimpleMail () (SimpleMail*)fmalloc(sizeof(SimpleMail))
Allocates memory for a simple mailbox.
The mailbox will be allocated in the FIFO memory. The pointer to it is local to the calling processor.
Definition at line 47 of file mail.h.
Referenced by ProcessRequest().
#define lDestroyMail (mail) ffree((void*)addr_direct(mail))
Cleans up a mailbox.
Definition at line 66 of file mail.h.
Referenced by HandleWPD(), and ProcessRequest().
#define MAIL_GOTMAIL_FLAG (0x80000000)
Flag to indicate a valid value in a simple mailbox.
Definition at line 71 of file mail.h.
Referenced by MailPeek(), MailRead(), and MailWrite().
Typedef Documentation
typedef volatile unsigned int SimpleMail
A simple mailbox: one single 31-bit value.
If a single 32-bit value is required, use Mail with one element.
Definition at line 25 of file mail.h.
Function Documentation
static void _InitMail (volatile void * mail) [inline, static]
Definition at line 60 of file mail.h.
bool MailPeek (SimpleMail * box)
Checks whether there is mail in the box.
Parameters:
box the mailbox to check. Can be NULL, but then the function always returns false.
Returns:
true when there is
Definition at line 38 of file mail.cc.
References MAIL_GOTMAIL_FLAG.
Referenced by dBootKernels(), DefaultTaskDaemon(), FinishForwardedRequest(), and MailRead().
bool MailPeek (Mail * box, unsigned int number)
Checks whether the specified message has been received.
Parameters:
box the mailbox to check. Can be NULL, but then the function always returns false.
number the message to check
Returns:
true when there is
Definition at line 48 of file mail.cc.
References Mail::count.
unsigned int MailRead (SimpleMail * box)
Reads mail from the mailbox and blocks if there is nothing to read yet.
Yield()s when empty. If a Yield() is not desirable, do a busy wait on MailPeek(SimpleMail*) before calling MailRead(SimpleMail*).
Parameters:
box the mailbox to read
Returns:
0 when box==NULL, otherwise the message
Definition at line 62 of file mail.cc.
References MAIL_GOTMAIL_FLAG, MailPeek(), and Yield().
Referenced by dBootKernels(), FinishForwardedRequest(), GetIssueSlot(), HandleWPD(), StartDumpStatsDaemon(), StartMallocDaemon(), and StartTimerDaemon().
unsigned int MailRead (Mail * box, unsigned int index)
Reads mail from the mailbox and blocks if there is no message at the specified index yet.
Yield()s when the message at the specified index is not there yet. If a Yield() is not desirable, do a busy wait on MailPeek(Mail*,unsigned int) before calling MailRead(Mail*,unsigned int).
Parameters:
box the mailbox to read
index the index of the message to look at
Definition at line 78 of file mail.cc.
References MailPeek(), Mail::msgs, and Yield().
void MailWrite (SimpleMail * box, unsigned int msg)
Write a value to a simple mailbox.
Parameters:
box The mailbox to write to. When NULL, nothing happens.
msg The message to write. Only the 31 LSBs are written.
Definition at line 13 of file mail.cc.
References MAIL_GOTMAIL_FLAG.
Referenced by dBootKernel(), DumpStatsDaemon(), FinishForwardedRequest(), InitTaskDaemon(), MallocDaemon(), ProcessRequest(), TimerDaemon(), and WaitProcessDaemon().
void MailWrite (Mail * box, unsigned int index, unsigned int msg)
Write a value to a mailbox.
Parameters:
box The mailbox to write to. When NULL, nothing happens.
index The index to write the message to. Note that by writing at index n, all indices lower than n are assumed to be valid and ready to be read by the other side.
msg The message to be written.
Definition at line 25 of file mail.cc.
References Mail::count, and Mail::msgs.