Starburst: ipc/mail.cc File Reference
ipc/mail.cc File Reference
Send and receive functions for mailboxes.
#include <mail.h>
#include <sys/syscall.h>
#include <sys/io.h>
Functions
void MailWrite (SimpleMail *box, unsigned int msg)
Write a value to a simple mailbox.
void MailWrite (Mail *box, unsigned int index, unsigned int msg)
Write a value to a mailbox.
bool MailPeek (SimpleMail *box)
Checks whether there is mail in the box.
bool MailPeek (Mail *box, unsigned int number)
Checks whether the specified message has been received.
unsigned int MailRead (SimpleMail *box)
Reads mail from the mailbox and blocks if there is nothing to read yet.
unsigned int MailRead (Mail *box, unsigned int index)
Reads mail from the mailbox and blocks if there is no message at the specified index yet.
Detailed Description
Send and receive functions for mailboxes.
Definition in file mail.cc.
Function Documentation
bool MailPeek (SimpleMail * box)
Checks whether there is mail in the box.
Parameters:
box the mailbox to check. Can be NULL, but then the function always returns false.
Returns:
true when there is
Definition at line 38 of file mail.cc.
References MAIL_GOTMAIL_FLAG.
Referenced by dBootKernels(), DefaultTaskDaemon(), FinishForwardedRequest(), and MailRead().
bool MailPeek (Mail * box, unsigned int number)
Checks whether the specified message has been received.
Parameters:
box the mailbox to check. Can be NULL, but then the function always returns false.
number the message to check
Returns:
true when there is
Definition at line 48 of file mail.cc.
References Mail::count.
unsigned int MailRead (SimpleMail * box)
Reads mail from the mailbox and blocks if there is nothing to read yet.
Yield()s when empty. If a Yield() is not desirable, do a busy wait on MailPeek(SimpleMail*) before calling MailRead(SimpleMail*).
Parameters:
box the mailbox to read
Returns:
0 when box==NULL, otherwise the message
Definition at line 62 of file mail.cc.
References MAIL_GOTMAIL_FLAG, MailPeek(), and Yield().
Referenced by dBootKernels(), FinishForwardedRequest(), GetIssueSlot(), HandleWPD(), StartDumpStatsDaemon(), StartMallocDaemon(), and StartTimerDaemon().
unsigned int MailRead (Mail * box, unsigned int index)
Reads mail from the mailbox and blocks if there is no message at the specified index yet.
Yield()s when the message at the specified index is not there yet. If a Yield() is not desirable, do a busy wait on MailPeek(Mail*,unsigned int) before calling MailRead(Mail*,unsigned int).
Parameters:
box the mailbox to read
index the index of the message to look at
Definition at line 78 of file mail.cc.
References MailPeek(), Mail::msgs, and Yield().
void MailWrite (SimpleMail * box, unsigned int msg)
Write a value to a simple mailbox.
Parameters:
box The mailbox to write to. When NULL, nothing happens.
msg The message to write. Only the 31 LSBs are written.
Definition at line 13 of file mail.cc.
References MAIL_GOTMAIL_FLAG.
Referenced by dBootKernel(), DumpStatsDaemon(), FinishForwardedRequest(), InitTaskDaemon(), MallocDaemon(), ProcessRequest(), TimerDaemon(), and WaitProcessDaemon().
void MailWrite (Mail * box, unsigned int index, unsigned int msg)
Write a value to a mailbox.
Parameters:
box The mailbox to write to. When NULL, nothing happens.
index The index to write the message to. Note that by writing at index n, all indices lower than n are assumed to be valid and ready to be read by the other side.
msg The message to be written.
Definition at line 25 of file mail.cc.
References Mail::count, and Mail::msgs.