Starburst: kernel/malloc.cc File Reference
kernel/malloc.cc File Reference
Heap management.
#include <unistd.h>
#include <malloc.h>
#include <sys/kernel.h>
#include <sys/api.h>
#include <stdio.h>
#include <string.h>
#include <daemons.h>
#include <pthread.h>
#include <sys/helix_config.h>
#include <mc.h>
#include <llock.h>
Defines
#define FILL_CACHELINE(a) ((char*)((((unsigned int)(a)-1)|(CACHELINE_ALIGN-1))+1))
#define HEAP_NODE_SIZE ((size_t)FILL_CACHELINE(sizeof(HEAP_NODE)))
#define DEBUG(str, a...) printf("malloc %d: " str "\n",GetProcID(),##a);
Functions
static size_t alloc_size (HEAP *const heap, void *ptr)
static void remove_from_size_list (HEAP *const heap, HEAP_NODE *ptr)
static void insert_in_size_list (HEAP *const heap, HEAP_NODE *ptr)
static void remove_from_addr_list (HEAP *const heap, HEAP_NODE *ptr)
static void insert_in_addr_list (HEAP *const heap, HEAP_NODE *ptr)
static void remove_from_used_list (HEAP *const heap, HEAP_NODE *ptr)
static void insert_in_used_list (HEAP *const heap, HEAP_NODE *ptr, pid_t owner)
static void compact_node (HEAP *const heap, HEAP_NODE *ptr)
void malloc_init (HEAP **heap, void *buffer, uint32_t length)
void * malloc (size_t size)
void * fmalloc (size_t size)
void * smalloc (size_t size)
void * omalloc (size_t size, pid_t owner)
void * _malloc (HEAP *const heap, size_t size, pid_t owner)
void * calloc (size_t nmemb, size_t size)
void * fcalloc (size_t nmemb, size_t size)
void * scalloc (size_t nmemb, size_t size)
void * _calloc (HEAP *const heap, size_t nmemb, size_t size, pid_t owner)
void * realloc (void *ptr, size_t size)
void * frealloc (void *ptr, size_t size)
void * srealloc (void *ptr, size_t size)
void * orealloc (void *ptr, size_t size, pid_t owner)
void * _realloc (HEAP *const heap, void *ptr, size_t size, pid_t owner)
int mown (void *ptr, pid_t owner)
int fmown (void *ptr, pid_t owner)
int smown (void *ptr, pid_t owner)
int _mown (HEAP *const heap, void *ptr, pid_t owner, pid_t oldowner)
void free (void *ptr)
void ffree (void *ptr)
void sfree (void *ptr)
void _free (HEAP *const heap, void *ptr, pid_t owner)
void freeAll (pid_t owner)
void ffreeAll (pid_t owner)
void sfreeAll (pid_t owner)
void _freeAll (HEAP *const heap, pid_t owner)
void malloc_dump (HEAP *const heap)
void * __real_malloc (size_t size)
void * __real_realloc (void *ptr, size_t size)
void * __real_calloc (size_t nmemb, size_t size)
void __real_free (void *ptr)
void * _malloc_r (struct _reent *, size_t size)
void _free_r (struct _reent *, void *p)
void * _realloc_r (struct _reent *, void *p, size_t size)
void * _calloc_r (struct _reent *, size_t nmemb, size_t size)
char * strdup (const char *s)
char * strndup (const char *s, size_t n)
void * operator new (long unsigned size)
void operator delete (void *p)
void * operator new[] (long unsigned size)
void operator delete[] (void *p)
Detailed Description
Heap management.
This implementation is not thread safe. There is no check how much memory a process already has, so one process could consume all memory, preventing other processes of having some.
It would be nice to check the total allocated memory and prevent allocating too much memory. This improves composable behavior: processes do not influence each other. However, sharing the same heap leads to fragmentation, which leads to sub-optimal allocation, which can lead to less memory than expected in advance...
HEAP_NODE is quite large. Therefore, a lot of memory is consumed by administration. This must be improved.
Definition in file malloc.cc.
Define Documentation
#define DEBUG (str, a...) printf("malloc %d: " str "\n",GetProcID(),##a);
Definition at line 56 of file malloc.cc.
#define FILL_CACHELINE (a) ((char*)((((unsigned int)(a)-1)|(CACHELINE_ALIGN-1))+1))
Definition at line 52 of file malloc.cc.
Referenced by _calloc(), _malloc(), and malloc_init().
#define HEAP_NODE_SIZE ((size_t)FILL_CACHELINE(sizeof(HEAP_NODE)))
Definition at line 53 of file malloc.cc.
Referenced by _malloc(), compact_node(), and malloc_init().
Function Documentation
void* __real_calloc (size_t nmemb, size_t size)
Definition at line 737 of file malloc.cc.
References calloc().
void __real_free (void * ptr)
Definition at line 741 of file malloc.cc.
References free().
void* __real_malloc (size_t size)
Definition at line 729 of file malloc.cc.
References malloc().
void* __real_realloc (void * ptr, size_t size)
Definition at line 733 of file malloc.cc.
References realloc().
void* _calloc (HEAP *const heap, size_t nmemb, size_t size, pid_t owner)
Definition at line 289 of file malloc.cc.
References _malloc(), and FILL_CACHELINE.
Referenced by calloc(), fcalloc(), MallocDaemonHandler(), and scalloc().
void* _calloc_r (struct _reent * , size_t nmemb, size_t size)
Definition at line 758 of file malloc.cc.
References lcalloc.
void _free (HEAP *const heap, void * ptr, pid_t owner)
Definition at line 468 of file malloc.cc.
References compact_node(), insert_in_addr_list(), insert_in_size_list(), HNTAG::owner, HNTAG::pHole, HNTAG::pNextAddr, HTAG::pUsedList, and remove_from_used_list().
Referenced by _realloc(), ffree(), free(), MallocDaemonHandler(), and sfree().
void _free_r (struct _reent * , void * p)
Definition at line 756 of file malloc.cc.
References lfree.
void _freeAll (HEAP *const heap, pid_t owner)
Definition at line 519 of file malloc.cc.
References compact_node(), insert_in_addr_list(), insert_in_size_list(), HNTAG::owner, HNTAG::pNextAddr, HTAG::pUsedList, and remove_from_used_list().
Referenced by ffreeAll(), freeAll(), MallocDaemonHandler(), and sfreeAll().
void* _malloc (HEAP *const heap, size_t size, pid_t owner)
Definition at line 167 of file malloc.cc.
References _putn, _putp(), _puts(), FILL_CACHELINE, HEAP_NODE_SIZE, insert_in_addr_list(), insert_in_size_list(), insert_in_used_list(), HNTAG::nLength, HNTAG::pHole, HNTAG::pNextSize, HTAG::pSizeList, remove_from_addr_list(), and remove_from_size_list().
Referenced by _calloc(), _realloc(), fmalloc(), malloc_init(), MallocDaemonHandler(), omalloc(), and smalloc().
void* _malloc_r (struct _reent * , size_t size)
Definition at line 755 of file malloc.cc.
References lmalloc.
int _mown (HEAP *const heap, void * ptr, pid_t owner, pid_t oldowner)
Definition at line 410 of file malloc.cc.
References ESUCCESS, getpid(), HNTAG::owner, HNTAG::pHole, HNTAG::pNextAddr, and HTAG::pUsedList.
Referenced by fmown(), MallocDaemonHandler(), mown(), and smown().
void* _realloc (HEAP *const heap, void * ptr, size_t size, pid_t owner)
Definition at line 352 of file malloc.cc.
References _free(), _malloc(), and alloc_size().
Referenced by frealloc(), MallocDaemonHandler(), orealloc(), and srealloc().
void* _realloc_r (struct _reent * , void * p, size_t size)
Definition at line 757 of file malloc.cc.
References lrealloc.
static size_t alloc_size (HEAP *const heap, void * ptr) [static]
Definition at line 370 of file malloc.cc.
References HNTAG::nLength, HNTAG::pHole, HNTAG::pNextAddr, and HTAG::pUsedList.
Referenced by _realloc().
void* calloc (size_t nmemb, size_t size)
Definition at line 249 of file malloc.cc.
References _calloc(), _pheap, b, GetHook(), getpid(), getupid(), HOOK_MALLOC, IssueMallocRequest(), MD_CALLOC, malloc_buffer_t::newptr, malloc_buffer_t::nmemb, and malloc_buffer_t::size.
Referenced by __real_calloc(), and PMC_NS::LocalAlloc::operator new().
static void compact_node (HEAP *const heap, HEAP_NODE * ptr) [static]
Definition at line 539 of file malloc.cc.
References HEAP_NODE_SIZE, insert_in_size_list(), HNTAG::nLength, HNTAG::pNextAddr, HNTAG::pPrevAddr, and remove_from_size_list().
Referenced by _free(), and _freeAll().
void* fcalloc (size_t nmemb, size_t size)
Definition at line 264 of file malloc.cc.
References _calloc(), _fifomem, getpid(), llck(), and lulck().
void ffree (void * ptr)
Definition at line 448 of file malloc.cc.
References _fifomem, _free(), getpid(), llck(), and lulck().
Referenced by dBootKernels(), PMC_NS::SASPMBackend< T, C >::exit_ro(), PMC_NS::SPMBackend< T >::exit_ro(), PMC_NS::SASPMBackend< T, C >::exit_x(), PMC_NS::SPMBackend< T >::exit_x(), linfs_unregister(), operator delete(), operator delete[](), and WorkQueue< T, W >::~WorkQueue().
void ffreeAll (pid_t owner)
Definition at line 509 of file malloc.cc.
References _fifomem, _freeAll(), llck(), and lulck().
Referenced by kDestroyProcess().
void* fmalloc (size_t size)
Definition at line 127 of file malloc.cc.
References _fifomem, _malloc(), getpid(), llck(), and lulck().
int fmown (void * ptr, pid_t owner)
Definition at line 399 of file malloc.cc.
References _fifomem, _mown(), getpid(), llck(), and lulck().
void* frealloc (void * ptr, size_t size)
Definition at line 306 of file malloc.cc.
References _fifomem, _realloc(), getpid(), llck(), and lulck().
void free (void * ptr)
Definition at line 435 of file malloc.cc.
References _free(), _pheap, b, GetHook(), getpid(), getupid(), HOOK_MALLOC, IssueMallocRequest(), MD_FREE, and malloc_buffer_t::oldptr.
Referenced by __real_free(), _getopt_internal(), bitshark_test_debug(), linfs_register(), linfs_unregister(), PMC_NS::LocalAlloc::operator delete(), TraceDump(), and TraceLog().
void freeAll (pid_t owner)
Definition at line 496 of file malloc.cc.
References _freeAll(), _pheap, b, GetHook(), getupid(), HOOK_MALLOC, IssueMallocRequest(), MD_FREEALL, and malloc_buffer_t::owner.
Referenced by kDestroyProcess().
static void insert_in_addr_list (HEAP *const heap, HEAP_NODE * ptr) [static]
Definition at line 617 of file malloc.cc.
References HTAG::pAddrList, HNTAG::pHole, HNTAG::pNextAddr, and HNTAG::pPrevAddr.
Referenced by _free(), _freeAll(), and _malloc().
static void insert_in_size_list (HEAP *const heap, HEAP_NODE * ptr) [static]
Definition at line 583 of file malloc.cc.
References HNTAG::nLength, HNTAG::pNextSize, HNTAG::pPrevSize, and HTAG::pSizeList.
Referenced by _free(), _freeAll(), _malloc(), and compact_node().
static void insert_in_used_list (HEAP *const heap, HEAP_NODE * ptr, pid_t owner) [static]
Definition at line 652 of file malloc.cc.
References HNTAG::owner, HNTAG::pHole, HNTAG::pNextAddr, HNTAG::pPrevAddr, and HTAG::pUsedList.
Referenced by _malloc().
void* malloc (size_t size)
Definition at line 123 of file malloc.cc.
References getpid(), and omalloc().
Referenced by __real_malloc(), _getopt_initialize(), bitshark_test_debug(), exchange(), kStartTaskDaemon(), linfs_register(), and CFifo< T, CFifo<>::w >::operator new().
void malloc_dump (HEAP *const heap)
Definition at line 679 of file malloc.cc.
References GetProcID(), HNTAG::nLength, HNTAG::owner, HTAG::pAddrList, HNTAG::pHole, HNTAG::pNextAddr, printk, and HTAG::pUsedList.
Referenced by kInitKernel(), and kPanic().
void malloc_init (HEAP ** heap, void * buffer, uint32_t length)
Definition at line 84 of file malloc.cc.
References _malloc(), _sheap, CACHELINE_ALIGN, FILL_CACHELINE, HEAP_NODE_SIZE, llck_init(), HTAG::lock, HNTAG::nLength, HTAG::pAddrList, HNTAG::pHole, HNTAG::pNextAddr, HNTAG::pNextSize, HNTAG::pPrevAddr, HNTAG::pPrevSize, HTAG::pSizeList, pthread_mutex_init(), and HTAG::pUsedList.
Referenced by InitSHeap(), and kInitKernel().
int mown (void * ptr, pid_t owner)
Definition at line 384 of file malloc.cc.
References _mown(), _pheap, b, GetHook(), getpid(), getupid(), HOOK_MALLOC, IssueMallocRequest(), MD_MOWN, malloc_buffer_t::oldptr, malloc_buffer_t::owner, and malloc_buffer_t::ret.
void* omalloc (size_t size, pid_t owner)
Definition at line 152 of file malloc.cc.
References _malloc(), _pheap, b, GetHook(), getupid(), HOOK_MALLOC, IssueMallocRequest(), MD_MALLOC, malloc_buffer_t::newptr, malloc_buffer_t::owner, and malloc_buffer_t::size.
Referenced by kCreateProcess(), and malloc().
void operator delete (void * p)
Definition at line 800 of file malloc.cc.
References _sheap, ffree(), and sfree().
Referenced by PMC_NS::SharedMemPool::free(), PMC_NS::Var< pointer_t, B >::operator delete(), PlacementDelete< T, Tref >::operator=(), and PlacementDelete< T, void >::operator=().
void operator delete[] (void * p)
Definition at line 814 of file malloc.cc.
References _sheap, ffree(), and sfree().
Referenced by PMC_NS::Var< pointer_t, B >::operator delete[]().
void* operator new (long unsigned size)
Definition at line 793 of file malloc.cc.
References abort(), and smalloc().
Referenced by PMC_NS::SharedMemPool::alloc(), CFifo< T, CFifo<>::w >::operator new(), and PMC_NS::Var< pointer_t, B >::operator new().
void* operator new[] (long unsigned size)
Definition at line 807 of file malloc.cc.
References abort(), and smalloc().
Referenced by CFifo< T, CFifo<>::r >::operator new[](), and PMC_NS::Var< pointer_t, B >::operator new[]().
void* orealloc (void * ptr, size_t size, pid_t owner)
Definition at line 336 of file malloc.cc.
References _pheap, _realloc(), b, GetHook(), getupid(), HOOK_MALLOC, IssueMallocRequest(), MD_REALLOC, malloc_buffer_t::newptr, malloc_buffer_t::oldptr, malloc_buffer_t::owner, and malloc_buffer_t::size.
Referenced by kAllocChannels(), and realloc().
void* realloc (void * ptr, size_t size)
Definition at line 302 of file malloc.cc.
References getpid(), and orealloc().
Referenced by __real_realloc().
static void remove_from_addr_list (HEAP *const heap, HEAP_NODE * ptr) [static]
Definition at line 608 of file malloc.cc.
References HTAG::pAddrList, HNTAG::pNextAddr, and HNTAG::pPrevAddr.
Referenced by _malloc().
static void remove_from_size_list (HEAP *const heap, HEAP_NODE * ptr) [static]
Definition at line 574 of file malloc.cc.
References HNTAG::pNextSize, HNTAG::pPrevSize, and HTAG::pSizeList.
Referenced by _malloc(), and compact_node().
static void remove_from_used_list (HEAP *const heap, HEAP_NODE * ptr) [static]
Definition at line 643 of file malloc.cc.
References HNTAG::pNextAddr, HNTAG::pPrevAddr, and HTAG::pUsedList.
Referenced by _free(), and _freeAll().
void* scalloc (size_t nmemb, size_t size)
Definition at line 271 of file malloc.cc.
References _calloc(), _sheap, dSCalloc(), getpid(), GetProcID(), mc_flush_(), pthread_mutex_lock(), pthread_mutex_unlock(), and SMALLOC_PROC.
void sfree (void * ptr)
Definition at line 454 of file malloc.cc.
References _free(), _sheap, dSFree(), getpid(), GetProcID(), pthread_mutex_lock(), pthread_mutex_unlock(), and SMALLOC_PROC.
Referenced by DumpStatsDaemon(), linfs_unregister(), PMC_NS::SharedAlloc::operator delete(), operator delete(), operator delete[](), pipe_close(), ProcessRequest(), and dvi_screen::~dvi_screen().
void sfreeAll (pid_t owner)
Definition at line 515 of file malloc.cc.
References _freeAll(), and _sheap.
void* smalloc (size_t size)
Definition at line 134 of file malloc.cc.
References _malloc(), _sheap, dSMalloc(), getpid(), GetProcID(), pthread_mutex_lock(), pthread_mutex_unlock(), and SMALLOC_PROC.
int smown (void * ptr, pid_t owner)
Definition at line 406 of file malloc.cc.
References _mown(), _sheap, and getpid().
void* srealloc (void * ptr, size_t size)
Definition at line 316 of file malloc.cc.
References _realloc(), _sheap, dSRealloc(), getpid(), GetProcID(), mc_flush_(), pthread_mutex_lock(), pthread_mutex_unlock(), and SMALLOC_PROC.
Referenced by ProcessRequest().
char* strdup (const char * s)
Definition at line 766 of file malloc.cc.
References strndup().
char* strndup (const char * s, size_t n)
Definition at line 768 of file malloc.cc.
References _sheap, lmalloc, mc_flush_(), and smalloc().
Referenced by strdup().