Starburst: include/malloc.h File Reference
include/malloc.h File Reference
#include <stdint.h>
#include <stdlib.h>
#include <sys/types.h>
#include <sys/helix_config.h>
#include <sys/kernel_types.h>
#include <sys/device.h>
#include <new>
#include <ttypes.h>
Data Structures
struct HNTAG
struct HTAG
struct delete_by_ref
class PlacementDelete< T, Tref >
class PlacementDelete< T, void >
Defines
#define lmalloc(a...) malloc(a)
#define lrealloc(a...) realloc(a)
#define lcalloc(a...) calloc(a)
#define lfree(a...) free(a)
#define pdelete(a) (PlacementDelete<typeof(a),typeof(delete_by_ref::f(a))>(a))=
Typedefs
typedef struct HNTAG HEAP_NODE
typedef struct HTAG HEAP
Functions
void malloc_init (HEAP **heap, void *buffer, uint32_t length) _NO_THROW
void malloc_dump (HEAP *heap) _NO_THROW
void * fmalloc (size_t size) _NO_THROW __attribute__((malloc
void * fcalloc (size_t nmemb, size_t size) _NO_THROW __attribute__((malloc
void * frealloc (void *ptr, size_t size) _NO_THROW __attribute__((warn_unused_result))
void ffree (void *ptr) _NO_THROW
void * smalloc (size_t size) _NO_THROW __attribute__((malloc
void * scalloc (size_t nmemb, size_t size) _NO_THROW __attribute__((malloc
void * srealloc (void *ptr, size_t size) _NO_THROW __attribute__((warn_unused_result))
void sfree (void *ptr) _NO_THROW
void freeAll (pid_t owner) _NO_THROW
void ffreeAll (pid_t owner) _NO_THROW
void sfreeAll (pid_t owner) _NO_THROW
void * omalloc (size_t size, pid_t owner) _NO_THROW __attribute__((warn_unused_result))
void * orealloc (void *ptr, size_t size, pid_t owner) _NO_THROW __attribute__((warn_unused_result))
int mown (void *ptr, pid_t owner) _NO_THROW
int fmown (void *ptr, pid_t owner) _NO_THROW
int smown (void *ptr, pid_t owner) _NO_THROW
void * _malloc (HEAP *const heap, size_t size, pid_t owner) _NO_THROW __attribute__((malloc))
void * _calloc (HEAP *const heap, size_t nmemb, size_t size, pid_t owner) _NO_THROW __attribute__((malloc))
void * _realloc (HEAP *const heap, void *ptr, size_t size, pid_t owner) _NO_THROW
int _mown (HEAP *const heap, void *ptr, pid_t owner, pid_t oldowner) _NO_THROW
void _free (HEAP *const heap, void *ptr, pid_t owner) _NO_THROW
void _freeAll (HEAP *const heap, pid_t owner) _NO_THROW
Variables
void warn_unused_result
HEAP *const _sheap
Define Documentation
#define lcalloc (a...) calloc(a)
Definition at line 95 of file malloc.h.
Referenced by _calloc_r(), kInitKernel(), kTraceInit(), lck_register(), pthread_stats_thread_init(), StartMallocDaemon(), and StatsInit().
#define lfree (a...) free(a)
Definition at line 96 of file malloc.h.
Referenced by _free_r(), closedir(), kTraceInit(), pthread_stats_thread_cleanup(), pthread_stats_thread_init(), SetupProfilerDaemon(), and StopMallocDaemon().
#define lmalloc (a...) malloc(a)
Definition at line 93 of file malloc.h.
Referenced by _malloc_r(), InitTaskDaemon(), lck_tree_add(), opendir(), realpath(), SetupProfilerDaemon(), strndup(), and TimerDaemon().
#define lrealloc (a...) realloc(a)
Definition at line 94 of file malloc.h.
Referenced by _realloc_r().
#define pdelete (a) (PlacementDelete<typeof(a),typeof(delete_by_ref::f(a))>(a))=
Definition at line 135 of file malloc.h.
Referenced by PMC_NS::FifoMemPool< Tsa, N, B >::pop().
Typedef Documentation
typedef struct HTAG HEAP
typedef struct HNTAG HEAP_NODE
Function Documentation
void* _calloc (HEAP *const heap, size_t nmemb, size_t size, pid_t owner)
Definition at line 289 of file malloc.cc.
References _malloc(), and FILL_CACHELINE.
Referenced by calloc(), fcalloc(), MallocDaemonHandler(), and scalloc().
void _free (HEAP *const heap, void * ptr, pid_t owner)
Definition at line 468 of file malloc.cc.
References compact_node(), insert_in_addr_list(), insert_in_size_list(), HNTAG::owner, HNTAG::pHole, HNTAG::pNextAddr, HTAG::pUsedList, and remove_from_used_list().
Referenced by _realloc(), ffree(), free(), MallocDaemonHandler(), and sfree().
void _freeAll (HEAP *const heap, pid_t owner)
Definition at line 519 of file malloc.cc.
References compact_node(), insert_in_addr_list(), insert_in_size_list(), HNTAG::owner, HNTAG::pNextAddr, HTAG::pUsedList, and remove_from_used_list().
Referenced by ffreeAll(), freeAll(), MallocDaemonHandler(), and sfreeAll().
void* _malloc (HEAP *const heap, size_t size, pid_t owner)
Definition at line 167 of file malloc.cc.
References _putn, _putp(), _puts(), FILL_CACHELINE, HEAP_NODE_SIZE, insert_in_addr_list(), insert_in_size_list(), insert_in_used_list(), HNTAG::nLength, HNTAG::pHole, HNTAG::pNextSize, HTAG::pSizeList, remove_from_addr_list(), and remove_from_size_list().
Referenced by _calloc(), _realloc(), fmalloc(), malloc_init(), MallocDaemonHandler(), omalloc(), and smalloc().
int _mown (HEAP *const heap, void * ptr, pid_t owner, pid_t oldowner)
Definition at line 410 of file malloc.cc.
References ESUCCESS, getpid(), HNTAG::owner, HNTAG::pHole, HNTAG::pNextAddr, and HTAG::pUsedList.
Referenced by fmown(), MallocDaemonHandler(), mown(), and smown().
void* _realloc (HEAP *const heap, void * ptr, size_t size, pid_t owner)
Definition at line 352 of file malloc.cc.
References _free(), _malloc(), and alloc_size().
Referenced by frealloc(), MallocDaemonHandler(), orealloc(), and srealloc().
void* fcalloc (size_t nmemb, size_t size)
void ffree (void * ptr)
Definition at line 448 of file malloc.cc.
References _fifomem, _free(), getpid(), llck(), and lulck().
Referenced by dBootKernels(), PMC_NS::SASPMBackend< T, C >::exit_ro(), PMC_NS::SPMBackend< T >::exit_ro(), PMC_NS::SASPMBackend< T, C >::exit_x(), PMC_NS::SPMBackend< T >::exit_x(), linfs_unregister(), operator delete(), operator delete[](), and WorkQueue< T, W >::~WorkQueue().
void ffreeAll (pid_t owner)
Definition at line 509 of file malloc.cc.
References _fifomem, _freeAll(), llck(), and lulck().
Referenced by kDestroyProcess().
void* fmalloc (size_t size)
Referenced by dBootKernels(), InitTaskDaemon(), linfs_register(), CFifo< T, CFifo<>::w >::operator new(), and WorkQueue< T, W >::WorkQueue().
int fmown (void * ptr, pid_t owner)
Definition at line 399 of file malloc.cc.
References _fifomem, _mown(), getpid(), llck(), and lulck().
void* frealloc (void * ptr, size_t size)
Definition at line 306 of file malloc.cc.
References _fifomem, _realloc(), getpid(), llck(), and lulck().
void freeAll (pid_t owner)
Definition at line 496 of file malloc.cc.
References _freeAll(), _pheap, b, GetHook(), getupid(), HOOK_MALLOC, IssueMallocRequest(), MD_FREEALL, and malloc_buffer_t::owner.
Referenced by kDestroyProcess().
void malloc_dump (HEAP * heap)
Definition at line 679 of file malloc.cc.
References GetProcID(), HNTAG::nLength, HNTAG::owner, HTAG::pAddrList, HNTAG::pHole, HNTAG::pNextAddr, printk, and HTAG::pUsedList.
Referenced by kInitKernel(), and kPanic().
void malloc_init (HEAP ** heap, void * buffer, uint32_t length)
Definition at line 84 of file malloc.cc.
References _malloc(), _sheap, CACHELINE_ALIGN, FILL_CACHELINE, HEAP_NODE_SIZE, llck_init(), HTAG::lock, HNTAG::nLength, HTAG::pAddrList, HNTAG::pHole, HNTAG::pNextAddr, HNTAG::pNextSize, HNTAG::pPrevAddr, HNTAG::pPrevSize, HTAG::pSizeList, pthread_mutex_init(), and HTAG::pUsedList.
Referenced by InitSHeap(), and kInitKernel().
int mown (void * ptr, pid_t owner)
Definition at line 384 of file malloc.cc.
References _mown(), _pheap, b, GetHook(), getpid(), getupid(), HOOK_MALLOC, IssueMallocRequest(), MD_MOWN, malloc_buffer_t::oldptr, malloc_buffer_t::owner, and malloc_buffer_t::ret.
void* omalloc (size_t size, pid_t owner)
Definition at line 152 of file malloc.cc.
References _malloc(), _pheap, b, GetHook(), getupid(), HOOK_MALLOC, IssueMallocRequest(), MD_MALLOC, malloc_buffer_t::newptr, malloc_buffer_t::owner, and malloc_buffer_t::size.
Referenced by kCreateProcess(), and malloc().
void* orealloc (void * ptr, size_t size, pid_t owner)
Definition at line 336 of file malloc.cc.
References _pheap, _realloc(), b, GetHook(), getupid(), HOOK_MALLOC, IssueMallocRequest(), MD_REALLOC, malloc_buffer_t::newptr, malloc_buffer_t::oldptr, malloc_buffer_t::owner, and malloc_buffer_t::size.
Referenced by kAllocChannels(), and realloc().
void* scalloc (size_t nmemb, size_t size)
Referenced by PMC_NS::SharedAlloc::operator new(), and ProcessRequest().
void sfree (void * ptr)
Definition at line 454 of file malloc.cc.
References _free(), _sheap, dSFree(), getpid(), GetProcID(), pthread_mutex_lock(), pthread_mutex_unlock(), and SMALLOC_PROC.
Referenced by DumpStatsDaemon(), linfs_unregister(), PMC_NS::SharedAlloc::operator delete(), operator delete(), operator delete[](), pipe_close(), ProcessRequest(), and dvi_screen::~dvi_screen().
void sfreeAll (pid_t owner)
Definition at line 515 of file malloc.cc.
References _freeAll(), and _sheap.
void* smalloc (size_t size)
Referenced by createCB(), createCBO(), createLB(), DumpStatsDaemon(), linfs_register(), CFifo< T, CFifo<>::w >::operator new(), operator new(), operator new[](), pipe(), ProcessRequest(), render_alloc_buf(), and strndup().
int smown (void * ptr, pid_t owner)
Definition at line 406 of file malloc.cc.
References _mown(), _sheap, and getpid().
void* srealloc (void * ptr, size_t size)
Definition at line 316 of file malloc.cc.
References _realloc(), _sheap, dSRealloc(), getpid(), GetProcID(), mc_flush_(), pthread_mutex_lock(), pthread_mutex_unlock(), and SMALLOC_PROC.
Referenced by ProcessRequest().
Variable Documentation
HEAP* const _sheap
Referenced by InitSHeap(), malloc_init(), operator delete(), operator delete[](), scalloc(), sfree(), sfreeAll(), smalloc(), smown(), srealloc(), and strndup().
void warn_unused_result
Definition at line 51 of file malloc.h.