Starburst: daemons/MallocDaemon.cc File Reference
daemons/MallocDaemon.cc File Reference
Daemons
A daemon to handle all malloc (and friends) requests in predictable order, thread-safe.
#include <unistd.h>
#include <sys/api.h>
#include <sys/syscall.h>
#include <daemons.h>
#include <sys/hooks.h>
Data Structures
struct md_t
Defines
#define MALLOC_SIGNAL_BASED
#define MAX_U_PROCESSES (2*MAX_PROCESSES)
#define MALLOC_PID 1
#define MALLOC_SIGNAL SIGUSR1
Functions
void MallocDaemonHandler (int sig)
void * MallocDaemon (void *arg)
Daemon to handle all processor heap operations.
int StartMallocDaemon ()
Starts the MallocDaemon().
int StopMallocDaemon ()
Stops the MallocDaemon().
void IssueMallocRequest (malloc_buffer_t *b, malloc_req_t type)
Sends a request to the MallocDaemon().
Detailed Description
A daemon to handle all malloc (and friends) requests in predictable order, thread-safe.
Definition in file MallocDaemon.cc.
Define Documentation
#define MALLOC_PID 1
Definition at line 19 of file MallocDaemon.cc.
Referenced by IssueMallocRequest(), and StartMallocDaemon().
#define MALLOC_SIGNAL SIGUSR1
Definition at line 20 of file MallocDaemon.cc.
Referenced by IssueMallocRequest(), and MallocDaemon().
#define MALLOC_SIGNAL_BASED
Definition at line 13 of file MallocDaemon.cc.
#define MAX_U_PROCESSES (2*MAX_PROCESSES)
Definition at line 14 of file MallocDaemon.cc.
Referenced by MallocDaemonHandler(), and StartMallocDaemon().
Function Documentation
void IssueMallocRequest (malloc_buffer_t * b, malloc_req_t type)
Sends a request to the MallocDaemon().
For internal use only. Use normal malloc() and friends.
Parameters:
b the malloc buffer to communicate with
type the request type
Returns:
after the request has been served
Definition at line 219 of file MallocDaemon.cc.
References lSendSignal(), MALLOC_PID, MALLOC_SIGNAL, MD_ACK, MD_NONE, malloc_buffer_t::request, and Yield().
Referenced by calloc(), free(), freeAll(), mown(), omalloc(), orealloc(), and StopMallocDaemon().
void* MallocDaemon (void * arg)
Daemon to handle all processor heap operations.
Every process can have one outstanding malloc/calloc/realloc/mown/free request. The daemon will handle all requests in order of process id. When all requests are processed, the daemon Yield()s. This means that all heap requests are serviced in one complete scheduling period, assuming that the daemon finishes before the end of its timeslice. The heap will not be locked; locking is implicit by using this daemon.
The FIFO heap and shared heap are not managed by this daemon. The daemon should be started by calling StartMallocDaemon().
Parameters:
arg a pointer to a malloc_buffer_t[MAX_PROCESSES*2], cannot be null
Returns:
(void*)errno
Definition at line 107 of file MallocDaemon.cc.
References md_t::b, b, HOOK_MALLOC, md_t::m, MailWrite(), MALLOC_SIGNAL, MallocDaemonHandler(), pause(), sigaction::sa_flags, sigaction::sa_handler, sigaction::sa_mask, SA_NODEFER, set_no_gracefull_exit(), sigaction(), sigemptyset(), thread_local, and UnregisterHook().
Referenced by StartMallocDaemon().
void MallocDaemonHandler (int sig)
Definition at line 22 of file MallocDaemon.cc.
References _calloc(), _free(), _freeAll(), _malloc(), _mown(), _pheap, _realloc(), b, getpid(), MAX_PROCESSES, MAX_U_PROCESSES, MD_ACK, MD_CALLOC, MD_EXIT, MD_FREE, MD_FREEALL, MD_MALLOC, MD_MOWN, malloc_buffer_t::md_pid, MD_REALLOC, malloc_buffer_t::newptr, pid, malloc_buffer_t::request, malloc_buffer_t::ret, thread_local, and Yield().
Referenced by MallocDaemon().
int StopMallocDaemon ()
Stops the MallocDaemon().
A stop signal is sent to the daemon. When all outstanding requests are handled, the daemon will exit eventually. This function will join the MallocDaemon process, so when the function returns, malloc()s have become thread-unsafe again. It is not safe to stop the daemon when malloc()s are in process. Race-conditions can occur, resulting in malloc()s that get never processed.
Returns:
0 on success, otherwise an errno
Definition at line 187 of file MallocDaemon.cc.
References b, ESUCCESS, GetHook(), getupid(), HOOK_MALLOC, IssueMallocRequest(), lDestroyProcess(), lfree, lJoinProcess(), MD_EXIT, malloc_buffer_t::md_pid, and UnregisterHook().