Starburst: include/mapping.h File Reference
include/mapping.h File Reference
API for mapper output and OS input for starting and stopping complete applications.
Data Structures
struct map_core_t
A description of a core.
struct map_hardware_t
A list of all cores in the system.
struct map_impl_memory_t
Implementation: read/write operations to a single address in memory mapped I/O.
struct map_impl_link_t
Implementation: a route over the network.
struct map_impl_process_t
Implementation: a process, specified by a function pointer.
struct map_impl_fifo_t
Implementation: a simple FIFO.
struct map_impl_mailbox_t
Implementation: a mailbox.
struct map_implementation_t
Implementation of a task and port.
struct map_port_t
A port: the connection between one task and another.
struct map_task_t
A task: a node with smart behavior.
struct map_application_t
An application: a set of connected tasks.
struct map_impl_layout_t
Information about the chosen binding and mapping.
struct map_task_layout_t
Binding/mapping information of this task and all its ports.
struct map_app_layout_t
Binding/mapping information of all tasks of this application.
Typedefs
typedef struct map_core_t map_core_t
A description of a core.
typedef struct map_task_t map_task_t
A task: a node with smart behavior.
typedef struct map_port_t map_port_t
A port: the connection between one task and another.
Enumerations
enum map_core_type_t { CORE_MICROBLAZE, CORE_COMM_MEM, CORE_SHARED_HEAP, CORE_DEDICATED }
enum map_implementation_type_t {
IMPL_MEMORY, IMPL_ROUTE, IMPL_PROCESS, IMPL_FIFO,
IMPL_MAILBOX, IMPL_DEDICATED
}
enum map_port_role_t { ROLE_UNUSED, ROLE_PRODUCER, ROLE_CONSUMER }
Functions
int map_init (map_hardware_t *hardware)
Initializes the system.
int map_start (map_hardware_t *hardware, map_application_t *app, map_app_layout_t *layout)
Start an application.
int map_stop (map_hardware_t *hardware, map_application_t *app, map_app_layout_t *layout)
Stop an application.
void map_dump (map_hardware_t *hardware, map_application_t *app, map_app_layout_t *layout)
Prints the OS's interpretation of an application (with layout).
Detailed Description
API for mapper output and OS input for starting and stopping complete applications.
Concepts:
Tasks are elements with behavior, such as a process, an ADC, or a FIFO. Tasks are connected to eachother via ports. A port is the bridge between an abstract channel number -- as used by the task -- and a physical link, such as a route through the NoC, memory map, etc. The concept of ports is added to offer hooks for the OS to setup the application.
Every task and port has one or more implementations. The binding must be done before the task graph is offered to the OS. Calls from the mapper/application/usecase loader is at the level of map_start(map_application_t*,map_app_layout_t*), where map_application_t contains the unmapped task graph and map_layout_t the binding/mapping information supplies.
The concept of usecases is only important for the developer and at application level. The OS will only setup and destroy applications; guarantees regarding usecases, valid usecase transitions, etc. must be implemented in the user application.
The task graph can be statically defined as shown at the bottom of this file, or can be generated by a run-time mapper. Executing the task graph will be done by two calls:
map_start(map_application_t*,map_app_layout_t*); map_stop(map_application_t*,map_app_layout_t*);
Both functions must return whether the execution is successful or not. However, all calls should be successful, because the mapper has determined the feasibility.
Definition in file mapping.h.
Typedef Documentation
typedef struct map_core_t map_core_t
A description of a core.
typedef struct map_port_t map_port_t
A port: the connection between one task and another.
This port builds up a directed (task) graph.
typedef struct map_task_t map_task_t
A task: a node with smart behavior.
Tasks are connected to eachother via ports.
Definition at line 149 of file mapping.h.
Enumeration Type Documentation
enum map_core_type_t
Enumerator:
CORE_MICROBLAZE
A MicroBlaze core that is capable of running Helix.
CORE_COMM_MEM
A communication dedicated memory.
CORE_SHARED_HEAP
A system wide shared heap.
CORE_DEDICATED
A dedicated hardware resource that does not need initialization.
Definition at line 45 of file mapping.h.
enum map_implementation_type_t
Enumerator:
IMPL_MEMORY
Memory mapped I/O via single address.
IMPL_ROUTE
Explicit route over the NoC.
IMPL_PROCESS
A process description.
IMPL_FIFO
A simple FIFO with one consumer and one producer.
IMPL_MAILBOX
A single-write, multiple-read mailbox.
IMPL_DEDICATED
A dedicated resource that can be used without initialization.
Definition at line 121 of file mapping.h.
enum map_port_role_t
Enumerator:
ROLE_UNUSED
ROLE_PRODUCER
ROLE_CONSUMER
Definition at line 151 of file mapping.h.
Function Documentation
void map_dump (map_hardware_t * hardware, map_application_t * app, map_app_layout_t * layout)
Prints the OS's interpretation of an application (with layout).
Parameters:
hardware the hardware information as presented to and annotated by map_init()
app the application to start (mapper's input)
layout all information regarding the mapping of this application (mapper's output, annotated by map_start())
Definition at line 359 of file mapping.cc.
References map_impl_layout_t::binding, map_port_t::implementation, map_task_t::implementation, map_implementation_t::memory, pid, map_port_t::port, map_task_t::port, map_task_layout_t::port_layout, map_port_t::role, map_application_t::task, map_app_layout_t::task, map_task_layout_t::task_layout, and map_implementation_t::type.
int map_init (map_hardware_t * hardware)
Initializes the system.
Before map_start() can be used, all cores should be initialized. This function will take care of that. The hardware parameter will be annotated by this function. The data that is added has no meaning to others than the OS. It should not be modified between map_* calls.
Parameters:
hardware the structure of the hardware
Returns:
0 on success, otherwise an appropriate errno
Definition at line 12 of file mapping.cc.
References map_hardware_t::core, and DEBUG.
int map_start (map_hardware_t * hardware, map_application_t * app, map_app_layout_t * layout)
Start an application.
The mapper should decide whether it is worth trying to start the application. The OS can always reject the request, when there are not enough resources. When the mapper does a good job, this call will always succeed.
All members of the union of map_impl_layout_t, which are included in the layout parameter, can be initialized with NULL. They will be overwritten by a newly malloc'ed pointer, which points to the heap of the calling process. These pointers must be preserved between the map_start() and map_stop() call.
When an error occurs, all partly initialized objects will be destroyed, such that the state of the system has not been changed.
Make sure that map_init() is called before calling map_start(), otherwise the behavior is not defined.
Tasks will be started in order they appear in the app->task array. Because channels need to be connected to tasks, the tasks must be initialized first, before the channel can be connected to it. Opening channels in tasks will block until the channels are allocated and assigned.
Parameters:
hardware the hardware information as presented to and annotated by map_init()
app the application to start (mapper's input)
layout all information regarding the mapping of this application (mapper's output)
Returns:
0 on success, ENOTSUP when an unsupported implementation is used, otherwise another appropriate errno
Definition at line 232 of file mapping.cc.
References map_impl_layout_t::binding, DEBUG, IMPL_DEDICATED, IMPL_FIFO, IMPL_MAILBOX, IMPL_MEMORY, IMPL_PROCESS, map_start_fifo(), map_start_mail(), map_start_task(), map_stop(), map_impl_layout_t::mapping, map_app_layout_t::task, map_task_layout_t::task_layout, and map_implementation_t::type.
int map_stop (map_hardware_t * hardware, map_application_t * app, map_app_layout_t * layout)
Stop an application.
All tasks will be forced to stop. In OS terminology, this means that processes will be killed and malloc'ed memory will be free'ed. The caller is responsible for a graceful shutdown, when appropriate.
It is unlikely that this call will fail, but when it does, the system will be left in an unknown state; the application is only partly torn down probably.
Tasks will be stopped in the order they appear in the app->task array.
Parameters:
hardware the hardware information as presented to and annotated by map_init()
app the application to start (mapper's input)
layout all information regarding the mapping of this application (mapper's output, annotated by map_start())
Returns:
0 on success, otherwise an errno
Definition at line 333 of file mapping.cc.
References map_impl_layout_t::binding, DEBUG, IMPL_DEDICATED, IMPL_FIFO, IMPL_MAILBOX, IMPL_MEMORY, IMPL_PROCESS, map_stop_fifo(), map_stop_task(), map_app_layout_t::task, map_task_layout_t::task_layout, and map_implementation_t::type.
Referenced by map_start().