Starburst: daemons/mapping.cc File Reference
daemons/mapping.cc File Reference
#include <sys/api.h>
#include <mapping.h>
#include <errno.h>
#include <stdio.h>
Defines
#define DEBUG(str, a...) printf("TG %d: " str "\n",GetProcID(),##a)
Functions
int map_init (map_hardware_t *hardware)
Initializes the system.
int map_start_task (map_task_layout_t *t)
int map_get_connection_info (map_task_layout_t *t, map_application_t *app, map_app_layout_t *layout, int portid, int *coreid, int *chanid, map_task_layout_t **partner, int *partner_portid)
int map_start_fifo (map_task_layout_t *f, map_application_t *app, map_app_layout_t *layout)
int map_start_mail (map_task_layout_t *m, map_application_t *app, map_app_layout_t *layout)
int map_start (map_hardware_t *hardware, map_application_t *app, map_app_layout_t *layout)
Start an application.
int map_stop_task (map_task_layout_t *t)
int map_stop_fifo (map_task_layout_t *f, map_application_t *app)
int map_stop_mail (map_task_layout_t *m, map_application_t *app)
int map_stop (map_hardware_t *hardware, map_application_t *app, map_app_layout_t *layout)
Stop an application.
void map_dump (map_hardware_t *hardware, map_application_t *app, map_app_layout_t *layout)
Prints the OS's interpretation of an application (with layout).
Define Documentation
#define DEBUG (str, a...) printf("TG %d: " str "\n",GetProcID(),##a)
Definition at line 7 of file mapping.cc.
Referenced by map_init(), map_start(), map_start_fifo(), map_start_mail(), and map_stop().
Function Documentation
void map_dump (map_hardware_t * hardware, map_application_t * app, map_app_layout_t * layout)
Prints the OS's interpretation of an application (with layout).
Parameters:
hardware the hardware information as presented to and annotated by map_init()
app the application to start (mapper's input)
layout all information regarding the mapping of this application (mapper's output, annotated by map_start())
Definition at line 359 of file mapping.cc.
References map_impl_layout_t::binding, map_port_t::implementation, map_task_t::implementation, map_implementation_t::memory, pid, map_port_t::port, map_task_t::port, map_task_layout_t::port_layout, map_port_t::role, map_application_t::task, map_app_layout_t::task, map_task_layout_t::task_layout, and map_implementation_t::type.
int map_get_connection_info (map_task_layout_t * t, map_application_t * app, map_app_layout_t * layout, int portid, int * coreid, int * chanid, map_task_layout_t ** partner, int * partner_portid)
Definition at line 85 of file mapping.cc.
References map_core_t::coreid, map_core_t::data, map_impl_layout_t::mapping, map_port_t::port, map_task_t::port, map_task_layout_t::port_layout, map_port_t::task, map_application_t::task, map_task_layout_t::task, map_app_layout_t::task, and map_task_layout_t::task_layout.
Referenced by map_start_fifo(), and map_start_mail().
int map_init (map_hardware_t * hardware)
Initializes the system.
Before map_start() can be used, all cores should be initialized. This function will take care of that. The hardware parameter will be annotated by this function. The data that is added has no meaning to others than the OS. It should not be modified between map_* calls.
Parameters:
hardware the structure of the hardware
Returns:
0 on success, otherwise an appropriate errno
Definition at line 12 of file mapping.cc.
References map_hardware_t::core, and DEBUG.
int map_start (map_hardware_t * hardware, map_application_t * app, map_app_layout_t * layout)
Start an application.
The mapper should decide whether it is worth trying to start the application. The OS can always reject the request, when there are not enough resources. When the mapper does a good job, this call will always succeed.
All members of the union of map_impl_layout_t, which are included in the layout parameter, can be initialized with NULL. They will be overwritten by a newly malloc'ed pointer, which points to the heap of the calling process. These pointers must be preserved between the map_start() and map_stop() call.
When an error occurs, all partly initialized objects will be destroyed, such that the state of the system has not been changed.
Make sure that map_init() is called before calling map_start(), otherwise the behavior is not defined.
Tasks will be started in order they appear in the app->task array. Because channels need to be connected to tasks, the tasks must be initialized first, before the channel can be connected to it. Opening channels in tasks will block until the channels are allocated and assigned.
Parameters:
hardware the hardware information as presented to and annotated by map_init()
app the application to start (mapper's input)
layout all information regarding the mapping of this application (mapper's output)
Returns:
0 on success, ENOTSUP when an unsupported implementation is used, otherwise another appropriate errno
Definition at line 232 of file mapping.cc.
References map_impl_layout_t::binding, DEBUG, IMPL_DEDICATED, IMPL_FIFO, IMPL_MAILBOX, IMPL_MEMORY, IMPL_PROCESS, map_start_fifo(), map_start_mail(), map_start_task(), map_stop(), map_impl_layout_t::mapping, map_app_layout_t::task, map_task_layout_t::task_layout, and map_implementation_t::type.
int map_start_fifo (map_task_layout_t * f, map_application_t * app, map_app_layout_t * layout)
Definition at line 108 of file mapping.cc.
References addr_local(), map_impl_layout_t::address, AllocFifoEndPoint(), AllocSharedFifoEndPoint, AssignChannel(), map_impl_layout_t::binding, CORE_COMM_MEM, CORE_SHARED_HEAP, DEBUG, DestroyFifoEndPoint(), map_impl_fifo_t::element_size, map_implementation_t::fifo, FIFO_ENDPOINT_BOTH, FIFO_ENDPOINT_READ, FIFO_ENDPOINT_WRITE, FIFO_LOCAL, FIFO_SHARED, map_impl_fifo_t::fifo_size, FIFO_SPLIT, map_impl_layout_t::flags, InitFifo(), lDestroyFifoEndPoint, map_get_connection_info(), map_impl_layout_t::mapping, map_impl_layout_t::pid, map_task_layout_t::port_layout, map_task_layout_t::task_layout, and map_core_t::type.
Referenced by map_start().
int map_start_mail (map_task_layout_t * m, map_application_t * app, map_app_layout_t * layout)
Definition at line 187 of file mapping.cc.
References addr_global(), map_impl_layout_t::address, AllocMail(), AllocSimpleMail(), AssignChannel(), map_impl_layout_t::binding, CORE_COMM_MEM, map_core_t::coreid, DEBUG, DestroyMail(), InitMail, map_implementation_t::mailbox, map_core_t::manager, map_get_connection_info(), map_impl_layout_t::mapping, map_impl_layout_t::pid, map_impl_mailbox_t::size, map_task_layout_t::task_layout, and map_core_t::type.
Referenced by map_start().
int map_start_task (map_task_layout_t * t)
Definition at line 46 of file mapping.cc.
References AllocChannels(), map_impl_process_t::arg, map_impl_layout_t::binding, CORE_DEDICATED, CORE_MICROBLAZE, map_core_t::coreid, CreateProcess(), DestroyProcess(), map_impl_process_t::main, map_impl_layout_t::mapping, map_impl_layout_t::pid, pid, map_task_layout_t::port_layout, map_implementation_t::process, map_impl_process_t::stack, StartProcess(), map_task_layout_t::task_layout, map_impl_process_t::timeslice, and map_core_t::type.
Referenced by map_start().
int map_stop (map_hardware_t * hardware, map_application_t * app, map_app_layout_t * layout)
Stop an application.
All tasks will be forced to stop. In OS terminology, this means that processes will be killed and malloc'ed memory will be free'ed. The caller is responsible for a graceful shutdown, when appropriate.
It is unlikely that this call will fail, but when it does, the system will be left in an unknown state; the application is only partly torn down probably.
Tasks will be stopped in the order they appear in the app->task array.
Parameters:
hardware the hardware information as presented to and annotated by map_init()
app the application to start (mapper's input)
layout all information regarding the mapping of this application (mapper's output, annotated by map_start())
Returns:
0 on success, otherwise an errno
Definition at line 333 of file mapping.cc.
References map_impl_layout_t::binding, DEBUG, IMPL_DEDICATED, IMPL_FIFO, IMPL_MAILBOX, IMPL_MEMORY, IMPL_PROCESS, map_stop_fifo(), map_stop_task(), map_app_layout_t::task, map_task_layout_t::task_layout, and map_implementation_t::type.
Referenced by map_start().
int map_stop_fifo (map_task_layout_t * f, map_application_t * app)
Definition at line 287 of file mapping.cc.
References map_impl_layout_t::address, CORE_COMM_MEM, CORE_SHARED_HEAP, map_core_t::coreid, DestroyFifoEndPoint(), DestroySharedFifoEndPoint, map_impl_layout_t::flags, map_core_t::manager, map_impl_layout_t::mapping, map_task_layout_t::port_layout, map_task_layout_t::task_layout, and map_core_t::type.
Referenced by map_stop().
int map_stop_mail (map_task_layout_t * m, map_application_t * app)
Definition at line 315 of file mapping.cc.
References map_impl_layout_t::address, CORE_COMM_MEM, map_core_t::coreid, DestroyMail(), map_impl_layout_t::mapping, map_task_layout_t::port_layout, map_task_layout_t::task_layout, and map_core_t::type.
int map_stop_task (map_task_layout_t * t)
Definition at line 270 of file mapping.cc.
References CORE_DEDICATED, CORE_MICROBLAZE, map_core_t::coreid, DestroyProcess(), map_impl_layout_t::mapping, map_impl_layout_t::pid, map_task_layout_t::task_layout, and map_core_t::type.
Referenced by map_stop().