Starburst: ipc/mc.cc File Reference
ipc/mc.cc File Reference
#include <mc.h>
#include <sys/device.h>
#include <sys/kernel.h>
#include <unistd.h>
#include <stdlib.h>
#include <sys/api.h>
Data Structures
struct mc_check_t
Defines
#define mc_printf(a...) printf(a)
Functions
static void mc_error_handler (void *obj, size_t objsize, int op, int err) __attribute__((noreturn))
void mc_set_error (void(handler)(void *, size_t, int, int))
Sets handler which is called when one of the mc_* functions fail.
void mc_error (void *obj, size_t objsize, int op, int err)
Entry function to call on consistency error.
static int mc_check_flush (void)
Define Documentation
#define mc_printf (a...) printf(a)
Definition at line 13 of file mc.cc.
Referenced by mc_error_handler().
Function Documentation
static int mc_check_flush (void) [static]
Definition at line 139 of file mc.cc.
References IS_TYPE_SIMPLE, and r.
void mc_error (void * obj, size_t objsize, int op, int err)
Entry function to call on consistency error.
Wrapper for default handler or handler set by mc_set_error().
See also:
mc_set_error()
Definition at line 27 of file mc.cc.
References mc_error_handler(), proc_local_t::mc_error_handler, and proc_local.
static void mc_error_handler (void * obj, size_t objsize, int op, int err) [static]
Definition at line 17 of file mc.cc.
References abort(), getpid(), GetProcID(), and mc_printf.
Referenced by mc_error().
void mc_set_error (void(handler)(void *, size_t, int, int))
Sets handler which is called when one of the mc_* functions fail.
The handler function will get the arguments: failing obj, objsize, failing MC_OP_*, errno
Definition at line 23 of file mc.cc.
References proc_local_t::mc_error_handler, and proc_local.