Starburst: posix/mutex.cc File Reference
posix/mutex.cc File Reference
POSIX mutex implementation, with software cache coherency.
#include <pthread.h>
#include <sys/syscall.h>
#include <sys/helix_config.h>
#include <sys/api.h>
#include <mc.h>
Defines
#define flushw(w)
#define flush(p, s)
#define invalw(w)
#define inval(p, s)
#define write_word(var, val) do{barrier();var=val;barrier();}while(0)
#define pthread_stats_elem_register(...)
#define pthread_stats_elem_unregister(...)
#define pthread_stats_global_init(...) 0
#define pthread_stats_global_cleanup(...) 0
#define pthread_stats_thread_init(...) 0
#define MUTEX2LCK(m) ((void*)((m)->attr.protectee?(m)->attr.protectee:(m)))
Functions
int pthread_mutexattr_protect (pthread_mutexattr_t *attr, void *protectee, size_t sprotectee)
Attaches a shared object to the mutex, implying mc_entry_x() on lock and mc_exit_x() on unlock.
int pthread_mutex_protect (pthread_mutex_t *mutex, void *protectee, size_t sprotectee)
int pthread_mutex_init (pthread_mutex_t *mutex, const pthread_mutexattr_t *attr)
int pthread_mutex_destroy (pthread_mutex_t *mutex)
int pthread_mutex_lock (pthread_mutex_t *mutex)
int pthread_mutex_unlock (pthread_mutex_t *mutex)
int pthread_mutexattr_init (pthread_mutexattr_t *attr)
int pthread_mutexattr_destroy (pthread_mutexattr_t *attr)
int pthread_mutexattr_gettype (const pthread_mutexattr_t *attr, int *type)
int pthread_mutexattr_settype (pthread_mutexattr_t *attr, int type)
int pthread_mutex_global_init ()
int pthread_mutex_global_cleanup ()
int pthread_mutex_thread_init ()
int pthread_mutex_thread_cleanup ()
Detailed Description
POSIX mutex implementation, with software cache coherency.
Definition in file mutex.cc.
Define Documentation
#define flush (p, s)
Definition at line 20 of file mutex.cc.
#define flushw (w)
Definition at line 19 of file mutex.cc.
#define inval (p, s)
Definition at line 22 of file mutex.cc.
#define invalw (w)
Definition at line 21 of file mutex.cc.
#define MUTEX2LCK (m) ((void*)((m)->attr.protectee?(m)->attr.protectee:(m)))
Definition at line 298 of file mutex.cc.
Referenced by pthread_mutex_destroy(), pthread_mutex_lock(), pthread_mutex_protect(), and pthread_mutex_unlock().
#define pthread_stats_elem_register (...)
Definition at line 29 of file mutex.cc.
#define pthread_stats_elem_unregister (...)
Definition at line 30 of file mutex.cc.
#define pthread_stats_global_cleanup (...) 0
Definition at line 32 of file mutex.cc.
#define pthread_stats_global_init (...) 0
Definition at line 31 of file mutex.cc.
#define pthread_stats_thread_init (...) 0
Definition at line 33 of file mutex.cc.
#define write_word (var, val) do{barrier();var=val;barrier();}while(0)
Definition at line 23 of file mutex.cc.
Referenced by pthread_mutex_lock().
Function Documentation
int pthread_mutex_destroy (pthread_mutex_t * mutex)
Definition at line 370 of file mutex.cc.
References lck_destroy(), mc_entry_ro, mc_exit_ro, MUTEX2LCK, and pthread_stats_elem_unregister.
Referenced by pipe_close(), and pthread_key_global_cleanup().
int pthread_mutex_global_cleanup (void)
Definition at line 478 of file mutex.cc.
References pthread_stats_global_cleanup.
Referenced by pthread_global_cleanup().
int pthread_mutex_global_init (void)
Definition at line 474 of file mutex.cc.
References pthread_stats_global_init.
Referenced by pthread_global_init().
int pthread_mutex_init (pthread_mutex_t * mutex, const pthread_mutexattr_t * attr)
Definition at line 347 of file mutex.cc.
References ESUCCESS, mc_entry_wou, mc_exit_wou, pthread_mutexattr_init(), and pthread_stats_elem_register.
Referenced by malloc_init(), pipe(), and pthread_key_global_init().
int pthread_mutex_lock (pthread_mutex_t * mutex)
Definition at line 381 of file mutex.cc.
References lck_lock(), lck_lock_p(), LR_FREE, LR_LOCAL, LR_NEW, mc_entry_ro, mc_entry_rwu, mc_exit_ro, MUTEX2LCK, TIMESTAMP_GET, TIMESTAMP_SET, TRACE_PHASE_MUTEX, TracePhaseChange(), unlikely, and write_word.
Referenced by _pthread_cond_wait(), find_cpu(), pipe_close(), pipe_read(), pipe_vfcntl(), pipe_write(), pprintf(), pthread_mutex_protect(), scalloc(), sfree(), smalloc(), and srealloc().
int pthread_mutex_protect (pthread_mutex_t * mutex, void * protectee, size_t sprotectee)
Definition at line 313 of file mutex.cc.
References lck_destroy(), lck_lock(), mc_entry_rwu, mc_exit_rwu, MUTEX2LCK, pthread_mutex_lock(), and pthread_mutex_unlock().
int pthread_mutex_thread_cleanup (void)
Definition at line 486 of file mutex.cc.
Referenced by pthread_thread_cleanup().
int pthread_mutex_thread_init (void)
Definition at line 482 of file mutex.cc.
References pthread_stats_thread_init.
Referenced by pthread_thread_init().
int pthread_mutex_unlock (pthread_mutex_t * mutex)
Definition at line 423 of file mutex.cc.
References lck_unlock(), mc_exit_ro, mc_exit_rwu, MUTEX2LCK, and TIMESTAMP_SET.
Referenced by _pthread_cond_wait(), find_cpu(), pipe_close(), pipe_read(), pipe_vfcntl(), pipe_write(), pprintf(), pthread_mutex_protect(), scalloc(), sfree(), smalloc(), and srealloc().
int pthread_mutexattr_destroy (pthread_mutexattr_t * attr)
Definition at line 457 of file mutex.cc.
int pthread_mutexattr_gettype (const pthread_mutexattr_t * attr, int * type)
Definition at line 461 of file mutex.cc.
References PTHREAD_MUTEX_DEFAULT.
int pthread_mutexattr_init (pthread_mutexattr_t * attr)
Definition at line 449 of file mutex.cc.
References PTHREAD_MUTEXATTR_INITIALIZER.
Referenced by pipe(), and pthread_mutex_init().
int pthread_mutexattr_protect (pthread_mutexattr_t * attr, void * protectee, size_t sprotectee)
Attaches a shared object to the mutex, implying mc_entry_x() on lock and mc_exit_x() on unlock.
Connects a memory region to be protected by the mutex (memory consistency).
Definition at line 305 of file mutex.cc.
References pthread_mutexattr_t::protectee, and pthread_mutexattr_t::sprotectee.
Referenced by pipe(), and pthread_key_global_init().
int pthread_mutexattr_settype (pthread_mutexattr_t * attr, int type)
Definition at line 468 of file mutex.cc.
References PTHREAD_MUTEX_DEFAULT.