Starburst: io/newlibstubs.cc File Reference
io/newlibstubs.cc File Reference
Implementation of the newlib stubs and syscalls.
#include <sys/io.h>
#include <sys/helix_config.h>
#include <ramfile.h>
#include "iodebug.h"
#include <unistd.h>
#include <sys/api.h>
#include <time.h>
#include <pipe.h>
#include <stdarg.h>
#include <linfs.h>
#include <sys/stat.h>
#include <sys/resource.h>
#include <signal.h>
Functions
int * __errno ()
newlib stub: returns pointer to errno within the reentrancy struct of the current process.
ssize_t read (int fd, void *buf, size_t cnt)
newlib syscall: reads bytes from a file descriptor.
ssize_t write (int fd, const void *buf, size_t cnt)
newlib syscall: writes bytes to a file descriptor.
int open (const char *pathname, int flags,...)
newlib syscall: open a file descriptor
int creat (const char *pathname, mode_t mode)
newlib syscall: create a new file and return it's descriptor
int close (int fd)
newlib syscall: closes a file descriptor.
int dup (int oldfd)
int dup2 (int oldfd, int newfd)
int link (const char *oldpath, const char *newpath)
pid_t fork (void)
int mkfifo (const char *pathname, mode_t mode)
pid_t waitpid (pid_t pid, int *status, int options)
int fcntl (int fd, int cmd,...)
int fstat (int fd, struct stat *buf)
newlib syscall: gets file status.
off_t lseek (int fd, off_t pos, int whence)
newlib syscall: seeks through file descriptor.
int isatty (int fd)
newlib syscall: checks whether the given file descriptor is a terminal.
int chmod (const char *path, mode_t mode)
mode_t umask (mode_t mask)
int gettimeofday (struct timeval *tv, struct timezone *tz)
newlib syscall: returns the current time.
int clock_gettime (clockid_t clk_id, struct timespec *tp)
time_t time (time_t *t)
int usleep (useconds_t useconds)
Suspends execution of the process for some time.
unsigned int sleep (unsigned int seconds)
int timecmp (const struct timeval *t1, const struct timeval *t2)
Compares two timevals.
Detailed Description
Implementation of the newlib stubs and syscalls.
Definition in file newlibstubs.cc.
Function Documentation
int* __errno ()
newlib stub: returns pointer to errno within the reentrancy struct of the current process.
Definition at line 25 of file newlibstubs.cc.
int chmod (const char * path, mode_t mode)
Definition at line 243 of file newlibstubs.cc.
int clock_gettime (clockid_t clk_id, struct timespec * tp)
Definition at line 322 of file newlibstubs.cc.
References CLOCK_MONOTONIC, CLOCK_PROCESS_CPUTIME_ID, CLOCK_REALTIME, CLOCK_THREAD_CPUTIME_ID, getrusage(), gettimeofday(), rusage::ru_utime, and RUSAGE_THREAD.
Referenced by timer_gettime(), timer_settime(), and TimerDaemon().
int close (int fd)
newlib syscall: closes a file descriptor.
Definition at line 133 of file newlibstubs.cc.
References ESUCCESS, linfs_close(), MAX_LINFS_FD, MAX_RAMFILE_FD, and pipe_close().
Referenced by TraceDump().
int creat (const char * pathname, mode_t mode)
newlib syscall: create a new file and return it's descriptor
Definition at line 120 of file newlibstubs.cc.
References ESUCCESS, _fd2q_t::fd, and linfs_creat().
Referenced by TraceDump().
int dup (int oldfd)
Definition at line 151 of file newlibstubs.cc.
int dup2 (int oldfd, int newfd)
Definition at line 155 of file newlibstubs.cc.
int fcntl (int fd, int cmd, ...)
Definition at line 187 of file newlibstubs.cc.
References ASSERT, MAX_LINFS_FD, MAX_RAMFILE_FD, and pipe_vfcntl().
pid_t fork (void)
Definition at line 169 of file newlibstubs.cc.
References ASSERT.
int fstat (int fd, struct stat * buf)
newlib syscall: gets file status.
Just sets st_mode to S_IFCHR.
Definition at line 211 of file newlibstubs.cc.
int gettimeofday (struct timeval * tv, struct timezone * tz)
newlib syscall: returns the current time.
Only the time since the last reset is measured. Any tz parameter will be zet to 0.
Returns:
always 0
See also:
get_clock() for the limitations of the clock
Definition at line 266 of file newlibstubs.cc.
References FlushDCacheRange(), get_clock(), and timezone.
Referenced by _pthread_cond_wait(), clock_gettime(), DumpStatsNow(), kInitKernel(), kPanic(), ProfilerDaemon(), sw_continue(), sw_stop(), time(), times(), TraceAbsTime(), and usleep().
int isatty (int fd)
newlib syscall: checks whether the given file descriptor is a terminal.
Returns:
1 when fd is 0, 1 or 2, otherwise an error is returned.
Definition at line 232 of file newlibstubs.cc.
int link (const char * oldpath, const char * newpath)
Definition at line 164 of file newlibstubs.cc.
off_t lseek (int fd, off_t pos, int whence)
newlib syscall: seeks through file descriptor.
Does nothing.
Definition at line 220 of file newlibstubs.cc.
References linfs_lseek().
int mkfifo (const char * pathname, mode_t mode)
Definition at line 175 of file newlibstubs.cc.
References ASSERT.
int open (const char * pathname, int flags, ...)
newlib syscall: open a file descriptor
Definition at line 100 of file newlibstubs.cc.
References ESUCCESS, _fd2q_t::fd, and linfs_open().
Referenced by ForceShutdown().
ssize_t read (int fd, void * buf, size_t cnt)
newlib syscall: reads bytes from a file descriptor.
Only fd 0 (stdin) is supported, which reads from the serial port. All other fds will return in an error.
See also:
inbyte()
Definition at line 32 of file newlibstubs.cc.
References inbyte(), and MAX_RAMFILE_FD.
Referenced by spi_selftest().
unsigned int sleep (unsigned int seconds)
Definition at line 435 of file newlibstubs.cc.
References usleep().
time_t time (time_t * t)
Definition at line 355 of file newlibstubs.cc.
References gettimeofday().
int timecmp (const struct timeval * t1, const struct timeval * t2)
Compares two timevals.
Returns:
1 when t1>t2, 0 when t1==t2, -1 otherwise
Definition at line 448 of file newlibstubs.cc.
Referenced by _pthread_cond_wait(), and usleep().
mode_t umask (mode_t mask)
Definition at line 247 of file newlibstubs.cc.
int usleep (useconds_t useconds)
Suspends execution of the process for some time.
The process Yield()s until the current time has passed the specified time.
Parameters:
useconds microseconds to sleep
Returns:
0 on success, otherwise -1 and errno is set
Definition at line 374 of file newlibstubs.cc.
References CLOCK_MONOTONIC, gettimeofday(), lGetProcessState(), likely, sigaddset(), SIGCONT, sigemptyset(), sigevent::sigev_notify, SIGEV_SIGNAL, sigevent::sigev_signo, Suspend(), timecmp(), timer_create(), timer_delete(), timer_settime(), and Yield().
Referenced by adc_init(), bitshark_cmd_write(), ForceShutdown(), ProfilerDaemon(), ShutdownDaemon(), sleep(), spi_transfer(), and TraceDump().
pid_t waitpid (pid_t pid, int * status, int options)
Definition at line 181 of file newlibstubs.cc.
References ASSERT.
ssize_t write (int fd, const void * buf, size_t cnt)
newlib syscall: writes bytes to a file descriptor.
Only fd 1 (stdout) and 2 (stderr) are supported, which both write to the serial port.
See also:
outbyte()
Definition at line 69 of file newlibstubs.cc.
References MAX_RAMFILE_FD, and outbyte().
Referenced by TraceDump().
Variable Documentation
struct { ... } ATTR_DATA_ALIGNED
Definition at line 252 of file newlibstubs.cc.
volatile int transition
Definition at line 253 of file newlibstubs.cc.