Starburst: com/OverlappingBuffer.cc File Reference
com/OverlappingBuffer.cc File Reference
#include <helios/OverlappingBuffer.h>
#include <helios/info_app.h>
#include <helios/SlidingBuffer.h>
#include <helios/cheap.h>
#include <sys/syscall.h>
#include <sys/api.h>
#include <mc.h>
Defines
#define MAX_WRAP_COUNT 3
#define NEXT_WRAP(c) (((c) + 1) % MAX_WRAP_COUNT)
#define WINDOW_PTR(a) ((a) & 0x3FFFFFFF)
#define WRAP_CTR(a) (((a) >> 30) & 0x03)
#define CREATE_PTR(p, c) (((c) << 30) | ((p) & 0x3FFFFFFF))
Functions
volatile InfoReadWindowOverlap * getReadWindow (volatile Info_CBOverlap *icbo, int idx)
volatile InfoWriteWindowOverlap * getWriteWindow (volatile Info_CBOverlap *icbo, int idx)
volatile Info_CB * createCBO (volatile Info_App *infoApp, uint32_t tokensize, uint32_t buffersize, uint32_t nReadWin, uint32_t nWriteWin, uint32_t id)
volatile Info_CBOverlap * findInfoFromAppCBO (volatile Info_App *appInfoPtr, int bufferid)
void initReadWindowCBO (volatile InfoReadWindowOverlap *rp, int id)
volatile Info_CBOverlap * openReadCB (int bufferid, int windowid, volatile InfoReadWindowOverlap **window_out)
void acquireDataPositionCBOL (volatile Info_CBOverlap *ptrCB, volatile InfoReadWindowOverlap *rp, uint32_t l)
void acquireDataCBOL (volatile Info_CBOverlap *ptrCB, volatile InfoReadWindowOverlap *rp, uint32_t l)
void readCBO (volatile Info_CBOverlap *ptrCB, volatile InfoReadWindowOverlap *rp, void *c, uint32_t l)
void releaseSpaceCBO (volatile Info_CBOverlap *ptrCB, volatile InfoReadWindowOverlap *rp)
void releaseSpaceBlockCBO (volatile Info_CBOverlap *ptrCB, volatile InfoReadWindowOverlap *rp, uint32_t n)
void initWriteWindowCBO (volatile InfoWriteWindowOverlap *wp, int id)
volatile Info_CBOverlap * openWriteCB (int bufferid, int windowid, volatile InfoWriteWindowOverlap **window_out)
void acquireSpaceCBO (volatile Info_CBOverlap *ptrCB, volatile InfoWriteWindowOverlap *wp)
void acquireSpaceBlockCBO (volatile Info_CBOverlap *ptrCB, volatile InfoWriteWindowOverlap *wp, uint32_t n)
void writeCBO (volatile Info_CBOverlap *ptrCB, volatile InfoWriteWindowOverlap *wp, const void *c, uint32_t l)
void releaseDataCBOL (volatile Info_CBOverlap *ptrCB, volatile InfoWriteWindowOverlap *wp, uint32_t l)
Variables
volatile Info_App * appInfoPtrList
Define Documentation
#define CREATE_PTR (p, c) (((c) << 30) | ((p) & 0x3FFFFFFF))
Definition at line 15 of file OverlappingBuffer.cc.
Referenced by acquireSpaceCBO(), createCBO(), releaseSpaceBlockCBO(), and releaseSpaceCBO().
#define MAX_WRAP_COUNT 3
Definition at line 11 of file OverlappingBuffer.cc.
Referenced by createCBO().
#define NEXT_WRAP (c) (((c) + 1) % MAX_WRAP_COUNT)
Definition at line 12 of file OverlappingBuffer.cc.
Referenced by acquireDataCBOL(), acquireDataPositionCBOL(), acquireSpaceCBO(), releaseSpaceBlockCBO(), releaseSpaceCBO(), and writeCBO().
#define WINDOW_PTR (a) ((a) & 0x3FFFFFFF)
Definition at line 13 of file OverlappingBuffer.cc.
Referenced by acquireDataCBOL(), acquireDataPositionCBOL(), acquireSpaceCBO(), releaseSpaceBlockCBO(), releaseSpaceCBO(), and writeCBO().
#define WRAP_CTR (a) (((a) >> 30) & 0x03)
Definition at line 14 of file OverlappingBuffer.cc.
Referenced by acquireDataCBOL(), acquireDataPositionCBOL(), acquireSpaceCBO(), releaseSpaceBlockCBO(), releaseSpaceCBO(), and writeCBO().
Function Documentation
void acquireDataCBOL (volatile Info_CBOverlap * ptrCB, volatile InfoReadWindowOverlap * rp, uint32_t l)
Definition at line 238 of file OverlappingBuffer.cc.
References Info_CBOverlap::buffer_size, getWriteWindow(), NEXT_WRAP, Info_CBOverlap::nWriteWin, WINDOW_PTR, WRAP_CTR, and Yield().
Referenced by readCBO().
void acquireDataPositionCBOL (volatile Info_CBOverlap * ptrCB, volatile InfoReadWindowOverlap * rp, uint32_t l)
Definition at line 207 of file OverlappingBuffer.cc.
References Info_CBOverlap::buffer_size, getWriteWindow(), NEXT_WRAP, Info_CBOverlap::nWriteWin, WINDOW_PTR, WRAP_CTR, and Yield().
void acquireSpaceBlockCBO (volatile Info_CBOverlap * ptrCB, volatile InfoWriteWindowOverlap * wp, uint32_t n)
Definition at line 381 of file OverlappingBuffer.cc.
References acquireSpaceCBO().
void acquireSpaceCBO (volatile Info_CBOverlap * ptrCB, volatile InfoWriteWindowOverlap * wp)
Definition at line 343 of file OverlappingBuffer.cc.
References Info_CBOverlap::buffer_size, CREATE_PTR, getReadWindow(), getWriteWindow(), NEXT_WRAP, Info_CBOverlap::nReadWin, Info_CBOverlap::nWriteWin, WINDOW_PTR, WRAP_CTR, and Yield().
Referenced by acquireSpaceBlockCBO().
volatile Info_CB* createCBO (volatile Info_App * infoApp, uint32_t tokensize, uint32_t buffersize, uint32_t nReadWin, uint32_t nWriteWin, uint32_t id)
Definition at line 27 of file OverlappingBuffer.cc.
References Info_CBOverlap::buffer_size, CB_OVERLAPPING_WINDOWS, Info_App_s::cbList, CREATE_PTR, Info_CBOverlap::data, Info_CB::data, getReadWindow(), getWriteWindow(), Info_FIFO::id, Info_CB::id, MAX_WRAP_COUNT, Info_CB::next, Info_CBOverlap::nReadWin, nReadWin, Info_CBOverlap::nWriteWin, nWriteWin, Info_CBOverlap::readWindowInfo, smalloc(), Info_CBOverlap::token_size, Info_CB::type, Info_CBOverlap::writeWindowInfo, and WW_SIZE.
volatile Info_CBOverlap* findInfoFromAppCBO (volatile Info_App * appInfoPtr, int bufferid)
Definition at line 124 of file OverlappingBuffer.cc.
References Info_App_s::cbList, Info_CB::data, Info_CB::id, Info_App_s::nBuffers, and Info_CB::next.
volatile InfoReadWindowOverlap* getReadWindow (volatile Info_CBOverlap * icbo, int idx) [inline]
Definition at line 19 of file OverlappingBuffer.cc.
References Info_CBOverlap::readWindowInfo.
Referenced by acquireSpaceCBO(), createCBO(), openReadCB(), and writeCBO().
volatile InfoWriteWindowOverlap* getWriteWindow (volatile Info_CBOverlap * icbo, int idx) [inline]
Definition at line 23 of file OverlappingBuffer.cc.
References Info_CBOverlap::buffer_size, Info_CBOverlap::writeWindowInfo, and WW_SIZE.
Referenced by acquireDataCBOL(), acquireDataPositionCBOL(), acquireSpaceCBO(), createCBO(), and openWriteCB().
void initReadWindowCBO (volatile InfoReadWindowOverlap * rp, int id)
Definition at line 160 of file OverlappingBuffer.cc.
References Info_FIFO::id.
void initWriteWindowCBO (volatile InfoWriteWindowOverlap * wp, int id)
Definition at line 296 of file OverlappingBuffer.cc.
References Info_FIFO::id.
volatile Info_CBOverlap* openReadCB (int bufferid, int windowid, volatile InfoReadWindowOverlap ** window_out)
Definition at line 164 of file OverlappingBuffer.cc.
References CB_OVERLAPPING_WINDOWS, Info_App_s::cbList, Info_CB::data, findApp(), getReadWindow(), Info_CB::id, Info_App_s::nBuffers, Info_CB::next, nReadWin, and Info_CB::type.
volatile Info_CBOverlap* openWriteCB (int bufferid, int windowid, volatile InfoWriteWindowOverlap ** window_out)
Definition at line 300 of file OverlappingBuffer.cc.
References CB_OVERLAPPING_WINDOWS, Info_App_s::cbList, Info_CB::data, findApp(), getWriteWindow(), Info_CB::id, Info_App_s::nBuffers, Info_CB::next, nWriteWin, and Info_CB::type.
void readCBO (volatile Info_CBOverlap * ptrCB, volatile InfoReadWindowOverlap * rp, void * c, uint32_t l)
Definition at line 271 of file OverlappingBuffer.cc.
References acquireDataCBOL(), Info_CBOverlap::buffer_size, Info_CBOverlap::data, and Info_CBOverlap::token_size.
void releaseDataCBOL (volatile Info_CBOverlap * ptrCB, volatile InfoWriteWindowOverlap * wp, uint32_t l)
Definition at line 418 of file OverlappingBuffer.cc.
References Info_CBOverlap::buffer_size.
Referenced by writeCBO().
void releaseSpaceBlockCBO (volatile Info_CBOverlap * ptrCB, volatile InfoReadWindowOverlap * rp, uint32_t n)
Definition at line 287 of file OverlappingBuffer.cc.
References Info_CBOverlap::buffer_size, CREATE_PTR, NEXT_WRAP, WINDOW_PTR, and WRAP_CTR.
void releaseSpaceCBO (volatile Info_CBOverlap * ptrCB, volatile InfoReadWindowOverlap * rp)
Definition at line 281 of file OverlappingBuffer.cc.
References Info_CBOverlap::buffer_size, CREATE_PTR, NEXT_WRAP, WINDOW_PTR, and WRAP_CTR.
void writeCBO (volatile Info_CBOverlap * ptrCB, volatile InfoWriteWindowOverlap * wp, const void * c, uint32_t l)
Definition at line 389 of file OverlappingBuffer.cc.
References Info_CBOverlap::buffer_size, Info_CBOverlap::data, getReadWindow(), NEXT_WRAP, Info_CBOverlap::nReadWin, releaseDataCBOL(), Info_CBOverlap::token_size, WINDOW_PTR, and WRAP_CTR.
Variable Documentation
volatile Info_App* appInfoPtrList