Starburst: include/pipe.h File Reference
include/pipe.h File Reference
#include <unistd.h>
#include <stdarg.h>
#include <ramfile.h>
Defines
#define FIFO_CAPACITY 16
#define PIPE_START_FDS (MAX_RAMFILE_FD+1)
Functions
ssize_t pipe_write (int fd, const void *buf, size_t cnt)
ssize_t pipe_read (int fd, void *buf, size_t cnt)
int pipe_close (int fd)
int pipe_vfcntl (int fd, int cmd, va_list argp)
Define Documentation
#define FIFO_CAPACITY 16
Definition at line 8 of file pipe.h.
#define PIPE_START_FDS (MAX_RAMFILE_FD+1)
Definition at line 9 of file pipe.h.
Function Documentation
int pipe_close (int fd)
Definition at line 212 of file pipe.cc.
References DEBUG, GET_PIPE, IS_READER, pipe_t::lock, pipe_t::nonempty, pipe_t::nonfull, pthread_cond_destroy(), pthread_mutex_destroy(), pthread_mutex_lock(), pthread_mutex_unlock(), and sfree().
Referenced by close().
ssize_t pipe_read (int fd, void * buf, size_t cnt)
Definition at line 99 of file pipe.cc.
References abort(), DEBUG, GET_PIPE, inc_ptr, IS_READER, pipe_t::lock, pipe_t::nonempty, pipe_t::nonfull, pthread_cond_signal(), pthread_cond_wait(), pthread_mutex_lock(), pthread_mutex_unlock(), r, readable, and real_ptr.
int pipe_vfcntl (int fd, int cmd, va_list argp)
Definition at line 237 of file pipe.cc.
References ASSERT, DEBUG, GET_PIPE, IS_READER, pipe_t::lock, pthread_mutex_lock(), and pthread_mutex_unlock().
Referenced by fcntl().
ssize_t pipe_write (int fd, const void * buf, size_t cnt)
Definition at line 155 of file pipe.cc.
References abort(), DEBUG, GET_PIPE, getpid(), inc_ptr, IS_WRITER, pipe_t::lock, pipe_t::nonempty, pipe_t::nonfull, pthread_cond_signal(), pthread_cond_wait(), pthread_mutex_lock(), pthread_mutex_unlock(), real_ptr, SendSignal(), SIGPIPE, and writable.