Starburst: ipc/pipe.cc File Reference
ipc/pipe.cc File Reference
Implementation of pipe() and friends.
#include <sys/api.h>
#include <fifo.h>
#include <pipe.h>
#include <errno.h>
#include <stdarg.h>
#include <fcntl.h>
#include <mc.h>
Data Structures
struct pipe_admin_t
struct pipe_t
Defines
#define DEBUG(str, a...)
#define IS_READER(fd) ((fd)&1)
#define IS_WRITER(fd) (!IS_READER(fd))
#define MAKE_READER_FD(p) ((int)(p)|1)
#define MAKE_WRITER_FD(p) ((int)(p))
#define GET_PIPE(fd) ((pipe_t*)((fd)&(~1)))
#define PIPE_CAPACITY 32
#define is_empty(rp, wp) ((rp)==(wp))
#define is_full(rp, wp) (!is_empty(rp,wp)&&((rp)%PIPE_CAPACITY==(wp)%PIPE_CAPACITY))
#define real_ptr(p) ((p)%PIPE_CAPACITY)
#define inc_ptr(p, cnt) (((p)+(cnt))%(PIPE_CAPACITY*2))
#define readable(rp, wp) (is_empty(rp,wp)?0:(real_ptr(wp)>real_ptr(rp)?real_ptr(wp):PIPE_CAPACITY)-real_ptr(rp))
#define writable(rp, wp) (is_full(rp,wp)?0:(real_ptr(rp)>real_ptr(wp)?real_ptr(rp):PIPE_CAPACITY)-real_ptr(wp))
Functions
int pipe (int pipefd[2])
ssize_t pipe_read (int fd, void *buf, size_t cnt)
ssize_t pipe_write (int fd, const void *buf, size_t cnt)
int pipe_close (int fd)
int pipe_vfcntl (int fd, int cmd, va_list argp)
Detailed Description
Implementation of pipe() and friends.
Do not use pipes with multiple readers or writers.
Definition in file pipe.cc.
Define Documentation
#define DEBUG (str, a...)
Definition at line 17 of file pipe.cc.
Referenced by pipe(), pipe_close(), pipe_read(), pipe_vfcntl(), and pipe_write().
#define GET_PIPE (fd) ((pipe_t*)((fd)&(~1)))
Definition at line 24 of file pipe.cc.
Referenced by pipe_close(), pipe_read(), pipe_vfcntl(), and pipe_write().
#define inc_ptr (p, cnt) (((p)+(cnt))%(PIPE_CAPACITY*2))
Definition at line 95 of file pipe.cc.
Referenced by pipe_read(), and pipe_write().
#define is_empty (rp, wp) ((rp)==(wp))
Definition at line 92 of file pipe.cc.
#define is_full (rp, wp) (!is_empty(rp,wp)&&((rp)%PIPE_CAPACITY==(wp)%PIPE_CAPACITY))
Definition at line 93 of file pipe.cc.
#define IS_READER (fd) ((fd)&1)
Definition at line 20 of file pipe.cc.
Referenced by pipe_close(), pipe_read(), and pipe_vfcntl().
#define IS_WRITER (fd) (!IS_READER(fd))
Definition at line 21 of file pipe.cc.
Referenced by pipe_write().
#define MAKE_READER_FD (p) ((int)(p)|1)
Definition at line 22 of file pipe.cc.
Referenced by pipe().
#define MAKE_WRITER_FD (p) ((int)(p))
Definition at line 23 of file pipe.cc.
Referenced by pipe().
#define PIPE_CAPACITY 32
Definition at line 26 of file pipe.cc.
#define readable (rp, wp) (is_empty(rp,wp)?0:(real_ptr(wp)>real_ptr(rp)?real_ptr(wp):PIPE_CAPACITY)-real_ptr(rp))
Definition at line 96 of file pipe.cc.
Referenced by pipe_read().
#define real_ptr (p) ((p)%PIPE_CAPACITY)
Definition at line 94 of file pipe.cc.
Referenced by pipe_read(), and pipe_write().
#define writable (rp, wp) (is_full(rp,wp)?0:(real_ptr(rp)>real_ptr(wp)?real_ptr(rp):PIPE_CAPACITY)-real_ptr(wp))
Definition at line 97 of file pipe.cc.
Referenced by pipe_write().
Function Documentation
int pipe (int pipefd[2])
Definition at line 49 of file pipe.cc.
References abort(), DEBUG, pipe_t::lock, MAKE_READER_FD, MAKE_WRITER_FD, mc_entry_wou, mc_exit_wou, pipe_t::nonempty, pipe_t::nonfull, pthread_cond_init(), pthread_mutex_init(), pthread_mutexattr_init(), pthread_mutexattr_protect(), and smalloc().
int pipe_close (int fd)
Definition at line 212 of file pipe.cc.
References DEBUG, GET_PIPE, IS_READER, pipe_t::lock, pipe_t::nonempty, pipe_t::nonfull, pthread_cond_destroy(), pthread_mutex_destroy(), pthread_mutex_lock(), pthread_mutex_unlock(), and sfree().
Referenced by close().
ssize_t pipe_read (int fd, void * buf, size_t cnt)
Definition at line 99 of file pipe.cc.
References abort(), DEBUG, GET_PIPE, inc_ptr, IS_READER, pipe_t::lock, pipe_t::nonempty, pipe_t::nonfull, pthread_cond_signal(), pthread_cond_wait(), pthread_mutex_lock(), pthread_mutex_unlock(), r, readable, and real_ptr.
int pipe_vfcntl (int fd, int cmd, va_list argp)
Definition at line 237 of file pipe.cc.
References ASSERT, DEBUG, GET_PIPE, IS_READER, pipe_t::lock, pthread_mutex_lock(), and pthread_mutex_unlock().
Referenced by fcntl().
ssize_t pipe_write (int fd, const void * buf, size_t cnt)
Definition at line 155 of file pipe.cc.
References abort(), DEBUG, GET_PIPE, getpid(), inc_ptr, IS_WRITER, pipe_t::lock, pipe_t::nonempty, pipe_t::nonfull, pthread_cond_signal(), pthread_cond_wait(), pthread_mutex_lock(), pthread_mutex_unlock(), real_ptr, SendSignal(), SIGPIPE, and writable.