Starburst: posix/signal.cc File Reference
posix/signal.cc File Reference
#include <sys/api.h>
#include <signal.h>
#include <errno.h>
Defines
#define SIGNAL_EXTERN_INLINE extern
Functions
int kill (pid_t pid, int sig)
int raise (int sig)
sighandler_t signal (int signum, sighandler_t handler)
int pause ()
int sigsuspend (const sigset_t *mask)
int sigaction (int signum, const struct sigaction *act, struct sigaction *oldact)
int siginterrupt (int sig, int flag)
int sigprocmask (int how, const sigset_t *set, sigset_t *oldset)
int sigemptyset (sigset_t *set)
int sigfillset (sigset_t *set)
int sigaddset (sigset_t *set, int signum)
int sigdelset (sigset_t *set, int signum)
int sigismember (const sigset_t *set, int signum)
int sigisemptyset (sigset_t *set)
int sigorset (sigset_t *dest, sigset_t *left, sigset_t *right)
int sigandset (sigset_t *dest, sigset_t *left, sigset_t *right)
Define Documentation
#define SIGNAL_EXTERN_INLINE extern
Definition at line 1 of file signal.cc.
Function Documentation
int kill (pid_t pid, int sig)
Definition at line 18 of file signal.cc.
References lSendSignal().
Referenced by DefaultTaskDaemon(), and raise().
int pause ()
Definition at line 48 of file signal.cc.
References sigemptyset(), and Suspend().
Referenced by DumpStatsDaemon(), and MallocDaemon().
int raise (int sig)
Definition at line 31 of file signal.cc.
References getpid(), and kill().
int sigaction (int signum, const struct sigaction * act, struct sigaction * oldact)
Todo:
oldact is not used
Definition at line 66 of file signal.cc.
References SetSignalHandler().
Referenced by MallocDaemon(), and timer_repeat().
int sigaddset (sigset_t * set, int signum)
Definition at line 99 of file signal.h.
Referenced by _pthread_cond_wait(), GetIssueSlot(), kClearSignal(), kSetSignalHandler(), lck_pass_p(), set_no_gracefull_exit(), sigblock(), usleep(), and WaitForResult().
int sigandset (sigset_t * dest, sigset_t * left, sigset_t * right)
Definition at line 104 of file signal.h.
Referenced by kMaskSignal().
int sigdelset (sigset_t * set, int signum)
Definition at line 100 of file signal.h.
Referenced by kSetSignalHandler(), and SignalDispatcher().
int sigemptyset (sigset_t * set)
Definition at line 97 of file signal.h.
Referenced by _pthread_cond_wait(), GetIssueSlot(), kCreateProcess(), lck_pass_p(), MallocDaemon(), pause(), set_no_gracefull_exit(), sigblock(), signal(), timer_repeat(), usleep(), and WaitForResult().
int sigfillset (sigset_t * set)
Definition at line 98 of file signal.h.
Referenced by kCreateProcess().
int siginterrupt (int sig, int flag)
Definition at line 72 of file signal.cc.
int sigisemptyset (sigset_t * set)
Definition at line 102 of file signal.h.
int sigismember (const sigset_t * set, int signum)
Definition at line 101 of file signal.h.
Referenced by kSendSignal(), and SignalDispatcher().
sighandler_t signal (int signum, sighandler_t handler)
Definition at line 35 of file signal.cc.
References sigaction::sa_flags, sigaction::sa_handler, sigaction::sa_mask, SetSignalHandler(), sigemptyset(), sigval::sival_int, and sigaction::sv.
int sigorset (sigset_t * dest, sigset_t * left, sigset_t * right)
Definition at line 103 of file signal.h.
Referenced by kMaskSignal().
int sigprocmask (int how, const sigset_t * set, sigset_t * oldset)
Definition at line 76 of file signal.cc.
References MaskSignal().
int sigsuspend (const sigset_t * mask)
Definition at line 55 of file signal.cc.
References Suspend().