Starburst: io/pprintf.cc File Reference
io/pprintf.cc File Reference
#include <par.h>
#include <stdio.h>
#include <pthread.h>
#include <stdarg.h>
#include <string.h>
Functions
int pprintf (const char *format,...)
Like printf(), but protects the output with a mutex to prevent garbage output by concurrent prints.
Variables
static pthread_mutex_t pprintf_lck = PTHREAD_MUTEX_INITIALIZER
Function Documentation
int pprintf (const char * format, ...)
Like printf(), but protects the output with a mutex to prevent garbage output by concurrent prints.
A newline will be appended when necessary.
Definition at line 13 of file pprintf.cc.
References getpid(), GetProcID(), pthread_mutex_lock(), and pthread_mutex_unlock().
Variable Documentation
pthread_mutex_t pprintf_lck = PTHREAD_MUTEX_INITIALIZER [static]
Definition at line 7 of file pprintf.cc.