Starburst: include/profiling.h File Reference
include/profiling.h File Reference
Application
Profiling support for the memory and MicroBlaze.
#include <stdlib.h>
#include <stdint.h>
#include <sys/time.h>
#include <autoret.h>
Data Structures
struct _prf_mem_t
struct _prf_mb_t
struct prf_mb_snapshot_t
struct stopwatch_t
Defines
#define PROFILE_MEM_BASE 0xe00a0000
#define PROFILE_MEM_MARKER 0xbeeb
#define PROFILE_MEM_REGIONS 8
#define PROFILE_MB_BASE 0x00220000
Typedefs
typedef struct _prf_mem_t prf_mem_t
typedef struct _prf_mb_t prf_mb_t
Functions
prf_mem_t const volatile * prf_mem_snapshot ()
Makes a snapshot of the counter of the memory profiling logic and reset the counters.
prf_mem_t const volatile * prf_mem_dump (prf_mem_t *prf=NULL)
Prints the memory profiling to the terminal.
prf_mb_t * prf_mb_snapshot ()
Makes a snapshot of the counter of the MicroBlaze trace profiling logic and reset the counters.
prf_mb_t * prf_mb_dump (prf_mb_t *prf=NULL)
Prints the MicroBlaze profiling to the terminal.
void prf_mb_dump_list (prf_mb_t *prf, int cnt=1)
Prints the MicroBlaze profiling to the terminal in a compact way.
void prf_mb_dump_list (prf_mb_snapshot_t *prf, int cnt=-1)
Prints the MicroBlaze profiling to the terminal in a compact way.
void * ProfilerDaemon (void *arg)
Polls the MicroBlaze profiling counters regularly and stores them for later inspection.
int SetupProfilerDaemon (pid_t &pid, prf_mb_snapshot_t **snapshots)
Starts the profiler daemon.
void PrintProfilerOutput (prf_mb_snapshot_t *snapshots, bool full=false)
Prints profiling information as gathered by the ProfilingDaemon()
void prf_snapshot (void)
Makes a snapshot of both the memory and MicroBlaze, with C-binding.
void prf_dump (void)
Makes a snapshot of both the memory and MicroBlaze and dumps the statistics, with C-binding.
auto_ret< int, 0 > sw_start (stopwatch_t &sw)
auto_ret< int, 0 > sw_continue (stopwatch_t &sw)
auto_ret< int, 0 > sw_stop (stopwatch_t &sw)
double sw_elapsed_sec (stopwatch_t &sw)
double sw_elapsed_cycles (stopwatch_t &sw)
Detailed Description
Profiling support for the memory and MicroBlaze.
The memory controller has several counters, which can be read and reset from every core. Only a MicroBlaze with 'trace_enabled' set in the system.xml has a unit to measure microarchitectural events (usually only core 0).
Definition in file profiling.h.
Define Documentation
#define PROFILE_MB_BASE 0x00220000
Definition at line 62 of file profiling.h.
Referenced by prf_mb_snapshot().
#define PROFILE_MEM_BASE 0xe00a0000
Definition at line 18 of file profiling.h.
Referenced by prf_mem_snapshot().
#define PROFILE_MEM_MARKER 0xbeeb
Definition at line 19 of file profiling.h.
Referenced by prf_mem_dump().
#define PROFILE_MEM_REGIONS 8
Definition at line 20 of file profiling.h.
Referenced by _prf_mem_t::operator+=(), and prf_mem_dump().
Typedef Documentation
typedef struct _prf_mb_t prf_mb_t
typedef struct _prf_mem_t prf_mem_t
Function Documentation
void prf_dump (void)
Makes a snapshot of both the memory and MicroBlaze and dumps the statistics, with C-binding.
Definition at line 373 of file profiling.cc.
References prf_mb_dump(), prf_mb_snapshot(), and prf_mem_dump().
prf_mb_t* prf_mb_dump (prf_mb_t * prf)
Prints the MicroBlaze profiling to the terminal.
Parameters:
prf the profile information to print, when NULL, prf_mb_snapshot() is called for that
Returns:
the data the output is based on
Definition at line 196 of file profiling.cc.
References _prf_mb_t::cycles, _prf_mb_t::dcache_rhit, _prf_mb_t::dcache_rreq, _prf_mb_t::delay_slots, GetClockFreq(), _prf_mb_t::icache_hit, _prf_mb_t::icache_req, _prf_mb_t::instr, _prf_mb_t::jumps, prf_busy_cycles(), prf_mb_dump_list(), PRF_MB_IS_VALID, PRF_MB_PRINTF, PRF_MB_PRINTF_FMT, PRF_MB_PRINTF_FMT_D, prf_mb_snapshot(), prf_other_cycles(), _prf_mb_t::read_fifo, _prf_mb_t::read_local, _prf_mb_t::read_noc, _prf_mb_t::stall_instr, _prf_mb_t::stall_read, _prf_mb_t::stall_read_noc, _prf_mb_t::stall_write, _prf_mb_t::stall_write_noc, _prf_mb_t::write_fifo, _prf_mb_t::write_local, and _prf_mb_t::write_noc.
Referenced by prf_dump(), and PrintProfilerOutput().
void prf_mb_dump_list (prf_mb_t * prf, int cnt)
Prints the MicroBlaze profiling to the terminal in a compact way.
Parameters:
prf an array with profile information to print, cannot be NULL
cnt the number of array elements prf points to
Definition at line 328 of file profiling.cc.
References prf_mb_dump_list_cycles(), prf_mb_dump_list_read(), and prf_mb_dump_list_write().
Referenced by prf_mb_dump(), and PrintProfilerOutput().
void prf_mb_dump_list (prf_mb_snapshot_t * prf, int cnt)
Prints the MicroBlaze profiling to the terminal in a compact way.
Prints snapshots until the time of the snapshot is either set to 0 or up to cnt.
Parameters:
prf an array with profile information to print, cannot be NULL
cnt the maximum number of array elements prf points to
Definition at line 347 of file profiling.cc.
References prf_mb_dump_list_cycles(), prf_mb_dump_list_read(), prf_mb_dump_list_write(), prf_mb_snapshot_t::snapshot, and prf_mb_snapshot_t::tv.
prf_mb_t* prf_mb_snapshot ()
Makes a snapshot of the counter of the MicroBlaze trace profiling logic and reset the counters.
Returns:
The counters just before the reset.
Definition at line 169 of file profiling.cc.
References io_write, PROFILE_MB_BASE, and WDC_FLUSH_SNAPSHOT.
Referenced by prf_dump(), prf_mb_dump(), prf_snapshot(), and ProfilerDaemon().
prf_mem_t const volatile* prf_mem_dump (prf_mem_t * prf)
Prints the memory profiling to the terminal.
Parameters:
prf the profile information to print, when NULL, prf_mem_snapshot() is called for that
Returns:
the data the output is based on
Definition at line 71 of file profiling.cc.
References _prf_mem_t::burst8_read, _prf_mem_t::burst8_write, _prf_mem_t::burstn_read, _prf_mem_t::burstn_write, const, _prf_mem_t::counter_width, _prf_mem_t::cycles, _prf_mem_t::idle, _prf_mem_t::marker, MEM_CLK_FREQ, MEM_REGION_END, MEM_REGION_START, _prf_mem_t::overflow(), PRF_MEM_PRINTF, PRF_MEM_PRINTF_FMT, PRF_MEM_PRINTF_FMT_D, prf_mem_snapshot(), PROFILE_MEM_MARKER, PROFILE_MEM_REGIONS, _prf_mem_t::stats_type, _prf_mem_t::word_read, and _prf_mem_t::word_write.
Referenced by prf_dump().
prf_mem_t const volatile* prf_mem_snapshot ()
Makes a snapshot of the counter of the memory profiling logic and reset the counters.
Returns:
The counters just before the reset.
Definition at line 31 of file profiling.cc.
References io_write, and PROFILE_MEM_BASE.
Referenced by prf_mem_dump(), and prf_snapshot().
void prf_snapshot (void)
Makes a snapshot of both the memory and MicroBlaze, with C-binding.
Definition at line 365 of file profiling.cc.
References prf_mb_snapshot(), and prf_mem_snapshot().
void* ProfilerDaemon (void * arg)
Polls the MicroBlaze profiling counters regularly and stores them for later inspection.
The daemon will copy the current counters and reset them, after it will Yield(). When this is all completed within one timeslice, the statistics are gathered after every context switch, so once every replenisment interval.
Channel 0 is expected to be a pointer to a malloced memory that is used to write the data to; it is used as an array of prf_mb_snapshot_t. Make sure that the memory is large enough. The snapshots in the array are valid up to the number of iterations specified when the process exists, otherwise up to the element that has a snapshot time set to 0.
Parameters:
arg the number of iterations to be made before the daemon exits
Returns:
0
Definition at line 29 of file ProfilerDaemon.cc.
References gettimeofday(), OpenChannel(), prf_mb_snapshot(), PROFILER_SAMPLE_TIME, prf_mb_snapshot_t::tv, usleep(), and Yield().
Referenced by SetupProfilerDaemon().
auto_ret<int,0> sw_continue (stopwatch_t & sw)
Definition at line 385 of file profiling.cc.
References gettimeofday(), and stopwatch_t::start.
Referenced by sw_start().
double sw_elapsed_cycles (stopwatch_t & sw)
Definition at line 400 of file profiling.cc.
References GetClockFreq(), and sw_elapsed_sec().
double sw_elapsed_sec (stopwatch_t & sw)
Definition at line 396 of file profiling.cc.
References stopwatch_t::elapsed.
Referenced by sw_elapsed_cycles().
auto_ret<int,0> sw_start (stopwatch_t & sw)
Definition at line 380 of file profiling.cc.
References stopwatch_t::elapsed, and sw_continue().
auto_ret<int,0> sw_stop (stopwatch_t & sw)
Definition at line 389 of file profiling.cc.
References stopwatch_t::elapsed, gettimeofday(), and stopwatch_t::start.