Starburst: util/profiling.cc File Reference
util/profiling.cc File Reference
Memory and MicroBlaze profiling information.
#include <sys/io.h>
#include <sys/device.h>
#include <profiling.h>
#include <stdio.h>
Defines
#define MEM_CLK_FREQ 100000000
Memory module clock frequency, in Hz.
#define PRINT_BREAKDOWN
Set to enable a compact space-separated dump of the statistics.
#define WDC_FLUSH_SNAPSHOT(...)
#define MEM_REGION_START(r) ((void*)(((uintptr_t)&_ddrbase)|(uintptr_t)(((r)&(PROFILE_MEM_REGIONS-1))<<28)))
#define MEM_REGION_END(r) ((void*)(((uintptr_t)&_ddrbase)|((uintptr_t)((((r)&(PROFILE_MEM_REGIONS-1))+1)<<28)-1)))
#define PRF_MEM_PRINTF_FMT "%c %18s"
#define PRF_MEM_PRINTF(p, field) ((p)->overflow((p)->field)?'>':' '),sprintf64(s,((p)->field))
#define PRF_MEM_PRINTF_FMT_D " %18.3f"
#define PRF_MB_PRINTF_FMT "%18s"
#define PRF_MB_PRINTF(p, field) sprintf64(s,((p)->field))
#define PRF_MB_PRINTF_FMT_D "%18.3f"
#define PRF_MB_IS_VALID(p, field) ((p)->field<=(p)->cycles)
Functions
prf_mem_t const volatile * prf_mem_snapshot ()
Makes a snapshot of the counter of the memory profiling logic and reset the counters.
static char const * sprintf64 (char(&s)[32], uint64_t v)
prf_mem_t const volatile * prf_mem_dump (prf_mem_t *prf)
Prints the memory profiling to the terminal.
prf_mb_t * prf_mb_snapshot ()
Makes a snapshot of the counter of the MicroBlaze trace profiling logic and reset the counters.
static uint64_t prf_busy_cycles (prf_mb_t const *prf)
static uint64_t prf_other_cycles (prf_mb_t const *prf)
prf_mb_t * prf_mb_dump (prf_mb_t *prf)
Prints the MicroBlaze profiling to the terminal.
static void prf_mb_dump_list_read (prf_mb_t *prf, int sample, struct timeval *time)
static void prf_mb_dump_list_write (prf_mb_t *prf, int sample, struct timeval *time)
static void prf_mb_dump_list_cycles (prf_mb_t *prf, int sample, struct timeval *time)
void prf_mb_dump_list (prf_mb_t *prf, int cnt)
Prints the MicroBlaze profiling to the terminal in a compact way.
void prf_mb_dump_list (prf_mb_snapshot_t *prf, int cnt)
Prints the MicroBlaze profiling to the terminal in a compact way.
void prf_snapshot (void)
Makes a snapshot of both the memory and MicroBlaze, with C-binding.
void prf_dump (void)
Makes a snapshot of both the memory and MicroBlaze and dumps the statistics, with C-binding.
auto_ret< int, 0 > sw_start (stopwatch_t &sw)
auto_ret< int, 0 > sw_continue (stopwatch_t &sw)
auto_ret< int, 0 > sw_stop (stopwatch_t &sw)
double sw_elapsed_sec (stopwatch_t &sw)
double sw_elapsed_cycles (stopwatch_t &sw)
Variables
unsigned int _ddrbase
const char prf_list_hdr_read [] = " read sample time instr local fifo cache_mis uncached\n"
const char prf_list_hdr_write [] = " write sample time local fifo noc_cached noc_uncached\n"
const char prf_list_hdr_cycles [] = " cycles sample time ifetch read_local read_noc write_local write_noc instr fp jump other\n"
Detailed Description
Memory and MicroBlaze profiling information.
Definition in file profiling.cc.
Define Documentation
#define MEM_CLK_FREQ 100000000
Memory module clock frequency, in Hz.
Definition at line 10 of file profiling.cc.
Referenced by prf_mem_dump().
#define MEM_REGION_END (r) ((void*)(((uintptr_t)&_ddrbase)|((uintptr_t)((((r)&(PROFILE_MEM_REGIONS-1))+1)<<28)-1)))
Definition at line 25 of file profiling.cc.
Referenced by prf_mem_dump().
#define MEM_REGION_START (r) ((void*)(((uintptr_t)&_ddrbase)|(uintptr_t)(((r)&(PROFILE_MEM_REGIONS-1))<<28)))
Definition at line 24 of file profiling.cc.
Referenced by prf_mem_dump().
#define PRF_MB_IS_VALID (p, field) ((p)->field<=(p)->cycles)
Referenced by prf_mb_dump().
#define PRF_MB_PRINTF (p, field) sprintf64(s,((p)->field))
Referenced by prf_mb_dump().
#define PRF_MB_PRINTF_FMT "%18s"
Referenced by prf_mb_dump().
#define PRF_MB_PRINTF_FMT_D "%18.3f"
Referenced by prf_mb_dump().
#define PRF_MEM_PRINTF (p, field) ((p)->overflow((p)->field)?'>':' '),sprintf64(s,((p)->field))
Referenced by prf_mem_dump().
#define PRF_MEM_PRINTF_FMT "%c %18s"
Referenced by prf_mem_dump().
#define PRF_MEM_PRINTF_FMT_D " %18.3f"
Referenced by prf_mem_dump().
#define PRINT_BREAKDOWN
Set to enable a compact space-separated dump of the statistics.
Definition at line 13 of file profiling.cc.
#define WDC_FLUSH_SNAPSHOT (...)
Definition at line 20 of file profiling.cc.
Referenced by prf_mb_snapshot().
Function Documentation
static uint64_t prf_busy_cycles (prf_mb_t const * prf) [static]
Definition at line 177 of file profiling.cc.
References _prf_mb_t::delay_slots, _prf_mb_t::fpinstr, _prf_mb_t::instr, and _prf_mb_t::jumps.
Referenced by prf_mb_dump(), and prf_other_cycles().
void prf_dump (void)
Makes a snapshot of both the memory and MicroBlaze and dumps the statistics, with C-binding.
Definition at line 373 of file profiling.cc.
References prf_mb_dump(), prf_mb_snapshot(), and prf_mem_dump().
prf_mb_t* prf_mb_dump (prf_mb_t * prf)
Prints the MicroBlaze profiling to the terminal.
Parameters:
prf the profile information to print, when NULL, prf_mb_snapshot() is called for that
Returns:
the data the output is based on
Definition at line 196 of file profiling.cc.
References _prf_mb_t::cycles, _prf_mb_t::dcache_rhit, _prf_mb_t::dcache_rreq, _prf_mb_t::delay_slots, GetClockFreq(), _prf_mb_t::icache_hit, _prf_mb_t::icache_req, _prf_mb_t::instr, _prf_mb_t::jumps, prf_busy_cycles(), prf_mb_dump_list(), PRF_MB_IS_VALID, PRF_MB_PRINTF, PRF_MB_PRINTF_FMT, PRF_MB_PRINTF_FMT_D, prf_mb_snapshot(), prf_other_cycles(), _prf_mb_t::read_fifo, _prf_mb_t::read_local, _prf_mb_t::read_noc, _prf_mb_t::stall_instr, _prf_mb_t::stall_read, _prf_mb_t::stall_read_noc, _prf_mb_t::stall_write, _prf_mb_t::stall_write_noc, _prf_mb_t::write_fifo, _prf_mb_t::write_local, and _prf_mb_t::write_noc.
Referenced by prf_dump(), and PrintProfilerOutput().
void prf_mb_dump_list (prf_mb_t * prf, int cnt)
Prints the MicroBlaze profiling to the terminal in a compact way.
Parameters:
prf an array with profile information to print, cannot be NULL
cnt the number of array elements prf points to
Definition at line 328 of file profiling.cc.
References prf_mb_dump_list_cycles(), prf_mb_dump_list_read(), and prf_mb_dump_list_write().
Referenced by prf_mb_dump(), and PrintProfilerOutput().
void prf_mb_dump_list (prf_mb_snapshot_t * prf, int cnt)
Prints the MicroBlaze profiling to the terminal in a compact way.
Prints snapshots until the time of the snapshot is either set to 0 or up to cnt.
Parameters:
prf an array with profile information to print, cannot be NULL
cnt the maximum number of array elements prf points to
Definition at line 347 of file profiling.cc.
References prf_mb_dump_list_cycles(), prf_mb_dump_list_read(), prf_mb_dump_list_write(), prf_mb_snapshot_t::snapshot, and prf_mb_snapshot_t::tv.
static void prf_mb_dump_list_cycles (prf_mb_t * prf, int sample, struct timeval * time) [static]
Definition at line 314 of file profiling.cc.
References _prf_mb_t::delay_slots, _prf_mb_t::fpinstr, _prf_mb_t::instr, _prf_mb_t::jumps, prf_other_cycles(), _prf_mb_t::stall_instr, _prf_mb_t::stall_read, _prf_mb_t::stall_read_noc, _prf_mb_t::stall_write, and _prf_mb_t::stall_write_noc.
Referenced by prf_mb_dump_list().
static void prf_mb_dump_list_read (prf_mb_t * prf, int sample, struct timeval * time) [static]
Definition at line 296 of file profiling.cc.
References _prf_mb_t::dcache_rhit, _prf_mb_t::dcache_rreq, _prf_mb_t::icache_hit, _prf_mb_t::icache_req, _prf_mb_t::read_fifo, _prf_mb_t::read_local, and _prf_mb_t::read_noc.
Referenced by prf_mb_dump_list().
static void prf_mb_dump_list_write (prf_mb_t * prf, int sample, struct timeval * time) [static]
Definition at line 305 of file profiling.cc.
References _prf_mb_t::dcache_req, _prf_mb_t::dcache_rreq, _prf_mb_t::write_fifo, _prf_mb_t::write_local, and _prf_mb_t::write_noc.
Referenced by prf_mb_dump_list().
prf_mb_t* prf_mb_snapshot ()
Makes a snapshot of the counter of the MicroBlaze trace profiling logic and reset the counters.
Returns:
The counters just before the reset.
Definition at line 169 of file profiling.cc.
References io_write, PROFILE_MB_BASE, and WDC_FLUSH_SNAPSHOT.
Referenced by prf_dump(), prf_mb_dump(), prf_snapshot(), and ProfilerDaemon().
prf_mem_t const volatile* prf_mem_dump (prf_mem_t * prf)
Prints the memory profiling to the terminal.
Parameters:
prf the profile information to print, when NULL, prf_mem_snapshot() is called for that
Returns:
the data the output is based on
Definition at line 71 of file profiling.cc.
References _prf_mem_t::burst8_read, _prf_mem_t::burst8_write, _prf_mem_t::burstn_read, _prf_mem_t::burstn_write, const, _prf_mem_t::counter_width, _prf_mem_t::cycles, _prf_mem_t::idle, _prf_mem_t::marker, MEM_CLK_FREQ, MEM_REGION_END, MEM_REGION_START, _prf_mem_t::overflow(), PRF_MEM_PRINTF, PRF_MEM_PRINTF_FMT, PRF_MEM_PRINTF_FMT_D, prf_mem_snapshot(), PROFILE_MEM_MARKER, PROFILE_MEM_REGIONS, _prf_mem_t::stats_type, _prf_mem_t::word_read, and _prf_mem_t::word_write.
Referenced by prf_dump().
prf_mem_t const volatile* prf_mem_snapshot ()
Makes a snapshot of the counter of the memory profiling logic and reset the counters.
Returns:
The counters just before the reset.
Definition at line 31 of file profiling.cc.
References io_write, and PROFILE_MEM_BASE.
Referenced by prf_mem_dump(), and prf_snapshot().
static uint64_t prf_other_cycles (prf_mb_t const * prf) [static]
Definition at line 182 of file profiling.cc.
References _prf_mb_t::cycles, prf_busy_cycles(), _prf_mb_t::stall_instr, _prf_mb_t::stall_read, _prf_mb_t::stall_read_noc, _prf_mb_t::stall_write, and _prf_mb_t::stall_write_noc.
Referenced by prf_mb_dump(), and prf_mb_dump_list_cycles().
void prf_snapshot (void)
Makes a snapshot of both the memory and MicroBlaze, with C-binding.
Definition at line 365 of file profiling.cc.
References prf_mb_snapshot(), and prf_mem_snapshot().
static char const* sprintf64 (char(&) s[32], uint64_t v) [static]
Definition at line 38 of file profiling.cc.
References unlikely.
auto_ret<int,0> sw_continue (stopwatch_t & sw)
Definition at line 385 of file profiling.cc.
References gettimeofday(), and stopwatch_t::start.
Referenced by sw_start().
double sw_elapsed_cycles (stopwatch_t & sw)
Definition at line 400 of file profiling.cc.
References GetClockFreq(), and sw_elapsed_sec().
double sw_elapsed_sec (stopwatch_t & sw)
Definition at line 396 of file profiling.cc.
References stopwatch_t::elapsed.
Referenced by sw_elapsed_cycles().
auto_ret<int,0> sw_start (stopwatch_t & sw)
Definition at line 380 of file profiling.cc.
References stopwatch_t::elapsed, and sw_continue().
auto_ret<int,0> sw_stop (stopwatch_t & sw)
Definition at line 389 of file profiling.cc.
References stopwatch_t::elapsed, gettimeofday(), and stopwatch_t::start.
Variable Documentation
unsigned int _ddrbase
const char prf_list_hdr_cycles[] = " cycles sample time ifetch read_local read_noc write_local write_noc instr fp jump other\n"
Definition at line 313 of file profiling.cc.
const char prf_list_hdr_read[] = " read sample time instr local fifo cache_mis uncached\n"
Definition at line 295 of file profiling.cc.
const char prf_list_hdr_write[] = " write sample time local fifo noc_cached noc_uncached\n"
Definition at line 304 of file profiling.cc.