Starburst: daemons/ProfilerDaemon.cc File Reference
daemons/ProfilerDaemon.cc File Reference
Daemons
MicroBlaze profiling daemon.
#include <sys/api.h>
#include <profiling.h>
#include <stdio.h>
#include <unistd.h>
Defines
#define PROFILER_SAMPLE_TIME 100
#define PROFILER_SNAPSHOTS 1200
Functions
void * ProfilerDaemon (void *arg)
Polls the MicroBlaze profiling counters regularly and stores them for later inspection.
int SetupProfilerDaemon (pid_t &pid, prf_mb_snapshot_t **snapshots)
Starts the profiler daemon.
void PrintProfilerOutput (prf_mb_snapshot_t *snapshots, bool full)
Prints profiling information as gathered by the ProfilingDaemon()
Detailed Description
MicroBlaze profiling daemon.
Definition in file ProfilerDaemon.cc.
Define Documentation
#define PROFILER_SAMPLE_TIME 100
Definition at line 11 of file ProfilerDaemon.cc.
Referenced by ProfilerDaemon().
#define PROFILER_SNAPSHOTS 1200
Definition at line 12 of file ProfilerDaemon.cc.
Referenced by PrintProfilerOutput(), and SetupProfilerDaemon().
Function Documentation
void* ProfilerDaemon (void * arg)
Polls the MicroBlaze profiling counters regularly and stores them for later inspection.
The daemon will copy the current counters and reset them, after it will Yield(). When this is all completed within one timeslice, the statistics are gathered after every context switch, so once every replenisment interval.
Channel 0 is expected to be a pointer to a malloced memory that is used to write the data to; it is used as an array of prf_mb_snapshot_t. Make sure that the memory is large enough. The snapshots in the array are valid up to the number of iterations specified when the process exists, otherwise up to the element that has a snapshot time set to 0.
Parameters:
arg the number of iterations to be made before the daemon exits
Returns:
0
Definition at line 29 of file ProfilerDaemon.cc.
References gettimeofday(), OpenChannel(), prf_mb_snapshot(), PROFILER_SAMPLE_TIME, prf_mb_snapshot_t::tv, usleep(), and Yield().
Referenced by SetupProfilerDaemon().