Starburst: include/pthread.h File Reference
include/pthread.h File Reference
POSIX Pthread standard implementation.
#include <sys/types.h>
#include <sys/helix_config.h>
#include <sys/kernel_types.h>
#include <errno.h>
#include <stdint.h>
#include <signal.h>
#include <stdio.h>
Data Structures
struct pthread_attr_t
struct pthread_sch_t
struct pthread_mutexattr_t
struct pthread_mutex_t
struct pthread_condattr_t
struct pthread_cond_t
struct pthread_barrierattr_t
struct pthread_barrier_t
Defines
#define PTHREAD_CREATE_JOINABLE PROC_FLAG_JOINABLE
#define PTHREAD_CREATE_DETACHED PROC_FLAG_DETACHED
#define PTHREAD_PROCESS_PRIVATE 0
#define PTHREAD_PROCESS_SHARED 1
#define PTHREAD_SCHEDULE_LOCAL 0
#define PTHREAD_SCHEDULE_ROUNDROBIN 1
#define PTHREAD_SCHEDULE_BALANCE 2
#define CPU_ZERO(set) *set=0
#define CPU_ALL(set) *set=-1
#define CPU_SET(cpu, set) *set|=(1<<(cpu))
#define CPU_CLR(cpu, set) *set=(*set)&~(1<<(cpu))
#define CPU_ISSET(cpu, set) (((*set)&(1<<(cpu)))!=0)
#define CPU_ISZERO(set) ((*set)==0)
#define pthread_sigmask(a...) sigprocmask(a)
#define PTHREAD_SPIN 1000
#define MUTEX_NR_IDS (NUM_PROCESSORS*MAX_PROCESSES)
#define PTHREAD_MUTEXATTR_INITIALIZER {NULL,0}
#define PTHREAD_MUTEX_INITIALIZER {}
#define pthread_mutex_trylock(...) ENOSYS
#define PTHREAD_MUTEX_NORMAL 0
#define PTHREAD_MUTEX_RECURSIVE 1
#define PTHREAD_MUTEX_ERRORCHECK 2
#define PTHREAD_MUTEX_OWNERTERM_NP 3
#define PTHREAD_MUTEX_DEFAULT PTHREAD_MUTEX_NORMAL
#define COND_NR_IDS MUTEX_NR_IDS
#define PTHREAD_COND_INITIALIZER {}
#define PTHREAD_BARRIER_SERIAL_THREAD EREMCHG
#define PTHREAD_BARRIER_INITIALIZER {}
#define PTHREAD_KEYS_MAX 8
#define PTHREAD_DESTRUCTOR_ITERATIONS 1024
#define pthread_rwlock_init(...) (printf("rwlock not implemented\n"),ENOSYS)
#define pthread_rwlock_destroy(...) (printf("rwlock not implemented\n"),ENOSYS)
#define pthread_rwlock_rdlock(...) (printf("rwlock not implemented\n"),ENOSYS)
#define pthread_rwlock_tryrdlock(...) (printf("rwlock not implemented\n"),ENOSYS)
#define pthread_rwlock_wrlock(...) (printf("rwlock not implemented\n"),ENOSYS)
#define pthread_rwlock_trywrlock(...) (printf("rwlock not implemented\n"),ENOSYS)
#define pthread_rwlock_unlock(...) (printf("rwlock not implemented\n"),ENOSYS)
#define pthread_rwlockattr_init(...) (printf("rwlock not implemented\n"),ENOSYS)
#define pthread_rwlockattr_destroy(...) (printf("rwlock not implemented\n"),ENOSYS)
#define pthread_rwlockattr_getpshared(...) (printf("rwlock not implemented\n"),ENOSYS)
#define pthread_rwlockattr_setpshared(...) (printf("rwlock not implemented\n"),ENOSYS)
#define PTHREAD_ONCE_INIT NULL
#define pthread_once(...) (printf("once not implemented\n"),ENOSYS)
#define write_word(var, val) do{barrier();var=val;barrier();}while(0)
#define TIMESTAMP_GET(now)
#define TIMESTAMP_SET(start, store)
Typedefs
typedef pid_t pthread_t
typedef uint64_t cpu_set_t
typedef int pthread_key_t
typedef int pthread_rwlock_t
typedef int pthread_rwlockattr_t
typedef int pthread_once_t
Functions
int pthread_create (pthread_t *thread, const pthread_attr_t *attr, void *(*start_routine)(void *), void *arg) __attribute__((warn_unused_result))
Creates somewhere a process.
void pthread_exit (void *value_ptr) __attribute__((noreturn))
int pthread_attr_init (pthread_attr_t *attr)
int pthread_attr_destroy (pthread_attr_t *attr)
int pthread_join (pthread_t thread, void **value_ptr) __attribute__((warn_unused_result))
int pthread_detach (pthread_t thread)
int pthread_attr_setdetachstate (pthread_attr_t *attr, int detachstate)
int pthread_attr_getdetachstate (const pthread_attr_t *attr, int *detachstate)
pthread_t pthread_self (void)
int pthread_equal (pthread_t t1, pthread_t t2)
int pthread_attr_setstacksize (pthread_attr_t *attr, size_t stacksize)
int pthread_attr_getstacksize (pthread_attr_t *attr, size_t *stacksize)
int pthread_attr_setschedparam (pthread_attr_t *attr, timems_t slicelength)
int pthread_attr_setaffinity_np (pthread_attr_t *attr, size_t cpusetsize, const cpu_set_t *cpuset)
int pthread_kill (pthread_t thread, int sig)
int pthread_cancel (pthread_t thread)
int pthread_yield (void)
int pthread_mutexattr_protect (pthread_mutexattr_t *attr, void *protectee, size_t sprotectee)
Connects a memory region to be protected by the mutex (memory consistency).
int pthread_mutex_init (pthread_mutex_t *mutex, const pthread_mutexattr_t *attr) __attribute__((warn_unused_result))
int pthread_mutex_destroy (pthread_mutex_t *mutex)
int pthread_mutex_lock (pthread_mutex_t *mutex) __attribute__((warn_unused_result))
int pthread_mutex_unlock (pthread_mutex_t *mutex)
int pthread_mutex_protect (pthread_mutex_t *mutex, void *protectee, size_t sprotectee)
int pthread_mutexattr_init (pthread_mutexattr_t *attr)
int pthread_mutexattr_destroy (pthread_mutexattr_t *attr)
int pthread_mutexattr_gettype (const pthread_mutexattr_t *attr, int *type)
int pthread_mutexattr_settype (pthread_mutexattr_t *attr, int type)
int pthread_cond_signal (pthread_cond_t *cond)
int pthread_cond_broadcast (pthread_cond_t *cond)
int pthread_cond_init (pthread_cond_t *cond, const pthread_condattr_t *attr) __attribute__((warn_unused_result))
int pthread_cond_destroy (pthread_cond_t *cond)
int pthread_cond_wait (pthread_cond_t *cond, pthread_mutex_t *mutex) __attribute__((warn_unused_result))
int pthread_condattr_init (pthread_condattr_t *attr)
int pthread_condattr_destroy (pthread_condattr_t *attr)
int pthread_condattr_getpshared (const pthread_condattr_t *attr, int *pshared)
int pthread_condattr_setpshared (pthread_condattr_t *attr, int pshared)
int pthread_barrier_destroy (pthread_barrier_t *barrier)
int pthread_barrier_init (pthread_barrier_t *barrier, const pthread_barrierattr_t *attr, unsigned int count) __attribute__((warn_unused_result))
int pthread_barrier_wait (pthread_barrier_t *barrier) __attribute__((warn_unused_result))
int pthread_barrierattr_destroy (pthread_barrierattr_t *attr)
int pthread_barrierattr_init (pthread_barrierattr_t *attr)
int pthread_barrierattr_getpshared (const pthread_barrierattr_t *attr, int *pshared)
int pthread_barrierattr_setpshared (pthread_barrierattr_t *attr, int pshared)
int pthread_key_create (pthread_key_t *key, void(*destructor)(void *)) __attribute__((warn_unused_result))
int pthread_key_delete (pthread_key_t key)
void * pthread_getspecific (pthread_key_t key)
int pthread_setspecific (pthread_key_t key, const void *value)
int pthread_global_init (void)
int pthread_global_cleanup (void)
int pthread_local_init (void)
int pthread_local_cleanup (void)
int pthread_thread_init (void)
int pthread_thread_cleanup (void)
int pthread_key_global_init (void)
int pthread_key_global_cleanup (void)
int pthread_key_thread_init (void)
int pthread_key_thread_cleanup (void)
int pthread_mutex_global_init (void)
int pthread_mutex_global_cleanup (void)
int pthread_mutex_thread_init (void)
int pthread_mutex_thread_cleanup (void)
int pthread_cond_global_init (void)
int pthread_cond_global_cleanup (void)
int pthread_cond_thread_init (void)
int pthread_cond_thread_cleanup (void)
int pthread_barrier_global_init (void)
int pthread_barrier_global_cleanup (void)
int pthread_barrier_thread_init (void)
int pthread_barrier_thread_cleanup (void)
void pthread_stats_elem_register (pthread_key_t key, void *elem, char *name)
void pthread_stats_elem_unregister (pthread_key_t key, void *elem)
int pthread_stats_global_init (pthread_key_t *key)
int pthread_stats_global_cleanup (pthread_key_t key)
int pthread_stats_thread_init (pthread_key_t key, void(*print_func)(void *))
Detailed Description
POSIX Pthread standard implementation.
A mutex, condition and barrier are synchronization variables. For memory consistency, they are assumed to be always shared objects, but they need not to be protected. So, when using i.e. a mutex, do not wrap the pthread_mutex_* calls in mc_entry_* and mc_exit_* calls. In contrast to any other variable, these are automatically cache line aligned and protected by themselves.
Definition in file pthread.h.
Define Documentation
#define COND_NR_IDS MUTEX_NR_IDS
Definition at line 202 of file pthread.h.
Referenced by _pthread_cond_signal(), pthread_cond_destroy(), and pthread_cond_init().
#define CPU_ALL (set) *set=-1
Definition at line 62 of file pthread.h.
Referenced by pthread_attr_init().
#define CPU_CLR (cpu, set) *set=(*set)&~(1<<(cpu))
Definition at line 64 of file pthread.h.
#define CPU_ISSET (cpu, set) (((*set)&(1<<(cpu)))!=0)
Definition at line 65 of file pthread.h.
Referenced by check_forced_cpu(), and find_cpu().
#define CPU_ISZERO (set) ((*set)==0)
Definition at line 66 of file pthread.h.
Referenced by check_attr().
#define CPU_SET (cpu, set) *set|=(1<<(cpu))
Definition at line 63 of file pthread.h.
#define CPU_ZERO (set) *set=0
Definition at line 61 of file pthread.h.
#define MUTEX_NR_IDS (NUM_PROCESSORS*MAX_PROCESSES)
Definition at line 112 of file pthread.h.
#define PTHREAD_BARRIER_INITIALIZER {}
Definition at line 262 of file pthread.h.
#define PTHREAD_BARRIER_SERIAL_THREAD EREMCHG
Definition at line 235 of file pthread.h.
Referenced by pthread_barrier_wait().
#define PTHREAD_COND_INITIALIZER {}
Definition at line 220 of file pthread.h.
#define PTHREAD_CREATE_DETACHED PROC_FLAG_DETACHED
Definition at line 43 of file pthread.h.
Referenced by check_attr(), pthread_attr_setdetachstate(), and pthread_detach().
#define PTHREAD_CREATE_JOINABLE PROC_FLAG_JOINABLE
Definition at line 42 of file pthread.h.
Referenced by pthread_attr_init(), and pthread_attr_setdetachstate().
#define PTHREAD_DESTRUCTOR_ITERATIONS 1024
Definition at line 276 of file pthread.h.
Referenced by pthread_key_thread_cleanup().
#define PTHREAD_KEYS_MAX 8
Definition at line 275 of file pthread.h.
Referenced by DumpConfig(), pthread_getspecific(), pthread_key_create(), pthread_key_delete(), pthread_key_global_init(), pthread_key_thread_init(), and pthread_setspecific().
#define PTHREAD_MUTEX_DEFAULT PTHREAD_MUTEX_NORMAL
Definition at line 194 of file pthread.h.
Referenced by pthread_mutexattr_gettype(), and pthread_mutexattr_settype().
#define PTHREAD_MUTEX_ERRORCHECK 2
Definition at line 192 of file pthread.h.
#define PTHREAD_MUTEX_INITIALIZER {}
Definition at line 169 of file pthread.h.
#define PTHREAD_MUTEX_NORMAL 0
Definition at line 190 of file pthread.h.
#define PTHREAD_MUTEX_OWNERTERM_NP 3
Definition at line 193 of file pthread.h.
#define PTHREAD_MUTEX_RECURSIVE 1
Definition at line 191 of file pthread.h.
#define pthread_mutex_trylock (...) ENOSYS
Definition at line 184 of file pthread.h.
#define PTHREAD_MUTEXATTR_INITIALIZER {NULL,0}
Definition at line 125 of file pthread.h.
Referenced by pthread_key_global_init(), and pthread_mutexattr_init().
#define pthread_once (...) (printf("once not implemented\n"),ENOSYS)
Definition at line 322 of file pthread.h.
#define PTHREAD_ONCE_INIT NULL
Definition at line 321 of file pthread.h.
#define PTHREAD_PROCESS_PRIVATE 0
Definition at line 44 of file pthread.h.
Referenced by pthread_barrierattr_init(), and pthread_condattr_init().
#define PTHREAD_PROCESS_SHARED 1
Definition at line 45 of file pthread.h.
#define pthread_rwlock_destroy (...) (printf("rwlock not implemented\n"),ENOSYS)
Definition at line 306 of file pthread.h.
#define pthread_rwlock_init (...) (printf("rwlock not implemented\n"),ENOSYS)
Definition at line 305 of file pthread.h.
#define pthread_rwlock_rdlock (...) (printf("rwlock not implemented\n"),ENOSYS)
Definition at line 307 of file pthread.h.
#define pthread_rwlock_tryrdlock (...) (printf("rwlock not implemented\n"),ENOSYS)
Definition at line 308 of file pthread.h.
#define pthread_rwlock_trywrlock (...) (printf("rwlock not implemented\n"),ENOSYS)
Definition at line 310 of file pthread.h.
#define pthread_rwlock_unlock (...) (printf("rwlock not implemented\n"),ENOSYS)
Definition at line 311 of file pthread.h.
#define pthread_rwlock_wrlock (...) (printf("rwlock not implemented\n"),ENOSYS)
Definition at line 309 of file pthread.h.
#define pthread_rwlockattr_destroy (...) (printf("rwlock not implemented\n"),ENOSYS)
Definition at line 313 of file pthread.h.
#define pthread_rwlockattr_getpshared (...) (printf("rwlock not implemented\n"),ENOSYS)
Definition at line 314 of file pthread.h.
#define pthread_rwlockattr_init (...) (printf("rwlock not implemented\n"),ENOSYS)
Definition at line 312 of file pthread.h.
#define pthread_rwlockattr_setpshared (...) (printf("rwlock not implemented\n"),ENOSYS)
Definition at line 315 of file pthread.h.
#define PTHREAD_SCHEDULE_BALANCE 2
Definition at line 49 of file pthread.h.
#define PTHREAD_SCHEDULE_LOCAL 0
Definition at line 47 of file pthread.h.
#define PTHREAD_SCHEDULE_ROUNDROBIN 1
Definition at line 48 of file pthread.h.
#define pthread_sigmask (a...) sigprocmask(a)
Definition at line 92 of file pthread.h.
#define PTHREAD_SPIN 1000
Definition at line 111 of file pthread.h.
Referenced by _pthread_cond_wait().
#define TIMESTAMP_GET (now)
Value:
do{                                             \
        struct timeval tv_now;                      \
        gettimeofday(&tv_now,NULL);                 \
        now=tv_now.tv_sec*1000000+tv_now.tv_usec;   \
    }while(0)
Definition at line 360 of file pthread.h.
Referenced by _pthread_cond_wait(), pthread_barrier_wait(), and pthread_mutex_lock().
#define TIMESTAMP_SET (start, store)
Value:
do{                                             \
        int _now;                                   \
        TIMESTAMP_GET(_now);                        \
        _now=(store)+(_now-start);                  \
        write_word(store,_now);                     \
    }while(0)
Definition at line 366 of file pthread.h.
Referenced by _pthread_cond_wait(), pthread_barrier_wait(), pthread_mutex_lock(), and pthread_mutex_unlock().
#define write_word (var, val) do{barrier();var=val;barrier();}while(0)
Definition at line 359 of file pthread.h.
Typedef Documentation
typedef uint64_t cpu_set_t
Definition at line 60 of file pthread.h.
typedef int pthread_key_t
Definition at line 278 of file pthread.h.
typedef int pthread_once_t
Definition at line 320 of file pthread.h.
typedef int pthread_rwlock_t
Definition at line 302 of file pthread.h.
typedef int pthread_rwlockattr_t
Definition at line 303 of file pthread.h.
typedef pid_t pthread_t
Definition at line 55 of file pthread.h.
Function Documentation
int pthread_attr_destroy (pthread_attr_t * attr)
Definition at line 154 of file pthread.cc.
References ESUCCESS.
int pthread_attr_getdetachstate (const pthread_attr_t * attr, int * detachstate)
Definition at line 180 of file pthread.cc.
References ESUCCESS, pthread_attr_t::flags, and PTHREAD_CREATE_DETACH_STATE.
int pthread_attr_getstacksize (pthread_attr_t * attr, size_t * stacksize)
Definition at line 202 of file pthread.cc.
References ESUCCESS, and pthread_attr_t::stack.
int pthread_attr_init (pthread_attr_t * attr)
Definition at line 146 of file pthread.cc.
References pthread_attr_t::affinity, CPU_ALL, ESUCCESS, pthread_attr_t::flags, PROC_DEFAULT_STACK, PROC_DEFAULT_TIMESLICE, PTHREAD_CREATE_JOINABLE, pthread_attr_t::slicelength, and pthread_attr_t::stack.
Referenced by check_attr().
int pthread_attr_setaffinity_np (pthread_attr_t * attr, size_t cpusetsize, const cpu_set_t * cpuset)
Definition at line 217 of file pthread.cc.
References pthread_attr_t::affinity, and ESUCCESS.
int pthread_attr_setdetachstate (pthread_attr_t * attr, int detachstate)
Definition at line 173 of file pthread.cc.
References ESUCCESS, pthread_attr_t::flags, PTHREAD_CREATE_DETACH_STATE, PTHREAD_CREATE_DETACHED, and PTHREAD_CREATE_JOINABLE.
int pthread_attr_setschedparam (pthread_attr_t * attr, timems_t slicelength)
Definition at line 210 of file pthread.cc.
References ESUCCESS, and pthread_attr_t::slicelength.
int pthread_attr_setstacksize (pthread_attr_t * attr, size_t stacksize)
Definition at line 195 of file pthread.cc.
References ESUCCESS, and pthread_attr_t::stack.
int pthread_barrier_destroy (pthread_barrier_t * barrier)
Definition at line 161 of file barrier.cc.
References abort(), pthread_barrier_t::attr, pthread_barrier_t::counter, mc_entry_ro, mc_exit_ro, pthread_barrierattr_destroy(), and pthread_stats_elem_unregister.
int pthread_barrier_global_cleanup (void)
Definition at line 324 of file barrier.cc.
References pthread_stats_global_cleanup.
Referenced by pthread_global_cleanup().
int pthread_barrier_global_init (void)
Definition at line 320 of file barrier.cc.
References pthread_stats_global_init.
Referenced by pthread_global_init().
int pthread_barrier_init (pthread_barrier_t * barrier, const pthread_barrierattr_t * attr, unsigned int count)
Definition at line 183 of file barrier.cc.
References abort(), pthread_barrier_t::attr, pthread_barrier_t::counter, mc_entry_wou, mc_exit_wou, pthread_barrier_t::participants, pthread_barrierattr_init(), pthread_stats_elem_register, and pthread_barrier_t::queue.
Referenced by dvi_screen::Init(), and ShutdownDaemonInit().
int pthread_barrier_thread_cleanup (void)
Definition at line 332 of file barrier.cc.
Referenced by pthread_thread_cleanup().
int pthread_barrier_thread_init (void)
Definition at line 328 of file barrier.cc.
References pthread_stats_thread_init.
Referenced by pthread_thread_init().
int pthread_barrier_wait (pthread_barrier_t * barrier)
Definition at line 212 of file barrier.cc.
References ASSERT, pthread_barrier_t::counter, lck_lock_p(), lck_pass(), lck_unlock(), mc_entry_rw, mc_exit_rw, pthread_barrier_t::participants, PTHREAD_BARRIER_SERIAL_THREAD, pthread_kill(), pthread_self(), pthread_barrier_t::queue, sigblock(), SIGSYNC, TIMESTAMP_GET, TIMESTAMP_SET, and unlikely.
Referenced by ShutdownDaemon().
int pthread_barrierattr_destroy (pthread_barrierattr_t * attr)
Definition at line 293 of file barrier.cc.
Referenced by pthread_barrier_destroy().
int pthread_barrierattr_getpshared (const pthread_barrierattr_t * attr, int * pshared)
Definition at line 306 of file barrier.cc.
References pthread_barrierattr_t::pshared.
int pthread_barrierattr_init (pthread_barrierattr_t * attr)
Definition at line 299 of file barrier.cc.
References pthread_barrierattr_t::pshared, and PTHREAD_PROCESS_PRIVATE.
Referenced by pthread_barrier_init().
int pthread_barrierattr_setpshared (pthread_barrierattr_t * attr, int pshared)
Definition at line 313 of file barrier.cc.
References pthread_barrierattr_t::pshared.
int pthread_cancel (pthread_t thread)
Definition at line 230 of file pthread.cc.
int pthread_cond_broadcast (pthread_cond_t * cond)
Definition at line 123 of file cond.cc.
References _pthread_cond_signal().
int pthread_cond_destroy (pthread_cond_t * cond)
Definition at line 53 of file cond.cc.
References COND_NR_IDS, COND_STATE_WAITING, mc_entry_ro, mc_exit_ro, and pthread_stats_elem_unregister.
Referenced by pipe_close().
int pthread_cond_global_cleanup (void)
Definition at line 296 of file cond.cc.
References pthread_stats_global_cleanup.
Referenced by pthread_global_cleanup().
int pthread_cond_global_init (void)
Definition at line 292 of file cond.cc.
References pthread_stats_global_init.
Referenced by pthread_global_init().
int pthread_cond_init (pthread_cond_t * cond, const pthread_condattr_t * attr)
Definition at line 27 of file cond.cc.
References pthread_cond_t::attr, COND_NR_IDS, COND_STATE_FREE, pthread_cond_t::last_signalled, mc_entry_wou, mc_exit_wou, pthread_condattr_init(), and pthread_stats_elem_register.
Referenced by pipe().
int pthread_cond_signal (pthread_cond_t * cond)
Definition at line 119 of file cond.cc.
References _pthread_cond_signal().
Referenced by pipe_read(), and pipe_write().
int pthread_cond_thread_cleanup (void)
Definition at line 304 of file cond.cc.
Referenced by pthread_thread_cleanup().
int pthread_cond_thread_init (void)
Definition at line 300 of file cond.cc.
References pthread_stats_thread_init.
Referenced by pthread_thread_init().
int pthread_cond_wait (pthread_cond_t * cond, pthread_mutex_t * mutex)
Definition at line 244 of file cond.cc.
References _pthread_cond_wait().
Referenced by pipe_read(), and pipe_write().
int pthread_condattr_destroy (pthread_condattr_t * attr)
Definition at line 261 of file cond.cc.
int pthread_condattr_getpshared (const pthread_condattr_t * attr, int * pshared)
Definition at line 267 of file cond.cc.
References pthread_condattr_t::pshared.
int pthread_condattr_init (pthread_condattr_t * attr)
Definition at line 254 of file cond.cc.
References pthread_condattr_t::pshared, and PTHREAD_PROCESS_PRIVATE.
Referenced by pthread_cond_init().
int pthread_condattr_setpshared (pthread_condattr_t * attr, int pshared)
Definition at line 274 of file cond.cc.
References pthread_condattr_t::pshared.
int pthread_create (pthread_t * thread, const pthread_attr_t * attr, void *(*)(void *) start_routine, void * arg)
Creates somewhere a process.
Keep in mind that a process is by default joinable.
All cores must be booted beforehand.
Definition at line 115 of file pthread.cc.
References a, check_attr(), check_forced_cpu(), CreateProcess(), DestroyProcess(), ESUCCESS, find_cpu(), pthread_attr_t::flags, getgpid(), pid, SetProcessFlags(), pthread_attr_t::slicelength, pthread_attr_t::stack, and StartProcess().
int pthread_detach (pthread_t thread)
Definition at line 164 of file pthread.cc.
References getgpidproc(), getlpid(), GetProcessFlags(), pid, PTHREAD_CREATE_DETACH_STATE, PTHREAD_CREATE_DETACHED, and SetProcessFlags().
int pthread_equal (pthread_t t1, pthread_t t2)
Definition at line 191 of file pthread.cc.
void pthread_exit (void * value_ptr)
Definition at line 142 of file pthread.cc.
void* pthread_getspecific (pthread_key_t key)
Definition at line 72 of file key.cc.
References abort(), GetProcLocal(), mc_entry_ro, mc_exit_ro, proc_local_t::pthread_key, pthread_key_admin_t::pthread_key_nr, proc_local_t::pthread_key_nr, and PTHREAD_KEYS_MAX.
Referenced by pthread_key_thread_cleanup(), pthread_stats_elem_register(), and pthread_stats_elem_unregister().
int pthread_global_cleanup (void)
Definition at line 260 of file pthread.cc.
References pthread_barrier_global_cleanup(), pthread_cond_global_cleanup(), pthread_key_global_cleanup(), and pthread_mutex_global_cleanup().
int pthread_global_init (void)
Definition at line 239 of file pthread.cc.
References MAX_PROCESSES, mc_entry_wou, mc_exit_wou, pthread_barrier_global_init(), pthread_cond_global_init(), pthread_key_global_init(), and pthread_mutex_global_init().
Referenced by kInitKernel().
int pthread_join (pthread_t thread, void ** value_ptr)
Definition at line 158 of file pthread.cc.
References getgpidproc(), getlpid(), pid, and WaitProcess().
int pthread_key_create (pthread_key_t * key, void(*)(void *) destructor)
Definition at line 25 of file key.cc.
References KEY_LOCK, KEY_UNLOCK, LOCAL_INIT, pthread_key_admin_t::pthread_key_destructor, pthread_key_admin_t::pthread_key_nr, and PTHREAD_KEYS_MAX.
Referenced by pthread_stats_global_init().
int pthread_key_delete (pthread_key_t key)
Definition at line 53 of file key.cc.
References KEY_LOCK, KEY_UNLOCK, LOCAL_INIT, and PTHREAD_KEYS_MAX.
Referenced by pthread_stats_global_cleanup().
int pthread_key_global_cleanup (void)
Definition at line 134 of file key.cc.
References pthread_mutex_destroy().
Referenced by pthread_global_cleanup().
int pthread_key_global_init (void)
Definition at line 116 of file key.cc.
References mc_entry_wou, mc_exit_wou, pthread_key_admin_t::pthread_key_nr, PTHREAD_KEYS_MAX, pthread_mutex_init(), PTHREAD_MUTEXATTR_INITIALIZER, and pthread_mutexattr_protect().
Referenced by pthread_global_init().
int pthread_key_thread_cleanup (void)
Definition at line 147 of file key.cc.
References LOCAL_INIT, mc_entry_ro, mc_exit_ro, PTHREAD_DESTRUCTOR_ITERATIONS, pthread_getspecific(), pthread_key_admin_t::pthread_key_destructor, and pthread_setspecific().
Referenced by pthread_thread_cleanup().
int pthread_key_thread_init (void)
Definition at line 139 of file key.cc.
References LOCAL_INIT, proc_local_t::pthread_key_nr, and PTHREAD_KEYS_MAX.
Referenced by pthread_thread_init().
int pthread_kill (pthread_t thread, int sig)
Definition at line 224 of file pthread.cc.
References getgpidproc(), getlpid(), pid, and SendSignal().
Referenced by _pthread_cond_signal(), lck_migrate(), and pthread_barrier_wait().
int pthread_local_cleanup (void)
Definition at line 285 of file pthread.cc.
int pthread_local_init (void)
Definition at line 273 of file pthread.cc.
References GetProcID(), HOOK_SCHEDULER, mc_entry_wou, mc_exit_wou, pthread_sch_t::processes, and RegisterHook().
Referenced by kInitKernel().
int pthread_mutex_destroy (pthread_mutex_t * mutex)
Definition at line 370 of file mutex.cc.
References lck_destroy(), mc_entry_ro, mc_exit_ro, MUTEX2LCK, and pthread_stats_elem_unregister.
Referenced by pipe_close(), and pthread_key_global_cleanup().
int pthread_mutex_global_cleanup (void)
Definition at line 478 of file mutex.cc.
References pthread_stats_global_cleanup.
Referenced by pthread_global_cleanup().
int pthread_mutex_global_init (void)
Definition at line 474 of file mutex.cc.
References pthread_stats_global_init.
Referenced by pthread_global_init().
int pthread_mutex_init (pthread_mutex_t * mutex, const pthread_mutexattr_t * attr)
Definition at line 347 of file mutex.cc.
References ESUCCESS, mc_entry_wou, mc_exit_wou, pthread_mutexattr_init(), and pthread_stats_elem_register.
Referenced by malloc_init(), pipe(), and pthread_key_global_init().
int pthread_mutex_lock (pthread_mutex_t * mutex)
Definition at line 381 of file mutex.cc.
References lck_lock(), lck_lock_p(), LR_FREE, LR_LOCAL, LR_NEW, mc_entry_ro, mc_entry_rwu, mc_exit_ro, MUTEX2LCK, TIMESTAMP_GET, TIMESTAMP_SET, TRACE_PHASE_MUTEX, TracePhaseChange(), unlikely, and write_word.
Referenced by _pthread_cond_wait(), find_cpu(), pipe_close(), pipe_read(), pipe_vfcntl(), pipe_write(), pprintf(), pthread_mutex_protect(), scalloc(), sfree(), smalloc(), and srealloc().
int pthread_mutex_protect (pthread_mutex_t * mutex, void * protectee, size_t sprotectee)
Definition at line 313 of file mutex.cc.
References lck_destroy(), lck_lock(), mc_entry_rwu, mc_exit_rwu, MUTEX2LCK, pthread_mutex_lock(), and pthread_mutex_unlock().
int pthread_mutex_thread_cleanup (void)
Definition at line 486 of file mutex.cc.
Referenced by pthread_thread_cleanup().
int pthread_mutex_thread_init (void)
Definition at line 482 of file mutex.cc.
References pthread_stats_thread_init.
Referenced by pthread_thread_init().
int pthread_mutex_unlock (pthread_mutex_t * mutex)
Definition at line 423 of file mutex.cc.
References lck_unlock(), mc_exit_ro, mc_exit_rwu, MUTEX2LCK, and TIMESTAMP_SET.
Referenced by _pthread_cond_wait(), find_cpu(), pipe_close(), pipe_read(), pipe_vfcntl(), pipe_write(), pprintf(), pthread_mutex_protect(), scalloc(), sfree(), smalloc(), and srealloc().
int pthread_mutexattr_destroy (pthread_mutexattr_t * attr)
Definition at line 457 of file mutex.cc.
int pthread_mutexattr_gettype (const pthread_mutexattr_t * attr, int * type)
Definition at line 461 of file mutex.cc.
References PTHREAD_MUTEX_DEFAULT.
int pthread_mutexattr_init (pthread_mutexattr_t * attr)
Definition at line 449 of file mutex.cc.
References PTHREAD_MUTEXATTR_INITIALIZER.
Referenced by pipe(), and pthread_mutex_init().
int pthread_mutexattr_protect (pthread_mutexattr_t * attr, void * protectee, size_t sprotectee)
Connects a memory region to be protected by the mutex (memory consistency).
Two mutexes protecting the same shared object are equivalent.
attr itself should not be a shared object.
Definition at line 305 of file mutex.cc.
References pthread_mutexattr_t::protectee, and pthread_mutexattr_t::sprotectee.
Referenced by pipe(), and pthread_key_global_init().
int pthread_mutexattr_settype (pthread_mutexattr_t * attr, int type)
Definition at line 468 of file mutex.cc.
References PTHREAD_MUTEX_DEFAULT.
pthread_t pthread_self (void)
Definition at line 187 of file pthread.cc.
References getgpid().
Referenced by pthread_barrier_wait().
int pthread_setspecific (pthread_key_t key, const void * value)
Definition at line 97 of file key.cc.
References LOCAL_INIT, mc_entry_ro, mc_exit_ro, proc_local_t::pthread_key, pthread_key_admin_t::pthread_key_nr, proc_local_t::pthread_key_nr, and PTHREAD_KEYS_MAX.
Referenced by pthread_key_thread_cleanup(), and pthread_stats_thread_init().
void pthread_stats_elem_register (pthread_key_t key, void * elem, char * name)
Definition at line 16 of file stats.cc.
References stats_t::e, MAX_STAT_ELEM, stats_t::num, and pthread_getspecific().
void pthread_stats_elem_unregister (pthread_key_t key, void * elem)
Definition at line 33 of file stats.cc.
References stats_t::e, MAX_STAT_ELEM, stats_t::num, stats_t::print_func, and pthread_getspecific().
int pthread_stats_global_cleanup (pthread_key_t key)
Definition at line 56 of file stats.cc.
References pthread_key_delete().
int pthread_stats_global_init (pthread_key_t * key)
Definition at line 52 of file stats.cc.
References pthread_key_create(), and pthread_stats_thread_cleanup().
int pthread_stats_thread_init (pthread_key_t key, void(*)(void *) print_func)
Definition at line 60 of file stats.cc.
References lcalloc, lfree, and pthread_setspecific().
int pthread_thread_cleanup (void)
Definition at line 302 of file pthread.cc.
References pthread_barrier_thread_cleanup(), pthread_cond_thread_cleanup(), pthread_key_thread_cleanup(), and pthread_mutex_thread_cleanup().
Referenced by ProcessEntry().
int pthread_thread_init (void)
Definition at line 289 of file pthread.cc.
References pthread_barrier_thread_init(), pthread_cond_thread_init(), pthread_key_thread_init(), and pthread_mutex_thread_init().
Referenced by ProcessEntry().
int pthread_yield (void)
Definition at line 235 of file pthread.cc.
References Yield().