Starburst: posix/pthread.cc File Reference
posix/pthread.cc File Reference
POSIX thread implementation for basic process management.
#include <pthread.h>
#include <sys/syscall.h>
#include <sys/helix_config.h>
#include <sys/api.h>
#include <stdlib.h>
#include <unistd.h>
#include <mc.h>
Defines
#define RR_SKIP -1
#define PTHREAD_CREATE_DETACH_STATE (PTHREAD_CREATE_JOINABLE|PTHREAD_CREATE_DETACHED)
Functions
static int check_attr (pthread_t *thread, const pthread_attr_t *attr_in, pthread_attr_t *attr_out)
static int check_forced_cpu (pthread_attr_t *attr)
static int find_cpu (pthread_attr_t *attr)
int pthread_create (pthread_t *thread, const pthread_attr_t *attr, void *(*start_routine)(void *), void *arg)
Creates somewhere a process.
void pthread_exit (void *value_ptr)
int pthread_attr_init (pthread_attr_t *attr)
int pthread_attr_destroy (pthread_attr_t *attr)
int pthread_join (pthread_t thread, void **value_ptr)
int pthread_detach (pthread_t thread)
int pthread_attr_setdetachstate (pthread_attr_t *attr, int detachstate)
int pthread_attr_getdetachstate (const pthread_attr_t *attr, int *detachstate)
pthread_t pthread_self (void)
int pthread_equal (pthread_t t1, pthread_t t2)
int pthread_attr_setstacksize (pthread_attr_t *attr, size_t stacksize)
int pthread_attr_getstacksize (pthread_attr_t *attr, size_t *stacksize)
int pthread_attr_setschedparam (pthread_attr_t *attr, timems_t slicelength)
int pthread_attr_setaffinity_np (pthread_attr_t *attr, size_t cpusetsize, const cpu_set_t *cpuset)
int pthread_kill (pthread_t thread, int sig)
int pthread_cancel (pthread_t thread)
int pthread_yield (void)
int pthread_global_init ()
int pthread_global_cleanup ()
int pthread_local_init ()
int pthread_local_cleanup ()
int pthread_thread_init ()
int pthread_thread_cleanup ()
Variables
pthread_mutex_t pthread_sch_lock = PTHREAD_MUTEX_INITIALIZER
pthread_sch_t pthread_sch[NUM_PROCESSORS] ATTR_DATA_ALIGNED
Detailed Description
POSIX thread implementation for basic process management.
Definition in file pthread.cc.
Define Documentation
#define PTHREAD_CREATE_DETACH_STATE (PTHREAD_CREATE_JOINABLE|PTHREAD_CREATE_DETACHED)
Definition at line 19 of file pthread.cc.
Referenced by check_attr(), pthread_attr_getdetachstate(), pthread_attr_setdetachstate(), and pthread_detach().
#define RR_SKIP -1
Definition at line 16 of file pthread.cc.
Referenced by find_cpu().
Function Documentation
static int check_attr (pthread_t * thread, const pthread_attr_t * attr_in, pthread_attr_t * attr_out) [static]
Definition at line 28 of file pthread.cc.
References pthread_attr_t::affinity, CPU_ISZERO, ESUCCESS, pthread_attr_t::flags, pthread_attr_init(), PTHREAD_CREATE_DETACH_STATE, and PTHREAD_CREATE_DETACHED.
Referenced by pthread_create().
static int check_forced_cpu (pthread_attr_t * attr) [static]
Definition at line 46 of file pthread.cc.
References pthread_attr_t::affinity, and CPU_ISSET.
Referenced by pthread_create().
static int find_cpu (pthread_attr_t * attr) [static]
Definition at line 58 of file pthread.cc.
References __attribute__, pthread_attr_t::affinity, CPU_ISSET, GetProcID(), MAX_PROCESSES, mc_entry_ro, mc_entry_rwu, mc_exit_ro, pthread_mutex_lock(), pthread_mutex_unlock(), RR_SKIP, and sysconf().
Referenced by pthread_create().
int pthread_attr_destroy (pthread_attr_t * attr)
Definition at line 154 of file pthread.cc.
References ESUCCESS.
int pthread_attr_getdetachstate (const pthread_attr_t * attr, int * detachstate)
Definition at line 180 of file pthread.cc.
References ESUCCESS, pthread_attr_t::flags, and PTHREAD_CREATE_DETACH_STATE.
int pthread_attr_getstacksize (pthread_attr_t * attr, size_t * stacksize)
Definition at line 202 of file pthread.cc.
References ESUCCESS, and pthread_attr_t::stack.
int pthread_attr_init (pthread_attr_t * attr)
Definition at line 146 of file pthread.cc.
References pthread_attr_t::affinity, CPU_ALL, ESUCCESS, pthread_attr_t::flags, PROC_DEFAULT_STACK, PROC_DEFAULT_TIMESLICE, PTHREAD_CREATE_JOINABLE, pthread_attr_t::slicelength, and pthread_attr_t::stack.
Referenced by check_attr().
int pthread_attr_setaffinity_np (pthread_attr_t * attr, size_t cpusetsize, const cpu_set_t * cpuset)
Definition at line 217 of file pthread.cc.
References pthread_attr_t::affinity, and ESUCCESS.
int pthread_attr_setdetachstate (pthread_attr_t * attr, int detachstate)
Definition at line 173 of file pthread.cc.
References ESUCCESS, pthread_attr_t::flags, PTHREAD_CREATE_DETACH_STATE, PTHREAD_CREATE_DETACHED, and PTHREAD_CREATE_JOINABLE.
int pthread_attr_setschedparam (pthread_attr_t * attr, timems_t slicelength)
Definition at line 210 of file pthread.cc.
References ESUCCESS, and pthread_attr_t::slicelength.
int pthread_attr_setstacksize (pthread_attr_t * attr, size_t stacksize)
Definition at line 195 of file pthread.cc.
References ESUCCESS, and pthread_attr_t::stack.
int pthread_cancel (pthread_t thread)
Definition at line 230 of file pthread.cc.
int pthread_create (pthread_t * thread, const pthread_attr_t * attr, void *(*)(void *) start_routine, void * arg)
Creates somewhere a process.
Keep in mind that a process is by default joinable.
All cores must be booted beforehand.
Definition at line 115 of file pthread.cc.
References a, check_attr(), check_forced_cpu(), CreateProcess(), DestroyProcess(), ESUCCESS, find_cpu(), pthread_attr_t::flags, getgpid(), pid, SetProcessFlags(), pthread_attr_t::slicelength, pthread_attr_t::stack, and StartProcess().
int pthread_detach (pthread_t thread)
Definition at line 164 of file pthread.cc.
References getgpidproc(), getlpid(), GetProcessFlags(), pid, PTHREAD_CREATE_DETACH_STATE, PTHREAD_CREATE_DETACHED, and SetProcessFlags().
int pthread_equal (pthread_t t1, pthread_t t2)
Definition at line 191 of file pthread.cc.
void pthread_exit (void * value_ptr)
Definition at line 142 of file pthread.cc.
int pthread_global_cleanup (void)
Definition at line 260 of file pthread.cc.
References pthread_barrier_global_cleanup(), pthread_cond_global_cleanup(), pthread_key_global_cleanup(), and pthread_mutex_global_cleanup().
int pthread_global_init (void)
Definition at line 239 of file pthread.cc.
References MAX_PROCESSES, mc_entry_wou, mc_exit_wou, pthread_barrier_global_init(), pthread_cond_global_init(), pthread_key_global_init(), and pthread_mutex_global_init().
Referenced by kInitKernel().
int pthread_join (pthread_t thread, void ** value_ptr)
Definition at line 158 of file pthread.cc.
References getgpidproc(), getlpid(), pid, and WaitProcess().
int pthread_kill (pthread_t thread, int sig)
Definition at line 224 of file pthread.cc.
References getgpidproc(), getlpid(), pid, and SendSignal().
Referenced by _pthread_cond_signal(), lck_migrate(), and pthread_barrier_wait().
int pthread_local_cleanup (void)
Definition at line 285 of file pthread.cc.
int pthread_local_init (void)
Definition at line 273 of file pthread.cc.
References GetProcID(), HOOK_SCHEDULER, mc_entry_wou, mc_exit_wou, pthread_sch_t::processes, and RegisterHook().
Referenced by kInitKernel().
pthread_t pthread_self (void)
Definition at line 187 of file pthread.cc.
References getgpid().
Referenced by pthread_barrier_wait().
int pthread_thread_cleanup (void)
Definition at line 302 of file pthread.cc.
References pthread_barrier_thread_cleanup(), pthread_cond_thread_cleanup(), pthread_key_thread_cleanup(), and pthread_mutex_thread_cleanup().
Referenced by ProcessEntry().
int pthread_thread_init (void)
Definition at line 289 of file pthread.cc.
References pthread_barrier_thread_init(), pthread_cond_thread_init(), pthread_key_thread_init(), and pthread_mutex_thread_init().
Referenced by ProcessEntry().
int pthread_yield (void)
Definition at line 235 of file pthread.cc.
References Yield().
Variable Documentation
pthread_sch_t pthread_sch [NUM_PROCESSORS] ATTR_DATA_ALIGNED
Definition at line 25 of file pthread.cc.
pthread_mutex_t pthread_sch_lock = PTHREAD_MUTEX_INITIALIZER
Definition at line 24 of file pthread.cc.