Starburst: ipc/rc.cc File Reference
ipc/rc.cc File Reference
#include <rc.h>
#include <lock.h>
#include <sys/api.h>
#include <string.h>
Defines
#define RC_DEBUG(a...)
#define RC_ASSERT(a...)
#define RC_ERR(cmd) do{int res __attribute__((unused))=(cmd);ASSERT(res<=0,"Ring consistency operation failed, got %d",res);}while(0)
#define RC_OBJ2LCK(o) ((void*)(o))
Functions
void rc_entry_x_ (void *obj, size_t objsize)
void rc_exit_x_ (void *obj, size_t objsize)
template<class T >
static void rc_memcpy_aligned (void *&dest, const void *&src, size_t &n, size_t max)
static void * rc_memcpy (void *dest, const void *src, size_t n)
void rc_flush_ (void *obj, size_t objsize, int dest)
static int rc_init ()
Variables
void * _rc_start
Define Documentation
#define RC_ASSERT (a...)
Definition at line 13 of file rc.cc.
Referenced by rc_entry_x_(), rc_exit_x_(), rc_flush_(), and rc_memcpy_aligned().
#define RC_DEBUG (a...)
Definition at line 12 of file rc.cc.
Referenced by rc_entry_x_(), rc_exit_x_(), and rc_flush_().
#define RC_ERR (cmd) do{int res __attribute__((unused))=(cmd);ASSERT(res<=0,"Ring consistency operation failed, got %d",res);}while(0)
Definition at line 16 of file rc.cc.
Referenced by rc_entry_x_(), and rc_exit_x_().
#define RC_OBJ2LCK (o) ((void*)(o))
Definition at line 17 of file rc.cc.
Referenced by rc_entry_x_(), and rc_exit_x_().
Function Documentation
void rc_entry_x_ (void * obj, size_t objsize)
Definition at line 19 of file rc.cc.
References lck_lock_p(), RC_ASSERT, RC_DEBUG, RC_ERR, RC_OBJ2LCK, and RING_CONSISTENCY_EDGE.
void rc_exit_x_ (void * obj, size_t objsize)
Definition at line 25 of file rc.cc.
References lck_unlock(), RC_ASSERT, RC_DEBUG, RC_ERR, RC_OBJ2LCK, and RING_CONSISTENCY_EDGE.
void rc_flush_ (void * obj, size_t objsize, int dest)
Definition at line 54 of file rc.cc.
References GetProcID(), MAKE_NOC_FIFOMEM_PTR, RC_ASSERT, RC_DEBUG, rc_memcpy(), RING_CONSISTENCY_EDGE, and sysconf().
static int rc_init () [static]
Definition at line 67 of file rc.cc.
References _rc_start, GetProcID(), MAKE_NOC_FIFOMEM_PTR, RING_CONSISTENCY_SIZE, and sysconf().
static void* rc_memcpy (void * dest, const void * src, size_t n) [static]
Definition at line 44 of file rc.cc.
Referenced by rc_flush_().
template<class T > static void rc_memcpy_aligned (void *& dest, const void *& src, size_t & n, size_t max) [static]
Definition at line 32 of file rc.cc.
References RC_ASSERT, and PMC_NS::T.
Variable Documentation
void* _rc_start
Referenced by rc_init().