Starburst: include/render/render.h File Reference
include/render/render.h File Reference
#include <stdlib.h>
#include <errno.h>
#include <sys/io.h>
#include <syncevent.h>
#include <sys/api.h>
Data Structures
struct coordinate_t
struct line_t
class poly_t< N >
struct polygon_t
Defines
#define DEBUG_RENDER 0
#define DVI_WIDTH IO_DVI_WIDTH
#define DVI_HEIGHT IO_DVI_HEIGHT
#define RENDER_OK 0
#define RENDER_OUT_OF_MEMORY ENOMEM
#define MAX_POLY_POINTS 64
#define black PIX_CONST(0,0,0)
#define red PIX_CONST(255,0,0)
#define green PIX_CONST(0,255,0)
#define blue PIX_CONST(0,0,255)
#define yellow PIX_CONST(255,255,0)
#define orange PIX_CONST(255,128,0)
#define white PIX_CONST(255,255,255)
#define gray PIX_CONST(128,128,128)
#define purple PIX_CONST(255,0,255)
#define pink PIX_CONST(255,128,255)
#define render_flip_buffer(...) PP_CONCAT(render_flip_buffer_,PP_NARG(__VA_ARGS__))(__VA_ARGS__)
#define render_flip_buffer_0() render_flip_buffer_master()
#define render_flip_buffer_1(xsubdiv) render_flip_buffer_master()
#define render_flip_buffer_2(xsubdiv, ysubdiv)
#define render_flip_buffer_3(xsubdiv, ysubdiv, se_to_master)
#define render_flip_buffer_4(xsubdiv, ysubdiv, se_to_master, se_to_slaves)
#define convert_rgb(r, g, b) ((uint32_t)dvi_color(r,g,b))
#define convert_col(rgb) convert_rgb(((dvi_pixel)(rgb)).r, ((dvi_pixel)(rgb)).g, ((dvi_pixel)(rgb)).b)
#define convert_from_col(raw, rgb) rgb=dvi_color(raw)
#define get_pixel_address(x, y) (&(render_get_buffer()->line[y].col[x]))
#define get_pixel_ptr(x, y) *(get_pixel_address(x,y))
#define set_pixel_rgb(x, y, r, g, b) get_pixel_ptr(x,y) = convert_rgb(r,g,b)
#define set_pixel_col(x, y, rgb) get_pixel_ptr(x,y) = convert_col(rgb)
#define set_pixel_raw(x, y, raw) get_pixel_ptr(x,y) = raw
#define ONSCREEN(x, y) (x >= 0 && x < DVI_WIDTH && y >= 0 && y < DVI_HEIGHT)
#define set_pixel_rgb_safe(x, y, r, g, b) if(ONSCREEN(x,y)) set_pixel_rgb(x,y,r,g,b)
#define set_pixel_col_safe(x, y, rgb) if(ONSCREEN(x,y)) set_pixel_col(x,y,rgb)
#define set_pixel_raw_safe(x, y, raw) if(ONSCREEN(x,y)) set_pixel_raw(x,y,raw)
Typedefs
typedef uint16_t coord_t
typedef dvi_color color_t
Functions
int render_destroy ()
Destroy all data structures and free the used memory for the render routines.
auto_ret< int, 0 > render_init (int use_double_buffer, int xsubdiv=1, int ysubdiv=1)
Initialize memory and pointers for rendering to DVI.
dvi_frame * render_alloc_buf (int count, dvi_frame **bufs) __attribute__((warn_unused_result))
Allocates properly aligned memory for multiple frame buffers.
int render_enable_double_buffering (int use_double_buffer)
When post-init the user feels he should enable/disable double buffering, this function can be used to disable it.
int render_flip_buffer_master (syncevent_t<>::wait_func collect_all=NULL, syncevent_t<>::hit_func signal_slaves=NULL)
Flip a double buffer, to be called by one master.
int render_flip_buffer_slave (syncevent_t<>::hit_func hit=NULL, syncevent_t<>::wait_func wait=NULL)
Flip a double buffer, to be called by all slaves.
int render_show_buffer (int id)
Manual override to show a specific screen buffer regardless of which one is active.
dvi_frame * render_get_buffer (int id=-1)
Returns the pointer to a rendering buffer.
int drawpixel (int x, int y, uint32_t raw, int xsubdiv=-1, int ysubdiv=-1)
Sets a specific pixel to a specific color.
int drawimage (const unsigned int *rawimage, const int width, const int height, const int x_offset, const int y_offset, int xsubdiv=-1, int ysubdiv=-1)
Copies an image to the frame buffer.
int drawline (line_t l, color_t col, int xsubdiv=-1, int ysubdiv=-1)
Draw a line in the currently active screen buffer.
int drawline (coordinate_t p1, coordinate_t p2, color_t col, int xsubdiv=-1, int ysubdiv=-1)
Draw a line in the currently active screen buffer.
int drawline (int x1, int y1, int x2, int y2, color_t col, int xsubdiv=-1, int ysubdiv=-1)
Draw a line in the currently active screen buffer.
int drawline_old (int x1, int y1, int x2, int y2, color_t col) __attribute__((deprecated))
Old method of drawing a line.
int drawrect (int x1, int y1, int x2, int y2, color_t col, int xsubdiv=-1, int ysubdiv=-1)
int fillrect (int x1, int y1, int x2, int y2, color_t col, unsigned char alpha=255, int xsubdiv=-1, int ysubdiv=-1)
Fill a rectangle in the currently active render buffer.
int fillrect (coordinate_t p1, coordinate_t p2, color_t col, unsigned char alpha=255) __attribute__((always_inline))
int drawpolygon (polygon_t &p, color_t col, int xsubdiv=-1, int ysubdiv=-1)
Draws a polygon.
template<unsigned int N>
int drawpolygon (poly_t< N > &p, color_t col, int xsubdiv=-1, int ysubdiv=-1)
int fillpoly (coordinate_t *points, int num_points, color_t col, unsigned char alpha=255, int xsubdiv=-1, int ysubdiv=-1)
Fill a polygon shape with a color.
int fillpoly (polygon_t &p, color_t col, unsigned char alpha=255) __attribute__((always_inline))
template<unsigned int N>
int fillpoly (poly_t< N > &p, color_t col, unsigned char alpha=255)
int drawchar (int x, int y, char c, color_t col, int xsubdiv=-1, int ysubdiv=-1)
Puts a character on the screen.
int drawstring (int x, int y, const char *c, color_t col, int xsubdiv=-1, int ysubdiv=-1)
Puts a string on the screen.
int render_flipnow ()
void render_flush ()
Define Documentation
#define black PIX_CONST(0,0,0)
Definition at line 62 of file render.h.
#define blue PIX_CONST(0,0,255)
Definition at line 65 of file render.h.
Referenced by dvi_color::dvi_color(), and dvi_set_pixel().
#define convert_col (rgb) convert_rgb(((dvi_pixel)(rgb)).r, ((dvi_pixel)(rgb)).g, ((dvi_pixel)(rgb)).b)
Definition at line 138 of file render.h.
Referenced by fillrect().
#define convert_from_col (raw, rgb) rgb=dvi_color(raw)
Definition at line 139 of file render.h.
Referenced by fillrect().
#define convert_rgb (r, g, b) ((uint32_t)dvi_color(r,g,b))
Definition at line 137 of file render.h.
#define DEBUG_RENDER 0
Definition at line 20 of file render.h.
#define DVI_HEIGHT IO_DVI_HEIGHT
Definition at line 24 of file render.h.
Referenced by dvi_screen::ClipBottom(), fillpoly(), dvi_screen::Init(), dvi_screen::IsValidSubdiv(), dvi_screen::OnScreen(), and dvi_screen::RangeY().
#define DVI_WIDTH IO_DVI_WIDTH
Definition at line 23 of file render.h.
Referenced by dvi_screen::ClipRight(), fillpoly(), fillrect(), dvi_screen::Init(), dvi_screen::IsValidSubdiv(), dvi_screen::OnScreen(), and dvi_screen::RangeX().
#define get_pixel_address (x, y) (&(render_get_buffer()->line[y].col[x]))
Definition at line 142 of file render.h.
#define get_pixel_ptr (x, y) *(get_pixel_address(x,y))
Definition at line 143 of file render.h.
#define gray PIX_CONST(128,128,128)
Definition at line 69 of file render.h.
#define green PIX_CONST(0,255,0)
Definition at line 64 of file render.h.
Referenced by dvi_color::dvi_color(), and dvi_set_pixel().
#define MAX_POLY_POINTS 64
Definition at line 31 of file render.h.
Referenced by fillpoly().
#define ONSCREEN (x, y) (x >= 0 && x < DVI_WIDTH && y >= 0 && y < DVI_HEIGHT)
Definition at line 151 of file render.h.
#define orange PIX_CONST(255,128,0)
Definition at line 67 of file render.h.
#define pink PIX_CONST(255,128,255)
Definition at line 71 of file render.h.
#define purple PIX_CONST(255,0,255)
Definition at line 70 of file render.h.
#define red PIX_CONST(255,0,0)
Definition at line 63 of file render.h.
Referenced by dvi_color::dvi_color(), and dvi_set_pixel().
#define render_flip_buffer (...) PP_CONCAT(render_flip_buffer_,PP_NARG(__VA_ARGS__))(__VA_ARGS__)
Definition at line 78 of file render.h.
#define render_flip_buffer_0 () render_flip_buffer_master()
Definition at line 79 of file render.h.
#define render_flip_buffer_1 (xsubdiv) render_flip_buffer_master()
Definition at line 81 of file render.h.
#define render_flip_buffer_2 (xsubdiv, ysubdiv)
Value:
(xsubdiv==-1||ysubdiv==-1||(xsubdiv==0&&ysubdiv==0)? \
    render_flip_buffer_master(): \
    render_flip_buffer_slave())
Definition at line 83 of file render.h.
#define render_flip_buffer_3 (xsubdiv, ysubdiv, se_to_master)
Value:
(xsubdiv==-1||ysubdiv==-1||(xsubdiv==0&&ysubdiv==0)? \
    render_flip_buffer_master(se_wait_static(se_to_master)):\
    render_flip_buffer_slave(se_hit_static(se_to_master)))
Definition at line 87 of file render.h.
#define render_flip_buffer_4 (xsubdiv, ysubdiv, se_to_master, se_to_slaves)
Value:
(xsubdiv==-1||ysubdiv==-1||(xsubdiv==0&&ysubdiv==0)? \
    render_flip_buffer_master(se_wait_static(se_to_master),se_hit_static(se_to_slaves)): \
    render_flip_buffer_slave(se_hit_static(se_to_master),se_wait_static(se_to_slaves)))
Definition at line 91 of file render.h.
#define RENDER_OK 0
Definition at line 27 of file render.h.
#define RENDER_OUT_OF_MEMORY ENOMEM
Definition at line 28 of file render.h.
#define set_pixel_col (x, y, rgb) get_pixel_ptr(x,y) = convert_col(rgb)
Definition at line 147 of file render.h.
#define set_pixel_col_safe (x, y, rgb) if(ONSCREEN(x,y)) set_pixel_col(x,y,rgb)
Definition at line 155 of file render.h.
#define set_pixel_raw (x, y, raw) get_pixel_ptr(x,y) = raw
Definition at line 148 of file render.h.
#define set_pixel_raw_safe (x, y, raw) if(ONSCREEN(x,y)) set_pixel_raw(x,y,raw)
Definition at line 156 of file render.h.
#define set_pixel_rgb (x, y, r, g, b) get_pixel_ptr(x,y) = convert_rgb(r,g,b)
Definition at line 146 of file render.h.
#define set_pixel_rgb_safe (x, y, r, g, b) if(ONSCREEN(x,y)) set_pixel_rgb(x,y,r,g,b)
Definition at line 154 of file render.h.
#define white PIX_CONST(255,255,255)
Definition at line 68 of file render.h.
#define yellow PIX_CONST(255,255,0)
Definition at line 66 of file render.h.
Typedef Documentation
typedef dvi_color color_t
Definition at line 59 of file render.h.
typedef uint16_t coord_t
Definition at line 32 of file render.h.
Function Documentation
int drawchar (int x, int y, char c, color_t col, int xsubdiv, int ysubdiv)
Puts a character on the screen.
Parameters:
x x coordinate of top left corner of character
y y coordinate of top left corner of character
c the character to print
col the color to use
xsubdiv clip to specific x subdiv, set to -1 to overrule
ysubdiv clip to specific y subdiv, set to -1 to overrule
Returns:
0 on success, otherwise an errno
Definition at line 935 of file render.cc.
References imon_font, and REQUIRE_INIT.
Referenced by drawstring().
int drawimage (const unsigned int * rawimage, const int width, const int height, const int x_offset, const int y_offset, int xsubdiv, int ysubdiv)
Copies an image to the frame buffer.
Parameters:
rawimage pointer to the source image
width width of the source
height height of the source
x_offset x coordinate of the destination
y_offset y coordinate of the destination
xsubdiv current x subdiv for clipping, set to -1 to overrule
ysubdiv current y subdiv for clipping, set to -1 to overrule
Returns:
0 on success, otherwise an errno
Definition at line 435 of file render.cc.
References REQUIRE_INIT.
int drawline (line_t l, color_t col, int xsubdiv, int ysubdiv)
Draw a line in the currently active screen buffer.
Parameters:
l line to draw
col color to draw the line with
xsubdiv current x subdiv for clipping, set to -1 to overrule
ysubdiv current y subdiv for clipping, set to -1 to overrule
Returns:
0 on success, otherwise an errno
Definition at line 456 of file render.cc.
References drawline(), line_t::p1, line_t::p2, coordinate_t::x, and coordinate_t::y.
Referenced by drawline(), drawpolygon(), and drawrect().
int drawline (coordinate_t p1, coordinate_t p2, color_t col, int xsubdiv, int ysubdiv)
Draw a line in the currently active screen buffer.
Parameters:
p1 one end of the line
p2 other end of the line
col color to draw the line with
xsubdiv current x subdiv for clipping, set to -1 to overrule
ysubdiv current y subdiv for clipping, set to -1 to overrule
Returns:
0 on success, otherwise an errno
Definition at line 469 of file render.cc.
References drawline(), coordinate_t::x, and coordinate_t::y.
int drawline (int x1, int y1, int x2, int y2, color_t col, int xsubdiv, int ysubdiv)
Draw a line in the currently active screen buffer.
Parameters:
x1 x coordinate of one end of the line
y1 y coordinate of one end of the line
x2 x coordinate of other end of the line
y2 y coordinate of other end of the line
col color to draw the line with
xsubdiv current x subdiv for clipping, set to -1 to overrule
ysubdiv current y subdiv for clipping, set to -1 to overrule
Returns:
0 on success, otherwise an errno
Definition at line 484 of file render.cc.
References IN_WINDOW, REQUIRE_INIT, and dvi_frame::set().
int drawline_old (int x1, int y1, int x2, int y2, color_t col)
Old method of drawing a line.
Deprecated:
Use drawline() instead.
Definition at line 643 of file render.cc.
References REQUIRE_INIT.
int drawpixel (int x, int y, uint32_t raw, int xsubdiv, int ysubdiv)
Sets a specific pixel to a specific color.
Quite slow, it is faster to use render_get_buffer() once and then access the memory directly.
Parameters:
x x coordinate
y y coordinate
raw raw rgb value to write
xsubdiv current x index of the subdiv to write to, set to -1 to overrule
ysubdiv current y index of the subdiv to write to, set to -1 to overrule
Returns:
0 on success, otherwise an errno
Definition at line 418 of file render.cc.
References REQUIRE_INIT.
int drawpolygon (polygon_t & p, color_t col, int xsubdiv, int ysubdiv)
Draws a polygon.
Parameters:
p reference to a polygon
col the color to use for drawing
xsubdiv clip to specific x subdiv, set to -1 to overrule
ysubdiv clip to specific y subdiv, set to -1 to overrule
Returns:
0 on success, otherwise an errno
Definition at line 822 of file render.cc.
References drawline(), polygon_t::num_edges, and polygon_t::points.
template<unsigned int N> int drawpolygon (poly_t< N > & p, color_t col, int xsubdiv = -1, int ysubdiv = -1)
Definition at line 112 of file render.h.
References drawline().
int drawrect (int x1, int y1, int x2, int y2, color_t col, int xsubdiv = -1, int ysubdiv = -1)
Definition at line 691 of file render.cc.
References drawline().
int drawstring (int x, int y, const char * c, color_t col, int xsubdiv, int ysubdiv)
Puts a string on the screen.
Parameters:
x x coordinate of top left corner of character
y y coordinate of top left corner of character
c pointer to the string to print
col the color to use
xsubdiv clip to specific x subdiv, set to -1 to overrule
ysubdiv clip to specific y subdiv, set to -1 to overrule
Returns:
0 on success, otherwise an errno
Definition at line 955 of file render.cc.
References drawchar().
int fillpoly (coordinate_t * points, int num_points, color_t col, unsigned char alpha, int xsubdiv, int ysubdiv)
Fill a polygon shape with a color.
Based on the algorithm at http://alienryderflex.com/polygon/
Parameters:
points a pointer to an array of points
num_points the number of points specified in the point argument
col the color to use for drawing and filling
alpha set to 255 for full opacity, 0 for full transparency or any other value in between
xsubdiv clip to specific x subdiv, set to -1 to overrule
ysubdiv clip to specific y subdiv, set to -1 to overrule
Returns:
0 on success, otherwise an errno
Definition at line 843 of file render.cc.
References dvi_color::b(), DVI_HEIGHT, DVI_WIDTH, dvi_color::g(), dvi_frame::get(), likely, MAX_POLY_POINTS, dvi_color::r(), REQUIRE_INIT, dvi_frame::set(), unlikely, coordinate_t::x, and coordinate_t::y.
Referenced by fillpoly().
int fillpoly (polygon_t & p, color_t col, unsigned char alpha = 255) [inline]
Definition at line 120 of file render.h.
References fillpoly().
template<unsigned int N> int fillpoly (poly_t< N > & p, color_t col, unsigned char alpha = 255)
Definition at line 122 of file render.h.
References fillpoly(), and poly_t< N >::points.
int fillrect (int x1, int y1, int x2, int y2, color_t col, unsigned char alpha, int xsubdiv, int ysubdiv)
Fill a rectangle in the currently active render buffer.
This function has been optimized a bit to be able to fill the complete screen @ 30 fps.
Hint: to get more than 30 fps, fill smaller regions or draw inverse lines instead.
Parameters:
x1 x coordinate of one corner
y1 y coordinate of one corner
x2 x coordinate of opposite corner
y2 y coordinate of opposite corner
col the color to draw and fill the rectangle with
alpha set to 255 for full opacity, 0 for full transparency or any other value in between
xsubdiv clip to specific x subdiv, set to -1 to overrule
ysubdiv clip to specific y subdiv, set to -1 to overrule
Returns:
0 on success, otherwise an errno
Definition at line 713 of file render.cc.
References a, dvi_color::b(), convert_col, convert_from_col, DVI_WIDTH, dvi_color::g(), dvi_frame::get(), likely, dvi_color::r(), REQUIRE_INIT, and unlikely.
Referenced by fillrect().
int fillrect (coordinate_t p1, coordinate_t p2, color_t col, unsigned char alpha = 255) [inline]
Definition at line 109 of file render.h.
References fillrect().
dvi_frame* render_alloc_buf (int count, dvi_frame ** bufs)
Allocates properly aligned memory for multiple frame buffers.
Parameters:
count the number of buffers to allocate
bufs a pointer to a variable that will receive the pointer to the first properly aligned buffer (others can be accessed via (*bufs)[index])
Returns:
the allocated memory that must be freeed afterwards (does not have to be identical to *bufs)
Definition at line 343 of file render.cc.
References smalloc().
Referenced by dvi_screen::Init().
int render_destroy ()
Destroy all data structures and free the used memory for the render routines.
Returns:
0 on success, otherwise an errno
Definition at line 305 of file render.cc.
References mc_flush.
int render_enable_double_buffering (int use_double_buffer)
When post-init the user feels he should enable/disable double buffering, this function can be used to disable it.
Parameters:
use_double_buffer 1 to use double buffers or 0 to use a single buffer.
Returns:
0 on success, otherwise an errno
Definition at line 360 of file render.cc.
References REQUIRE_INIT.
int render_flip_buffer_master (syncevent_t<>::wait_func collect_all, syncevent_t<>::hit_func signal_slaves)
Flip a double buffer, to be called by one master.
A wrapper macro render_flip_buffer(int xsubdiv,int ysubdiv,syncevent_t master,syncevent_t slaves) is also defined and probably easier to use.
Parameters:
collect_all a syncevent to wait upon until all slaves call render_flip_buffer_slave(), set to NULL to skip waiting
signal_slaves a syncevent to hit such that all slaves can continue, set to NULL to skip signalling
Returns:
0 on success, otherwise an errno
Definition at line 372 of file render.cc.
References REQUIRE_INIT.
int render_flip_buffer_slave (syncevent_t<>::hit_func hit, syncevent_t<>::wait_func wait)
Flip a double buffer, to be called by all slaves.
A wrapper macro render_flip_buffer(int xsubdiv,int ysubdiv,syncevent_t master,syncevent_t slaves) is also defined and probably easier to use.
Parameters:
hit a syncevent to hit in order to signal the master that this slave is finished rendering, set to NULL to skip signalling
wait a syncevent to wait in order to block until the buffer has actually flipped, set to NULL to skip waiting
Returns:
0 on success, otherwise an errno
Definition at line 384 of file render.cc.
References REQUIRE_INIT.
int render_flipnow ()
Definition at line 292 of file render.cc.
References REQUIRE_INIT.
void render_flush ()
Definition at line 315 of file render.cc.
References mc_flush.
dvi_frame* render_get_buffer (int id)
Returns the pointer to a rendering buffer.
Parameters:
id the id to retrieve, set to -1 to get the current buffer that can be used for rendering
Returns:
the pointer to the requested buffer, or NULL on an error
Definition at line 404 of file render.cc.
auto_ret<int,0> render_init (int use_double_buffer, int xsubdiv, int ysubdiv)
Initialize memory and pointers for rendering to DVI.
Parameters:
use_double_buffer When non-zero, double buffering is used: after drawing you will need to flip the active and render buffers.
xsubdiv number of subdivisions of x axis
ysubdiv number of subdivisions of y axis
Returns:
0 on success, otherwise an errno
Definition at line 328 of file render.cc.
References mc_flush.
int render_show_buffer (int id)
Manual override to show a specific screen buffer regardless of which one is active.
Parameters:
id the index of the buffer to display
Returns:
0 on success, otherwise an errno
Definition at line 394 of file render.cc.
References REQUIRE_INIT.