Starburst: io/render.cc File Reference
io/render.cc File Reference
#include <stdlib.h>
#include <sys/io.h>
#include <render/render.h>
#include <render/imon_font.h>
#include <mc.h>
#include <syncevent.h>
#include <fixed.h>
Data Structures
class dvi_screen
Low-level access to DVI.
Defines
#define REQUIRE_INIT(...) do{if(unlikely(!screen))return EINVAL;}while(0)
#define max(i, j) ((i>j) ? i : j)
#define min(i, j) ((i<j) ? i : j)
Enumerations
enum range_t {
BEFORE_SCREEN = -2, BEFORE_WINDOW = -1, IN_WINDOW = 0, AFTER_WINDOW = 1,
AFTER_SCREEN = 2
}
Position of a point with respect to current subdiv/screen.
Functions
int render_flipnow ()
int render_destroy ()
Destroy all data structures and free the used memory for the render routines.
void render_flush ()
auto_ret< int, 0 > render_init (int use_double_buffer, int xsubdiv, int ysubdiv)
Initialize memory and pointers for rendering to DVI.
dvi_frame * render_alloc_buf (int count, dvi_frame **bufs)
Allocates properly aligned memory for multiple frame buffers.
int render_enable_double_buffering (int use_double_buffer)
When post-init the user feels he should enable/disable double buffering, this function can be used to disable it.
int render_flip_buffer_master (syncevent_t<>::wait_func collect_all, syncevent_t<>::hit_func signal_slaves)
Flip a double buffer, to be called by one master.
int render_flip_buffer_slave (syncevent_t<>::hit_func hit, syncevent_t<>::wait_func wait)
Flip a double buffer, to be called by all slaves.
int render_show_buffer (int id)
Manual override to show a specific screen buffer regardless of which one is active.
dvi_frame * render_get_buffer (int id)
Returns the pointer to a rendering buffer.
int drawpixel (int x, int y, uint32_t raw, int xsubdiv, int ysubdiv)
Sets a specific pixel to a specific color.
int drawimage (const unsigned int *rawimage, const int width, const int height, const int x_offset, const int y_offset, int xsubdiv, int ysubdiv)
Copies an image to the frame buffer.
int drawline (line_t l, color_t col, int xsubdiv, int ysubdiv)
Draw a line in the currently active screen buffer.
int drawline (coordinate_t p1, coordinate_t p2, color_t col, int xsubdiv, int ysubdiv)
Draw a line in the currently active screen buffer.
int drawline (int x1, int y1, int x2, int y2, color_t col, int xsubdiv, int ysubdiv)
Draw a line in the currently active screen buffer.
int drawline_old (int x1, int y1, int x2, int y2, color_t col)
Old method of drawing a line.
int drawrect (int x1, int y1, int x2, int y2, color_t col, int xsubdiv, int ysubdiv)
int fillrect (int x1, int y1, int x2, int y2, color_t col, unsigned char alpha, int xsubdiv, int ysubdiv)
Fill a rectangle in the currently active render buffer.
int drawpolygon (polygon_t &p, color_t col, int xsubdiv, int ysubdiv)
Draws a polygon.
int fillpoly (coordinate_t *points, int num_points, color_t col, unsigned char alpha, int xsubdiv, int ysubdiv)
Fill a polygon shape with a color.
int drawchar (int x, int y, char c, color_t col, int xsubdiv, int ysubdiv)
Puts a character on the screen.
int drawstring (int x, int y, const char *c, color_t col, int xsubdiv, int ysubdiv)
Puts a string on the screen.
Variables
static dvi_screen *screen ATTR_DATA_ALIGNED
Pointer to single screen, initialized by render_init().
Detailed Description
2D render library for the XPS DVI interface as exposed in the NEST platform.
This library uses screen subdivisions (or subdivs for short). This means that multiple threads can be used to render a subdiv of the screen. All functions have a xsubdiv and ysubdiv parameter, which indicate which subdiv is intended to use. When set, a thread cannot write outside of its subdiv; all images are clipped. When either is set to -1, clipping is overruled.
Created on: May 13, 2011 Author: Berend Dekens <b.h.j.dekens@utwente.nl> Version: 2
History: 2:
Complete rewrite. 1.2:
Added support for memory consistency and fully cached external memory
Added rectangle fill mode with alpha transparency support 1.1:
Fixed a bug in the fillrect where too many pixels are drawn in the horizontal direction on non-multiples of 32 pixels in width
Added a raw image drawing routine and a raw pixel drawing function 1.0:
Feature complete for the visual spectrum analyser
Definition in file render.cc.
Define Documentation
#define max (i, j) ((i>j) ? i : j)
Definition at line 298 of file render.cc.
#define min (i, j) ((i<j) ? i : j)
Definition at line 299 of file render.cc.
#define REQUIRE_INIT (...) do{if(unlikely(!screen))return EINVAL;}while(0)
Definition at line 36 of file render.cc.
Referenced by drawchar(), drawimage(), drawline(), drawline_old(), drawpixel(), fillpoly(), fillrect(), render_enable_double_buffering(), render_flip_buffer_master(), render_flip_buffer_slave(), render_flipnow(), and render_show_buffer().
Enumeration Type Documentation
enum range_t
Position of a point with respect to current subdiv/screen.
Enumerator:
BEFORE_SCREEN
BEFORE_WINDOW
IN_WINDOW
AFTER_WINDOW
AFTER_SCREEN
Definition at line 39 of file render.cc.
Function Documentation
int drawchar (int x, int y, char c, color_t col, int xsubdiv, int ysubdiv)
Puts a character on the screen.
Parameters:
x x coordinate of top left corner of character
y y coordinate of top left corner of character
c the character to print
col the color to use
xsubdiv clip to specific x subdiv, set to -1 to overrule
ysubdiv clip to specific y subdiv, set to -1 to overrule
Returns:
0 on success, otherwise an errno
Definition at line 935 of file render.cc.
References imon_font, and REQUIRE_INIT.
Referenced by drawstring().
int drawimage (const unsigned int * rawimage, const int width, const int height, const int x_offset, const int y_offset, int xsubdiv, int ysubdiv)
Copies an image to the frame buffer.
Parameters:
rawimage pointer to the source image
width width of the source
height height of the source
x_offset x coordinate of the destination
y_offset y coordinate of the destination
xsubdiv current x subdiv for clipping, set to -1 to overrule
ysubdiv current y subdiv for clipping, set to -1 to overrule
Returns:
0 on success, otherwise an errno
Definition at line 435 of file render.cc.
References REQUIRE_INIT.
int drawline (line_t l, color_t col, int xsubdiv, int ysubdiv)
Draw a line in the currently active screen buffer.
Parameters:
l line to draw
col color to draw the line with
xsubdiv current x subdiv for clipping, set to -1 to overrule
ysubdiv current y subdiv for clipping, set to -1 to overrule
Returns:
0 on success, otherwise an errno
Definition at line 456 of file render.cc.
References drawline(), line_t::p1, line_t::p2, coordinate_t::x, and coordinate_t::y.
Referenced by drawline(), drawpolygon(), and drawrect().
int drawline (coordinate_t p1, coordinate_t p2, color_t col, int xsubdiv, int ysubdiv)
Draw a line in the currently active screen buffer.
Parameters:
p1 one end of the line
p2 other end of the line
col color to draw the line with
xsubdiv current x subdiv for clipping, set to -1 to overrule
ysubdiv current y subdiv for clipping, set to -1 to overrule
Returns:
0 on success, otherwise an errno
Definition at line 469 of file render.cc.
References drawline(), coordinate_t::x, and coordinate_t::y.
int drawline (int x1, int y1, int x2, int y2, color_t col, int xsubdiv, int ysubdiv)
Draw a line in the currently active screen buffer.
Parameters:
x1 x coordinate of one end of the line
y1 y coordinate of one end of the line
x2 x coordinate of other end of the line
y2 y coordinate of other end of the line
col color to draw the line with
xsubdiv current x subdiv for clipping, set to -1 to overrule
ysubdiv current y subdiv for clipping, set to -1 to overrule
Returns:
0 on success, otherwise an errno
Definition at line 484 of file render.cc.
References IN_WINDOW, REQUIRE_INIT, and dvi_frame::set().
int drawline_old (int x1, int y1, int x2, int y2, color_t col)
Old method of drawing a line.
Deprecated:
Use drawline() instead.
Definition at line 643 of file render.cc.
References REQUIRE_INIT.
int drawpixel (int x, int y, uint32_t raw, int xsubdiv, int ysubdiv)
Sets a specific pixel to a specific color.
Quite slow, it is faster to use render_get_buffer() once and then access the memory directly.
Parameters:
x x coordinate
y y coordinate
raw raw rgb value to write
xsubdiv current x index of the subdiv to write to, set to -1 to overrule
ysubdiv current y index of the subdiv to write to, set to -1 to overrule
Returns:
0 on success, otherwise an errno
Definition at line 418 of file render.cc.
References REQUIRE_INIT.
int drawpolygon (polygon_t & p, color_t col, int xsubdiv, int ysubdiv)
Draws a polygon.
Parameters:
p reference to a polygon
col the color to use for drawing
xsubdiv clip to specific x subdiv, set to -1 to overrule
ysubdiv clip to specific y subdiv, set to -1 to overrule
Returns:
0 on success, otherwise an errno
Definition at line 822 of file render.cc.
References drawline(), polygon_t::num_edges, and polygon_t::points.
int drawrect (int x1, int y1, int x2, int y2, color_t col, int xsubdiv, int ysubdiv)
Definition at line 691 of file render.cc.
References drawline().
int drawstring (int x, int y, const char * c, color_t col, int xsubdiv, int ysubdiv)
Puts a string on the screen.
Parameters:
x x coordinate of top left corner of character
y y coordinate of top left corner of character
c pointer to the string to print
col the color to use
xsubdiv clip to specific x subdiv, set to -1 to overrule
ysubdiv clip to specific y subdiv, set to -1 to overrule
Returns:
0 on success, otherwise an errno
Definition at line 955 of file render.cc.
References drawchar().
int fillpoly (coordinate_t * points, int num_points, color_t col, unsigned char alpha, int xsubdiv, int ysubdiv)
Fill a polygon shape with a color.
Based on the algorithm at http://alienryderflex.com/polygon/
Parameters:
points a pointer to an array of points
num_points the number of points specified in the point argument
col the color to use for drawing and filling
alpha set to 255 for full opacity, 0 for full transparency or any other value in between
xsubdiv clip to specific x subdiv, set to -1 to overrule
ysubdiv clip to specific y subdiv, set to -1 to overrule
Returns:
0 on success, otherwise an errno
Definition at line 843 of file render.cc.
References dvi_color::b(), DVI_HEIGHT, DVI_WIDTH, dvi_color::g(), dvi_frame::get(), likely, MAX_POLY_POINTS, dvi_color::r(), REQUIRE_INIT, dvi_frame::set(), unlikely, coordinate_t::x, and coordinate_t::y.
Referenced by fillpoly().
int fillrect (int x1, int y1, int x2, int y2, color_t col, unsigned char alpha, int xsubdiv, int ysubdiv)
Fill a rectangle in the currently active render buffer.
This function has been optimized a bit to be able to fill the complete screen @ 30 fps.
Hint: to get more than 30 fps, fill smaller regions or draw inverse lines instead.
Parameters:
x1 x coordinate of one corner
y1 y coordinate of one corner
x2 x coordinate of opposite corner
y2 y coordinate of opposite corner
col the color to draw and fill the rectangle with
alpha set to 255 for full opacity, 0 for full transparency or any other value in between
xsubdiv clip to specific x subdiv, set to -1 to overrule
ysubdiv clip to specific y subdiv, set to -1 to overrule
Returns:
0 on success, otherwise an errno
Definition at line 713 of file render.cc.
References a, dvi_color::b(), convert_col, convert_from_col, DVI_WIDTH, dvi_color::g(), dvi_frame::get(), likely, dvi_color::r(), REQUIRE_INIT, and unlikely.
Referenced by fillrect().
dvi_frame* render_alloc_buf (int count, dvi_frame ** bufs)
Allocates properly aligned memory for multiple frame buffers.
Parameters:
count the number of buffers to allocate
bufs a pointer to a variable that will receive the pointer to the first properly aligned buffer (others can be accessed via (*bufs)[index])
Returns:
the allocated memory that must be freeed afterwards (does not have to be identical to *bufs)
Definition at line 343 of file render.cc.
References smalloc().
Referenced by dvi_screen::Init().
int render_destroy ()
Destroy all data structures and free the used memory for the render routines.
Returns:
0 on success, otherwise an errno
Definition at line 305 of file render.cc.
References mc_flush.
int render_enable_double_buffering (int use_double_buffer)
When post-init the user feels he should enable/disable double buffering, this function can be used to disable it.
Parameters:
use_double_buffer 1 to use double buffers or 0 to use a single buffer.
Returns:
0 on success, otherwise an errno
Definition at line 360 of file render.cc.
References REQUIRE_INIT.
int render_flip_buffer_master (syncevent_t<>::wait_func collect_all, syncevent_t<>::hit_func signal_slaves)
Flip a double buffer, to be called by one master.
A wrapper macro render_flip_buffer(int xsubdiv,int ysubdiv,syncevent_t master,syncevent_t slaves) is also defined and probably easier to use.
Parameters:
collect_all a syncevent to wait upon until all slaves call render_flip_buffer_slave(), set to NULL to skip waiting
signal_slaves a syncevent to hit such that all slaves can continue, set to NULL to skip signalling
Returns:
0 on success, otherwise an errno
Definition at line 372 of file render.cc.
References REQUIRE_INIT.
int render_flip_buffer_slave (syncevent_t<>::hit_func hit, syncevent_t<>::wait_func wait)
Flip a double buffer, to be called by all slaves.
A wrapper macro render_flip_buffer(int xsubdiv,int ysubdiv,syncevent_t master,syncevent_t slaves) is also defined and probably easier to use.
Parameters:
hit a syncevent to hit in order to signal the master that this slave is finished rendering, set to NULL to skip signalling
wait a syncevent to wait in order to block until the buffer has actually flipped, set to NULL to skip waiting
Returns:
0 on success, otherwise an errno
Definition at line 384 of file render.cc.
References REQUIRE_INIT.
int render_flipnow ()
Definition at line 292 of file render.cc.
References REQUIRE_INIT.
void render_flush ()
Definition at line 315 of file render.cc.
References mc_flush.
dvi_frame* render_get_buffer (int id)
Returns the pointer to a rendering buffer.
Parameters:
id the id to retrieve, set to -1 to get the current buffer that can be used for rendering
Returns:
the pointer to the requested buffer, or NULL on an error
Definition at line 404 of file render.cc.
auto_ret<int,0> render_init (int use_double_buffer, int xsubdiv, int ysubdiv)
Initialize memory and pointers for rendering to DVI.
Parameters:
use_double_buffer When non-zero, double buffering is used: after drawing you will need to flip the active and render buffers.
xsubdiv number of subdivisions of x axis
ysubdiv number of subdivisions of y axis
Returns:
0 on success, otherwise an errno
Definition at line 328 of file render.cc.
References mc_flush.
int render_show_buffer (int id)
Manual override to show a specific screen buffer regardless of which one is active.
Parameters:
id the index of the buffer to display
Returns:
0 on success, otherwise an errno
Definition at line 394 of file render.cc.
References REQUIRE_INIT.
Variable Documentation
dvi_screen* screen ATTR_DATA_ALIGNED [static]
Pointer to single screen, initialized by render_init().
Definition at line 290 of file render.cc.