Starburst: include/sys/resource.h File Reference
include/sys/resource.h File Reference
#include <sys/time.h>
Data Structures
struct rusage
Defines
#define RUSAGE_SELF 0
#define RUSAGE_CHILDREN 1
#define RUSAGE_THREAD 2
Functions
int getrusage (int who, struct rusage *usage)
Define Documentation
#define RUSAGE_CHILDREN 1
Definition at line 7 of file resource.h.
Referenced by getrusage().
#define RUSAGE_SELF 0
Definition at line 6 of file resource.h.
Referenced by getrusage().
#define RUSAGE_THREAD 2
Definition at line 8 of file resource.h.
Referenced by clock_gettime(), and getrusage().
Function Documentation
int getrusage (int who, struct rusage * usage)
Definition at line 31 of file resource.cc.
References _getrusage(), getpid(), RUSAGE_CHILDREN, RUSAGE_SELF, and RUSAGE_THREAD.
Referenced by clock_gettime().