Starburst: kernel/resource.cc File Reference
kernel/resource.cc File Reference
#include <sys/api.h>
#include <sys/resource.h>
#include <string.h>
#include <errno.h>
#include <sys/times.h>
#include <sys/time.h>
#include <unistd.h>
Functions
int _getrusage (pid_t pid, struct rusage *rusage)
int getrusage (int who, struct rusage *usage)
clock_t times (struct tms *buf)
Function Documentation
int _getrusage (pid_t pid, struct rusage * rusage)
Definition at line 14 of file resource.cc.
References proc_stats_t::context_switches, GetProcessStats(), proc_stats_t::min_stack, rusage::ru_isrss, rusage::ru_nivcsw, rusage::ru_nvcsw, rusage::ru_utime, proc_stats_t::slice_used, and proc_stats_t::yields.
Referenced by getrusage().
int getrusage (int who, struct rusage * usage)
Definition at line 31 of file resource.cc.
References _getrusage(), getpid(), RUSAGE_CHILDREN, RUSAGE_SELF, and RUSAGE_THREAD.
Referenced by clock_gettime().
clock_t times (struct tms * buf)
Definition at line 53 of file resource.cc.
References freq, getpid(), GetProcessStats(), gettimeofday(), proc_stats_t::slice_used, and sysconf().