Starburst: include/sched.h File Reference
include/sched.h File Reference
Defines
#define sched_yield Yield
Functions
int Yield (void)
Define Documentation
#define sched_yield Yield
Definition at line 6 of file sched.h.
Function Documentation
int Yield (void)
Referenced by _pthread_cond_wait(), PMC_NS::SCBackend< T >::acquire(), mfifo_t< T, FIFO_READERS, FIFO_SIZE_BITS, B >::acquire_elem(), acquireDataCB(), acquireDataCBOL(), acquireDataPositionCBOL(), acquireSpaceCB(), acquireSpaceCBO(), PMC_NS::FifoMemPool< Tsa, N, B >::alloc(), dBootKernels(), DefaultTaskDaemon(), WorkQueue< T, W >::DispatchWork(), PMC_NS::FifoMemPool< Tsa, N, B >::front(), mfifo_t< T, FIFO_READERS, FIFO_SIZE_BITS, B >::front_elem(), syncevent_t< N >::hit(), IssueMallocRequest(), linfs_close(), linfs_lseek(), linfs_open(), linfs_read(), linfs_register(), linfs_write(), llck(), lock(), MailRead(), MallocDaemonHandler(), ProfilerDaemon(), pthread_yield(), readFifo(), WorkQueue< T, W >::RunDispatcher(), ShutdownDaemon(), PMC_NS::SACallback::throw(), TimerDaemon(), usleep(), WFifo< T >::wait(), RFifo< T >::wait(), WaitForResult(), WaitProcess(), WaitProcessDaemon(), and writeFifo().