Starburst: daemons/ShutdownDaemon.cc File Reference
daemons/ShutdownDaemon.cc File Reference
Daemons
Implementation of a gracefull shutdown daemon.
#include <sys/syscall.h>
#include <daemons.h>
#include <stdio.h>
#include <errno.h>
#include <sys/helix_config.h>
#include <sys/types.h>
#include <unistd.h>
#include <sys/signal.h>
#include <linfs.h>
Defines
#define DEBUG(...)
Functions
void do_gracefull_exit_funs ()
Function to cleanup process stuff, called by abort() and exit() (via atexit()).
void set_no_gracefull_exit ()
Prevents the calling process to be killed by the ShutdownDaemon on reboot.
static void ForceShutdown ()
static int ShutdownDaemonInit ()
static void * ShutdownDaemon (void *arg)
The process that sends all processes SIGTERM and joins them afterwards.
int StartShutdownDaemon ()
Starts the ShutdownDaemon to gracefully shutdown the kernel.
Variables
static pthread_barrier_t shutdown_bar = PTHREAD_BARRIER_INITIALIZER
Detailed Description
Implementation of a gracefull shutdown daemon.
It will send all processes SIGTERM. Since critical daemons like MallocDaemon and TimerDaemon do not require cleanup operations and are required for further shutdown sequence, these daemons block SIGTERM and remaing running. All other processes will (by default) terminate via abort(), which will call eventually do_gracefull_exit_funs().
When all processes finished handling the SIGTERM, the kShutdown() syscall will be executed. Even when processes fail to terminate, the kShutdown() will be called after 30 seconds (when timers are supported), regardless of the state of the system.
Definition in file ShutdownDaemon.cc.
Define Documentation
#define DEBUG (...)
Definition at line 29 of file ShutdownDaemon.cc.
Referenced by ForceShutdown(), set_no_gracefull_exit(), ShutdownDaemon(), and StartShutdownDaemon().
Function Documentation
void do_gracefull_exit_funs ()
Function to cleanup process stuff, called by abort() and exit() (via atexit()).
Definition at line 34 of file ShutdownDaemon.cc.
References linfs_close_all().
Referenced by ProcessEntry().
static void ForceShutdown () [static]
Definition at line 55 of file ShutdownDaemon.cc.
References DEBUG, dRemoteCall(), GetProcID(), GetSoCCores(), MAKE_NOC_FIFOMEM_PTR, open(), Shutdown(), and usleep().
Referenced by ShutdownDaemon().
void set_no_gracefull_exit ()
Prevents the calling process to be killed by the ShutdownDaemon on reboot.
SIGTERM will be masked.
Only critical daemons that do not require system-wide cleanup functions should call this.
Definition at line 46 of file ShutdownDaemon.cc.
References DEBUG, MaskSignal(), SIG_BLOCK, sigaddset(), sigemptyset(), and SIGTERM.
Referenced by MallocDaemon(), ShutdownDaemon(), TimerDaemon(), and TraceDump().
static void* ShutdownDaemon (void * arg) [static]
The process that sends all processes SIGTERM and joins them afterwards.
When all processes either blocked SIGTERM or are joined, the kShutdown() syscall is executed.
Parameters:
arg ignored
Returns:
never
Definition at line 83 of file ShutdownDaemon.cc.
References __attribute__, DEBUG, ESUCCESS, ForceShutdown(), GetProcessFlags(), GetProcID(), lJoinProcess(), MAX_PROCESSES, pid, PROC_FLAG_DETACHED, PROC_FLAG_JOINABLE, pthread_barrier_wait(), SendSignal(), set_no_gracefull_exit(), SetProcessFlags(), SIGTERM, timer_repeat(), usleep(), and Yield().
Referenced by StartShutdownDaemon().
static int ShutdownDaemonInit () [static]
Definition at line 72 of file ShutdownDaemon.cc.
References GetSoCCores(), and pthread_barrier_init().
Variable Documentation
pthread_barrier_t shutdown_bar = PTHREAD_BARRIER_INITIALIZER [static]
Definition at line 70 of file ShutdownDaemon.cc.