Starburst: include/helios/SlidingBuffer.h File Reference
include/helios/SlidingBuffer.h File Reference
#include <inttypes.h>
#include "info_app.h"
Defines
#define CONSUMERS 1
#define PRODUCERS 0
#define NUM_TASKS 16 /*It is designed to have a maximum of 16 tasks */
#define COUNTVAL(a) ((a)&0x7fffffff)
Functions
void initWindowCB (volatile Info_Window *, int windowid)
volatile Info_CB * createCB (volatile Info_App *infoApp, uint32_t tokensize, uint32_t buffersize, uint32_t nReadWin, uint32_t nWriteWin, uint32_t id)
volatile Info_CB * createRingCB (volatile Info_App *infoApp, uint32_t tokensize, uint32_t buffersize, uint32_t nReadWin, uint32_t nWriteWin, uint32_t id)
volatile Info_CB * createRingOptCB (volatile Info_App *infoApp, uint32_t tokensize, uint32_t buffersize, uint32_t nReadWin, uint32_t nWriteWin, uint32_t id)
volatile Info_App * findApp (void)
volatile Info_CBSliding * findInfoFromAppCB (volatile Info_App *appInfoPtr, int bufferid)
uint32_t getBufferSizeCB (volatile Info_CBSliding *ptrCB)
volatile Info_CBSliding * openCB (int bufferid, int windowid, volatile Info_Window **window_out)
void acquireSpaceCB (volatile Info_CBSliding *ptrCB, volatile Info_Window *wp)
void acquireSpaceCBBlock (volatile Info_CBSliding *ptrCB, volatile Info_Window *wp, uint32_t n)
void * getWriteAddressCB (volatile Info_CBSliding *ptrCB, int l)
void writeCB (volatile Info_CBSliding *ptrCB, void *c, int l)
void releaseDataCB (volatile Info_CBSliding *ptrCB, volatile Info_Window *wp)
void releaseDataCBBlock (volatile Info_CBSliding *ptrCB, volatile Info_Window *wp, uint32_t n)
void acquireDataCB (volatile Info_CBSliding *ptrCB, volatile Info_Window *wp)
void acquireDataCBBlock (volatile Info_CBSliding *ptrCB, volatile Info_Window *wp, uint32_t n)
void * getReadAddressCB (volatile Info_CBSliding *ptrCB, int l)
void readCB (volatile Info_CBSliding *ptrCB, void *c, int l)
Read the value at location l and return it.
void releaseSpaceCB (volatile Info_CBSliding *ptrCB, volatile Info_Window *wp)
void releaseSpaceCBBlock (volatile Info_CBSliding *ptrCB, volatile Info_Window *wp, uint32_t n)
void readStreamCB (volatile Info_CBSliding *ptrCB, void *c, int l, int startloc)
void writeStreamCB (volatile Info_CBSliding *ptrCB, void *c, int l, int startloc)
void lockCB (int lockid, int id)
void unlockCB (int lockid, int id)
void myYield (void)
volatile RingBufferOptStruct * openReadRingOptCB (int bufferid, int windowid, volatile RingBufferPointers **rbp)
volatile RingBufferOptStruct * openReadRingOptCB2 (int bufferid, int windowid, volatile RingBufferPointers **rbp, volatile RingBufferOptStruct *out)
volatile RingBufferOptStruct * openWriteRingOptCB (int bufferid, int windowid, volatile RingBufferPointers **rbp)
volatile RingBufferOptStruct * openWriteRingOptCB2 (int bufferid, int windowid, volatile RingBufferPointers **rbp, volatile RingBufferOptStruct *out)
void acquireDataRingOptCB (volatile RingBufferOptStruct *ringbuffer, volatile RingBufferPointers *rbp)
void acquireSpaceRingOptCB (volatile RingBufferOptStruct *ringbuffer, volatile RingBufferPointers *rbp)
void releaseDataRingOptCB (volatile RingBufferOptStruct *ringbuffer, volatile RingBufferPointers *rbp)
void releaseSpaceRingOptCB (volatile RingBufferOptStruct *ringbuffer, volatile RingBufferPointers *rbp)
void * getReadAddressRingOptCB (volatile RingBufferOptStruct *ringbuffer, int dummy)
void * getWriteAddressRingOptCB (volatile RingBufferOptStruct *ringbuffer, int dummy)
void writeRingOptCB (volatile RingBufferOptStruct *ringbuffer, void *c, int dummy)
void readRingOptCB (volatile RingBufferOptStruct *ringbuffer, void *c, int dummy)
volatile RingBufferStruct * openReadRingCB (int bufferid, int windowid, volatile RingBufferPointers **rbp)
volatile RingBufferStruct * openReadRingCB2 (int bufferid, int windowid, volatile RingBufferPointers **rbp, volatile RingBufferStruct *out)
volatile RingBufferStruct * openWriteRingCB (int bufferid, int windowid, volatile RingBufferPointers **rbp)
volatile RingBufferStruct * openWriteRingCB2 (int bufferid, int windowid, volatile RingBufferPointers **rbp, volatile RingBufferStruct *out)
void acquireDataRingCB (volatile RingBufferStruct *ringbuffer, volatile RingBufferPointers *rbp)
void acquireSpaceRingCB (volatile RingBufferStruct *ringbuffer, volatile RingBufferPointers *rbp)
void releaseDataRingCB (volatile RingBufferStruct *ringbuffer, volatile RingBufferPointers *rbp)
void releaseSpaceRingCB (volatile RingBufferStruct *ringbuffer, volatile RingBufferPointers *rbp)
void * getReadAddressRingCB (volatile RingBufferStruct *ringbuffer, int dummy)
void * getWriteAddressRingCB (volatile RingBufferStruct *ringbuffer, int dummy)
void writeRingCB (volatile RingBufferStruct *ringbuffer, void *c, int dummy)
void readRingCB (volatile RingBufferStruct *ringbuffer, void *c, int dummy)
Define Documentation
#define CONSUMERS 1
Definition at line 11 of file SlidingBuffer.h.
#define COUNTVAL (a) ((a)&0x7fffffff)
Definition at line 18 of file SlidingBuffer.h.
#define NUM_TASKS 16 /*It is designed to have a maximum of 16 tasks */
Definition at line 16 of file SlidingBuffer.h.
Referenced by findApp().
#define PRODUCERS 0
Definition at line 12 of file SlidingBuffer.h.
Function Documentation
void acquireDataCB (volatile Info_CBSliding * ptrCB, volatile Info_Window * wp)
Definition at line 476 of file SlidingBuffer.cc.
References Info_CBSliding::buffer_size, buffer_size, COUNTVAL, FLIP_WRAP, Info_Window::headptr, Info_Window::id, Info_CBSliding::nWriteWin, SET_WRAP_COUNT, Info_Window::tailptr, WRAPVAL, Info_CBSliding::writewindowinfo, and Yield().
Referenced by readFifoCB().
void acquireDataCBBlock (volatile Info_CBSliding * ptrCB, volatile Info_Window * wp, uint32_t n)
void acquireDataRingCB (volatile RingBufferStruct * ringbuffer, volatile RingBufferPointers * rbp)
void acquireDataRingOptCB (volatile RingBufferOptStruct * ringbuffer, volatile RingBufferPointers * rbp)
void acquireSpaceCB (volatile Info_CBSliding * ptrCB, volatile Info_Window * wp)
Definition at line 420 of file SlidingBuffer.cc.
References Info_CBSliding::buffer_size, buffer_size, COUNTVAL, FLIP_WRAP, Info_Window::headptr, Info_Window::id, Info_CBSliding::nReadWin, Info_CBSliding::readwindowinfo, SET_WRAP_COUNT, Info_Window::tailptr, WRAPVAL, and Yield().
Referenced by writeFifoCB().
void acquireSpaceCBBlock (volatile Info_CBSliding * ptrCB, volatile Info_Window * wp, uint32_t n)
void acquireSpaceRingCB (volatile RingBufferStruct * ringbuffer, volatile RingBufferPointers * rbp)
void acquireSpaceRingOptCB (volatile RingBufferOptStruct * ringbuffer, volatile RingBufferPointers * rbp)
volatile Info_CB* createCB (volatile Info_App * infoApp, uint32_t tokensize, uint32_t buffersize, uint32_t nReadWin, uint32_t nWriteWin, uint32_t id)
Definition at line 53 of file SlidingBuffer.cc.
References CB_SLIDING_WINDOWS, Info_App_s::cbList, data, Info_CB::data, Info_FIFO::id, Info_CB::id, initWindowCB(), Info_CB::next, Info_CBSliding::nReadWin, nReadWin, Info_CBSliding::nWriteWin, nWriteWin, smalloc(), and Info_CB::type.
volatile Info_CB* createRingCB (volatile Info_App * infoApp, uint32_t tokensize, uint32_t buffersize, uint32_t nReadWin, uint32_t nWriteWin, uint32_t id)
Definition at line 26 of file SlidingBuffer.cc.
References Info_App_s::cbList.
volatile Info_CB* createRingOptCB (volatile Info_App * infoApp, uint32_t tokensize, uint32_t buffersize, uint32_t nReadWin, uint32_t nWriteWin, uint32_t id)
Definition at line 37 of file SlidingBuffer.cc.
References Info_App_s::cbList.
volatile Info_App* findApp (void)
Definition at line 228 of file SlidingBuffer.cc.
References getpid(), GetProcID(), and NUM_TASKS.
Referenced by openCB(), openReadCB(), and openWriteCB().
volatile Info_CBSliding* findInfoFromAppCB (volatile Info_App * appInfoPtr, int bufferid)
Definition at line 201 of file SlidingBuffer.cc.
References Info_App_s::cbList.
uint32_t getBufferSizeCB (volatile Info_CBSliding * ptrCB)
Definition at line 252 of file SlidingBuffer.cc.
References Info_CBSliding::buffer_size.
void* getReadAddressCB (volatile Info_CBSliding * ptrCB, int l)
Definition at line 336 of file SlidingBuffer.cc.
References Info_CBSliding::buffer_size, Info_CBSliding::data, invalidateDCache(), and Info_CBSliding::token_size.
void* getReadAddressRingCB (volatile RingBufferStruct * ringbuffer, int dummy)
void* getReadAddressRingOptCB (volatile RingBufferOptStruct * ringbuffer, int dummy)
void* getWriteAddressCB (volatile Info_CBSliding * ptrCB, int l)
Definition at line 347 of file SlidingBuffer.cc.
References Info_CBSliding::buffer_size, Info_CBSliding::data, and Info_CBSliding::token_size.
void* getWriteAddressRingCB (volatile RingBufferStruct * ringbuffer, int dummy)
void* getWriteAddressRingOptCB (volatile RingBufferOptStruct * ringbuffer, int dummy)
void initWindowCB (volatile Info_Window * , int windowid)
Definition at line 222 of file SlidingBuffer.cc.
References Info_Window::headptr, Info_Window::id, and Info_Window::tailptr.
Referenced by createCB().
void lockCB (int lockid, int id)
Definition at line 560 of file SlidingBuffer.cc.
References lock(), and NUMBER_OF_PROC.
void myYield (void)
volatile Info_CBSliding* openCB (int bufferid, int windowid, volatile Info_Window ** window_out)
Definition at line 256 of file SlidingBuffer.cc.
References CB_SLIDING_WINDOWS, Info_App_s::cbList, Info_CB::data, findApp(), Info_Window::id, Info_CB::id, Info_App_s::name, Info_CB::next, Info_CBSliding::nReadWin, Info_CBSliding::nWriteWin, Info_CBSliding::readwindowinfo, Info_CB::type, and Info_CBSliding::writewindowinfo.
Referenced by openFifoCB().
volatile RingBufferStruct* openReadRingCB (int bufferid, int windowid, volatile RingBufferPointers ** rbp)
volatile RingBufferStruct* openReadRingCB2 (int bufferid, int windowid, volatile RingBufferPointers ** rbp, volatile RingBufferStruct * out)
volatile RingBufferOptStruct* openReadRingOptCB (int bufferid, int windowid, volatile RingBufferPointers ** rbp)
volatile RingBufferOptStruct* openReadRingOptCB2 (int bufferid, int windowid, volatile RingBufferPointers ** rbp, volatile RingBufferOptStruct * out)
volatile RingBufferStruct* openWriteRingCB (int bufferid, int windowid, volatile RingBufferPointers ** rbp)
volatile RingBufferStruct* openWriteRingCB2 (int bufferid, int windowid, volatile RingBufferPointers ** rbp, volatile RingBufferStruct * out)
volatile RingBufferOptStruct* openWriteRingOptCB (int bufferid, int windowid, volatile RingBufferPointers ** rbp)
volatile RingBufferOptStruct* openWriteRingOptCB2 (int bufferid, int windowid, volatile RingBufferPointers ** rbp, volatile RingBufferOptStruct * out)
void readCB (volatile Info_CBSliding * ptrCB, void * c, int l)
Read the value at location l and return it.
Definition at line 313 of file SlidingBuffer.cc.
References Info_CBSliding::buffer_size, Info_CBSliding::data, invalidateDCache(), and Info_CBSliding::token_size.
Referenced by readFifoCB(), and readStreamCB().
void readRingCB (volatile RingBufferStruct * ringbuffer, void * c, int dummy)
void readRingOptCB (volatile RingBufferOptStruct * ringbuffer, void * c, int dummy)
void readStreamCB (volatile Info_CBSliding * ptrCB, void * c, int l, int startloc)
Definition at line 358 of file SlidingBuffer.cc.
References readCB().
void releaseDataCB (volatile Info_CBSliding * ptrCB, volatile Info_Window * wp)
Definition at line 366 of file SlidingBuffer.cc.
References Info_CBSliding::buffer_size, buffer_size, COUNTVAL, FLIP_WRAP, Info_Window::id, SET_WRAP_COUNT, and Info_Window::tailptr.
Referenced by writeFifoCB().
void releaseDataCBBlock (volatile Info_CBSliding * ptrCB, volatile Info_Window * wp, uint32_t n)
void releaseDataRingCB (volatile RingBufferStruct * ringbuffer, volatile RingBufferPointers * rbp)
void releaseDataRingOptCB (volatile RingBufferOptStruct * ringbuffer, volatile RingBufferPointers * rbp)
void releaseSpaceCB (volatile Info_CBSliding * ptrCB, volatile Info_Window * wp)
Definition at line 393 of file SlidingBuffer.cc.
References Info_CBSliding::buffer_size, buffer_size, COUNTVAL, FLIP_WRAP, Info_Window::id, SET_WRAP_COUNT, and Info_Window::tailptr.
Referenced by readFifoCB().
void releaseSpaceCBBlock (volatile Info_CBSliding * ptrCB, volatile Info_Window * wp, uint32_t n)
void releaseSpaceRingCB (volatile RingBufferStruct * ringbuffer, volatile RingBufferPointers * rbp)
void releaseSpaceRingOptCB (volatile RingBufferOptStruct * ringbuffer, volatile RingBufferPointers * rbp)
void unlockCB (int lockid, int id)
Definition at line 566 of file SlidingBuffer.cc.
References NUMBER_OF_PROC, and unlock().
void writeCB (volatile Info_CBSliding * ptrCB, void * c, int l)
Definition at line 322 of file SlidingBuffer.cc.
References Info_CBSliding::buffer_size, cleanDCache(), Info_CBSliding::data, and Info_CBSliding::token_size.
Referenced by writeFifoCB(), and writeStreamCB().
void writeRingCB (volatile RingBufferStruct * ringbuffer, void * c, int dummy)
void writeRingOptCB (volatile RingBufferOptStruct * ringbuffer, void * c, int dummy)
void writeStreamCB (volatile Info_CBSliding * ptrCB, void * c, int l, int startloc)
Definition at line 362 of file SlidingBuffer.cc.
References writeCB().