Starburst: com/SlidingBuffer.cc File Reference
com/SlidingBuffer.cc File Reference
#include <helios/SlidingBuffer.h>
#include <helios/cheap.h>
#include <sys/syscall.h>
#include <sys/api.h>
#include <mc.h>
Defines
#define CONSUMERS 1
#define PRODUCERS 0
#define FLIP_WRAP(a) ((a)^0x80000000)
#define WRAPVAL(a) ((a)&0x80000000)
#define COUNTVAL(a) ((a)&0x7fffffff)
#define SET_WRAP_COUNT(a, b) (((a)&0x80000000)|((b)&0x7fffffff))
Functions
volatile Info_CB * createRingCB (volatile Info_App *infoApp, uint32_t tokensize, uint32_t buffersize, uint32_t nReadWin, uint32_t nWriteWin, uint32_t id)
volatile Info_CB * createRingOptCB (volatile Info_App *infoApp, uint32_t tokensize, uint32_t buffersize, uint32_t nReadWin, uint32_t nWriteWin, uint32_t id)
volatile Info_CB * createCB (volatile Info_App *infoApp, uint32_t tokensize, uint32_t buffersize, uint32_t nReadWin, uint32_t nWriteWin, uint32_t id)
volatile Info_CBSliding * findInfoFromAppCB (volatile Info_App *appInfoPtr, int bufferid)
void initWindowCB (volatile Info_Window *window, int windowid)
volatile Info_App * findApp (void)
uint32_t getBufferSizeCB (volatile Info_CBSliding *ptrCB)
volatile Info_CBSliding * openCB (int bufferid, int windowid, volatile Info_Window **window_out)
void readCB (volatile Info_CBSliding *ptrCB, void *c, int l)
Read the value at location l and return it.
void writeCB (volatile Info_CBSliding *ptrCB, void *c, int l)
void * getReadAddressCB (volatile Info_CBSliding *ptrCB, int l)
void * getWriteAddressCB (volatile Info_CBSliding *ptrCB, int l)
void readStreamCB (volatile Info_CBSliding *ptrCB, void *c, int l, int startloc)
void writeStreamCB (volatile Info_CBSliding *ptrCB, void *c, int l, int startloc)
void releaseDataCB (volatile Info_CBSliding *ptrCB, volatile Info_Window *wp)
void releaseSpaceCB (volatile Info_CBSliding *ptrCB, volatile Info_Window *wp)
void acquireSpaceCB (volatile Info_CBSliding *ptrCB, volatile Info_Window *wp)
void acquireDataCB (volatile Info_CBSliding *ptrCB, volatile Info_Window *wp)
volatile Info_CBSliding * openFifoCB (int id)
void writeFifoCB (volatile Info_CBSliding *ptrCB, void *data)
void readFifoCB (volatile Info_CBSliding *ptrCB, void *data)
void lockCB (int lockid, int id)
void unlockCB (int lockid, int id)
Variables
volatile Info_App * appInfoPtrList
Define Documentation
#define CONSUMERS 1
Definition at line 13 of file SlidingBuffer.cc.
#define COUNTVAL (a) ((a)&0x7fffffff)
Definition at line 21 of file SlidingBuffer.cc.
Referenced by acquireDataCB(), acquireSpaceCB(), readFifoCB(), releaseDataCB(), releaseSpaceCB(), and writeFifoCB().
#define FLIP_WRAP (a) ((a)^0x80000000)
Definition at line 19 of file SlidingBuffer.cc.
Referenced by acquireDataCB(), acquireSpaceCB(), releaseDataCB(), and releaseSpaceCB().
#define PRODUCERS 0
Definition at line 14 of file SlidingBuffer.cc.
#define SET_WRAP_COUNT (a, b) (((a)&0x80000000)|((b)&0x7fffffff))
Definition at line 22 of file SlidingBuffer.cc.
Referenced by acquireDataCB(), acquireSpaceCB(), releaseDataCB(), and releaseSpaceCB().
#define WRAPVAL (a) ((a)&0x80000000)
Definition at line 20 of file SlidingBuffer.cc.
Referenced by acquireDataCB(), and acquireSpaceCB().
Function Documentation
void acquireDataCB (volatile Info_CBSliding * ptrCB, volatile Info_Window * wp)
Definition at line 476 of file SlidingBuffer.cc.
References Info_CBSliding::buffer_size, buffer_size, COUNTVAL, FLIP_WRAP, Info_Window::headptr, Info_Window::id, Info_CBSliding::nWriteWin, SET_WRAP_COUNT, Info_Window::tailptr, WRAPVAL, Info_CBSliding::writewindowinfo, and Yield().
Referenced by readFifoCB().
void acquireSpaceCB (volatile Info_CBSliding * ptrCB, volatile Info_Window * wp)
Definition at line 420 of file SlidingBuffer.cc.
References Info_CBSliding::buffer_size, buffer_size, COUNTVAL, FLIP_WRAP, Info_Window::headptr, Info_Window::id, Info_CBSliding::nReadWin, Info_CBSliding::readwindowinfo, SET_WRAP_COUNT, Info_Window::tailptr, WRAPVAL, and Yield().
Referenced by writeFifoCB().
volatile Info_CB* createCB (volatile Info_App * infoApp, uint32_t tokensize, uint32_t buffersize, uint32_t nReadWin, uint32_t nWriteWin, uint32_t id)
Definition at line 53 of file SlidingBuffer.cc.
References CB_SLIDING_WINDOWS, Info_App_s::cbList, data, Info_CB::data, Info_FIFO::id, Info_CB::id, initWindowCB(), Info_CB::next, Info_CBSliding::nReadWin, nReadWin, Info_CBSliding::nWriteWin, nWriteWin, smalloc(), and Info_CB::type.
volatile Info_CB* createRingCB (volatile Info_App * infoApp, uint32_t tokensize, uint32_t buffersize, uint32_t nReadWin, uint32_t nWriteWin, uint32_t id)
Definition at line 26 of file SlidingBuffer.cc.
References Info_App_s::cbList.
volatile Info_CB* createRingOptCB (volatile Info_App * infoApp, uint32_t tokensize, uint32_t buffersize, uint32_t nReadWin, uint32_t nWriteWin, uint32_t id)
Definition at line 37 of file SlidingBuffer.cc.
References Info_App_s::cbList.
volatile Info_App* findApp (void)
Definition at line 228 of file SlidingBuffer.cc.
References getpid(), GetProcID(), and NUM_TASKS.
Referenced by openCB(), openReadCB(), and openWriteCB().
volatile Info_CBSliding* findInfoFromAppCB (volatile Info_App * appInfoPtr, int bufferid)
Definition at line 201 of file SlidingBuffer.cc.
References Info_App_s::cbList.
uint32_t getBufferSizeCB (volatile Info_CBSliding * ptrCB)
Definition at line 252 of file SlidingBuffer.cc.
References Info_CBSliding::buffer_size.
void* getReadAddressCB (volatile Info_CBSliding * ptrCB, int l)
Definition at line 336 of file SlidingBuffer.cc.
References Info_CBSliding::buffer_size, Info_CBSliding::data, invalidateDCache(), and Info_CBSliding::token_size.
void* getWriteAddressCB (volatile Info_CBSliding * ptrCB, int l)
Definition at line 347 of file SlidingBuffer.cc.
References Info_CBSliding::buffer_size, Info_CBSliding::data, and Info_CBSliding::token_size.
void initWindowCB (volatile Info_Window * window, int windowid)
Definition at line 222 of file SlidingBuffer.cc.
References Info_Window::headptr, Info_Window::id, and Info_Window::tailptr.
Referenced by createCB().
void lockCB (int lockid, int id)
Definition at line 560 of file SlidingBuffer.cc.
References lock(), and NUMBER_OF_PROC.
volatile Info_CBSliding* openCB (int bufferid, int windowid, volatile Info_Window ** window_out)
Definition at line 256 of file SlidingBuffer.cc.
References CB_SLIDING_WINDOWS, Info_App_s::cbList, Info_CB::data, findApp(), Info_Window::id, Info_CB::id, Info_App_s::name, Info_CB::next, Info_CBSliding::nReadWin, Info_CBSliding::nWriteWin, Info_CBSliding::readwindowinfo, Info_CB::type, and Info_CBSliding::writewindowinfo.
Referenced by openFifoCB().
volatile Info_CBSliding* openFifoCB (int id)
Definition at line 529 of file SlidingBuffer.cc.
References openCB().
void readCB (volatile Info_CBSliding * ptrCB, void * c, int l)
Read the value at location l and return it.
Definition at line 313 of file SlidingBuffer.cc.
References Info_CBSliding::buffer_size, Info_CBSliding::data, invalidateDCache(), and Info_CBSliding::token_size.
Referenced by readFifoCB(), and readStreamCB().
void readFifoCB (volatile Info_CBSliding * ptrCB, void * data)
Definition at line 545 of file SlidingBuffer.cc.
References acquireDataCB(), COUNTVAL, readCB(), Info_CBSliding::readwindowinfo, releaseSpaceCB(), and Info_Window::tailptr.
void readStreamCB (volatile Info_CBSliding * ptrCB, void * c, int l, int startloc)
Definition at line 358 of file SlidingBuffer.cc.
References readCB().
void releaseDataCB (volatile Info_CBSliding * ptrCB, volatile Info_Window * wp)
Definition at line 366 of file SlidingBuffer.cc.
References Info_CBSliding::buffer_size, buffer_size, COUNTVAL, FLIP_WRAP, Info_Window::id, SET_WRAP_COUNT, and Info_Window::tailptr.
Referenced by writeFifoCB().
void releaseSpaceCB (volatile Info_CBSliding * ptrCB, volatile Info_Window * wp)
Definition at line 393 of file SlidingBuffer.cc.
References Info_CBSliding::buffer_size, buffer_size, COUNTVAL, FLIP_WRAP, Info_Window::id, SET_WRAP_COUNT, and Info_Window::tailptr.
Referenced by readFifoCB().
void unlockCB (int lockid, int id)
Definition at line 566 of file SlidingBuffer.cc.
References NUMBER_OF_PROC, and unlock().
void writeCB (volatile Info_CBSliding * ptrCB, void * c, int l)
Definition at line 322 of file SlidingBuffer.cc.
References Info_CBSliding::buffer_size, cleanDCache(), Info_CBSliding::data, and Info_CBSliding::token_size.
Referenced by writeFifoCB(), and writeStreamCB().
void writeFifoCB (volatile Info_CBSliding * ptrCB, void * data)
Definition at line 534 of file SlidingBuffer.cc.
References acquireSpaceCB(), COUNTVAL, releaseDataCB(), Info_Window::tailptr, writeCB(), and Info_CBSliding::writewindowinfo.
void writeStreamCB (volatile Info_CBSliding * ptrCB, void * c, int l, int startloc)
Definition at line 362 of file SlidingBuffer.cc.
References writeCB().
Variable Documentation
volatile Info_App* appInfoPtrList