Starburst: bitshark/spi.cc File Reference
bitshark/spi.cc File Reference
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/api.h>
#include <bitshark/spi.h>
Defines
#define SPI_VERBOSE_TRANSFER 0
#define spi_printf(args...)
Functions
void spi_reset ()
Do a soft reset on the XPS SPI controller using the Soft Reset Register.
int spi_can_write ()
Check if a SPI write can be performed.
int spi_can_read ()
void spi_transfer (unsigned short cmd, unsigned short *data)
Read a 16-bit word from the SPI bus.
void spi_selftest ()
Incomplete self-test, do not use.
int operator== (const spireg_spicr_t &left, const spireg_spicr_t &right)
Utility operator to quickly compare spireg_spicr_t structures.
int operator!= (const spireg_spicr_t &left, const spireg_spicr_t &right)
Utility operator to quickly compare spireg_spicr_t structures.
Define Documentation
#define spi_printf (args...)
Definition at line 25 of file spi.cc.
Referenced by spi_reset(), and spi_transfer().
#define SPI_VERBOSE_TRANSFER 0
Definition at line 20 of file spi.cc.
Function Documentation
int operator!= (const spireg_spicr_t & left, const spireg_spicr_t & right)
Utility operator to quickly compare spireg_spicr_t structures.
Definition at line 178 of file spi.cc.
int operator== (const spireg_spicr_t & left, const spireg_spicr_t & right)
Utility operator to quickly compare spireg_spicr_t structures.
Definition at line 161 of file spi.cc.
References spireg_spicr_t::cpha, spireg_spicr_t::cpol, spireg_spicr_t::loop, spireg_spicr_t::lsb_first, spireg_spicr_t::master, spireg_spicr_t::mssae, spireg_spicr_t::mti, spireg_spicr_t::Rx_Reset, spireg_spicr_t::spe, and spireg_spicr_t::Tx_Reset.
int spi_can_read ()
Definition at line 48 of file spi.cc.
References spireg_spisr_t::Rx_Full, and spi_get_sr.
int spi_can_write ()
Check if a SPI write can be performed.
Returns:
1 when a SPI write can be performed or 0 if a transaction is busy
Definition at line 43 of file spi.cc.
References spi_get_sr, and spireg_spisr_t::Tx_Empty.
void spi_reset ()
Do a soft reset on the XPS SPI controller using the Soft Reset Register.
Definition at line 31 of file spi.cc.
References spi_printf, and spi_set_srr.
Referenced by adc_init().
void spi_selftest ()
Incomplete self-test, do not use.
Definition at line 139 of file spi.cc.
References cmd, spireg_spicr_t::loop, read(), spi_get_cr, spi_set_cr, and spi_transfer().
void spi_transfer (unsigned short cmd, unsigned short * data)
Read a 16-bit word from the SPI bus.
Write a 16-bit word to the SPI bus.
When the SPI controller is busy, this function will block until the write can be performed. Note: without the delays the SPI commands seem to be ignored; this is beyond our control so we can only delay the commands
Definition at line 57 of file spi.cc.
References spireg_spidrr_t::data, spireg_spicr_t::mti, spireg_spisr_t::Rx_Empty, spi_dump_cr, spi_dump_sr, spi_get_cr, spi_get_drr, spi_get_sr, spi_printf, spi_set_cr, spi_set_dtr, spireg_spisr_t::Tx_Empty, spireg_spisr_t::Tx_Full, usleep(), XPS_SPI_SPISSR, and XPS_SPI_SS_REG.
Referenced by adc_init(), adc_reset(), and spi_selftest().