Starburst: util/srec.cc File Reference
util/srec.cc File Reference
#include <sys/io.h>
#include <srec.h>
Functions
static char srec_char ()
static void srec_putc (char c)
static void srec_putb (char b)
static int srec_char2int (char c)
static char srec_byte ()
static unsigned int srec_int (int len, char &checksum)
static char * srec_addr (int len, char &checksum)
static bool srec_lineend ()
static bool srec_checksum (char checksum)
static bool srec_drop (int len, int addrlen)
static bool srec_store (int len, int addrlen)
static void srec_putx (int i)
static bool srec_load (int len, int addrlen)
static bool srec_exec (int len, int addrlen)
static char srec_line ()
void srec ()
Function Documentation
void srec (void)
Definition at line 157 of file srec.cc.
References _puts(), srec_line(), and srec_putx().
Referenced by main().
static char* srec_addr (int len, char & checksum) [static]
Definition at line 47 of file srec.cc.
References srec_int().
Referenced by srec_exec(), srec_load(), and srec_store().
static char srec_byte () [static]
Definition at line 30 of file srec.cc.
References srec_char(), and srec_char2int().
Referenced by srec_checksum(), srec_exec(), srec_int(), srec_line(), and srec_store().
static char srec_char () [static]
Definition at line 6 of file srec.cc.
References inbyte().
Referenced by srec_byte(), srec_drop(), srec_line(), and srec_lineend().
static int srec_char2int (char c) [static]
Definition at line 23 of file srec.cc.
Referenced by srec_byte().
static bool srec_checksum (char checksum) [static]
Definition at line 59 of file srec.cc.
References srec_byte().
Referenced by srec_exec(), srec_load(), and srec_store().
static bool srec_drop (int len, int addrlen) [static]
Definition at line 63 of file srec.cc.
References srec_char(), and srec_lineend().
Referenced by srec_line().
static bool srec_exec (int len, int addrlen) [static]
Definition at line 101 of file srec.cc.
References _puts(), a, srec_addr(), srec_byte(), srec_checksum(), and srec_lineend().
Referenced by srec_line().
static unsigned int srec_int (int len, char & checksum) [static]
Definition at line 37 of file srec.cc.
References b, and srec_byte().
Referenced by srec_addr(), and srec_load().
static char srec_line () [static]
Definition at line 114 of file srec.cc.
References srec_byte(), srec_char(), srec_drop(), srec_exec(), srec_load(), and srec_store().
Referenced by srec().
static bool srec_lineend () [static]
Definition at line 51 of file srec.cc.
References srec_char().
Referenced by srec_drop(), srec_exec(), srec_load(), and srec_store().
static bool srec_load (int len, int addrlen) [static]
Definition at line 86 of file srec.cc.
References _puts(), a, srec_addr(), srec_checksum(), srec_int(), srec_lineend(), and srec_putx().
Referenced by srec_line().
static void srec_putb (char b) [static]
Definition at line 18 of file srec.cc.
References srec_putc().
Referenced by srec_putx().
static void srec_putc (char c) [static]
Definition at line 10 of file srec.cc.
References outbyte().
Referenced by srec_putb().
static void srec_putx (int i) [static]
Definition at line 81 of file srec.cc.
References srec_putb().
Referenced by srec(), and srec_load().
static bool srec_store (int len, int addrlen) [static]
Definition at line 69 of file srec.cc.
References a, b, srec_addr(), srec_byte(), srec_checksum(), and srec_lineend().
Referenced by srec_line().