Starburst: posix/stats.cc File Reference
posix/stats.cc File Reference
#include <pthread.h>
#include <sys/api.h>
#include <stdio.h>
Data Structures
struct stats_t
Defines
#define MAX_STAT_ELEM (1024*84-1)
Functions
void pthread_stats_thread_cleanup (stats_t *s)
void pthread_stats_elem_register (pthread_key_t key, void *elem, char *name)
void pthread_stats_elem_unregister (pthread_key_t key, void *elem)
int pthread_stats_global_init (pthread_key_t *key)
int pthread_stats_global_cleanup (pthread_key_t key)
int pthread_stats_thread_init (pthread_key_t key, void(*print_func)(void *))
Define Documentation
#define MAX_STAT_ELEM (1024*84-1)
Definition at line 6 of file stats.cc.
Referenced by pthread_stats_elem_register(), and pthread_stats_elem_unregister().
Function Documentation
void pthread_stats_elem_register (pthread_key_t key, void * elem, char * name)
Definition at line 16 of file stats.cc.
References stats_t::e, MAX_STAT_ELEM, stats_t::num, and pthread_getspecific().
void pthread_stats_elem_unregister (pthread_key_t key, void * elem)
Definition at line 33 of file stats.cc.
References stats_t::e, MAX_STAT_ELEM, stats_t::num, stats_t::print_func, and pthread_getspecific().
int pthread_stats_global_cleanup (pthread_key_t key)
Definition at line 56 of file stats.cc.
References pthread_key_delete().
int pthread_stats_global_init (pthread_key_t * key)
Definition at line 52 of file stats.cc.
References pthread_key_create(), and pthread_stats_thread_cleanup().
void pthread_stats_thread_cleanup (stats_t * s)
Definition at line 74 of file stats.cc.
References stats_t::e, lfree, and stats_t::print_func.
Referenced by pthread_stats_global_init().
int pthread_stats_thread_init (pthread_key_t key, void(*)(void *) print_func)
Definition at line 60 of file stats.cc.
References lcalloc, lfree, and pthread_setspecific().