Starburst: mc_ptr< T > Struct Template Reference
mc_ptr< T > Struct Template Reference
#include <mc.h>
Public Member Functions
mc_ptr ()
mc_ptr (T *p)
struct mc_ptr< T > & operator= (void *rh)
template<class A >
struct mc_ptr< T > & operator= (const A rh)
template<class A >
operator A * () const
operator long () const
T & operator* () const
T & operator[] (long x) const
T * operator-> () const
bool operator! () const
Detailed Description
template<class T>
struct mc_ptr< T >
Definition at line 312 of file mc.h.
Constructor & Destructor Documentation
template<class T > mc_ptr< T >::mc_ptr () [inline]
Definition at line 313 of file mc.h.
template<class T > mc_ptr< T >::mc_ptr (T * p) [inline]
Definition at line 314 of file mc.h.
Member Function Documentation
template<class T > template<class A > mc_ptr< T >::operator A * () const [inline]
Definition at line 317 of file mc.h.
References mc_var< T * >::_var, a, mc_var< T * >::enter_r(), and mc_var< T * >::exit_r().
template<class T > mc_ptr< T >::operator long () const [inline]
Definition at line 318 of file mc.h.
References mc_var< T * >::_var, mc_var< T * >::enter_r(), and mc_var< T * >::exit_r().
template<class T > bool mc_ptr< T >::operator! () const [inline]
Definition at line 322 of file mc.h.
References mc_var< T * >::_var, mc_var< T * >::enter_r(), and mc_var< T * >::exit_r().
template<class T > T& mc_ptr< T >::operator* () const [inline]
Definition at line 319 of file mc.h.
References mc_var< T * >::_var, mc_var< T * >::enter_r(), mc_var< T * >::exit_r(), and PMC_NS::T.
template<class T > T* mc_ptr< T >::operator-> () const [inline]
Definition at line 321 of file mc.h.
References mc_var< T * >::_var, mc_var< T * >::enter_r(), mc_var< T * >::exit_r(), and PMC_NS::T.
template<class T > struct mc_ptr< T >& mc_ptr< T >::operator= (void * rh) [inline, read]
Definition at line 315 of file mc.h.
References mc_var< T * >::_var, mc_var< T * >::enter_w(), mc_var< T * >::exit_w(), and PMC_NS::T.
template<class T > template<class A > struct mc_ptr< T >& mc_ptr< T >::operator= (const A rh) [inline, read]
Reimplemented from mc_prim< T * >.
Definition at line 316 of file mc.h.
References mc_var< T * >::_var, mc_var< T * >::enter_w(), mc_var< T * >::exit_w(), and PMC_NS::T.
template<class T > T& mc_ptr< T >::operator[] (long x) const [inline]
Definition at line 320 of file mc.h.
References mc_var< T * >::_var, mc_var< T * >::enter_r(), mc_var< T * >::exit_r(), and PMC_NS::T.
The documentation for this struct was generated from the following file:
include/mc.h