Starburst: include/syncevent.h File Reference
include/syncevent.h File Reference
#include <sys/helix_config.h>
#include <mc.h>
#include <stdarg.h>
#include <sys/kernel_types.h>
#include <pthread.h>
#include <sys/api.h>
Data Structures
class syncevent_t< N >
struct syncevent_t< N >::dest_t
Defines
#define se_hit_static(se) ((syncevent_t<>::hit_func)&(se).hit_static<se>)
#define se_wait_static(se) ((syncevent_t<>::wait_func)&(se).wait_static<se>)
#define se_t syncevent_t
#define se_create(se, p...) se_create_((syncevent_t<VA_NUMARGS(p)/2>&)(se),##p)
#define se_create_pt(se, p...) se_create_pt_((syncevent_t<VA_NUMARGS(p)>&)(se),##p)
#define se_hit(se) (se).hit()
#define se_wait(se, count...) (se).wait(count);
Functions
template<int N>
int se_create_a (syncevent_t< N > &se, pid_t(&pid)[N], int(&proc)[N])
template<int N>
int se_create_ (syncevent_t< N > &se, pid_t pid, int proc,...)
template<int N>
int se_create_pta (syncevent_t< N > &se, pthread_t(&p)[N])
template<int N>
int se_create_pt_ (syncevent_t< N > &se, pthread_t p,...)
Define Documentation
#define se_create (se, p...) se_create_((syncevent_t<VA_NUMARGS(p)/2>&)(se),##p)
Definition at line 89 of file syncevent.h.
#define se_create_pt (se, p...) se_create_pt_((syncevent_t<VA_NUMARGS(p)>&)(se),##p)
Definition at line 115 of file syncevent.h.
#define se_hit (se) (se).hit()
Definition at line 117 of file syncevent.h.
#define se_hit_static (se) ((syncevent_t<>::hit_func)&(se).hit_static<se>)
Definition at line 58 of file syncevent.h.
#define se_t syncevent_t
Definition at line 61 of file syncevent.h.
#define se_wait (se, count...) (se).wait(count);
Definition at line 118 of file syncevent.h.
#define se_wait_static (se) ((syncevent_t<>::wait_func)&(se).wait_static<se>)
Definition at line 59 of file syncevent.h.
Function Documentation
template<int N> int se_create_ (syncevent_t< N > & se, pid_t pid, int proc, ...)
Definition at line 74 of file syncevent.h.
References pid, and se_create_a().
template<int N> int se_create_a (syncevent_t< N > & se, pid_t(&) pid[N], int(&) proc[N])
Definition at line 64 of file syncevent.h.
References syncevent_t< N >::finish(), and pid.
Referenced by se_create_().
template<int N> int se_create_pt_ (syncevent_t< N > & se, pthread_t p, ...)
Definition at line 102 of file syncevent.h.
References a, and se_create_pta().
template<int N> int se_create_pta (syncevent_t< N > & se, pthread_t(&) p[N])
Definition at line 92 of file syncevent.h.
References syncevent_t< N >::finish(), getgpidproc(), and getlpid().
Referenced by se_create_pt_().