Starburst: include/sys/syscall.h File Reference
include/sys/syscall.h File Reference
System calls to kernel functions.
#include <sys/kernel.h>
#include <errno.h>
#include <stdint.h>
Defines
#define SC_INVAL (0*PTR_SIZE)
#define SC_PROCESS_GETPID (1*PTR_SIZE)
#define SC_PROCESS_CREATE (2*PTR_SIZE)
#define SC_PROCESS_GETFLAGS (3*PTR_SIZE)
#define SC_PROCESS_SETFLAGS (4*PTR_SIZE)
#define SC_PROCESS_GETSTATE (5*PTR_SIZE)
#define SC_PROCESS_START (6*PTR_SIZE)
#define SC_PROCESS_YIELD (7*PTR_SIZE)
#define SC_PROCESS_SUSPEND (8*PTR_SIZE)
#define SC_PROCESS_END (9*PTR_SIZE)
#define SC_PROCESS_JOIN (10*PTR_SIZE)
#define SC_PROCESS_DESTROY (11*PTR_SIZE)
#define SC_PROCESS_ZOMBIE (12*PTR_SIZE)
#define SC_PROCESS_DUMP (13*PTR_SIZE)
#define SC_PROCESS_SETTIMESLICE (14*PTR_SIZE)
#define SC_PROCESS_GETSTATS (15*PTR_SIZE)
#define SC_PROCESS_PROCLOCAL (16*PTR_SIZE)
#define SC_CHANNEL_ALLOC (17*PTR_SIZE)
#define SC_CHANNEL_ASSIGN (18*PTR_SIZE)
#define SC_CHANNEL_FIND (19*PTR_SIZE)
#define SC_CHANNEL_OPEN (20*PTR_SIZE)
#define SC_CHANNEL_COUNT (21*PTR_SIZE)
#define SC_CHANNEL_LABEL (22*PTR_SIZE)
#define SC_HOOK_TABLE (23*PTR_SIZE)
#define SC_SIGNAL_SET (24*PTR_SIZE)
#define SC_SIGNAL_CLEAR (25*PTR_SIZE)
#define SC_SIGNAL_SEND (26*PTR_SIZE)
#define SC_SIGNAL_MASK (27*PTR_SIZE)
#define SC_SIGNAL_YIELD (28*PTR_SIZE)
#define SC_SHUTDOWN (29*PTR_SIZE)
#define SC_SYNCEVENT_HIT (30*PTR_SIZE)
#define SC_SYNCEVENT_WAIT (31*PTR_SIZE)
#define __SYSCALL_H_DONE
Functions
int InvalSyscall () _NO_THROW
Dummy function to catch invalid syscalls.
int lCreateProcess (pid_t &pid, void *(*main)(void *), void *arg=NULL, timems_t slicelength=PROC_DEFAULT_TIMESLICE, size_t stack=PROC_DEFAULT_STACK) _NO_THROW __attribute__((warn_unused_result))
Syscall to kCreateProcess().
int lGetProcessFlags (pid_t pid, int *flags) _NO_THROW
Syscall to kGetProcessFlags().
int lSetProcessFlags (pid_t pid, int flags) _NO_THROW
Syscall to kSetProcessFlags().
int lGetProcessState (pid_t pid, proc_state_t *state, bool *sighandling=NULL) _NO_THROW
Syscall to kGetProcessState().
int lStartProcess (pid_t pid) _NO_THROW __attribute__((warn_unused_result))
Syscall to kStartProcess().
pid_t getpid () _NO_THROW
Syscall to kGetPid().
int Yield (bool havework=true) _NO_THROW
Syscall to kYield().
int Suspend (const sigset_t *mask=NULL, const sigset_t *wait_sticky=NULL) _NO_THROW
Syscall to kSuspend().
void EndProcess (void *ret) _NO_THROW
Syscall to kEndProcess().
int lJoinProcess (pid_t pid, void **ret=NULL) _NO_THROW __attribute__((warn_unused_result))
Syscall to kJoinProcess().
int lDestroyProcess (pid_t pid, void **ret) _NO_THROW
Syscall to kDestroyProcess().
int lGetZombie (pid_t *pid, void **ret) _NO_THROW
Syscall to kGetZombie().
int CoreDump () _NO_THROW
Syscall to kCoreDump().
int lAllocChannels (pid_t pid, int num_chan) _NO_THROW __attribute__((warn_unused_result))
Syscall to kAllocChannels().
int lAssignChannel (pid_t pid, int chan_id, void *channel, int label=0) _NO_THROW
Syscall to kAssignChannel().
int FindChannel (int label) _NO_THROW
Syscall to kFindChannel().
void * OpenChannel (int channel) _NO_THROW
Syscall to kOpenChannel().
int lGetChannelCount (pid_t pid) _NO_THROW
Syscall to kGetChannelCount().
int lSetChannelLabel (pid_t pid, int chan_id, int label) _NO_THROW
Syscall to kSetChannelLabel().
int lSetProcessTimeslice (pid_t pid, timems_t slicelength) _NO_THROW
Syscall to kSetProcessTimeslice().
int GetProcessStats (pid_t pid, proc_stats_t *stats) _NO_THROW
Syscall to kGetProcessStats().
int GetProcLocal (proc_local_t **p) _NO_THROW
Syscall to kGetProcLocal().
hook_t * GetHookTable () _NO_THROW
Syscall to kGetHookTable().
int SetSignalHandler (int signum, const struct sigaction *act) _NO_THROW __attribute__((warn_unused_result))
Syscall to kSetSignalHandler().
int ClearSignal (int signum, struct sigaction *sa) _NO_THROW
Syscall to kClearSignal().
int lSendSignal (pid_t pid, int sig, union sigval *si) _NO_THROW
Syscall to kSendSignal().
int MaskSignal (int how, const sigset_t *set, sigset_t *oldset) _NO_THROW
Syscall to kMaskSignal().
int Shutdown () _NO_THROW
Syscall to kShutdown().
int lSyncEventHit (pid_t pid, void *event) _NO_THROW
Syscall to kSyncEventHit().
int SyncEventWait (void *event, int count) _NO_THROW __attribute__((warn_unused_result))
Syscall to kSyncEventWait().
Detailed Description
System calls to kernel functions.
Definition in file syscall.h.
Define Documentation
#define __SYSCALL_H_DONE
Definition at line 119 of file syscall.h.
#define SC_CHANNEL_ALLOC (17*PTR_SIZE)
Definition at line 28 of file syscall.h.
#define SC_CHANNEL_ASSIGN (18*PTR_SIZE)
Definition at line 29 of file syscall.h.
#define SC_CHANNEL_COUNT (21*PTR_SIZE)
Definition at line 32 of file syscall.h.
#define SC_CHANNEL_FIND (19*PTR_SIZE)
Definition at line 30 of file syscall.h.
#define SC_CHANNEL_LABEL (22*PTR_SIZE)
Definition at line 33 of file syscall.h.
#define SC_CHANNEL_OPEN (20*PTR_SIZE)
Definition at line 31 of file syscall.h.
#define SC_HOOK_TABLE (23*PTR_SIZE)
Definition at line 34 of file syscall.h.
#define SC_INVAL (0*PTR_SIZE)
Definition at line 11 of file syscall.h.
#define SC_PROCESS_CREATE (2*PTR_SIZE)
Definition at line 13 of file syscall.h.
#define SC_PROCESS_DESTROY (11*PTR_SIZE)
Definition at line 22 of file syscall.h.
#define SC_PROCESS_DUMP (13*PTR_SIZE)
Definition at line 24 of file syscall.h.
#define SC_PROCESS_END (9*PTR_SIZE)
Definition at line 20 of file syscall.h.
#define SC_PROCESS_GETFLAGS (3*PTR_SIZE)
Definition at line 14 of file syscall.h.
#define SC_PROCESS_GETPID (1*PTR_SIZE)
Definition at line 12 of file syscall.h.
#define SC_PROCESS_GETSTATE (5*PTR_SIZE)
Definition at line 16 of file syscall.h.
#define SC_PROCESS_GETSTATS (15*PTR_SIZE)
Definition at line 26 of file syscall.h.
#define SC_PROCESS_JOIN (10*PTR_SIZE)
Definition at line 21 of file syscall.h.
#define SC_PROCESS_PROCLOCAL (16*PTR_SIZE)
Definition at line 27 of file syscall.h.
#define SC_PROCESS_SETFLAGS (4*PTR_SIZE)
Definition at line 15 of file syscall.h.
#define SC_PROCESS_SETTIMESLICE (14*PTR_SIZE)
Definition at line 25 of file syscall.h.
#define SC_PROCESS_START (6*PTR_SIZE)
Definition at line 17 of file syscall.h.
#define SC_PROCESS_SUSPEND (8*PTR_SIZE)
Definition at line 19 of file syscall.h.
#define SC_PROCESS_YIELD (7*PTR_SIZE)
Definition at line 18 of file syscall.h.
#define SC_PROCESS_ZOMBIE (12*PTR_SIZE)
Definition at line 23 of file syscall.h.
#define SC_SHUTDOWN (29*PTR_SIZE)
Definition at line 40 of file syscall.h.
#define SC_SIGNAL_CLEAR (25*PTR_SIZE)
Definition at line 36 of file syscall.h.
#define SC_SIGNAL_MASK (27*PTR_SIZE)
Definition at line 38 of file syscall.h.
#define SC_SIGNAL_SEND (26*PTR_SIZE)
Definition at line 37 of file syscall.h.
#define SC_SIGNAL_SET (24*PTR_SIZE)
Definition at line 35 of file syscall.h.
#define SC_SIGNAL_YIELD (28*PTR_SIZE)
Definition at line 39 of file syscall.h.
#define SC_SYNCEVENT_HIT (30*PTR_SIZE)
Definition at line 41 of file syscall.h.
#define SC_SYNCEVENT_WAIT (31*PTR_SIZE)
Definition at line 42 of file syscall.h.
Function Documentation
int ClearSignal (int signum, struct sigaction * sa)
Syscall to kClearSignal().
Referenced by SignalDispatcher().
int CoreDump ()
Syscall to kCoreDump().
void EndProcess (void * ret)
Syscall to kEndProcess().
Referenced by _exit().
int FindChannel (int label)
Syscall to kFindChannel().
hook_t* GetHookTable ()
Syscall to kGetHookTable().
Referenced by GetHook(), RegisterHook(), and UnregisterHook().
pid_t getpid ()
Syscall to kGetPid().
Referenced by _mown(), abort(), auto_ret< T, ok >::abort(), calloc(), WorkQueue< T, W >::Dispatcher(), dLockRegister(), fcalloc(), ffree(), findApp(), fmalloc(), fmown(), PMC_NS::Error::format(), frealloc(), free(), GarbageCollect(), getgpid(), getrusage(), getupid(), lck_ask(), lck_destroy(), lck_giveup(), lck_pass_p(), lck_register(), lck_request(), lck_unlock(), linfs_register(), malloc(), MallocDaemonHandler(), mc_error_handler(), mown(), pipe_write(), pprintf(), raise(), realloc(), scalloc(), sfree(), smalloc(), smown(), srealloc(), timer_create(), timer_settime(), times(), TraceDump(), WaitProcess(), and WaitProcessDaemon().
int GetProcessStats (pid_t pid, proc_stats_t * stats)
Syscall to kGetProcessStats().
Referenced by _getrusage(), DumpStats(), GarbageCollect(), and times().
int GetProcLocal (proc_local_t ** p)
Syscall to kGetProcLocal().
Referenced by pthread_getspecific(), and TracePhaseChange().
int InvalSyscall ()
Dummy function to catch invalid syscalls.
Does not do anything except for returning ENOSYS.
Returns:
always ENOSYS
Definition at line 19 of file syscall.cc.
int lAllocChannels (pid_t pid, int num_chan)
Syscall to kAllocChannels().
Referenced by ProcessRequest(), and SetupProfilerDaemon().
int lAssignChannel (pid_t pid, int chan_id, void * channel, int label = 0)
Syscall to kAssignChannel().
Referenced by ProcessRequest(), and SetupProfilerDaemon().
int lCreateProcess (pid_t & pid, void *(*)(void *) main, void * arg = NULL, timems_t slicelength = PROC_DEFAULT_TIMESLICE, size_t stack = PROC_DEFAULT_STACK)
Syscall to kCreateProcess().
Referenced by InitTaskDaemon(), ProcessRequest(), SetupProfilerDaemon(), StartDumpStatsDaemon(), StartMallocDaemon(), StartShutdownDaemon(), and TraceDump().
int lDestroyProcess (pid_t pid, void ** ret)
Syscall to kDestroyProcess().
Referenced by ProcessRequest(), SetupProfilerDaemon(), StartMallocDaemon(), StopMallocDaemon(), and TraceDump().
int lGetChannelCount (pid_t pid)
Syscall to kGetChannelCount().
int lGetProcessFlags (pid_t pid, int * flags)
Syscall to kGetProcessFlags().
Referenced by ProcessRequest().
int lGetProcessState (pid_t pid, proc_state_t * state, bool * sighandling = NULL)
Syscall to kGetProcessState().
Referenced by __wrap_exit(), getupid(), ProcessRequest(), and usleep().
int lGetZombie (pid_t * pid, void ** ret)
Syscall to kGetZombie().
Referenced by GarbageCollect().
int lJoinProcess (pid_t pid, void ** ret = NULL)
Syscall to kJoinProcess().
Referenced by ShutdownDaemon(), StopMallocDaemon(), WaitProcess(), and WaitProcessDaemon().
int lSendSignal (pid_t pid, int sig, union sigval * si)
Syscall to kSendSignal().
Referenced by FireTimer(), IssueMallocRequest(), kill(), and ProcessRequest().
int lSetChannelLabel (pid_t pid, int chan_id, int label)
Syscall to kSetChannelLabel().
Referenced by ProcessRequest().
int lSetProcessFlags (pid_t pid, int flags)
Syscall to kSetProcessFlags().
Referenced by ProcessRequest(), and StartMallocDaemon().
int lSetProcessTimeslice (pid_t pid, timems_t slicelength)
Syscall to kSetProcessTimeslice().
Referenced by ProcessRequest().
int lStartProcess (pid_t pid)
Syscall to kStartProcess().
Referenced by InitTaskDaemon(), ProcessRequest(), SetupProfilerDaemon(), StartDumpStatsDaemon(), StartMallocDaemon(), StartShutdownDaemon(), and TraceDump().
int lSyncEventHit (pid_t pid, void * event)
Syscall to kSyncEventHit().
Referenced by ProcessRequest().
int MaskSignal (int how, const sigset_t * set, sigset_t * oldset)
Syscall to kMaskSignal().
Referenced by set_no_gracefull_exit(), SignalDispatcher(), and sigprocmask().
void* OpenChannel (int channel)
Syscall to kOpenChannel().
Referenced by ProfilerDaemon(), and WaitProcessDaemon().
int SetSignalHandler (int signum, const struct sigaction * act)
Syscall to kSetSignalHandler().
Referenced by sigaction(), and signal().
int Shutdown ()
Syscall to kShutdown().
Referenced by ForceShutdown(), and StartShutdownDaemon().
int Suspend (const sigset_t * mask = NULL, const sigset_t * wait_sticky = NULL)
Syscall to kSuspend().
int SyncEventWait (void * event, int count)
Syscall to kSyncEventWait().
Referenced by syncevent_t< N >::wait().
int Yield (bool havework = true)
Syscall to kYield().