Starburst: io/timer.cc File Reference
io/timer.cc File Reference
Low-level functions to control the local timer for interrupts.
#include <sys/io.h>
#include <sys/helix_config.h>
#include "iodebug.h"
Functions
void kSetTimer (unsigned int time, unsigned int repeat)
Sets the local timer to the designated number of clock cycles.
unsigned int kGetTimer ()
Returns the current value of the timer.
void kStopTimer ()
Stops the local timer.
Detailed Description
Low-level functions to control the local timer for interrupts.
These functions should only be used by the kernel to manage the time-slices for scheduling.
Definition in file timer.cc.
Function Documentation
unsigned int kGetTimer ()
Returns the current value of the timer.
Definition at line 68 of file timer.cc.
References io_read, and IO_TIMER_TCR0.
Referenced by bitshark_verify_clk(), GetRemainingTimeslice(), and kYield().
void kSetTimer (unsigned int time, unsigned int repeat)
Sets the local timer to the designated number of clock cycles.
The timer will be started automatically. When the value 0 is reached, an interrupt is generated.
Parameters:
time number of cycles to set the counter to
repeat set to non-zero to reload and restart the timer with this interval when zero is reached
Definition at line 22 of file timer.cc.
References IO_TIMER_TCSR0, IO_TIMER_TLR0, and io_write.
Referenced by kScheduleProcess(), kStartScheduling(), and kYield().
void kStopTimer ()
Stops the local timer.
The interrupt flag will be cleared.
Definition at line 76 of file timer.cc.
References IO_TIMER_TCSR0, and io_write.
Referenced by kInitKernel(), and kPanic().