Starburst: daemons/TimerDaemon.cc File Reference
daemons/TimerDaemon.cc File Reference
Daemons
Daemon to handle all timer calls.
#include <sys/api.h>
#include <time.h>
#include <daemons.h>
#include <stdio.h>
Data Structures
struct _timer_event_t
Defines
#define DEBUGH(str, a...) printf("TimerDaemon %d: " str "\n",GetProcID(),##a)
#define DEBUGL(str, a...)
#define TIMER_FLAG_NONE 0
#define TIMER_FLAG_ENABLED 1
#define TIMER_FLAG_SIGNAL 2
#define TIMER_FLAG_ARMED 4
#define TIMER_FLAG_FIRE (TIMER_FLAG_ENABLED|TIMER_FLAG_SIGNAL|TIMER_FLAG_ARMED)
#define FIND_TIMER(timerid, t)
#define TIMESPEC_ADD(dest, diff)
#define TIMESPEC_SUB(dest, op)
#define TIMESPEC_LE(op1, op2)
Typedefs
typedef struct _timer_event_t timer_event_t
Functions
int timer_create (clockid_t clockid, struct sigevent *sevp, timer_t *timerid)
Creates a new timer.
int timer_delete (timer_t timerid)
int timer_getoverrun (timer_t timerid)
int timer_settime (timer_t timerid, int flags, const struct itimerspec *new_value, struct itimerspec *old_value)
int timer_gettime (timer_t timerid, struct itimerspec *curr_value)
int timer_repeat (void(*handler)(int, siginfo_t *, void *), void *arg, long interval_sec, long interval_nsec)
void FireTimer (timer_event_t *t, pid_t pid, timer_t timerid, struct timespec *now)
void * TimerDaemon (void *arg)
int StartTimerDaemon ()
Starts the timer daemon.
Detailed Description
Daemon to handle all timer calls.
Definition in file TimerDaemon.cc.
Define Documentation
#define DEBUGH (str, a...) printf("TimerDaemon %d: " str "\n",GetProcID(),##a)
Definition at line 14 of file TimerDaemon.cc.
Referenced by FireTimer(), and TimerDaemon().
#define DEBUGL (str, a...)
Definition at line 19 of file TimerDaemon.cc.
Referenced by FireTimer(), timer_create(), and timer_settime().
#define FIND_TIMER (timerid, t)
Value:
if(timerid<0||timerid>=MAX_PROCESSES*MAX_TIMERS){errno=EINVAL;return -1;}   \
    timer_event_t* t=(timer_event_t*)GetHook(HOOK_TIMER);       \
    if(t==NULL){errno=EAGAIN;return -1;}                        \
    t=&t[timerid];                                              \
    if(!(t->flags&TIMER_FLAG_ENABLED)){errno=EINVAL;return -1;}
Definition at line 101 of file TimerDaemon.cc.
Referenced by timer_delete(), timer_getoverrun(), timer_gettime(), and timer_settime().
#define TIMER_FLAG_ARMED 4
Definition at line 28 of file TimerDaemon.cc.
Referenced by FireTimer(), and timer_settime().
#define TIMER_FLAG_ENABLED 1
Definition at line 26 of file TimerDaemon.cc.
Referenced by timer_create().
#define TIMER_FLAG_FIRE (TIMER_FLAG_ENABLED|TIMER_FLAG_SIGNAL|TIMER_FLAG_ARMED)
Definition at line 29 of file TimerDaemon.cc.
Referenced by TimerDaemon().
#define TIMER_FLAG_NONE 0
Definition at line 25 of file TimerDaemon.cc.
Referenced by FireTimer(), timer_create(), timer_delete(), and TimerDaemon().
#define TIMER_FLAG_SIGNAL 2
Definition at line 27 of file TimerDaemon.cc.
Referenced by FireTimer(), and timer_create().
#define TIMESPEC_ADD (dest, diff)
Value:
dest.tv_nsec+=diff.tv_nsec;                                 \
    dest.tv_sec+=diff.tv_sec;                                   \
    if(dest.tv_nsec>1000000000){                                \
        dest.tv_nsec-=1000000000;                               \
        dest.tv_sec++;                                          \
    }
Definition at line 108 of file TimerDaemon.cc.
Referenced by FireTimer(), and timer_settime().
#define TIMESPEC_LE (op1, op2)
Value:
((op1).tv_sec<(op2).tv_sec ||                               \
    ((op1).tv_sec==(op2).tv_sec&&(op1).tv_nsec<(op2).tv_nsec))
Definition at line 121 of file TimerDaemon.cc.
Referenced by FireTimer(), and TimerDaemon().
#define TIMESPEC_SUB (dest, op)
Value:
dest.tv_sec-=op.tv_sec;                                     \
    if(dest.tv_nsec>op.tv_nsec)dest.tv_nsec-=op.tv_nsec;        \
    else{dest.tv_nsec-=op.tv_nsec+1000000000;dest.tv_sec--;}
Definition at line 116 of file TimerDaemon.cc.
Referenced by timer_gettime().
Typedef Documentation
typedef struct _timer_event_t timer_event_t
Function Documentation
void FireTimer (timer_event_t * t, pid_t pid, timer_t timerid, struct timespec * now)
Definition at line 227 of file TimerDaemon.cc.
References DEBUGH, DEBUGL, _timer_event_t::flags, _timer_event_t::interval, lSendSignal(), _timer_event_t::overrun, _timer_event_t::signum, TIMER_FLAG_ARMED, TIMER_FLAG_NONE, TIMER_FLAG_SIGNAL, TIMESPEC_ADD, TIMESPEC_LE, and _timer_event_t::value.
Referenced by TimerDaemon().
int timer_create (clockid_t clockid, struct sigevent * sevp, timer_t * timerid)
Creates a new timer.
clockid is ignored, CLOCK_MONOTONIC is always used
Definition at line 43 of file TimerDaemon.cc.
References DEBUGL, _timer_event_t::flags, GetHook(), getpid(), HOOK_TIMER, MAX_TIMERS, _timer_event_t::overrun, SIGALRM, SIGEV_NONE, sigevent::sigev_notify, SIGEV_SIGNAL, sigevent::sigev_signo, sigevent::sigev_value, _timer_event_t::signum, sigval::sival_int, StartTimerDaemon(), TIMER_FLAG_ENABLED, TIMER_FLAG_NONE, TIMER_FLAG_SIGNAL, and _timer_event_t::value.
Referenced by timer_repeat(), and usleep().
int timer_delete (timer_t timerid)
Definition at line 125 of file TimerDaemon.cc.
References FIND_TIMER, and TIMER_FLAG_NONE.
Referenced by usleep().
int timer_getoverrun (timer_t timerid)
Definition at line 131 of file TimerDaemon.cc.
References FIND_TIMER.
int timer_gettime (timer_t timerid, struct itimerspec * curr_value)
Definition at line 182 of file TimerDaemon.cc.
References clock_gettime(), CLOCK_MONOTONIC, FIND_TIMER, and TIMESPEC_SUB.
Referenced by timer_settime().
int timer_repeat (void(*)(int, siginfo_t *, void *) handler, void * arg, long interval_sec, long interval_nsec)
Definition at line 195 of file TimerDaemon.cc.
References CLOCK_MONOTONIC, sigaction::sa_flags, sigaction::sa_mask, sigaction::sa_sigaction, SA_SIGINFO, sigaction(), SIGALRM, sigemptyset(), sigevent::sigev_notify, SIGEV_SIGNAL, sigevent::sigev_signo, sigevent::sigev_value, sigval::sival_ptr, timer_create(), and timer_settime().
Referenced by DumpStatsDaemon(), and ShutdownDaemon().
int timer_settime (timer_t timerid, int flags, const struct itimerspec * new_value, struct itimerspec * old_value)
Definition at line 137 of file TimerDaemon.cc.
References clock_gettime(), CLOCK_MONOTONIC, DEBUGL, FIND_TIMER, getpid(), TIMER_FLAG_ARMED, timer_gettime(), and TIMESPEC_ADD.
Referenced by timer_repeat(), and usleep().
void* TimerDaemon (void * arg)
Definition at line 265 of file TimerDaemon.cc.
References clock_gettime(), CLOCK_MONOTONIC, DEBUGH, FireTimer(), _timer_event_t::flags, HOOK_TIMER, _timer_event_t::interval, lmalloc, MailWrite(), MAX_PROCESSES, MAX_TIMERS, pid, RegisterHook(), set_no_gracefull_exit(), TIMER_FLAG_FIRE, TIMER_FLAG_NONE, TIMESPEC_LE, and Yield().
Referenced by StartTimerDaemon().