Starburst: include/trace.h File Reference
include/trace.h File Reference
Tracing of process execution and phases.
#include <sys/helix_config.h>
#include <sys/types.h>
#include <sys/kernel_types.h>
Data Structures
struct trace_t
Defines
#define TRACE_SCHEDULE_CMD(p, c) (0x00|(p)|((c)?0x40:0))
Enable tracing of TRACE_PHASE_MUTEX during pthread_mutex_lock().
#define TRACE_PHASE_CMD(p) (0x80|(p))
Phase change command, followed by relative timestamp in clock cycles.
#define TRACE_LOG_CMD 0xf9
String command, followed by relative timestamp and arbitrary length null-terminated string.
#define TRACE_START_CMD 0xfa
Start of trace command, followed by processor ID and speed in Hz.
#define TRACE_PROC_CMD 0xfb
Process change command, followed by pid, timeslice, relative timestamp and entry point.
#define TRACE_YIELD_CMD 0xfc
Yield command, followed by remaining timeslice.
#define TRACE_YIELD_FORCED_CMD 0xfd
Like Yield, but this yield was forced by the scheduler.
#define TRACE_SYNC_CMD 0xfe
Sync command, followed by absolute timestamp in usec (syncs previous command)
#define TRACE_END_CMD 0xff
End of trace command, followed by relative and absolute timestamp (syncs both)
#define TRACE_ABS_TIME_SIZE 4
Size of an absolute timestamp, in bytes.
#define TRACE_REL_TIME_SIZE 4
Size of a relative timestamp, in bytes.
#define TRACE_SYNC_SIZE (1+TRACE_ABS_TIME_SIZE)
Size of a sync command, in bytes.
#define TRACE_SCHEDULE_SIZE 1
Size of a schedule command, in bytes.
#define TRACE_PHASE_SIZE (1+TRACE_REL_TIME_SIZE)
Size of a phase change command, in bytes.
#define TRACE_START_SIZE 6
Size of a start command, in bytes.
#define TRACE_PROC_SIZE (1+1+4+TRACE_REL_TIME_SIZE+4)
Size of a process change command, in bytes.
#define TRACE_YIELD_SIZE (1+TRACE_REL_TIME_SIZE)
Size of a yield command, in bytes.
#define TRACE_END_SIZE (1+TRACE_REL_TIME_SIZE+TRACE_ABS_TIME_SIZE)
Size of an end command, in bytes.
#define TRACE_LOG_SIZE (1+TRACE_REL_TIME_SIZE)
Size of a log command, without log string in bytes.
#define TRACE_MAX_PHASES 120
#define TRACE_PHASE_RESERVED 16
#define TRACE_PHASE_INIT 0
#define TRACE_PHASE_RUNNING 1
#define TRACE_PHASE_SIGNAL 2
#define TRACE_PHASE_MUTEX 3
#define TRACE_PHASE_SHUTDOWN (TRACE_PHASE_RESERVED-1)
#define LINFS_TRACE_OUTPUT "/var/run/helix_mb%03u.trace"
Functions
trace_t * kTraceInit ()
Initializes the trace data structure.
int TracePhaseChange (int phase)
Signals a new phase in the application.
void kTraceProcChange (trace_t *trace, pid_t proc, timeslice_t timeslice, void *main)
Signals a change in the process information.
void kTraceYield (trace_t *trace, timeslice_t yielded)
bool kTraceSchedule (trace_t *trace, pid_t proc, bool continue_slice) __attribute__((section(".text.schedule")))
Put scheduling information in trace.
bool kTraceScheduleYield (trace_t *trace, timeslice_t yielded) __attribute__((section(".text.schedule")))
Inserts yield in trace.
void TraceLog (const char *msg,...) __attribute__((format(printf
void void kTraceClose (trace_t *trace)
Closes the trace.
int TraceRedir (const char *file=LINFS_TRACE_OUTPUT)
Flags the trace to dump to file instead of the terminal.
int TraceDump ()
Prints details how to get the trace.
void TraceDumpAll ()
Calls TraceDump() on all cores.
void TraceExitProc ()
Simple wrapper to call TracePhaseChange() at process termination.
Detailed Description
Tracing of process execution and phases.
Definition in file trace.h.
Define Documentation
#define LINFS_TRACE_OUTPUT "/var/run/helix_mb%03u.trace"
Definition at line 52 of file trace.h.
#define TRACE_ABS_TIME_SIZE 4
Size of an absolute timestamp, in bytes.
Definition at line 21 of file trace.h.
#define TRACE_END_CMD 0xff
End of trace command, followed by relative and absolute timestamp (syncs both)
Definition at line 19 of file trace.h.
Referenced by kTraceClose().
#define TRACE_END_SIZE (1+TRACE_REL_TIME_SIZE+TRACE_ABS_TIME_SIZE)
Size of an end command, in bytes.
Definition at line 29 of file trace.h.
Referenced by kTraceClose(), and kTraceInit().
#define TRACE_LOG_CMD 0xf9
String command, followed by relative timestamp and arbitrary length null-terminated string.
Definition at line 13 of file trace.h.
Referenced by TraceLog_().
#define TRACE_LOG_SIZE (1+TRACE_REL_TIME_SIZE)
Size of a log command, without log string in bytes.
Definition at line 30 of file trace.h.
Referenced by TraceLog_().
#define TRACE_MAX_PHASES 120
Definition at line 32 of file trace.h.
Referenced by TracePhaseChange().
#define TRACE_PHASE_CMD (p) (0x80|(p))
Phase change command, followed by relative timestamp in clock cycles.
Definition at line 12 of file trace.h.
Referenced by TracePhaseChange().
#define TRACE_PHASE_INIT 0
Definition at line 34 of file trace.h.
#define TRACE_PHASE_MUTEX 3
Definition at line 37 of file trace.h.
Referenced by pthread_mutex_lock().
#define TRACE_PHASE_RESERVED 16
Definition at line 33 of file trace.h.
#define TRACE_PHASE_RUNNING 1
Definition at line 35 of file trace.h.
Referenced by ProcessEntry().
#define TRACE_PHASE_SHUTDOWN (TRACE_PHASE_RESERVED-1)
Definition at line 38 of file trace.h.
Referenced by TraceExitProc().
#define TRACE_PHASE_SIGNAL 2
Definition at line 36 of file trace.h.
Referenced by SignalDispatcher().
#define TRACE_PHASE_SIZE (1+TRACE_REL_TIME_SIZE)
Size of a phase change command, in bytes.
Definition at line 25 of file trace.h.
Referenced by TracePhaseChange().
#define TRACE_PROC_CMD 0xfb
Process change command, followed by pid, timeslice, relative timestamp and entry point.
Definition at line 15 of file trace.h.
Referenced by kTraceProcChange().
#define TRACE_PROC_SIZE (1+1+4+TRACE_REL_TIME_SIZE+4)
Size of a process change command, in bytes.
Definition at line 27 of file trace.h.
Referenced by kTraceProcChange().
#define TRACE_REL_TIME_SIZE 4
Size of a relative timestamp, in bytes.
Definition at line 22 of file trace.h.
#define TRACE_SCHEDULE_CMD (p, c) (0x00|(p)|((c)?0x40:0))
Enable tracing of TRACE_PHASE_MUTEX during pthread_mutex_lock().
Usually makes trace significantly larger. Schedule to other process command
Definition at line 11 of file trace.h.
Referenced by kTraceSchedule().
#define TRACE_SCHEDULE_SIZE 1
Size of a schedule command, in bytes.
Definition at line 24 of file trace.h.
#define TRACE_START_CMD 0xfa
Start of trace command, followed by processor ID and speed in Hz.
Definition at line 14 of file trace.h.
Referenced by kTraceInit().
#define TRACE_START_SIZE 6
Size of a start command, in bytes.
Definition at line 26 of file trace.h.
Referenced by kTraceInit().
#define TRACE_SYNC_CMD 0xfe
Sync command, followed by absolute timestamp in usec (syncs previous command)
Definition at line 18 of file trace.h.
Referenced by kTraceSync().
#define TRACE_SYNC_SIZE (1+TRACE_ABS_TIME_SIZE)
Size of a sync command, in bytes.
Definition at line 23 of file trace.h.
Referenced by kTraceSync().
#define TRACE_YIELD_CMD 0xfc
Yield command, followed by remaining timeslice.
Definition at line 16 of file trace.h.
Referenced by kTraceYield().
#define TRACE_YIELD_FORCED_CMD 0xfd
Like Yield, but this yield was forced by the scheduler.
Definition at line 17 of file trace.h.
Referenced by kTraceScheduleYield().
#define TRACE_YIELD_SIZE (1+TRACE_REL_TIME_SIZE)
Size of a yield command, in bytes.
Definition at line 28 of file trace.h.
Referenced by kTraceScheduleYield(), and kTraceYield().
Function Documentation
void void kTraceClose (trace_t * trace)
Closes the trace.
Will be called automatically when the trace is full (out of memory).
Closing does not flush the cache, so only download the trace after TraceDump() has been called.
Parameters:
trace the trace data structure, as returned by kTraceInit()
Definition at line 402 of file trace.cc.
References lxchg(), TRACE_END_CMD, TRACE_END_SIZE, TraceAbsTime(), and TraceRelTime().
Referenced by kScheduleNext(), kScheduleProcess(), kTraceCommandSpace(), and TraceDump().
trace_t* kTraceInit ()
Initializes the trace data structure.
Memory is allocated on the heap (and also returned) and the address is RegisterHook()'ed.
Returns:
a pointer to the trace data structure on the heap
Definition at line 98 of file trace.cc.
References trace_t::current, trace_t::end, GetClockFreq(), GetProcID(), HOOK_TRACE, kTraceCommandSpace(), lcalloc, lfree, mc_entry_wou, mc_exit_wou, PRINT, RegisterHook(), trace_t::sync, trace_t::trace, TRACE_END_SIZE, TRACE_SIZE, TRACE_START_CMD, TRACE_START_SIZE, TRACE_TIME_TO_SYNC, and TraceRedir().
Referenced by kInitKernel().
void kTraceProcChange (trace_t * trace, pid_t proc, timeslice_t timeslice, void * main)
Signals a change in the process information.
Parameters:
trace the trace data structure, as returned by kTraceInit()
proc the process that changes
timeslice the new timeslice of the specified process, set to 0 to remove the process
main entry point of process
Definition at line 258 of file trace.cc.
References kTraceCommandSpace(), kTraceSync(), main, timeslice, TRACE_PROC_CMD, TRACE_PROC_SIZE, and TraceRelTime().
Referenced by kDestroyProcess(), and kSetProcessTimeslice().
bool kTraceSchedule (trace_t * trace, pid_t proc, bool continue_slice)
Put scheduling information in trace.
Should be called by the scheduler, assumes that it cannot be interrupted.
Parameters:
trace the trace data structure, as returned by kTraceInit()
proc the process that is scheduled to
continue_slice set to true when the timeslice is continued after a previous Yield() instead of set to full length
Returns:
false when the trace is full and should be closed (see kTraceClose())
Definition at line 304 of file trace.cc.
References trace_t::current, trace_t::end, likely, TRACE_SCHEDULE_CMD, and unlikely.
Referenced by kScheduleProcess().
bool kTraceScheduleYield (trace_t * trace, timeslice_t yielded)
Inserts yield in trace.
The result is similar to kTraceYield(), but no atomic operations are used.
This makes the function fast and feasible to be used by the scheduler.
Parameters:
trace the trace data structure
yielded time that has been yielded
Returns:
false when the trace is full and should be closed (see kTraceClose())
Definition at line 327 of file trace.cc.
References trace_t::current, trace_t::end, likely, TRACE_YIELD_FORCED_CMD, TRACE_YIELD_SIZE, and unlikely.
Referenced by kScheduleNext().
void kTraceYield (trace_t * trace, timeslice_t yielded)
Definition at line 283 of file trace.cc.
References kTraceCommandSpace(), kTraceSync(), TRACE_YIELD_CMD, and TRACE_YIELD_SIZE.
Referenced by kYield().
int TraceDump ()
Prints details how to get the trace.
Tracing is closed first, cache will be flushed.
If TraceRedir() is called before, the specified file will be created/truncated before the dump.
Returns:
0 on success, otherwise an errno
Definition at line 449 of file trace.cc.
References close(), creat(), trace_t::current, DAEMON_DEFAULT_STACK, DAEMON_DEFAULT_TIMESLICE, DEBUG, trace_t::dump_to_file, FlushDCache(), free(), GetHook(), GetOSState, getpid(), GetProcID(), HOOK_TRACE, kTraceClose(), lCreateProcess(), lDestroyProcess(), lStartProcess(), OS_SHUTDOWN, pid, PRINT, set_no_gracefull_exit(), trace_t::trace, TraceDump(), usleep(), and write().
Referenced by TraceDump(), and TraceDumpAll().
void TraceDumpAll ()
Calls TraceDump() on all cores.
Definition at line 544 of file trace.cc.
References dRemoteCall(), GetOSState, OS_SHUTDOWN, PRINT, sysconf(), and TraceDump().
Referenced by mainProc().
void TraceExitProc ()
Simple wrapper to call TracePhaseChange() at process termination.
Definition at line 556 of file trace.cc.
References TRACE_PHASE_SHUTDOWN, and TracePhaseChange().
Referenced by ProcessEntry().
void TraceLog (const char * msg, ...)
Referenced by mainProc().
int TracePhaseChange (int phase)
Signals a new phase in the application.
Parameters:
phase the new phase, for applications, only specify a number between TRACE_PHASE_RESERVED and TRACE_MAX_PHASES.
Returns:
Previous phase
Definition at line 210 of file trace.cc.
References DEBUG, GetHook(), GetProcLocal(), HOOK_TRACE, kTraceCommandSpace(), kTraceSync(), proc_local_t::last_phase, TRACE_MAX_PHASES, TRACE_PHASE_CMD, TRACE_PHASE_SIZE, and TraceRelTime().
Referenced by ProcessEntry(), pthread_mutex_lock(), SignalDispatcher(), and TraceExitProc().
int TraceRedir (const char * file)
Flags the trace to dump to file instead of the terminal.
Should be called before TraceDump() is called.
Parameters:
file a printf-formatted filename to dump the trace to, the first u in the name will be replaced by the processor ID, set to NULL to disable
Definition at line 430 of file trace.cc.
References trace_t::dump_to_file, GetHook(), and HOOK_TRACE.
Referenced by kTraceInit().