Starburst: util/trace.cc File Reference
util/trace.cc File Reference
Application
Tracing of process execution and phases.
#include <sys/helix_config.h>
#include <trace.h>
#include <malloc.h>
#include <sys/device.h>
#include <sys/time.h>
#include <sys/api.h>
#include <unistd.h>
#include <stdarg.h>
#include <sys/types.h>
#include <sys/stat.h>
#include <fcntl.h>
#include <mc.h>
Data Structures
union __attribute__
union __attribute__
union __attribute__
union __attribute__
union __attribute__
union __attribute__
union __attribute__
union __attribute__
union __attribute__
Defines
#define TRACE_SIZE 0x20000
#define TRACE_TIME_TO_SYNC 1000
#define PRINT(msg, a...) printf("Trace %d: " msg "\n",GetProcID(),##a)
#define DEBUG(...)
Functions
static char * kTraceCommandSpace (trace_t *trace, size_t size)
Allocates bytes in the trace stream.
static void kTraceCommand (trace_t *trace, char *cmd, size_t size) __attribute__((unused))
Allocates space and copies the trace command.
trace_t * kTraceInit ()
Initializes the trace data structure.
static void TraceRelTime (char *buf)
Puts the relative time in the buffer.
static void TraceAbsTime (char *buf)
Puts the absolute time in the buffer.
static void kTraceSync (trace_t *trace, bool force)
Adds a synchronization command to the trace.
int TracePhaseChange (int phase)
Signals a new phase in the application.
void kTraceProcChange (trace_t *trace, pid_t proc, timeslice_t timeslice, void *main)
Signals a change in the process information.
void kTraceYield (trace_t *trace, timeslice_t yielded)
bool kTraceSchedule (trace_t *trace, pid_t proc, bool continue_slice)
Put scheduling information in trace.
bool kTraceScheduleYield (trace_t *trace, timeslice_t yielded)
Inserts yield in trace.
static void TraceLog_ (const char *msg)
Writes an arbitrary string to the trace.
void TraceLog (const char *msg,...)
Writes an arbitrary formatted string to the trace.
void kTraceClose (trace_t *trace)
Closes the trace.
int TraceRedir (const char *file)
Flags the trace to dump to file instead of the terminal.
int TraceDump ()
Prints details how to get the trace.
void TraceDumpAll ()
Calls TraceDump() on all cores.
void TraceExitProc ()
Simple wrapper to call TracePhaseChange() at process termination.
Variables
trace_t *traces[NUM_PROCESSORS] ATTR_DATA_ALIGNED
char cmd
char core
unsigned int freq
unsigned int time
pid_t pid
timeslice_t timeslice
void * main
char log []
unsigned int rel_time
unsigned int abs_time
Detailed Description
Tracing of process execution and phases.
An application can call TracePhaseChange() to indicate a different phase. All other kTrace*() calls should not be called from within an application. Based on the recorded trace stream, execution times can be calculated.
The size of a trace of a single processor is determined by TRACE_SIZE, which is the number of bytes that is malloc()ed on the processor heap. Traces can be converted to VCD by using the trace2vcd tool.
Definition in file trace.cc.
Define Documentation
#define DEBUG (...)
Definition at line 37 of file trace.cc.
Referenced by TraceAbsTime(), TraceDump(), and TracePhaseChange().
#define PRINT (msg, a...) printf("Trace %d: " msg "\n",GetProcID(),##a)
Definition at line 32 of file trace.cc.
Referenced by kTraceInit(), TraceDump(), and TraceDumpAll().
#define TRACE_SIZE 0x20000
Definition at line 29 of file trace.cc.
Referenced by kTraceInit().
#define TRACE_TIME_TO_SYNC 1000
Definition at line 30 of file trace.cc.
Referenced by kTraceInit(), and kTraceSync().
Function Documentation
void kTraceClose (trace_t * trace)
Closes the trace.
Will be called automatically when the trace is full (out of memory).
Closing does not flush the cache, so only download the trace after TraceDump() has been called.
Parameters:
trace the trace data structure, as returned by kTraceInit()
Definition at line 402 of file trace.cc.
References lxchg(), TRACE_END_CMD, TRACE_END_SIZE, TraceAbsTime(), and TraceRelTime().
Referenced by kScheduleNext(), kScheduleProcess(), kTraceCommandSpace(), and TraceDump().
static void kTraceCommand (trace_t * trace, char * cmd, size_t size) [static]
Allocates space and copies the trace command.
Calls kTraceCommandSpace() and copies the buffer.
Parameters:
trace the trace data structure, as returned by kTraceInit()
cmd the command to write
size the number of bytes in cmd
Definition at line 77 of file trace.cc.
References kTraceCommandSpace().
static char* kTraceCommandSpace (trace_t * trace, size_t size) [static]
Allocates bytes in the trace stream.
Thread safe for local processes.
When out of memory, kTraceClose() is called automatically.
Parameters:
trace the trace data structure, as returned by kTraceInit()
size the number of bytes to allocate
Returns:
a pointer to the buffer, or NULL when there is no space anymore
Definition at line 50 of file trace.cc.
References trace_t::current, trace_t::end, and kTraceClose().
Referenced by kTraceCommand(), kTraceInit(), kTraceProcChange(), kTraceSync(), kTraceYield(), TraceLog_(), and TracePhaseChange().
trace_t* kTraceInit ()
Initializes the trace data structure.
Memory is allocated on the heap (and also returned) and the address is RegisterHook()'ed.
Returns:
a pointer to the trace data structure on the heap
Definition at line 98 of file trace.cc.
References trace_t::current, trace_t::end, GetClockFreq(), GetProcID(), HOOK_TRACE, kTraceCommandSpace(), lcalloc, lfree, mc_entry_wou, mc_exit_wou, PRINT, RegisterHook(), trace_t::sync, trace_t::trace, TRACE_END_SIZE, TRACE_SIZE, TRACE_START_CMD, TRACE_START_SIZE, TRACE_TIME_TO_SYNC, and TraceRedir().
Referenced by kInitKernel().
void kTraceProcChange (trace_t * trace, pid_t proc, timeslice_t timeslice, void * main)
Signals a change in the process information.
Parameters:
trace the trace data structure, as returned by kTraceInit()
proc the process that changes
timeslice the new timeslice of the specified process, set to 0 to remove the process
main entry point of process
Definition at line 258 of file trace.cc.
References kTraceCommandSpace(), kTraceSync(), main, timeslice, TRACE_PROC_CMD, TRACE_PROC_SIZE, and TraceRelTime().
Referenced by kDestroyProcess(), and kSetProcessTimeslice().
bool kTraceSchedule (trace_t * trace, pid_t proc, bool continue_slice)
Put scheduling information in trace.
Should be called by the scheduler, assumes that it cannot be interrupted.
Parameters:
trace the trace data structure, as returned by kTraceInit()
proc the process that is scheduled to
continue_slice set to true when the timeslice is continued after a previous Yield() instead of set to full length
Returns:
false when the trace is full and should be closed (see kTraceClose())
Definition at line 304 of file trace.cc.
References trace_t::current, trace_t::end, likely, TRACE_SCHEDULE_CMD, and unlikely.
Referenced by kScheduleProcess().
bool kTraceScheduleYield (trace_t * trace, timeslice_t yielded)
Inserts yield in trace.
The result is similar to kTraceYield(), but no atomic operations are used.
This makes the function fast and feasible to be used by the scheduler.
Parameters:
trace the trace data structure
yielded time that has been yielded
Returns:
false when the trace is full and should be closed (see kTraceClose())
Definition at line 327 of file trace.cc.
References trace_t::current, trace_t::end, likely, TRACE_YIELD_FORCED_CMD, TRACE_YIELD_SIZE, and unlikely.
Referenced by kScheduleNext().
static void kTraceSync (trace_t * trace, bool force) [static]
Adds a synchronization command to the trace.
This synchronizes the last command to the actual time.
Parameters:
trace the trace data structure, as returned by kTraceInit()
force force syncing immediately
Definition at line 178 of file trace.cc.
References ASSERT, kTraceCommandSpace(), ladec, TRACE_SYNC_CMD, TRACE_SYNC_SIZE, TRACE_TIME_TO_SYNC, and TraceAbsTime().
Referenced by kTraceProcChange(), kTraceYield(), and TracePhaseChange().
void kTraceYield (trace_t * trace, timeslice_t yielded)
Definition at line 283 of file trace.cc.
References kTraceCommandSpace(), kTraceSync(), TRACE_YIELD_CMD, and TRACE_YIELD_SIZE.
Referenced by kYield().
static void TraceAbsTime (char * buf) [static]
Puts the absolute time in the buffer.
Parameters:
buf the buffer to put the time in, cannot be NULL
Definition at line 154 of file trace.cc.
References ASSERT, DEBUG, and gettimeofday().
Referenced by kTraceClose(), and kTraceSync().
int TraceDump ()
Prints details how to get the trace.
Tracing is closed first, cache will be flushed.
If TraceRedir() is called before, the specified file will be created/truncated before the dump.
Returns:
0 on success, otherwise an errno
Definition at line 449 of file trace.cc.
References close(), creat(), trace_t::current, DAEMON_DEFAULT_STACK, DAEMON_DEFAULT_TIMESLICE, DEBUG, trace_t::dump_to_file, FlushDCache(), free(), GetHook(), GetOSState, getpid(), GetProcID(), HOOK_TRACE, kTraceClose(), lCreateProcess(), lDestroyProcess(), lStartProcess(), OS_SHUTDOWN, pid, PRINT, set_no_gracefull_exit(), trace_t::trace, TraceDump(), usleep(), and write().
Referenced by TraceDump(), and TraceDumpAll().
void TraceDumpAll ()
Calls TraceDump() on all cores.
Definition at line 544 of file trace.cc.
References dRemoteCall(), GetOSState, OS_SHUTDOWN, PRINT, sysconf(), and TraceDump().
Referenced by mainProc().
void TraceExitProc ()
Simple wrapper to call TracePhaseChange() at process termination.
Definition at line 556 of file trace.cc.
References TRACE_PHASE_SHUTDOWN, and TracePhaseChange().
Referenced by ProcessEntry().
void TraceLog (const char * msg, ...)
Writes an arbitrary formatted string to the trace.
Parameters:
msg a printf-like formatted string
Definition at line 374 of file trace.cc.
References free(), and TraceLog_().
static void TraceLog_ (const char * msg) [static]
Writes an arbitrary string to the trace.
Parameters:
msg the null-terminated string to log, cannot be NULL
Definition at line 357 of file trace.cc.
References GetHook(), HOOK_TRACE, kTraceCommandSpace(), TRACE_LOG_CMD, TRACE_LOG_SIZE, and TraceRelTime().
Referenced by TraceLog().
int TracePhaseChange (int phase)
Signals a new phase in the application.
Parameters:
phase the new phase, for applications, only specify a number between TRACE_PHASE_RESERVED and TRACE_MAX_PHASES.
Returns:
Previous phase
Definition at line 210 of file trace.cc.
References DEBUG, GetHook(), GetProcLocal(), HOOK_TRACE, kTraceCommandSpace(), kTraceSync(), proc_local_t::last_phase, TRACE_MAX_PHASES, TRACE_PHASE_CMD, TRACE_PHASE_SIZE, and TraceRelTime().
Referenced by ProcessEntry(), pthread_mutex_lock(), SignalDispatcher(), and TraceExitProc().
int TraceRedir (const char * file)
Flags the trace to dump to file instead of the terminal.
Should be called before TraceDump() is called.
Parameters:
file a printf-formatted filename to dump the trace to, the first u in the name will be replaced by the processor ID, set to NULL to disable
Definition at line 430 of file trace.cc.
References trace_t::dump_to_file, GetHook(), and HOOK_TRACE.
Referenced by kTraceInit().
static void TraceRelTime (char * buf) [static]
Puts the relative time in the buffer.
Parameters:
buf the buffer to put the time in, cannot be NULL
Definition at line 139 of file trace.cc.
References ASSERT, and GetRemainingTimeslice().
Referenced by kTraceClose(), kTraceProcChange(), TraceLog_(), and TracePhaseChange().
Variable Documentation
unsigned int abs_time
Definition at line 396 of file trace.cc.
trace_t* traces [NUM_PROCESSORS] ATTR_DATA_ALIGNED
Definition at line 40 of file trace.cc.
char cmd
Definition at line 91 of file trace.cc.
Referenced by adc_init(), bitshark_cmd_get_iqbal(), bitshark_cmd_read_adclk(), bitshark_cmd_read_chanbw(), dAllocChannels(), dAllocFifoEndPoint(), dAllocMail(), dAssignChannel(), dAtomicAdd(), dAtomicCAS(), dAtomicXCHG(), dCreateProcess(), dDestroyFifoEndPoint(), dDestroyMail(), dDestroyProcess(), DefaultTaskDaemon(), dGetProcessFlags(), dGetProcessState(), dLockAsk(), dLockGiveup(), dLockRegister(), dLockRequest(), dRemoteCall(), dSCalloc(), dSendSignal(), dSetChannelLabel(), dSetProcessFlags(), dSetProcessTimeslice(), dSFree(), dSMalloc(), dSRealloc(), dStartProcess(), dSyncEventHit(), dWaitProcess(), ReserveRemoteSlot(), spi_selftest(), and StatsCount().
char core
Definition at line 92 of file trace.cc.
Referenced by DumpStatsDaemon(), DumpStatsNow(), CFifo< T, r >::init(), ring_get_accelerator(), ring_get_cpu(), ring_get_fsl(), and ring_printall().
unsigned int freq
Definition at line 93 of file trace.cc.
Referenced by times().
char log[]
Definition at line 353 of file trace.cc.
void* main
Definition at line 253 of file trace.cc.
Referenced by CreateProcess(), dCreateProcess(), kCreateProcess(), kTraceProcChange(), mainProc(), ProcessEntry(), and StartDumpStatsDaemon().
pid_t pid
Definition at line 250 of file trace.cc.
Referenced by dAllocChannels(), dAssignChannel(), dDestroyProcess(), DefaultTaskDaemon(), dGetProcessFlags(), dGetProcessState(), dSendSignal(), dSetChannelLabel(), dSetProcessFlags(), dSetProcessTimeslice(), dStartProcess(), dSyncEventHit(), dWaitProcess(), getupid(), syncevent_t< N >::hit(), kAllocChannels(), kAssignChannel(), kCreateProcess(), kDestroyProcess(), kGetChannelCount(), kGetProcessFlags(), kGetProcessState(), kGetProcessStats(), kJoinProcess(), kSendSignal(), kSetChannelLabel(), kSetProcessFlags(), kSetProcessTimeslice(), kStartProcess(), kStartTaskDaemon(), kSyncEventHit(), MallocDaemonHandler(), map_dump(), map_start_task(), ProcessRequest(), pthread_create(), pthread_detach(), pthread_join(), pthread_kill(), se_create_(), se_create_a(), ShutdownDaemon(), WorkQueue< T, W >::StartDispatcher(), StartMallocDaemon(), StartShutdownDaemon(), WorkQueue< T, W >::StartSlaves(), StartTimerDaemon(), TimerDaemon(), TraceDump(), and WaitProcessDaemon().
unsigned int rel_time
Definition at line 395 of file trace.cc.
unsigned int time
Definition at line 171 of file trace.cc.
Referenced by linfs_register().
timeslice_t timeslice
Definition at line 251 of file trace.cc.
Referenced by kScheduleProcess(), and kTraceProcChange().