Starburst: dvi_frame Union Reference
dvi_frame Union Reference
#include <io.h>
Public Member Functions
dvi_pixel * get (int x, int y)
void set (int x, int y, uint32_t c)
Data Fields
char raw [0x200000]
struct {
dvi_line line [480]
dvi_pixel frame_padding [32]
};
Detailed Description
Definition at line 240 of file io.h.
Member Function Documentation
dvi_pixel* dvi_frame::get (int x, int y) [inline]
Definition at line 246 of file io.h.
Referenced by fillpoly(), and fillrect().
void dvi_frame::set (int x, int y, uint32_t c) [inline]
Definition at line 247 of file io.h.
Referenced by drawline(), and fillpoly().
Field Documentation
struct { ... }
dvi_pixel dvi_frame::frame_padding[32]
Definition at line 244 of file io.h.
dvi_line dvi_frame::line[480]
Definition at line 243 of file io.h.
char dvi_frame::raw[0x200000]
Definition at line 241 of file io.h.
The documentation for this union was generated from the following file:
include/sys/io.h