Starburst: include/unistd.h File Reference
include/unistd.h File Reference
#include <sys/unistd.h>
#include <sys/kernel_types.h>
Defines
#define _POSIX_THREAD_CPUTIME _SC_THREAD_CPUTIME
#define lstat(a...) stat(a)
Functions
int truncate (const char *path, off_t length)
int ftruncate (int fd, off_t length)
int usleep (useconds_t useconds) _NO_THROW
Suspends execution of the process for some time.
Define Documentation
#define _POSIX_THREAD_CPUTIME _SC_THREAD_CPUTIME
Definition at line 10 of file unistd.h.
#define lstat (a...) stat(a)
Definition at line 20 of file unistd.h.
Function Documentation
int ftruncate (int fd, off_t length)
Definition at line 38 of file file.cc.
int truncate (const char * path, off_t length)
Definition at line 33 of file file.cc.
int usleep (useconds_t useconds)
Suspends execution of the process for some time.
The process Yield()s until the current time has passed the specified time.
Parameters:
useconds microseconds to sleep
Returns:
0 on success, otherwise -1 and errno is set
Definition at line 374 of file newlibstubs.cc.
References CLOCK_MONOTONIC, gettimeofday(), lGetProcessState(), likely, sigaddset(), SIGCONT, sigemptyset(), sigevent::sigev_notify, SIGEV_SIGNAL, sigevent::sigev_signo, Suspend(), timecmp(), timer_create(), timer_delete(), timer_settime(), and Yield().
Referenced by adc_init(), bitshark_cmd_write(), ForceShutdown(), ProfilerDaemon(), ShutdownDaemon(), sleep(), spi_transfer(), and TraceDump().