Starburst: kernel/wrap_exit.cc File Reference
kernel/wrap_exit.cc File Reference
#include <sys/helix_config.h>
#include <sys/api.h>
Functions
void exit_from_sigh (int status, proc_context_t *context, char *trig) __attribute__((noreturn))
void __real_exit (int status) __attribute__((noreturn))
void __wrap_exit (int status)
Function Documentation
void __real_exit (int status)
Referenced by __wrap_exit().
void __wrap_exit (int status)
Definition at line 8 of file wrap_exit.cc.
References __real_exit(), _proc_table_t::context, current_proc, exit_from_sigh(), lGetProcessState(), _proc_table_t::sig_trig_handling, and SIG_TRIG_HANDLING_ABRT.
void exit_from_sigh (int status, proc_context_t * context, char * trig)
Referenced by __wrap_exit().